import {registerHooks} from "node:module";
registerHooks({resolve(s,c,next){if(s==="@platform/ui")return {url:new URL("../../../ui/src/components/date.ts",import.meta.url).href,shortCircuit:true};try{return next(s,c)}catch(e){if(s.startsWith(".")&&!s.endsWith(".ts"))return next(`${s}.ts`,c);throw e;}}});
import assert from "node:assert/strict";
import test from "node:test";
const {createObservationStatisticsReader}=await import("./observation-reader.ts");
const request={object:"sample.observation",query:{domain:[["status","=","ready"]],search:"current",sort:["name"],offset:500,limit:2},window:{timeField:"at",field:"value",rows:1000,threshold:"11.5"}};
const result=()=>({columns:[],rows:[],window:{timeField:"at",field:"value",requestedRows:1000,threshold:"11.5",generation:"7",total:1500,timed:1500,missingTime:0,count:1000,valid:998,missing:2,above:250,min:0,mean:20,max:40,first:{id:"Z",revision:2,time:"2026-10-03T00:00:00.000000002Z"},last:{id:"A",revision:1,time:"2026-10-03T00:00:00.000000001Z"}}});
function fixture(){let active=true;const calls=[],source={scope:"tenant/member/definition",revision:1,entity:()=>({type:"sample.observation",fields:[{name:"at",type:"datetime"},{name:"value",type:"decimal"}]}),aggregate:async(...args)=>{calls.push(args);return result();}};const service=createObservationStatisticsReader(source,()=>active);return{source,calls,read:service.read,scope:service.scope,retire:()=>active=false};}
test("original complete predicates survive record paging; the explicit window alone selects latest N records",async()=>{const f=fixture(),r=await f.read(request);assert.deepEqual(f.calls[0],[request.object,{domain:request.query.domain,search:"current",set:undefined,archived:undefined,traversal:undefined,window:request.window}]);assert.deepEqual(r.statistics,{scope:r.scope,signal:"value",threshold:11.5,windowRows:1000,count:1000,valid:998,above:250,min:0,mean:20,max:40});assert.notEqual(r.scope,f.source.scope);assert.equal(r.scope,f.scope(request));assert.equal(r.window.first.id,"Z");});
test("count/field/threshold/edge tampering and ordinary aggregate answers cannot become window statistics",async()=>{for(const change of [r=>r.window.field="hidden",r=>r.window.threshold="12",r=>r.window.count=500,r=>r.window.valid=1001,r=>r.window.mean=null,r=>r.window.generation="18446744073709551616",r=>r.window.last.time="2026-10-03T00:00:00.000000003Z",r=>r.window.first.revision=-1,r=>r.rows=[{count:1000}],r=>delete r.window]){const f=fixture();f.source.aggregate=async()=>{const r=result();change(r);return r;};await assert.rejects(()=>f.read(request),/invalid/);}});
test("new parameters, retired views and changed member/data revisions discard old success or refusal",async()=>{for(const change of [f=>f.retire(),f=>f.source.scope="another-member",f=>f.source.revision++]){const f=fixture();let release;f.source.aggregate=()=>new Promise(r=>release=r);const pending=f.read(request);change(f);release(result());assert.equal(await pending,undefined);}const f=fixture();let release;f.source.aggregate=()=>new Promise(r=>release=r);const first=f.read(request),later={...request,window:{...request.window,threshold:"12"}};f.source.aggregate=async()=>{const r=result();r.window.threshold="12";return r;};const next=await f.read(later);release(result());assert.equal(await first,undefined);assert.equal(next.statistics.threshold,12);});
test("missing bindings and HTTP refusals never fall back to ordinary aggregates or downloaded records",async()=>{const f=fixture();f.source.aggregate=async()=>{f.calls.push("original");throw Error("HTTP 403");};await assert.rejects(()=>f.read(request),/403/);assert.deepEqual(f.calls,["original"]);f.source.entity=()=>({fields:[{name:"at",type:"datetime"}]});await assert.rejects(()=>f.read(request),/bindings/);assert.equal(f.calls.length,1);});
test("read-only seed revision zero and empty windows are preserved; late refusals end with their retired lease",async()=>{const f=fixture();f.source.aggregate=async()=>{const r=result();r.window.first.revision=0;return r;};assert.equal((await f.read(request)).window.first.revision,0);f.source.aggregate=async()=>({columns:[],rows:[],window:{...request.window,timeField:"at",field:"value",requestedRows:1000,generation:"0",total:0,timed:0,missingTime:0,count:0,valid:0,missing:0,above:0}});const empty=await f.read(request);assert.equal(empty.statistics.count,0);assert.equal(empty.statistics.mean,undefined);let refuse;f.source.aggregate=()=>new Promise((_resolve,reject)=>refuse=reject);const pending=f.read(request);f.retire();refuse(Error("Late HTTP 403"));assert.equal(await pending,undefined);});
