import {Button} from "../primitives/button";
import {Input} from "../primitives/input";
import {t} from "../i18n";
import {timestampParts,validTimestampOffset} from "./date";

export function DateTimeInput({value,offset,label,title,disabled,onChange}:{value:string;offset:string;label?:string;title:string;disabled?:boolean;onChange:(value:string)=>void}){
 const caption=label??"",name=caption.trim()?caption:title,parts=timestampParts(value),invalid=value!==""&&!parts;
 const write=(local:string,fraction:string,zone:string)=>{if(!disabled)onChange(local?`${local.length===16?local+":00":local}${fraction?"."+fraction:""}${zone}`:"");};
 return <div className="grid min-w-0 gap-2"><label className="grid min-w-0 gap-1 text-xs">{caption&&<span className="break-words">{caption}</span>}<Input aria-label={name} type="datetime-local" step="1" min="0001-01-01T00:00:00" max="9999-12-31T23:59:59" value={parts?.local??""} disabled={disabled||!validTimestampOffset(offset)} aria-invalid={invalid} onChange={e=>write(e.target.value,parts?.fraction??"",parts?.offset??offset)}/></label><label className="grid gap-1 text-xs">{t("UTC offset")}<Input aria-label={t("{label} UTC offset",{label:name})} maxLength={6} value={parts?.offset??offset} disabled={disabled||!parts} onChange={e=>{if(parts)write(parts.local,parts.fraction,e.target.value);}}/></label><label className="grid gap-1 text-xs">{t("Fractional seconds")}<Input aria-label={t("{label} fractional seconds",{label:name})} inputMode="numeric" maxLength={9} value={parts?.fraction??""} disabled={disabled||!parts} onChange={e=>{if(parts)write(parts.local,e.target.value,parts.offset);}}/></label>{invalid&&<><label className="grid gap-1 text-xs">{t("Invalid datetime draft")}<Input aria-label={t("{label} datetime draft",{label:name})} value={value} disabled={disabled} aria-invalid onChange={e=>{if(!disabled)onChange(e.target.value);}}/></label><p role="alert" className="break-words text-xs text-danger">{t("Invalid datetime value. Use a real date and time with seconds and Z or a UTC offset; the original draft is retained.")}</p></>}<p className="text-xs text-muted">{t("Date and time use the displayed UTC offset, independently of your browser timezone.")}</p><Button size="sm" variant="ghost" disabled={disabled||value===""} className="justify-self-start" onClick={()=>{if(!disabled)onChange("");}}>{t("Clear datetime")}</Button></div>;
}
