import {useId,useRef,useState} from "react";
import {Button} from "../primitives/button";
import {Input} from "../primitives/input";
import {t} from "../i18n";
import {validCivilDate} from "./date";

const civil=(date:Date)=>`${String(date.getUTCFullYear()).padStart(4,"0")}-${String(date.getUTCMonth()+1).padStart(2,"0")}-${String(date.getUTCDate()).padStart(2,"0")}`;
const day=(value:string)=>new Date(`${value}T00:00:00Z`);
const shift=(value:string,days:number)=>{const date=day(value);date.setUTCDate(date.getUTCDate()+days);return civil(date);};

/** Two declared civil-date fields, one calendar. Original text stays repairable. */
export function DateRangeInput({id,start,end,startLabel,endLabel,inclusive=false,disabled,invalid,describedBy,onChange}:{id?:string;start:string;end:string;startLabel:string;endLabel:string;inclusive?:boolean;disabled?:boolean;invalid?:boolean;describedBy?:string;onChange:(start:string,end:string)=>void}){
 const unique=useId(),root=id??unique,trigger=useRef<HTMLSpanElement>(null),calendar=useRef<HTMLDivElement>(null);
 const [open,setOpen]=useState(false),[month,setMonth]=useState(()=>validCivilDate(start)?start.slice(0,7):civil(new Date()).slice(0,7)),[anchor,setAnchor]=useState<string>(),[hover,setHover]=useState<string>();
 const drag=useRef<string|undefined>(undefined),moved=useRef(false),skipClick=useRef(false);
 const finish=(first:string,last:string)=>{onChange(first<last?first:last,first<last?last:first);setAnchor(undefined);setHover(undefined);setOpen(false);trigger.current?.querySelector<HTMLButtonElement>("button")?.focus();};
 const choose=(value:string)=>{if(anchor)finish(anchor,value);else{setAnchor(value);setHover(undefined);onChange(value,"");}};
 const navigate=(delta:number)=>{const date=day(`${month}-01`);date.setUTCMonth(date.getUTCMonth()+delta);if(date.getUTCFullYear()>0&&date.getUTCFullYear()<10000)setMonth(civil(date).slice(0,7));};
 const first=drag.current??anchor??start,last=drag.current?hover??drag.current:anchor?hover??anchor:end,lo=first<last?first:last,hi=first<last?last:first;
 const count=validCivilDate(start)&&validCivilDate(end)&&end>=start?Math.round((day(end).getTime()-day(start).getTime())/86400000)+(inclusive?1:0):undefined;
 return <div className="relative grid gap-2">
  <span ref={trigger}><Button id={id} disabled={disabled} aria-expanded={open} aria-controls={`${root}-calendar`} aria-invalid={invalid} aria-describedby={describedBy} className="h-auto min-h-7 w-full justify-start whitespace-normal text-left" onClick={()=>{drag.current=undefined;skipClick.current=false;setOpen(!open);setAnchor(undefined);setHover(undefined);if(validCivilDate(start))setMonth(start.slice(0,7));}}>{startLabel}: {start||"—"} → {endLabel}: {end||"—"}</Button></span>
  {count!==undefined&&<p className="text-xs text-muted">{inclusive?(count===1?t("{count} day",{count}):t("{count} days",{count})):(count===1?t("{count} night",{count}):t("{count} nights",{count}))}</p>}
  {open&&<div ref={calendar} id={`${root}-calendar`} role="group" aria-label={t("Choose a date range")} className="z-20 grid gap-2 rounded-md border border-border bg-surface p-3 shadow-lg" onPointerLeave={()=>{drag.current=undefined;moved.current=false;setHover(undefined);}} onPointerCancel={()=>{drag.current=undefined;moved.current=false;setHover(undefined);}} onKeyDown={event=>{if(event.key==="Escape"){setOpen(false);trigger.current?.querySelector<HTMLButtonElement>("button")?.focus();}const target=event.target as HTMLElement,value=target.dataset.date,delta=({ArrowLeft:-1,ArrowRight:1,ArrowUp:-7,ArrowDown:7} as Record<string,number>)[event.key];if(value&&delta){event.preventDefault();const next=shift(value,delta);if(!validCivilDate(next))return;const button=calendar.current?.querySelector<HTMLButtonElement>(`[data-date="${next}"]`);if(button)button.focus();else{setMonth(next.slice(0,7));requestAnimationFrame(()=>calendar.current?.querySelector<HTMLButtonElement>(`[data-date="${next}"]`)?.focus());}}}}>
   <div className="flex justify-between"><Button size="sm" aria-label={t("Previous month")} onClick={()=>navigate(-1)}>‹</Button><span className="text-xs">{anchor?t("Choose the end date"):t("Choose the start date")}</span><Button size="sm" aria-label={t("Next month")} onClick={()=>navigate(1)}>›</Button></div>
   <div className="grid gap-4 sm:grid-cols-2">{[0,1].map(offset=>{const date=day(`${month}-01`);date.setUTCMonth(date.getUTCMonth()+offset);if(date.getUTCFullYear()>9999)return null;const base=civil(date).slice(0,7),lead=(date.getUTCDay()+6)%7;date.setUTCMonth(date.getUTCMonth()+1);date.setUTCDate(0);const days=date.getUTCDate();return <div key={base} className={offset?"hidden sm:block":""}><p className="mb-2 text-center text-sm">{base}</p><div className="grid grid-cols-7 gap-1">{["Mon","Tue","Wed","Thu","Fri","Sat","Sun"].map(label=><span key={label} className="text-center text-[10px] text-muted">{t(label)}</span>)}{Array.from({length:lead},(_,i)=><span key={`empty-${i}`}/>)}{Array.from({length:days},(_,i)=>{const value=`${base}-${String(i+1).padStart(2,"0")}`,selected=!!first&&!!last&&value>=lo&&value<=hi;return <button key={value} type="button" data-date={value} aria-label={value} aria-pressed={selected} className={`h-8 rounded text-xs hover:bg-muted/30 focus-visible:outline focus-visible:outline-2 focus-visible:outline-primary ${value===first||value===last?"bg-primary text-white":selected?"bg-primary/15":""}`} onPointerDown={event=>{if(event.button!==0)return;skipClick.current=false;drag.current=value;moved.current=false;}} onPointerEnter={()=>{setHover(value);if(drag.current&&drag.current!==value)moved.current=true;}} onFocus={()=>setHover(value)} onPointerUp={()=>{if(drag.current&&moved.current){skipClick.current=true;finish(drag.current,value);}drag.current=undefined;}} onClick={event=>{if(skipClick.current&&event.detail>0){skipClick.current=false;return;}skipClick.current=false;choose(value);}}>{i+1}</button>;})}</div></div>;})}</div>
   <div className="grid gap-2 sm:grid-cols-2"><label className="grid gap-1 text-xs">{startLabel}<Input type="text" placeholder="YYYY-MM-DD" value={start} aria-invalid={!!start&&!validCivilDate(start)} onChange={e=>onChange(e.target.value,end)}/></label><label className="grid gap-1 text-xs">{endLabel}<Input type="text" placeholder="YYYY-MM-DD" value={end} aria-invalid={!!end&&!validCivilDate(end)} onChange={e=>onChange(start,e.target.value)}/></label></div>
   <div className="flex justify-end gap-2"><Button size="sm" onClick={()=>{onChange("","");setAnchor(undefined);setHover(undefined);}}>{t("Clear dates")}</Button><Button size="sm" onClick={()=>{setOpen(false);trigger.current?.querySelector<HTMLButtonElement>("button")?.focus();}}>{t("Close")}</Button></div>
  </div>}
 </div>;
}
