import {cleanup,fireEvent,render,screen} from "@testing-library/react";
import {afterEach,expect,test} from "vitest";
import type {Api} from "@platform/kernel";
import {Histogram} from "./Histogram";
import {validHistogram} from "./histogram-data";
afterEach(cleanup);
const data=():Api.HistogramResult=>({field:"value",requestedBins:3,valid:4,missing:1,minimum:"0",maximum:"1",buckets:[{lower:"0",upper:"1/3",upperInclusive:false,count:1},{lower:"1/3",upper:"2/3",upperInclusive:false,count:1},{lower:"2/3",upper:"1",upperInclusive:true,count:2}]});
test("histogram exposes exact intervals, keyboard feedback, missing values and honest empty and constant states",()=>{const {rerender}=render(<Histogram label="Values" value={data()}/>);expect(screen.getAllByRole("listitem")).toHaveLength(3);expect(screen.getByText("Missing values excluded: 1")).toBeTruthy();fireEvent.focus(screen.getAllByRole("listitem")[0]!);expect(screen.getByRole("status").textContent).toBe("0 ≤ x < 1/3: 1");expect(screen.queryByRole("button")).toBeNull();rerender(<Histogram label="Values" value={{...data(),valid:0,minimum:"",maximum:"",buckets:[]}}/>);expect(screen.getByRole("status").textContent).toContain("No numeric values");rerender(<Histogram label="Values" value={{...data(),valid:4,minimum:"7",maximum:"7",buckets:[{lower:"7",upper:"7",upperInclusive:true,count:4}]}}/>);expect(screen.getAllByRole("listitem")).toHaveLength(1);expect(screen.getByText("Constant values share one closed interval.")).toBeTruthy();});
test("histogram rejects partial, mismatched, unsafe or discontinuous replies without recomputing bins",()=>{expect(validHistogram(data(),"value",3)).toBe(true);expect(validHistogram(data(),"other",3)).toBe(false);expect(validHistogram(data(),"value",4)).toBe(false);for(const change of [d=>d.requestedBins=65,d=>d.buckets.pop(),d=>d.valid=5,d=>d.missing=-1,d=>d.buckets[0]!.count=Number.MAX_SAFE_INTEGER+1,d=>d.buckets[0]!.upperInclusive=true,d=>d.buckets[1]!.lower="1/4",d=>d.buckets[0]!.lower="1/0",d=>d.buckets[0]!.upper="NaN",d=>{d.buckets[0]!.upper="1/4";d.buckets[1]!.lower="1/4"}] as ((d:Api.HistogramResult)=>void)[]){const d=data();change(d);expect(validHistogram(d)).toBe(false);}});
