import {cleanup,fireEvent,render,screen} from "@testing-library/react";
import {afterEach,expect,test} from "vitest";
import {pageUIManifest} from "@platform/kernel";
import {StaticImage,validStaticImage,validStaticImageURL} from "./StaticImage";
afterEach(cleanup);
test("static image policy preserves actual public URLs and refuses ambiguous, credentialed or executable sources",()=>{
 for(const url of ["https://images.example/real.png?version=2#crop","http://localhost:18496/real.png","/assets/real.png","/图像.png","https://[::1]:5433/img.png"]){expect(validStaticImageURL(url),url).toBe(true);expect(validStaticImage({url,caption:"",height:0}),url).toBe(true);}
 for(const url of ["",undefined,"//other.example/real.png","/%2fevil.example/img.png","https:///other.example/real.png","https://user:secret@other.example/img.png","https://@other.example/img.png","https://other.example/white space.png","https://other.example/%20.png","/assets/%0A.png","/assets/%5C.png","/assets/%FF.png","/assets/%.png","https://other.example:invalid/a","https://other.example:65536/a","https://other.example/a\u007f.png","https:\\other.example/a","data:image/png;base64,actual","blob:https://other.example/A","file:///img.png","javascript:alert(1)"]){expect(validStaticImageURL(url),String(url)).toBe(false);}
 expect(validStaticImage({})).toBe(true);expect(validStaticImage({url:"",caption:"",height:12.5})).toBe(true);for(const config of [{height:NaN},{height:Infinity},{height:-1},{height:pageUIManifest.runtime.contextViews.maxImageHeight+1},{url:"https://example/a".padEnd(pageUIManifest.runtime.contextViews.maxURLBytes+1,"a")},{caption:"字".repeat(pageUIManifest.runtime.contextViews.maxCaptionBytes)},{url:null},{height:"160"},{variableId:"IMAGE"}])expect(validStaticImage(config)).toBe(false);
});
test("static image preserves source URL, literal caption and alt while reporting genuine load or failure",()=>{
 const view=render(<StaticImage src="https://images.example/real.png" alt="Actual image" caption="<b>Original caption</b>" height={0}/>),img=screen.getByRole("img",{name:"Actual image"});expect(img.getAttribute("src")).toBe("https://images.example/real.png");expect(img.getAttribute("referrerpolicy")).toBe("no-referrer");expect(screen.getByRole("status").textContent).toBe("Loading configured image…");expect(screen.getByText("<b>Original caption</b>")).toBeTruthy();expect(view.container.querySelector("b")).toBeNull();fireEvent.load(img);expect(screen.queryByRole("status")).toBeNull();fireEvent.error(img);expect(screen.getByRole("alert").textContent).toBe("The configured image could not be loaded.");
});
test("URL replacement retires late image events and resets refused state while missing URLs retain the explicit placeholder",()=>{
 const view=render(<StaticImage src="/assets/A.png" alt="A"/>),original=screen.getByRole("img");fireEvent.error(original);expect(screen.getByRole("alert")).toBeTruthy();view.rerender(<StaticImage src="/assets/B.png" alt="B"/>);const next=screen.getByRole("img",{name:"B"});expect(screen.queryByRole("alert")).toBeNull();expect(screen.getByRole("status").textContent).toBe("Loading configured image…");fireEvent.load(original);fireEvent.error(original);expect(screen.getByRole("status").textContent).toBe("Loading configured image…");fireEvent.load(next);expect(screen.queryByRole("status")).toBeNull();
 view.rerender(<StaticImage alt="Original empty image" caption=""/>);expect(screen.getByRole("status").textContent).toBe("No image URL configured");expect(screen.queryByRole("img")).toBeNull();view.rerender(<StaticImage src="data:image/png;base64,AAAA" alt="Unsupported"/>);expect(screen.getByRole("alert")).toBeTruthy();expect(screen.queryByRole("img")).toBeNull();
});
