import {useEffect,useMemo,useState} from "react";
import {RecordMap} from "./RecordMap";
import {ImageAnnotation} from "./ImageAnnotation";
import {Scene3D} from "./Scene3D";
import {triangleGLB} from "./scene-fixture";
import type {EntityInfo,EntityRecord,AttachedFile} from "../records/Records";
import {t} from "../i18n";
const stamp={by:"example",at:"2026-10-04T00:00:00Z"},record=(id:string,data:Record<string,unknown>)=>({id,revision:1,created:stamp,changed:stamp,...data}),info={type:"example.asset",app:"example",title:"Example assets",plural:"Example assets",display:"name",fields:[{name:"name",title:"Name",type:"text"},{name:"latitude",title:"Latitude",type:"decimal"},{name:"longitude",title:"Longitude",type:"decimal"},{name:"pressure",title:"Pressure",type:"decimal"}],standard:[]} as EntityInfo;
const rows=[record("EXAMPLE-A",{name:"Example Alpha",latitude:37.7749,longitude:-122.4194,pressure:12}),record("EXAMPLE-B",{name:"Example Beta",latitude:31.2304,longitude:121.4737,pressure:16})];
export function SpatialMapExample(){const [selected,setSelected]=useState<string>();return <RecordMap records={rows} info={info} fields={{latitudeField:"latitude",longitudeField:"longitude",labelField:"name"}} scope="isolated-map-example" selected={selected} onSelect={r=>setSelected(r.id)}/>;}
function useFixtureAttachment(kind:"raster"|"model"){
 const [result,setResult]=useState<{attachment:AttachedFile;blob:Blob}>();
 useEffect(()=>{let active=true;void(async()=>{let blob:Blob;if(kind==="model")blob=new Blob([triangleGLB()],{type:"model/gltf-binary"});else {const canvas=document.createElement("canvas");canvas.width=320;canvas.height=160;const context=canvas.getContext("2d");if(!context)return;context.fillStyle="#d5dde4";context.fillRect(0,0,320,160);context.fillStyle="#238acf";context.fillRect(40,35,90,75);context.fillStyle="#1abb7f";context.fillRect(180,35,90,75);blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(value=>value?resolve(value):reject(Error("fixture")),"image/png"));}const hash=[...new Uint8Array(await crypto.subtle.digest("SHA-256",await blob.arrayBuffer()))].map(n=>n.toString(16).padStart(2,"0")).join("");if(active)setResult({blob,attachment:{...record("EXAMPLE-FILE",{}),by:"example",name:kind==="model"?"triangle.glb":"drawing.png",contentType:blob.type,size:blob.size,hash,target:"example.asset/EXAMPLE-A",regions:[{id:"EXAMPLE-REGION",label:"Example region",x:.125,y:.21875,width:.28125,height:.46875}]}});})();return()=>{active=false;};},[kind]);return result;
}
export function SpatialAnnotationExample(){const fixture=useFixtureAttachment("raster");return fixture?<ImageAnnotation {...fixture} scope="isolated-annotation-example"/>:<p role="status">{t("Preparing isolated spatial fixture…")}</p>;}
export function SpatialSceneExample(){const fixture=useFixtureAttachment("model"),[selected,setSelected]=useState<string>(),config=useMemo(()=>({background:"dark" as const,showGrid:true,quality:"balanced" as const,layers:[{id:"part",name:"Example layer",nodes:["FixturePart"],visible:true,opacity:1,wireframe:false}],mappings:[{id:"pressure",node:"FixturePart",source:"asset" as const,field:"pressure",mode:"position" as const,axis:"x" as const,inputMin:0,inputMax:20,outputMin:-.1,outputMax:.1,enabled:true}]}),[]);return fixture?<><Scene3D {...fixture} scope="isolated-scene-example" asset={{record:rows[0] as EntityRecord,info}} config={config} selected={selected} onSelect={setSelected}/>{selected&&<p>{t("Selected model part: {part}",{part:selected})}</p>}</>:<p role="status">{t("Preparing isolated spatial fixture…")}</p>;}
