import {rasterDimensions} from "../records/attachment-bytes";
import {sceneLimits} from "./scene-model";
type Obj=Record<string,any>;
const object=(v:unknown):v is Obj=>!!v&&typeof v==="object"&&!Array.isArray(v),uint=(n:unknown):n is number=>typeof n==="number"&&Number.isSafeInteger(n)&&n>=0;
/** Inspect the binary container and allocation bounds before Three can allocate or resolve any URI. */
export function boundedGLB(bytes:ArrayBuffer){
 function invalid():never{throw Error("The model is not a bounded self-contained GLB.");}
 if(bytes.byteLength<20||bytes.byteLength>sceneLimits.maxBytes)invalid();const data=new DataView(bytes);
 if(data.getUint32(0,true)!==0x46546c67||data.getUint32(4,true)!==2||data.getUint32(8,true)!==bytes.byteLength)invalid();
 const size=data.getUint32(12,true);if(size>sceneLimits.maxJSONBytes||size%4||20+size>bytes.byteLength||data.getUint32(16,true)!==0x4e4f534a)invalid();
 let doc:Obj;try{doc=JSON.parse(new TextDecoder("utf-8",{fatal:true}).decode(new Uint8Array(bytes,20,size)));}catch{return invalid();}
 if(!object(doc)||doc.asset?.version!=="2.0")invalid();let binary:Uint8Array|undefined;const at=20+size;
 if(at<bytes.byteLength){if(at+8>bytes.byteLength||data.getUint32(at+4,true)!==0x004e4942||data.getUint32(at,true)%4||at+8+data.getUint32(at,true)!==bytes.byteLength)invalid();binary=new Uint8Array(bytes,at+8);}
 const scan=[doc];let slots=0;while(scan.length){const value=scan.pop()!;if(++slots>100000)invalid();if(Array.isArray(value)){scan.push(...value);continue;}if(!object(value))continue;for(const [key,v]of Object.entries(value)){if(["uri","__proto__","prototype","constructor"].includes(key))invalid();if(key==="extensions"&&(!object(v)||Object.keys(v).some(k=>k!=="KHR_materials_unlit")))invalid();if(v&&typeof v==="object")scan.push(v);}}
 for(const key of ["extensionsUsed","extensionsRequired"]){if(doc[key]!==undefined&&(!Array.isArray(doc[key])||doc[key].some((s:unknown)=>s!=="KHR_materials_unlit")))invalid();}
 for(const [key,limit]of [["nodes",sceneLimits.maxNodes],["meshes",sceneLimits.maxMeshes],["materials",sceneLimits.maxMaterials],["images",32],["textures",32],["bufferViews",4096],["accessors",4096],["scenes",1],["animations",32],["skins",32]] as const){if(doc[key]!==undefined&&(!Array.isArray(doc[key])||doc[key].length>limit))invalid();}
 if(!Array.isArray(doc.nodes)||!Array.isArray(doc.meshes)||!Array.isArray(doc.scenes)||!uint(doc.scene??0)||!doc.scenes[doc.scene??0])invalid();
 if(!Array.isArray(doc.buffers)||doc.buffers.length!==1||!binary||!uint(doc.buffers[0]?.byteLength)||doc.buffers[0].byteLength>binary.length||binary.length-doc.buffers[0].byteLength>3)invalid();
 const buffers=doc.bufferViews??[];for(const b of buffers){if(!object(b)||b.buffer!==0||!uint(b.byteOffset??0)||!uint(b.byteLength)||(b.byteOffset??0)+b.byteLength>doc.buffers[0].byteLength||b.byteStride!==undefined&&(!uint(b.byteStride)||b.byteStride<4||b.byteStride>252||b.byteStride%4))invalid();}
 const packed=new DataView(binary!.buffer,binary!.byteOffset,binary!.byteLength);let vertices=0,indices=0;
 for(const a of doc.accessors??[]){const components={SCALAR:1,VEC2:2,VEC3:3,VEC4:4,MAT2:4,MAT3:9,MAT4:16}[a.type as string],width={5120:1,5121:1,5122:2,5123:2,5125:4,5126:4}[a.componentType as number],view=buffers[a.bufferView];if(!object(a)||!uint(a.count)||!components||!width||!uint(a.byteOffset??0)||a.sparse!==undefined||!uint(a.bufferView)||!view)invalid();for(const key of ["min","max"]){if(a[key]!==undefined&&(!Array.isArray(a[key])||a[key].length!==components||a[key].some((n:unknown)=>typeof n!=="number"||!Number.isFinite(n)||Math.abs(n)>1e9)))invalid();}const stride=view.byteStride??components*width;if(stride<components*width||(a.byteOffset??0)+(a.count?stride*(a.count-1)+components*width:0)>view.byteLength)invalid();if(a.type==="SCALAR")indices+=a.count;else vertices+=a.count;}
 if(vertices>sceneLimits.maxVertices||indices>sceneLimits.maxIndices)invalid();
 let pixels=0;for(const img of doc.images??[]){const view=buffers[img.bufferView];if(!object(img)||!uint(img.bufferView)||!view||!["image/png","image/jpeg"].includes(img.mimeType))invalid();const dimensions=rasterDimensions(binary!.subarray(view.byteOffset??0,(view.byteOffset??0)+view.byteLength),img.mimeType);if(!dimensions||!dimensions.width||!dimensions.height)invalid();pixels+=dimensions!.width*dimensions!.height;if(pixels>sceneLimits.maxTexturePixels)invalid();}
 const visited=new Set<number>(),parents=new Set<number>();
 const walk=(id:number,path:Set<number>)=>{if(!uint(id)||!doc.nodes[id]||path.has(id)||parents.has(id))invalid();parents.add(id);const n=doc.nodes[id];if(n.name!==undefined&&(typeof n.name!=="string"||n.name.length>256))invalid();for(const [key,len]of [["translation",3],["rotation",4],["scale",3],["matrix",16]] as const){if(n[key]!==undefined&&(!Array.isArray(n[key])||n[key].length!==len||n[key].some((v:unknown)=>typeof v!=="number"||!Number.isFinite(v)||Math.abs(v)>1e9)))invalid();}if(n.mesh!==undefined&&(!uint(n.mesh)||!doc.meshes[n.mesh]))invalid();if(n.children!==undefined&&!Array.isArray(n.children))invalid();visited.add(id);const next=new Set(path);next.add(id);for(const child of n.children??[])walk(child,next);};
 for(const id of doc.scenes[doc.scene??0].nodes??[])walk(id,new Set());
 // GLTFLoader constructs every declared node, including unreachable ones.
 for(let i=0;i<doc.nodes.length;i++){if(!visited.has(i))walk(i,new Set());}
 for(const mesh of doc.meshes){if(!Array.isArray(mesh.primitives)||mesh.primitives.length>128)invalid();for(const p of mesh.primitives){if(!object(p.attributes)||!uint(p.attributes.POSITION)||!doc.accessors[p.attributes.POSITION]||p.mode!==undefined&&p.mode!==4)invalid();for(const index of Object.values(p.attributes)){if(!uint(index)||!doc.accessors[index])invalid();}if(p.indices!==undefined&&(!uint(p.indices)||!doc.accessors[p.indices]))invalid();if(p.material!==undefined&&(!uint(p.material)||!doc.materials?.[p.material]))invalid();const a=doc.accessors[p.attributes.POSITION],v=buffers[a.bufferView];if(a.type!=="VEC3"||a.componentType!==5126)invalid();const stride=v.byteStride??12,base=(v.byteOffset??0)+(a.byteOffset??0);for(let i=0;i<a.count;i++)for(let axis=0;axis<3;axis++){const n=packed.getFloat32(base+i*stride+axis*4,true);if(!Number.isFinite(n)||Math.abs(n)>1e9||a.min&&n<a.min[axis]||a.max&&n>a.max[axis])invalid();}}}
 return {doc,vertices,indices,nodes:doc.nodes.length};
}
