import {InputDraftProvider,InputProblems,useInputDrafts} from "../fields/draft";
import {useEffect,useRef,useState} from "react";
import {imageRegionLimits,type Api} from "@platform/kernel";
import {Button} from "../primitives/button";
import {Input} from "../primitives/input";
import {t} from "../i18n";
import type {AttachmentPreviewProps} from "../records/MediaPreview";
import {useRasterAttachment} from "../records/useRasterAttachment";
import {validImageRegions} from "./image-regions";
import {useSvgViewport} from "./useSvgViewport";

export type ImageAnnotationProps=AttachmentPreviewProps&{enabled?:boolean;onSave?:(regions:Api.ImageRegion[],revision:number)=>Promise<boolean>};
export function ImageAnnotation(props:ImageAnnotationProps){return <InputDraftProvider isolated key={JSON.stringify([props.scope,props.attachment.id,props.attachment.hash])} scope={props.attachment.id}><AnnotationSession {...props}/></InputDraftProvider>;}
function AnnotationSession({attachment,blob,scope,enabled=true,onSave}:ImageAnnotationProps){
 const inputs=useInputDrafts();
 const raster=useRasterAttachment(attachment,blob,scope),[regions,setRegions]=useState<Api.ImageRegion[]>(()=>structuredClone(attachment.regions??[])),[base,setBase]=useState(attachment.revision),[edited,setDirty]=useState(false),[mode,setMode]=useState<"draw"|"pan">("draw"),[selected,setSelected]=useState<string>(),[pending,setPending]=useState<{x:number;y:number;width:number;height:number}>(),[busy,setBusy]=useState(false),[error,setError]=useState<string>();
 const dirty=edited||!!inputs?.dirty;
 const mounted=useRef(true),start=useRef<{x:number;y:number}|undefined>(undefined),camera=useSvgViewport(raster.width??1,raster.height??1,mode==="pan",16),w=raster.width??1,h=raster.height??1,writable=enabled&&!!onSave&&!busy,valid=validImageRegions(regions);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
 useEffect(()=>{if(!dirty){setRegions(structuredClone(attachment.regions??[]));setBase(attachment.revision);}},[attachment.revision,JSON.stringify(attachment.regions)]);
 const save=async()=>{if(!writable||!valid||!dirty||inputs?.invalid)return;setBusy(true);setError(undefined);try{if(await onSave!(structuredClone(regions),base)&&mounted.current){setBase(base+1);setDirty(false);inputs?.clear();}else if(mounted.current)setError(t("Image regions were not saved. Your draft is retained."));}catch(e){if(mounted.current)setError(e instanceof Error?t(e.message):t("Image regions were not saved. Your draft is retained."));}finally{if(mounted.current)setBusy(false);}};
 const edit=(id:string,patch:Partial<Api.ImageRegion>)=>{if(!writable)return;const next=regions.map(r=>r.id===id?{...r,...patch}:r);if(!validImageRegions(next)){setError(t("Image region identities or coordinates are incompatible."));return;}setError(undefined);setRegions(next);setDirty(true);};
 if(raster.error||!valid)return <p role="alert">{raster.error?t(raster.error):t("Image region identities or coordinates are incompatible.")}</p>;
 if(!raster.supported)return <p role="status">{t("Annotations require an original raster attachment.")}</p>;
 if(!raster.url)return <p role="status">{t("Decoding authorized media bytes…")}</p>;
 const v=camera.view,chosen=regions.find(r=>r.id===selected);
 return <section aria-label={t("Image annotation")} className="grid min-w-0 gap-2"><p className="text-xs text-muted">{attachment.name} · {attachment.id} · {w} × {h}</p><div className="flex flex-wrap gap-1"><Button size="sm" disabled={!writable} aria-pressed={mode==="draw"} onClick={()=>setMode("draw")}>{t("Draw region")}</Button><Button size="sm" aria-pressed={mode==="pan"} onClick={()=>setMode("pan")}>{t("Pan image")}</Button><Button size="sm" onClick={()=>camera.zoom(1.5)}>{t("Zoom in")}</Button><Button size="sm" onClick={()=>camera.zoom(1/1.5)}>{t("Zoom out")}</Button><Button size="sm" onClick={camera.reset}>{t("Fit image")}</Button></div>
 <svg ref={camera.ref} {...camera.handlers} role="group" aria-label={t("Annotated image")} viewBox={`0 0 ${w} ${h}`} className="w-full touch-none overflow-hidden rounded border border-border" onPointerDown={e=>{if(mode==="pan"){camera.handlers.onPointerDown(e);return;}if(!writable||e.button!==0||regions.length>=imageRegionLimits.maxRegions)return;const p=camera.imagePoint(e.clientX,e.clientY);if(!p)return;e.currentTarget.setPointerCapture(e.pointerId);start.current=p;setPending(undefined);}} onPointerMove={e=>{if(mode==="pan"){camera.handlers.onPointerMove(e);return;}const a=start.current,p=camera.imagePoint(e.clientX,e.clientY);if(!a||!p)return;setPending({x:Math.min(a.x,p.x)/w,y:Math.min(a.y,p.y)/h,width:Math.abs(p.x-a.x)/w,height:Math.abs(p.y-a.y)/h});}} onPointerUp={e=>{if(mode==="pan"){camera.handlers.onPointerUp();return;}const a=start.current,p=camera.imagePoint(e.clientX,e.clientY);start.current=undefined;setPending(undefined);if(!a||!p||!writable||regions.length>=imageRegionLimits.maxRegions)return;const r={id:"REGION-"+crypto.randomUUID(),label:"",x:Math.min(a.x,p.x)/w,y:Math.min(a.y,p.y)/h,width:Math.abs(p.x-a.x)/w,height:Math.abs(p.y-a.y)/h};if(!validImageRegions([...regions,r]))return;setRegions(old=>[...old,r]);setDirty(true);setSelected(r.id);}} onPointerCancel={()=>{start.current=undefined;setPending(undefined);camera.handlers.onPointerCancel();}}>
 <g transform={`translate(${v.x} ${v.y}) scale(${v.k})`}><image href={raster.url} width={w} height={h} onError={raster.fail}/>{regions.map(r=><g key={r.id}><rect x={r.x*w} y={r.y*h} width={r.width*w} height={r.height*h} fill="var(--tone-danger)" fillOpacity={.12} stroke={r.id===selected?"var(--foreground)":"var(--tone-danger)"} strokeWidth={2} vectorEffect="non-scaling-stroke"/><title>{r.label||r.id}</title></g>)}{pending&&<rect x={pending.x*w} y={pending.y*h} width={pending.width*w} height={pending.height*h} fill="none" stroke="var(--accent)" strokeWidth={2} vectorEffect="non-scaling-stroke"/>}</g></svg>
 <p role="status" className="text-xs text-muted">{t("{count} image regions",{count:regions.length})}{attachment.revision!==base&&dirty?` · ${t("The original attachment changed. Reload or resolve the region conflict before saving.")}`:""}</p><div className="flex flex-wrap gap-1">{regions.map(r=><Button key={r.id} size="sm" aria-pressed={r.id===selected} onClick={()=>setSelected(r.id)}>{r.label||r.id}</Button>)}</div>
 {chosen&&<div className="grid gap-2"><label className="grid gap-1 text-xs">{t("Region label")}<Input value={chosen.label} disabled={!writable} onChange={e=>edit(chosen.id,{label:e.target.value})}/></label><div className="grid grid-cols-2 gap-2">{(["x","y","width","height"] as const).map(key=><label key={key} className="grid gap-1 text-xs">{t({x:"Region X",y:"Region Y",width:"Region width",height:"Region height"}[key])}<Input draftKey={`region:${chosen.id}:${key}`} type="number" min={0} max={1} step={.01} value={chosen[key]} disabled={!writable} onChange={e=>{const next={...chosen,[key]:e.target.valueAsNumber};if(validImageRegions([next]))edit(chosen.id,{[key]:e.target.valueAsNumber});else inputs?.set(`${inputs.scope}/number:region:${chosen.id}:${key}`,{text:e.target.value,source:String(chosen[key]),problem:t("Image region identities or coordinates are incompatible.")});}}/></label>)}</div><Button size="sm" disabled={!writable} onClick={()=>{inputs?.clear(`${inputs.scope}/number:region:${chosen.id}:`);setRegions(old=>old.filter(r=>r.id!==chosen.id));setDirty(true);setSelected(undefined);}}>{t("Delete region")}</Button></div>}
 {onSave&&<div className="flex flex-wrap gap-1"><Button disabled={!writable||!dirty||!valid||inputs?.invalid} onClick={()=>void save()}>{t(busy?"Saving regions…":"Save image regions")}</Button><Button disabled={!writable||regions.length>=imageRegionLimits.maxRegions} onClick={()=>{const r={id:"REGION-"+crypto.randomUUID(),label:"",x:.1,y:.1,width:.2,height:.2};setRegions(old=>[...old,r]);setSelected(r.id);setDirty(true);}}>{t("Add region")}</Button><Button disabled={!writable||!regions.length} onClick={()=>{inputs?.clear();setRegions([]);setSelected(undefined);setDirty(true);}}>{t("Clear regions")}</Button><Button disabled={busy} onClick={()=>{inputs?.clear();setRegions(structuredClone(attachment.regions??[]));setBase(attachment.revision);setDirty(false);setSelected(undefined);setError(undefined);}}>{t("Reload saved regions")}</Button></div>}<InputProblems/>{error&&<p role="alert">{error}</p>}</section>;
}
