import {useEffect,useState} from "react";
import {Button} from "../primitives/button";
import {t} from "../i18n";
import {scatterPoints} from "../records/RecordScatter";
import type {EntityInfo,EntityRecord} from "../records/Records";
import {useSvgViewport} from "./useSvgViewport";
import {landRingPath} from "./world-land";

export type RecordMapFields={latitudeField:string;longitudeField:string;labelField:string;colorField?:string};
export type RecordMapProps={records:EntityRecord[];info:EntityInfo;fields:RecordMapFields;scope?:string;selected?:string;enabled?:boolean;clusterEnabled?:boolean;onSelect?:(record:EntityRecord)=>void};
const W=1000,H=500,project=(longitude:number,latitude:number)=>({x:(longitude+180)/360*W,y:(90-latitude)/180*H});
export function mapPoints(records:EntityRecord[],info:EntityInfo,fields:RecordMapFields){const model=scatterPoints(records,info,{xField:fields.longitudeField,yField:fields.latitudeField,labelField:fields.labelField,colorField:fields.colorField});if(!model)return;let invalid=0;const points=model.points.flatMap(p=>{if(p.y < -90||p.y>90||p.x < -180||p.x>180){invalid++;return [];}return [{...p,...project(p.x,p.y),latitude:p.y,longitude:p.x}];});return {...model,points,invalid};}
let land:Promise<string>|undefined;
async function worldLand(){land??=(async()=>{const [{feature},{default:raw}]=await Promise.all([import("topojson-client"),import("world-atlas/countries-110m.json")]);const topology=raw as unknown as Parameters<typeof feature>[0],result=feature(topology,topology.objects.countries!);if(result.type!=="FeatureCollection")throw Error("Invalid map background");return result.features.flatMap(f=>f.geometry.type==="Polygon"?f.geometry.coordinates.map(landRingPath):f.geometry.type==="MultiPolygon"?f.geometry.coordinates.flatMap(p=>p.map(landRingPath)):[]).join("");})();return land;}
export function RecordMap(props:RecordMapProps){return <MapSession key={props.scope} {...props}/>;}
function MapSession({records,info,fields,selected,enabled=true,clusterEnabled=true,onSelect}:RecordMapProps){
 const model=mapPoints(records,info,fields),camera=useSvgViewport(W,H),[background,setBackground]=useState<string>(),[failure,setFailure]=useState(false),[hidden,setHidden]=useState<(string|undefined)[]>([]),[cluster,setCluster]=useState(clusterEnabled),[showLand,setShowLand]=useState(true),[hover,setHover]=useState<string>();
 useEffect(()=>{let active=true;void worldLand().then(path=>{if(active)setBackground(path);}).catch(()=>{if(active)setFailure(true);});return()=>{active=false;};},[]);
 const selectedPoint=model?.points.find(p=>p.record.id===selected);
 useEffect(()=>{if(selectedPoint)camera.reveal(selectedPoint);},[selected,selectedPoint?.x,selectedPoint?.y]);
 if(!model)return <p role="alert">{t("Map fields or record coordinates are unavailable or incompatible.")}</p>;
 const v=camera.view,categories=model.categories,color=(c?:string)=>`var(${["--tone-info","--tone-success","--tone-warning","--tone-danger","--chart-5","--chart-6"][categories.indexOf(c)%6]})`,label=(c?:string)=>c===undefined?t("No value"):c===""?t("Empty text"):c,visible=model.points.filter(p=>!hidden.includes(p.category)),groups=new Map<string,typeof visible>();
 const cell=34/v.k;for(const p of visible){const key=cluster&&v.k<18&&p.record.id!==selected?`${Math.floor(p.x/cell)}:${Math.floor(p.y/cell)}`:p.record.id;if(!groups.has(key))groups.set(key,[]);groups.get(key)!.push(p);}
 const select=(record:EntityRecord)=>{if(enabled&&!camera.moved())onSelect?.(record);};
 return <div className="grid min-w-0 gap-2"><div className="flex flex-wrap gap-1"><Button size="sm" onClick={()=>camera.zoom(1.5)}>{t("Zoom in")}</Button><Button size="sm" onClick={()=>camera.zoom(1/1.5)}>{t("Zoom out")}</Button><Button size="sm" onClick={()=>camera.fit(model.points)}>{t("Fit records")}</Button><Button size="sm" onClick={camera.reset}>{t("Reset view")}</Button><Button size="sm" aria-pressed={cluster} onClick={()=>setCluster(!cluster)}>{t("Cluster records")}</Button><Button size="sm" aria-pressed={showLand} onClick={()=>setShowLand(!showLand)}>{t("World background")}</Button></div>
 <p role="status" className="text-xs text-muted">{t("{points} mapped records · {missing} missing · {invalid} outside WGS84 bounds",{points:model.points.length,missing:model.missing,invalid:model.invalid})}</p>{failure&&<p role="alert">{t("The bundled map background could not be loaded.")}</p>}
 <svg ref={camera.ref} {...camera.handlers} role="group" aria-label={t("Record map")} viewBox={`0 0 ${W} ${H}`} className="w-full touch-none rounded border border-border bg-surface"><g transform={`translate(${v.x} ${v.y}) scale(${v.k})`}>
 <path d={Array.from({length:13},(_,i)=>`M${i*W/12} 0V${H}`).join("")+Array.from({length:7},(_,i)=>`M0 ${i*H/6}H${W}`).join("")} stroke="var(--border)" fill="none" vectorEffect="non-scaling-stroke"/>{showLand&&background&&<path d={background} fill="var(--row-hover)" stroke="var(--muted)" strokeWidth={.6} fillRule="evenodd" vectorEffect="non-scaling-stroke"/>}
 {[...groups].map(([key,items])=>items.length>1?<g key={key} role="button" aria-label={t("Zoom to {count} clustered records",{count:items.length})} tabIndex={0} onClick={()=>{if(!camera.moved())camera.fit(items);}} onKeyDown={e=>{if(e.key==="Enter")camera.fit(items);}} transform={`translate(${items.reduce((n,p)=>n+p.x,0)/items.length} ${items.reduce((n,p)=>n+p.y,0)/items.length})`} className="cursor-pointer"><circle r={14/v.k} fill="var(--accent)"/><text textAnchor="middle" dy={4/v.k} fontSize={12/v.k} fill="var(--accent-foreground)">{items.length}</text></g>:<circle key={key} cx={items[0]!.x} cy={items[0]!.y} r={(items[0]!.record.id===selected?8:5)/v.k} fill={color(items[0]!.category)} stroke={items[0]!.record.id===selected?"var(--foreground)":"var(--surface)"} vectorEffect="non-scaling-stroke" role="button" aria-label={`${items[0]!.label} · ${items[0]!.record.id}`} aria-pressed={items[0]!.record.id===selected} tabIndex={0} onClick={()=>select(items[0]!.record)} onKeyDown={e=>{if(enabled&&(e.key==="Enter"||e.key===" ")){e.preventDefault();onSelect?.(items[0]!.record);}}} onPointerEnter={()=>setHover(items[0]!.record.id)} onPointerLeave={()=>setHover(undefined)}><title>{`${items[0]!.label} · ${items[0]!.latitude}, ${items[0]!.longitude}`}</title></circle>)}
 </g></svg>{hover&&<p className="text-xs">{model.points.find(p=>p.record.id===hover)?.label} · {hover}</p>}
 <div className="flex flex-wrap gap-2">{categories.map((c,i)=><Button key={i} size="sm" aria-pressed={!hidden.includes(c)} onClick={()=>setHidden(h=>h.includes(c)?h.filter(v=>v!==c):[...h,c])}><span style={{background:color(c)}} className="size-2 rounded-full"/>{label(c)} · {model.points.filter(p=>p.category===c).length}</Button>)}</div>
 <details><summary className="text-xs">{t("Records in this map window")}</summary><div className="flex flex-wrap gap-1">{visible.map(p=><Button key={p.record.id} size="sm" disabled={!enabled||!onSelect} aria-pressed={p.record.id===selected} onClick={()=>onSelect?.(p.record)}>{p.label} · {p.record.id}</Button>)}</div></details><p className="text-xs text-muted">{t("World background: Natural Earth, bundled with World Atlas.")}</p></div>;
}
