import {useEffect,useRef,useState} from "react";
import type {Material,Mesh,Object3D,Texture,Vector3,Euler,Color} from "three";
import {Button} from "../primitives/button";
import {Input} from "../primitives/input";
import {t} from "../i18n";
import type {AttachmentPreviewProps} from "../records/MediaPreview";
import {attachmentBytesError,mediaType} from "../records/attachment-bytes";
import {boundedGLB} from "./glb";
import {sceneMappingValue,validSceneConfig,type SceneConfig,type SceneInput} from "./scene-model";

export type Scene3DProps=AttachmentPreviewProps&{scope:string;asset:SceneInput;sample?:SceneInput;config:SceneConfig;enabled?:boolean;selected?:string;onSelect?:(part:string)=>void};
type Part={path:string;name:string;depth:number};
function disposeModel(root:Object3D){const geometries=new Set<Mesh["geometry"]>(),materials=new Set<Material>(),textures=new Set<Texture>();root.traverse(node=>{const mesh=node as Mesh;if(!mesh.isMesh)return;geometries.add(mesh.geometry);for(const m of Array.isArray(mesh.material)?mesh.material:[mesh.material]){materials.add(m);for(const v of Object.values(m))if(v&&typeof v==="object"&&(v as Texture).isTexture)textures.add(v as Texture);}});for(const g of geometries)g.dispose();for(const m of materials)m.dispose();for(const texture of textures){const image=texture.source?.data;if(image&&typeof (image as {close?:unknown}).close==="function")(image as {close:()=>void}).close();texture.dispose();}}
export function Scene3D(props:Scene3DProps){return <SceneSession key={JSON.stringify([props.scope,props.attachment.id,props.attachment.hash])} {...props}/>;}
function SceneSession({attachment,blob,scope,asset,sample,config,enabled=true,selected,onSelect}:Scene3DProps){
 const canvas=useRef<HTMLDivElement>(null),[parts,setParts]=useState<Part[]>([]),[chosen,setChosen]=useState(selected),[layers,setLayers]=useState(config.layers),[explode,setExplode]=useState(0),[isolate,setIsolate]=useState(false),[state,setState]=useState<"loading"|"ready"|"error">("loading"),[error,setError]=useState<string>(),[stats,setStats]=useState<{meshes:number;triangles:number}>(),[tab,setTab]=useState<"parts"|"layers"|"bindings">("parts");
 const current=useRef({asset,sample,config,layers,explode,isolate,chosen,enabled,onSelect});current.current={asset,sample,config,layers,explode,isolate,chosen,enabled,onSelect};const fit=useRef<(()=>void)|undefined>(undefined),pick=useRef<((path:string)=>void)|undefined>(undefined);
 useEffect(()=>setChosen(selected),[selected]);useEffect(()=>setLayers(config.layers),[JSON.stringify(config.layers)]);
 const metadataError=attachmentBytesError(attachment,blob),valid=validSceneConfig(config),type=mediaType(attachment.contentType),supported=["model/gltf-binary","application/octet-stream"].includes(type),targetValid=attachment.target===`${asset.info.type}/${asset.record.id}`;
 useEffect(()=>{
  const host=canvas.current;if(!host||metadataError||!valid||!supported||!targetValid)return;
  let active=true,cleanup:(()=>void)|undefined,orphanedMaterials:Material[]=[];setState("loading");setParts([]);setStats(undefined);setError(undefined);
  void(async()=>{let loaded:Object3D|undefined;try{
   const bytes=await blob.arrayBuffer();if(!active)return;const original=boundedGLB(bytes);
   if(typeof attachment.hash!=="string"||!/^[a-f0-9]{64}$/.test(attachment.hash))throw Error("The original model hash is unavailable.");
   const digest=[...new Uint8Array(await crypto.subtle.digest("SHA-256",bytes))].map(n=>n.toString(16).padStart(2,"0")).join("");if(!active)return;if(digest!==attachment.hash)throw Error("The model bytes do not match the original attachment hash.");
   const THREE=await import("three"),[{OrbitControls},{GLTFLoader}]=await Promise.all([import("three/addons/controls/OrbitControls.js"),import("three/addons/loaders/GLTFLoader.js")]);if(!active)return;
   const manager=new THREE.LoadingManager();manager.setURLModifier(url=>{if(!url.startsWith("blob:"))throw Error("The model requested a resource outside its attachment.");return url;});
   const gltf=await new GLTFLoader(manager).parseAsync(bytes,"");loaded=gltf.scene;if(!active){disposeModel(loaded);return;}
   const root=loaded,scene=new THREE.Scene();
   const originals=new Map<Object3D,{position:Vector3;rotation:Euler;scale:Vector3;visible:boolean}>(),materials=new Map<Material,Material>(),nodes=new Map<string,Object3D>(),names=new Map<string,Object3D[]>(),paths=new Map<Object3D,string>(),partList:Part[]=[];let meshes=0;
   const originalMaterials=new Set<Material>();
   const walk=(node:Object3D,path:string,depth:number)=>{const association=gltf.parser.associations.get(node),originalName=association?.nodes===undefined?node.name:original.doc.nodes[association.nodes]?.name;const name=typeof originalName==="string"?originalName:"";const key=path+"/"+encodeURIComponent(name||"node")+"["+depth+"]";paths.set(node,key);nodes.set(key,node);originals.set(node,{position:node.position.clone(),rotation:node.rotation.clone(),scale:node.scale.clone(),visible:node.visible});if(name){if(!names.has(name))names.set(name,[]);names.get(name)!.push(node);partList.push({path:key,name,depth:key.split("/").length-2});}const mesh=node as Mesh;if(mesh.isMesh){meshes++;const clone=(m:Material)=>{originalMaterials.add(m);const next=m.clone();const base=next.clone();materials.set(next,base);orphanedMaterials.push(base);return next;};mesh.material=Array.isArray(mesh.material)?mesh.material.map(clone):clone(mesh.material);}node.children.forEach((child,i)=>walk(child,key,i));};walk(root,"",0);for(const m of originalMaterials)m.dispose();
   const resolve=(key:string)=>{const exact=nodes.get(key);if(exact)return exact;const list=names.get(key);return list?.length===1?list[0]:undefined;};
   const diagnostics=()=>{for(const l of current.current.layers)for(const n of l.nodes)if(!resolve(n))throw Error("A configured model part is missing or ambiguous.");for(const m of current.current.config.mappings)if(!resolve(m.node))throw Error("A configured model part is missing or ambiguous.");};diagnostics();
   const renderer=new THREE.WebGLRenderer({antialias:config.quality!=="performance",alpha:false}),camera=new THREE.PerspectiveCamera(46,1,.01,1000),controls=new OrbitControls(camera,renderer.domElement);
   cleanup=()=>{controls.dispose();renderer.dispose();renderer.forceContextLoss();renderer.domElement.remove();disposeModel(root);for(const m of orphanedMaterials)m.dispose();};
   renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.domElement.className="h-full w-full touch-none";host.appendChild(renderer.domElement);scene.add(root);scene.add(new THREE.HemisphereLight(0xffffff,0x466377,2.5));const light=new THREE.DirectionalLight(0xffffff,3);light.position.set(3,7,5);scene.add(light);const grid=new THREE.GridHelper(6,32);scene.add(grid);const box=new THREE.BoxHelper(root,0x238acf);box.visible=false;scene.add(box);
   controls.enableDamping=true;controls.dampingFactor=.1;
   const fitModel=()=>{const bounds=new THREE.Box3().setFromObject(root),center=bounds.getCenter(new THREE.Vector3()),size=bounds.getSize(new THREE.Vector3()),distance=Math.max(.01,size.x,size.y,size.z)*2.15;controls.target.copy(center);camera.position.copy(center).add(new THREE.Vector3(distance*.9,distance*.75,distance*1.15));camera.near=Math.max(.0001,distance/1000);camera.far=Math.max(50,distance*20);camera.updateProjectionMatrix();controls.update();};fit.current=fitModel;fitModel();
   const resize=()=>{const width=Math.max(1,host.clientWidth),height=Math.max(1,host.clientHeight);renderer.setSize(width,height,false);camera.aspect=width/height;camera.updateProjectionMatrix();};const ro=new ResizeObserver(resize);ro.observe(host);resize();
   let frame=0,inView=true,last=performance.now(),statsAt=0,lost=false;const smooth=new Map<string,number>();
   const choose=(node:Object3D)=>{const path=paths.get(node);if(!active||!path)return;setChosen(path);if(current.current.enabled)current.current.onSelect?.(path);};pick.current=path=>{const node=resolve(path);if(node)choose(node);};
   const apply=()=>{
    const c=current.current,delta=Math.min(.1,Math.max(0,(performance.now()-last)/1000));last=performance.now();
    root.traverse(node=>{const base=originals.get(node)!;node.position.copy(base.position);node.rotation.copy(base.rotation);node.scale.copy(base.scale);node.visible=base.visible;const mesh=node as Mesh;if(mesh.isMesh)for(const m of Array.isArray(mesh.material)?mesh.material:[mesh.material]){const original=materials.get(m);if(original)m.copy(original);}});
    for(const layer of c.layers){const targets=layer.nodes.map(resolve).filter((n):n is Object3D=>!!n);for(const node of targets){node.visible=layer.visible;node.traverse(child=>{const mesh=child as Mesh;if(!mesh.isMesh)return;for(const m of Array.isArray(mesh.material)?mesh.material:[mesh.material]){m.opacity=layer.opacity;m.transparent=layer.opacity<1;if("wireframe" in m)m.wireframe=layer.wireframe;if(layer.color&&"color" in m)(m.color as Color).set(layer.color);}});}}
    for(const mapping of c.config.mappings){if(!mapping.enabled)continue;const node=resolve(mapping.node),value=sceneMappingValue(mapping,c.asset,c.sample,c.config.sampleAssetField);if(!node||!value){smooth.delete(mapping.id);continue;}const prior=smooth.get(mapping.id),response=mapping.smooth??.12,interpolated=prior===undefined?value.value:prior+(value.value-prior)*(1-Math.exp(-delta/response));smooth.set(mapping.id,interpolated);const base=originals.get(node)!;
     if(mapping.mode==="position")node.position[mapping.axis]=base.position[mapping.axis]+interpolated;else if(mapping.mode==="rotation")node.rotation[mapping.axis]=base.rotation[mapping.axis]+interpolated;else if(mapping.mode==="scale")node.scale[mapping.axis]=Math.max(.001,interpolated);else if(mapping.mode==="visibility")node.visible=mapping.threshold===undefined?interpolated>=.5:value.raw>mapping.threshold;else {const color=new THREE.Color(mapping.colorLow??"#1abb7f").lerp(new THREE.Color(mapping.colorHigh??"#e65b43"),mapping.threshold===undefined?value.normalised:value.raw>mapping.threshold?1:0);node.traverse(child=>{const mesh=child as Mesh;if(mesh.isMesh)for(const m of Array.isArray(mesh.material)?mesh.material:[mesh.material])if("color" in m)(m.color as Color).copy(color);});}
    }
    const selectedNode=c.chosen?resolve(c.chosen):undefined;root.traverse(node=>{const mesh=node as Mesh;if(!mesh.isMesh)return;if(c.explode){const dir=originals.get(node)!.position.clone();if(dir.lengthSq()<.001)dir.set(.2,.15,.2);mesh.position.add(dir.normalize().multiplyScalar(c.explode*.32));}if(c.isolate&&selectedNode&&node!==selectedNode&&!selectedNode.getObjectById(node.id)&&!node.getObjectById(selectedNode.id))for(const m of Array.isArray(mesh.material)?mesh.material:[mesh.material]){m.opacity=.12;m.transparent=true;}});
    box.visible=!!selectedNode;if(selectedNode)box.setFromObject(selectedNode);grid.visible=c.config.showGrid;scene.background=new THREE.Color(c.config.background==="dark"?0x101d2b:0xe9f0f5);renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,c.config.quality==="high"?2:c.config.quality==="performance"?1:1.5));
   };
   const render=()=>{if(!active||!inView||lost)return;try{apply();controls.update();renderer.render(scene,camera);if(performance.now()-statsAt>1000){statsAt=performance.now();setStats({meshes,triangles:renderer.info.render.triangles});}}catch{lost=true;setState("error");setError("The model could not be rendered.");return;}frame=requestAnimationFrame(render);};frame=requestAnimationFrame(render);
   const io=new IntersectionObserver(entries=>{inView=entries[0]?.isIntersecting??true;cancelAnimationFrame(frame);if(inView&&active&&!lost){last=performance.now();frame=requestAnimationFrame(render);}},{threshold:.01});io.observe(host);
   const ray=new THREE.Raycaster(),mouse=new THREE.Vector2();let down:{x:number;y:number}|undefined;
   const onDown=(e:PointerEvent)=>{down={x:e.clientX,y:e.clientY};},onUp=(e:PointerEvent)=>{if(!down||Math.hypot(e.clientX-down.x,e.clientY-down.y)>5)return;const rect=renderer.domElement.getBoundingClientRect();mouse.set((e.clientX-rect.left)/rect.width*2-1,-((e.clientY-rect.top)/rect.height)*2+1);ray.setFromCamera(mouse,camera);const hit=ray.intersectObject(root,true).find(h=>h.object.visible);let node=hit?.object;while(node&&!node.name)node=node.parent??undefined;if(node)choose(node);down=undefined;},onLost=(e:Event)=>{e.preventDefault();lost=true;cancelAnimationFrame(frame);setState("error");setError("WebGL context was lost. Reload the model.");};
   renderer.domElement.addEventListener("pointerdown",onDown);renderer.domElement.addEventListener("pointerup",onUp);renderer.domElement.addEventListener("webglcontextlost",onLost);
   cleanup=()=>{cancelAnimationFrame(frame);ro.disconnect();io.disconnect();renderer.domElement.removeEventListener("pointerdown",onDown);renderer.domElement.removeEventListener("pointerup",onUp);renderer.domElement.removeEventListener("webglcontextlost",onLost);controls.dispose();box.geometry.dispose();(box.material as Material).dispose();grid.geometry.dispose();for(const m of Array.isArray(grid.material)?grid.material:[grid.material])m.dispose();disposeModel(root);for(const m of materials.values())m.dispose();renderer.dispose();renderer.forceContextLoss();renderer.domElement.remove();fit.current=undefined;pick.current=undefined;};
   setParts(partList);setState("ready");
  }catch(failure){if(cleanup)cleanup();else {if(loaded)disposeModel(loaded);for(const m of orphanedMaterials)m.dispose();}cleanup=undefined;if(active){setState("error");const known=new Set(["The model is not a bounded self-contained GLB.","The original model hash is unavailable.","The model bytes do not match the original attachment hash.","The model requested a resource outside its attachment.","A configured model part is missing or ambiguous."]);setError(failure instanceof Error&&known.has(failure.message)?failure.message:"The model could not be rendered. WebGL2 support is required.");}}})();
  return()=>{active=false;cleanup?.();};
 },[scope,blob,attachment.id,attachment.hash,metadataError,valid,supported,targetValid]);
 if(!targetValid)return <p role="alert">{t("The model attachment does not belong to this asset.")}</p>;
 const failure=metadataError??(!valid?"The scene layers or field mappings are incompatible.":!supported?"Select an original GLB attachment.":!targetValid?"The model attachment does not belong to this asset.":error);
 return <section aria-label={t("3D scene")} className="grid min-w-0 grid-cols-1 gap-2"><p className="break-all text-xs text-muted">{attachment.name} · {attachment.id} · {asset.record.id}</p><div className="flex flex-wrap items-center gap-1"><Button size="sm" disabled={state!=="ready"||!!failure} onClick={()=>fit.current?.()}>{t("Fit model")}</Button><Button size="sm" aria-pressed={isolate} disabled={!chosen||state!=="ready"} onClick={()=>setIsolate(!isolate)}>{t("Isolate part")}</Button><label className="flex gap-2 text-xs">{t("Explode model")}<Input className="w-28" type="range" min={0} max={1} step={.01} value={explode} onChange={e=>setExplode(Number(e.target.value))}/></label></div>{failure&&<p role="alert">{t(failure)}</p>}{state==="loading"&&!failure&&<p role="status">{t("Loading authorized 3D model…")}</p>}
 <div ref={canvas} className="h-80 min-w-0 overflow-hidden rounded border border-border" aria-label={t("3D model canvas")}/>{stats&&state==="ready"&&<p role="status" className="text-xs text-muted">{t("{meshes} model meshes · {triangles} rendered triangles",stats)}</p>}
 <div className="flex flex-wrap gap-1">{(["parts","layers","bindings"] as const).map(name=><Button key={name} size="sm" aria-pressed={tab===name} onClick={()=>setTab(name)}>{t({parts:"Model parts",layers:"Model layers",bindings:"Field mappings"}[name])}</Button>)}</div>
 {tab==="parts"&&<div className="grid max-h-60 gap-1 overflow-auto">{parts.map(p=><Button key={p.path} size="sm" aria-pressed={chosen===p.path} onClick={()=>pick.current?.(p.path)} className="justify-start"><span style={{paddingInlineStart:p.depth*8}}>{p.name}</span></Button>)}</div>}
 {tab==="layers"&&layers.map(l=><div key={l.id} className="flex flex-wrap items-center gap-2"><Button size="sm" aria-pressed={l.visible} onClick={()=>setLayers(old=>old.map(x=>x.id===l.id?{...x,visible:!x.visible}:x))}>{l.name}</Button><label className="flex gap-1 text-xs">{t("Layer opacity")}<Input className="w-28" type="range" min={0} max={1} step={.05} value={l.opacity} onChange={e=>setLayers(old=>old.map(x=>x.id===l.id?{...x,opacity:Number(e.target.value)}:x))}/></label><Button size="sm" aria-pressed={l.wireframe} onClick={()=>setLayers(old=>old.map(x=>x.id===l.id?{...x,wireframe:!x.wireframe}:x))}>{t("Wireframe")}</Button></div>)}
 {tab==="bindings"&&config.mappings.map(m=>{const v=sceneMappingValue(m,asset,sample,config.sampleAssetField);return <p key={m.id} className="break-words text-xs">{m.node} · {m.source} / {m.field} · {m.mode} / {m.axis} · {v?.raw??t("No readable mapped value")}</p>;})}</section>;
}
