import {expect,test} from "@playwright/test";
import {decide,fresh,open,pageUIProfile} from "./host";

test("an authored application record shares authorized selection across pages and retires instances",async({page,request},info)=>{
 test.setTimeout(60_000);
 const name=fresh("apprecord").replace(/[^a-z0-9]/gi,"").toLowerCase(),type=`build.${name}`,object=fresh("OBJ"),app=fresh("APP"),first=fresh("PAGE"),second=fresh("PAGE"),ref={app:"build",kind:"object",name:type},application=`build:${name}app`;
 await decide(request,"manager","build","build.object.create",{type:"build.object",id:object},{name,title:"Shared record notes",states:[{name:"open",title:"Open"},{name:"done",title:"Done"}],actions:[{name:"close",title:"Finish shared note",from:["open"],to:"done"}],fields:[{name:"note",title:"Note",type:"text"},{name:"active",title:"Active",type:"boolean"}]});await decide(request,"manager","build","build.object.publish",{type:"build.object",id:object},{});
 for(const suffix of ["A","B"])await decide(request,"desk","build",`${type}.create`,{type,id:`${name}${suffix}`},{note:`RECORD-${suffix}`,active:suffix==="A"});
 const sections=(bound=false)=>[{id:"filter",widget:"filter",configVersion:1,title:"Producer filter",fields:["active"]},{id:"table",widget:"table",configVersion:1,title:"Record choices",fields:["note"],...(bound?{selectionVariable:"selected"}:{})},{id:"detail",widget:"detail",configVersion:1,title:"Shared record",fields:["note"],...(bound?{recordVariable:"selected"}:{})},{id:"actions",widget:"actions",configVersion:1,title:"Shared work",actions:[`${type}.close`],...(bound?{recordVariable:"selected"}:{})},{id:"next",widget:"button",configVersion:1,title:"Next record page"}];
 const document=(target:string,bound=false)=>({formatVersion:2,uiProfile:pageUIProfile,root:"root",nodes:{root:{kind:"rows",children:["filter","table","detail","actions","next"]},filter:{kind:"widget",section:"filter"},table:{kind:"widget",section:"table"},detail:{kind:"widget",section:"detail"},actions:{kind:"widget",section:"actions"},next:{kind:"widget",section:"next"}},variables:{selected:bound?{title:"Selected note",scope:"application",type:"record",mode:"shared",writable:true,source:{kind:"application",variable:"selected",object:ref}}:{title:"Selected note",scope:"page",type:"string",mode:"state",initial:""}},events:[{source:"next",event:"click",effects:[{kind:"navigate", navigate:{page:{app:"build",kind:"page",name:target},interfaceVersion:0}}]}]});
 for(const [id,suffix,title] of [[first,"first","Record first"],[second,"second","Record second"]]){await decide(request,"manager","build","build.page.create",{type:"build.page",id},{name:`${name}${suffix}`,title,object:type,sections:sections(),document:document(`${name}${suffix}`)});await decide(request,"manager","build","build.page.publish",{type:"build.page",id},{});}
 await decide(request,"manager","build","build.app.create",{type:"build.app",id:app},{name:`${name}app`,title:"Record desk",pages:[`${name}first`,`${name}second`],uiProfile:pageUIProfile,variables:{selected:{title:"Selected note",scope:"application",type:"string",mode:"state",initial:""}}});await decide(request,"manager","build","build.app.publish",{type:"build.app",id:app},{});
 await open(page,"manager",`/application?id=${app}`);await page.getByRole("combobox",{name:"Choose application variable",exact:true}).selectOption("selected");await page.getByRole("combobox",{name:"Variable mode",exact:true}).selectOption("resource");await page.getByRole("combobox",{name:"Resource output kind",exact:true}).selectOption("record");await page.getByRole("combobox",{name:"Selection object",exact:true}).selectOption(type);await page.getByRole("button",{name:"Save application",exact:true}).click();await expect(page.getByRole("button",{name:"Save application",exact:true})).toBeDisabled();await decide(request,"manager","build","build.app.publish",{type:"build.app",id:app},{});
 await open(page,"manager",`/compose?id=${first}`);const tree=page.getByRole("region",{name:"Widgets and layout",exact:true}),inspector=page.getByRole("region",{name:"The widget in hand",exact:true});await tree.getByRole("button",{name:"Page variables",exact:true}).click();await inspector.getByRole("combobox",{name:"Choose page variable",exact:true}).selectOption("selected");await inspector.getByRole("combobox",{name:"Variable mode",exact:true}).selectOption("shared");await inspector.getByRole("combobox",{name:"Application variable",exact:true}).selectOption("selected");await expect(inspector.getByRole("combobox",{name:"Application variable",exact:true}).locator("option[value=selected]")).toContainText("Record selection");const update=inspector.getByRole("button",{name:"Update shared binding",exact:true});if(await update.isVisible())await update.click();await expect(inspector.getByRole("combobox",{name:"Value type",exact:true})).toHaveValue("record");
 await tree.getByRole("button",{name:"Record choices",exact:true}).click();await inspector.getByRole("combobox",{name:"Shared record selection",exact:true}).selectOption("selected");await tree.getByRole("button",{name:"Shared record",exact:true}).click();await inspector.getByRole("combobox",{name:"Input record binding",exact:true}).selectOption("selected");await page.getByRole("button",{name:"Save",exact:true}).click();await expect(page.getByRole("button",{name:"Save",exact:true})).toBeDisabled();await page.getByRole("button",{name:"Direct install",exact:true}).click();
 await decide(request,"manager","build","build.page.edit",{type:"build.page",id:first},{sections:sections(true),document:document(`${name}second`,true)});await decide(request,"manager","build","build.page.publish",{type:"build.page",id:first},{});await decide(request,"manager","build","build.page.edit",{type:"build.page",id:second},{sections:sections(true),document:document(`${name}first`,true)});await decide(request,"manager","build","build.page.publish",{type:"build.page",id:second},{});
 await open(page,"manager",`/application?id=${app}`);await page.getByRole("button",{name:"Review application release",exact:true}).click();await page.getByRole("button",{name:"Check draft and dependencies",exact:true}).click();await page.getByRole("button",{name:"Save immutable candidate",exact:true}).click();await decide(request,"manager","build","build.app.edit",{type:"build.app",id:app},{variables:{}});await page.getByRole("button",{name:"Activate release",exact:true}).click();
 const operation=await page.context().newPage(),route=`/page?app=build&kind=page&name=${name}first&application=${application}&instance=main`;await open(operation,"desk",route);const table=operation.getByRole("table"),detail=operation.getByRole("heading",{name:"Shared record",exact:true}).locator(".."),filter=operation.getByRole("search",{name:"Producer filter",exact:true}).getByRole("combobox",{name:"Active",exact:true});
 await table.getByRole("row").filter({hasText:"RECORD-A"}).click();await expect(detail.getByText("RECORD-A",{exact:true})).toBeVisible();await operation.getByRole("button",{name:"Next record page",exact:true}).click();await expect(operation.getByRole("heading",{name:"Record second",exact:true})).toBeVisible();await expect(detail.getByText("RECORD-A",{exact:true})).toBeVisible();await table.getByRole("row").filter({hasText:"RECORD-B"}).click();await expect(detail.getByText("RECORD-B",{exact:true})).toBeVisible();await operation.getByRole("button",{name:"Next record page",exact:true}).click();await expect(detail.getByText("RECORD-B",{exact:true})).toBeVisible();
 // An obsolete producer's filter must not clear another page's newer selection.
 await filter.selectOption("true");await expect(table.getByText("RECORD-B",{exact:true})).toHaveCount(0);await expect(detail.getByText("RECORD-B",{exact:true})).toBeVisible();await table.getByRole("row").filter({hasText:"RECORD-A"}).click();await expect(detail.getByText("RECORD-A",{exact:true})).toBeVisible();await filter.selectOption("false");await expect(detail.getByText("Select a record to see it here.",{exact:true})).toBeVisible();await filter.selectOption("");await expect(table.getByText("RECORD-A",{exact:true})).toBeVisible();
 await table.getByRole("row").filter({hasText:"RECORD-B"}).click();await expect(detail.getByText("RECORD-B",{exact:true})).toBeVisible();await operation.getByRole("button",{name:"Finish shared note",exact:true}).click();await expect.poll(async()=>(await(await request.get(`/v1/records/${type}/${name}B`,{headers:{Authorization:"Bearer desk"}})).json()).record.state).toBe("done");await expect(detail.getByText("RECORD-B",{exact:true})).toBeVisible();if(process.env.PLATFORM_SCREENSHOTS)await operation.screenshot({path:info.outputPath("application-record-shared.png"),fullPage:true});
 await operation.getByRole("button",{name:"New application instance",exact:true}).click();await expect(detail.getByText("Select a record to see it here.",{exact:true})).toBeVisible();await operation.evaluate(route=>{location.hash=route},route);await expect(detail.getByText("RECORD-B",{exact:true})).toBeVisible();await operation.getByRole("button",{name:"Close application instance",exact:true}).click();await operation.evaluate(route=>{location.hash=route},route);await expect(detail.getByText("Select a record to see it here.",{exact:true})).toBeVisible();
 await table.getByRole("row").filter({hasText:"RECORD-B"}).click();await expect(detail.getByText("RECORD-B",{exact:true})).toBeVisible();await operation.route(`**/v1/records/${type}/${name}A`,r=>r.fulfill({status:403,contentType:"application/json",body:JSON.stringify({error:{message:"Denied"}})}));await table.getByRole("row").filter({hasText:"RECORD-A"}).click();await expect(operation.getByRole("alert").filter({hasText:"Resource read failed"})).toBeVisible();await expect(detail.getByText("Select a record to see it here.",{exact:true})).toBeVisible();await operation.unroute(`**/v1/records/${type}/${name}A`);
 let release!:()=>void,held=false;const wait=new Promise<void>(resolve=>release=resolve);await operation.route(`**/v1/records/${type}/${name}A`,async r=>{if(!held){const response=await r.fetch();held=true;await wait;await r.fulfill({response});}else await r.continue();});await table.getByRole("row").filter({hasText:"RECORD-A"}).click();await expect.poll(()=>held).toBe(true);await operation.getByRole("button",{name:"Close application instance",exact:true}).click();await operation.evaluate(route=>{location.hash=route},route);release();await expect(detail.getByText("Select a record to see it here.",{exact:true})).toBeVisible();await operation.unroute(`**/v1/records/${type}/${name}A`);
 if(process.env.PLATFORM_SCREENSHOTS){await expect(table.getByText("RECORD-A",{exact:true})).toBeVisible();await operation.setViewportSize({width:390,height:844});await operation.evaluate(()=>new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve()))));await operation.screenshot({path:info.outputPath("application-record-shared-narrow.png"),fullPage:true});}await operation.reload();await expect(detail.getByText("Select a record to see it here.",{exact:true})).toBeVisible();
 await table.getByRole("row").filter({hasText:"RECORD-B"}).click();await expect(detail.getByText("RECORD-B",{exact:true})).toBeVisible();await operation.getByRole("button",{name:/desk-1/}).click();await operation.getByRole("menuitemradio",{name:/manager-1/}).click();await operation.evaluate(route=>{location.hash=route},route);await expect(detail.getByText("Select a record to see it here.",{exact:true})).toBeVisible();await table.getByRole("row").filter({hasText:"RECORD-B"}).click();await expect(detail.getByText("RECORD-B",{exact:true})).toBeVisible();
 await decide(request,"manager","build","build.app.edit",{type:"build.app",id:app},{title:"Record desk revised",variables:{selected:{title:"Selected note",scope:"application",type:"record",mode:"resource",source:{kind:"record",object:ref}}}});await operation.evaluate(id=>{location.hash=`/application?id=${id}`},app);await operation.getByRole("button",{name:"Review application release",exact:true}).click();await operation.getByRole("button",{name:"Check draft and dependencies",exact:true}).click();await operation.getByRole("button",{name:"Save immutable candidate",exact:true}).click();await operation.getByRole("button",{name:"Activate release",exact:true}).click();await operation.evaluate(route=>{location.hash=route},route);await expect(detail.getByText("Select a record to see it here.",{exact:true})).toBeVisible();

});
