import {expect,test} from "@playwright/test";
import {decide,fresh,open,pageUIProfile} from "./host";

test("an authored application query shares one read across pages and isolates and retires explicit instances",async({page,request},testInfo)=>{
 test.setTimeout(60_000);
 const name=fresh("appquery").replace(/[^a-z0-9]/gi,"").toLowerCase(),type=`build.${name}`,object=fresh("OBJ"),app=fresh("APP"),first=fresh("PAGE"),second=fresh("PAGE"),application=`build:${name}app`;
 await decide(request,"manager","build","build.object.create",{type:"build.object",id:object},{name,title:"Application query notes",fields:[{name:"note",title:"Note",type:"text"},{name:"bucket",title:"Bucket",type:"text"}]});
 await decide(request,"manager","build","build.object.publish",{type:"build.object",id:object},{});
 for(const [suffix,bucket] of [["A1","A"],["A2","A"],["A3","A"],["B","B"]])await decide(request,"desk","build",`${type}.create`,{type,id:`${name}${suffix}`},{note:`APP-${suffix}`,bucket});
 const document=(target:string,shared=false)=>({formatVersion:2,uiProfile:pageUIProfile,root:"root",nodes:{root:{kind:"rows",children:["input","table","detail","next"]},input:{kind:"widget",section:"input",valueVariable:"bucket"},table:{kind:"widget",section:"table"},detail:{kind:"widget",section:"detail"},next:{kind:"widget",section:"next"}},variables:{bucket:shared?{scope:"application",type:"string",mode:"shared",writable:true,source:{kind:"application",variable:"bucket"}}:{scope:"page",type:"string",mode:"state",initial:"A"}},events:[{source:"next",event:"click",target:"",navigate:{page:{app:"build",kind:"page",name:target},interfaceVersion:0}}]});
 for(const [id,suffix,title] of [[first,"first","Query first"],[second,"second","Query second"]]){await decide(request,"manager","build","build.page.create",{type:"build.page",id},{name:`${name}${suffix}`,title,object:type,sections:[{id:"input",widget:"input",configVersion:1,title:"Shared bucket"},{id:"table",widget:"table",configVersion:1,title:"Application window",fields:["note","bucket"]},{id:"detail",widget:"detail",configVersion:1,title:"Page selected record",fields:["note"]},{id:"next",widget:"button",configVersion:1,title:"Next query page"}],document:document(`${name}${suffix}`)});await decide(request,"manager","build","build.page.publish",{type:"build.page",id},{});}
 await decide(request,"manager","build","build.app.create",{type:"build.app",id:app},{name:`${name}app`,title:"Query application",pages:[`${name}first`,`${name}second`],uiProfile:pageUIProfile,variables:{bucket:{title:"Application bucket",scope:"application",type:"string",mode:"state",initial:"A"}}});
 await open(page,"manager",`/application?id=${app}`);
 await page.getByRole("button",{name:"Add query plan",exact:true}).click();await page.getByRole("combobox",{name:"Query object",exact:true}).selectOption(type);await page.getByLabel("Query title",{exact:true}).fill("Shared application query");await page.getByLabel("Query window limit",{exact:true}).fill("2");await page.getByRole("button",{name:"Add query condition",exact:true}).click();await page.getByRole("combobox",{name:"Query condition field",exact:true}).selectOption("bucket");await page.getByRole("combobox",{name:"Query condition value",exact:true}).selectOption("bucket");
 await page.getByRole("button",{name:"Save application",exact:true}).click();await expect(page.getByRole("button",{name:"Save application",exact:true})).toBeDisabled();
 const savedApp=(await(await request.get(`/v1/records/build.app/${app}`,{headers:{Authorization:"Bearer manager"}})).json()).record,resourceID=Object.entries(savedApp.variables).find(([,v]:any)=>v.source?.kind==="plan")![0];
 await decide(request,"manager","build","build.app.publish",{type:"build.app",id:app},{});
 for(const [id,target] of [[first,`${name}second`],[second,`${name}first`]]){
  await decide(request,"manager","build","build.page.edit",{type:"build.page",id},{document:document(target,true)});
  await open(page,"manager",`/compose?id=${id}`);const tree=page.getByRole("region",{name:"Widgets and layout",exact:true}),inspector=page.getByRole("region",{name:"The widget in hand",exact:true});
  await tree.getByRole("button",{name:"Page variables",exact:true}).click();await inspector.getByRole("button",{name:"Add variable",exact:true}).click();await inspector.getByLabel("Variable label",{exact:true}).fill("Shared dataset");await inspector.getByRole("combobox",{name:"Variable mode",exact:true}).selectOption("shared");await inspector.getByRole("combobox",{name:"Application variable",exact:true}).selectOption(resourceID);
  await tree.getByRole("button",{name:"Application window",exact:true}).click();await inspector.getByRole("combobox",{name:"Table query window",exact:true}).selectOption({label:"Shared dataset"});await page.getByRole("button",{name:"Save",exact:true}).click();await expect(page.getByRole("button",{name:"Save",exact:true})).toBeDisabled();if(id===second){const saved=(await(await request.get(`/v1/records/build.page/${id}`,{headers:{Authorization:"Bearer manager"}})).json()).record;const collection=Object.entries(saved.document.variables).find(([,v]:any)=>v.type==="object-set")![0];saved.document.nodes.root.children.push("cards");Object.assign(saved.document.nodes,{cards:{kind:"loop",title:"Application cards",children:["card"],loop:{collection,itemVariable:"item",limit:2}},card:{kind:"widget",section:"card"}});saved.document.variables.item={scope:"loop-item",owner:"cards",type:"record",mode:"resource",source:{kind:"item",node:"cards"}};saved.sections.push({id:"card",widget:"detail",configVersion:1,title:"Application card",fields:["note"],recordVariable:"item"});await decide(request,"manager","build","build.page.edit",{type:"build.page",id},{document:saved.document,sections:saved.sections});}
  await decide(request,"manager","build","build.page.publish",{type:"build.page",id},{});
 }
 await open(page,"manager",`/application?id=${app}`);await page.getByRole("button",{name:"Review application release",exact:true}).click();await page.getByRole("button",{name:"Check draft and dependencies",exact:true}).click();await page.getByRole("button",{name:"Save immutable candidate",exact:true}).click();
 const changed=structuredClone(savedApp.queries);Object.values(changed).forEach((q:any)=>q.limit=1);await decide(request,"manager","build","build.app.edit",{type:"build.app",id:app},{queries:changed});await page.getByRole("button",{name:"Activate release",exact:true}).click();
 const operation=await page.context().newPage();let reads=0;operation.on("request",req=>{if(new URL(req.url()).pathname===`/v1/records/${type}`)reads++;});const route=`/page?app=build&kind=page&name=${name}first&application=${application}&instance=main`;
 await open(operation,"desk",route);const input=operation.getByRole("textbox",{name:"Shared bucket",exact:true}),table=operation.getByRole("table"),selected=operation.getByRole("heading",{name:"Page selected record",exact:true}).locator("..");
 await expect(table.getByText("APP-A1",{exact:true})).toBeVisible();await expect(table.getByText("APP-A2",{exact:true})).toBeVisible();expect(reads).toBe(1);
 await table.getByRole("row").filter({hasText:"APP-A1"}).click();await expect(selected.getByText("APP-A1",{exact:true})).toBeVisible();await operation.getByRole("button",{name:"Next page",exact:true}).click();await expect(table.getByText("APP-A3",{exact:true})).toBeVisible();await expect(selected.getByText("Select a record to see it here.",{exact:true})).toBeVisible();
 await operation.getByRole("button",{name:"Next query page",exact:true}).click();await expect(operation.getByRole("heading",{name:"Query second",exact:true})).toBeVisible();await expect(table.getByText("APP-A3",{exact:true})).toBeVisible();await expect(operation.getByRole("list",{name:"Application cards",exact:true}).getByText("APP-A3",{exact:true})).toBeVisible();expect(reads).toBe(2);
 await input.fill("B");await expect(table.getByText("APP-B",{exact:true})).toBeVisible();await operation.getByRole("button",{name:"Next query page",exact:true}).click();await expect(operation.getByRole("heading",{name:"Query first",exact:true})).toBeVisible();await expect(input).toHaveValue("B");await expect(table.getByText("APP-B",{exact:true})).toBeVisible();expect(reads).toBe(3);
 if(process.env.PLATFORM_SCREENSHOTS)await operation.screenshot({path:testInfo.outputPath("application-query-shared.png"),fullPage:true});
 await operation.getByRole("button",{name:"New application instance",exact:true}).click();await expect(input).toHaveValue("A");await expect(table.getByText("APP-A1",{exact:true})).toBeVisible();const otherRoute=new URL(operation.url()).hash.slice(1);
 await operation.evaluate(route=>{location.hash=route},route);await expect(input).toHaveValue("B");await expect(table.getByText("APP-B",{exact:true})).toBeVisible();
 let release!:()=>void,held=false;const wait=new Promise<void>(resolve=>release=resolve);
 await operation.route(`**/v1/records/${type}?*`,async r=>{const domain=new URL(r.request().url()).searchParams.get("domain")??"";if(domain.includes('"A"')&&!held){const response=await r.fetch();held=true;await wait;await r.fulfill({response});}else await r.continue();});
 await input.fill("A");await expect.poll(()=>held).toBe(true);await operation.getByRole("button",{name:"Close application instance",exact:true}).click();await operation.evaluate(route=>{location.hash=route},route);await expect(input).toHaveValue("A");release();await expect(table.getByText("APP-A1",{exact:true})).toBeVisible();await expect(table.getByText("APP-B",{exact:true})).toHaveCount(0);await operation.unroute(`**/v1/records/${type}?*`);
 await operation.evaluate(route=>{location.hash=route},otherRoute);await expect(input).toHaveValue("A");await expect(table.getByText("APP-A1",{exact:true})).toBeVisible();
 if(process.env.PLATFORM_SCREENSHOTS){await operation.setViewportSize({width:390,height:844});await operation.evaluate(()=>new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve()))));await operation.screenshot({path:testInfo.outputPath("application-query-shared-narrow.png"),fullPage:true});}
 await operation.reload();await expect(input).toHaveValue("A");await expect(table.getByText("APP-A1",{exact:true})).toBeVisible();
 await input.fill("B");await expect(table.getByText("APP-B",{exact:true})).toBeVisible();await operation.getByRole("button",{name:/desk-1/}).click();await operation.getByRole("menuitemradio",{name:/manager-1/}).click();await operation.evaluate(route=>{location.hash=route},route);await expect(input).toHaveValue("A");await expect(table.getByText("APP-A1",{exact:true})).toBeVisible();
 await input.fill("B");await expect(table.getByText("APP-B",{exact:true})).toBeVisible();await operation.evaluate(id=>{location.hash=`/application?id=${id}`},app);await operation.getByRole("button",{name:"Review application release",exact:true}).click();await operation.getByRole("button",{name:"Check draft and dependencies",exact:true}).click();await operation.getByRole("button",{name:"Save immutable candidate",exact:true}).click();await operation.getByRole("button",{name:"Activate release",exact:true}).click();await operation.evaluate(route=>{location.hash=route},route);await expect(input).toHaveValue("A");await expect(table.getByText("APP-A1",{exact:true})).toBeVisible();await expect(table.getByText("APP-A2",{exact:true})).toHaveCount(0);

});
