import {expect,test} from "@playwright/test";
import {decide,fresh,open,pageUIProfile} from "./host";

test("authored application filters share across pages while local and fixed query conditions remain independent",async({page,request},info)=>{
 test.setTimeout(60_000);
 const name=fresh("appfilter").replace(/[^a-z0-9]/gi,"").toLowerCase(),type=`build.${name}`,object=fresh("OBJ"),app=fresh("APP"),query=fresh("QUERY"),first=fresh("PAGE"),second=fresh("PAGE"),ref={app:"build",kind:"object",name:type},application=`build:${name}app`,queryName=`${name}fixed`;
 await decide(request,"manager","build","build.object.create",{type:"build.object",id:object},{name,title:"Filter notes",fields:[{name:"note",title:"Note",type:"text"},{name:"active",title:"Active",type:"boolean"},{name:"bucket",title:"Bucket",type:"choice",choices:"A,B"}]});await decide(request,"manager","build","build.object.publish",{type:"build.object",id:object},{});
 for(const [suffix,bucket,active] of [["A1","A",true],["A2","A",false],["B","B",false]])await decide(request,"desk","build",`${type}.create`,{type,id:`${name}${suffix}`},{note:`SHARED-${suffix}`,bucket,active});
 await decide(request,"manager","build","build.query.create",{type:"build.query",id:query},{name:queryName,title:"Fixed A",description:"Only A",object:type,domain:[["bucket","=","A"]],limit:20});await decide(request,"manager","build","build.query.publish",{type:"build.query",id:query},{});
 const sections=(bound=false)=>[{id:"filter",widget:"filter",configVersion:1,title:"Shared active",fields:["active"],...(bound?{filterVariable:"filter"}:{})},{id:"local",widget:"filter",configVersion:1,title:"Local bucket",fields:["bucket"]},{id:"table",widget:"table",configVersion:1,title:"Shared window",fields:["note"],query:`build.${queryName}`,...(bound?{filterVariable:"filter"}:{})},{id:"detail",widget:"detail",configVersion:1,title:"Selection",fields:["note"]},{id:"unbound",widget:"table",configVersion:1,title:"Local window",fields:["note"]},{id:"fixed",widget:"table",configVersion:1,title:"Plan stays fixed",fields:["note"],collectionVariable:"fixedWindow"},{id:"notice",widget:"text",configVersion:1,text:"Shared filter active"},{id:"next",widget:"button",configVersion:1,title:"Next filter page"}];
 const document=(target:string,bound=false)=>({formatVersion:2,uiProfile:pageUIProfile,root:"root",nodes:{root:{kind:"rows",children:["filter","local","table","detail","unbound","fixed","notice","next"]},filter:{kind:"widget",section:"filter"},local:{kind:"widget",section:"local"},table:{kind:"widget",section:"table"},detail:{kind:"widget",section:"detail"},unbound:{kind:"widget",section:"unbound"},fixed:{kind:"widget",section:"fixed"},notice:{kind:"widget",section:"notice",visibleWhen:"filtered"},next:{kind:"widget",section:"next"}},variables:{filter:bound?{title:"Application filter",scope:"application",type:"filter",mode:"shared",writable:true,source:{kind:"application",variable:"filter",object:ref}}:{title:"Application filter",scope:"page",type:"string",mode:"state",initial:""},filterOut:{scope:"page",type:"filter",mode:"resource",source:{kind:"filter",section:"filter"}},filtered:{scope:"page",type:"boolean",mode:"derived",expression:{op:"present",args:[{variable:"filterOut"}]}},fixedWindow:{scope:"page",type:"object-set",mode:"resource",source:{kind:"plan",query:"fixed"}}},queries:{fixed:{object:ref,limit:10,conditions:[{field:"bucket",op:"=",value:{literal:"B"}}]}},events:[{source:"next",event:"click",effects:[{kind:"navigate", navigate:{page:{app:"build",kind:"page",name:target},interfaceVersion:0}}]}]});
 for(const [id,suffix,title] of [[first,"first","Filter first"],[second,"second","Filter second"]]){await decide(request,"manager","build","build.page.create",{type:"build.page",id},{name:`${name}${suffix}`,title,object:type,sections:sections(),document:document(`${name}${suffix}`)});await decide(request,"manager","build","build.page.publish",{type:"build.page",id},{});}
 await decide(request,"manager","build","build.app.create",{type:"build.app",id:app},{name:`${name}app`,title:"Filter desk",pages:[`${name}first`,`${name}second`],uiProfile:pageUIProfile,variables:{filter:{title:"Application filter",scope:"application",type:"string",mode:"state",initial:""}}});await decide(request,"manager","build","build.app.publish",{type:"build.app",id:app},{});
 await open(page,"manager",`/application?id=${app}`);await page.getByRole("combobox",{name:"Choose application variable",exact:true}).selectOption("filter");await page.getByRole("combobox",{name:"Variable mode",exact:true}).selectOption("resource");await page.getByRole("combobox",{name:"Resource output kind",exact:true}).selectOption("filter");await page.getByRole("combobox",{name:"Filter object",exact:true}).selectOption(type);await page.getByRole("checkbox",{name:"Active",exact:true}).check();await page.getByRole("button",{name:"Save application",exact:true}).click();await expect(page.getByRole("button",{name:"Save application",exact:true})).toBeDisabled();await decide(request,"manager","build","build.app.publish",{type:"build.app",id:app},{});
 await open(page,"manager",`/compose?id=${first}`);const tree=page.getByRole("region",{name:"Widgets and layout",exact:true}),inspector=page.getByRole("region",{name:"The widget in hand",exact:true});await tree.getByRole("button",{name:"Page variables",exact:true}).click();await inspector.getByRole("combobox",{name:"Choose page variable",exact:true}).selectOption("filter");await inspector.getByRole("combobox",{name:"Variable mode",exact:true}).selectOption("shared");await expect(inspector.getByRole("option",{name:"Application filter · Filter values",exact:true})).toBeAttached();await inspector.getByRole("combobox",{name:"Application variable",exact:true}).selectOption("filter");await expect(inspector.getByRole("combobox",{name:"Value type",exact:true})).toHaveValue("filter");

 for(const title of ["Shared active","Shared window"]){await tree.getByRole("button",{name:title,exact:true}).click();await inspector.getByRole("combobox",{name:"Shared filter binding",exact:true}).selectOption("filter",{timeout:5000});}await page.getByRole("button",{name:"Save",exact:true}).click();await expect(page.getByRole("button",{name:"Save",exact:true})).toBeDisabled();await page.getByRole("button",{name:"Direct install",exact:true}).click();
 await decide(request,"manager","build","build.page.edit",{type:"build.page",id:first},{sections:sections(true),document:document(`${name}second`,true)});await decide(request,"manager","build","build.page.publish",{type:"build.page",id:first},{});await decide(request,"manager","build","build.page.edit",{type:"build.page",id:second},{sections:sections(true),document:document(`${name}first`,true)});await decide(request,"manager","build","build.page.publish",{type:"build.page",id:second},{});
 await open(page,"manager",`/application?id=${app}`);await page.getByRole("button",{name:"Review application release",exact:true}).click();await page.getByRole("button",{name:"Check draft and dependencies",exact:true}).click();await page.getByRole("button",{name:"Save immutable candidate",exact:true}).click();await decide(request,"manager","build","build.app.edit",{type:"build.app",id:app},{variables:{}});await page.getByRole("button",{name:"Activate release",exact:true}).click();
 const operation=await page.context().newPage(),route=`/page?app=build&kind=page&name=${name}first&application=${application}&instance=main`;await open(operation,"desk",route);const shared=operation.getByRole("search",{name:"Shared active",exact:true}).getByRole("combobox",{name:"Active",exact:true}),local=operation.getByRole("search",{name:"Local bucket",exact:true}).getByRole("combobox",{name:"Bucket",exact:true}),table=operation.getByRole("heading",{name:"Shared window",exact:true}).locator("..").getByRole("table"),unbound=operation.getByRole("heading",{name:"Local window",exact:true}).locator("..").getByRole("table"),fixed=operation.getByRole("heading",{name:"Plan stays fixed",exact:true}).locator("..").getByRole("table"),detail=operation.getByRole("heading",{name:"Selection",exact:true}).locator("..");
 await expect(table.getByText("SHARED-A1",{exact:true})).toBeVisible();await expect(table.getByText("SHARED-B",{exact:true})).toHaveCount(0);await shared.selectOption("true");await expect(table.getByText("SHARED-A2",{exact:true})).toHaveCount(0);await expect(operation.getByText("Shared filter active",{exact:true})).toBeVisible();await expect(unbound.getByText("SHARED-B",{exact:true})).toBeVisible();await expect(fixed.getByText("SHARED-B",{exact:true})).toBeVisible();
 await local.selectOption("B");await expect(table.getByText("SHARED-A1",{exact:true})).toHaveCount(0);await expect(unbound.getByText("SHARED-B",{exact:true})).toBeVisible();await operation.getByRole("button",{name:"Next filter page",exact:true}).click();await expect(operation.getByRole("heading",{name:"Filter second",exact:true})).toBeVisible();await expect(shared).toHaveValue("true");await expect(local).toHaveValue("");await expect(table.getByText("SHARED-A1",{exact:true})).toBeVisible();await shared.selectOption("false");await expect(table.getByText("SHARED-A2",{exact:true})).toBeVisible();await table.getByRole("row").filter({hasText:"SHARED-A2"}).click();await expect(detail.getByText("SHARED-A2",{exact:true})).toBeVisible();await shared.selectOption("true");await expect(table.getByText("SHARED-A1",{exact:true})).toBeVisible();await expect(detail.getByText("Select a record to see it here.",{exact:true})).toBeVisible();
 if(process.env.PLATFORM_SCREENSHOTS)await operation.screenshot({path:info.outputPath("application-filter-shared.png"),fullPage:true});await operation.getByRole("button",{name:"New application instance",exact:true}).click();await expect(shared).toHaveValue("");await expect(table.getByText("SHARED-A2",{exact:true})).toBeVisible();await operation.evaluate(route=>{location.hash=route},route);await expect(shared).toHaveValue("true");await expect(local).toHaveValue("B");await local.selectOption("");await expect(table.getByText("SHARED-A1",{exact:true})).toBeVisible();
 let release!:()=>void,held=false;const wait=new Promise<void>(resolve=>release=resolve);await operation.route(`**/v1/records/${type}?*`,async r=>{const domain=new URL(r.request().url()).searchParams.get("domain")??"";if(domain.includes('"A"')&&domain.includes('false')&&!held){const response=await r.fetch();held=true;await wait;await r.fulfill({response});}else await r.continue();});await shared.selectOption("false");await expect.poll(()=>held).toBe(true);await operation.getByRole("button",{name:"Close application instance",exact:true}).click();await operation.evaluate(route=>{location.hash=route},route);release();await expect(shared).toHaveValue("");await expect(local).toHaveValue("");await expect(table.getByText("SHARED-A1",{exact:true})).toBeVisible();await expect(table.getByText("SHARED-A2",{exact:true})).toBeVisible();await operation.unroute(`**/v1/records/${type}?*`);
 if(process.env.PLATFORM_SCREENSHOTS){await operation.setViewportSize({width:390,height:844});await operation.evaluate(()=>new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve()))));await operation.screenshot({path:info.outputPath("application-filter-shared-narrow.png"),fullPage:true});}await shared.selectOption("true");await expect(table.getByText("SHARED-A2",{exact:true})).toHaveCount(0);await operation.reload();await expect(shared).toHaveValue("");await expect(table.getByText("SHARED-A2",{exact:true})).toBeVisible();
 await shared.selectOption("true");await operation.getByRole("button",{name:/desk-1/}).click();await operation.getByRole("menuitemradio",{name:/manager-1/}).click();await operation.evaluate(route=>{location.hash=route},route);await expect(shared).toHaveValue("");await shared.selectOption("false");
 await decide(request,"manager","build","build.app.edit",{type:"build.app",id:app},{title:"Filter desk revised",variables:{filter:{title:"Application filter",scope:"application",type:"filter",mode:"resource",source:{kind:"filter",object:ref,fields:["active"]}}}});await operation.evaluate(id=>{location.hash=`/application?id=${id}`},app);await operation.getByRole("button",{name:"Review application release",exact:true}).click();await operation.getByRole("button",{name:"Check draft and dependencies",exact:true}).click();await operation.getByRole("button",{name:"Save immutable candidate",exact:true}).click();await operation.getByRole("button",{name:"Activate release",exact:true}).click();await operation.evaluate(route=>{location.hash=route},route);await expect(shared).toHaveValue("");await expect(table.getByText("SHARED-A1",{exact:true})).toBeVisible();await expect(table.getByText("SHARED-A2",{exact:true})).toBeVisible();
});
