import { expect, test } from "@playwright/test";
import { decide, fresh, open } from "./host";

test("a delivered application opens an original failed workflow, retains its startup release and resumes through the original control",async({page,request})=>{
 test.setTimeout(90000);
 const stamp=fresh("diagnose").replace(/[^a-z0-9]/gi,"").toLowerCase(),appName=`${stamp}app`,type=`build.${stamp}`,object=fresh("OBJ"),process=fresh("FLOW"),application=fresh("APP"),pageID=fresh("PAGE"),headers={Authorization:"Bearer manager"};
 await decide(request,"manager","build","build.object.create",{type:"build.object",id:object},{name:stamp,title:"Diagnostic notes",fields:[{name:"note",title:"Note",type:"text"}],states:[{name:"open",title:"Open"},{name:"ready",title:"Ready"},{name:"done",title:"Done"}],actions:[{name:"ready",title:"Prepare",from:["open"],to:"ready"},{name:"close",title:"Close",from:["ready"],to:"done"}]});
 await decide(request,"manager","build","build.object.publish",{type:"build.object",id:object},{});
 await decide(request,"manager","build","build.page.create",{type:"build.page",id:pageID},{name:stamp,title:"Diagnostic notes",object:type,sections:[{id:"table",widget:"table",configVersion:1,fields:["note"]}]});
 await decide(request,"manager","build","build.page.publish",{type:"build.page",id:pageID},{});
 await decide(request,"manager","build","build.process.create",{type:"build.process",id:process},{name:stamp,title:"Original failed workflow",object:type,manual:true,steps:[{name:"blocked",kind:"action",title:"Original blocked action",act:`${type}.close`,target:{source:"literal",value:"R2"},next:"finish"},{name:"finish",kind:"end"}]});
 await decide(request,"manager","build","build.process.publish",{type:"build.process",id:process},{});
 await decide(request,"manager","build","build.app.create",{type:"build.app",id:application},{name:appName,title:"Diagnostic application",pages:[stamp],resources:[{app:"build",kind:"flow",name:`build.${stamp}`}]});
 await decide(request,"manager","build","build.app.publish",{type:"build.app",id:application},{});
 await open(page,"manager",`/release-review?kind=app&id=${application}`);
 await page.getByRole("button",{name:"Check draft and dependencies",exact:true}).click();
 const release=await page.getByText("Draft candidate:").locator("code").textContent();expect(release).toBeTruthy();
 await page.getByRole("button",{name:"Save immutable candidate",exact:true}).click();await page.getByRole("button",{name:"Activate release",exact:true}).click();await expect(page.getByText("Release active for operators.",{exact:false})).toBeVisible();
 await decide(request,"manager","build",`${type}.create`,{type,id:"R1"},{note:"Needs preparation"});
 await decide(request,"manager","build","build.process.run",{type:"build.process",id:process},{key:"R1"});
 let instance:any;
 await expect.poll(async()=>{const result=await(await request.get("/v1/records/flow.instance?limit=500",{headers})).json();instance=result.records.find((row:any)=>row.flow===`build.${stamp}`);return instance?.tokens?.some((token:any)=>!!token.error);},{timeout:15000}).toBe(true);
 expect(instance.release).toBe(release);expect(instance.version).toBe(1);
 // A later saved source must not masquerade as the old run's startup version.
 await decide(request,"manager","build","build.process.edit",{type:"build.process",id:process},{title:"Current saved editor source"});
 await open(page,"manager",`/application?id=${application}`);await page.getByRole("button",{name:"Application runs",exact:true}).click();
 await expect(page.getByRole("heading",{name:"Diagnostic application",exact:true})).toBeVisible();
 await page.getByRole("button",{name:/^Original failed workflow R1$/}).filter({visible:true}).first().click();
 await expect(page.getByRole("cell",{name:"blocked",exact:true})).toBeVisible();
 await expect(page.getByText(release!,{exact:true}).filter({visible:true}).first()).toBeVisible();
 await page.getByRole("button",{name:"Open current source editor",exact:true}).click();
 await expect(page.getByRole("heading",{name:"Current saved editor source",exact:true})).toBeVisible();
 await page.goto(`/#/application-runs?app=build&name=${appName}&application=build:${appName}`);
 await page.getByRole("button",{name:/^Original failed workflow R1$/}).filter({visible:true}).first().click();
 await decide(request,"manager","build",`${type}.create`,{type,id:"R2"},{note:"Recovered target"});
 await decide(request,"manager","build",`${type}.ready`,{type,id:"R2"},{});
 await page.getByRole("button",{name:"Retry",exact:true}).filter({visible:true}).first().click();
 await expect.poll(async()=>{const result=await(await request.get(`/v1/records/flow.instance/${encodeURIComponent(instance.id)}`,{headers})).json();return result.record?.state;}).toBe("done");
 const final=await(await request.get(`/v1/records/flow.instance/${encodeURIComponent(instance.id)}`,{headers})).json();expect(final.record.version).toBe(1);expect(final.record.release).toBe(release);
 await open(page,"desk",`/application-runs?app=build&name=${appName}`);await expect(page.getByText("Original failed workflow",{exact:true})).toHaveCount(0);
});
