import {expect,test} from "@playwright/test";
import {decide,fresh,open} from "./host";

test("frozen relationship protection rejects original archive and active child writes until their condition clears",async({page,request},info)=>{
 const name=fresh("protected").replace(/[^a-z0-9]/gi,"").toLowerCase(),parent=`build.${name}parent`,child=`build.${name}child`;
 for(const [suffix,title]of [["parent","Protected parents"],["child","Protected children"]]){const id=fresh("OBJ");await decide(request,"manager","build","build.object.create",{type:"build.object",id},{name:name+suffix,title,fields:[{name:"note",title:"Note",type:"text"},...(suffix==="child"?[{name:"parent",title:"Parent",type:"reference",ref:parent}]:[])]});await decide(request,"manager","build","build.object.publish",{type:"build.object",id},{});}
 for(const id of ["P","Q"])await decide(request,"desk","build",`${parent}.create`,{type:parent,id},{note:id});await decide(request,"desk","build",`${child}.create`,{type:child,id:"C1"},{note:"ACTIVE-CHILD",parent:"P"});
 await open(page,"manager","/link-type?id=new");await page.getByLabel("Relationship name",{exact:true}).fill(name);await page.getByLabel("Relationship title",{exact:true}).fill("Protected children relation");await page.getByLabel("Relationship description",{exact:true}).fill("Activity protects original parent archive");await page.getByRole("combobox",{name:"Parent object",exact:true}).selectOption(parent);await page.getByRole("combobox",{name:"Child object",exact:true}).selectOption(child);await page.getByRole("combobox",{name:"Reference field",exact:true}).selectOption("parent");await page.getByRole("combobox",{name:"Relationship archive policy",exact:true}).selectOption("restrict-active");
 if(process.env.PLATFORM_SCREENSHOTS){await page.screenshot({path:info.outputPath("archive-policy-editor.png"),fullPage:true});await page.setViewportSize({width:390,height:844});await page.evaluate(()=>new Promise<void>(r=>requestAnimationFrame(()=>requestAnimationFrame(()=>r()))));await page.getByRole("combobox",{name:"Relationship archive policy",exact:true}).scrollIntoViewIfNeeded();await page.screenshot({path:info.outputPath("archive-policy-narrow.png"),fullPage:true});await page.setViewportSize({width:1280,height:720});}
 await page.getByRole("button",{name:"Save relationship",exact:true}).click();await expect(page.getByRole("button",{name:"Save relationship",exact:true})).toBeDisabled();await expect.poll(()=>new URL(page.url()).hash.includes("id=new")).toBe(false);const id=new URL(page.url()).hash.match(/id=([^&]+)/)![1];await page.getByRole("button",{name:"Review release",exact:true}).click();await page.getByRole("button",{name:"Check draft and dependencies",exact:true}).click();await page.getByRole("button",{name:"Save immutable candidate",exact:true}).click();
 await decide(request,"manager","build","build.linktype.edit",{type:"build.linktype",id},{deletePolicy:"owner",title:"Later unprotected draft"});await page.getByRole("button",{name:"Activate release",exact:true}).click();
 const get=async(type:string,id:string)=>(await(await request.get(`/v1/records/${type}/${id}`,{headers:{Authorization:"Bearer desk"}})).json()).record;
 await expect(decide(request,"desk","build",`${parent}.archive`,{type:parent,id:"P"},{})).rejects.toThrow(/archive protection/);expect((await get(parent,"P")).archived).not.toBe(true);
 await decide(request,"desk","build",`${child}.edit`,{type:child,id:"C1"},{parent:"Q"});await decide(request,"desk","build",`${parent}.archive`,{type:parent,id:"P"},{});expect((await get(parent,"P")).archived).toBe(true);
 await expect(decide(request,"desk","build",`${child}.create`,{type:child,id:"NEW"},{note:"REFUSED-CHILD",parent:"P"})).rejects.toThrow(/archive protection/);await expect(decide(request,"desk","build",`${child}.edit`,{type:child,id:"C1"},{parent:"P"})).rejects.toThrow(/archive protection/);expect((await get(child,"C1")).parent).toBe("Q");
 await decide(request,"desk","build",`${child}.archive`,{type:child,id:"C1"},{});await decide(request,"desk","build",`${parent}.archive`,{type:parent,id:"Q"},{});expect((await get(child,"C1")).parent).toBe("Q");expect((await get(child,"C1")).archived).toBe(true);
 await open(page,"manager",`/model?object=${parent}&tab=links`);await page.getByRole("button",{name:/children.*Incoming reference/}).click();await expect(page.getByRole("region",{name:"Semantic inspector",exact:true}).getByText("Protect active references",{exact:true})).toBeVisible();if(process.env.PLATFORM_SCREENSHOTS)await page.screenshot({path:info.outputPath("archive-policy-model.png"),fullPage:true});
 const definitions=await(await request.get("/v1/definitions",{headers:{Authorization:"Bearer desk"}})).json(),link=definitions.find((d:any)=>d.ref.kind==="link-type"&&d.ref.name===name);expect(link.contractVersion).toBe(3);expect(link.linkType.deletePolicy).toBe("restrict-active");expect(link.linkType.title).toBe("Protected children relation");await page.reload();await expect(decide(request,"desk","build",`${child}.create`,{type:child,id:"AFTER"},{note:"REFUSED-AFTER",parent:"P"})).rejects.toThrow(/archive protection/);
});
