import {expect,test} from "@playwright/test";
import {decide,fresh,open} from "./host";

test("a model relationship is authored, frozen and used by a page through authorized typed traversal",async({page,request},info)=>{
 test.setTimeout(60_000);
 const name=fresh("links").replace(/[^a-z0-9]/gi,"").toLowerCase(),parent=`build.${name}parent`,child=`build.${name}child`,parentID=fresh("OBJ"),childID=fresh("OBJ");
 await decide(request,"manager","build","build.object.create",{type:"build.object",id:parentID},{name:`${name}parent`,title:"Link parents",fields:[{name:"note",title:"Note",type:"text"}]});await decide(request,"manager","build","build.object.publish",{type:"build.object",id:parentID},{});
 await decide(request,"manager","build","build.object.create",{type:"build.object",id:childID},{name:`${name}child`,title:"Link children",fields:[{name:"note",title:"Note",type:"text"},{name:"parent",title:"Parent",type:"reference",ref:parent,required:true}],states:[{name:"open",title:"Open"},{name:"done",title:"Done"}],actions:[{name:"complete",title:"Complete related child",from:["open"],to:"done"}]});await decide(request,"manager","build","build.object.publish",{type:"build.object",id:childID},{});
 for(const suffix of ["A","B"]){await decide(request,"desk","build",`${parent}.create`,{type:parent,id:`${name}${suffix}`},{note:`LINK-PARENT-${suffix}`});for(const n of [1,2])await decide(request,"desk","build",`${child}.create`,{type:child,id:`${name}${suffix}${n}`},{note:`LINK-CHILD-${suffix}${n}`,parent:`${name}${suffix}`});}
 await open(page,"manager","/link-type?id=new");await page.getByLabel("Relationship name",{exact:true}).fill(name);await page.getByLabel("Relationship title",{exact:true}).fill("Declared children");await page.getByLabel("Relationship description",{exact:true}).fill("Reference-backed parent and children");await page.getByRole("combobox",{name:"Parent object",exact:true}).selectOption(parent);await page.getByRole("combobox",{name:"Child object",exact:true}).selectOption(child);await page.getByRole("combobox",{name:"Reference field",exact:true}).selectOption("parent");await page.getByLabel("Parent to children name",{exact:true}).fill("children");await page.getByLabel("Child to parent name",{exact:true}).fill("parent");if(process.env.PLATFORM_SCREENSHOTS){await page.screenshot({path:info.outputPath("relationship-editor.png"),fullPage:true});await page.setViewportSize({width:390,height:844});await page.evaluate(()=>new Promise<void>(r=>requestAnimationFrame(()=>requestAnimationFrame(()=>r()))));await page.screenshot({path:info.outputPath("relationship-editor-narrow.png"),fullPage:true});await page.setViewportSize({width:1280,height:720});}await page.getByRole("button",{name:"Save relationship",exact:true}).click();await expect(page.getByRole("button",{name:"Save relationship",exact:true})).toBeDisabled();await expect.poll(()=>new URL(page.url()).hash.includes("id=new")).toBe(false);const linkID=new URL(page.url()).hash.match(/id=([^&]+)/)![1];await page.getByRole("button",{name:"Review release",exact:true}).click();await page.getByRole("button",{name:"Check draft and dependencies",exact:true}).click();await page.getByRole("button",{name:"Save immutable candidate",exact:true}).click();await decide(request,"manager","build","build.linktype.edit",{type:"build.linktype",id:linkID},{forward:"laterchildren",title:"Later relationship draft"});await page.getByRole("button",{name:"Activate release",exact:true}).click();
 await open(page,"manager",`/model?object=${parent}&tab=links`);await page.getByRole("button",{name:/children.*Incoming reference/}).click();await expect(page.getByRole("region",{name:"Semantic inspector",exact:true}).getByText("1.link-1",{exact:true})).toBeVisible();await page.getByRole("button",{name:"Use related records in page",exact:true}).click();const form=page.getByRole("region",{name:"Create page from model",exact:true});await form.getByLabel("Page name",{exact:true}).fill(`${name}page`);await form.getByLabel("Page title",{exact:true}).fill("Declared relation desk");await form.getByRole("button",{name:"Create page draft",exact:true}).click();await expect(page.getByRole("heading",{name:"Declared relation desk",exact:true})).toBeVisible();const pageID=new URL(page.url()).hash.match(/id=([^&]+)/)![1];
 const saved=(await(await request.get(`/v1/records/build.page/${pageID}`,{headers:{Authorization:"Bearer manager"}})).json()).record;saved.sections.push({id:"actions",widget:"actions",configVersion:1,title:"Child work",object:child,selection:"related",actions:[`${child}.complete`]});saved.document.nodes.root.children.push("actions");saved.document.nodes.actions={kind:"widget",section:"actions"};await decide(request,"manager","build","build.page.edit",{type:"build.page",id:pageID},{sections:saved.sections,document:saved.document});await page.reload();await open(page,"manager",`/compose?id=${pageID}`);
 const tree=page.getByRole("region",{name:"Widgets and layout",exact:true}),inspector=page.getByRole("region",{name:"The widget in hand",exact:true});await tree.getByRole("button",{name:"Query plans",exact:true}).click();await expect(inspector.getByRole("combobox",{name:"Relationship binding",exact:true})).toHaveValue(`build/${name}@1.link-1`);await inspector.getByRole("textbox",{name:"Query title",exact:true}).fill("Retained child relationship");await page.getByRole("button",{name:"Save",exact:true}).click();await expect(page.getByRole("button",{name:"Save",exact:true})).toBeDisabled();await page.getByRole("button",{name:"Review release",exact:true}).click();await page.getByRole("button",{name:"Check draft and dependencies",exact:true}).click();await page.getByRole("button",{name:"Save immutable candidate",exact:true}).click();await page.getByRole("button",{name:"Activate release",exact:true}).click();
 await decide(request,"manager","build","build.linktype.publish",{type:"build.linktype",id:linkID},{});
 const operation=await page.context().newPage();let reads=0;operation.on("request",r=>{if(r.url().endsWith(`/v1/records/${child}/query`)){reads++;expect(r.postDataJSON().traversal.binding.sourceVersion).toBe("1.link-1");expect(r.postDataJSON().traversal.direction).toBe("forward");}});await open(operation,"desk",`/page?app=build&kind=page&name=${name}page`);const tables=operation.getByRole("table"),parents=tables.nth(0),children=tables.nth(1),detail=operation.getByRole("heading",{name:"Detail",exact:true}).locator("..");await expect(children.getByText("LINK-CHILD-A1",{exact:true})).toHaveCount(0);expect(reads).toBe(0);await parents.getByRole("row").filter({hasText:"LINK-PARENT-A"}).click();await expect(children.getByText("LINK-CHILD-A1",{exact:true})).toBeVisible();await expect(children.getByText("LINK-CHILD-B1",{exact:true})).toHaveCount(0);await children.getByRole("row").filter({hasText:"LINK-CHILD-A1"}).click();await expect(detail.getByText("LINK-CHILD-A1",{exact:true})).toBeVisible();await operation.getByRole("button",{name:"Complete related child",exact:true}).click();await expect.poll(async()=>(await(await request.get(`/v1/records/${child}/${name}A1`,{headers:{Authorization:"Bearer desk"}})).json()).record.state).toBe("done");expect((await(await request.get(`/v1/records/${child}/${name}B1`,{headers:{Authorization:"Bearer desk"}})).json()).record.state).toBe("open");
 await parents.getByRole("row").filter({hasText:"LINK-PARENT-B"}).click();await expect(children.getByText("LINK-CHILD-B1",{exact:true})).toBeVisible();await expect(detail.getByText("LINK-CHILD-A1",{exact:true})).toHaveCount(0);let release!:()=>void,held=false,released=false;const completed:Promise<void>[]=[];const wait=new Promise<void>(r=>release=r);await operation.route(`**/v1/records/${child}/query`,async route=>{if(route.request().postDataJSON().traversal.id===`${name}A`&&!released){let done!:()=>void;completed.push(new Promise<void>(r=>done=r));try{const response=await route.fetch();held=true;await wait;await route.fulfill({response});}finally{done();}}else await route.continue();});await parents.getByRole("row").filter({hasText:"LINK-PARENT-A"}).click();await expect.poll(()=>held).toBe(true);await parents.getByRole("row").filter({hasText:"LINK-PARENT-B"}).click();await expect(children.getByText("LINK-CHILD-B1",{exact:true})).toBeVisible();released=true;release();await Promise.all(completed);await expect(children.getByText("LINK-CHILD-A1",{exact:true})).toHaveCount(0);await operation.unroute(`**/v1/records/${child}/query`);
 await operation.route(`**/v1/records/${child}/query`,route=>route.fulfill({status:403,contentType:"application/json",body:JSON.stringify({error:{message:"Denied"}})}));await parents.getByRole("row").filter({hasText:"LINK-PARENT-A"}).click();await expect(operation.getByRole("alert").filter({hasText:"Resource read failed"})).toBeVisible();await expect(children.getByText("LINK-CHILD-B1",{exact:true})).toHaveCount(0);await operation.unroute(`**/v1/records/${child}/query`);await operation.getByRole("button",{name:"Retry query",exact:true}).click();await expect(children.getByText("LINK-CHILD-A1",{exact:true})).toBeVisible();
 if(process.env.PLATFORM_SCREENSHOTS){await operation.screenshot({path:info.outputPath("relationship-page.png"),fullPage:true});await operation.setViewportSize({width:390,height:844});await operation.evaluate(()=>new Promise<void>(r=>requestAnimationFrame(()=>requestAnimationFrame(()=>r()))));await operation.screenshot({path:info.outputPath("relationship-page-narrow.png"),fullPage:true});}await operation.reload();await expect(children.getByText("LINK-CHILD-B1",{exact:true})).toHaveCount(0);await parents.getByRole("row").filter({hasText:"LINK-PARENT-A"}).click();await expect(children.getByText("LINK-CHILD-A1",{exact:true})).toBeVisible();
});
