import {expect,test} from "@playwright/test";
import {decide,fresh,open} from "./host";

test("a model authors a frozen one-to-one relation and original writes reject duplicate references",async({page,request},info)=>{
 const name=fresh("unique").replace(/[^a-z0-9]/gi,"").toLowerCase(),parent=`build.${name}parent`,child=`build.${name}child`;
 for(const [suffix,title]of [["parent","Unique parents"],["child","Unique children"]]){const id=fresh("OBJ");await decide(request,"manager","build","build.object.create",{type:"build.object",id},{name:name+suffix,title,fields:[{name:"note",title:"Note",type:"text"},...(suffix==="child"?[{name:"parent",title:"Parent",type:"reference",ref:parent}]:[])]});await decide(request,"manager","build","build.object.publish",{type:"build.object",id},{});}
 for(const id of ["P","Q"])await decide(request,"desk","build",`${parent}.create`,{type:parent,id},{note:id});await decide(request,"desk","build",`${child}.create`,{type:child,id:"C1"},{note:"FIRST-CHILD",parent:"P"});
 await open(page,"manager","/link-type?id=new");await page.getByLabel("Relationship name",{exact:true}).fill(name);await page.getByLabel("Relationship title",{exact:true}).fill("Unique children relation");await page.getByLabel("Relationship description",{exact:true}).fill("At most one child holds a parent reference");await page.getByRole("combobox",{name:"Parent object",exact:true}).selectOption(parent);await page.getByRole("combobox",{name:"Child object",exact:true}).selectOption(child);await page.getByRole("combobox",{name:"Reference field",exact:true}).selectOption("parent");await page.getByRole("combobox",{name:"Relationship cardinality",exact:true}).selectOption("one-to-one");
 if(process.env.PLATFORM_SCREENSHOTS){await page.screenshot({path:info.outputPath("cardinality-editor.png"),fullPage:true});await page.setViewportSize({width:390,height:844});await page.evaluate(()=>new Promise<void>(r=>requestAnimationFrame(()=>requestAnimationFrame(()=>r()))));await page.screenshot({path:info.outputPath("cardinality-editor-narrow.png"),fullPage:true});await page.setViewportSize({width:1280,height:720});}
 await page.getByRole("button",{name:"Save relationship",exact:true}).click();await expect(page.getByRole("button",{name:"Save relationship",exact:true})).toBeDisabled();await expect.poll(()=>new URL(page.url()).hash.includes("id=new")).toBe(false);const id=new URL(page.url()).hash.match(/id=([^&]+)/)![1];
 await page.getByRole("button",{name:"Review release",exact:true}).click();await page.getByRole("button",{name:"Check draft and dependencies",exact:true}).click();await page.getByRole("button",{name:"Save immutable candidate",exact:true}).click();
 await decide(request,"manager","build","build.linktype.edit",{type:"build.linktype",id},{cardinality:"one-to-many",title:"Later weak draft"});await page.getByRole("button",{name:"Activate release",exact:true}).click();
 const definitions=await(await request.get("/v1/definitions",{headers:{Authorization:"Bearer desk"}})).json(),link=definitions.find((d:any)=>d.ref.kind==="link-type"&&d.ref.name===name);expect(link.contractVersion).toBe(2);expect(link.linkType.cardinality).toBe("one-to-one");expect(link.linkType.title).toBe("Unique children relation");
 await expect(decide(request,"desk","build",`${child}.create`,{type:child,id:"C2"},{note:"REFUSED-CHILD",parent:"P"})).rejects.toThrow(/cardinality/);
 await decide(request,"desk","build",`${child}.create`,{type:child,id:"C2"},{note:"SECOND-CHILD",parent:"Q"});await expect(decide(request,"desk","build",`${child}.edit`,{type:child,id:"C2"},{parent:"P"})).rejects.toThrow(/cardinality/);expect((await(await request.get(`/v1/records/${child}/C2`,{headers:{Authorization:"Bearer desk"}})).json()).record.parent).toBe("Q");
 await open(page,"manager",`/model?object=${parent}&tab=links`);await page.getByRole("button",{name:/children.*Incoming reference/}).click();await expect(page.getByRole("region",{name:"Semantic inspector",exact:true}).getByText("One-to-one (at most one child)",{exact:true})).toBeVisible();
 if(process.env.PLATFORM_SCREENSHOTS)await page.screenshot({path:info.outputPath("cardinality-model.png"),fullPage:true});
 await page.reload();await page.getByRole("button",{name:/children.*Incoming reference/}).click();await expect(page.getByRole("region",{name:"Semantic inspector",exact:true}).getByText("One-to-one (at most one child)",{exact:true})).toBeVisible();await expect(decide(request,"desk","build",`${child}.create`,{type:child,id:"C3"},{note:"REFUSED-AGAIN",parent:"P"})).rejects.toThrow(/cardinality/);
});
