import type {APIRequestContext} from "@playwright/test";
import {decide,fresh,pageUIProfile} from "./host";

export async function createNestedLoopFixture(request:APIRequestContext){
 const name=fresh("nested").replace(/[^a-z0-9]/gi,"").toLowerCase(),parent=`build.${name}parent`,child=`build.${name}child`,parentObject=fresh("OBJ"),childObject=fresh("OBJ"),query=fresh("QUERY"),id=fresh("PAGE"),ref={app:"build",kind:"object",name:parent},childRef={app:"build",kind:"object",name:child};
 await decide(request,"manager","build","build.object.create",{type:"build.object",id:parentObject},{name:`${name}parent`,title:"Nested parents",fields:[{name:"note",title:"Note",type:"text",search:true},{name:"bucket",title:"Bucket",type:"text"}]});await decide(request,"manager","build","build.object.publish",{type:"build.object",id:parentObject},{});
 await decide(request,"manager","build","build.object.create",{type:"build.object",id:childObject},{name:`${name}child`,title:"Nested children",fields:[{name:"note",title:"Note",type:"text"},{name:"parent",title:"Parent",type:"reference",ref:parent,required:true}],states:[{name:"open",title:"Open"},{name:"done",title:"Done"}],actions:[{name:"complete",title:"Complete child",from:["open"],to:"done"}]});await decide(request,"manager","build","build.object.publish",{type:"build.object",id:childObject},{});
 for(const suffix of ["A","B"]){await decide(request,"desk","build",`${parent}.create`,{type:parent,id:`${name}${suffix}`},{note:`PARENT-${suffix}`,bucket:suffix});for(const n of suffix==="A"?[1,2]:[1])await decide(request,"desk","build",`${child}.create`,{type:child,id:`${name}${suffix}${n}`},{note:`CHILD-${suffix}${n}`,parent:`${name}${suffix}`});}
 await decide(request,"manager","build","build.query.create",{type:"build.query",id:query},{name,title:"Children for a parent",description:"Read the original parent reference",object:child,by:"parent",limit:3});await decide(request,"manager","build","build.query.publish",{type:"build.query",id:query},{});
 const document={formatVersion:2,uiProfile:pageUIProfile,root:"root",nodes:{root:{kind:"rows",children:["input","parents"]},input:{kind:"widget",section:"input",valueVariable:"search"},parents:{kind:"loop",title:"Parent cards",children:["parentDetail","parentCountButton","children"],loop:{collection:"parentWindow",itemVariable:"parentItem",limit:2}},parentDetail:{kind:"widget",section:"parentDetail"},parentCountButton:{kind:"widget",section:"parentCountButton",enabledWhen:"hasTwo"},children:{kind:"loop",title:"Child cards",children:["childDetail","actions","scratchInput","button","notice"],loop:{collection:"childWindow",itemVariable:"childItem",limit:3}},childDetail:{kind:"widget",section:"childDetail"},actions:{kind:"widget",section:"actions"},scratchInput:{kind:"widget",section:"scratchInput",valueVariable:"scratch"},button:{kind:"widget",section:"button"},notice:{kind:"widget",section:"notice",visibleWhen:"shown"}},variables:{parentShown:{scope:"loop-item",owner:"parents",type:"boolean",mode:"state",initial:false},childCount:{scope:"loop-item",owner:"parents",type:"decimal",mode:"aggregate",source:{kind:"count",query:"children"}},hasTwo:{scope:"loop-item",owner:"parents",type:"boolean",mode:"derived",expression:{op:"decimal-less",args:[{literal:{kind:"decimal",value:"1"}},{variable:"childCount"}]}},search:{scope:"page",type:"string",mode:"state",initial:""},parentWindow:{scope:"page",type:"object-set",mode:"resource",source:{kind:"plan",query:"parents"}},parentItem:{scope:"loop-item",owner:"parents",type:"record",mode:"resource",source:{kind:"item",node:"parents"}},childWindow:{scope:"loop-item",owner:"parents",type:"object-set",mode:"resource",source:{kind:"plan",query:"children"}},childItem:{scope:"loop-item",owner:"children",type:"record",mode:"resource",source:{kind:"item",node:"children"}},scratch:{scope:"loop-item",owner:"children",type:"string",mode:"state",initial:"seed"},shown:{scope:"loop-item",owner:"children",type:"boolean",mode:"state",initial:false}},queries:{parents:{object:ref,limit:2,sort:["id"],search:{variable:"search"}},children:{title:"Per-parent children",itemOwner:"parents",object:childRef,query:{ref:{app:"build",kind:"query",name},sourceVersion:"1.query-1"},for:{variable:"parentItem"},limit:3,sort:["id"]}},events:[{source:"parentCountButton",event:"click",effects:[{kind:"set", target:"parentShown", value:true}]},{source:"button",event:"click",effects:[{kind:"set", target:"shown", value:true}]}]};
 await decide(request,"manager","build","build.page.create",{type:"build.page",id},{name,title:"Nested operation desk",object:parent,sections:[{id:"parentCountButton",widget:"button",configVersion:1,title:"Work with this parent’s children"},{id:"input",widget:"input",configVersion:1,title:"Parent search"},{id:"parentDetail",widget:"detail",configVersion:1,title:"Parent",object:parent,fields:["note"],recordVariable:"parentItem"},{id:"childDetail",widget:"detail",configVersion:1,title:"Child",object:child,fields:["note"],recordVariable:"childItem"},{id:"actions",widget:"actions",configVersion:1,title:"Child work",object:child,actions:[`${child}.complete`],recordVariable:"childItem"},{id:"scratchInput",widget:"input",configVersion:1,title:"Child scratch"},{id:"button",widget:"button",configVersion:1,title:"Show child context"},{id:"notice",widget:"text",configVersion:1,text:"This child's context"}],document});
 return {name,parent,child,id,document};
}
