import {expect,test} from "@playwright/test";
import {open} from "./host";

test("four shared observation views preserve wide-window identities, controlled statistics and actual time geometry",async({page},info)=>{
 test.setTimeout(90_000);page.setDefaultTimeout(10_000);
 const example=async(id:string)=>{await open(page,"manager",`/catalog-example?id=ui/${id}`);await expect(page.getByText("Synthetic fixed observations; this example does not read tenant data.",{exact:true}).filter({visible:true})).toBeVisible();};
 await example("observation-table");const table=page.getByRole("table");await expect(table).toHaveAttribute("aria-colcount","106");expect(await table.getByRole("columnheader").count()).toBeLessThan(30);expect(await table.getByRole("row").count()).toBeLessThan(45);await table.getByRole("row").nth(1).click();await expect(page.getByText("Selected original observation OBS-000",{exact:true})).toBeVisible();await page.getByRole("button",{name:"Export original window",exact:true}).click();await expect(page.getByText("Export callback received 60 original rows and 106 columns.",{exact:true})).toBeVisible();
 await table.evaluate(element=>element.scrollLeft=element.scrollWidth);await expect(table.getByRole("columnheader",{name:/signal99/i})).toBeVisible();expect(await table.getByRole("columnheader").count()).toBeLessThan(30);await expect(table.getByRole("columnheader",{name:"Record ID",exact:true})).toBeVisible();await table.evaluate(element=>element.scrollTop=element.scrollHeight);await expect(table.getByRole("cell",{name:"OBS-059",exact:true})).toBeVisible();const last=table.getByRole("cell",{name:"OBS-059",exact:true}).locator("..").getByRole("cell",{name:"158.00",exact:true});await expect(last).toBeVisible();await last.click();await expect(page.getByText("Selected original observation OBS-059",{exact:true})).toBeVisible();
 await page.getByText("Observation columns",{exact:true}).click();await page.getByRole("searchbox",{name:"Find observation columns",exact:true}).fill("signal99");await expect(page.getByRole("checkbox",{name:/signal99/})).toBeVisible();await page.getByRole("button",{name:"Hide all signals",exact:true}).click();await expect(table).toHaveAttribute("aria-colcount","6");await page.getByRole("button",{name:"New observation view",exact:true}).click();await expect(table).toHaveAttribute("aria-colcount","106");await expect(page.getByText("Selected original observation OBS-059",{exact:true})).toHaveCount(0);await page.getByRole("button",{name:"Show earlier answer",exact:true}).click();await expect(table).toHaveCount(0);await page.getByRole("button",{name:"Show current answer",exact:true}).click();await expect(table).toBeVisible();
 if(process.env.PLATFORM_SCREENSHOTS){await page.screenshot({path:info.outputPath("observation-table.png")});await page.setViewportSize({width:390,height:844});await page.getByRole("switch",{name:"Pin observation metadata",exact:true}).click();await table.evaluate(element=>element.scrollLeft=element.scrollWidth);await page.screenshot({path:info.outputPath("observation-table-narrow.png")});await page.setViewportSize({width:1280,height:720});}
 await example("observation-statistics");await expect(page.getByText("60 observations · 59 numeric values in the original 10,000-row window",{exact:true})).toBeVisible();const threshold=page.getByRole("textbox",{name:"Alarm above",exact:true});await threshold.fill("");await expect(page.getByRole("alert").filter({hasText:"invalid draft"})).toBeVisible();await threshold.fill("50");await expect(page.getByText("Above 50",{exact:true})).toBeVisible();await page.getByRole("combobox",{name:"Observation signal",exact:true}).selectOption("temperature");await expect(page.getByText("60 observations · 60 numeric values in the original 10,000-row window",{exact:true})).toBeVisible();await page.getByRole("combobox",{name:"Observation window rows",exact:true}).selectOption("1000");await expect(page.getByText("60 observations · 60 numeric values in the original 1,000-row window",{exact:true})).toBeVisible();await page.getByRole("button",{name:"Show earlier answer",exact:true}).click();await expect(page.getByText("Max",{exact:true})).toHaveCount(0);await expect(page.getByRole("img",{name:/^OBS-/})).toHaveCount(0);await page.getByRole("button",{name:"Show current answer",exact:true}).click();await expect(page.getByText("Max",{exact:true})).toBeVisible();if(process.env.PLATFORM_SCREENSHOTS)await page.screenshot({path:info.outputPath("observation-statistics.png")});
 await example("observation-availability");await expect(page.getByText(/Complete authorized average.*96.5 %.*60 records/)).toBeVisible();await expect(page.getByRole("img",{name:"SLO 99",exact:true})).toBeAttached();if(process.env.PLATFORM_SCREENSHOTS)await page.screenshot({path:info.outputPath("observation-availability.png")});
 await example("observation-time-series");await expect(page.getByRole("group",{name:/by original event time/,exact:false})).toHaveCount(3);await expect(page.getByRole("img",{name:/OBS-020.*pressure/})).toHaveCount(0);await expect(page.getByRole("img",{name:/OBS-020.*temperature: 100 °C/})).toBeVisible();const point=page.getByRole("img",{name:/OBS-059.*availability: 97.95 %/});await point.focus();await expect(page.getByRole("status").filter({hasText:"OBS-059 · 2026-10-03T00:59:00.000Z · availability: 97.95 %"})).toBeVisible();if(process.env.PLATFORM_SCREENSHOTS){await page.screenshot({path:info.outputPath("observation-series.png")});for(const signal of ["pressure","temperature","availability"])await page.getByRole("group",{name:`${signal} by original event time`,exact:true}).screenshot({path:info.outputPath(`observation-series-${signal}.png`)});await page.setViewportSize({width:390,height:844});await page.screenshot({path:info.outputPath("observation-series-narrow.png")});}
 await page.getByRole("button",{name:"Refuse example read",exact:true}).click();await expect(page.getByRole("alert").filter({hasText:"Catalog observation read refused"})).toBeVisible();await expect(page.getByRole("img",{name:/^OBS-/})).toHaveCount(0);await page.getByRole("button",{name:"Restore example read",exact:true}).click();await expect(point).toBeVisible();
});
