import {expect,test} from "@playwright/test";
import {decide,fresh,open,pageUIProfile,stableReadRevision} from "./host";

test("a registered pivot is authored and frozen over a complete set while paging and obsolete reads cannot change totals",async({page,request},info)=>{
 test.setTimeout(60_000);
 const name=fresh("pivot").replace(/[^a-z0-9]/gi,"").toLowerCase(),type=`build.${name}`,object=fresh("OBJ"),id=fresh("PAGE"),ref={app:"build",kind:"object",name:type};
 await decide(request,"manager","build","build.object.create",{type:"build.object",id:object},{name,title:"Pivot notes",fields:[{name:"bucket",title:"Bucket",type:"text"},{name:"line",title:"Line",type:"text"},{name:"qty",title:"Quantity",type:"integer"}]});await decide(request,"manager","build","build.object.publish",{type:"build.object",id:object},{});
 for(const [suffix,line,qty] of [["A1","X",10],["A2","X",20],["A3","Y",30],["B1","X",40],["B2","Y",50],["C1","X",60]] as const)await decide(request,"desk","build",`${type}.create`,{type,id:`${name}${suffix}`},{bucket:suffix[0],line,qty});
 await decide(request,"manager","build","build.page.create",{type:"build.page",id},{name,title:"Pivot desk",object:type,sections:[{id:"input",widget:"input",configVersion:1,title:"Pivot bucket"},{id:"table",widget:"table",configVersion:1,title:"One record window",fields:["bucket","line"],collectionVariable:"window"}],document:{formatVersion:2,uiProfile:pageUIProfile,root:"root",nodes:{root:{kind:"rows",children:["input","table"]},input:{kind:"widget",section:"input",valueVariable:"bucket"},table:{kind:"widget",section:"table"}},variables:{bucket:{scope:"page",type:"string",mode:"state",initial:"B"},window:{title:"Complete set",scope:"page",type:"object-set",mode:"resource",source:{kind:"plan",query:"combined"}}},queries:{left:{object:ref,limit:1,conditions:[{field:"bucket",op:"=",value:{literal:"A"}}]},right:{object:ref,limit:1,conditions:[{field:"bucket",op:"=",value:{variable:"bucket"}}]},combined:{object:ref,limit:1,sort:["id"],set:{op:"union",inputs:["left","right"]}}}}});
 await open(page,"manager",`/compose?id=${id}`);const tree=page.getByRole("region",{name:"Widgets and layout",exact:true}),inspector=page.getByRole("region",{name:"The widget in hand",exact:true});
 await tree.getByRole("button",{name:"Pivot table",exact:true}).click();await inspector.getByLabel("Title",{exact:true}).fill("Complete pivot");await inspector.getByRole("combobox",{name:"Aggregate query set",exact:true}).selectOption("window");await inspector.getByRole("combobox",{name:"Rows grouped by",exact:true}).selectOption("bucket");await inspector.getByRole("combobox",{name:"Columns grouped by",exact:true}).selectOption("line");await inspector.getByRole("combobox",{name:"Measure",exact:true}).selectOption("sum:qty");
 if(process.env.PLATFORM_SCREENSHOTS)await inspector.screenshot({path:info.outputPath("pivot-inspector.png")});
 await page.getByRole("button",{name:"Save",exact:true}).click();await expect.poll(async()=>(await(await request.get(`/v1/records/build.page/${id}`,{headers:{Authorization:"Bearer manager"}})).json()).record.sections.find((s:any)=>s.widget==="pivot")?.columnGroup).toBe("line");
 await page.getByRole("button",{name:"Review release",exact:true}).click();await page.getByRole("button",{name:"Check draft and dependencies",exact:true}).click();await page.getByRole("button",{name:"Save immutable candidate",exact:true}).click();
 const saved=(await(await request.get(`/v1/records/build.page/${id}`,{headers:{Authorization:"Bearer manager"}})).json()).record;saved.sections.find((s:any)=>s.widget==="pivot").columnGroup="";saved.document.queries.combined.set.op="subtract";await decide(request,"manager","build","build.page.edit",{type:"build.page",id},{sections:saved.sections,document:saved.document});await page.getByRole("button",{name:"Activate release",exact:true}).click();
 const operation=await page.context().newPage();await stableReadRevision(operation);let reads=0;operation.on("request",r=>{if(r.url().endsWith(`/v1/aggregates/${type}/query`)){reads++;const q=r.postDataJSON();expect(q.groups).toEqual(["bucket","line"]);expect(q.measures).toEqual(["sum:qty"]);expect(q.set.op).toBe("union");expect(q.limit).toBeUndefined();expect(q.offset).toBeUndefined();expect(q.sort).toBeUndefined();}});
 await open(operation,"desk",`/page?app=build&kind=page&name=${name}`);const pivot=operation.getByRole("heading",{name:"Complete pivot",exact:true}).locator(".."),input=operation.getByRole("textbox",{name:"Pivot bucket",exact:true});await expect(pivot.getByRole("table")).toBeVisible();await expect(pivot.getByRole("row").filter({hasText:/^Total/}).getByText("150",{exact:true})).toBeVisible();await expect(pivot.getByRole("columnheader",{name:"X",exact:true})).toBeVisible();expect(reads).toBe(1);
 await operation.getByRole("button",{name:"Next page",exact:true}).click();await expect(operation.getByText("2–2 of 5",{exact:true})).toBeVisible();expect(reads).toBe(1);
 let release!:()=>void,delivered!:()=>void,held=false;const gate=new Promise<void>(r=>release=r),done=new Promise<void>(r=>delivered=r);await operation.route(`**/v1/aggregates/${type}/query`,async route=>{if(route.request().postDataJSON().set.inputs[1].domain[0][2]==="C"){const response=await route.fetch();held=true;await gate;await route.fulfill({response});delivered();}else await route.continue();});await input.fill("C");await expect.poll(()=>held).toBe(true);await expect(pivot.getByText("150",{exact:true})).toHaveCount(0);await input.fill("D");await expect(pivot.getByRole("row").filter({hasText:/^Total/}).getByText("60",{exact:true})).toBeVisible();release();await done;await operation.unroute(`**/v1/aggregates/${type}/query`);await expect(pivot.getByText("120",{exact:true})).toHaveCount(0);
 await operation.route(`**/v1/aggregates/${type}/query`,route=>route.fulfill({status:403,contentType:"application/json",body:JSON.stringify({error:{message:"Denied"}})}));await input.fill("B");await expect(pivot.getByRole("alert")).toBeVisible();await expect(pivot.getByRole("table")).toHaveCount(0);await operation.unroute(`**/v1/aggregates/${type}/query`);await input.fill("C");await expect(pivot.getByRole("row").filter({hasText:/^Total/}).getByText("120",{exact:true})).toBeVisible();
 if(process.env.PLATFORM_SCREENSHOTS){await pivot.scrollIntoViewIfNeeded();await operation.screenshot({path:info.outputPath("pivot-runtime.png"),fullPage:true});await operation.setViewportSize({width:390,height:844});await operation.evaluate(()=>new Promise<void>(r=>requestAnimationFrame(()=>requestAnimationFrame(()=>r()))));await operation.screenshot({path:info.outputPath("pivot-runtime-narrow.png"),fullPage:true});}
 await operation.reload();await expect(pivot.getByRole("row").filter({hasText:/^Total/}).getByText("150",{exact:true})).toBeVisible();
});
