import {expect,test} from "@playwright/test";
import {readFileSync} from "node:fs";
import {decide,fresh,open,pageUIProfile,stableReadRevision} from "./host";

test("Stepper, Tabs and TagList share original typed states and complete counts through import, frozen delivery and isolated overlays",async({page,request},info)=>{
 test.setTimeout(120_000);page.setDefaultTimeout(10_000);
 const name=fresh("grouped").replace(/[^a-z0-9]/gi,"").toLowerCase(),type=`build.${name}`,object=fresh("OBJ"),id=fresh("PAGE");
 await decide(request,"manager","build","build.object.create",{type:"build.object",id:object},{name,title:"Grouped assets",fields:[{name:"name",title:"Asset title",type:"text"},{name:"model",title:"Model",type:"text"},{name:"secret",title:"Private model",type:"text",read:["builder"]}]});await decide(request,"manager","build","build.object.publish",{type:"build.object",id:object},{});
 for(const [i,model] of ["Open","Open","Closed"].entries())await decide(request,"manager","build",`${type}.create`,{type,id:`${name}${i}`},{name:`ASSET-${i}`,model,secret:model});
 const m=JSON.parse(readFileSync(new URL("../../packages/build/src/workshop/module-import/sample.workshop.json",import.meta.url),"utf8")),state=(id:string,type:string,value:unknown)=>({id,name:id,type,definitionKind:"static",staticValue:value}),set=(id:string,clauses:any[])=>({id,name:id,type:"objectSet",definitionKind:"objectSetDefinition",sourceObjectType:"Asset",objectSet:{objectType:"Asset",steps:clauses.length?[{op:"where",clauses}]:[]}}),steps=(id:string,title:string,variable?:string)=>({id,name:title,type:"Stepper",config:{steps:["Observe","Investigate","Decide","Act"],...(variable?{currentVarId:variable}:{})}}),tabs=(id:string,title:string,variable?:string)=>({id,name:title,type:"Tabs",config:{tabs:["Open","In Progress","Done"],...(variable?{variableId:variable}:{})}}),tags=(id:string,title:string,setID:string,filter?:string,property="model")=>({id,name:title,type:"TagList",config:{objectSetVarId:setID,property,...(filter?{filterVarId:filter}:{})}});
 m.variables=[state("index","numeric",0),state("tag","string",""),state("tagSearch","string",""),state("enabled","boolean",true),set("notes",[{property:"model",op:"is",varId:"tag"}]),set("tags",[{property:"name",op:"contains",varId:"tagSearch"}]),state("localIndex","numeric",1),state("localTag","string",""),set("localTags",[])];
 m.widgets={steps:steps("steps","Work steps","index"),tabs:tabs("tabs","Work tabs","index"),readOnly:steps("readOnly","Read only steps"),raw:{id:"raw",name:"Original index",type:"NumericInput",config:{variableId:"index",label:"Original index"}},gate:{id:"gate",name:"Allow controls",type:"ToggleSwitch",config:{variableId:"enabled",label:"Allow controls"}},tags:tags("tags","Model tags","tags","tag"),privateTags:tags("privateTags","Private tags","tags",undefined,"secret"),tagSearch:{id:"tagSearch",name:"Tag search",type:"TextInput",config:{variableId:"tagSearch",label:"Tag search"}},rawTag:{id:"rawTag",name:"Original tag",type:"TextInput",config:{variableId:"tag",label:"Original tag"}},table:{id:"table",name:"Filtered assets",type:"ObjectTable",config:{objectSetVarId:"notes",columns:[{key:"name"},{key:"model"}]}},localSteps:steps("localSteps","Local steps","localIndex"),localTabs:tabs("localTabs","Local tabs","localIndex"),localTags:tags("localTags","Local tags","localTags","localTag"),trigger:{id:"trigger",name:"Open controls",type:"SingleButton",config:{label:"Open controls",eventActions:[{kind:"openOverlay",overlayId:"panel"}]}},close:{id:"close",name:"Close controls",type:"SingleButton",config:{label:"Close controls",eventActions:[{kind:"closeOverlay",overlayId:"panel"}]}}};
 m.sections={root:{id:"root",name:"Root",layout:"rows",children:["gate","steps","tabs","readOnly","raw","tags","privateTags","tagSearch","rawTag","table","trigger"].map(id=>({kind:"widget",id}))},panel:{id:"panel",name:"Panel",layout:"rows",children:["localSteps","localTabs","localTags","close"].map(id=>({kind:"widget",id}))}};m.overlays=[{id:"panel",name:"Control panel",kind:"drawer",rootSectionId:"panel"}];
 await decide(request,"manager","build","build.page.create",{type:"build.page",id},{name,title:"Grouped controls",object:type,sections:[{id:"initial",widget:"text",configVersion:1,text:"Initial"}],document:{formatVersion:2,uiProfile:pageUIProfile,root:"root",nodes:{root:{kind:"rows",children:["initial"]},initial:{kind:"widget",section:"initial"}}}});
 await open(page,"manager",`/compose?id=${id}`);await page.getByRole("button",{name:"Import Workshop module",exact:true}).click();const dialog=page.getByRole("dialog",{name:"Import Workshop module",exact:true});await dialog.getByRole("textbox",{name:"Source module JSON",exact:true}).fill(JSON.stringify(m));await dialog.getByRole("combobox",{name:"Map object Asset",exact:true}).selectOption(type);for(const field of ["name","model","secret"])await dialog.getByRole("combobox",{name:`Map field Asset.${field}`,exact:true}).selectOption(field);await dialog.getByRole("checkbox").check();await expect(dialog.getByRole("button",{name:"Apply imported page draft",exact:true})).toBeEnabled();await dialog.getByRole("button",{name:"Apply imported page draft",exact:true}).click();
 const tree=page.getByRole("region",{name:"Widgets and layout",exact:true}),inspector=page.getByRole("region",{name:"The widget in hand",exact:true});for(const title of ["Work steps","Work tabs","Model tags"]){await tree.getByRole("button",{name:title,exact:true}).click();await inspector.getByRole("combobox",{name:"Enabled when",exact:true}).selectOption({label:"enabled"});}
 await tree.getByRole("button",{name:"Work steps",exact:true}).click();await expect(inspector.getByRole("combobox",{name:"Choice presentation",exact:true})).toHaveValue("steps");await inspector.getByRole("textbox",{name:"Choice option label 2",exact:true}).fill("Investigate frozen");await tree.getByRole("button",{name:"Model tags",exact:true}).click();await expect(inspector.getByRole("combobox",{name:"Tag grouping field",exact:true})).toHaveValue("model");await page.getByRole("button",{name:"Save",exact:true}).click();
 let saved:any;await expect.poll(async()=>{saved=(await(await request.get(`/v1/records/build.page/${id}`,{headers:{Authorization:"Bearer manager"}})).json()).record;return saved.sections?.filter((s:any)=>s.widget==="tag-counts").length;}).toBe(3);const chosen=saved.sections.find((s:any)=>s.title==="Work steps"),nativeTabs=saved.sections.find((s:any)=>s.title==="Work tabs");expect(chosen.choiceVariable).toBe(nativeTabs.choiceVariable);
 await page.getByRole("button",{name:"Review release",exact:true}).click();await page.getByRole("button",{name:"Check draft and dependencies",exact:true}).click();await page.getByRole("button",{name:"Save immutable candidate",exact:true}).click();chosen.choiceInput.optionLabels[1]="Later draft";saved.document.variables[chosen.choiceVariable].initial="3";saved.sections.find((s:any)=>s.title==="Model tags").group="secret";await decide(request,"manager","build","build.page.edit",{type:"build.page",id},{sections:saved.sections,document:saved.document});await page.getByRole("button",{name:"Activate release",exact:true}).click();
 const runtime=await page.context().newPage();runtime.setDefaultTimeout(10_000);await stableReadRevision(runtime);await open(runtime,"desk",`/page?app=build&kind=page&name=${name}`);const section=(title:string)=>runtime.getByRole("heading",{name:title,exact:true}).locator(".."),step=section("Work steps"),tab=section("Work tabs"),tagView=section("Model tags"),table=section("Filtered assets"),raw=runtime.getByRole("textbox",{name:"Original index",exact:true}),rawTag=runtime.getByRole("textbox",{name:"Original tag",exact:true}),search=runtime.getByRole("textbox",{name:"Tag search",exact:true});
 await expect(step.getByRole("button",{name:"Observe",exact:true})).toHaveAttribute("aria-current","step");await expect(tab.getByRole("tab",{name:"Open",exact:true})).toHaveAttribute("aria-selected","true");await expect(section("Read only steps").getByRole("button").first()).toBeDisabled();await expect(runtime.getByRole("heading",{name:"Private tags",exact:true})).toHaveCount(0);await expect(tagView.getByRole("button",{name:/^Open/})).toContainText("2");await expect(tagView.getByRole("button",{name:/^Closed/})).toContainText("1");
 await step.getByRole("button",{name:"Investigate frozen",exact:true}).click();await expect(raw).toHaveValue("1");await expect(tab.getByRole("tab",{name:"In Progress",exact:true})).toHaveAttribute("aria-selected","true");await tab.getByRole("tab",{name:"Done",exact:true}).click();await expect(raw).toHaveValue("2");await expect(step.getByRole("button",{name:"Decide",exact:true})).toHaveAttribute("aria-current","step");await raw.fill("3");await expect(step.getByRole("button",{name:"Act",exact:true})).toHaveAttribute("aria-current","step");await expect(tab.getByRole("tab",{selected:true})).toHaveCount(0);await raw.fill("");await expect(step.getByRole("button",{pressed:true})).toHaveCount(0);await tab.getByRole("tab",{name:"Open",exact:true}).click();await expect(raw).toHaveValue("0");
 await tagView.getByRole("button",{name:/^Open/}).click();await expect(rawTag).toHaveValue("Open");await expect(table.getByRole("cell",{name:"Closed",exact:true})).toHaveCount(0);await expect(table.getByRole("cell",{name:"Open",exact:true})).toHaveCount(2);await tagView.getByRole("button",{name:/Clear/}).click();await expect(rawTag).toHaveValue("");await expect(table.getByRole("cell",{name:"Closed",exact:true})).toBeVisible();
 if(process.env.PLATFORM_SCREENSHOTS){await step.screenshot({path:info.outputPath("grouped-steps.png")});await tagView.screenshot({path:info.outputPath("grouped-tags.png")});await runtime.setViewportSize({width:390,height:844});await step.screenshot({path:info.outputPath("grouped-steps-narrow.png")});await tab.screenshot({path:info.outputPath("grouped-tabs-narrow.png")});await runtime.setViewportSize({width:1280,height:720});}
 await runtime.getByRole("switch",{name:"Allow controls",exact:true}).click();await expect(step.getByRole("button").first()).toBeDisabled();await expect(tab.getByRole("tab").first()).toBeDisabled();await expect(tagView.getByRole("button",{name:/^Open/})).toBeDisabled();await runtime.getByRole("switch",{name:"Allow controls",exact:true}).click();
 let denied=false;await runtime.route(`**/v1/aggregates/${type}/query`,async route=>{denied=true;await route.fulfill({status:403,contentType:"application/json",body:JSON.stringify({error:{message:"Denied"}})});});await search.fill("ASSET-0");await expect.poll(()=>denied).toBe(true);await expect(tagView.getByRole("alert")).toBeVisible();await expect(tagView.getByRole("button",{name:/^Open/})).toHaveCount(0);await runtime.unroute(`**/v1/aggregates/${type}/query`);await search.fill("");await expect(tagView.getByRole("button",{name:/^Open/})).toBeVisible();
 let releaseOld:()=>void=()=>{};const oldGate=new Promise<void>(r=>releaseOld=r);let oldStarted=false;await runtime.route(`**/v1/aggregates/${type}/query`,async route=>{if(JSON.stringify(route.request().postDataJSON()).includes("ASSET-0")){oldStarted=true;const response=await route.fetch();await oldGate;await route.fulfill({response});}else await route.continue();});await search.fill("ASSET-0");await expect.poll(()=>oldStarted).toBe(true);await search.fill("ASSET-2");await expect(tagView.getByRole("button",{name:/^Closed/})).toBeVisible();const completed=runtime.waitForResponse(r=>r.url().endsWith(`/v1/aggregates/${type}/query`)&&JSON.stringify(r.request().postDataJSON()).includes("ASSET-0"));releaseOld();await completed;await runtime.evaluate(()=>new Promise<void>(r=>requestAnimationFrame(()=>requestAnimationFrame(()=>r()))));await expect(tagView.getByRole("button",{name:/^Open/})).toHaveCount(0);await runtime.unroute(`**/v1/aggregates/${type}/query`);await search.fill("");await expect(tagView.getByRole("button",{name:/^Open/})).toBeVisible();
 await runtime.getByRole("button",{name:"Open controls",exact:true}).click();const panel=runtime.getByRole("dialog",{name:"Control panel",exact:true}),localSteps=panel.getByRole("heading",{name:"Local steps",exact:true}).locator(".."),localTabs=panel.getByRole("heading",{name:"Local tabs",exact:true}).locator(".."),localTags=panel.getByRole("heading",{name:"Local tags",exact:true}).locator("..");await expect(localTabs.getByRole("tab",{name:"In Progress",exact:true})).toHaveAttribute("aria-selected","true");await localSteps.getByRole("button",{name:"Decide",exact:true}).click();await expect(localTabs.getByRole("tab",{name:"Done",exact:true})).toHaveAttribute("aria-selected","true");await localTags.getByRole("button",{name:/^Closed/}).click();await panel.getByRole("button",{name:"Close controls",exact:true}).click();await expect(raw).toHaveValue("0");await expect(rawTag).toHaveValue("");await runtime.getByRole("button",{name:"Open controls",exact:true}).click();await expect(localTabs.getByRole("tab",{name:"In Progress",exact:true})).toHaveAttribute("aria-selected","true");await panel.getByRole("button",{name:"Close controls",exact:true}).click();
});
