import {expect,test} from '@playwright/test';
import {readFileSync} from 'node:fs';
import {defaultAnalyticsComparisonGroup} from '../../packages/build/src/module-import/default-analytics.fixture.mjs';
import {decide,fresh,open,pageUIProfile,stableReadRevision} from './host';

test('original Operations multiselect and Analytics scatter ranking comparison share one frozen application with independent single selection',async({page,request},info)=>{
 test.setTimeout(150_000);page.setDefaultTimeout(10_000);
 const name=fresh('sets').replace(/[^a-z0-9]/gi,'').toLowerCase(),type=`build.${name}`,obj=fresh('OBJ'),op=fresh('PAGE'),analytics=fresh('PAGE'),app=fresh('APP'),headers={Authorization:'Bearer manager'},ref={app:'build',kind:'object',name:type},application=`build:${name}app`,fixture=defaultAnalyticsComparisonGroup(pageUIProfile),source=JSON.stringify(fixture.module);
 await decide(request,'manager','build','build.object.create',{type:'build.object',id:obj},{name,title:'Original comparison assets',fields:[{name:'name',title:'Name',type:'text',search:true},{name:'status',title:'Status',type:'choice',choices:'active,warning,offline,maintenance'},{name:'priority',title:'Priority',type:'choice',choices:'Low,High'},{name:'owner',title:'Owner',type:'text'},...['pressure','temperature','availability','exposure','openalerts'].map(name=>({name,title:name[0]!.toUpperCase()+name.slice(1),type:'integer'})),{name:'model',title:'Model',type:'text'},...['installedat','lastinspection','nextmaintenance'].map(name=>({name,title:name,type:'date'})),{name:'secret',title:'Private comparison',type:'text',read:['builder']}]});await decide(request,'manager','build','build.object.publish',{type:'build.object',id:obj},{});
 for(let n=0;n<12;n++)await decide(request,'manager','build',`${type}.create`,{type,id:`R${String(n).padStart(2,'0')}`},{name:`Asset ${String(n).padStart(2,'0')}`,status:n%2?'warning':'active',priority:'Low',owner:n%2?'Team B':'Team A',pressure:n,temperature:n*2,availability:90,exposure:n*100,openalerts:0,model:'Original model',installedat:'2020-01-01',lastinspection:'2026-10-01',nextmaintenance:'2026-10-10',secret:'Never copied into selection state'});
 for(const [id,suffix,title]of [[op,'operations','Operations selection'],[analytics,'analytics','Analytics comparison']]){await decide(request,'manager','build','build.page.create',{type:'build.page',id:id!},{name:`${name}${suffix}`,title,object:type,sections:[{id:'initial',widget:'text',configVersion:1,text:'Initial'}],document:{formatVersion:2,uiProfile:pageUIProfile,root:'root',nodes:{root:{kind:'rows',children:['initial']},initial:{kind:'widget',section:'initial'}}}});await decide(request,'manager','build','build.page.publish',{type:'build.page',id:id!},{});}
 await decide(request,'manager','build','build.app.create',{type:'build.app',id:app},{name:`${name}app`,title:'Original shared comparison desk',pages:[`${name}operations`,`${name}analytics`],uiProfile:pageUIProfile,variables:{record:{scope:'application',type:'record',mode:'resource',source:{kind:'record',object:ref}},records:{scope:'application',type:'record-set',mode:'resource',source:{kind:'record-set',object:ref}},currentPage:{scope:'application',type:'string',mode:'state',initial:'pOperations'},showDetail:{scope:'application',type:'boolean',mode:'state',initial:true}}});await decide(request,'manager','build','build.app.publish',{type:'build.app',id:app},{});
 const defs=await(await request.get('/v1/definitions',{headers})).json(),def=defs.find((d:any)=>d.ref.kind==='app'&&d.ref.name===`${name}app`),binding={ref:def.ref,sourceVersion:def.version},savedPages:any[]=[];
 const mapped={id:'id',name:'name',status:'status',priority:'priority',owner:'owner',pressure:'pressure',temperature:'temperature',availability:'availability',revenueImpact:'exposure',openAlerts:'openalerts',model:'model',installedAt:'installedat',lastInspection:'lastinspection',nextMaintenance:'nextmaintenance'};
 for(const [id,sourcePage,target,title]of [[op,'pOperations',`${name}analytics`,'Go to Analytics'],[analytics,'pAnalytics',`${name}operations`,'Back to Operations']]){
  await open(page,'manager',`/compose?id=${id}`);await page.reload();await expect(page.getByRole('textbox',{name:'What people call it',exact:true})).toHaveValue(sourcePage==='pOperations'?'Operations selection':'Analytics comparison');await page.getByRole('button',{name:'Import Workshop module',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Import Workshop module',exact:true});await dialog.getByRole('textbox',{name:'Source module JSON',exact:true}).fill(source);await dialog.getByRole('combobox',{name:'Source page',exact:true}).selectOption(sourcePage!);await dialog.getByRole('combobox',{name:'Map object Asset',exact:true}).selectOption(type);
  for(const [property,field]of Object.entries(mapped)){const control=dialog.getByRole('combobox',{name:`Map field Asset.${property}`,exact:true});if(await control.count())await control.selectOption(field);}
  await dialog.getByRole('combobox',{name:'Reviewed original application',exact:true}).selectOption(JSON.stringify(binding));for(const port of ['selectedAsset','currentPage','showDetail'])await dialog.getByRole('combobox',{name:`Map module port ${port}`,exact:true}).selectOption(port==='selectedAsset'?'record':port);await dialog.getByRole('combobox',{name:'Map module port showDetail',exact:true}).locator('..').locator('..').getByRole('checkbox',{name:'Allow module presentation updates',exact:true}).check();await dialog.getByRole('combobox',{name:'Map application selection set selectedAssets',exact:true}).selectOption('records');
  if(sourcePage==='pOperations'){await dialog.getByRole('combobox',{name:'Map table edit action Assets',exact:true}).selectOption(`${type}.edit`);await dialog.getByRole('group',{name:'Editable table fields',exact:true}).getByRole('button',{name:'Owner',exact:true}).click();}
  else {await dialog.getByRole('group',{name:'Map scatter plot Pressure vs temperature',exact:true}).getByRole('combobox',{name:'Scatter title field',exact:true}).selectOption('name');await dialog.getByRole('group',{name:'Map leaderboard Top revenue exposure',exact:true}).getByRole('combobox',{name:'Ranking title field',exact:true}).selectOption('name');const group=dialog.getByRole('group',{name:'Map object comparison Compare selected',exact:true});await group.getByRole('combobox',{name:'Comparison title field',exact:true}).selectOption('name');for(const field of ['Owner','Pressure','Temperature'])await group.getByRole('button',{name:field,exact:true}).click();}
  await dialog.getByRole('checkbox').last().check();await expect(dialog.getByRole('button',{name:'Apply imported page draft',exact:true})).toBeEnabled();const downloading=page.waitForEvent('download');await dialog.getByRole('button',{name:'Download mapping report',exact:true}).click();const download=await downloading,path=await download.path();if(!path)throw Error('Missing report');const report=JSON.parse(readFileSync(path,'utf8'));expect(report.source).toBe(source);expect(report.bindings.application.recordSets.selectedAssets).toEqual({variable:'records',writable:sourcePage==='pOperations'});
  await dialog.getByRole('button',{name:'Apply imported page draft',exact:true}).click();const tree=page.getByRole('region',{name:'Widgets and layout',exact:true}),inspector=page.getByRole('region',{name:'The widget in hand',exact:true});await tree.getByRole('button',{name:sourcePage==='pOperations'?'Assets':'Compare selected',exact:true}).click();await expect(inspector.getByRole('combobox',{name:sourcePage==='pOperations'?'Record selection set output':'Input record set binding',exact:true})).not.toHaveValue('');await page.getByRole('button',{name:'Save',exact:true}).click();let saved:any;await expect.poll(async()=>{saved=(await(await request.get(`/v1/records/build.page/${id}`,{headers})).json()).record;return saved.sections.length;}).toBe(3);
  saved.sections.push({id:'next',widget:'button',configVersion:1,title});saved.document.nodes.next={kind:'widget',section:'next'};saved.document.nodes[saved.document.root].children.push('next');saved.document.events=[...(saved.document.events??[]),{source:'next',event:'click',target:'',navigate:{page:{app:'build',kind:'page',name:target},interfaceVersion:0}}];
  if(sourcePage==='pAnalytics'){const comparison=saved.sections.find((s:any)=>s.widget==='record-comparison');saved.sections.push({...structuredClone(comparison),id:'private',title:'Private comparison title',recordComparison:{labelField:'secret'}});saved.document.nodes.private={kind:'widget',section:'private'};saved.document.nodes[saved.document.root].children.push('private');}
  await decide(request,'manager','build','build.page.edit',{type:'build.page',id:id!},{sections:saved.sections,document:saved.document});await decide(request,'manager','build','build.page.publish',{type:'build.page',id:id!},{});savedPages.push(saved);
 }
 await open(page,'manager',`/application?id=${app}`);await page.getByRole('combobox',{name:'Choose application variable',exact:true}).selectOption('records');await expect(page.getByRole('combobox',{name:'Resource output kind',exact:true})).toHaveValue('record-set');await expect(page.getByRole('combobox',{name:'Selection object',exact:true})).toHaveValue(type);await page.getByRole('button',{name:'Review application release',exact:true}).click();await page.getByRole('button',{name:'Check draft and dependencies',exact:true}).click();await page.getByRole('button',{name:'Save immutable candidate',exact:true}).click();await page.getByRole('button',{name:'Activate release',exact:true}).click();const later=structuredClone(savedPages[1].sections);later.find((s:any)=>s.widget==='record-comparison').fields=['name'];await decide(request,'manager','build','build.page.edit',{type:'build.page',id:analytics},{sections:later});
 const runtime=await page.context().newPage();runtime.setDefaultTimeout(10_000);await stableReadRevision(runtime);const route=`/page?app=build&kind=page&name=${name}operations&application=${application}&instance=main`;await open(runtime,'desk',route);const frame=(title:string)=>runtime.getByRole('heading',{name:title,exact:true,level:3}).locator('..'),table=runtime.getByRole('heading',{name:/^Assets \(\d+\)$/,level:3}).locator('..'),comparison=frame('Compare selected'),detail=frame('Properties'),pick=(n:number)=>table.getByRole('checkbox',{name:`Select R${String(n).padStart(2,'0')}`,exact:true}),go=()=>runtime.getByRole('button',{name:'Go to Analytics',exact:true}).click(),back=()=>runtime.getByRole('button',{name:'Back to Operations',exact:true}).click();
 await pick(0).check();await pick(1).check();await expect(table.getByText('2 records selected in this window',{exact:true})).toBeVisible();await go();await expect(comparison.getByRole('table')).toBeVisible();await expect(comparison.getByRole('columnheader').filter({hasText:/Asset 0[01]/})).toHaveCount(2);await expect(comparison.getByRole('rowheader').filter({hasText:'Owner'}).locator('..')).toContainText('Different');await expect(runtime.getByRole('heading',{name:'Private comparison title',exact:true})).toHaveCount(0);
 await frame('Top revenue exposure').getByRole('button',{name:'Asset 11',exact:true}).click();await expect(comparison.getByRole('columnheader').filter({hasText:/Asset 0[01]/})).toHaveCount(2);await frame('Pressure vs temperature').getByRole('group',{name:'Record scatter plot',exact:true}).getByRole('button',{name:/R03 · Pressure:/}).focus();await frame('Pressure vs temperature').getByRole('group',{name:'Record scatter plot',exact:true}).getByRole('button',{name:/R03 · Pressure:/}).press('Enter');await back();await expect(detail.getByRole('definition').filter({hasText:/^Asset 03$/})).toBeVisible();await expect(pick(0)).toBeChecked();await expect(pick(1)).toBeChecked();
 for(const n of [2,3,4])await pick(n).check();await go();await expect(comparison.getByRole('alert')).toBeVisible();await expect(comparison.getByRole('table')).toHaveCount(0);await back();await pick(4).uncheck();await go();await expect(comparison.getByRole('columnheader').filter({hasText:/Asset 0[0-3]/})).toHaveCount(4);if(process.env.PLATFORM_SCREENSHOTS)await comparison.screenshot({path:info.outputPath('original-cross-page-comparison.png')});await back();
 await runtime.route(`**/v1/records/${type}/R05`,r=>r.fulfill({status:403,contentType:'application/json',body:JSON.stringify({error:{message:'Denied'}})}));await pick(5).click();await expect(table.getByRole('alert').filter({hasText:'Selection read failed'})).toBeVisible();await go();await expect(comparison.getByRole('table')).toHaveCount(0);await runtime.unroute(`**/v1/records/${type}/R05`);await back();await pick(0).check();
 let release:()=>void=()=>{},held=false;const gate=new Promise<void>(resolve=>release=resolve);await runtime.route(`**/v1/records/${type}/R06`,async r=>{held=true;const response=await r.fetch();await gate;await r.fulfill({response});});await pick(6).check();await expect.poll(()=>held).toBe(true);await runtime.getByRole('textbox',{name:'Original search',exact:true}).fill('Asset 09');await expect(table.getByRole('cell',{name:'Asset 09',exact:true})).toBeVisible();const completed=runtime.waitForResponse(r=>r.url().endsWith(`/${type}/R06`));release();await completed;await go();await expect(comparison.getByText('Select two to four records to compare.',{exact:true})).toBeVisible();await runtime.unroute(`**/v1/records/${type}/R06`);await back();await runtime.getByRole('textbox',{name:'Original search',exact:true}).fill('');await pick(0).check();await pick(1).check();await go();await expect(comparison.getByRole('table')).toBeVisible();
 await runtime.getByRole('button',{name:'Close application instance',exact:true}).click();await runtime.evaluate(route=>{location.hash=route},route);await go();await expect(comparison.getByText('Select two to four records to compare.',{exact:true})).toBeVisible();
});
