import {expect,test} from "@playwright/test";
import {readFileSync} from "node:fs";
import {decide,fresh,open,pageUIProfile,stableReadRevision} from "./host";

test("ObjectComparison freezes original selected IDs and typed differences while permissions and obsolete reads retire complete comparisons",async({page,request},info)=>{
 test.setTimeout(120_000);
 const name=fresh("compare").replace(/[^a-z0-9]/gi,"").toLowerCase(),type=`build.${name}`,object=fresh("OBJ"),id=fresh("PAGE");
 await decide(request,"manager","build","build.object.create",{type:"build.object",id:object},{name,title:"Comparison assets",fields:[{name:"name",title:"Asset title",type:"text"},{name:"amount",title:"Amount",type:"decimal"},{name:"active",title:"Active",type:"boolean"},{name:"day",title:"Date",type:"date"},{name:"missing",title:"Missing",type:"text"},{name:"secret",title:"Private property",type:"text",read:["builder"]}]});
 await decide(request,"manager","build","build.object.publish",{type:"build.object",id:object},{});
 for(let i=0;i<7;i++)await decide(request,"manager","build",`${type}.create`,{type,id:`${name}${i}`},{name:i<2?"Same title":`Other asset ${i}`,amount:i===0?1.001:i===1?1.002:i,active:false,day:"2026-10-03",secret:"Never visible"});
 const m=JSON.parse(readFileSync(new URL("../../packages/build/src/module-import/sample.workshop.json",import.meta.url),"utf8"));
 const set=(id:string,input:string)=>({id,name:id,type:"objectSet",definitionKind:"objectSetDefinition",sourceObjectType:"Asset",objectSet:{objectType:"Asset",steps:[{op:"where",clauses:[{property:"name",op:"contains",varId:input}]}]}}),state=(id:string)=>({id,name:id,type:"string",definitionKind:"static",staticValue:""}),selected=(id:string,widget:string)=>({id,name:id,type:"array",definitionKind:"widgetOutput",widgetId:widget,widgetOutputKey:"selectedObjects"}),table=(id:string,title:string,setID:string,selectedID:string)=>({id,name:title,type:"ObjectTable",config:{objectSetVarId:setID,selectedVarId:selectedID,selectionMode:"multiple",columns:[{key:"name",label:"Title"}]}}),comparison=(id:string,title:string,variable:string)=>({id,name:title,type:"ObjectComparison",config:{objectsVarId:variable}});
 m.variables=[state("filter"),set("notes","filter"),selected("selected","table"),state("localFilter"),set("localNotes","localFilter"),selected("localSelected","localTable")];
 m.widgets={input:{id:"input",name:"Record filter",type:"TextInput",config:{variableId:"filter",label:"Record filter"}},table:table("table","Comparison records","notes","selected"),comparison:comparison("comparison","Selected comparison","selected"),hidden:comparison("hidden","Private title comparison","selected"),localTable:table("localTable","Local records","localNotes","localSelected"),localComparison:comparison("localComparison","Local comparison","localSelected"),localInput:{id:"localInput",name:"Local filter",type:"TextInput",config:{variableId:"localFilter",label:"Local filter"}},trigger:{id:"trigger",name:"Open comparison",type:"SingleButton",config:{label:"Open comparison",eventActions:[{kind:"openOverlay",overlayId:"panel"}]}},close:{id:"close",name:"Close comparison",type:"SingleButton",config:{label:"Close comparison",eventActions:[{kind:"closeOverlay",overlayId:"panel"}]}}};
 m.sections={root:{id:"root",name:"Root",layout:"rows",children:["input","table","comparison","hidden","trigger"].map(id=>({kind:"widget",id}))},panel:{id:"panel",name:"Panel",layout:"rows",children:["localInput","localTable","localComparison","close"].map(id=>({kind:"widget",id}))}};m.overlays=[{id:"panel",name:"Comparison panel",kind:"drawer",rootSectionId:"panel"}];
 await decide(request,"manager","build","build.page.create",{type:"build.page",id},{name,title:"Comparison work",object:type,sections:[{id:"initial",widget:"text",configVersion:1,text:"Initial"}],document:{formatVersion:2,uiProfile:pageUIProfile,root:"root",nodes:{root:{kind:"rows",children:["initial"]},initial:{kind:"widget",section:"initial"}}}});
 await open(page,"manager",`/compose?id=${id}`);await page.getByRole("button",{name:"Import Workshop module",exact:true}).click();const dialog=page.getByRole("dialog",{name:"Import Workshop module",exact:true});
 await dialog.getByRole("textbox",{name:"Source module JSON",exact:true}).fill(JSON.stringify(m));await dialog.getByRole("combobox",{name:"Map object Asset",exact:true}).selectOption(type);await dialog.getByRole("combobox",{name:"Map field Asset.name",exact:true}).selectOption("name");
 for(const [title,label] of [["Selected comparison","name"],["Private title comparison","secret"],["Local comparison","name"]]){const mapping=dialog.getByRole("group",{name:`Map object comparison ${title}`,exact:true});await mapping.getByRole("combobox",{name:"Comparison title field",exact:true}).selectOption(label);for(const field of ["Amount","Active","Date","Missing","Private property"])await mapping.getByRole("button",{name:field,exact:true}).click();}
 await dialog.getByRole("checkbox").check();await expect(dialog.getByRole("button",{name:"Apply imported page draft",exact:true})).toBeEnabled();await dialog.getByRole("button",{name:"Apply imported page draft",exact:true}).click();
 await page.getByRole("region",{name:"Widgets and layout",exact:true}).getByRole("button",{name:"Selected comparison",exact:true}).click();const inspector=page.getByRole("region",{name:"The widget in hand",exact:true});await expect(inspector.getByRole("combobox",{name:"Comparison title field",exact:true})).toHaveValue("name");await inspector.getByRole("combobox",{name:"Comparison title field",exact:true}).selectOption("id");await inspector.getByRole("combobox",{name:"Comparison title field",exact:true}).selectOption("name");await page.getByRole("button",{name:"Save",exact:true}).click();
 let saved:any;await expect.poll(async()=>{saved=(await(await request.get(`/v1/records/build.page/${id}`,{headers:{Authorization:"Bearer manager"}})).json()).record;return saved.sections?.filter((s:any)=>s.widget==="record-comparison").length;}).toBe(3);
 await page.getByRole("button",{name:"Review release",exact:true}).click();await page.getByRole("button",{name:"Check draft and dependencies",exact:true}).click();await page.getByRole("button",{name:"Save immutable candidate",exact:true}).click();saved.sections.find((s:any)=>s.title==="Selected comparison").recordComparison={labelField:"id"};saved.sections.find((s:any)=>s.title==="Selected comparison").fields=["name"];await decide(request,"manager","build","build.page.edit",{type:"build.page",id},{sections:saved.sections,document:saved.document});await page.getByRole("button",{name:"Activate release",exact:true}).click();
 const runtime=await page.context().newPage();await stableReadRevision(runtime);await open(runtime,"desk",`/page?app=build&kind=page&name=${name}`);const section=(title:string)=>runtime.getByRole("heading",{name:title,exact:true}).locator(".."),summary=section("Selected comparison"),tableView=section("Comparison records"),input=runtime.getByRole("textbox",{name:"Record filter",exact:true}),pick=(target:any,i:number)=>target.getByRole("checkbox",{name:`Select ${name}${i}`,exact:true});
 await expect(summary.getByText("Select two to four records to compare.",{exact:true})).toBeVisible();await expect(runtime.getByRole("heading",{name:"Private title comparison",exact:true})).toHaveCount(0);
 await pick(tableView,0).check();await expect(summary.getByRole("table")).toHaveCount(0);
 let release:()=>void=()=>{};const gate=new Promise<void>(r=>release=r);let started=false;await runtime.route(`**/v1/records/${type}/${name}1`,async route=>{started=true;const response=await route.fetch();await gate;await route.fulfill({response});});await pick(tableView,1).check();await expect.poll(()=>started).toBe(true);await expect(summary.getByText("Confirming selected record access…",{exact:true})).toBeVisible();await expect(summary.getByRole("table")).toHaveCount(0);const confirmed=runtime.waitForResponse(r=>r.url().endsWith(`/${type}/${name}1`));release();await confirmed;await runtime.unroute(`**/v1/records/${type}/${name}1`);
 await expect(summary.getByRole("columnheader").filter({hasText:"Same title"})).toHaveCount(2);for(const i of [0,1])await expect(summary.getByText(`${name}${i}`,{exact:true})).toBeVisible();await expect(summary.getByText("Never visible",{exact:true})).toHaveCount(0);await expect(summary.getByText("Private property",{exact:true})).toHaveCount(0);
 const valueRow=(label:string)=>summary.getByRole("row").filter({hasText:label});await expect(valueRow("Amount")).toContainText("Different");await expect(valueRow("Amount").getByRole("cell").filter({hasText:/^1\.00$/})).toHaveCount(2);await expect(valueRow("Active")).toContainText("Same");await expect(valueRow("Date")).toContainText("Same");await expect(valueRow("Missing")).toContainText("Same");
 if(process.env.PLATFORM_SCREENSHOTS){await summary.scrollIntoViewIfNeeded();await summary.screenshot({path:info.outputPath("record-comparison.png")});await runtime.setViewportSize({width:390,height:844});await summary.scrollIntoViewIfNeeded();await summary.screenshot({path:info.outputPath("record-comparison-narrow.png")});await runtime.setViewportSize({width:1280,height:720});}
 for(const i of [2,3])await pick(tableView,i).check();await expect(summary.getByRole("columnheader").filter({hasText:name})).toHaveCount(4);await pick(tableView,4).check();await expect(summary.getByRole("alert")).toBeVisible();await expect(summary.getByRole("table")).toHaveCount(0);await pick(tableView,4).uncheck();await expect(summary.getByRole("table")).toBeVisible();
 await pick(tableView,2).uncheck();await runtime.route(`**/v1/records/${type}/${name}5`,route=>route.fulfill({status:403,contentType:"application/json",body:JSON.stringify({error:{message:"Denied"}})}));await pick(tableView,5).click();await expect(summary.getByRole("alert")).toContainText("could not be loaded");await expect(summary.getByRole("table")).toHaveCount(0);await runtime.unroute(`**/v1/records/${type}/${name}5`);
 await input.fill("Other asset 4");await expect(tableView.getByRole("cell",{name:"Other asset 4",exact:true})).toBeVisible();await input.fill("");await expect(pick(tableView,0)).toBeVisible();await pick(tableView,0).check();
 let releaseOld:()=>void=()=>{};const oldGate=new Promise<void>(r=>releaseOld=r);let oldStarted=false;await runtime.route(`**/v1/records/${type}/${name}6`,async route=>{oldStarted=true;const response=await route.fetch();await oldGate;await route.fulfill({response});});await pick(tableView,6).check();await expect.poll(()=>oldStarted).toBe(true);await input.fill("Other asset 4");await expect(tableView.getByRole("cell",{name:"Other asset 4",exact:true})).toBeVisible();await expect(summary.getByText("Select two to four records to compare.",{exact:true})).toBeVisible();const completed=runtime.waitForResponse(r=>r.url().endsWith(`/${type}/${name}6`));releaseOld();await completed;await runtime.evaluate(()=>new Promise<void>(r=>requestAnimationFrame(()=>requestAnimationFrame(()=>r()))));await expect(summary.getByRole("table")).toHaveCount(0);await runtime.unroute(`**/v1/records/${type}/${name}6`);
 await runtime.getByRole("button",{name:"Open comparison",exact:true}).click();const panel=runtime.getByRole("dialog",{name:"Comparison panel",exact:true}),local=panel.getByRole("heading",{name:"Local comparison",exact:true}).locator(".."),localTable=panel.getByRole("heading",{name:"Local records",exact:true}).locator(".."),localInput=panel.getByRole("textbox",{name:"Local filter",exact:true});await pick(localTable,0).check();await pick(localTable,1).check();await expect(local.getByRole("table")).toBeVisible();await expect(summary.getByRole("table")).toHaveCount(0);await localInput.fill("Other asset 4");await expect(local.getByRole("table")).toHaveCount(0);await panel.getByRole("button",{name:"Close comparison",exact:true}).click();await runtime.getByRole("button",{name:"Open comparison",exact:true}).click();await expect(localInput).toHaveValue("");await expect(local.getByText("Select two to four records to compare.",{exact:true})).toBeVisible();await panel.getByRole("button",{name:"Close comparison",exact:true}).click();
});
