import {expect,test} from '@playwright/test';
import {defaultConsumerGroup} from '../../packages/build/src/workshop/module-import/default-consumers.fixture.mjs';
import {decide,fresh,open,pageUIProfile} from './host';
test('original page and drawer title links and lifecycle consumers share authorized inputs and freeze together',async({page,request},info)=>{
 test.setTimeout(180_000);page.setDefaultTimeout(10_000);
 const name=fresh('consumers').replace(/[^a-z0-9]/gi,'').toLowerCase(),type=`build.${name}`,object=fresh('OBJ'),parent=fresh('PAGE'),app=fresh('APP'),headers={Authorization:'Bearer manager'},stages=['Active','Warning','Maintenance','Offline'];
 await decide(request,'manager','build','build.object.create',{type:'build.object',id:object},{name,title:'Original consumer assets',fields:[{name:'name',title:'Name',type:'text',search:true},{name:'priority',title:'Priority',type:'choice',choices:'High,Low'},{name:'owner',title:'Owner',type:'text'},{name:'pressure',title:'Pressure',type:'integer'}],states:stages.map(title=>({name:title.toLowerCase(),title})),actions:[{name:'warn',title:'Mark warning',from:['active'],to:'warning'}]});await decide(request,'manager','build','build.object.publish',{type:'build.object',id:object},{});
 for(const id of ['A','B',...Array.from({length:100},(_,n)=>`Z${String(n).padStart(3,'0')}`)])await decide(request,'desk','build',`${type}.create`,{type,id},{name:`Original ${id}`,priority:'High',owner:'Owner',pressure:20});
 await decide(request,'desk','build',`${type}.warn`,{type,id:'B'},{});
 const groups=['sensor','alert','work'];for(const kind of groups){const id=fresh('OBJ');await decide(request,'manager','build','build.object.create',{type:'build.object',id},{name:`${name}${kind}`,title:`Original ${kind} records`,fields:[{name:'label',title:'Label',type:'text'},{name:'asset',title:'Asset',type:'reference',ref:type,inverse:kind,...kind==='alert'?{read:['builder']}:{}}]});await decide(request,'manager','build','build.object.publish',{type:'build.object',id},{});}
 for(const asset of ['A','B'])for(const kind of groups){const child=`build.${name}${kind}`;for(let n=0;n<(kind==='sensor'&&asset==='B'?25:1);n++)await decide(request,'manager','build',`${child}.create`,{type:child,id:`${kind}-${asset}-${n}`},{label:`${kind.toUpperCase()}-${asset}-${n}`,asset});}
 await decide(request,'manager','build','build.page.create',{type:'build.page',id:parent},{name:`${name}page`,title:'Original consumer task',object:type,sections:[{id:'initial',widget:'text',configVersion:1,text:'Initial'}],document:{formatVersion:2,uiProfile:pageUIProfile,root:'root',nodes:{root:{kind:'rows',children:['initial']},initial:{kind:'widget',section:'initial'}}}});await decide(request,'manager','build','build.page.publish',{type:'build.page',id:parent},{});
 const ref={app:'build',kind:'object',name:type};await decide(request,'manager','build','build.app.create',{type:'build.app',id:app},{name:`${name}app`,title:'Original consumer desk',pages:[`${name}page`],uiProfile:pageUIProfile,variables:{record:{scope:'application',type:'record',mode:'resource',source:{kind:'record',object:ref}}}});await decide(request,'manager','build','build.app.publish',{type:'build.app',id:app},{});
 const defs=await(await request.get('/v1/definitions',{headers})).json(),definition=defs.find((d:any)=>d.ref.kind==='app'&&d.ref.name===`${name}app`),binding={ref:definition.ref,sourceVersion:definition.version},module=defaultConsumerGroup();
 await open(page,'manager',`/compose?id=${parent}`);await page.getByRole('button',{name:'Import Workshop module',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Import Workshop module',exact:true});await dialog.getByRole('textbox',{name:'Source module JSON',exact:true}).fill(JSON.stringify(module));await dialog.getByRole('combobox',{name:'Map object Asset',exact:true}).selectOption(type);
 for(const field of ['name','status','priority','owner','pressure'])await dialog.getByRole('combobox',{name:`Map field Asset.${field}`,exact:true}).selectOption(field==='status'?'state':field);
 await dialog.getByRole('combobox',{name:'Reviewed original application',exact:true}).selectOption(JSON.stringify(binding));await dialog.getByRole('combobox',{name:'Map module port selectedAsset',exact:true}).selectOption('record');
 for(const state of stages)await dialog.getByRole('combobox',{name:`Map lifecycle state ${state}`,exact:true}).selectOption(state.toLowerCase());
 for(const [n,label] of ['Sensors','Alerts','Work Orders'].entries())for(const chooser of await dialog.getByRole('combobox',{name:`Map related group ${label}`,exact:true}).all())await chooser.selectOption(JSON.stringify([`build.${name}${groups[n]}`,'asset']));
 await dialog.getByRole('checkbox').last().check();await expect(dialog.getByRole('button',{name:'Apply imported page draft',exact:true})).toBeEnabled();await dialog.getByRole('button',{name:'Apply imported page draft',exact:true}).click();await page.getByRole('button',{name:'Save',exact:true}).click();
 let saved:any;await expect.poll(async()=>{saved=(await(await request.get(`/v1/records/build.page/${parent}`,{headers})).json()).record;return saved.sections.filter((s:any)=>s.widget==='collection-title').length;}).toBe(2);
 const titles=saved.sections.filter((s:any)=>s.widget==='collection-title');expect(titles[0].countVariable).toBe(titles[1].countVariable);expect(saved.document.variables[titles[0].countVariable].scope).toBe('page');await decide(request,'manager','build','build.page.publish',{type:'build.page',id:parent},{});
 await open(page,'manager',`/application?id=${app}`);await page.getByRole('button',{name:'Review application release',exact:true}).click();await page.getByRole('button',{name:'Check draft and dependencies',exact:true}).click();await page.getByRole('button',{name:'Save immutable candidate',exact:true}).click();await page.getByRole('button',{name:'Activate release',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'Release active for operators.'})).toBeVisible();
 const later=structuredClone(saved.sections);later.filter((s:any)=>s.widget==='record-links').forEach((s:any)=>s.recordLinks[0].title='Later draft sensor group');later.find((s:any)=>s.widget==='status-tracker').statusTracker.stages=['active'];await decide(request,'manager','build','build.page.edit',{type:'build.page',id:parent},{sections:later});
 const runtime=await page.context().newPage();runtime.setDefaultTimeout(10_000);await open(runtime,'desk',`/page?app=build&kind=page&name=${name}page&application=build:${name}app&instance=main`);
 const table=runtime.getByRole('heading',{name:'Original asset selector',exact:true,level:3}).locator('..'),count=runtime.getByRole('status',{name:'Complete collection count',exact:true});await expect(count).toHaveText('102');
 const sourceLink=module.widgets.wLinks1!,sourceStatus=module.widgets.wStatusTracker!,links=runtime.getByRole('heading',{name:sourceLink.name,exact:true,level:3}).locator('..'),tracker=runtime.getByRole('heading',{name:sourceStatus.name,exact:true,level:3}).locator('..');
 await table.getByRole('cell',{name:'Original A',exact:true}).click();await expect(tracker.locator('li[aria-current="step"]')).toHaveText('Active');await expect(links.getByRole('cell',{name:'SENSOR-A-0',exact:true})).toBeVisible();await expect(links.getByRole('cell',{name:'ALERT-A-0',exact:true})).toHaveCount(0);
 await runtime.getByRole('textbox',{name:'Search',exact:true}).and(runtime.locator('input:not([disabled])')).fill('Original B');await expect(count).toHaveText('1');await table.getByRole('cell',{name:'Original B',exact:true}).click();await expect(tracker.locator('li[aria-current="step"]')).toHaveText('Warning');await expect(tracker.getByRole('listitem')).toHaveCount(4);await expect(links.getByRole('heading',{name:/^Sensors \(25/})).toBeVisible();await expect(links.getByRole('cell',{name:'WORK-B-0',exact:true})).toBeVisible();await expect(links.getByRole('cell',{name:'SENSOR-A-0',exact:true})).toHaveCount(0);await expect(links.getByText('Later draft sensor group')).toHaveCount(0);
 await runtime.getByRole('button',{name:'Open original consumer drawer',exact:true}).click();const popup=runtime.getByRole('dialog',{name:'Asset Detail Drawer',exact:true});await expect(popup.getByRole('status',{name:'Complete collection count',exact:true})).toHaveText('1');await expect(popup.getByRole('heading',{name:/^Sensors \(25/})).toBeVisible();await expect(popup.getByRole('cell',{name:'WORK-B-0',exact:true})).toBeVisible();await expect(popup.getByRole('cell',{name:'ALERT-B-0',exact:true})).toHaveCount(0);if(process.env.PLATFORM_SCREENSHOTS)await popup.screenshot({path:info.outputPath('default-consumer-drawer.png')});
 await popup.getByRole('button',{name:'Close',exact:true}).click();await expect(count).toHaveText('1');await expect(runtime.getByRole('textbox',{name:'Search',exact:true}).and(runtime.locator('input:not([disabled])'))).toHaveValue('Original B');await runtime.getByRole('button',{name:'Open original consumer drawer',exact:true}).click();await expect(popup.getByRole('status',{name:'Complete collection count',exact:true})).toHaveText('1');await expect(popup.getByRole('cell',{name:'WORK-B-0',exact:true})).toBeVisible();await popup.getByRole('cell',{name:'WORK-B-0',exact:true}).click();await expect(popup).not.toBeVisible();const opened=runtime.getByRole('dialog',{name:'work-B-0',exact:true});await expect(opened.getByRole('definition').filter({hasText:/^WORK-B-0$/})).toBeVisible();await opened.getByRole('button',{name:'Edit',exact:true}).click();const edit=runtime.getByRole('dialog',{name:'Edit work-B-0',exact:true});await expect(edit.getByRole('textbox',{name:'Label',exact:true})).toHaveValue('WORK-B-0');await edit.getByRole('button',{name:'Cancel',exact:true}).click();await expect(edit).not.toBeVisible();
});
