import {expect,test} from "@playwright/test";
import {decide,fresh,open,pageUIProfile} from "./host";

test("context commands stage stable widgets and freeze dormant reads while copies keep independent inputs",async({page,request},testInfo)=>{
 test.setTimeout(60_000);
 const name=fresh("unused").replace(/[^a-z0-9]/gi,"").toLowerCase(),type=`build.${name}`,spare=`build.${name}spare`,id=fresh("PAGE");
 for(const suffix of ["","spare"]){const object=fresh("OBJ");await decide(request,"manager","build","build.object.create",{type:"build.object",id:object},{name:name+suffix,title:suffix?"Spare records":"Working records",states:[{name:"open",title:"Open"},{name:"done",title:"Done"}],actions:[{name:"close",title:"Complete staged work",from:["open"],to:"done"}],fields:[{name:"title",title:"Title",type:"text"}]});await decide(request,"manager","build","build.object.publish",{type:"build.object",id:object},{});await decide(request,"desk","build",`${suffix?spare:type}.create`,{type:suffix?spare:type,id:"WORK"},{title:suffix?"SPARE-WORK":"ORIGINAL-WORK"});}
 const ids=["table","detail","actions","spare","scratch","toggle"];
 await decide(request,"manager","build","build.page.create",{type:"build.page",id},{name,title:"Staged work desk",object:type,sections:[{id:"table",widget:"table",configVersion:1,title:"Work choices",fields:["title"]},{id:"detail",widget:"detail",configVersion:1,title:"Chosen work",fields:["title","state"]},{id:"actions",widget:"actions",configVersion:1,title:"Original actions",actions:[`${type}.close`]},{id:"spare",widget:"table",configVersion:1,title:"Spare choices",object:spare,fields:["title"]},{id:"scratch",widget:"input",configVersion:1,title:"Scratch input"},{id:"toggle",widget:"button",configVersion:1,title:"Dormant command"},{id:"overlayInput",widget:"input",configVersion:1,title:"Overlay scratch"}],document:{formatVersion:2,uiProfile:pageUIProfile,root:"root",nodes:{root:{kind:"rows",children:ids},panelRoot:{kind:"rows",children:["overlayInput"]},overlayInput:{kind:"widget",section:"overlayInput",valueVariable:"overlayState"},...Object.fromEntries(ids.map(section=>[section,{kind:"widget",section,...(section==="scratch"?{valueVariable:"scratchState"}:{})}]))},overlays:{panel:{root:"panelRoot",kind:"drawer",title:"Scratch panel",openVariable:"toggled"}},variables:{overlayState:{scope:"overlay",owner:"panel",type:"string",mode:"state",initial:"local"},scratchState:{scope:"page",type:"string",mode:"state",initial:"seed"},toggled:{scope:"page",type:"boolean",mode:"state",initial:false}},events:[{source:"toggle",event:"click",target:"toggled",value:true}]}});
 await open(page,"manager",`/compose?id=${id}`);const tree=page.getByRole("region",{name:"Widgets and layout",exact:true}),unused=tree.getByRole("region",{name:"Unused widgets",exact:true}),inspector=page.getByRole("region",{name:"The widget in hand",exact:true});
 // Pointer context opening and the visible trigger expose the same operation.
 await tree.getByRole("button",{name:"Spare choices",exact:true}).click({button:"right"});await page.getByRole("menuitem",{name:"Move to unused widgets",exact:true}).click();await expect(unused.getByRole("button",{name:"Spare choices",exact:true})).toBeVisible();
 await page.getByRole("button",{name:"Undo",exact:true}).click();await expect(unused.getByRole("button",{name:"Spare choices",exact:true})).toHaveCount(0);await page.getByRole("button",{name:"Redo",exact:true}).click();await expect(unused.getByRole("button",{name:"Spare choices",exact:true})).toBeVisible();
 await tree.getByRole("button",{name:"Scratch input",exact:true}).focus();await page.keyboard.press("Shift+F10");await page.getByRole("menuitem",{name:"Move to unused widgets",exact:true}).click();
 await unused.getByRole("button",{name:"Commands for Scratch input",exact:true}).click();await page.getByRole("menuitem",{name:"Duplicate widget",exact:true}).click();await inspector.getByLabel("Title",{exact:true}).fill("Scratch copy");
 await unused.getByRole("button",{name:"Commands for Scratch copy",exact:true}).click();await page.getByRole("menuitem",{name:"Put back in original layout",exact:true}).click();await unused.getByRole("button",{name:"Commands for Scratch input",exact:true}).click();await page.getByRole("menuitem",{name:"Put back in original layout",exact:true}).click();
 const canvas=page.getByRole("region",{name:"The page",exact:true}),original=canvas.getByRole("textbox",{name:"Scratch input",exact:true}),copy=canvas.getByRole("textbox",{name:"Scratch copy",exact:true});await original.fill("alpha");await expect(copy).toHaveValue("seed");await copy.fill("beta");await expect(original).toHaveValue("alpha");
 for(const title of ["Scratch input","Dormant command","Overlay scratch"]){await tree.getByRole("button",{name:`Commands for ${title}`,exact:true}).click();await page.getByRole("menuitem",{name:"Move to unused widgets",exact:true}).click();}
 // Delete a temporary dormant duplicate through the same command owner.
 await unused.getByRole("button",{name:"Commands for Dormant command",exact:true}).click();await page.getByRole("menuitem",{name:"Duplicate widget",exact:true}).click();await inspector.getByLabel("Title",{exact:true}).fill("Disposable command");await unused.getByRole("button",{name:"Commands for Disposable command",exact:true}).click();await page.getByRole("menuitem",{name:"Delete widget",exact:true}).click();await expect(unused.getByRole("button",{name:"Disposable command",exact:true})).toHaveCount(0);await expect(canvas.getByRole("heading",{name:"Work choices",exact:true})).toBeVisible();
 if(process.env.PLATFORM_SCREENSHOTS){await page.setViewportSize({width:1280,height:1000});await unused.screenshot({path:testInfo.outputPath("unused-inventory.png")});await unused.getByRole("button",{name:"Commands for Spare choices",exact:true}).click();await page.screenshot({path:testInfo.outputPath("unused-commands.png"),fullPage:true});await page.keyboard.press("Escape");}
 await page.getByRole("button",{name:"Save",exact:true}).click();await expect(page.getByRole("button",{name:"Save",exact:true})).toBeDisabled();const saved=(await(await request.get(`/v1/records/build.page/${id}`,{headers:{Authorization:"Bearer manager"}})).json()).record;
 expect(saved.document.unusedWidgets.map((e:any)=>e.node).sort()).toEqual(["overlayInput","scratch","spare","toggle"]);expect(saved.document.nodes.root.children).not.toContain("spare");expect(saved.sections.find((s:any)=>s.id==="spare").object).toBe(spare);const copySection=saved.sections.find((s:any)=>s.title==="Scratch copy"),copyNode=Object.values(saved.document.nodes).find((n:any)=>n.section===copySection.id) as any;expect(copyNode.valueVariable).not.toBe("scratchState");expect(saved.document.variables[copyNode.valueVariable].initial).toBe("seed");expect(saved.document.events.some((e:any)=>e.source==="toggle")).toBe(true);
 await page.getByRole("button",{name:"Review release",exact:true}).click();await page.getByRole("button",{name:"Check draft and dependencies",exact:true}).click();await page.getByRole("button",{name:"Save immutable candidate",exact:true}).click();for(const entry of saved.document.unusedWidgets)(saved.document.nodes[entry.parent].children??=[]).push(entry.node);saved.document.unusedWidgets=[];await decide(request,"manager","build","build.page.edit",{type:"build.page",id},{document:saved.document});await page.getByRole("button",{name:"Activate release",exact:true}).click();
 const operation=await page.context().newPage();let spareReads=0;operation.on("request",r=>{if(new URL(r.url()).pathname.startsWith(`/v1/records/${spare}`))spareReads++;});await open(operation,"desk",`/page?app=build&kind=page&name=${name}`);await expect(operation.getByRole("row").filter({hasText:"ORIGINAL-WORK"})).toBeVisible();await expect(operation.getByRole("heading",{name:"Spare choices",exact:true})).toHaveCount(0);await expect(operation.getByRole("button",{name:"Dormant command",exact:true})).toHaveCount(0);await expect(operation.getByRole("textbox",{name:"Scratch input",exact:true})).toHaveCount(0);await operation.getByRole("textbox",{name:"Scratch copy",exact:true}).fill("runtime copy");
 const detail=operation.getByRole("heading",{name:"Chosen work",exact:true}).locator("..");await operation.getByRole("row").filter({hasText:"ORIGINAL-WORK"}).click();await expect(detail.getByText("ORIGINAL-WORK",{exact:true})).toBeVisible();await operation.getByRole("button",{name:"Complete staged work",exact:true}).click();await expect(detail.getByText("Done",{exact:true})).toBeVisible();await operation.reload();await expect(operation.getByRole("textbox",{name:"Scratch copy",exact:true})).toHaveValue("seed");await expect(operation.getByRole("row").filter({hasText:"ORIGINAL-WORK"})).toBeVisible();expect(spareReads).toBe(0);
 if(process.env.PLATFORM_SCREENSHOTS){await operation.setViewportSize({width:390,height:844});await operation.screenshot({path:testInfo.outputPath("unused-runtime-narrow.png"),fullPage:true});}
});
