import {expect,test} from "@playwright/test";
import {readFileSync} from "node:fs";
import {decide,fresh,open,pageUIProfile,stableReadRevision} from "./host";

test("imported active and multi-record ports stay distinct, authorized, producer-scoped and retired with their windows and overlays",async({page,request},info)=>{
 test.setTimeout(90_000);
 const m=JSON.parse(readFileSync(new URL("../../packages/build/src/module-import/sample.workshop.json",import.meta.url),"utf8")),name=fresh("sets").replace(/[^a-z0-9]/gi,"").toLowerCase(),type=`build.${name}`,object=fresh("OBJ"),id=fresh("PAGE");
 await decide(request,"manager","build","build.object.create",{type:"build.object",id:object},{name,title:"Selected notes",fields:[{name:"note",title:"Note",type:"text"}],states:[{name:"open",title:"Open"},{name:"done",title:"Done"}],actions:[{name:"close",title:"Finish selected note",from:["open"],to:"done",inputs:[{name:"reason",title:"Reason",type:"text",required:true}]}]});await decide(request,"manager","build","build.object.publish",{type:"build.object",id:object},{});for(const suffix of ["A","B","C"])await decide(request,"desk","build",`${type}.create`,{type,id:`${name}${suffix}`},{note:`SET-${suffix}`});
 m.widgets.table.config.selectionMode="multiple";m.widgets.table.config.selectedVarId="picked";m.variables.push({id:"picked",name:"Selected notes",type:"array",definitionKind:"widgetOutput",widgetId:"table",widgetOutputKey:"selectedObjects"});m.variables.find((v:any)=>v.id==="scratch").staticValue="";m.widgets.input.name="Filter note";m.widgets.input.config.label="Filter note";m.variables.find((v:any)=>v.id==="notes").objectSet.steps=[{op:"where",clauses:[{id:"filter",property:"name",op:"contains",varId:"scratch"}]}];
 for(const [key,title] of [["other","Other notes"],["picker","Picker notes"]]){m.widgets[key]={id:key,type:"ObjectTable",name:title,config:{objectSetVarId:`${key}Window`,selectedVarId:`${key}Picked`,selectionMode:"multiple",enableSelection:true,enableInlineEdit:false,columns:[{key:"name"}]}};m.variables.push({id:`${key}Window`,name:`${key}Window`,type:"objectSet",definitionKind:"objectSetDefinition",sourceObjectType:"Asset",objectSet:{objectType:"Asset",steps:[]}},{id:`${key}Picked`,name:`${key}Picked`,type:"array",definitionKind:"widgetOutput",widgetId:key,widgetOutputKey:"selectedObjects"});}
 m.sections.root.children.push({kind:"widget",id:"other"},{kind:"widget",id:"trigger"});m.widgets.trigger={id:"trigger",type:"SingleButton",name:"Open picker",config:{label:"Open picker",eventActions:[{kind:"openOverlay",overlayId:"pickerPanel"}]}};m.widgets.close={id:"close",type:"SingleButton",name:"Close picker",config:{label:"Close picker",eventActions:[{kind:"closeOverlay",overlayId:"pickerPanel"}]}};m.sections.panel={id:"panel",name:"Picker root",layout:"rows",children:[{kind:"widget",id:"picker"},{kind:"widget",id:"close"}]};m.overlays=[{id:"pickerPanel",name:"Record picker",kind:"drawer",rootSectionId:"panel"}];
 await decide(request,"manager","build","build.page.create",{type:"build.page",id},{name,title:"Selection import",object:type,sections:[{id:"help",widget:"text",configVersion:1,text:"Original"}],document:{formatVersion:2,uiProfile:pageUIProfile,root:"root",nodes:{root:{kind:"rows",children:["help"]},help:{kind:"widget",section:"help"}}}});
 await open(page,"manager",`/compose?id=${id}`);await page.getByRole("button",{name:"Import Workshop module",exact:true}).click();const dialog=page.getByRole("dialog",{name:"Import Workshop module",exact:true});await dialog.getByRole("textbox",{name:"Source module JSON",exact:true}).fill(JSON.stringify(m));await dialog.getByRole("combobox",{name:"Map object Asset",exact:true}).selectOption(type);await dialog.getByRole("combobox",{name:"Map field Asset.name",exact:true}).selectOption("note");await dialog.getByRole("combobox",{name:"Map action finishAsset",exact:true}).selectOption(`${type}.close`);await dialog.getByRole("checkbox").check();await dialog.getByRole("button",{name:"Apply imported page draft",exact:true}).click();await page.getByRole("button",{name:"Save",exact:true}).click();let saved:any;await expect.poll(async()=>{saved=(await(await request.get(`/v1/records/build.page/${id}`,{headers:{Authorization:"Bearer manager"}})).json()).record;return saved.sections?.filter((s:any)=>s.selectionSetVariable).length;}).toBe(3);
 await page.getByRole("button",{name:"Review release",exact:true}).click();await page.getByRole("button",{name:"Check draft and dependencies",exact:true}).click();await page.getByRole("button",{name:"Save immutable candidate",exact:true}).click();saved.sections.forEach((s:any)=>delete s.selectionSetVariable);await decide(request,"manager","build","build.page.edit",{type:"build.page",id},{sections:saved.sections});await page.getByRole("button",{name:"Activate release",exact:true}).click();
 const runtime=await page.context().newPage();await stableReadRevision(runtime);await open(runtime,"desk",`/page?app=build&kind=page&name=${name}`);const main=runtime.getByRole("heading",{name:"Imported notes",exact:true}).locator(".."),other=runtime.getByRole("heading",{name:"Other notes",exact:true}).locator(".."),selected=(table:any,record:string)=>table.getByRole("checkbox",{name:`Select ${name}${record}`,exact:true});
 await selected(main,"A").check();await selected(main,"B").check();await expect(main.getByRole("list",{name:"Selected records",exact:true})).toContainText("SET-A");await expect(main.getByRole("list",{name:"Selected records",exact:true})).toContainText("SET-B");await expect(runtime.getByRole("heading",{name:"Imported selection",exact:true}).locator("..").getByText("SET-B",{exact:true})).toBeVisible();await selected(other,"C").check();await expect(other.getByRole("list",{name:"Selected records",exact:true})).toContainText("SET-C");await main.getByRole("checkbox",{name:"Select this window",exact:true}).check();await expect(main.getByRole("list",{name:"Selected records",exact:true})).toContainText("SET-C");
 const form=runtime.getByRole("heading",{name:"Imported action",exact:true}).locator("..");await form.getByRole("textbox",{name:"Reason *",exact:true}).fill("From active port");await form.getByRole("button",{name:"Finish selected note",exact:true}).click();await expect.poll(async()=>(await(await request.get(`/v1/records/${type}/${name}B`,{headers:{Authorization:"Bearer desk"}})).json()).record.state).toBe("done");await runtime.getByRole("textbox",{name:"Filter note",exact:true}).fill("SET-A");await expect(main.getByRole("list",{name:"Selected records",exact:true})).toHaveCount(0);await expect(other.getByRole("list",{name:"Selected records",exact:true})).toContainText("SET-C");
 await runtime.getByRole("button",{name:"Open picker",exact:true}).click();const panel=runtime.getByRole("dialog",{name:"Record picker",exact:true});await selected(panel,"A").check();await expect(panel.getByRole("list",{name:"Selected records",exact:true})).toContainText("SET-A");
 if(process.env.PLATFORM_SCREENSHOTS){await panel.screenshot({path:info.outputPath("record-set-picker.png")});await runtime.setViewportSize({width:390,height:844});await runtime.evaluate(()=>new Promise<void>(r=>requestAnimationFrame(()=>requestAnimationFrame(()=>r()))));await panel.screenshot({path:info.outputPath("record-set-picker-narrow.png")});}
 await panel.getByRole("button",{name:"Close picker",exact:true}).click();await runtime.getByRole("button",{name:"Open picker",exact:true}).click();await expect(panel.getByRole("list",{name:"Selected records",exact:true})).toHaveCount(0);await panel.getByRole("button",{name:"Close picker",exact:true}).click();await expect(other.getByRole("list",{name:"Selected records",exact:true})).toContainText("SET-C");await runtime.reload();await expect(main.getByRole("list",{name:"Selected records",exact:true})).toHaveCount(0);await expect(other.getByRole("list",{name:"Selected records",exact:true})).toHaveCount(0);
 await runtime.route(`**/v1/records/${type}/${name}C`,route=>route.fulfill({status:403,contentType:"application/json",body:JSON.stringify({error:{message:"Denied"}})}));await selected(other,"C").click();await expect(other.getByRole("alert")).toContainText("Selection read failed");await expect(other.getByRole("list",{name:"Selected records",exact:true})).toHaveCount(0);await runtime.unroute(`**/v1/records/${type}/${name}C`);await selected(other,"C").check();await expect(other.getByRole("list",{name:"Selected records",exact:true})).toContainText("SET-C");
 let release!:()=>void,finished!:()=>void,held=false;const gate=new Promise<void>(r=>release=r),delivered=new Promise<void>(r=>finished=r);await runtime.route(`**/v1/records/${type}/${name}A`,async route=>{const response=await route.fetch();held=true;await gate;await route.fulfill({response});finished();});await selected(main,"A").check();await expect.poll(()=>held).toBe(true);await runtime.getByRole("textbox",{name:"Filter note",exact:true}).fill("SET-B");await expect(main.getByRole("list",{name:"Selected records",exact:true})).toHaveCount(0);release();await delivered;await expect(main.getByRole("list",{name:"Selected records",exact:true})).toHaveCount(0);await runtime.unroute(`**/v1/records/${type}/${name}A`);
});
