import {expect,test} from "@playwright/test";
import {readFileSync} from "node:fs";
import {decide,fresh,open,pageUIProfile,stableReadRevision} from "./host";

test("ScatterPlot imports original points, confirms distinct coincident records, clears scoped reads and freezes field bindings",async({page,request},info)=>{
 test.setTimeout(120_000);
 const name=fresh("scatter").replace(/[^a-z0-9]/gi,"").toLowerCase(),type=`build.${name}`,object=fresh("OBJ"),id=fresh("PAGE");
 await decide(request,"manager","build","build.object.create",{type:"build.object",id:object},{name,title:"Scatter records",fields:[{name:"name",title:"Asset name",type:"text"},{name:"marker",title:"Record marker",type:"text"},{name:"x",title:"Pressure",type:"integer"},{name:"y",title:"Exposure",type:"decimal"},{name:"status",title:"Status",type:"choice",choices:"open,done"},{name:"bucket",title:"Bucket",type:"text"},{name:"secret",title:"Private coordinate",type:"decimal",read:["builder"]},{name:"privatecolor",title:"Private color",type:"text",read:["builder"]}]});await decide(request,"manager","build","build.object.publish",{type:"build.object",id:object},{});
 for(let i=0;i<105;i++)await decide(request,"manager","build",`${type}.create`,{type,id:`${name}${String(i).padStart(3,"0")}`},{name:"Same asset",marker:`Marker ${i}`,...i===2?{}:{x:i<2?5:i},...i===3?{}:{y:i<2?10:i*2},status:i%2?"done":"open",bucket:i<100?"A":"B",secret:1,privatecolor:"Private"});
 const m=JSON.parse(readFileSync(new URL("../../packages/build/src/workshop/module-import/sample.workshop.json",import.meta.url),"utf8")),scatter=(id:string,title:string,set="notes",x="pressure",color="status",active?:string)=>({id,name:title,type:"ScatterPlot",config:{objectSetVarId:set,x,y:"impact",colorBy:color,...active?{activeVarId:active}:{}}});
 m.widgets={scatter:scatter("scatter","Asset scatter","notes","pressure","status","selected"),hiddenx:scatter("hiddenx","Hidden coordinates","notes","secret"),hiddencolor:scatter("hiddencolor","Hidden colors","notes","pressure","privatecolor"),detail:{id:"detail",type:"PropertyList",name:"Point selection",config:{objectVarId:"selected",properties:["marker"],inlineEdit:false,hideNull:false}},input:{id:"input",type:"TextInput",name:"Point bucket",config:{variableId:"scratch",label:"Point bucket"}},local:scatter("local","Local scatter","localNotes","pressure","status","localSelected"),localDetail:{id:"localDetail",type:"PropertyList",name:"Local selection",config:{objectVarId:"localSelected",properties:["marker"],inlineEdit:false,hideNull:false}},localInput:{id:"localInput",type:"TextInput",name:"Local bucket",config:{variableId:"localScratch",label:"Local bucket"}},trigger:{id:"trigger",type:"SingleButton",name:"Open scatter",config:{label:"Open scatter",eventActions:[{kind:"openOverlay",overlayId:"panel"}]}},close:{id:"close",type:"SingleButton",name:"Close scatter",config:{label:"Close scatter",eventActions:[{kind:"closeOverlay",overlayId:"panel"}]}}};
 delete m.widgets.hiddencolor;
 m.variables.find((v:any)=>v.id==="scratch").staticValue="";m.variables.find((v:any)=>v.id==="notes").objectSet.steps=[{op:"where",clauses:[{property:"bucket",op:"contains",varId:"scratch"}]}];m.variables.push({id:"localScratch",name:"Local bucket",type:"string",definitionKind:"static",staticValue:""},{id:"localNotes",name:"Local notes",type:"objectSet",definitionKind:"objectSetDefinition",sourceObjectType:"Asset",objectSet:{objectType:"Asset",steps:[{op:"where",clauses:[{property:"bucket",op:"contains",varId:"localScratch"}]}]}},{id:"localSelected",name:"Local selection",type:"object",definitionKind:"widgetOutput",widgetId:"local",widgetOutputKey:"activeObject"});
 m.sections={root:{id:"root",name:"Root",layout:"rows",children:["input","scatter","detail","hiddenx","trigger"].map(id=>({kind:"widget",id}))},panel:{id:"panel",name:"Panel",layout:"rows",children:["localInput","local","localDetail","close"].map(id=>({kind:"widget",id}))}};m.overlays=[{id:"panel",name:"Scatter panel",kind:"drawer",rootSectionId:"panel"}];
 await decide(request,"manager","build","build.page.create",{type:"build.page",id},{name,title:"Record scatter",object:type,sections:[{id:"initial",widget:"text",configVersion:1,text:"Initial"}],document:{formatVersion:2,uiProfile:pageUIProfile,root:"root",nodes:{root:{kind:"rows",children:["initial"]},initial:{kind:"widget",section:"initial"}}}});
 await open(page,"manager",`/compose?id=${id}`);await page.getByRole("button",{name:"Import Workshop module",exact:true}).click();const dialog=page.getByRole("dialog",{name:"Import Workshop module",exact:true});await dialog.getByRole("textbox",{name:"Source module JSON",exact:true}).fill(JSON.stringify(m));await dialog.getByRole("combobox",{name:"Map object Asset",exact:true}).selectOption(type);for(const [source,target] of [["pressure","x"],["impact","y"],["status","status"],["marker","marker"],["bucket","bucket"],["secret","secret"]])await dialog.getByRole("combobox",{name:`Map field Asset.${source}`,exact:true}).selectOption(target);
 for(const title of ["Asset scatter","Hidden coordinates","Local scatter"])await dialog.getByRole("group",{name:`Map scatter plot ${title}`,exact:true}).getByRole("combobox",{name:"Scatter title field",exact:true}).selectOption("name");await dialog.getByRole("checkbox").check();await expect(dialog.getByRole("button",{name:"Apply imported page draft",exact:true})).toBeEnabled();await dialog.getByRole("button",{name:"Apply imported page draft",exact:true}).click();await page.getByRole("region",{name:"Widgets and layout",exact:true}).getByRole("button",{name:"Asset scatter",exact:true}).click();const inspector=page.getByRole("region",{name:"The widget in hand",exact:true});await expect(inspector.getByRole("combobox",{name:"Scatter X field",exact:true})).toHaveValue("x");await inspector.getByRole("combobox",{name:"Scatter Y field",exact:true}).selectOption("");await expect(page.getByRole("button",{name:"Save",exact:true})).toBeDisabled();await inspector.getByRole("combobox",{name:"Scatter Y field",exact:true}).selectOption("y");await page.getByRole("button",{name:"Save",exact:true}).click();let saved:any;await expect.poll(async()=>{saved=(await(await request.get(`/v1/records/build.page/${id}`,{headers:{Authorization:"Bearer manager"}})).json()).record;return saved.sections?.filter((s:any)=>s.widget==="record-scatter").length;}).toBe(3);
 await page.getByRole("button",{name:"Review release",exact:true}).click();await page.getByRole("button",{name:"Check draft and dependencies",exact:true}).click();await page.getByRole("button",{name:"Save immutable candidate",exact:true}).click();saved.sections.find((s:any)=>s.title==="Asset scatter").scatter={xField:"x",yField:"x",colorField:"status",labelField:"id"};await decide(request,"manager","build","build.page.edit",{type:"build.page",id},{sections:saved.sections,document:saved.document});await page.getByRole("button",{name:"Activate release",exact:true}).click();
 const runtime=await page.context().newPage();await stableReadRevision(runtime);let aggregates=0;runtime.on("request",r=>{if(r.url().includes(`/v1/aggregates/${type}`))aggregates++;});await open(runtime,"desk",`/page?app=build&kind=page&name=${name}`);const section=(title:string)=>runtime.getByRole("heading",{name:title,exact:true}).locator(".."),root=section("Asset scatter"),detail=section("Point selection"),input=runtime.getByRole("textbox",{name:"Point bucket",exact:true}),plot=root.getByRole("group",{name:"Record scatter plot",exact:true}),point=(i:number)=>plot.getByRole("button",{name:new RegExp(`${name}${String(i).padStart(3,"0")} · Pressure:`)});
 await expect(root.getByText("98 plotted records · 2 records with missing coordinates",{exact:true})).toBeVisible();await expect(plot.getByRole("button")).toHaveCount(98);await expect(plot.getByRole("button").first()).toHaveAccessibleName(new RegExp(`${name}000 · Pressure: 5 · Exposure: 10`));for(const title of ["Hidden coordinates","Hidden colors"])await expect(runtime.getByRole("heading",{name:title,exact:true})).toHaveCount(0);
 await point(1).focus();await point(1).press("Enter");await expect(detail.getByText("Marker 1",{exact:true})).toBeVisible();await expect(point(1)).toHaveAttribute("aria-pressed","true");await root.getByText("Individual records, including overlapping points",{exact:true}).click();await root.locator("details").getByRole("button",{name:new RegExp(`${name}000 · Pressure:`)}).click();await expect(detail.getByText("Marker 0",{exact:true})).toBeVisible();await expect(point(0)).toHaveAttribute("aria-pressed","true");
 if(process.env.PLATFORM_SCREENSHOTS){await runtime.setViewportSize({width:1280,height:1400});await root.screenshot({path:info.outputPath("record-scatter.png")});await runtime.setViewportSize({width:390,height:844});await root.screenshot({path:info.outputPath("record-scatter-narrow.png")});await runtime.setViewportSize({width:1280,height:720});}
 await root.getByRole("button",{name:"Next",exact:true}).click();await expect(root.getByText("5 plotted records · 0 records with missing coordinates",{exact:true})).toBeVisible();await expect(detail.getByText("Marker 0",{exact:true})).toHaveCount(0);await expect(plot.getByRole("button").first()).toHaveAccessibleName(new RegExp(`${name}100`));await input.fill("B");await expect(plot.getByRole("button")).toHaveCount(5);await point(100).focus();await point(100).press("Space");await expect(detail.getByText("Marker 100",{exact:true})).toBeVisible();
 await runtime.route(`**/v1/records/${type}/${name}101`,route=>route.fulfill({status:403,contentType:"application/json",body:JSON.stringify({error:{message:"Denied"}})}));const denied=runtime.waitForResponse(r=>r.url().endsWith(`/${type}/${name}101`)&&r.status()===403);await point(101).focus();await point(101).press("Enter");await denied;await expect(root.getByRole("alert")).toContainText("could not be confirmed");await expect(detail.getByText("Marker 100",{exact:true})).toHaveCount(0);await expect(point(101)).toHaveAttribute("aria-pressed","false");await runtime.unroute(`**/v1/records/${type}/${name}101`);
 let release:()=>void=()=>{};const gate=new Promise<void>(r=>release=r);let started=false;await runtime.route(`**/v1/records/${type}/${name}102`,async route=>{started=true;await gate;await route.continue();});await point(102).focus();await point(102).press("Enter");await expect.poll(()=>started).toBe(true);await input.fill("A");await expect(plot.getByRole("button")).toHaveCount(98);const completed=runtime.waitForResponse(r=>r.url().endsWith(`/${type}/${name}102`));release();await completed;await runtime.evaluate(()=>new Promise<void>(r=>requestAnimationFrame(()=>requestAnimationFrame(()=>r()))));await expect(detail.getByText("Marker 102",{exact:true})).toHaveCount(0);await runtime.unroute(`**/v1/records/${type}/${name}102`);
 await runtime.route(`**/v1/records/${type}?*`,route=>route.fulfill({status:403,contentType:"application/json",body:JSON.stringify({error:{message:"Denied"}})}));await input.fill("B");await expect(root.getByRole("alert")).toBeVisible();await expect(root.getByRole("group",{name:"Record scatter plot",exact:true})).toHaveCount(0);await runtime.unroute(`**/v1/records/${type}?*`);await input.fill("A");await expect(plot.getByRole("button")).toHaveCount(98);
 await runtime.getByRole("button",{name:"Open scatter",exact:true}).click();const panel=runtime.getByRole("dialog",{name:"Scatter panel",exact:true}),local=panel.getByRole("group",{name:"Record scatter plot",exact:true}),localInput=panel.getByRole("textbox",{name:"Local bucket",exact:true});await expect(local.getByRole("button")).toHaveCount(98);await local.getByRole("button").first().focus();await local.getByRole("button").first().press("Enter");await expect(panel.getByText("Marker 0",{exact:true})).toBeVisible();await localInput.fill("B");await expect(local.getByRole("button")).toHaveCount(5);await expect(panel.getByText("Marker 0",{exact:true})).toHaveCount(0);await panel.getByRole("button",{name:"Close scatter",exact:true}).click();await runtime.getByRole("button",{name:"Open scatter",exact:true}).click();await expect(localInput).toHaveValue("");await expect(local.getByRole("button")).toHaveCount(98);await expect(panel.getByText("Marker 0",{exact:true})).toHaveCount(0);await panel.getByRole("button",{name:"Close scatter",exact:true}).click();expect(aggregates).toBe(0);
});
