import {expect,test} from "@playwright/test";
import {decide,open} from "./host";
import {createNestedLoopFixture} from "./nested-loop-fixture";

test("copied nested loops freeze rewritten owners and keep item input, child queries and original work isolated",async({page,request},testInfo)=>{
 test.setTimeout(90_000);
 const {name,child,id}=await createNestedLoopFixture(request);
 await open(page,"manager",`/compose?id=${id}`);const tree=page.getByRole("region",{name:"Widgets and layout",exact:true}),inspector=page.getByRole("region",{name:"The widget in hand",exact:true});
 await tree.getByRole("button",{name:"Commands for Parent cards",exact:true}).click();await page.getByRole("menuitem",{name:"Copy layout",exact:true}).click();await expect(page.getByRole("button",{name:"Save",exact:true})).toBeDisabled();await tree.getByRole("button",{name:"Commands for Rows",exact:true}).first().click();await page.getByRole("menuitem",{name:"Paste layout",exact:true}).click();await expect(inspector.getByRole("combobox",{name:"Layout",exact:true})).toHaveValue("loop");await inspector.getByRole("textbox",{name:"Container title",exact:true}).fill("Copied parent cards");
 await page.getByRole("button",{name:"Undo",exact:true}).click();await page.getByRole("button",{name:"Undo",exact:true}).click();await expect(tree.getByRole("button",{name:"Commands for Child cards",exact:true})).toHaveCount(1);await page.getByRole("button",{name:"Redo",exact:true}).click();await page.getByRole("button",{name:"Redo",exact:true}).click();await expect(tree.getByRole("button",{name:"Commands for Child cards",exact:true})).toHaveCount(2);
 if(process.env.PLATFORM_SCREENSHOTS){await tree.getByRole("button",{name:"Commands for Copied parent cards",exact:true}).click();await page.getByRole("menuitem",{name:"Select layout",exact:true}).click();await inspector.screenshot({path:testInfo.outputPath("loop-copy-inspector.png")});}
 await page.getByRole("button",{name:"Save",exact:true}).click();await expect(page.getByRole("button",{name:"Save",exact:true})).toBeDisabled();const saved=(await(await request.get(`/v1/records/build.page/${id}`,{headers:{Authorization:"Bearer manager"}})).json()).record;
 const copyParent=saved.document.nodes.root.children.at(-1),copyChild=saved.document.nodes[copyParent].children.find((id:string)=>saved.document.nodes[id].kind==="loop"),copyWindow=saved.document.nodes[copyChild].loop.collection,copyQuery=saved.document.variables[copyWindow].source.query;
 expect(saved.document.nodes[copyParent].loop.collection).toBe("parentWindow");expect(saved.document.variables[copyWindow].owner).toBe(copyParent);expect(saved.document.queries[copyQuery].itemOwner).toBe(copyParent);expect(saved.document.queries[copyQuery].for.variable).toBe(saved.document.nodes[copyParent].loop.itemVariable);expect(saved.document.queries[copyQuery].query).toEqual(saved.document.queries.children.query);
 await page.getByRole("button",{name:"Review release",exact:true}).click();await page.getByRole("button",{name:"Check draft and dependencies",exact:true}).click();await page.getByRole("button",{name:"Save immutable candidate",exact:true}).click();saved.document.queries[copyQuery].conditions=[{field:"note",op:"=",value:{literal:"missing"}}];await decide(request,"manager","build","build.page.edit",{type:"build.page",id},{document:saved.document});await page.getByRole("button",{name:"Activate release",exact:true}).click();
 const operation=await page.context().newPage();await open(operation,"desk",`/page?app=build&kind=page&name=${name}`);const original=operation.getByRole("list",{name:"Parent cards",exact:true}),copy=operation.getByRole("list",{name:"Copied parent cards",exact:true}),a=original.getByRole("region",{name:`${name}A`,exact:true}),ca=copy.getByRole("region",{name:`${name}A`,exact:true}),cb=copy.getByRole("region",{name:`${name}B`,exact:true}),a1=a.getByRole("region",{name:`${name}A1`,exact:true}),ca1=ca.getByRole("region",{name:`${name}A1`,exact:true}),cb1=cb.getByRole("region",{name:`${name}B1`,exact:true}),input=operation.getByRole("textbox",{name:"Parent search",exact:true});
 await expect(ca1.getByText("CHILD-A1",{exact:true})).toBeVisible();await expect(cb1.getByText("CHILD-B1",{exact:true})).toBeVisible();await expect(ca.getByText("CHILD-B1",{exact:true})).toHaveCount(0);await expect(ca.getByRole("button",{name:"Work with this parent’s children",exact:true})).toBeEnabled();await expect(cb.getByRole("button",{name:"Work with this parent’s children",exact:true})).toBeDisabled();
 await a1.getByRole("textbox",{name:"Child scratch",exact:true}).fill("Original item draft");await a1.getByRole("button",{name:"Show child context",exact:true}).click();await expect(ca1.getByRole("textbox",{name:"Child scratch",exact:true})).toHaveValue("seed");await expect(ca1.getByText("This child's context",{exact:true})).toHaveCount(0);await ca1.getByRole("textbox",{name:"Child scratch",exact:true}).fill("Copied item draft");await ca1.getByRole("button",{name:"Show child context",exact:true}).click();await expect(ca1.getByText("This child's context",{exact:true})).toBeVisible();await expect(cb1.getByText("This child's context",{exact:true})).toHaveCount(0);await ca1.getByRole("button",{name:"Complete child",exact:true}).click();await expect.poll(async()=>(await(await request.get(`/v1/records/${child}/${name}A1`,{headers:{Authorization:"Bearer desk"}})).json()).record.state).toBe("done");await expect(a1.getByRole("textbox",{name:"Child scratch",exact:true})).toHaveValue("Original item draft");await expect(ca1.getByRole("textbox",{name:"Child scratch",exact:true})).toHaveValue("Copied item draft");
 await input.fill("PARENT-B");await expect(a).toHaveCount(0);await expect(ca).toHaveCount(0);await expect(cb1.getByText("CHILD-B1",{exact:true})).toBeVisible();await input.fill("");await expect(ca1.getByText("CHILD-A1",{exact:true})).toBeVisible();await expect(ca1.getByRole("textbox",{name:"Child scratch",exact:true})).toHaveValue("seed");await expect(a1.getByRole("textbox",{name:"Child scratch",exact:true})).toHaveValue("seed");await expect(ca1.getByText("This child's context",{exact:true})).toHaveCount(0);
 // Both copies share the external parent window, but each owns its child read lifetime.
 let release!:()=>void,held=false;const pending:Promise<void>[]=[];const gate=new Promise<void>(resolve=>release=resolve);await operation.route(`**/v1/records/${child}?*`,async route=>{if((new URL(route.request().url()).searchParams.get("domain")??"").includes(`${name}A`)){let done!:()=>void;pending.push(new Promise<void>(resolve=>done=resolve));try{const response=await route.fetch();held=true;await gate;await route.fulfill({response});}finally{done();}}else await route.continue();});await input.fill("PARENT-A");await expect.poll(()=>held).toBe(true);await input.fill("PARENT-B");await expect(a).toHaveCount(0);await expect(ca).toHaveCount(0);await expect(cb1.getByText("CHILD-B1",{exact:true})).toBeVisible();release();await Promise.all(pending);await expect(copy.getByText("CHILD-A1",{exact:true})).toHaveCount(0);await operation.unroute(`**/v1/records/${child}?*`);
 if(process.env.PLATFORM_SCREENSHOTS){await cb1.screenshot({path:testInfo.outputPath("loop-copy-runtime.png")});await operation.setViewportSize({width:390,height:844});await operation.evaluate(()=>new Promise<void>(r=>requestAnimationFrame(()=>requestAnimationFrame(()=>r()))));await cb1.scrollIntoViewIfNeeded();await cb1.screenshot({path:testInfo.outputPath("loop-copy-runtime-narrow.png")});}
 await operation.setViewportSize({width:1280,height:720});await input.fill("");await expect(ca1.getByText("CHILD-A1",{exact:true})).toBeVisible();await ca1.getByRole("textbox",{name:"Child scratch",exact:true}).fill("Retired member draft");await operation.getByRole("button",{name:/desk-1 hotel-a/}).click();await operation.getByRole("menuitemradio",{name:/manager-1/}).click();await expect(ca1.getByRole("textbox",{name:"Child scratch",exact:true})).toHaveValue("seed");await ca1.getByRole("textbox",{name:"Child scratch",exact:true}).fill("Retired close draft");await operation.getByRole("menuitem",{name:"Window",exact:true}).click();await operation.getByRole("menuitem",{name:"Close tab",exact:true}).click();await expect(copy).toHaveCount(0);await operation.evaluate(()=>location.hash="/inbox");await expect(operation.getByRole("heading",{name:"Inbox",exact:true})).toBeVisible();await operation.evaluate(route=>location.hash=route,`/page?app=build&kind=page&name=${name}`);await expect(ca1.getByRole("textbox",{name:"Child scratch",exact:true})).toHaveValue("seed");await operation.reload();await expect(input).toHaveValue("");await expect(ca1.getByText("CHILD-A1",{exact:true})).toBeVisible();await expect(ca1.getByRole("textbox",{name:"Child scratch",exact:true})).toHaveValue("seed");
});
