import {expect,test} from "@playwright/test";
import {decide,fresh,open,pageUIProfile,stableReadRevision} from "./host";

test("a record timeline freezes typed fields and keeps selection scoped to its authorized query window",async({page,request},testInfo)=>{
 test.setTimeout(90_000);
 const name=fresh("schedule").replace(/[^a-z0-9]/gi,"").toLowerCase(),type=`build.${name}`,object=fresh("OBJ"),id=fresh("PAGE"),ref={app:"build",kind:"object",name:type};
 await decide(request,"manager","build","build.object.create",{type:"build.object",id:object},{name,title:"Scheduled work",fields:[{name:"title",title:"Title",type:"text"},{name:"team",title:"Team",type:"text"},{name:"start",title:"Start",type:"date"},{name:"end",title:"End",type:"date"}],states:[{name:"open",title:"Open"},{name:"done",title:"Done"}],actions:[{name:"close",title:"Complete scheduled work",from:["open"],to:"done"}]});await decide(request,"manager","build","build.object.publish",{type:"build.object",id:object},{});
 for(const [suffix,team,start,end] of [["A1","A","2026-10-01","2026-10-03"],["A2","A","2026-10-02","2026-10-04"],["B1","B","2026-10-05","2026-10-06"],["C1","C","2026-10-07","2026-10-08"],["D1","D","2026-10-09","2026-10-10"]])await decide(request,"desk","build",`${type}.create`,{type,id:`${name}${suffix}`},{title:`WORK-${suffix}`,team,start,end});
 await decide(request,"manager","build","build.page.create",{type:"build.page",id},{name,title:"Schedule desk",object:type,sections:[{id:"input",widget:"input",configVersion:1,title:"Schedule team"},{id:"detail",widget:"detail",configVersion:1,title:"Scheduled record",fields:["title","state"]},{id:"actions",widget:"actions",configVersion:1,title:"Schedule actions",actions:[`${type}.close`]}],document:{formatVersion:2,uiProfile:pageUIProfile,root:"root",nodes:{root:{kind:"rows",children:["input","detail","actions"]},input:{kind:"widget",section:"input",valueVariable:"team"},detail:{kind:"widget",section:"detail"},actions:{kind:"widget",section:"actions"}},variables:{team:{scope:"page",type:"string",mode:"state",initial:"A"},window:{scope:"page",type:"object-set",mode:"resource",title:"Schedule window",source:{kind:"plan",query:"work"}}},queries:{work:{object:ref,limit:1,sort:["id"],conditions:[{field:"team",op:"=",value:{variable:"team"}}]}}}});
 await open(page,"manager",`/compose?id=${id}`);const tree=page.getByRole("region",{name:"Widgets and layout",exact:true}),inspector=page.getByRole("region",{name:"The widget in hand",exact:true});
 await tree.getByRole("button",{name:"Record timeline",exact:true}).click();await inspector.getByLabel("Title",{exact:true}).fill("Work timeline");await inspector.getByRole("combobox",{name:"Timeline query window",exact:true}).selectOption("window");await inspector.getByRole("combobox",{name:"Start time field",exact:true}).selectOption("start");await inspector.getByRole("combobox",{name:"End time field",exact:true}).selectOption("end");await inspector.getByRole("combobox",{name:"Timeline label field",exact:true}).selectOption("title");await inspector.getByRole("combobox",{name:"Timeline resource field",exact:true}).selectOption("team");
 if(process.env.PLATFORM_SCREENSHOTS)await inspector.screenshot({path:testInfo.outputPath("timeline-inspector.png")});
 await page.getByRole("button",{name:"Save",exact:true}).click();let saved:any;await expect.poll(async()=>{saved=(await(await request.get(`/v1/records/build.page/${id}`,{headers:{Authorization:"Bearer manager"}})).json()).record;return saved.sections.find((s:any)=>s.widget==="record-timeline")?.timeEnd;}).toBe("end");
 await page.getByRole("button",{name:"Review release",exact:true}).click();await page.getByRole("button",{name:"Check draft and dependencies",exact:true}).click();await page.getByRole("button",{name:"Save immutable candidate",exact:true}).click();
 saved.sections.find((s:any)=>s.widget==="record-timeline").timeEnd="";saved.document.variables.team.initial="B";await decide(request,"manager","build","build.page.edit",{type:"build.page",id},{sections:saved.sections,document:saved.document});await page.getByRole("button",{name:"Activate release",exact:true}).click();
 const operation=await page.context().newPage();await stableReadRevision(operation);await open(operation,"desk",`/page?app=build&kind=page&name=${name}`);
 const timeline=operation.getByRole("heading",{name:"Work timeline",exact:true}).locator(".."),input=operation.getByRole("textbox",{name:"Schedule team",exact:true}),detail=operation.getByRole("heading",{name:"Scheduled record",exact:true}).locator("..");
 await expect(timeline.getByRole("button",{name:"WORK-A1",exact:true})).toBeVisible();await expect(timeline).toContainText("Showing 1 of 2 matching records");await expect(timeline).toContainText("2026-10-01 → 2026-10-03");
 await timeline.getByRole("button",{name:"WORK-A1",exact:true}).click();await expect(detail.getByText("WORK-A1",{exact:true})).toBeVisible();await operation.getByRole("button",{name:"Complete scheduled work",exact:true}).click();await expect(detail.getByText("Done",{exact:true})).toBeVisible();
 await timeline.getByRole("button",{name:"Next",exact:true}).click();await expect(timeline.getByRole("button",{name:"WORK-A2",exact:true})).toBeVisible();await expect(detail.getByText("WORK-A1",{exact:true})).toHaveCount(0);
 await timeline.getByRole("button",{name:"WORK-A2",exact:true}).click();await expect(detail.getByText("WORK-A2",{exact:true})).toBeVisible();await input.fill("B");await expect(timeline.getByRole("button",{name:"WORK-B1",exact:true})).toBeVisible();await expect(detail.getByText("WORK-A2",{exact:true})).toHaveCount(0);
 let release!:()=>void,delivered!:()=>void,held=false;const gate=new Promise<void>(r=>release=r),done=new Promise<void>(r=>delivered=r);
 await operation.route(`**/v1/records/${type}*`,async route=>{const domain=new URL(route.request().url()).searchParams.get("domain");if(domain?.includes('"C"')){const response=await route.fetch();held=true;await gate;await route.fulfill({response});delivered();}else await route.continue();});await input.fill("C");await expect.poll(()=>held).toBe(true);await expect(timeline.getByRole("button",{name:"WORK-B1",exact:true})).toHaveCount(0);await input.fill("D");await expect(timeline.getByRole("button",{name:"WORK-D1",exact:true})).toBeVisible();release();await done;await operation.unroute(`**/v1/records/${type}*`);await expect(timeline.getByRole("button",{name:"WORK-C1",exact:true})).toHaveCount(0);
 await operation.route(`**/v1/records/${type}*`,route=>route.fulfill({status:403,contentType:"application/json",body:JSON.stringify({error:{message:"Denied"}})}));await input.fill("B");await expect(timeline.getByRole("alert")).toBeVisible();await expect(timeline.getByRole("button",{name:"WORK-D1",exact:true})).toHaveCount(0);await operation.unroute(`**/v1/records/${type}*`);await input.fill("A");await expect(timeline.getByRole("button",{name:"WORK-A1",exact:true})).toBeVisible();
 if(process.env.PLATFORM_SCREENSHOTS){await timeline.scrollIntoViewIfNeeded();await operation.screenshot({path:testInfo.outputPath("timeline-runtime.png"),fullPage:true});await operation.setViewportSize({width:390,height:844});await operation.evaluate(()=>new Promise<void>(r=>requestAnimationFrame(()=>requestAnimationFrame(()=>r()))));await timeline.scrollIntoViewIfNeeded();await operation.screenshot({path:testInfo.outputPath("timeline-runtime-narrow.png"),fullPage:true});}
 await operation.reload();await expect(input).toHaveValue("A");await expect(timeline.getByRole("button",{name:"WORK-A1",exact:true})).toBeVisible();
});
