import {expect,test} from '@playwright/test';import {createServer} from 'node:http';import {readFileSync} from 'node:fs';
import {decide,fresh,open,pageUIProfile} from './host';
const original=JSON.parse(readFileSync(new URL('../../packages/build/src/workshop/module-import/default.workshop.json',import.meta.url),'utf8'));
test('four original overlays freeze dismissal and shared record detail action and generated AI context',async({page,request},info)=>{
 test.setTimeout(180_000);page.setDefaultTimeout(10_000);const name=fresh('overlayai').replace(/[^a-z0-9]/gi,'').toLowerCase(),type=`build.${name}`,object=fresh('OBJ'),parent=fresh('PAGE'),app=fresh('APP'),fn=fresh('FN'),provider=fresh('provider').replace(/[^a-z0-9]/gi,''),headers={Authorization:'Bearer manager'},calls:any[]=[];
 const server=createServer(async(req,res)=>{let body='';for await(const chunk of req)body+=chunk;const raw=JSON.parse(body),input=JSON.parse(raw.messages.find((m:any)=>m.role==='user').content);calls.push(input);res.setHeader('Content-Type','application/json');res.end(JSON.stringify({choices:[{message:{content:JSON.stringify({summary:`Protocol fixture: ${input.name}`})}}],usage:{prompt_tokens:10,completion_tokens:12,cost:.001}}));});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const address=server.address();if(!address||typeof address==='string')throw Error('fixture address');
 try{
 await decide(request,'manager','platform','platform.member.grant',{type:'platform.member',id:'manager-1'},{app:'ai',role:'admin'});await decide(request,'manager','ai','ai.provider.add',{type:'ai.provider',id:provider},{kind:'local',baseUrl:`http://127.0.0.1:${address.port}`,wire:'openai'});await decide(request,'manager','ai','ai.model.enable',{type:'ai.model',id:`${provider}/probe`},{access:'users'});
 await decide(request,'manager','build','build.object.create',{type:'build.object',id:object},{name,title:'Original overlay assets',fields:[{name:'name',title:'Name',type:'text'}],states:[{name:'open',title:'Open'},{name:'done',title:'Done'}],actions:[{name:'close',title:'Complete original asset',from:['open'],to:'done'}]});await decide(request,'manager','build','build.object.publish',{type:'build.object',id:object},{});for(const id of ['A','B'])await decide(request,'desk','build',`${type}.create`,{type,id},{name:`Original ${id}`});
 await decide(request,'manager','build','build.function.create',{type:'build.function',id:fn},{name:`${name}advice`,title:'Original fixed advice',description:'Protocol fixture',object:type,fields:['name'],instructions:'Use only the original authorized record.',output:[{name:'summary',type:'string',description:'Typed advice',required:true}],model:`${provider}/probe`,maxInputBytes:4096,maxOutputBytes:1024,maxTokens:256,roles:['builder','user']});await decide(request,'manager','build','build.function.publish',{type:'build.function',id:fn},{});
 await decide(request,'manager','build','build.page.create',{type:'build.page',id:parent},{name:`${name}page`,title:'Overlay task',object:type,sections:[{id:'initial',widget:'text',configVersion:1,text:'Initial'}],document:{formatVersion:2,uiProfile:pageUIProfile,root:'root',nodes:{root:{kind:'rows',children:['initial']},initial:{kind:'widget',section:'initial'}}}});await decide(request,'manager','build','build.page.publish',{type:'build.page',id:parent},{});
 const ref={app:'build',kind:'object',name:type};await decide(request,'manager','build','build.app.create',{type:'build.app',id:app},{name:`${name}app`,title:'Overlay shared desk',pages:[`${name}page`],uiProfile:pageUIProfile,variables:{record:{scope:'application',type:'record',mode:'resource',source:{kind:'record',object:ref}}}});await decide(request,'manager','build','build.app.publish',{type:'build.app',id:app},{});
 const defs=await(await request.get('/v1/definitions',{headers})).json(),appDef=defs.find((d:any)=>d.ref.kind==='app'&&d.ref.name===`${name}app`),functionDef=defs.find((d:any)=>d.ref.kind==='function'&&d.ref.name===`${name}advice`),appBinding={ref:appDef.ref,sourceVersion:appDef.version},functionBinding={ref:functionDef.ref,sourceVersion:functionDef.version};
 const module:any={id:'group',name:'Original overlay group',pages:[{id:'page',name:'Original overlays',rootSectionId:'root'}],sections:{root:{id:'root',name:'Root',layout:'rows',children:[{kind:'widget',id:'table'}]}},widgets:{table:{id:'table',name:'Original shared assets',type:'ObjectTable',config:{objectSetVarId:'assets',activeVarId:'selected',columns:[{key:'name'}]}}},variables:[{id:'assets',name:'Assets',type:'objectSet',definitionKind:'objectSetDefinition',objectSet:{objectType:'Asset',steps:[]}},{id:'selected',name:'Selected asset',type:'object',definitionKind:'widgetOutput',widgetId:'table',widgetOutputKey:'activeObject'}],moduleInterface:[{variableId:'selected',externalId:'selectedAsset',direction:'inputOutput'}],overlays:structuredClone(original.overlays),unusedWidgetIds:[]};
 for(const o of module.overlays){const button=`open-${o.id}`,detail=`detail-${o.id}`,action=`action-${o.id}`;module.variables.push({id:o.openVariableId,name:o.openVariableId,type:'boolean',definitionKind:'static',staticValue:false});module.widgets[button]={id:button,name:`Open ${o.name}`,type:'SingleButton',config:{label:`Open ${o.name}`,eventActions:[{kind:'openOverlay',overlayId:o.id}]}};module.sections.root.children.push({kind:'widget',id:button});module.widgets[detail]={id:detail,name:`${o.name} record`,type:'PropertyList',config:{objectVarId:'selected',properties:['name']}};module.widgets[action]={id:action,name:`${o.name} action`,type:'InlineAction',config:{objectVarId:'selected',actionId:'finish'}};module.sections[o.rootSectionId]={id:o.rootSectionId,name:o.name,layout:'rows',children:[{kind:'widget',id:detail},{kind:'widget',id:action}]};}
 module.widgets.generated={id:'generated',name:'Original shared generated AI',type:'AIPGenerated',config:{objectVarId:'selected'}};module.sections[module.overlays[0].rootSectionId].children.push({kind:'widget',id:'generated'});
 await open(page,'manager',`/compose?id=${parent}`);await page.getByRole('button',{name:'Import Workshop module',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Import Workshop module',exact:true});await dialog.getByRole('textbox',{name:'Source module JSON',exact:true}).fill(JSON.stringify(module));await dialog.getByRole('combobox',{name:'Map object Asset',exact:true}).selectOption(type);await dialog.getByRole('combobox',{name:'Map field Asset.name',exact:true}).selectOption('name');await dialog.getByRole('combobox',{name:'Map action finish',exact:true}).selectOption(`${type}.close`);await dialog.getByRole('combobox',{name:'Reviewed original application',exact:true}).selectOption(JSON.stringify(appBinding));await dialog.getByRole('combobox',{name:'Map module port selectedAsset',exact:true}).selectOption('record');const ai=dialog.getByRole('group',{name:'Map original AI Original shared generated AI',exact:true});await ai.getByRole('combobox',{name:'AI source interpretation',exact:true}).selectOption('record-scoped-functions');await ai.getByRole('combobox',{name:'Fixed original AI function',exact:true}).selectOption(JSON.stringify(functionBinding));await dialog.getByRole('checkbox').last().check();await expect(dialog.getByRole('button',{name:'Apply imported page draft',exact:true})).toBeEnabled();await dialog.getByRole('button',{name:'Apply imported page draft',exact:true}).click();await page.getByRole('button',{name:'Save',exact:true}).click();await expect.poll(async()=>{const body=await(await request.get(`/v1/records/build.page/${parent}`,{headers})).json();return Object.values(body.record.document.overlays).filter((o:any)=>o.presentation).length;}).toBe(4);await decide(request,'manager','build','build.page.publish',{type:'build.page',id:parent},{});
 const planTitle=`${name} advice evaluation`;await open(page,'manager','/candidate-test');await page.getByRole('combobox',{name:'Candidate kind'}).selectOption('function');await page.getByRole('combobox',{name:'Saved function draft'}).selectOption(fn);await page.getByRole('textbox',{name:'Test plan name'}).fill(planTitle);await page.getByRole('textbox',{name:'Model identifier'}).fill(`${provider}/probe`);await page.getByRole('checkbox',{name:'Require a measured release evaluation'}).check();await page.getByRole('textbox',{name:'Synthetic input (JSON object)'}).fill(JSON.stringify({name:'Synthetic'}));await page.getByRole('textbox',{name:'Expected typed answer (JSON object)'}).fill(JSON.stringify({summary:'Protocol fixture: Synthetic'}));await page.getByRole('button',{name:'Save test plan'}).click();await expect(page.getByRole('status').filter({hasText:'Test plan saved.'})).toBeVisible();
 await open(page,'manager',`/application?id=${app}`);await page.getByRole('button',{name:'Review application release',exact:true}).click();await page.getByRole('button',{name:'Check draft and dependencies',exact:true}).click();await page.getByRole('button',{name:'Save immutable candidate',exact:true}).click();await page.getByRole('combobox',{name:'Evaluation plan'}).selectOption({label:planTitle});await page.getByRole('button',{name:'Run measured evaluation'}).click();await expect.poll(async()=>{const rows=await(await request.get('/v1/records/build.evaluation?limit=500',{headers})).json();return rows.records.some((r:any)=>r.function===`${name}advice`&&r.state==='passed');}).toBe(true);await page.getByRole('button',{name:'Refresh evaluation reports'}).click();await page.getByRole('button',{name:'Activate release',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'Release active for operators.'})).toBeVisible();
 const saved=await(await request.get(`/v1/records/build.page/${parent}`,{headers})).json(),later=structuredClone(saved.record.document);Object.values(later.overlays).forEach((o:any)=>o.presentation.closeOnBackdrop=true);await decide(request,'manager','build','build.page.edit',{type:'build.page',id:parent},{document:later});
 const runtime=await page.context().newPage();runtime.setDefaultTimeout(10_000);const route=`/page?app=build&kind=page&name=${name}page&application=build:${name}app&instance=main`;await open(runtime,'desk',route);const table=runtime.getByRole('heading',{name:'Original shared assets',exact:true,level:3}).locator('..');await table.getByRole('cell',{name:'Original A',exact:true}).click();
 for(const o of module.overlays){await runtime.getByRole('button',{name:`Open ${o.name}`,exact:true}).click();const title=o.title??o.name,popup=runtime.getByRole('dialog',{name:title,exact:true});await expect(popup.getByText('Original A',{exact:true})).toBeVisible();if(o.id==='oAssetDrawer'){await popup.getByRole('button',{name:'Request original analysis',exact:true}).click();await expect(popup).toContainText('Protocol fixture: Original A');if(process.env.PLATFORM_SCREENSHOTS)await popup.screenshot({path:info.outputPath('shared-ai-drawer.png')});}if(o.closeOnBackdrop===false){await runtime.mouse.click(5,5);await expect(popup).toBeVisible();}await runtime.keyboard.press('Escape');await expect(popup).not.toBeVisible();}
 await table.getByRole('cell',{name:'Original B',exact:true}).click();await runtime.getByRole('button',{name:'Open Asset Detail Drawer',exact:true}).click();const drawer=runtime.getByRole('dialog',{name:'Asset Detail Drawer',exact:true});await expect(drawer).not.toContainText('Protocol fixture: Original A');await drawer.getByRole('button',{name:'Request original analysis',exact:true}).click();await expect(drawer).toContainText('Protocol fixture: Original B');expect(calls.some(c=>c.name==='Original B')).toBe(true);await drawer.getByRole('button',{name:'Close',exact:true}).click();await runtime.getByRole('button',{name:'Open Edit Status Modal',exact:true}).click();await runtime.getByRole('dialog',{name:'Edit Asset Status',exact:true}).getByRole('button',{name:'Complete original asset',exact:true}).click();await expect.poll(async()=>(await(await request.get(`/v1/records/${type}/B`,{headers:{Authorization:'Bearer desk'}})).json()).record.state).toBe('done');
 }finally{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));}
});
