import {expect,test} from '@playwright/test';import {readFileSync} from 'node:fs';
import {decide,fresh,open,pageUIProfile} from './host';
const sample=JSON.parse(readFileSync(new URL('../../packages/build/src/module-import/sample.workshop.json',import.meta.url),'utf8'));
test('module interface binds grouped record views to an original frozen application across pages overlays and instances',async({page,request},info)=>{
 test.setTimeout(150_000);page.setDefaultTimeout(10_000);const name=fresh('moduleapp').replace(/[^a-z0-9]/gi,'').toLowerCase(),type=`build.${name}`,object=fresh('OBJ'),app=fresh('APP'),first=fresh('PAGE'),second=fresh('PAGE'),headers={Authorization:'Bearer manager'},ref={app:'build',kind:'object',name:type},application=`build:${name}app`;
 await decide(request,'manager','build','build.object.create',{type:'build.object',id:object},{name,title:'Shared imported assets',fields:[{name:'note',title:'Note',type:'text'}],states:[{name:'open',title:'Open'},{name:'done',title:'Done'}],actions:[{name:'close',title:'Complete original asset',from:['open'],to:'done'}]});await decide(request,'manager','build','build.object.publish',{type:'build.object',id:object},{});for(const id of ['A','B'])await decide(request,'desk','build',`${type}.create`,{type,id},{note:`ORIGINAL-${id}`});
 for(const [id,suffix] of [[first,'first'],[second,'second']]){await decide(request,'manager','build','build.page.create',{type:'build.page',id},{name:`${name}${suffix}`,title:`Original ${suffix}`,object:type,sections:[{id:'initial',widget:'text',configVersion:1,text:'Initial'}],document:{formatVersion:2,uiProfile:pageUIProfile,root:'root',nodes:{root:{kind:'rows',children:['initial']},initial:{kind:'widget',section:'initial'}}}});await decide(request,'manager','build','build.page.publish',{type:'build.page',id},{});}
 const vars={record:{title:'Shared asset',scope:'application',type:'record',mode:'resource',source:{kind:'record',object:ref}},page:{title:'Page state',scope:'application',type:'string',mode:'state',initial:'first'},detail:{title:'Shared detail visibility',scope:'application',type:'boolean',mode:'state',initial:false}};await decide(request,'manager','build','build.app.create',{type:'build.app',id:app},{name:`${name}app`,title:'Shared bridge desk',pages:[`${name}first`,`${name}second`],uiProfile:pageUIProfile,variables:vars});await decide(request,'manager','build','build.app.publish',{type:'build.app',id:app},{});
 const definitions=await(await request.get('/v1/definitions',{headers})).json(),d=definitions.find((d:any)=>d.ref.kind==='app'&&d.ref.name===`${name}app`),binding={ref:d.ref,sourceVersion:d.version},module=structuredClone(sample);module.moduleInterface=[{variableId:'selected',externalId:'selectedAsset',direction:'inputOutput'},{variableId:'currentPage',externalId:'currentPage',direction:'inputOutput'},{variableId:'showDetail',externalId:'showDetail',direction:'input'}];module.variables.push({id:'currentPage',name:'Page state',type:'string',definitionKind:'static',staticValue:'page'},{id:'showDetail',name:'Show detail',type:'boolean',definitionKind:'static',staticValue:false},{id:'showPopup',name:'Popup',type:'boolean',definitionKind:'static',staticValue:false});module.widgets.table.events=[{id:'select',trigger:'onSelect',actions:[{kind:'setVariable',variableId:'showDetail',valueExpr:'true'}]}];module.sections.side.visibleVariableId='showDetail';module.widgets.open={id:'open',name:'Open shared detail',type:'SingleButton',config:{label:'Open shared detail',eventActions:[{kind:'openOverlay',overlayId:'popup'}]}};module.sections.root.children.push({kind:'widget',id:'open'});module.widgets.popupDetail={id:'popupDetail',name:'Shared popup detail',type:'PropertyList',config:{objectVarId:'selected',properties:['name'],hideNull:false,inlineEdit:false}};module.sections.popup={id:'popup',name:'Popup detail',layout:'rows',children:[{kind:'widget',id:'popupDetail'}]};module.overlays=[{id:'popup',name:'Shared popup',kind:'modal',rootSectionId:'popup',openVariableId:'showPopup'}];module.widgets.input.config.variableId='currentPage';module.widgets.input.config.label='Shared page text';
 // Import both pages against one original application; JSON events remain literal-only.
 for(const [id,title] of [[first,'Imported first'],[second,'Imported second']]){
  const copy=structuredClone(module);copy.pages[0].name=title;copy.widgets.table.name=`${title} choices`;await open(page,'manager',`/compose?id=${id}`);await page.getByRole('button',{name:'Import Workshop module',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Import Workshop module',exact:true});await dialog.getByRole('textbox',{name:'Source module JSON',exact:true}).fill(JSON.stringify(copy));await dialog.getByRole('combobox',{name:'Map object Asset',exact:true}).selectOption(type);await dialog.getByRole('combobox',{name:'Map field Asset.name',exact:true}).selectOption('note');await dialog.getByRole('combobox',{name:'Map action finishAsset',exact:true}).selectOption(`${type}.close`);await dialog.getByRole('combobox',{name:'Reviewed original application',exact:true}).selectOption(JSON.stringify(binding));for(const [port,target] of [['selectedAsset','record'],['currentPage','page'],['showDetail','detail']])await dialog.getByRole('combobox',{name:`Map module port ${port}`,exact:true}).selectOption(target);await dialog.getByRole('combobox',{name:'Map module port showDetail',exact:true}).locator('..').locator('..').getByRole('checkbox',{name:'Allow module presentation updates',exact:true}).check();await dialog.getByRole('checkbox').last().check();await expect(dialog.getByRole('button',{name:'Apply imported page draft',exact:true})).toBeEnabled();await dialog.getByRole('button',{name:'Apply imported page draft',exact:true}).click();await page.getByRole('button',{name:'Save',exact:true}).click();await expect.poll(async()=>{const body=await(await request.get(`/v1/records/build.page/${id}`,{headers})).json();return body.record.sections.some((s:any)=>s.selectionVariable);}).toBe(true);
 }
 for(const id of [first,second])await decide(request,'manager','build','build.page.publish',{type:'build.page',id},{});
 await open(page,'manager',`/application?id=${app}`);await page.getByRole('button',{name:'Review application release',exact:true}).click();await page.getByRole('button',{name:'Check draft and dependencies',exact:true}).click();await page.getByRole('button',{name:'Save immutable candidate',exact:true}).click();await page.getByRole('button',{name:'Activate release',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'Release active for operators.'})).toBeVisible();
 // Later page draft cannot replace the candidate's shared object or action binding.
 const saved=await(await request.get(`/v1/records/build.page/${first}`,{headers})).json(),changed=structuredClone(saved.record.sections);changed.find((s:any)=>s.widget==='detail').title='Later unactivated detail';await decide(request,'manager','build','build.page.edit',{type:'build.page',id:first},{sections:changed});
 const runtime=await page.context().newPage();runtime.setDefaultTimeout(10_000);const route=(suffix:string,instance='main')=>`/page?app=build&kind=page&name=${name}${suffix}&application=${application}&instance=${instance}`,section=(title:string)=>runtime.getByRole('heading',{name:title,exact:true,level:3}).locator('..');await open(runtime,'desk',route('first'));await expect(runtime.getByRole('heading',{name:'Imported selection',level:3,exact:true})).toHaveCount(0);await section('Imported first choices').getByRole('row').filter({hasText:'ORIGINAL-A'}).click();await expect(section('Imported selection').getByText('ORIGINAL-A',{exact:true})).toBeVisible();await expect(runtime.getByRole('heading',{name:'Later unactivated detail',exact:true})).toHaveCount(0);await runtime.getByRole('textbox',{name:'Shared page text',exact:true}).fill('keep shared text');await runtime.getByRole('button',{name:'Open shared detail',exact:true}).click();const popup=runtime.getByRole('dialog',{name:'Shared popup',exact:true});await expect(popup.getByText('ORIGINAL-A',{exact:true})).toBeVisible();await popup.getByRole('button',{name:'Close',exact:true}).click();
 await runtime.evaluate(r=>{location.hash=r},route('second'));await expect(section('Imported selection').getByText('ORIGINAL-A',{exact:true})).toBeVisible();await expect(runtime.getByRole('textbox',{name:'Shared page text',exact:true})).toHaveValue('keep shared text');await section('Imported action').getByRole('button',{name:'Complete original asset',exact:true}).click();await expect.poll(async()=>(await(await request.get(`/v1/records/${type}/A`,{headers:{Authorization:'Bearer desk'}})).json()).record.state).toBe('done');
 await section('Imported second choices').getByRole('row').filter({hasText:'ORIGINAL-B'}).click();await expect(section('Imported selection').getByText('ORIGINAL-B',{exact:true})).toBeVisible();if(process.env.PLATFORM_SCREENSHOTS)await runtime.screenshot({path:info.outputPath('module-application-shared.png'),fullPage:true});
 await runtime.evaluate(r=>{location.hash=r},route('first','separate'));await expect(runtime.getByRole('heading',{name:'Imported selection',level:3,exact:true})).toHaveCount(0);await expect(runtime.getByRole('textbox',{name:'Shared page text',exact:true})).toHaveCount(0);await section('Imported first choices').getByRole('row').filter({hasText:'ORIGINAL-A'}).click();await expect(runtime.getByRole('textbox',{name:'Shared page text',exact:true})).toHaveValue('first');await runtime.evaluate(r=>{location.hash=r},route('first'));await expect(section('Imported selection').getByText('ORIGINAL-B',{exact:true})).toBeVisible();await expect(runtime.getByRole('textbox',{name:'Shared page text',exact:true})).toHaveValue('keep shared text');
});
