import {expect,test} from "@playwright/test";
import {readFileSync} from "node:fs";
import {decide,fresh,open,pageUIProfile,stableReadRevision} from "./host";

test("default grouped XY imports original fields and freezes complete averages with member and overlay scope",async({page,request},info)=>{
 test.setTimeout(90_000);
 const name=fresh("xy").replace(/[^a-z0-9]/gi,"").toLowerCase(),type=`build.${name}`,object=fresh("OBJ"),id=fresh("PAGE");
 await decide(request,"manager","build","build.object.create",{type:"build.object",id:object},{name,title:"Chart assets",fields:[{name:"note",title:"Note",type:"text"},{name:"bucket",title:"Status",type:"text"},{name:"qty",title:"Availability",type:"decimal"},{name:"privategroup",title:"Private group",type:"text",read:["builder"]},{name:"privateqty",title:"Private availability",type:"decimal",read:["builder"]}]});await decide(request,"manager","build","build.object.publish",{type:"build.object",id:object},{});
 for(const [suffix,qty] of [["A1",10],["A2",20],["A3",30],["B1",40],["B2",50],["B3",60]] as const)await decide(request,"manager","build",`${type}.create`,{type,id:`${name}${suffix}`},{note:suffix,bucket:suffix[0],qty,privategroup:"keep",privateqty:100});
 const m=JSON.parse(readFileSync(new URL("../../packages/build/src/workshop/module-import/sample.workshop.json",import.meta.url),"utf8"));
 const chart=(id:string,title:string,set="notes",x="status",y="availability")=>({id,name:title,type:"ChartXY",config:{objectSetVarId:set,chartKind:"bar",xProperty:x,yProperty:y,agg:"avg"}});
 m.widgets.chart=chart("chart","Availability by Status");m.widgets.privategroup=chart("privategroup","Private chart group","notes","privategroup");m.widgets.privateqty=chart("privateqty","Private chart measure","notes","status","privateqty");m.widgets.privateCondition=chart("privateCondition","Private chart condition","privateNotes");m.widgets.local=chart("local","Local averages","localNotes");
 m.widgets.input={id:"input",name:"Chart bucket",type:"TextInput",config:{variableId:"scratch",label:"Chart bucket"}};m.widgets.localInput={id:"localInput",name:"Local chart bucket",type:"TextInput",config:{variableId:"localScratch",label:"Local chart bucket"}};
 m.widgets.trigger={id:"trigger",name:"Open chart panel",type:"SingleButton",config:{label:"Open chart panel",eventActions:[{kind:"openOverlay",overlayId:"panel"}]}};m.widgets.close={id:"close",name:"Close chart panel",type:"SingleButton",config:{label:"Close chart panel",eventActions:[{kind:"closeOverlay",overlayId:"panel"}]}};
 m.variables.find((v:any)=>v.id==="scratch").staticValue="";m.variables.find((v:any)=>v.id==="notes").objectSet.steps=[{op:"where",clauses:[{id:"bucket",property:"status",op:"contains",varId:"scratch"}]}];
 m.variables.push({id:"localScratch",name:"Local bucket",type:"string",definitionKind:"static",staticValue:""},{id:"localNotes",name:"Local notes",type:"objectSet",definitionKind:"objectSetDefinition",sourceObjectType:"Asset",objectSet:{objectType:"Asset",steps:[{op:"where",clauses:[{id:"localBucket",property:"status",op:"contains",varId:"localScratch"}]}]}},{id:"privateNotes",name:"Private notes",type:"objectSet",definitionKind:"objectSetDefinition",sourceObjectType:"Asset",objectSet:{objectType:"Asset",steps:[{op:"where",clauses:[{id:"private",property:"privategroup",op:"is",value:"keep"}]}]}});
 m.sections={root:{id:"root",name:"Root",layout:"rows",children:["input","table","chart","privategroup","privateqty","privateCondition","trigger"].map(id=>({kind:"widget",id}))},panel:{id:"panel",name:"Panel",layout:"rows",children:["localInput","local","close"].map(id=>({kind:"widget",id}))}};m.overlays=[{id:"panel",name:"Chart panel",kind:"drawer",rootSectionId:"panel"}];
 await decide(request,"manager","build","build.page.create",{type:"build.page",id},{name,title:"Imported analysis",object:type,sections:[{id:"initial",widget:"table",configVersion:1,fields:["note"]}],document:{formatVersion:2,uiProfile:pageUIProfile,root:"root",nodes:{root:{kind:"rows",children:["initial"]},initial:{kind:"widget",section:"initial"}}}});
 await open(page,"manager",`/compose?id=${id}`);await page.getByRole("button",{name:"Import Workshop module",exact:true}).click();const dialog=page.getByRole("dialog",{name:"Import Workshop module",exact:true});
 const invalid=structuredClone(m);invalid.widgets.chart.config.chartKind="line";await dialog.getByRole("textbox",{name:"Source module JSON",exact:true}).fill(JSON.stringify(invalid));await expect(dialog.getByRole("alert").filter({hasText:"chart-aggregate-profile"})).toBeVisible();await expect(dialog.getByRole("button",{name:"Apply imported page draft",exact:true})).toBeDisabled();
 await dialog.getByRole("textbox",{name:"Source module JSON",exact:true}).fill(JSON.stringify(m));await dialog.getByRole("combobox",{name:"Map object Asset",exact:true}).selectOption(type);
 for(const [source,target] of [["name","note"],["status","bucket"],["availability","qty"],["privategroup","privategroup"],["privateqty","privateqty"]])await dialog.getByRole("combobox",{name:`Map field Asset.${source}`,exact:true}).selectOption(target);
 await dialog.getByRole("checkbox").check();await dialog.getByRole("button",{name:"Apply imported page draft",exact:true}).click();
 await page.getByRole("region",{name:"Widgets and layout",exact:true}).getByRole("button",{name:"Availability by Status",exact:true}).click();const inspector=page.getByRole("region",{name:"The widget in hand",exact:true});await expect(inspector.getByRole("combobox",{name:"Grouped by",exact:true})).toHaveValue("bucket");await expect(inspector.getByRole("combobox",{name:"Measure",exact:true})).toHaveValue("avg:qty");
 await page.getByRole("button",{name:"Query plans",exact:true}).click();await page.getByRole("combobox",{name:"Choose query plan",exact:true}).selectOption({index:1});await page.getByRole("spinbutton",{name:"Query window limit",exact:true}).fill("1");
 await page.getByRole("button",{name:"Save",exact:true}).click();let saved:any;await expect.poll(async()=>{saved=(await(await request.get(`/v1/records/build.page/${id}`,{headers:{Authorization:"Bearer manager"}})).json()).record;return saved.sections?.filter((s:any)=>s.widget==="chart").length;}).toBe(5);
 await page.getByRole("button",{name:"Review release",exact:true}).click();await page.getByRole("button",{name:"Check draft and dependencies",exact:true}).click();await page.getByRole("button",{name:"Save immutable candidate",exact:true}).click();saved.sections.find((s:any)=>s.title==="Availability by Status").measure="count";await decide(request,"manager","build","build.page.edit",{type:"build.page",id},{sections:saved.sections});await page.getByRole("button",{name:"Activate release",exact:true}).click();
 const runtime=await page.context().newPage();await stableReadRevision(runtime);const endpoint=`/v1/aggregates/${type}/query`,first=runtime.waitForResponse(r=>r.url().endsWith(endpoint));let reads=0;runtime.on("request",r=>{if(r.url().endsWith(endpoint)){reads++;const q=r.postDataJSON();expect(q.groups).toEqual(["bucket"]);expect(q.measures).toEqual(["avg:qty"]);expect(q.limit).toBeUndefined();expect(q.offset).toBeUndefined();expect(q.maxRows).toBe(4096);}});
 await open(runtime,"desk",`/page?app=build&kind=page&name=${name}`);const section=(title:string)=>runtime.getByRole("heading",{name:title,exact:true}).locator(".."),root=section("Availability by Status"),input=runtime.getByRole("textbox",{name:"Chart bucket",exact:true});await expect(root.getByRole("img")).toBeVisible();expect((await(await first).json()).rows).toEqual([{bucket:"A","avg:qty":20},{bucket:"B","avg:qty":50}]);await expect(runtime.getByText("1–1 of 6",{exact:true})).toBeVisible();for(const title of ["Private chart group","Private chart measure","Private chart condition"])await expect(runtime.getByRole("heading",{name:title,exact:true})).toHaveCount(0);
 const before=reads;await runtime.getByRole("button",{name:"Next page",exact:true}).click();await expect(runtime.getByText("2–2 of 6",{exact:true})).toBeVisible();expect(reads).toBe(before);
 const filtered=runtime.waitForResponse(r=>r.url().endsWith(endpoint));await input.fill("A");expect((await(await filtered).json()).rows).toEqual([{bucket:"A","avg:qty":20}]);await expect(root.getByRole("img")).toBeVisible();
 await runtime.route(`**${endpoint}`,route=>route.fulfill({status:403,contentType:"application/json",body:JSON.stringify({error:{message:"Denied"}})}));await input.fill("B");await expect(root.getByRole("alert")).toBeVisible();await expect(root.getByRole("img")).toHaveCount(0);await runtime.unroute(`**${endpoint}`);await input.fill("A");await expect(root.getByRole("img")).toBeVisible();
 await runtime.getByRole("button",{name:"Open chart panel",exact:true}).click();const panel=runtime.getByRole("dialog",{name:"Chart panel",exact:true}),localInput=panel.getByRole("textbox",{name:"Local chart bucket",exact:true});await expect(panel.getByRole("img")).toBeVisible();const localFiltered=runtime.waitForResponse(r=>r.url().endsWith(endpoint));await localInput.fill("B");expect((await(await localFiltered).json()).rows).toEqual([{bucket:"B","avg:qty":50}]);await expect(panel.getByRole("img")).toBeVisible();await panel.getByRole("button",{name:"Close chart panel",exact:true}).click();await expect(input).toHaveValue("A");await runtime.getByRole("button",{name:"Open chart panel",exact:true}).click();await expect(localInput).toHaveValue("");await expect(panel.getByRole("img")).toBeVisible();await panel.getByRole("button",{name:"Close chart panel",exact:true}).click();
 if(process.env.PLATFORM_SCREENSHOTS){await root.screenshot({path:info.outputPath("module-chart.png")});await runtime.setViewportSize({width:390,height:844});await runtime.evaluate(()=>new Promise<void>(r=>requestAnimationFrame(()=>requestAnimationFrame(()=>r()))));await root.scrollIntoViewIfNeeded();await root.screenshot({path:info.outputPath("module-chart-narrow.png")});}
 await runtime.reload();await expect(input).toHaveValue("");await expect(root.getByRole("img")).toBeVisible();
});
