import {expect,test} from "@playwright/test";
import {decide,fresh,open,pageUIProfile} from "./host";

test("exact decimal inputs drive released queries without floating rounding or stale results from invalid drafts",async({page,request},info)=>{
 test.setTimeout(60_000);
 const name=fresh("decimal").replace(/[^a-z0-9]/gi,"").toLowerCase(),type=`build.${name}`,object=fresh("OBJ"),id=fresh("PAGE"),app=fresh("APP"),ref={app:"build",kind:"object",name:type},decimal=(value:string)=>({kind:"decimal",value});
 await decide(request,"manager","build","build.object.create",{type:"build.object",id:object},{name,title:"Quantity notes",fields:[{name:"note",title:"Note",type:"text"},{name:"count",title:"Count",type:"integer"}]});await decide(request,"manager","build","build.object.publish",{type:"build.object",id:object},{});
 for(const [suffix,count] of [["ONE",1],["TWO",2],["THREE",3]])await decide(request,"desk","build",`${type}.create`,{type,id:`${name}${suffix}`},{note:`DECIMAL-${suffix}`,count});
 const doc={formatVersion:2,uiProfile:pageUIProfile,root:"root",nodes:{root:{kind:"rows",children:["threshold","table"]},threshold:{kind:"widget",section:"threshold",valueVariable:"threshold"},table:{kind:"widget",section:"table"}},variables:{threshold:{scope:"page",type:"string",mode:"state",initial:"0"},window:{scope:"page",type:"object-set",mode:"resource",source:{kind:"plan",query:"read"}}},queries:{read:{object:ref,limit:10,conditions:[{field:"count",op:">",value:{literal:0}}]}}};
 await decide(request,"manager","build","build.page.create",{type:"build.page",id},{name,title:"Quantity threshold desk",object:type,sections:[{id:"threshold",widget:"input",configVersion:1,title:"Quantity threshold"},{id:"table",widget:"table",configVersion:1,title:"Above threshold",fields:["note"],collectionVariable:"window"}],document:doc});
 await open(page,"manager",`/compose?id=${id}`);const tree=page.getByRole("region",{name:"Widgets and layout",exact:true}),inspector=page.getByRole("region",{name:"The widget in hand",exact:true});await tree.getByRole("button",{name:"Page variables",exact:true}).click();await inspector.getByRole("combobox",{name:"Choose page variable",exact:true}).selectOption("threshold");await inspector.getByRole("combobox",{name:"Value type",exact:true}).selectOption("decimal");await inspector.getByLabel("Initial value",{exact:true}).fill("1.9999999999999999");await inspector.getByLabel("Initial value",{exact:true}).blur();await tree.getByRole("button",{name:"Query plans",exact:true}).click();await inspector.getByRole("combobox",{name:"Query condition value",exact:true}).selectOption("threshold");
 await page.getByRole("button",{name:"Save",exact:true}).click();await expect(page.getByRole("button",{name:"Save",exact:true})).toBeDisabled();await page.getByRole("button",{name:"Review release",exact:true}).click();await page.getByRole("button",{name:"Check draft and dependencies",exact:true}).click();await page.getByRole("button",{name:"Save immutable candidate",exact:true}).click();await page.getByRole("button",{name:"Activate release",exact:true}).click();
 const operation=await page.context().newPage(),route=`/page?app=build&kind=page&name=${name}`;await open(operation,"desk",route);const input=operation.getByRole("textbox",{name:"Quantity threshold",exact:true}),table=operation.getByRole("table");await expect(input).toHaveValue("1.9999999999999999");await expect(table.getByText("DECIMAL-TWO",{exact:true})).toBeVisible();await expect(table.getByText("DECIMAL-THREE",{exact:true})).toBeVisible();await expect(table.getByText("DECIMAL-ONE",{exact:true})).toHaveCount(0);
 await input.fill("-0.");await expect(input).toHaveValue("-0.");await expect(input.locator("..").getByText("Invalid numeric value.",{exact:true})).toBeVisible();await expect(operation.getByText("DECIMAL-TWO",{exact:true})).toHaveCount(0);await input.fill("2.0000000000000001");await expect(table.getByText("DECIMAL-THREE",{exact:true})).toBeVisible();await expect(table.getByText("DECIMAL-TWO",{exact:true})).toHaveCount(0);await input.fill("0.100");await expect(input).toHaveValue("0.100");await expect(table.getByText("DECIMAL-ONE",{exact:true})).toBeVisible();
 if(process.env.PLATFORM_SCREENSHOTS)await operation.screenshot({path:info.outputPath("decimal-threshold.png"),fullPage:true});
 let release!:()=>void,held=false;const wait=new Promise<void>(resolve=>release=resolve);await operation.route(`**/v1/records/${type}?*`,async r=>{const domain=new URL(r.request().url()).searchParams.get("domain")??"";if(domain.includes('"2.0000000000000001"')&&!held){const response=await r.fetch();held=true;await wait;await r.fulfill({response});}else await r.continue();});await input.fill("2.0000000000000001");await expect.poll(()=>held).toBe(true);await input.fill("1.9999999999999999");release();await expect(table.getByText("DECIMAL-TWO",{exact:true})).toBeVisible();await operation.unroute(`**/v1/records/${type}?*`);await operation.reload();await expect(input).toHaveValue("1.9999999999999999");
 // Application state uses the same numeric codec and candidate owner.
 await decide(request,"manager","build","build.app.create",{type:"build.app",id:app},{name:`${name}app`,title:"Quantity desk",pages:[name],uiProfile:pageUIProfile,variables:{threshold:{scope:"application",type:"decimal",mode:"state",initial:decimal("1.9999999999999999")}}});await decide(request,"manager","build","build.app.publish",{type:"build.app",id:app},{});
 const saved=await(await request.get(`/v1/records/build.page/${id}`,{headers:{Authorization:"Bearer manager"}})).json();saved.record.document.variables.threshold={scope:"application",type:"decimal",mode:"shared",writable:true,source:{kind:"application",variable:"threshold"}};await decide(request,"manager","build","build.page.edit",{type:"build.page",id},{document:saved.record.document});await decide(request,"manager","build","build.page.publish",{type:"build.page",id},{});
 await open(page,"manager",`/application?id=${app}`);await page.getByRole("button",{name:"Review application release",exact:true}).click();await page.getByRole("button",{name:"Check draft and dependencies",exact:true}).click();await page.getByRole("button",{name:"Save immutable candidate",exact:true}).click();await page.getByRole("button",{name:"Activate release",exact:true}).click();const sharedRoute=`${route}&application=build:${name}app&instance=main`;await operation.evaluate(route=>{location.hash=route},sharedRoute);await expect(input).toHaveValue("1.9999999999999999");await input.fill("-");await expect(input).toHaveValue("-");await expect(input.locator("..").getByText("Invalid numeric value.",{exact:true})).toBeVisible();await input.fill("2.0000000000000001");await expect(table.getByText("DECIMAL-TWO",{exact:true})).toHaveCount(0);await operation.getByRole("button",{name:"New application instance",exact:true}).click();await expect(input).toHaveValue("1.9999999999999999");await expect(table.getByText("DECIMAL-TWO",{exact:true})).toBeVisible();await operation.evaluate(route=>{location.hash=route},sharedRoute);await expect(input).toHaveValue("2.0000000000000001");
 if(process.env.PLATFORM_SCREENSHOTS){await operation.setViewportSize({width:390,height:844});await operation.evaluate(()=>new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve()))));await operation.screenshot({path:info.outputPath("decimal-threshold-narrow.png"),fullPage:true});}await operation.getByRole("button",{name:"Close application instance",exact:true}).click();await operation.evaluate(route=>{location.hash=route},sharedRoute);await expect(input).toHaveValue("1.9999999999999999");
});
