import {expect,test} from "@playwright/test";
import {decide,fresh,open,pageUIProfile,stableReadRevision} from "./host";

test("four native observation kinds freeze original identities, complete statistics and independent asset availability",async({page,request},info)=>{
 test.setTimeout(150_000);page.setDefaultTimeout(10_000);
 const name=fresh("obs").replace(/[^a-z0-9]/gi,"").toLowerCase(),samples=`build.${name}`,assets=`build.${name}assets`,id=fresh("PAGE"),ref=(name:string)=>({app:"build",kind:"object",name}),asset=ref(assets),sample=ref(samples),headers={Authorization:"Bearer manager"};
 for(const [type,fields] of [[assets,[{name:"name",title:"Asset name",type:"text"},{name:"availability",title:"Asset availability",type:"decimal"}]],[samples,[{name:"at",title:"Business event time",type:"datetime"},{name:"pressure",title:"Pressure",type:"decimal"},{name:"temperature",title:"Temperature",type:"decimal"},{name:"availability",title:"Sample availability",type:"decimal"},{name:"asset",title:"Original asset",type:"reference",ref:assets}]]] as const){const object=fresh("OBJ");await decide(request,"manager","build","build.object.create",{type:"build.object",id:object},{name:type.slice(6),title:type===assets?"Actual assets":"Actual observations",fields});await decide(request,"manager","build","build.object.publish",{type:"build.object",id:object},{});}
 for(const [assetID,value,title]of [["A",80,"Original asset A"],["B",98,"Original asset B"]] as const)await decide(request,"manager","build",`${assets}.create`,{type:assets,id:assetID},{name:title,availability:value});
 for(let i=0;i<132;i++)await decide(request,"manager","build",`${samples}.create`,{type:samples,id:`S${String(i).padStart(3,"0")}`},{at:new Date(Date.UTC(2026,9,3,0,0,i)).toISOString(),pressure:i,temperature:100+i,availability:96,asset:i%2?"B":"A"});
 const queryID=fresh("QUERY"),queryName=`${name}history`;await decide(request,"manager","build","build.query.create",{type:"build.query",id:queryID},{name:queryName,title:"Original history by asset",description:"Actual ordered business samples",object:samples,by:"asset",sort:["-at","id"],limit:100});await decide(request,"manager","build","build.query.publish",{type:"build.query",id:queryID},{});
 const defs=await(await request.get("/v1/definitions",{headers})).json(),definitions=Array.isArray(defs)?defs:defs.definitions,version=definitions.find((d:any)=>d.ref.kind==="query"&&d.ref.name===queryName).version;
 const signals=[{field:"pressure",unit:"bar"},{field:"temperature",unit:"°C"},{field:"availability",unit:"%"}],sections:any[]=[
 {id:"table",widget:"observation",configVersion:1,title:"Original telemetry rows",collectionVariable:"samples",observation:{kind:"table",timeField:"at",signals,metadata:{asset:"asset"},assetField:"asset",assetObject:asset,rowHeight:30,rowOutput:"row",assetOutput:"asset"}},
 {id:"stats",widget:"observation",configVersion:1,title:"Original complete statistics",collectionVariable:"samples",recordVariable:"asset",observationContextVariable:"context",observationSignalVariable:"signal",observationThresholdVariable:"threshold",observationRowsVariable:"rows",observation:{kind:"statistics",timeField:"at",signals,assetField:"asset",assetObject:asset}},
 {id:"availability",widget:"observation",configVersion:1,title:"Original asset availability",object:assets,collectionVariable:"assets",observationHistoryVariable:"history",observationCountVariable:"count",observationMeanVariable:"mean",observation:{kind:"availability",timeField:"at",signals:signals.slice(2),averageField:"availability"}},
 {id:"series",widget:"observation",configVersion:1,title:"Original three time series",collectionVariable:"history",observation:{kind:"series",timeField:"at",signals}},
 {id:"detail",widget:"detail",configVersion:1,title:"Original asset detail",object:assets,recordVariable:"asset",fields:["name"]}];
 const variables:any={},queries:any={};for(const key of ["samples","history","context","assets"]){variables[key]={scope:"page",type:"object-set",mode:"resource",source:{kind:"plan",query:key}};queries[key]={object:key==="assets"?asset:sample,limit:key==="assets"?1:100,sort:key==="assets"?["id"]:["-at","id"],...(key==="context"?{query:{ref:{app:"build",kind:"query",name:queryName},sourceVersion:version},for:{variable:"asset"}}:{})};}
 for(const port of ["row","asset"])variables[port]={scope:"page",type:"record",mode:"resource",source:{kind:"record",section:"table",port}};for(const [key,initial]of [["signal","pressure"],["threshold","11.5"],["rows","10000"]])variables[key]={scope:"page",type:"string",mode:"state",initial};variables.count={scope:"page",type:"decimal",mode:"aggregate",source:{kind:"count",query:"assets"}};variables.mean={scope:"page",type:"number",mode:"aggregate",source:{kind:"aggregate",query:"assets",measure:"avg:availability"}};
 const localStats={...structuredClone(sections[1]),id:"localStats",title:"Local original statistics",collectionVariable:"localSamples",observationContextVariable:"localContext",observationSignalVariable:"localSignal",observationThresholdVariable:"localThreshold",observationRowsVariable:"localRows"};sections.push({id:"open",widget:"button",configVersion:1,title:"Open observation panel"},localStats,{id:"close",widget:"button",configVersion:1,title:"Close observation panel"});
 for(const [id,original]of [["localSamples","samples"],["localContext","context"],["localSignal","signal"],["localThreshold","threshold"],["localRows","rows"]]){variables[id]={...structuredClone(variables[original]),scope:"overlay",owner:"panel",...(variables[original].source?{source:{...variables[original].source,query:id}}:{})};if(queries[original])queries[id]={...structuredClone(queries[original]),owner:"panel"};}variables.open={scope:"page",type:"boolean",mode:"state",initial:false};
 const document={formatVersion:2,uiProfile:pageUIProfile,root:"root",nodes:{root:{kind:"rows",children:sections.filter(s=>!["localStats","close"].includes(s.id)).map(s=>s.id)},panelRoot:{kind:"rows",children:["localStats","close"]},...Object.fromEntries(sections.map(s=>[s.id,{kind:"widget",section:s.id}]))},variables,queries,overlays:{panel:{kind:"drawer",title:"Original observation panel",root:"panelRoot",openVariable:"open"}},events:[{source:"open",event:"click",effects:[{kind:"set", target:"open", value:true}]},{source:"close",event:"click",effects:[{kind:"set", target:"open", value:false}]}]};
 await decide(request,"manager","build","build.page.create",{type:"build.page",id},{name,title:"Original business observations",object:samples,sections,document});
 await open(page,"manager",`/compose?id=${id}`);await page.getByRole("textbox",{name:"What people call it",exact:true}).fill("Frozen original observations");await page.getByRole("region",{name:"Widgets and layout",exact:true}).getByRole("button",{name:"Original telemetry rows",exact:true}).click();const inspector=page.getByRole("region",{name:"The widget in hand",exact:true});await expect(inspector.getByRole("combobox",{name:"Observation view",exact:true})).toHaveValue("table");await inspector.getByRole("spinbutton",{name:"Observation row height",exact:true}).fill("25");await expect(page.getByRole("button",{name:"Save",exact:true})).toBeDisabled();await inspector.getByRole("spinbutton",{name:"Observation row height",exact:true}).fill("31");await page.getByRole("button",{name:"Save",exact:true}).click();const read=async()=>(await(await request.get(`/v1/records/build.page/${id}`,{headers})).json()).record;await expect.poll(async()=>((await read()).sections??[]).filter((s:any)=>s.widget==="observation").length).toBe(5);
 await page.getByRole("button",{name:"Review release",exact:true}).click();await page.getByRole("button",{name:"Check draft and dependencies",exact:true}).click();await page.getByRole("button",{name:"Save immutable candidate",exact:true}).click();const saved=await read();saved.sections[0].observation.signals[0].unit="LATER";saved.document.variables.threshold.initial="999";await decide(request,"manager","build","build.page.edit",{type:"build.page",id},{sections:saved.sections,document:saved.document});await page.getByRole("button",{name:"Activate release",exact:true}).click();
 const runtime=await page.context().newPage();await stableReadRevision(runtime);await open(runtime,"desk",`/page?app=build&kind=page&name=${name}`);const section=(title:string)=>runtime.getByRole("heading",{name:title,exact:true,level:3}).locator(".."),table=section("Original telemetry rows"),stats=section("Original complete statistics"),availability=section("Original asset availability"),series=section("Original three time series"),detail=section("Original asset detail");
 await expect(table).toContainText("Showing 100 of 132 matching records");await expect(stats).toContainText("132 observations · 132 numeric values in the original 10,000-row window");await expect(stats.getByRole("textbox",{name:"Alarm above",exact:true})).toHaveValue("11.5");await expect(availability).toContainText("Complete authorized average · 89 % · 2 records");await expect(series.getByRole("group",{name:/by original event time/})).toHaveCount(3);await expect(series.getByRole("img",{name:/^S131.*Pressure: 131 bar/})).toBeVisible();await expect(table).not.toContainText("LATER");
 await table.getByRole("cell",{name:"S131",exact:true}).click();await expect(detail).toContainText("Original asset B");await expect(stats).toContainText("Latest original sample · S131");await expect(stats).toContainText("66 original observations");await table.getByRole("cell",{name:"S130",exact:true}).click();await expect(detail).toContainText("Original asset A");await expect(stats).toContainText("Latest original sample · S130");
 await table.getByRole("button",{name:"Next",exact:true}).click();await expect(table).toContainText("101–132");await expect(detail).not.toContainText("Original asset A");await expect(stats).toContainText("132 observations");await expect(series.getByRole("img",{name:/^S131.*Pressure: 131 bar/})).toBeVisible();await expect(availability).toContainText("89 % · 2 records");
 await stats.getByRole("combobox",{name:"Observation window rows",exact:true}).selectOption("1000");await expect(stats).toContainText("original 1,000-row window");await stats.getByRole("combobox",{name:"Observation signal",exact:true}).selectOption("temperature");await expect(stats).toContainText("231");await stats.getByRole("textbox",{name:"Alarm above",exact:true}).fill("200");await expect(stats).toContainText("Above 200");await stats.getByRole("textbox",{name:"Alarm above",exact:true}).fill("");await expect(stats.getByRole("alert")).toContainText("invalid draft");await stats.getByRole("textbox",{name:"Alarm above",exact:true}).fill("100");await expect(stats).toContainText("Above 100");
 await runtime.getByRole("button",{name:"Open observation panel",exact:true}).click();const panel=runtime.getByRole("dialog",{name:"Original observation panel",exact:true}),local=panel.getByRole("heading",{name:"Local original statistics",exact:true}).locator("..");await expect(local.getByRole("textbox",{name:"Alarm above",exact:true})).toHaveValue("11.5");await expect(local).toContainText("132 observations");await local.getByRole("combobox",{name:"Observation signal",exact:true}).selectOption("temperature");await local.getByRole("textbox",{name:"Alarm above",exact:true}).fill("215");await expect(local).toContainText("Above 215");await panel.getByRole("button",{name:"Close observation panel",exact:true}).click();await expect(stats.getByRole("textbox",{name:"Alarm above",exact:true})).toHaveValue("100");await runtime.getByRole("button",{name:"Open observation panel",exact:true}).click();await expect(local.getByRole("textbox",{name:"Alarm above",exact:true})).toHaveValue("11.5");await expect(local.getByRole("combobox",{name:"Observation signal",exact:true})).toHaveValue("pressure");await panel.getByRole("button",{name:"Close observation panel",exact:true}).click();
 if(process.env.PLATFORM_SCREENSHOTS){await stats.screenshot({path:info.outputPath("observations-statistics.png")});await availability.screenshot({path:info.outputPath("observations-availability.png")});await series.screenshot({path:info.outputPath("observations-series.png")});await runtime.setViewportSize({width:390,height:844});await runtime.evaluate(()=>new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve()))));await expect(stats.getByRole("textbox",{name:"Alarm above",exact:true})).toBeVisible();await stats.screenshot({path:info.outputPath("observations-statistics-narrow.png")});await series.screenshot({path:info.outputPath("observations-series-narrow.png")});await runtime.setViewportSize({width:1280,height:720});}
 await runtime.route(`**/v1/aggregates/${samples}/query`,route=>route.fulfill({status:403,contentType:"application/json",body:'{"error":{"message":"Denied"}}'}));await stats.getByRole("textbox",{name:"Alarm above",exact:true}).fill("102");await expect(stats.getByRole("alert")).toContainText("could not be read");await expect(stats.getByText("Max",{exact:true})).toHaveCount(0);await expect(stats.getByRole("img",{name:/^S/})).toHaveCount(0);await runtime.unroute(`**/v1/aggregates/${samples}/query`);await stats.getByRole("textbox",{name:"Alarm above",exact:true}).fill("101");await expect(stats.getByText("Max",{exact:true})).toBeVisible();
 let release:()=>void=()=>{},finished:()=>void=()=>{},started=false;const gate=new Promise<void>(resolve=>release=resolve),done=new Promise<void>(resolve=>finished=resolve);await runtime.route(`**/v1/aggregates/${samples}/query`,async route=>{if(route.request().postDataJSON().window?.threshold!=="105")return route.continue();started=true;await gate;const response=await route.fetch();await route.fulfill({response});finished();});await stats.getByRole("textbox",{name:"Alarm above",exact:true}).fill("105");await expect.poll(()=>started).toBe(true);await stats.getByRole("textbox",{name:"Alarm above",exact:true}).fill("106");await expect(stats.getByText("Above 106",{exact:true})).toBeVisible();release();await done;await runtime.evaluate(()=>new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve()))));await expect(stats.getByText("Above 106",{exact:true})).toBeVisible();await expect(stats.getByText("Above 105",{exact:true})).toHaveCount(0);await runtime.unroute(`**/v1/aggregates/${samples}/query`);
 await runtime.reload();await expect(stats.getByRole("textbox",{name:"Alarm above",exact:true})).toHaveValue("11.5");await expect(stats.getByRole("combobox",{name:"Observation signal",exact:true})).toHaveValue("pressure");await expect(table).toContainText("Showing 100 of 132 matching records");await expect(detail).not.toContainText("Original asset B");
});
