import {expect,test} from "@playwright/test";
import {readFileSync} from "node:fs";
import {decide,fresh,open,pageUIProfile,stableReadRevision} from "./host";

test("context widgets jointly import and freeze actual home navigation, personnel queries and browser images",async({page,request},info)=>{
 test.setTimeout(120_000);page.setDefaultTimeout(10_000);
 const name=fresh("context").replace(/[^a-z0-9]/gi,"").toLowerCase(),asset=`build.${name}asset`,person=`build.${name}person`,id=fresh("PAGE"),homeID=fresh("HOME"),homeName=`${name}home`;
 const record=async(type:string,id:string)=>(await(await request.get(`/v1/records/${type}/${id}`,{headers:{Authorization:"Bearer manager"}})).json()).record;
 const make=async(suffix:string,fields:any[])=>{const object=fresh("OBJ");await decide(request,"manager","build","build.object.create",{type:"build.object",id:object},{name:`${name}${suffix}`,title:suffix==="asset"?"Original assets":"Business personnel",fields});await decide(request,"manager","build","build.object.publish",{type:"build.object",id:object},{});};
 await make("asset",[{name:"title",title:"Asset title",type:"text"}]);
 await make("person",[{name:"name",title:"Personnel name",type:"text"},{name:"shift",title:"Shift",type:"text"},{name:"asset",title:"Assigned asset",type:"reference",ref:asset},{name:"private",title:"Private personnel note",type:"text",read:["builder"]}]);
 for(const suffix of ["A","B"])await decide(request,"manager","build",`${asset}.create`,{type:asset,id:`${name}${suffix}`},{title:`ASSET-${suffix}`});
 for(let i=0;i<8;i++)await decide(request,"manager","build",`${person}.create`,{type:person,id:`${name}person${i}`},{name:i<2?"Same personnel name":`Person ${i}`,shift:i%2?"Night":"Day",asset:`${name}${i<2?"A":"B"}`,private:"PRIVATE-PERSONNEL"});
 const queries:Record<string,string>={};
 for(const [suffix,by] of [["all",""],["related","asset"]]){const q=fresh("QUERY"),queryName=`${name}${suffix}`;await decide(request,"manager","build","build.query.create",{type:"build.query",id:q},{name:queryName,title:suffix==="all"?"All original personnel":"Personnel by original asset",description:"Original published personnel association",object:person,domain:[],sort:["id"],limit:6,...(by?{by}:{})});await decide(request,"manager","build","build.query.publish",{type:"build.query",id:q},{});queries[suffix]=queryName;}
 await decide(request,"manager","build","build.page.create",{type:"build.page",id:homeID},{name:homeName,title:"Original published home",object:asset,sections:[{id:"welcome",widget:"text",configVersion:1,text:"HOME-ORIGINAL-RELEASE"}],document:{formatVersion:2,uiProfile:pageUIProfile,root:"root",nodes:{root:{kind:"rows",children:["welcome"]},welcome:{kind:"widget",section:"welcome"}},interface:{version:1}}});
 await decide(request,"manager","build","build.page.publish",{type:"build.page",id:homeID},{});
 const m=JSON.parse(readFileSync(new URL("../../packages/build/src/workshop/module-import/sample.workshop.json",import.meta.url),"utf8"));m.header.title="Original Studio";m.pages[0].name="Context Desk";
 const set=(id:string)=>({id,name:id,type:"objectSet",definitionKind:"objectSetDefinition",sourceObjectType:"Asset",dependsOn:[],objectSet:{objectType:"Asset",steps:[]}}),selected=(id:string,widget:string)=>({id,name:id,type:"object",definitionKind:"widgetOutput",dependsOn:[],widgetId:widget,widgetOutputKey:"activeObject"}),table=(id:string,set:string,active:string)=>({id,name:id==="table"?"Original assets":"Panel assets",type:"ObjectTable",config:{objectSetVarId:set,activeVarId:active,columns:[{key:"name"}]}}),trail=(id:string,selection:string)=>({id,name:id==="trail"?"Context trail":"Panel trail",type:"Breadcrumbs",config:{objectVarId:selection}}),avatars=(id:string,selection:string)=>({id,name:id==="people"?"Personnel group":"Panel personnel",type:"AvatarStack",config:{objectVarId:selection}}),image=(id:string)=>({id,name:id==="poster"?"Static poster":"Panel poster",type:"ImageWidget",config:{url:"https://images.example.invalid/platform.png",caption:id==="poster"?"Original public poster":"Panel public poster",height:160}});
 m.variables=[set("items"),selected("selected","table"),set("localItems"),selected("localSelected","localTable")];
 m.widgets={table:table("table","items","selected"),trail:trail("trail","selected"),people:avatars("people","selected"),poster:image("poster"),localTable:table("localTable","localItems","localSelected"),localTrail:trail("localTrail","localSelected"),localPeople:avatars("localPeople","localSelected"),localPoster:image("localPoster"),trigger:{id:"trigger",name:"Open context panel",type:"SingleButton",config:{label:"Open context panel",eventActions:[{kind:"openOverlay",overlayId:"panel"}]}},close:{id:"close",name:"Close context panel",type:"SingleButton",config:{label:"Close context panel",eventActions:[{kind:"closeOverlay",overlayId:"panel"}]}}};
 m.sections={root:{id:"root",name:"Root",layout:"rows",children:["trail","people","poster","table","trigger"].map(id=>({kind:"widget",id}))},panel:{id:"panel",name:"Panel",layout:"rows",children:["localTrail","localPeople","localPoster","localTable","close"].map(id=>({kind:"widget",id}))}};m.overlays=[{id:"panel",name:"Original context panel",kind:"drawer",rootSectionId:"panel"}];
 await decide(request,"manager","build","build.page.create",{type:"build.page",id},{name,title:"Original context desk",object:asset,sections:[{id:"initial",widget:"text",configVersion:1,text:"Initial"}],document:{formatVersion:2,uiProfile:pageUIProfile,root:"root",nodes:{root:{kind:"rows",children:["initial"]},initial:{kind:"widget",section:"initial"}}}});
 const imageRequests:any[]=[];const posterBody='<svg xmlns="http://www.w3.org/2000/svg" width="600" height="200" viewBox="0 0 600 200"><rect width="600" height="200" fill="#29445b"/><path d="M0 200 L150 40 L270 160 L420 20 L600 200" fill="#80af8e"/><circle cx="520" cy="45" r="20" fill="#ffd37b"/></svg>';
 await page.context().route("https://images.example.invalid/platform.png",route=>{imageRequests.push(route.request().headers());return route.fulfill({status:200,contentType:"image/svg+xml",body:posterBody});});
 await open(page,"manager",`/compose?id=${id}`);await page.getByRole("button",{name:"Import Workshop module",exact:true}).click();const dialog=page.getByRole("dialog",{name:"Import Workshop module",exact:true});await dialog.getByRole("textbox",{name:"Source module JSON",exact:true}).fill(JSON.stringify(m));await dialog.getByRole("combobox",{name:"Map object Asset",exact:true}).selectOption(asset);await dialog.getByRole("combobox",{name:"Map field Asset.name",exact:true}).selectOption("title");
 for(const title of ["Context trail","Panel trail"]){const group=dialog.getByRole("group",{name:`Map breadcrumb ${title}`,exact:true});await group.getByRole("combobox",{name:"Breadcrumb home page",exact:true}).selectOption((await group.getByRole("combobox",{name:"Breadcrumb home page",exact:true}).locator("option").filter({hasText:"Original published home"}).getAttribute("value"))!);await group.getByRole("combobox",{name:"Breadcrumb record title field",exact:true}).selectOption("title");}
 for(const title of ["Personnel group","Panel personnel"]){const group=dialog.getByRole("group",{name:`Map participants ${title}`,exact:true});for(const [label,key] of [["All personnel query","all"],["Context personnel query","related"]]){const selector=group.getByRole("combobox",{name:label,exact:true}),value=await selector.locator("option").filter({hasText:queries[key]}).getAttribute("value");await selector.selectOption(value!);}await group.getByRole("combobox",{name:"Participant title field",exact:true}).selectOption("name");await group.getByRole("button",{name:"Shift",exact:true}).click();}
 await dialog.getByRole("checkbox").check();await expect(dialog.getByRole("button",{name:"Apply imported page draft",exact:true})).toBeEnabled();await dialog.getByRole("button",{name:"Apply imported page draft",exact:true}).click();await page.getByRole("region",{name:"Widgets and layout",exact:true}).getByRole("button",{name:"Static poster",exact:true}).click();const inspector=page.getByRole("region",{name:"The widget in hand",exact:true});await inspector.getByRole("spinbutton",{name:"Image height",exact:true}).fill("-1");await expect(page.getByRole("button",{name:"Save",exact:true})).toBeDisabled();await inspector.getByRole("spinbutton",{name:"Image height",exact:true}).fill("160");await page.getByRole("button",{name:"Save",exact:true}).click();let saved:any;await expect.poll(async()=>{saved=await record("build.page",id);return saved.sections?.filter((s:any)=>["breadcrumb","avatar-stack","static-image"].includes(s.widget)).length;}).toBe(6);
 await page.getByRole("button",{name:"Review release",exact:true}).click();await page.getByRole("button",{name:"Check draft and dependencies",exact:true}).click();await page.getByRole("button",{name:"Save immutable candidate",exact:true}).click();saved.sections.find((s:any)=>s.title==="Static poster").image.caption="LATER-DRAFT-POSTER";saved.sections.find((s:any)=>s.title==="Context trail").breadcrumb.homeLabel="LATER-DRAFT-HOME";await decide(request,"manager","build","build.page.edit",{type:"build.page",id},{sections:saved.sections});await page.getByRole("button",{name:"Activate release",exact:true}).click();
 const runtime=await page.context().newPage();await stableReadRevision(runtime);await open(runtime,"desk",`/page?app=build&kind=page&name=${name}`);const section=(title:string)=>runtime.getByRole("heading",{name:title,exact:true,level:3}).locator(".."),trailView=runtime.getByRole("navigation",{name:"Context trail",exact:true}),peopleView=section("Personnel group"),posterView=runtime.getByRole("figure",{name:"Original public poster",exact:true}),tableView=section("Original assets");
 await expect(peopleView).toContainText("6 of 8");await expect(peopleView.getByRole("listitem")).toHaveCount(6);await expect(peopleView).not.toContainText("PRIVATE-PERSONNEL");await expect(posterView.getByRole("img",{name:"Original public poster",exact:true})).toBeVisible();await expect(posterView).not.toContainText("LATER-DRAFT-POSTER");expect(imageRequests.length).toBeGreaterThan(0);expect(imageRequests.every(h=>!h.authorization&&!h.referer)).toBe(true);
 await tableView.getByRole("row").filter({hasText:"ASSET-A"}).click();await expect(trailView).toContainText("ASSET-A");await expect(peopleView.getByRole("listitem")).toHaveCount(2);await expect(peopleView).toContainText(`${name}person0`);await expect(peopleView).toContainText(`${name}person1`);await expect(peopleView).toContainText("Same personnel name");
 if(process.env.PLATFORM_SCREENSHOTS){await runtime.screenshot({path:info.outputPath("context-views.png"),fullPage:true});await runtime.setViewportSize({width:390,height:844});await runtime.screenshot({path:info.outputPath("context-views-narrow.png"),fullPage:true});await runtime.setViewportSize({width:1280,height:720});}
 await trailView.getByRole("button",{name:"Context Desk",exact:true}).click();await expect(trailView).not.toContainText("ASSET-A");await expect(peopleView).toContainText("6 of 8");
 await tableView.getByRole("row").filter({hasText:"ASSET-A"}).click();await runtime.getByRole("button",{name:"Open context panel",exact:true}).click();const panel=runtime.getByRole("dialog",{name:"Original context panel",exact:true}),localTrail=panel.getByRole("navigation",{name:"Panel trail",exact:true}),localPeople=panel.getByRole("heading",{name:"Panel personnel",exact:true}).locator("..");await expect(localPeople).toContainText("6 of 8");await panel.getByRole("row").filter({hasText:"ASSET-B"}).click();await expect(localTrail).toContainText("ASSET-B");await expect(localPeople.getByRole("listitem")).toHaveCount(6);await localTrail.getByRole("button",{name:"Context Desk",exact:true}).click();await expect(localPeople).toContainText("6 of 8");await panel.getByRole("button",{name:"Close context panel",exact:true}).click();await expect(trailView).toContainText("ASSET-A");await expect(peopleView.getByRole("listitem")).toHaveCount(2);
 await runtime.getByRole("button",{name:"Open context panel",exact:true}).click();await expect(localTrail).not.toContainText("ASSET-B");await panel.getByRole("button",{name:"Close context panel",exact:true}).click();
 await runtime.route(`**/v1/records/${person}?*`,route=>route.fulfill({status:403,contentType:"application/json",body:'{"error":{"message":"Denied"}}'}));await runtime.reload();await expect(section("Personnel group").getByRole("alert")).toContainText("could not be read");await expect(section("Personnel group").getByRole("listitem")).toHaveCount(0);await runtime.unroute(`**/v1/records/${person}?*`);await runtime.reload();await expect(section("Personnel group")).toContainText("6 of 8");
 await runtime.route(`**/v1/records/${asset}/${name}B`,route=>route.fulfill({status:403,contentType:"application/json",body:'{"error":{"message":"Denied"}}'}));await section("Original assets").getByRole("row").filter({hasText:"ASSET-B"}).click();await expect(runtime.getByRole("alert").filter({hasText:"The breadcrumb record could not be confirmed."})).toBeVisible();await expect(section("Personnel group").getByRole("listitem")).toHaveCount(0);await runtime.getByRole("navigation",{name:"Context trail",exact:true}).getByRole("button",{name:"Context Desk",exact:true}).click();await expect(section("Personnel group")).toContainText("6 of 8");await runtime.unroute(`**/v1/records/${asset}/${name}B`);await runtime.reload();await expect(section("Personnel group")).toContainText("6 of 8");
 let release:()=>void=()=>{};const gate=new Promise<void>(r=>release=r);let started=false;await runtime.route(`**/v1/records/${asset}/${name}B`,async route=>{started=true;await gate;await route.continue();});await section("Original assets").getByRole("row").filter({hasText:"ASSET-B"}).click();await expect.poll(()=>started).toBe(true);await section("Original assets").getByRole("row").filter({hasText:"ASSET-A"}).click();await expect(runtime.getByRole("navigation",{name:"Context trail",exact:true})).toContainText("ASSET-A");release();await runtime.unroute(`**/v1/records/${asset}/${name}B`);await runtime.evaluate(()=>new Promise<void>(r=>requestAnimationFrame(()=>requestAnimationFrame(()=>r()))));await expect(runtime.getByRole("navigation",{name:"Context trail",exact:true})).not.toContainText("ASSET-B");await expect(section("Personnel group").getByRole("listitem")).toHaveCount(2);
 await runtime.getByRole("navigation",{name:"Context trail",exact:true}).getByRole("button",{name:"Original Studio",exact:true}).click();await expect(runtime.getByRole("heading",{name:"Original published home",exact:true})).toBeVisible();await expect(runtime.getByText("HOME-ORIGINAL-RELEASE",{exact:true})).toBeVisible();
});
