import {expect,test} from "@playwright/test";
import {readFileSync} from "node:fs";
import {decide,fresh,open,pageUIProfile,stableReadRevision} from "./host";

test("source pie and donut freeze original complete counts and clear private, refused and closed-scope distributions",async({page,request},info)=>{
 test.setTimeout(90_000);
 const name=fresh("pies").replace(/[^a-z0-9]/gi,"").toLowerCase(),type=`build.${name}`,object=fresh("OBJ"),id=fresh("PAGE");
 await decide(request,"manager","build","build.object.create",{type:"build.object",id:object},{name,title:"Distribution assets",fields:[{name:"note",title:"Note",type:"text"},{name:"bucket",title:"Status",type:"text"},{name:"priority",title:"Priority",type:"text"},{name:"secret",title:"Private grouping",type:"text",read:["builder"]}]});await decide(request,"manager","build","build.object.publish",{type:"build.object",id:object},{});for(const [suffix,priority] of [["A1","high"],["A2","high"],["A3","low"],["B1","low"],["B2","low"],["C1","medium"]])await decide(request,"manager","build",`${type}.create`,{type,id:`${name}${suffix}`},{note:suffix,bucket:suffix[0],priority,secret:"private"});
 const m=JSON.parse(readFileSync(new URL("../../packages/build/src/workshop/module-import/sample.workshop.json",import.meta.url),"utf8")),pie=(id:string,name:string,set="notes",groupBy="status",variant?:string)=>({id,name,type:"ChartPie",config:{objectSetVarId:set,groupBy,...(variant?{variant}:{})}});
 m.widgets.status=pie("status","Status Distribution");m.widgets.priority=pie("priority","Priority Breakdown","notes","priority","donut");m.widgets.hidden=pie("hidden","Private distribution","notes","secret");m.widgets.hiddenCondition=pie("hiddenCondition","Private conditional distribution","privateNotes");m.widgets.local=pie("local","Local distribution","localNotes","status","donut");m.widgets.input={id:"input",name:"Distribution filter",type:"TextInput",config:{variableId:"scratch",label:"Distribution filter"}};m.widgets.localInput={id:"localInput",name:"Local distribution filter",type:"TextInput",config:{variableId:"localScratch",label:"Local distribution filter"}};m.widgets.trigger={id:"trigger",name:"Open distribution",type:"SingleButton",config:{label:"Open distribution",eventActions:[{kind:"openOverlay",overlayId:"panel"}]}};m.widgets.close={id:"close",name:"Close distribution",type:"SingleButton",config:{label:"Close distribution",eventActions:[{kind:"closeOverlay",overlayId:"panel"}]}};
 m.variables.find((v:any)=>v.id==="scratch").staticValue="";m.variables.find((v:any)=>v.id==="notes").objectSet.steps=[{op:"where",clauses:[{id:"status",property:"status",op:"contains",varId:"scratch"}]}];m.variables.push({id:"localScratch",name:"Local status",type:"string",definitionKind:"static",staticValue:""},{id:"localNotes",name:"Local notes",type:"objectSet",definitionKind:"objectSetDefinition",sourceObjectType:"Asset",objectSet:{objectType:"Asset",steps:[{op:"where",clauses:[{id:"local",property:"status",op:"contains",varId:"localScratch"}]}]}},{id:"privateNotes",name:"Private notes",type:"objectSet",definitionKind:"objectSetDefinition",sourceObjectType:"Asset",objectSet:{objectType:"Asset",steps:[{op:"where",clauses:[{id:"private",property:"secret",op:"is",value:"private"}]}]}});
 m.sections={root:{id:"root",name:"Root",layout:"rows",children:["input","table","status","priority","hidden","hiddenCondition","trigger"].map(id=>({kind:"widget",id}))},panel:{id:"panel",name:"Panel",layout:"rows",children:["localInput","local","close"].map(id=>({kind:"widget",id}))}};m.overlays=[{id:"panel",name:"Distribution panel",kind:"drawer",rootSectionId:"panel"}];
 await decide(request,"manager","build","build.page.create",{type:"build.page",id},{name,title:"Imported distributions",object:type,sections:[{id:"initial",widget:"table",configVersion:1,fields:["note"]}],document:{formatVersion:2,uiProfile:pageUIProfile,root:"root",nodes:{root:{kind:"rows",children:["initial"]},initial:{kind:"widget",section:"initial"}}}});
 await open(page,"manager",`/compose?id=${id}`);await page.getByRole("button",{name:"Import Workshop module",exact:true}).click();const dialog=page.getByRole("dialog",{name:"Import Workshop module",exact:true});await dialog.getByRole("textbox",{name:"Source module JSON",exact:true}).fill(JSON.stringify(m));await dialog.getByRole("combobox",{name:"Map object Asset",exact:true}).selectOption(type);for(const [source,target] of [["name","note"],["status","bucket"],["priority","priority"],["secret","secret"]])await dialog.getByRole("combobox",{name:`Map field Asset.${source}`,exact:true}).selectOption(target);await dialog.getByRole("checkbox").check();await dialog.getByRole("button",{name:"Apply imported page draft",exact:true}).click();const tree=page.getByRole("region",{name:"Widgets and layout",exact:true}),inspector=page.getByRole("region",{name:"The widget in hand",exact:true});await tree.getByRole("button",{name:"Priority Breakdown",exact:true}).click();await expect(inspector.getByRole("combobox",{name:"Pie presentation",exact:true})).toHaveValue("donut");await inspector.getByRole("combobox",{name:"Pie presentation",exact:true}).selectOption("pie");await inspector.getByRole("combobox",{name:"Pie presentation",exact:true}).selectOption("donut");await page.getByRole("button",{name:"Query plans",exact:true}).click();await page.getByRole("combobox",{name:"Choose query plan",exact:true}).selectOption({index:1});await page.getByRole("spinbutton",{name:"Query window limit",exact:true}).fill("1");await page.getByRole("button",{name:"Save",exact:true}).click();let saved:any;await expect.poll(async()=>{saved=(await(await request.get(`/v1/records/build.page/${id}`,{headers:{Authorization:"Bearer manager"}})).json()).record;return saved.sections?.filter((s:any)=>s.widget==="chart").length;}).toBe(5);
 await page.getByRole("button",{name:"Review release",exact:true}).click();await page.getByRole("button",{name:"Check draft and dependencies",exact:true}).click();await page.getByRole("button",{name:"Save immutable candidate",exact:true}).click();saved.sections.find((s:any)=>s.title==="Priority Breakdown").chartVariant="pie";await decide(request,"manager","build","build.page.edit",{type:"build.page",id},{sections:saved.sections});await page.getByRole("button",{name:"Activate release",exact:true}).click();
 const runtime=await page.context().newPage();await stableReadRevision(runtime);const endpoint=`/v1/aggregates/${type}/query`;let reads=0;runtime.on("request",r=>{if(r.url().endsWith(endpoint)){reads++;expect(r.postDataJSON().measures).toEqual(["count"]);expect(r.postDataJSON().limit).toBeUndefined();expect(r.postDataJSON().maxRows).toBe(4096);}});const statusRead=runtime.waitForResponse(r=>r.url().endsWith(endpoint)&&r.request().postDataJSON().groups[0]==="bucket"),priorityRead=runtime.waitForResponse(r=>r.url().endsWith(endpoint)&&r.request().postDataJSON().groups[0]==="priority");await open(runtime,"desk",`/page?app=build&kind=page&name=${name}`);const section=(title:string)=>runtime.getByRole("heading",{name:title,exact:true}).locator(".."),status=section("Status Distribution"),priority=section("Priority Breakdown"),input=runtime.getByRole("textbox",{name:"Distribution filter",exact:true});await expect(status.getByRole("img")).toBeVisible();await expect(priority.getByRole("img")).toBeVisible();expect((await(await statusRead).json()).rows).toEqual([{bucket:"A",count:3},{bucket:"B",count:2},{bucket:"C",count:1}]);expect((await(await priorityRead).json()).rows).toEqual([{priority:"high",count:2},{priority:"low",count:3},{priority:"medium",count:1}]);await expect(runtime.getByText("1–1 of 6",{exact:true})).toBeVisible();for(const title of ["Private distribution","Private conditional distribution"])await expect(runtime.getByRole("heading",{name:title,exact:true})).toHaveCount(0);const before=reads;await runtime.getByRole("button",{name:"Next page",exact:true}).click();await expect(runtime.getByText("2–2 of 6",{exact:true})).toBeVisible();expect(reads).toBe(before);
 if(process.env.PLATFORM_SCREENSHOTS){await status.screenshot({path:info.outputPath("imported-pie.png")});await priority.screenshot({path:info.outputPath("imported-donut.png")});await runtime.setViewportSize({width:390,height:844});await runtime.evaluate(()=>new Promise<void>(r=>requestAnimationFrame(()=>requestAnimationFrame(()=>r()))));await priority.scrollIntoViewIfNeeded();await priority.screenshot({path:info.outputPath("imported-donut-narrow.png")});await runtime.setViewportSize({width:1280,height:720});}
 await input.fill("Z");await expect(status.getByText("No data",{exact:true})).toBeVisible();await expect(priority.getByRole("img")).toHaveCount(0);await runtime.route(`**${endpoint}`,route=>route.fulfill({status:403,contentType:"application/json",body:JSON.stringify({error:{message:"Denied"}})}));await input.fill("A");await expect(status.getByRole("alert")).toBeVisible();await expect(status.getByRole("img")).toHaveCount(0);await runtime.unroute(`**${endpoint}`);await input.fill("B");await expect(status.getByRole("img")).toBeVisible();
 await runtime.getByRole("button",{name:"Open distribution",exact:true}).click();const panel=runtime.getByRole("dialog",{name:"Distribution panel",exact:true}),localInput=panel.getByRole("textbox",{name:"Local distribution filter",exact:true});await expect(panel.getByRole("img")).toBeVisible();const localRead=runtime.waitForResponse(r=>r.url().endsWith(endpoint)&&r.request().postDataJSON().domain?.[0]?.[2]==="A");await localInput.fill("A");expect((await(await localRead).json()).rows).toEqual([{bucket:"A",count:3}]);await panel.getByRole("button",{name:"Close distribution",exact:true}).click();await expect(input).toHaveValue("B");await runtime.getByRole("button",{name:"Open distribution",exact:true}).click();await expect(localInput).toHaveValue("");await expect(panel.getByRole("img")).toBeVisible();await panel.getByRole("button",{name:"Close distribution",exact:true}).click();await runtime.reload();await expect(input).toHaveValue("");await expect(status.getByRole("img")).toBeVisible();
});
