import {expect,test} from "@playwright/test";
import {readFileSync} from "node:fs";
import {decide,fresh,open,pageUIProfile,stableReadRevision} from "./host";

test("imported standalone links keep explicit frozen groups, original navigation and overlay record lifetime",async({page,request},info)=>{
 test.setTimeout(90_000);
 const name=fresh("links").replace(/[^a-z0-9]/gi,"").toLowerCase(),type=`build.${name}`,childType=`build.${name}child`,object=fresh("OBJ"),child=fresh("OBJ"),id=fresh("PAGE");
 await decide(request,"manager","build","build.object.create",{type:"build.object",id:object},{name,title:"Link parents",fields:[{name:"note",title:"Note",type:"text"}]});await decide(request,"manager","build","build.object.publish",{type:"build.object",id:object},{});
 await decide(request,"manager","build","build.object.create",{type:"build.object",id:child},{name:`${name}child`,title:"Linked items",fields:[{name:"label",title:"Label",type:"text"},{name:"parent",title:"Parent",type:"reference",ref:type,inverse:"items"},{name:"hidden",title:"Hidden parent",type:"reference",ref:type,inverse:"hiddenitems",read:["builder"]}]});await decide(request,"manager","build","build.object.publish",{type:"build.object",id:child},{});
 for(const suffix of ["A","B"])await decide(request,"desk","build",`${type}.create`,{type,id:`${name}${suffix}`},{note:`PARENT-${suffix}`});
 await decide(request,"manager","build",`${childType}.create`,{type:childType,id:`${name}child`},{label:"LINKED-B",parent:`${name}B`,hidden:`${name}B`});
 const m=JSON.parse(readFileSync(new URL("../../packages/build/src/module-import/sample.workshop.json",import.meta.url),"utf8"));
 m.widgets={table:m.widgets.table,links:{id:"links",name:"Standalone links",type:"Links",config:{objectVarId:"selected",linkTypes:[{label:"Public related",target:"Sensor",linkField:"assetId"},{label:"Hidden related",target:"Sensor",linkField:"hiddenAssetId"}]}},trigger:{id:"trigger",name:"Open local links",type:"SingleButton",config:{label:"Open local links",eventActions:[{kind:"openOverlay",overlayId:"panel"}]}},close:{id:"close",name:"Close local links",type:"SingleButton",config:{label:"Close local links",eventActions:[{kind:"closeOverlay",overlayId:"panel"}]}},picker:{id:"picker",name:"Local parents",type:"ObjectTable",config:{objectSetVarId:"localNotes",activeVarId:"localSelected",columns:[{key:"name"}],enableSelection:true,selectionMode:"single",enableInlineEdit:false}},localLinks:{id:"localLinks",name:"Local links",type:"Links",config:{objectVarId:"localSelected",linkTypeApiNames:["Asset.items"]}}};
 m.sections={root:{id:"root",name:"Root",layout:"rows",children:[{kind:"widget",id:"table"},{kind:"widget",id:"links"},{kind:"widget",id:"trigger"}]},panel:{id:"panel",name:"Panel",layout:"rows",children:[{kind:"widget",id:"picker"},{kind:"widget",id:"localLinks"},{kind:"widget",id:"close"}]}};
 m.variables=m.variables.filter((v:any)=>v.id!=="scratch");m.variables.push({...structuredClone(m.variables.find((v:any)=>v.id==="notes")),id:"localNotes",name:"Local notes"});m.variables.push({id:"localSelected",name:"Local selection",type:"object",definitionKind:"widgetOutput",widgetId:"picker",widgetOutputKey:"activeObject"});m.overlays=[{id:"panel",name:"Local link panel",kind:"drawer",rootSectionId:"panel"}];
 await decide(request,"manager","build","build.page.create",{type:"build.page",id},{name,title:"Linked page",object:type,sections:[{id:"initial",widget:"table",configVersion:1,fields:["note"]}],document:{formatVersion:2,uiProfile:pageUIProfile,root:"root",nodes:{root:{kind:"rows",children:["initial"]},initial:{kind:"widget",section:"initial"}}}});
 await open(page,"manager",`/compose?id=${id}`);await page.getByRole("button",{name:"Import Workshop module",exact:true}).click();const dialog=page.getByRole("dialog",{name:"Import Workshop module",exact:true});await dialog.getByRole("textbox",{name:"Source module JSON",exact:true}).fill(JSON.stringify(m));await dialog.getByRole("combobox",{name:"Map object Asset",exact:true}).selectOption(type);await dialog.getByRole("combobox",{name:"Map field Asset.name",exact:true}).selectOption("note");
 await expect(dialog.getByRole("button",{name:"Apply imported page draft",exact:true})).toBeDisabled();
 for(const [group,field] of [["Public related","parent"],["Hidden related","hidden"],["Asset.items","parent"]])await dialog.getByRole("combobox",{name:`Map related group ${group}`,exact:true}).selectOption(JSON.stringify([childType,field]));await dialog.getByRole("checkbox").check();await dialog.getByRole("button",{name:"Apply imported page draft",exact:true}).click();
 await page.getByRole("region",{name:"Widgets and layout",exact:true}).getByRole("button",{name:"Standalone links",exact:true}).click();const inspector=page.getByRole("region",{name:"The widget in hand",exact:true});await expect(inspector.getByRole("combobox",{name:"Input record binding",exact:true})).toBeVisible();await inspector.getByRole("textbox",{name:"Related group title",exact:true}).first().fill("Frozen related items");await inspector.getByRole("button",{name:"Add related group",exact:true}).click();await expect(page.getByRole("button",{name:"Save",exact:true})).toBeDisabled();await inspector.getByRole("button",{name:"Remove related group",exact:true}).last().click();await page.getByRole("button",{name:"Save",exact:true}).click();
 let saved:any;await expect.poll(async()=>{saved=(await(await request.get(`/v1/records/build.page/${id}`,{headers:{Authorization:"Bearer manager"}})).json()).record;return saved.sections?.find((s:any)=>s.widget==="record-links")?.recordLinks[0].title;}).toBe("Frozen related items");
 await page.getByRole("button",{name:"Review release",exact:true}).click();await page.getByRole("button",{name:"Check draft and dependencies",exact:true}).click();await page.getByRole("button",{name:"Save immutable candidate",exact:true}).click();saved.sections.find((s:any)=>s.widget==="record-links").recordLinks[0].title="Later draft links";await decide(request,"manager","build","build.page.edit",{type:"build.page",id},{sections:saved.sections,document:saved.document});await page.getByRole("button",{name:"Activate release",exact:true}).click();
 const runtime=await page.context().newPage();await stableReadRevision(runtime);await open(runtime,"desk",`/page?app=build&kind=page&name=${name}`);const table=runtime.getByRole("heading",{name:"Imported notes",exact:true}).locator(".."),links=runtime.getByRole("heading",{name:"Standalone links",exact:true}).locator("..");await table.getByRole("cell",{name:"PARENT-B",exact:true}).click();await expect(links.getByRole("heading",{name:/Frozen related items/})).toBeVisible();await expect(links.getByRole("cell",{name:"LINKED-B",exact:true})).toBeVisible();await expect(links.getByText("Hidden related",{exact:false})).toHaveCount(0);await expect(links.getByText("Later draft links",{exact:false})).toHaveCount(0);
 if(process.env.PLATFORM_SCREENSHOTS){await links.screenshot({path:info.outputPath("record-links.png")});await runtime.setViewportSize({width:390,height:844});await links.screenshot({path:info.outputPath("record-links-narrow.png")});await runtime.setViewportSize({width:1280,height:720});}
 await table.getByRole("cell",{name:"PARENT-A",exact:true}).click();await expect(links.getByRole("cell",{name:"LINKED-B",exact:true})).toHaveCount(0);await table.getByRole("cell",{name:"PARENT-B",exact:true}).click();await expect(links.getByRole("cell",{name:"LINKED-B",exact:true})).toBeVisible();await links.getByRole("cell",{name:"LINKED-B",exact:true}).click();const opened=runtime.getByRole("dialog",{name:`${name}child`,exact:true});await expect(opened.getByRole("heading",{name:`${name}child`,exact:true})).toBeVisible();await expect(opened.getByRole("definition").filter({hasText:/^LINKED-B$/})).toBeVisible();
 // A fresh workspace keeps the navigation assertion independent of window positioning.
 const local=await page.context().newPage();await open(local,"desk",`/page?app=build&kind=page&name=${name}`);await local.getByRole("button",{name:"Open local links",exact:true}).click();const panel=local.getByRole("dialog",{name:"Local link panel",exact:true});await expect(panel.getByText("Select a record to see it here.", {exact:true})).toBeVisible();await panel.getByRole("cell",{name:"PARENT-B",exact:true}).click();await expect(panel.getByRole("cell",{name:"LINKED-B",exact:true})).toBeVisible();await panel.getByRole("button",{name:"Close local links",exact:true}).click();await local.getByRole("button",{name:"Open local links",exact:true}).click();await expect(panel.getByRole("cell",{name:"LINKED-B",exact:true})).toHaveCount(0);await expect(panel.getByText("Select a record to see it here.", {exact:true})).toBeVisible();await panel.getByRole("button",{name:"Close local links",exact:true}).click();await local.reload();await expect(local.getByRole("heading",{name:"Standalone links",exact:true}).locator("..").getByText("Select a record to see it here.",{exact:true})).toBeVisible();
});
