import { expect, test } from "@playwright/test";
import { decide, fresh, open } from "./host";

test("typed page calls transfer a loop record, return output and expire after reload through a frozen release", async ({page,request},testInfo)=>{
  const name=fresh("calls").replace(/[^a-z0-9]/gi,"").toLowerCase(), type=`build.${name}`, object=fresh("OBJ"), source=fresh("PAGE"), target=fresh("PAGE"), a=fresh("NOTE"), b=fresh("NOTE");
  await decide(request,"manager","build","build.object.create",{type:"build.object",id:object},{name,title:"Call notes",fields:[{name:"note",title:"Note",type:"text"}],states:[{name:"open",title:"Open"},{name:"done",title:"Done"}],actions:[{name:"complete",title:"Complete note",from:["open"],to:"done"}]});
  await decide(request,"manager","build","build.object.publish",{type:"build.object",id:object},{});
  for(const [id,note] of [[a,"CALL-A"],[b,"CALL-B"]])await decide(request,"desk","build",`${type}.create`,{type,id},{note});
  await decide(request,"manager","build","build.page.create",{type:"build.page",id:target},{name:`${name}detail`,title:"Note handler",object:type,sections:[{widget:"detail",title:"Incoming note",fields:["note"]},{widget:"actions",title:"Handle note",actions:[`${type}.complete`]}]});
  await open(page,"manager",`/compose?id=${target}`);
  const tree=page.getByRole("region",{name:"Widgets and layout",exact:true}), inspector=page.getByRole("region",{name:"The widget in hand",exact:true});
  await tree.getByRole("button",{name:"Page interface",exact:true}).click();
  await inspector.getByRole("button",{name:"Add input",exact:true}).click();
  await inspector.getByLabel("Port name",{exact:true}).fill("record");await inspector.getByLabel("Port name",{exact:true}).press("Tab");
  await inspector.getByRole("combobox",{name:"Input type",exact:true}).selectOption("record");
  for(const title of ["Incoming note","Handle note"]){await tree.getByRole("button",{name:title,exact:true}).click();await inspector.getByRole("combobox",{name:"Input record binding",exact:true}).selectOption({label:"record"});}
  await tree.getByRole("button",{name:"Page variables",exact:true}).click();
  await inspector.getByRole("button",{name:"Add variable",exact:true}).click();
  await inspector.getByLabel("Variable label",{exact:true}).fill("Visited handler");
  await inspector.getByRole("combobox",{name:"Value type",exact:true}).selectOption("boolean");
  await inspector.getByRole("checkbox",{name:"Initial value",exact:true}).check();
  await inspector.getByRole("combobox",{name:"Variable mode",exact:true}).selectOption("constant");
  await inspector.getByRole("checkbox",{name:"Initial value",exact:true}).check();
  await tree.getByRole("button",{name:"Page interface",exact:true}).click();
  await inspector.getByRole("button",{name:"Add output",exact:true}).click();
  await inspector.getByLabel("Port name",{exact:true}).last().fill("visited");await inspector.getByLabel("Port name",{exact:true}).last().press("Tab");
  await inspector.getByRole("combobox",{name:"Output variable",exact:true}).selectOption({label:"Visited handler"});
  await tree.getByRole("button",{name:"Page settings",exact:true}).click();
  await tree.getByRole("button",{name:"Button",exact:true}).click();await inspector.getByLabel("Title",{exact:true}).fill("Return to notes");
  await inspector.getByRole("combobox",{name:"Click handler",exact:true}).selectOption("return");
  await page.getByRole("button",{name:"Save",exact:true}).click();await expect(page.getByRole("button",{name:"Save",exact:true})).toBeDisabled();
  await page.getByRole("button",{name:"Direct install",exact:true}).click();
  await decide(request,"manager","build","build.page.create",{type:"build.page",id:source},{name,title:"Call note list",object:type,sections:[{widget:"table",title:"Source notes",fields:["note"]},{widget:"detail",title:"Note cards",fields:["note"]},{widget:"text",title:"Return marker",text:"Returned to this note."}]});
  await open(page,"manager",`/compose?id=${source}`);
  await tree.getByRole("button",{name:"Page variables",exact:true}).click();await inspector.getByRole("button",{name:"Add variable",exact:true}).click();
  await inspector.getByLabel("Variable label",{exact:true}).fill("Notes window");await inspector.getByRole("combobox",{name:"Variable mode",exact:true}).selectOption("resource");await inspector.getByRole("combobox",{name:"Resource output kind",exact:true}).selectOption("query");await inspector.getByRole("combobox",{name:"Source widget",exact:true}).selectOption({label:"Source notes"});
  await tree.getByRole("button",{name:"Note cards",exact:true}).click();await tree.getByRole("button",{name:"Loop",exact:true}).click();await inspector.getByLabel("Container title",{exact:true}).fill("Callable notes");
  const loop=tree.getByRole("button",{name:/^Loop \d+/});
  await tree.getByRole("button",{name:"Page variables",exact:true}).click();await inspector.getByRole("button",{name:"Add variable",exact:true}).click();await inspector.getByLabel("Variable label",{exact:true}).fill("Returned here");await inspector.getByRole("combobox",{name:"Value type",exact:true}).selectOption("boolean");await inspector.getByRole("combobox",{name:"Variable scope",exact:true}).selectOption({label:"Callable notes"});
  const flag=await inspector.getByRole("combobox",{name:"Choose page variable",exact:true}).inputValue();
  await tree.getByRole("button",{name:"Return marker",exact:true}).click();await inspector.getByRole("combobox",{name:"Visible when",exact:true}).selectOption(flag);
  await loop.click();await tree.getByRole("button",{name:"Button",exact:true}).click();await inspector.getByLabel("Title",{exact:true}).fill("Open handler");await inspector.getByRole("combobox",{name:"Click handler",exact:true}).selectOption("navigate");await inspector.getByRole("combobox",{name:"Target page",exact:true}).selectOption({label:"Note handler"});
  const itemOption=await inspector.getByRole("combobox",{name:"Input record",exact:true}).locator("option").last().getAttribute("value");
  await inspector.getByRole("combobox",{name:"Input record",exact:true}).selectOption(itemOption!);await inspector.getByRole("combobox",{name:"Return visited to state",exact:true}).selectOption(flag);
  await page.getByRole("button",{name:"Save",exact:true}).click();await expect(page.getByRole("button",{name:"Save",exact:true})).toBeDisabled();
  const canvas=page.getByRole("region",{name:"The page",exact:true});
  await canvas.getByRole("button",{name:"Open handler",exact:true}).first().click();
  await expect(page.getByRole("heading",{name:"Note handler",exact:true})).toBeVisible();
  await expect(page.getByRole("region",{name:"Note handler",exact:true}).getByText("Actions do not run while you compose.",{exact:true}).first()).toBeVisible();
  await expect(page.getByRole("button",{name:"Complete note",exact:true})).toHaveCount(0);
  await page.getByRole("button",{name:"Return to notes",exact:true}).click();
  await page.getByRole("button",{name:"Review release",exact:true}).click();await page.getByRole("button",{name:"Check draft and dependencies",exact:true}).click();await page.getByRole("button",{name:"Save immutable candidate",exact:true}).click();await page.getByRole("button",{name:"Activate release",exact:true}).click();
  const operation=await page.context().newPage();await open(operation,"desk",`/page?app=build&kind=page&name=${name}`);
  const list=operation.getByRole("list",{name:"Callable notes",exact:true}), first=list.getByRole("region",{name:a,exact:true}), second=list.getByRole("region",{name:b,exact:true});
  await first.getByRole("button",{name:"Open handler",exact:true}).click();
  await expect(operation.getByRole("heading",{name:"Note handler",exact:true})).toBeVisible();
  await expect(operation.getByRole("definition").filter({hasText:/^CALL-A$/})).toBeVisible();
  expect(operation.url()).not.toContain(a);expect(operation.url()).not.toContain("CALL-A");
  await operation.getByRole("button",{name:"Complete note",exact:true}).click();
  await expect.poll(async()=>(await(await request.get(`/v1/records/${type}/${a}`,{headers:{Authorization:"Bearer desk"}})).json()).record.state).toBe("done");
  if(process.env.PLATFORM_SCREENSHOTS)await operation.screenshot({path:testInfo.outputPath("page-call-handler.png"),fullPage:true});
  await operation.getByRole("button",{name:"Return to notes",exact:true}).click();await expect(first.getByText("Returned to this note.",{exact:true})).toBeVisible();await expect(second.getByText("Returned to this note.",{exact:true})).toHaveCount(0);
  if(process.env.PLATFORM_SCREENSHOTS){
    await first.getByText("Returned to this note.",{exact:true}).scrollIntoViewIfNeeded();
    await operation.screenshot({path:testInfo.outputPath("page-call-returned.png"),fullPage:true});
    await operation.setViewportSize({width:390,height:844});
    await first.getByText("Returned to this note.",{exact:true}).scrollIntoViewIfNeeded();
    await operation.screenshot({path:testInfo.outputPath("page-call-returned-narrow.png"),fullPage:true});
    await operation.setViewportSize({width:1280,height:720});
  }
  // Deny the receiving page input while leaving caller card refreshes readable.
  await operation.route(`**/v1/records/${type}/${b}`,route=>new URLSearchParams(operation.url().split("?")[1]).get("name")===`${name}detail`?route.fulfill({status:403,contentType:"application/json",body:JSON.stringify({error:"Denied"})}):route.continue());
  await second.getByRole("button",{name:"Open handler",exact:true}).click();
  await expect(operation.getByRole("alert").filter({hasText:"A page record input is unavailable."})).toBeVisible();await expect(operation.getByRole("button",{name:"Complete note",exact:true})).toHaveCount(0);
  await operation.unroute(`**/v1/records/${type}/${b}`);
  await operation.evaluate((fragment)=>{location.hash=fragment;},`/page?app=build&kind=page&name=${name}`);
  await second.getByRole("button",{name:"Open handler",exact:true}).click();await expect(operation.getByRole("definition").filter({hasText:/^CALL-B$/})).toBeVisible();
  await operation.reload();await expect(operation.getByRole("alert").filter({hasText:"The page navigation context expired."})).toBeVisible();await expect(operation.getByRole("button",{name:"Complete note",exact:true})).toHaveCount(0);
});
