import {expect,test} from "@playwright/test";
import {createServer} from "node:http";
import {decide,fresh,open} from "./host";
import {pageUIManifest} from "../../packages/kernel/src/gen/host";

test("three original AI sources jointly import, freeze functions and show retained analysis and record-scoped conversation",async({page,request},info)=>{
 test.setTimeout(150_000);page.setDefaultTimeout(10_000);const name=fresh("aiview").replace(/[^a-z0-9]/gi,"").toLowerCase(),type=`build.${name}`,object=fresh("OBJ"),parent=fresh("PAGE"),provider=fresh("provider").replace(/[^a-z0-9]/gi,"").toLowerCase(),headers={Authorization:"Bearer manager"},calls:any[]=[];
 const server=createServer(async(req,res)=>{let body="";for await(const chunk of req)body+=chunk;const raw=JSON.parse(body),input=JSON.parse(raw.messages.find((m:any)=>m.role==="user").content);calls.push(input);const output=input.record?{reply:`Protocol fixture: ${input.record.name} · ${input.question} · history ${input.history.length}`} :{summary:`Protocol fixture analysis: ${input.name}`};res.setHeader("Content-Type","application/json");res.end(JSON.stringify({choices:[{message:{content:JSON.stringify(output)}}],usage:{prompt_tokens:10,completion_tokens:12,cost:0.001}}));});
 await new Promise<void>(resolve=>server.listen(0,"127.0.0.1",resolve));const address=server.address();if(!address||typeof address==="string")throw Error("fixture address");
 try{
  await decide(request,"manager","platform","platform.member.grant",{type:"platform.member",id:"manager-1"},{app:"ai",role:"admin"});
  await decide(request,"manager","ai","ai.provider.add",{type:"ai.provider",id:provider},{kind:"local",baseUrl:`http://127.0.0.1:${address.port}`,wire:"openai"});
  await decide(request,"manager","ai","ai.model.enable",{type:"ai.model",id:`${provider}/probe`},{access:"users"});
  await decide(request,"manager","build","build.object.create",{type:"build.object",id:object},{name,title:"Original AI records",fields:[{name:"name",title:"Name",type:"text"}]});await decide(request,"manager","build","build.object.publish",{type:"build.object",id:object},{});
  for(const id of ["A","B"])await decide(request,"manager","build",`${type}.create`,{type,id},{name:`Original context ${id}`});
  const bindings:any={},plans:string[]=[];for(const [kind,conversation]of [["analysis",false],["conversation",true]] as const){const id=fresh("FN"),fnName=`${name}${kind}`;await decide(request,"manager","build","build.function.create",{type:"build.function",id},{name:fnName,title:kind==="analysis"?"Fixed original analysis":"Fixed original conversation",description:"Local HTTP model protocol fixture",object:type,fields:["name"],instructions:"Use only the supplied authorized source context.",conversation,output:[{name:conversation?"reply":"summary",type:"string",description:"Typed original result",required:true}],model:`${provider}/probe`,maxInputBytes:8192,maxOutputBytes:1024,maxTokens:256,roles:["builder","user"]});await decide(request,"manager","build","build.function.publish",{type:"build.function",id},{});const defs=await(await request.get("/v1/definitions",{headers})).json(),d=defs.find((d:any)=>d.ref.kind==="function"&&d.ref.name===fnName);bindings[kind]={ref:d.ref,sourceVersion:d.version};
   await open(page,"manager","/candidate-test");await page.getByRole("combobox",{name:"Candidate kind"}).selectOption("function");await page.getByRole("combobox",{name:"Saved function draft"}).selectOption(id);const planTitle=`${name} ${kind} evaluation`;plans.push(planTitle);await page.getByRole("textbox",{name:"Test plan name"}).fill(planTitle);await page.getByRole("textbox",{name:"Model identifier"}).fill(`${provider}/probe`);await page.getByRole("checkbox",{name:"Require a measured release evaluation"}).check();await page.getByRole("textbox",{name:"Synthetic input (JSON object)"}).fill(JSON.stringify(conversation?{record:{name:"Synthetic conversation"},question:"Synthetic evaluation question",history:[]}:{name:"Synthetic analysis"}));await page.getByRole("textbox",{name:"Expected typed answer (JSON object)"}).fill(JSON.stringify(conversation?{reply:"Protocol fixture: Synthetic conversation · Synthetic evaluation question · history 0"}:{summary:"Protocol fixture analysis: Synthetic analysis"}));await page.getByRole("button",{name:"Save test plan"}).click();await expect(page.getByRole("status").filter({hasText:"Test plan saved."})).toBeVisible();}
  const widgets={table:{id:"table",name:"Original AI context table",type:"ObjectTable",config:{objectSetVarId:"filteredAssets",activeVarId:"selected",columns:[{key:"name"}]}},analyst:{id:"analyst",name:"Imported AI analyst",type:"AIPAnalyst",config:{contextVarId:"selected",outputVarId:"filteredAssets"}},generated:{id:"generated",name:"Imported AI generated",type:"AIPGenerated",config:{objectVarId:"selected"}},chat:{id:"chat",name:"Imported AI chatbot",type:"AIPChatbot",config:{historyVarId:"history",inputVarId:"question",suggestions:["Summarise this record"]}}};
  const module={id:"source",name:"Original AI sources",pages:[{id:"page",name:"Original AI sources",rootSectionId:"root"}],sections:{root:{id:"root",name:"Root",layout:"rows",children:Object.keys(widgets).map(id=>({kind:"widget",id}))}},widgets,variables:[{id:"filteredAssets",name:"Original assets",type:"objectSet",definitionKind:"objectSetDefinition",objectSet:{objectType:"Asset",steps:[]}},{id:"selected",name:"Selected original record",type:"object",definitionKind:"widgetOutput",widgetId:"table",widgetOutputKey:"activeObject"},{id:"question",name:"Question",type:"string",definitionKind:"static",staticValue:""},{id:"history",name:"History",type:"struct",definitionKind:"static",staticValue:[]}],overlays:[],unusedWidgetIds:[]};
  await decide(request,"manager","build","build.page.create",{type:"build.page",id:parent},{name:`${name}page`,title:"AI import",object:type,sections:[{id:"initial",widget:"text",configVersion:1,text:"Initial"}],document:{formatVersion:2,uiProfile:pageUIManifest.uiProfile,root:"root",nodes:{root:{kind:"rows",children:["initial"]},initial:{kind:"widget",section:"initial"}}}});
  await open(page,"manager",`/compose?id=${parent}`);await page.getByRole("button",{name:"Import Workshop module",exact:true}).click();const dialog=page.getByRole("dialog",{name:"Import Workshop module",exact:true});await dialog.getByRole("textbox",{name:"Source module JSON",exact:true}).fill(JSON.stringify(module));await dialog.getByRole("combobox",{name:"Map object Asset",exact:true}).selectOption(type);await dialog.getByRole("combobox",{name:"Map field Asset.name",exact:true}).selectOption("name");
  for(const [title,kind]of [["Imported AI analyst","analyst"],["Imported AI generated","generated"],["Imported AI chatbot","chat"]]){const group=dialog.getByRole("group",{name:`Map original AI ${title}`,exact:true});await group.getByRole("combobox",{name:"AI source interpretation",exact:true}).selectOption("record-scoped-functions");await group.getByRole("combobox",{name:"Fixed original AI function",exact:true}).selectOption(JSON.stringify(bindings[kind==="chat"?"conversation":"analysis"]));if(kind==="analyst")await group.getByRole("combobox",{name:"AI output interpretation",exact:true}).selectOption("display-only");if(kind==="chat"){await group.getByRole("combobox",{name:"Original AI context producer",exact:true}).selectOption("selected");await group.getByRole("combobox",{name:"AI reply field",exact:true}).selectOption("reply");await group.getByRole("combobox",{name:"AI history interpretation",exact:true}).selectOption("original-call-history");}}
  await dialog.getByRole("checkbox").check();await expect(dialog.getByRole("button",{name:"Apply imported page draft",exact:true})).toBeEnabled();await dialog.getByRole("button",{name:"Apply imported page draft",exact:true}).click();await page.getByRole("button",{name:"Save",exact:true}).click();await expect.poll(async()=>{const row=await(await request.get(`/v1/records/build.page/${parent}`,{headers})).json();return row.record.sections.filter((s:any)=>s.ai).length;}).toBe(3);
  await decide(request,"manager","build","build.page.publish",{type:"build.page",id:parent},{});await page.getByRole("button",{name:"Review release",exact:true}).click();await page.getByRole("button",{name:"Check draft and dependencies",exact:true}).click();await page.getByRole("button",{name:"Save immutable candidate",exact:true}).click();for(const title of plans){await page.getByRole("combobox",{name:"Evaluation plan"}).selectOption({label:title});await page.getByRole("button",{name:"Run measured evaluation"}).click();await expect.poll(async()=>{const reports=await(await request.get("/v1/records/build.evaluation?limit=500",{headers})).json();return reports.records.filter((r:any)=>r.function.startsWith(name)&&r.state==="passed").length;}).toBe(plans.indexOf(title)+1);await page.getByRole("button",{name:"Refresh evaluation reports"}).click();}await page.getByRole("button",{name:"Activate release",exact:true}).click();await expect(page.getByRole("status").filter({hasText:"Release active for operators."})).toBeVisible();
  const runtime=await page.context().newPage();runtime.setDefaultTimeout(10_000);await open(runtime,"desk",`/page?app=build&kind=page&name=${name}page`);const section=(title:string)=>runtime.getByRole("heading",{name:title,exact:true,level:3}).locator(".."),table=section("Original AI context table"),analyst=section("Imported AI analyst"),generated=section("Imported AI generated"),chat=section("Imported AI chatbot");
  await table.getByRole("cell",{name:"Original context A",exact:true}).click();
  for(const view of [analyst,generated]){await view.getByRole("button",{name:"Request original analysis",exact:true}).click();await expect(view).toContainText("Protocol fixture analysis: Original context A");}
  const question=chat.getByRole("textbox",{name:"AI question",exact:true});await question.fill("First actual question");await chat.getByRole("button",{name:"Send AI question",exact:true}).click();await expect(chat).toContainText("First actual question · history 0");await expect(question).toHaveValue("");
  await question.fill("Second actual question");await chat.getByRole("button",{name:"Send AI question",exact:true}).click();await expect(chat).toContainText("Second actual question · history 1");expect(calls.some(c=>c.question==="Second actual question"&&c.history[0]?.question==="First actual question")).toBe(true);
  await question.fill("Unsent context A draft");if(process.env.PLATFORM_SCREENSHOTS)await generated.screenshot({path:info.outputPath("original-ai-generated.png")});await table.getByRole("cell",{name:"Original context B",exact:true}).click();await expect(question).toHaveValue("");await expect(chat).not.toContainText("First actual question");await expect(analyst).not.toContainText("Protocol fixture analysis: Original context A");await question.fill("New context");await chat.getByRole("button",{name:"Send AI question",exact:true}).click();await expect(chat).toContainText("Original context B · New context · history 0");if(process.env.PLATFORM_SCREENSHOTS){await runtime.setViewportSize({width:390,height:844});await chat.screenshot({path:info.outputPath("original-ai-chat-narrow.png")});}await chat.getByRole("button",{name:"Reset AI view",exact:true}).click();await expect(chat).not.toContainText("New context · history 0");

 }finally{server.closeAllConnections();await new Promise<void>(resolve=>server.close(()=>resolve()));}
});
