import {expect,test} from "@playwright/test";
import {decide,fresh,open,pageUIProfile} from "./host";

test("record property variables use authorized fields and discard switched or refused record values after release",async({page,request},info)=>{
 test.setTimeout(60_000);
 const name=fresh("property").replace(/[^a-z0-9]/gi,"").toLowerCase(),type=`build.${name}`,object=fresh("OBJ"),id=fresh("PAGE"),ref={app:"build",kind:"object",name:type};
 await decide(request,"manager","build","build.object.create",{type:"build.object",id:object},{name,title:"Property notes",fields:[{name:"note",title:"Note",type:"text"},{name:"active",title:"Active",type:"boolean"},{name:"count",title:"Count",type:"integer"},{name:"secret",title:"Secret",type:"boolean",read:["builder"]}]});await decide(request,"manager","build","build.object.publish",{type:"build.object",id:object},{});
 for(const [suffix,active,count] of [["A",true,2],["B",false,1]])await decide(request,"desk","build",`${type}.create`,{type,id:`${name}${suffix}`},{note:`PROPERTY-${suffix}`,active,count});
 const doc={formatVersion:2,uiProfile:pageUIProfile,root:"root",nodes:{root:{kind:"rows",children:["table","detail","notice","button"]},table:{kind:"widget",section:"table"},detail:{kind:"widget",section:"detail"},notice:{kind:"widget",section:"notice",visibleWhen:"active"},button:{kind:"widget",section:"button",enabledWhen:"active"}},variables:{selected:{title:"Selected record",scope:"page",type:"record",mode:"resource",source:{kind:"record",section:"table"}},active:{title:"Active property",scope:"page",type:"boolean",mode:"constant",initial:false},count:{title:"Count property",scope:"page",type:"decimal",mode:"constant",initial:{kind:"decimal",value:"0"}},clicked:{scope:"page",type:"boolean",mode:"state",initial:false}},events:[{source:"button",event:"click",effects:[{kind:"set", target:"clicked", value:true}]}]};
 await decide(request,"manager","build","build.page.create",{type:"build.page",id},{name,title:"Property desk",object:type,sections:[{id:"table",widget:"table",configVersion:1,title:"Notes",fields:["note"]},{id:"detail",widget:"detail",configVersion:1,title:"Selected note",fields:["note"]},{id:"notice",widget:"text",configVersion:1,text:"Active record selected"},{id:"button",widget:"button",configVersion:1,title:"Use active record"}],document:doc});
 await open(page,"manager",`/compose?id=${id}`);const tree=page.getByRole("region",{name:"Widgets and layout",exact:true}),inspector=page.getByRole("region",{name:"The widget in hand",exact:true});await tree.getByRole("button",{name:"Page variables",exact:true}).click();
 for(const [variable,field] of [["active","active"],["count","count"]]){await inspector.getByRole("combobox",{name:"Choose page variable",exact:true}).selectOption(variable);await inspector.getByRole("combobox",{name:"Variable mode",exact:true}).selectOption("property");await inspector.getByRole("combobox",{name:"Source record variable",exact:true}).selectOption("selected");await inspector.getByRole("combobox",{name:"Record property field",exact:true}).selectOption(field);}
 await page.getByRole("button",{name:"Save",exact:true}).click();await expect(page.getByRole("button",{name:"Save",exact:true})).toBeDisabled();await page.getByRole("button",{name:"Review release",exact:true}).click();await page.getByRole("button",{name:"Check draft and dependencies",exact:true}).click();await page.getByRole("button",{name:"Save immutable candidate",exact:true}).click();await page.getByRole("button",{name:"Activate release",exact:true}).click();
 const operation=await page.context().newPage();await open(operation,"desk",`/page?app=build&kind=page&name=${name}`);const table=operation.getByRole("table"),button=operation.getByRole("button",{name:"Use active record",exact:true}),notice=operation.getByText("Active record selected",{exact:true});await expect(button).toBeDisabled();await table.getByRole("row").filter({hasText:"PROPERTY-A"}).click();await expect(notice).toBeVisible();await expect(button).toBeEnabled();await table.getByRole("row").filter({hasText:"PROPERTY-B"}).click();await expect(notice).toHaveCount(0);await expect(button).toBeDisabled();
 let release!:()=>void,held=false,released=false;const completed:Promise<void>[]=[];const wait=new Promise<void>(resolve=>release=resolve);await operation.route(`**/v1/records/${type}/${name}A`,async r=>{if(!released){let done!:()=>void;completed.push(new Promise<void>(resolve=>done=resolve));try{const response=await r.fetch();held=true;await wait;await r.fulfill({response});}finally{done();}}else await r.continue();});await table.getByRole("row").filter({hasText:"PROPERTY-A"}).click();await expect.poll(()=>held).toBe(true);await expect(button).toBeDisabled();await table.getByRole("row").filter({hasText:"PROPERTY-B"}).click();released=true;release();await Promise.all(completed);await expect(button).toBeDisabled();await expect(notice).toHaveCount(0);await operation.unroute(`**/v1/records/${type}/${name}A`);
 await operation.route(`**/v1/records/${type}/${name}A`,r=>r.fulfill({status:403,contentType:"application/json",body:JSON.stringify({error:{message:"Denied"}})}));await table.getByRole("row").filter({hasText:"PROPERTY-A"}).click();await expect(button).toBeDisabled();await expect(notice).toHaveCount(0);await operation.unroute(`**/v1/records/${type}/${name}A`);await table.getByRole("row").filter({hasText:"PROPERTY-A"}).click();await expect(notice).toBeVisible();
 if(process.env.PLATFORM_SCREENSHOTS){await operation.screenshot({path:info.outputPath("record-property.png"),fullPage:true});await operation.setViewportSize({width:390,height:844});await operation.evaluate(()=>new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve()))));await operation.screenshot({path:info.outputPath("record-property-narrow.png"),fullPage:true});}await operation.reload();await expect(button).toBeDisabled();await expect(notice).toHaveCount(0);
 const reader=await(await request.get(`/v1/records/${type}/${name}A`,{headers:{Authorization:"Bearer desk"}})).json();expect(reader.values.active).toBe(true);expect(reader.values.count).toEqual({kind:"decimal",value:"2"});expect(reader.values.secret).toBeUndefined();
 // A private property is removed together with the branch that consumes it.
 const saved=await(await request.get(`/v1/records/build.page/${id}`,{headers:{Authorization:"Bearer manager"}})).json();saved.record.document.variables.secret={scope:"page",type:"boolean",mode:"property",source:{kind:"property",variable:"selected",object:ref,field:"secret"}};saved.record.document.nodes.notice.visibleWhen="secret";await decide(request,"manager","build","build.page.edit",{type:"build.page",id},{document:saved.record.document});await decide(request,"manager","build","build.page.publish",{type:"build.page",id},{});const defs=await(await request.get("/v1/definitions",{headers:{Authorization:"Bearer desk"}})).json(),visible=defs.find((d:any)=>d.ref.kind==="page"&&d.ref.name===name);expect(visible.page.document.variables.secret).toBeUndefined();expect(visible.page.sections.some((s:any)=>s.id==="notice")).toBe(false);
});

test("application record properties follow shared selections across pages and retire with their instance",async({page,request})=>{
 test.setTimeout(60_000);
 const name=fresh("appproperty").replace(/[^a-z0-9]/gi,"").toLowerCase(),type=`build.${name}`,object=fresh("OBJ"),app=fresh("APP"),ref={app:"build",kind:"object",name:type};
 await decide(request,"manager","build","build.object.create",{type:"build.object",id:object},{name,title:"Application property notes",fields:[{name:"note",title:"Note",type:"text"},{name:"active",title:"Active",type:"boolean"}]});
 await decide(request,"manager","build","build.object.publish",{type:"build.object",id:object},{});
 for(const [suffix,active] of [["A",true],["B",false]])await decide(request,"desk","build",`${type}.create`,{type,id:`${name}${suffix}`},{note:`APP-PROPERTY-${suffix}`,active});
 const pages:{id:string;target:string}[]=[];
 for(const [suffix,target] of [["first","second"],["second","first"]]){
  const id=fresh("PAGE");pages.push({id,target});
  await decide(request,"manager","build","build.page.create",{type:"build.page",id},{name:`${name}${suffix}`,title:`Property ${suffix}`,object:type,sections:[{id:"table",widget:"table",configVersion:1,fields:["note"],selectionVariable:"selected"},{id:"notice",widget:"text",configVersion:1,text:"Shared active property"},{id:"next",widget:"button",configVersion:1,title:"Next property page"}],document:{formatVersion:2,uiProfile:pageUIProfile,root:"root",nodes:{root:{kind:"rows",children:["table","notice","next"]},table:{kind:"widget",section:"table"},notice:{kind:"widget",section:"notice",visibleWhen:"active"},next:{kind:"widget",section:"next"}},variables:{selected:{scope:"application",type:"record",mode:"shared",writable:true,source:{kind:"application",variable:"selected",object:ref}},active:{scope:"application",type:"boolean",mode:"shared",source:{kind:"application",variable:"active"}}},events:[{source:"next",event:"click",effects:[{kind:"navigate", navigate:{page:{app:"build",kind:"page",name:`${name}${suffix}`},interfaceVersion:0}}]}]}});
  await decide(request,"manager","build","build.page.publish",{type:"build.page",id},{});
 }
 for(const {id,target} of pages){const saved=await(await request.get(`/v1/records/build.page/${id}`,{headers:{Authorization:"Bearer manager"}})).json();saved.record.document.events[0].navigate.page.name=`${name}${target}`;await decide(request,"manager","build","build.page.edit",{type:"build.page",id},{document:saved.record.document});await decide(request,"manager","build","build.page.publish",{type:"build.page",id},{});}
 await decide(request,"manager","build","build.app.create",{type:"build.app",id:app},{name:`${name}app`,title:"Application properties",pages:[`${name}first`,`${name}second`],uiProfile:pageUIProfile,variables:{selected:{scope:"application",type:"record",mode:"resource",source:{kind:"record",object:ref}},active:{scope:"application",type:"boolean",mode:"property",source:{kind:"property",variable:"selected",object:ref,field:"active"}}}});
 await decide(request,"manager","build","build.app.publish",{type:"build.app",id:app},{});
 const route=`/page?app=build&kind=page&name=${name}first&application=build:${name}app&instance=main`;
 await open(page,"desk",route);const notice=page.getByText("Shared active property",{exact:true}),table=page.getByRole("table");
 await expect(notice).toHaveCount(0);await table.getByRole("row").filter({hasText:"APP-PROPERTY-A"}).click();await expect(notice).toBeVisible();
 await page.getByRole("button",{name:"Next property page",exact:true}).click();await expect(page.getByRole("heading",{name:"Property second",exact:true})).toBeVisible();await expect(notice.filter({visible:true})).toHaveCount(1);
 await table.getByRole("row").filter({hasText:"APP-PROPERTY-B"}).click();await expect(notice).toHaveCount(0);
 await table.getByRole("row").filter({hasText:"APP-PROPERTY-A"}).click();await expect(notice.filter({visible:true})).toHaveCount(1);
 await page.getByRole("button",{name:"Close application instance",exact:true}).click();await page.evaluate(route=>{location.hash=route},route);await expect(notice).toHaveCount(0);
});

test("loop item properties use each authorized record rather than the page selection",async({page,request})=>{
 const name=fresh("loopproperty").replace(/[^a-z0-9]/gi,"").toLowerCase(),type=`build.${name}`,object=fresh("OBJ"),id=fresh("PAGE"),ref={app:"build",kind:"object",name:type};
 await decide(request,"manager","build","build.object.create",{type:"build.object",id:object},{name,title:"Loop property notes",fields:[{name:"note",title:"Note",type:"text"},{name:"active",title:"Active",type:"boolean"}]});await decide(request,"manager","build","build.object.publish",{type:"build.object",id:object},{});
 for(const [suffix,active] of [["A",true],["B",false]])await decide(request,"desk","build",`${type}.create`,{type,id:`${name}${suffix}`},{note:`LOOP-PROPERTY-${suffix}`,active});
 await decide(request,"manager","build","build.page.create",{type:"build.page",id},{name,title:"Loop properties",object:type,sections:[{id:"detail",widget:"detail",configVersion:1,title:"Item note",fields:["note"],recordVariable:"item"},{id:"notice",widget:"text",configVersion:1,text:"Active item property"}],document:{formatVersion:2,uiProfile:pageUIProfile,root:"root",nodes:{root:{kind:"rows",children:["cards"]},cards:{kind:"loop",title:"Property cards",children:["detail","notice"],loop:{collection:"window",itemVariable:"item",limit:10}},detail:{kind:"widget",section:"detail"},notice:{kind:"widget",section:"notice",visibleWhen:"active"}},queries:{read:{object:ref,limit:10}},variables:{window:{scope:"page",type:"object-set",mode:"resource",source:{kind:"plan",query:"read"}},item:{scope:"loop-item",owner:"cards",type:"record",mode:"resource",source:{kind:"item",node:"cards"}},active:{scope:"loop-item",owner:"cards",type:"boolean",mode:"property",source:{kind:"property",variable:"item",object:ref,field:"active"}}}}});
 await decide(request,"manager","build","build.page.publish",{type:"build.page",id},{});await open(page,"desk",`/page?app=build&kind=page&name=${name}`);
 const cards=page.getByRole("list",{name:"Property cards",exact:true}),active=cards.getByRole("region",{name:`${name}A`,exact:true}),inactive=cards.getByRole("region",{name:`${name}B`,exact:true});
 await expect(active.getByText("Active item property",{exact:true})).toBeVisible();await expect(inactive.getByText("LOOP-PROPERTY-B",{exact:true})).toBeVisible();await expect(inactive.getByText("Active item property",{exact:true})).toHaveCount(0);
});
