import {expect,test,type Locator} from "@playwright/test";
import {readFileSync} from "node:fs";
import {decide,fresh,open,pageUIProfile,stableReadRevision} from "./host";

async function booleanState(control:Locator,checked:boolean){
 if(await control.getAttribute("role")==="switch")await expect(control).toHaveAttribute("aria-checked",String(checked));
 else await expect(control).toBeChecked({checked});
}
for(const sourceType of ["ToggleSwitch","Checkbox"] as const){
test(`source ${sourceType} freezes original booleans, shares query and visibility conditions, respects enabled state and retires closed overlay state`,async({page,request},info)=>{
 test.setTimeout(90_000);
 const role=sourceType==="Checkbox"?"checkbox":"switch";
 const name=fresh("flags").replace(/[^a-z0-9]/gi,"").toLowerCase(),type=`build.${name}`,object=fresh("OBJ"),id=fresh("PAGE");
 await decide(request,"manager","build","build.object.create",{type:"build.object",id:object},{name,title:"Flag assets",fields:[{name:"note",title:"Name",type:"text"},{name:"active",title:"Active",type:"boolean"},{name:"privateactive",title:"Private active",type:"boolean",read:["builder"]}]});
 await decide(request,"manager","build","build.object.publish",{type:"build.object",id:object},{});
 for(const active of [false,true])await decide(request,"manager","build",`${type}.create`,{type,id:`${name}${active}`},{note:`ASSET-${active}`,active,privateactive:active});
 const m=JSON.parse(readFileSync(new URL("../../packages/build/src/workshop/module-import/sample.workshop.json",import.meta.url),"utf8")),variable=(id:string,name:string)=>({id,name,type:"boolean",definitionKind:"static",staticValue:false}),control=(id:string,name:string,variableId:string,label?:string)=>({id,name,type:sourceType,config:{variableId,...label!==undefined?{label}:{}}}),set=(id:string,flag:string,field="active")=>({id,name:id,type:"objectSet",definitionKind:"objectSetDefinition",sourceObjectType:"Asset",objectSet:{objectType:"Asset",steps:[{op:"where",clauses:[{id:"active",property:field,op:"is",varId:flag}]}]}});
 m.variables.push(variable("flag","Active flag"),variable("enabled","Editing enabled"),variable("blank","Blank flag"),variable("localFlag","Local flag"),set("privateNotes","flag","privateactive"),set("localNotes","localFlag"),{id:"localSelected",name:"Local selection",type:"object",definitionKind:"widgetOutput",widgetId:"localTable",widgetOutputKey:"activeObject"});m.variables.find((v:any)=>v.id==="notes").objectSet=set("notes","flag").objectSet;
 m.widgets.gate=control("gate","Editing gate","enabled","Allow active selection");m.widgets.switch=control("switch","Active toggle","flag","Active assets");m.widgets.mirror=control("mirror","Mirror toggle","flag","Mirror active choice");m.widgets.mirror.type="ToggleSwitch";m.widgets.blank=control("blank","Quiet flag","blank","");m.widgets.localSwitch=control("localSwitch","Local toggle","localFlag","Local active assets");m.widgets.notice={id:"notice",name:"Visible notice",type:"HeaderText",config:{text:"Active condition is true",variant:"h3"}};
 m.widgets.privateTable={...m.widgets.table,id:"privateTable",name:"Hidden active table",config:{...m.widgets.table.config,objectSetVarId:"privateNotes",activeVarId:undefined}};m.widgets.localTable={...m.widgets.table,id:"localTable",name:"Local table",config:{...m.widgets.table.config,objectSetVarId:"localNotes",activeVarId:"localSelected"}};m.widgets.localDetail={...m.widgets.detail,id:"localDetail",name:"Local selection",config:{...m.widgets.detail.config,objectVarId:"localSelected"}};
 m.widgets.trigger={id:"trigger",name:"Open switches",type:"SingleButton",config:{label:"Open switches",eventActions:[{kind:"openOverlay",overlayId:"panel"}]}};m.widgets.close={id:"close",name:"Close switches",type:"SingleButton",config:{label:"Close switches",eventActions:[{kind:"closeOverlay",overlayId:"panel"}]}};
 m.sections={root:{id:"root",name:"Root",layout:"rows",children:["gate","switch","mirror","blank","table","detail","privateTable","trigger"].map(id=>({kind:"widget",id})).concat([{kind:"section",id:"reveal"}])},reveal:{id:"reveal",name:"Reveal",layout:"rows",visibleVariableId:"flag",children:[{kind:"widget",id:"notice"}]},panel:{id:"panel",name:"Panel",layout:"rows",children:["localSwitch","localTable","localDetail","close"].map(id=>({kind:"widget",id}))}};m.overlays=[{id:"panel",name:"Switch panel",kind:"drawer",rootSectionId:"panel"}];
 await decide(request,"manager","build","build.page.create",{type:"build.page",id},{name,title:"Imported switches",object:type,sections:[{id:"initial",widget:"text",configVersion:1,text:"Initial"}],document:{formatVersion:2,uiProfile:pageUIProfile,root:"root",nodes:{root:{kind:"rows",children:["initial"]},initial:{kind:"widget",section:"initial"}}}});
 await open(page,"manager",`/compose?id=${id}`);await page.getByRole("button",{name:"Import Workshop module",exact:true}).click();const dialog=page.getByRole("dialog",{name:"Import Workshop module",exact:true});await dialog.getByRole("textbox",{name:"Source module JSON",exact:true}).fill(JSON.stringify(m));await dialog.getByRole("combobox",{name:"Map object Asset",exact:true}).selectOption(type);for(const [source,target] of [["name","note"],["active","active"],["privateactive","privateactive"]])await dialog.getByRole("combobox",{name:`Map field Asset.${source}`,exact:true}).selectOption(target);await dialog.getByRole("checkbox").check();await dialog.getByRole("button",{name:"Apply imported page draft",exact:true}).click();
 const tree=page.getByRole("region",{name:"Widgets and layout",exact:true}),inspector=page.getByRole("region",{name:"The widget in hand",exact:true});for(const title of ["Active toggle","Mirror toggle"]){await tree.getByRole("button",{name:title,exact:true}).click();if(title==="Active toggle"&&sourceType==="Checkbox"){const presentation=inspector.getByRole("combobox",{name:"Boolean presentation",exact:true});await expect(presentation).toHaveValue("checkbox");await presentation.selectOption("switch");await expect(page.getByRole("switch",{name:"Active assets",exact:true})).toBeVisible();await presentation.selectOption("checkbox");}await inspector.getByRole("combobox",{name:"Enabled when",exact:true}).selectOption({label:"Editing enabled"});}const state=inspector.getByRole("combobox",{name:"Boolean state variable",exact:true}),value=await state.inputValue();await state.selectOption("");await expect(page.getByRole("button",{name:"Save",exact:true})).toBeDisabled();await state.selectOption(value);await expect(state.getByRole("option",{name:"Local flag",exact:true})).toHaveCount(0);await page.getByRole("button",{name:"Save",exact:true}).click();let saved:any;await expect.poll(async()=>{saved=(await(await request.get(`/v1/records/build.page/${id}`,{headers:{Authorization:"Bearer manager"}})).json()).record;return saved.sections?.filter((s:any)=>s.widget==="boolean-input").length;}).toBe(5);
 const main=saved.sections.find((s:any)=>s.title==="Active toggle"),mirror=saved.sections.find((s:any)=>s.title==="Mirror toggle"),blank=saved.sections.find((s:any)=>s.title==="Quiet flag");expect(main.booleanVariable).toBe(mirror.booleanVariable);expect(blank.booleanLabel).toBe("");if(sourceType==="ToggleSwitch"){saved.document.uiProfile="platform.page.v2.53";await decide(request,"manager","build","build.page.edit",{type:"build.page",id},{sections:saved.sections,document:saved.document});await page.reload();}else expect(main.booleanVariant).toBe("checkbox");await page.getByRole("button",{name:"Review release",exact:true}).click();await page.getByRole("button",{name:"Check draft and dependencies",exact:true}).click();await page.getByRole("button",{name:"Save immutable candidate",exact:true}).click();main.booleanLabel="Later label";if(sourceType==="Checkbox")main.booleanVariant="switch";saved.document.variables[main.booleanVariable].initial=true;await decide(request,"manager","build","build.page.edit",{type:"build.page",id},{sections:saved.sections,document:saved.document});await page.getByRole("button",{name:"Activate release",exact:true}).click();
 const runtime=await page.context().newPage();await stableReadRevision(runtime);await open(runtime,"desk",`/page?app=build&kind=page&name=${name}`);const section=(title:string)=>runtime.getByRole("heading",{name:title,exact:true}).locator(".."),table=section("Imported notes"),detail=section("Imported selection"),gate=runtime.getByRole(role,{name:"Allow active selection",exact:true}),flag=runtime.getByRole(role,{name:"Active assets",exact:true}),other=runtime.getByRole("switch",{name:"Mirror active choice",exact:true});
 await booleanState(flag,false);await expect(flag).toBeDisabled();await expect(other).toBeDisabled();await expect(table.getByText("ASSET-false",{exact:true})).toBeVisible();await expect(table.getByText("ASSET-true",{exact:true})).toHaveCount(0);await expect(runtime.getByText("Active condition is true",{exact:true})).toHaveCount(0);await expect(runtime.getByRole("heading",{name:"Hidden active table",exact:true})).toHaveCount(0);await expect(runtime.getByRole(role,{name:"Quiet flag",exact:true})).toHaveText("");await flag.dispatchEvent("click");await booleanState(flag,false);
 await table.getByRole("row").filter({hasText:"ASSET-false"}).click();await expect(detail.getByRole("definition").filter({hasText:/^ASSET-false$/})).toBeVisible();await gate.focus();await gate.press("Space");await expect(flag).toBeEnabled();await flag.focus();await flag.press(sourceType==="Checkbox"?"Space":"Enter");await booleanState(flag,true);await booleanState(other,true);await expect(table.getByText("ASSET-true",{exact:true})).toBeVisible();await expect(table.getByText("ASSET-false",{exact:true})).toHaveCount(0);await expect(detail.getByText("Select a record to see it here.",{exact:true})).toBeVisible();await expect(runtime.getByText("Active condition is true",{exact:true})).toBeVisible();
 if(process.env.PLATFORM_SCREENSHOTS){await section("Active toggle").screenshot({path:info.outputPath(sourceType==="Checkbox"?"checkbox.png":"switch.png")});await runtime.setViewportSize({width:390,height:844});await runtime.evaluate(()=>new Promise<void>(r=>requestAnimationFrame(()=>requestAnimationFrame(()=>r()))));await section("Active toggle").screenshot({path:info.outputPath(sourceType==="Checkbox"?"checkbox-narrow.png":"switch-narrow.png")});await runtime.setViewportSize({width:1280,height:720});}
 await other.click();await booleanState(flag,false);await expect(table.getByText("ASSET-false",{exact:true})).toBeVisible();await expect(runtime.getByText("Active condition is true",{exact:true})).toHaveCount(0);if(sourceType==="Checkbox"){await runtime.getByText("Active assets",{exact:true}).click();await booleanState(flag,true);await booleanState(other,true);await flag.focus();await flag.press("Space");await booleanState(flag,false);}
 await gate.click();await expect(flag).toBeDisabled();await flag.dispatchEvent("click");await booleanState(flag,false);await gate.click();
 await runtime.route(`**/v1/records/${type}*`,route=>route.fulfill({status:403,contentType:"application/json",body:JSON.stringify({error:{message:"Denied"}})}));await flag.click();await expect(table.getByRole("alert")).toBeVisible();await expect(table.getByText("ASSET-false",{exact:true})).toHaveCount(0);await runtime.unroute(`**/v1/records/${type}*`);await flag.click();await expect(table.getByText("ASSET-false",{exact:true})).toBeVisible();
 await runtime.getByRole("button",{name:"Open switches",exact:true}).click();const panel=runtime.getByRole("dialog",{name:"Switch panel",exact:true}),local=panel.getByRole(role,{name:"Local active assets",exact:true});await booleanState(local,false);await expect(panel.getByRole("cell",{name:"ASSET-false",exact:true})).toBeVisible();await local.click();await expect(panel.getByRole("cell",{name:"ASSET-true",exact:true})).toBeVisible();await panel.getByRole("row").filter({hasText:"ASSET-true"}).click();await expect(panel.getByRole("definition").filter({hasText:/^ASSET-true$/})).toBeVisible();await panel.getByRole("button",{name:"Close switches",exact:true}).click();await booleanState(flag,false);await runtime.getByRole("button",{name:"Open switches",exact:true}).click();await booleanState(local,false);await expect(panel.getByRole("cell",{name:"ASSET-false",exact:true})).toBeVisible();await expect(panel.getByText("Select a record to see it here.",{exact:true})).toBeVisible();await panel.getByRole("button",{name:"Close switches",exact:true}).click();await runtime.reload();await booleanState(flag,false);await expect(flag).toBeDisabled();await expect(table.getByText("ASSET-false",{exact:true})).toBeVisible();const unchanged=(await(await request.get(`/v1/records/${type}/${name}false`,{headers:{Authorization:"Bearer manager"}})).json()).record;expect(unchanged.active).toBe(false);
});
}
