import {expect,test} from "@playwright/test";
import {readFileSync} from "node:fs";
import {decide,fresh,open,pageUIProfile,stableReadRevision} from "./host";

test("UserSelect imports business personnel IDs, confirms authority, filters references and freezes mapping",async({page,request},info)=>{
 test.setTimeout(90_000);const name=fresh("people").replace(/[^a-z0-9]/gi,"").toLowerCase(),person=`build.${name}person`,asset=`build.${name}asset`,id=fresh("PAGE");
 const make=async(suffix:string,fields:any[])=>{const object=fresh("OBJ");await decide(request,"manager","build","build.object.create",{type:"build.object",id:object},{name:`${name}${suffix}`,title:suffix==="person"?"Personnel":"Assigned assets",fields});await decide(request,"manager","build","build.object.publish",{type:"build.object",id:object},{});};
 await make("person",[{name:"name",title:"Name",type:"text"},{name:"secret",title:"Private title",type:"text",read:["builder"]}]);await make("asset",[{name:"title",title:"Title",type:"text"},{name:"owner",title:"Responsible person",type:"reference",ref:person}]);for(let i=0;i<25;i++)await decide(request,"manager","build",`${person}.create`,{type:person,id:`${name}${String(i).padStart(3,"0")}`},{name:i<2?"Same name":`Person ${i}`,secret:"Private"});for(let i=0;i<2;i++)await decide(request,"manager","build",`${asset}.create`,{type:asset,id:`${name}asset${i}`},{title:`Asset ${i}`,owner:`${name}00${i}`});
 const m=JSON.parse(readFileSync(new URL("../../packages/build/src/module-import/sample.workshop.json",import.meta.url),"utf8"));m.variables=[{id:"owner",name:"Personnel ID",type:"string",definitionKind:"static",staticValue:""},{id:"notes",name:"Assigned assets",type:"objectSet",definitionKind:"objectSetDefinition",sourceObjectType:"Asset",objectSet:{objectType:"Asset",steps:[{op:"where",clauses:[{property:"owner",op:"contains",varId:"owner"}]}]}}];m.widgets={people:{id:"people",name:"People",type:"UserSelect",config:{variableId:"owner",label:"Responsible person"}},input:{id:"input",name:"ID draft",type:"TextInput",config:{variableId:"owner",label:"Personnel ID draft"}},table:{id:"table",name:"Assignments",type:"ObjectTable",config:{objectSetVarId:"notes",columns:[{key:"title",label:"Title"}]}}};m.sections={root:{id:"root",name:"Root",layout:"rows",children:["people","input","table"].map(id=>({kind:"widget",id}))}};m.overlays=[];
 await decide(request,"manager","build","build.page.create",{type:"build.page",id},{name,title:"Personnel assignment",object:asset,sections:[{id:"initial",widget:"text",configVersion:1,text:"Initial"}],document:{formatVersion:2,uiProfile:pageUIProfile,root:"root",nodes:{root:{kind:"rows",children:["initial"]},initial:{kind:"widget",section:"initial"}}}});
 await open(page,"manager",`/compose?id=${id}`);await page.getByRole("button",{name:"Import Workshop module",exact:true}).click();const dialog=page.getByRole("dialog",{name:"Import Workshop module",exact:true});await dialog.getByRole("textbox",{name:"Source module JSON",exact:true}).fill(JSON.stringify(m));await dialog.getByRole("combobox",{name:"Map object Asset",exact:true}).selectOption(asset);await dialog.getByRole("combobox",{name:"Map field Asset.owner",exact:true}).selectOption("owner");await dialog.getByRole("combobox",{name:"Map field Asset.title",exact:true}).selectOption("title");const mapping=dialog.getByRole("group",{name:"Map people picker People",exact:true});await mapping.getByRole("combobox",{name:"Business personnel object",exact:true}).selectOption(person);await mapping.getByRole("combobox",{name:"Picker title field",exact:true}).selectOption("name");await dialog.getByRole("checkbox").check();await dialog.getByRole("button",{name:"Apply imported page draft",exact:true}).click();await page.getByRole("region",{name:"Widgets and layout",exact:true}).getByRole("button",{name:"People",exact:true}).click();const output=page.getByRole("region",{name:"The widget in hand",exact:true}).getByRole("combobox",{name:"Confirmed ID output",exact:true});await output.selectOption("");await output.selectOption({label:"Personnel ID"});await page.getByRole("button",{name:"Save",exact:true}).click();let saved:any;await expect.poll(async()=>{saved=(await(await request.get(`/v1/records/build.page/${id}`,{headers:{Authorization:"Bearer manager"}})).json()).record;return saved.sections?.some((s:any)=>s.pickerValueVariable);}).toBe(true);await page.getByRole("button",{name:"Review release",exact:true}).click();await page.getByRole("button",{name:"Check draft and dependencies",exact:true}).click();await page.getByRole("button",{name:"Save immutable candidate",exact:true}).click();saved.sections.find((s:any)=>s.widget==="record-picker").recordPicker.label="Later draft";await decide(request,"manager","build","build.page.edit",{type:"build.page",id},{sections:saved.sections,document:saved.document});await page.getByRole("button",{name:"Activate release",exact:true}).click();
 const runtime=await page.context().newPage();await stableReadRevision(runtime);await open(runtime,"desk",`/page?app=build&kind=page&name=${name}`);const lookup=runtime.getByRole("combobox",{name:"Responsible person",exact:true}),input=runtime.getByRole("textbox",{name:"Personnel ID draft",exact:true}),people=runtime.getByRole("heading",{name:"People",exact:true}).locator(".."),table=runtime.getByRole("heading",{name:"Assignments",exact:true}).locator("..");await expect(table.getByRole("cell",{name:"Asset 0",exact:true})).toBeVisible();await expect(table.getByRole("cell",{name:"Asset 1",exact:true})).toBeVisible();await lookup.focus();await expect(people.getByRole("option")).toHaveCount(20);await expect(people.getByRole("option").nth(0)).toContainText(`${name}000 · Same name`);await expect(people.getByRole("option").nth(1)).toContainText(`${name}001 · Same name`);await people.getByRole("option").nth(1).click();await expect(input).toHaveValue(`${name}001`);await expect(table.getByRole("cell",{name:"Asset 1",exact:true})).toBeVisible();await expect(table.getByRole("cell",{name:"Asset 0",exact:true})).toHaveCount(0);
 if(process.env.PLATFORM_SCREENSHOTS){await people.screenshot({path:info.outputPath("user-select.png")});await runtime.setViewportSize({width:390,height:844});await people.screenshot({path:info.outputPath("user-select-narrow.png")});await runtime.setViewportSize({width:1280,height:720});}
 await lookup.focus();await people.getByRole("button",{name:"Clear selection",exact:true}).click();await expect(input).toHaveValue("");await expect(table.getByRole("cell",{name:"Asset 0",exact:true})).toBeVisible();await input.fill("Unmatched legacy name");await expect(lookup).toHaveValue("Unmatched legacy name");await expect(people.getByRole("status")).toContainText("outside the current candidate window");await lookup.focus();await lookup.fill("Person 24");await expect(people.getByRole("option")).toHaveCount(1);await lookup.press("Enter");await expect(input).toHaveValue(`${name}024`);
 await runtime.route(`**/v1/records/${person}/${name}000`,route=>route.fulfill({status:403,contentType:"application/json",body:JSON.stringify({error:{message:"Denied"}})}));await lookup.focus();await lookup.fill("Same name");await expect(people.getByRole("option")).toHaveCount(2);const denied=runtime.waitForResponse(r=>r.url().endsWith(`/${person}/${name}000`)&&r.status()===403);await people.getByRole("option").first().click();await denied;await expect(people.getByRole("alert")).toContainText("could not be confirmed");await expect(input).toHaveValue(`${name}024`);await runtime.unroute(`**/v1/records/${person}/${name}000`);
 let release:()=>void=()=>{};const gate=new Promise<void>(r=>release=r);let started=false;await runtime.route(`**/v1/records/${person}/${name}001`,async route=>{started=true;await gate;await route.continue();});await lookup.focus();await people.getByRole("option").nth(1).click();await expect.poll(()=>started).toBe(true);await input.fill("newer draft");const completion=runtime.waitForResponse(r=>r.url().endsWith(`/${person}/${name}001`));release();await completion;await runtime.evaluate(()=>new Promise<void>(r=>requestAnimationFrame(()=>requestAnimationFrame(()=>r()))));await expect(input).toHaveValue("newer draft");await runtime.unroute(`**/v1/records/${person}/${name}001`);await runtime.route(`**/v1/records/${person}?*`,route=>route.fulfill({status:403,contentType:"application/json",body:JSON.stringify({error:{message:"Denied"}})}));await lookup.focus();await lookup.fill("Person 23");await expect(people.getByRole("alert")).toBeVisible();await expect(people.getByRole("option")).toHaveCount(0);await expect(input).toHaveValue("newer draft");await runtime.unroute(`**/v1/records/${person}?*`);await runtime.reload();await expect(input).toHaveValue("");
});
