import {expect,test} from "@playwright/test";
import {decide,fresh,open,pageUIProfile} from "./host";

test("a frozen inline form uses original inputs, revision refusals and approval and retires its scopes",async({browser,page,request},testInfo)=>{
 test.setTimeout(120_000);
 const name=fresh("inline").replace(/[^a-z0-9]/gi,"").toLowerCase(),type=`build.${name}`,object=fresh("OBJ"),id=fresh("PAGE"),route=`/page?app=build&kind=page&name=${name}`;
 await decide(request,"manager","build","build.object.create",{type:"build.object",id:object},{name,title:"Inline requests",fields:[{name:"note",title:"Note",type:"text"}],access:[{role:"user",read:"all",create:true,edit:true},{role:"supervisor",read:"all"}],states:[{name:"open",title:"Open"},{name:"pending",title:"Pending"},{name:"approved",title:"Approved"}],actions:[{name:"submit",title:"Send request",from:["open"],to:"approved",roles:["user","builder"],inputs:[{name:"reason",title:"Reason",type:"text",required:true}],conditions:[{field:"input.reason",operator:"=",value:"approved",message:"Reason must be approved"}],approval:{pending:"pending",levels:[{title:"Business supervisor",role:"supervisor"}]}}]});
 await decide(request,"manager","build","build.object.publish",{type:"build.object",id:object},{});
 await decide(request,"manager","platform","platform.member.grant",{type:"platform.member",id:"business-supervisor-1"},{app:"build",role:"supervisor"});
 for(const suffix of ["A","B","C"])await decide(request,"desk","build",`${type}.create`,{type,id:`${name}${suffix}`},{note:`REQUEST-${suffix}`});
 await decide(request,"manager","build","build.page.create",{type:"build.page",id},{name,title:"Inline desk",object:type,sections:[{id:"table",widget:"table",configVersion:1,title:"Requests",fields:["note","state"]},{id:"trigger",widget:"button",configVersion:1,title:"Open request panel"},{id:"localTable",widget:"table",configVersion:1,title:"Panel requests",fields:["note","state"]},{id:"localInline",widget:"inline-action",configVersion:1,title:"Panel action",actions:[`${type}.submit`]},{id:"close",widget:"button",configVersion:1,title:"Close request panel"}],document:{formatVersion:2,uiProfile:pageUIProfile,root:"root",nodes:{root:{kind:"rows",children:["table","trigger"]},table:{kind:"widget",section:"table"},trigger:{kind:"widget",section:"trigger"},panel:{kind:"rows",children:["localTable","localInline","close"]},localTable:{kind:"widget",section:"localTable"},localInline:{kind:"widget",section:"localInline"},close:{kind:"widget",section:"close"}},overlays:{panel:{root:"panel",kind:"drawer",title:"Request panel",openVariable:"open"}},variables:{open:{scope:"page",type:"boolean",mode:"state",initial:false}},events:[{source:"trigger",event:"click",target:"open",value:true},{source:"close",event:"click",target:"open",value:false}]}});
 await open(page,"manager",`/compose?id=${id}`);
 const tree=page.getByRole("region",{name:"Widgets and layout",exact:true}),inspector=page.getByRole("region",{name:"The widget in hand",exact:true});
 await tree.getByRole("button",{name:"Inline action",exact:true}).click();await inspector.getByLabel("Title",{exact:true}).fill("Request in place");await expect(page.getByRole("button",{name:"Save",exact:true})).toBeDisabled();await inspector.getByRole("combobox",{name:"Inline record action",exact:true}).selectOption(`${type}.submit`);
 const preview=page.getByRole("heading",{name:"Request in place",exact:true}).locator("..");await preview.getByRole("textbox",{name:"Reason *",exact:true}).fill("approved");await expect(preview.getByRole("button",{name:"Send request",exact:true})).toBeDisabled();
 if(process.env.PLATFORM_SCREENSHOTS)await inspector.screenshot({path:testInfo.outputPath("inline-inspector.png")});
 await page.getByRole("button",{name:"Save",exact:true}).click();let saved:any;await expect.poll(async()=>{saved=(await(await request.get(`/v1/records/build.page/${id}`,{headers:{Authorization:"Bearer manager"}})).json()).record;return saved.sections.find((s:any)=>s.title==="Request in place")?.actions;}).toEqual([`${type}.submit`]);
 await page.getByRole("button",{name:"Review release",exact:true}).click();await page.getByRole("button",{name:"Check draft and dependencies",exact:true}).click();await page.getByRole("button",{name:"Save immutable candidate",exact:true}).click();saved.sections.find((s:any)=>s.title==="Request in place").actions=[`${type}.edit`];await decide(request,"manager","build","build.page.edit",{type:"build.page",id},{sections:saved.sections});await page.getByRole("button",{name:"Activate release",exact:true}).click();
 const operation=await page.context().newPage();await open(operation,"desk",route);
 const table=operation.getByRole("heading",{name:"Requests",exact:true}).locator(".."),form=operation.getByRole("heading",{name:"Request in place",exact:true}).locator(".."),reason=form.getByRole("textbox",{name:"Reason *",exact:true});
 await expect(form).toContainText("Select a record to act on it.");await table.getByRole("row").filter({hasText:"REQUEST-A"}).click();await expect(form.getByRole("button",{name:"Send request",exact:true})).toBeDisabled();if(process.env.PLATFORM_SCREENSHOTS){await reason.fill("approved");await form.screenshot({path:testInfo.outputPath("inline-runtime.png")});await operation.setViewportSize({width:390,height:844});await form.screenshot({path:testInfo.outputPath("inline-runtime-narrow.png")});await operation.setViewportSize({width:1280,height:720});}await reason.fill("refused");await form.getByRole("button",{name:"Send request",exact:true}).click();await expect(form.getByRole("alert")).toContainText("Reason must be approved");await expect(reason).toHaveValue("refused");
 await decide(request,"manager","build",`${type}.edit`,{type,id:`${name}A`},{note:"REQUEST-A refreshed"});await expect(table.getByRole("row").filter({hasText:"REQUEST-A refreshed"})).toBeVisible();await reason.fill("approved");await form.getByRole("button",{name:"Send request",exact:true}).click();await expect(form.getByRole("alert")).toContainText(/CONFLICT|revision|changed/i);await expect(reason).toHaveValue("approved");
 await form.getByRole("button",{name:"Cancel",exact:true}).click();await expect(reason).toHaveValue("");await reason.fill("approved");await form.getByRole("button",{name:"Send request",exact:true}).click();await expect(form).toContainText("Request submitted. Check the record or My requests for its result.");await expect.poll(async()=>(await(await request.get(`/v1/records/${type}/${name}A`,{headers:{Authorization:"Bearer desk"}})).json()).record.state).toBe("pending");
 const supervisor=await browser.newContext({baseURL:"http://127.0.0.1:18496",locale:"en-US"});try{const inbox=await supervisor.newPage();await open(inbox,"business-supervisor","/inbox");await inbox.getByRole("listitem").filter({hasText:`${name}A`}).getByRole("button",{name:"Approve",exact:true}).click();await expect.poll(async()=>(await(await request.get(`/v1/records/${type}/${name}A`,{headers:{Authorization:"Bearer desk"}})).json()).record.state).toBe("approved");}finally{await supervisor.close();}
 await table.getByRole("row").filter({hasText:"REQUEST-B"}).click();await reason.fill("B draft");await table.getByRole("row").filter({hasText:"REQUEST-C"}).click();await expect(reason).toHaveValue("");await table.getByRole("row").filter({hasText:"REQUEST-B"}).click();await expect(reason).toHaveValue("");await reason.fill("Root draft");
 await operation.getByRole("button",{name:"Open request panel",exact:true}).click();const panel=operation.getByRole("dialog",{name:"Request panel",exact:true});await panel.getByRole("row").filter({hasText:"REQUEST-C"}).click();await panel.getByRole("textbox",{name:"Reason *",exact:true}).fill("Panel draft");await panel.getByRole("button",{name:"Close request panel",exact:true}).click();await operation.getByRole("button",{name:"Open request panel",exact:true}).click();await panel.getByRole("row").filter({hasText:"REQUEST-C"}).click();await expect(panel.getByRole("textbox",{name:"Reason *",exact:true})).toHaveValue("");await panel.getByRole("button",{name:"Close request panel",exact:true}).click();await expect(reason).toHaveValue("Root draft");
 saved.sections.find((s:any)=>s.title==="Request in place").actions=[`${type}.submit`];saved.sections.find((s:any)=>s.title==="Request in place").title="Updated inline form";await decide(request,"manager","build","build.page.edit",{type:"build.page",id},{sections:saved.sections});await decide(request,"manager","build","build.page.publish",{type:"build.page",id},{});
 const updated=operation.getByRole("heading",{name:"Updated inline form",exact:true}).locator("..");await expect(updated).toContainText("Select a record to act on it.");await table.getByRole("row").filter({hasText:"REQUEST-B"}).click();await expect(updated.getByRole("textbox",{name:"Reason *",exact:true})).toHaveValue("");await updated.getByRole("textbox",{name:"Reason *",exact:true}).fill("Retired definition draft");
 await operation.getByRole("button",{name:/desk-1 hotel-a/}).click();await operation.getByRole("menuitemradio",{name:/business-supervisor-1/}).click();await expect(operation.getByRole("textbox",{name:"Reason *",exact:true})).toHaveCount(0);await operation.getByRole("button",{name:/business-supervisor-1 hotel-a/}).click();await operation.getByRole("menuitemradio",{name:/desk-1/}).click();await table.getByRole("row").filter({hasText:"REQUEST-B"}).click();await expect(updated.getByRole("textbox",{name:"Reason *",exact:true})).toHaveValue("");await updated.getByRole("textbox",{name:"Reason *",exact:true}).fill("Reload draft");await operation.reload();await table.getByRole("row").filter({hasText:"REQUEST-B"}).click();await expect(updated.getByRole("textbox",{name:"Reason *",exact:true})).toHaveValue("");
});
