import {expect,test} from "@playwright/test";
import {readFileSync} from "node:fs";
import {decide,fresh,open,pageUIProfile,stableReadRevision} from "./host";

test("source summary freezes original five-measure answers and field permissions while complete sets, aliases and closed scopes retain correct statistics",async({page,request},info)=>{
 test.setTimeout(90_000);
 const name=fresh("summary").replace(/[^a-z0-9]/gi,"").toLowerCase(),type=`build.${name}`,object=fresh("OBJ"),id=fresh("PAGE");
 await decide(request,"manager","build","build.object.create",{type:"build.object",id:object},{name,title:"Summary assets",fields:[{name:"note",title:"Name",type:"text"},{name:"qty",title:"Pressure",type:"decimal"},{name:"otherqty",title:"Other pressure",type:"decimal"},{name:"bucket",title:"Bucket",type:"text"},{name:"privateqty",title:"Private pressure",type:"decimal",read:["builder"]}]});await decide(request,"manager","build","build.object.publish",{type:"build.object",id:object},{});for(const [suffix,qty] of [["A1",20],["A2",40],["A3",80],["B1",100],["B2",50],["C1",90]])await decide(request,"manager","build",`${type}.create`,{type,id:`${name}${suffix}`},{note:`STATS-${suffix}`,qty,otherqty:Number(qty)*2,bucket:String(suffix)[0],privateqty:99});
 const m=JSON.parse(readFileSync(new URL("../../packages/build/src/module-import/sample.workshop.json",import.meta.url),"utf8")),summary=(id:string,title:string,property="pressure",set="notes")=>({id,name:title,type:"SummaryStats",config:{objectSetVarId:set,property}});
 m.widgets={table:m.widgets.table,input:{id:"input",name:"Summary filter",type:"TextInput",config:{variableId:"scratch",label:"Summary filter"}},summary:summary("summary","Pressure statistics"),alias:summary("alias","Same pressure"),other:summary("other","Other statistics","otherpressure"),hidden:summary("hidden","Private statistics","privatepressure"),local:summary("local","Local statistics","pressure","localNotes"),localInput:{id:"localInput",name:"Local filter",type:"TextInput",config:{variableId:"localScratch",label:"Local filter"}},trigger:{id:"trigger",name:"Open statistics",type:"SingleButton",config:{label:"Open statistics",eventActions:[{kind:"openOverlay",overlayId:"panel"}]}},close:{id:"close",name:"Close statistics",type:"SingleButton",config:{label:"Close statistics",eventActions:[{kind:"closeOverlay",overlayId:"panel"}]}}};delete m.widgets.table.config.activeVarId;
 m.variables=m.variables.filter((v:any)=>v.id!=="selected");m.variables.find((v:any)=>v.id==="scratch").staticValue="";m.variables.find((v:any)=>v.id==="notes").objectSet.steps=[{op:"where",clauses:[{id:"bucket",property:"bucket",op:"contains",varId:"scratch"}]}];m.variables.push({id:"localScratch",name:"Local bucket",type:"string",definitionKind:"static",staticValue:""},{id:"localNotes",name:"Local assets",type:"objectSet",definitionKind:"objectSetDefinition",sourceObjectType:"Asset",objectSet:{objectType:"Asset",steps:[{op:"where",clauses:[{id:"bucket",property:"bucket",op:"contains",varId:"localScratch"}]}]}});m.sections={root:{id:"root",name:"Root",layout:"rows",children:["input","summary","alias","other","table","hidden","trigger"].map(id=>({kind:"widget",id}))},panel:{id:"panel",name:"Panel",layout:"rows",children:["localInput","local","close"].map(id=>({kind:"widget",id}))}};m.overlays=[{id:"panel",name:"Statistics panel",kind:"drawer",rootSectionId:"panel"}];
 await decide(request,"manager","build","build.page.create",{type:"build.page",id},{name,title:"Imported statistics",object:type,sections:[{id:"initial",widget:"text",configVersion:1,text:"Initial"}],document:{formatVersion:2,uiProfile:pageUIProfile,root:"root",nodes:{root:{kind:"rows",children:["initial"]},initial:{kind:"widget",section:"initial"}}}});
 await open(page,"manager",`/compose?id=${id}`);await page.getByRole("button",{name:"Import Workshop module",exact:true}).click();const dialog=page.getByRole("dialog",{name:"Import Workshop module",exact:true});await dialog.getByRole("textbox",{name:"Source module JSON",exact:true}).fill(JSON.stringify(m));await dialog.getByRole("combobox",{name:"Map object Asset",exact:true}).selectOption(type);for(const [source,target] of [["name","note"],["bucket","bucket"],["pressure","qty"],["otherpressure","otherqty"],["privatepressure","privateqty"]])await dialog.getByRole("combobox",{name:`Map field Asset.${source}`,exact:true}).selectOption(target);await dialog.getByRole("checkbox").check();await dialog.getByRole("button",{name:"Apply imported page draft",exact:true}).click();
 const tree=page.getByRole("region",{name:"Widgets and layout",exact:true}),inspector=page.getByRole("region",{name:"The widget in hand",exact:true});await tree.getByRole("button",{name:"Pressure statistics",exact:true}).click();await expect(inspector.getByRole("combobox",{name:"Summary numeric field",exact:true})).toHaveValue("qty");const stats=await inspector.getByRole("combobox",{name:"Statistics variable",exact:true}).inputValue();await inspector.getByRole("combobox",{name:"Statistics variable",exact:true}).selectOption("");await expect(page.getByRole("button",{name:"Save",exact:true})).toBeDisabled();await inspector.getByRole("combobox",{name:"Statistics variable",exact:true}).selectOption(stats);await tree.getByRole("button",{name:"Page variables",exact:true}).click();await inspector.getByRole("combobox",{name:"Choose page variable",exact:true}).selectOption(stats);await expect(inspector.getByRole("combobox",{name:"Aggregate measure",exact:true})).toHaveValue("statistics:qty");await page.getByRole("button",{name:"Save",exact:true}).click();let saved:any;await expect.poll(async()=>{saved=(await(await request.get(`/v1/records/build.page/${id}`,{headers:{Authorization:"Bearer manager"}})).json()).record;return saved.sections?.filter((s:any)=>s.widget==="summary-stats").length;}).toBe(5);for(const q of Object.values(saved.document.queries) as any[])q.limit=1;await decide(request,"manager","build","build.page.edit",{type:"build.page",id},{document:saved.document});await page.reload();
 await page.getByRole("button",{name:"Review release",exact:true}).click();await page.getByRole("button",{name:"Check draft and dependencies",exact:true}).click();await page.getByRole("button",{name:"Save immutable candidate",exact:true}).click();saved.sections.find((s:any)=>s.title==="Pressure statistics").summaryField="otherqty";saved.document.variables[stats].source.measure="otherqty";await decide(request,"manager","build","build.page.edit",{type:"build.page",id},{sections:saved.sections,document:saved.document});await page.getByRole("button",{name:"Activate release",exact:true}).click();
 const runtime=await page.context().newPage();await stableReadRevision(runtime);const requests:string[]=[];runtime.on("request",r=>{const url=new URL(r.url());if(url.pathname===`/v1/aggregates/${type}`){requests.push(url.searchParams.get("measure")??"");expect(url.searchParams.has("limit")).toBe(false);expect(url.searchParams.has("offset")).toBe(false);}});await open(runtime,"desk",`/page?app=build&kind=page&name=${name}`);const section=(title:string)=>runtime.getByRole("heading",{name:title,exact:true}).locator(".."),root=section("Pressure statistics"),alias=section("Same pressure"),other=section("Other statistics"),input=runtime.getByRole("textbox",{name:"Summary filter",exact:true});const values=(scope:any)=>scope.getByRole("definition");await expect(values(root)).toHaveText(["6","20","63.3","100","380"]);await expect(values(alias)).toHaveText(["6","20","63.3","100","380"]);await expect(values(other)).toHaveText(["6","40","126.7","200","760"]);await expect(runtime.getByRole("heading",{name:"Private statistics",exact:true})).toHaveCount(0);expect(requests.filter(measures=>measures==="count,min:qty,avg:qty,max:qty,sum:qty")).toHaveLength(1);await expect(runtime.getByText("1–1 of 6",{exact:true})).toBeVisible();const before=requests.length;await runtime.getByRole("button",{name:"Next page",exact:true}).click();await expect(runtime.getByText("2–2 of 6",{exact:true})).toBeVisible();await expect(values(root)).toHaveText(["6","20","63.3","100","380"]);expect(requests.length).toBe(before);
 if(process.env.PLATFORM_SCREENSHOTS){await root.screenshot({path:info.outputPath("summary.png")});await runtime.setViewportSize({width:390,height:844});await runtime.evaluate(()=>new Promise<void>(r=>requestAnimationFrame(()=>requestAnimationFrame(()=>r()))));await root.screenshot({path:info.outputPath("summary-narrow.png")});await runtime.setViewportSize({width:1280,height:720});}
 await input.fill("A");await expect(values(root)).toHaveText(["3","20","46.7","80","140"]);await input.fill("NO-MATCH");await expect(values(root)).toHaveText(["0","No value","No value","No value","No value"]);await runtime.route(`**/v1/aggregates/${type}**`,route=>route.fulfill({status:403,contentType:"application/json",body:JSON.stringify({error:{message:"Denied"}})}));await input.fill("B");await expect(root.getByRole("alert")).toBeVisible();await expect(values(root)).toHaveCount(0);await runtime.unroute(`**/v1/aggregates/${type}**`);await input.fill("");await expect(values(root)).toHaveText(["6","20","63.3","100","380"]);
 await runtime.getByRole("button",{name:"Open statistics",exact:true}).click();const panel=runtime.getByRole("dialog",{name:"Statistics panel",exact:true}),localInput=panel.getByRole("textbox",{name:"Local filter",exact:true});await expect(values(panel)).toHaveText(["6","20","63.3","100","380"]);await localInput.fill("A");await expect(values(panel)).toHaveText(["3","20","46.7","80","140"]);await panel.getByRole("button",{name:"Close statistics",exact:true}).click();await runtime.getByRole("button",{name:"Open statistics",exact:true}).click();await expect(localInput).toHaveValue("");await expect(values(panel)).toHaveText(["6","20","63.3","100","380"]);await panel.getByRole("button",{name:"Close statistics",exact:true}).click();await runtime.reload();await expect(values(root)).toHaveText(["6","20","63.3","100","380"]);
});
