import {expect,test} from "@playwright/test";
import {decide,fresh,open,pageUIProfile,stableReadRevision} from "./host";

test("authored trend and pie marks retain their frozen source and clear invalid or obsolete shares",async({page,request},info)=>{
 test.setTimeout(60_000);
 const name=fresh("marks").replace(/[^a-z0-9]/gi,"").toLowerCase(),type=`build.${name}`,object=fresh("OBJ"),id=fresh("PAGE"),ref={app:"build",kind:"object",name:type};
 await decide(request,"manager","build","build.object.create",{type:"build.object",id:object},{name,title:"Chart notes",fields:[{name:"bucket",title:"Bucket",type:"text"},{name:"day",title:"Day",type:"date"},{name:"qty",title:"Quantity",type:"integer"}]});await decide(request,"manager","build","build.object.publish",{type:"build.object",id:object},{});
 for(const [suffix,day,qty] of [["A1","2026-01-01",10],["A2","2026-01-02",20],["A3","2026-01-03",30],["B1","2026-02-01",40],["B2","2026-02-02",50],["C1","2026-03-01",60],["D1","2026-03-02",-100]] as const)await decide(request,"desk","build",`${type}.create`,{type,id:`${name}${suffix}`},{bucket:suffix[0],day,qty});
 await decide(request,"manager","build","build.page.create",{type:"build.page",id},{name,title:"Chart desk",object:type,sections:[{id:"input",widget:"input",configVersion:1,title:"Chart bucket"},{id:"table",widget:"table",configVersion:1,title:"One record window",fields:["bucket"],collectionVariable:"window"},{id:"trend",widget:"chart",configVersion:1,title:"Monthly quantities",group:"bucket",measure:"count"},{id:"pie",widget:"chart",configVersion:1,title:"Quantity shares",group:"bucket",measure:"count"}],document:{formatVersion:2,uiProfile:pageUIProfile,root:"root",nodes:{root:{kind:"rows",children:["input","table","trend","pie"]},input:{kind:"widget",section:"input",valueVariable:"bucket"},table:{kind:"widget",section:"table"},trend:{kind:"widget",section:"trend"},pie:{kind:"widget",section:"pie"}},variables:{bucket:{scope:"page",type:"string",mode:"state",initial:"B"},window:{title:"Complete set",scope:"page",type:"object-set",mode:"resource",source:{kind:"plan",query:"combined"}}},queries:{left:{object:ref,limit:1,conditions:[{field:"bucket",op:"=",value:{literal:"A"}}]},right:{object:ref,limit:1,conditions:[{field:"bucket",op:"=",value:{variable:"bucket"}}]},combined:{object:ref,limit:1,sort:["id"],set:{op:"union",inputs:["left","right"]}}}}});
 await open(page,"manager",`/compose?id=${id}`);const tree=page.getByRole("region",{name:"Widgets and layout",exact:true}),inspector=page.getByRole("region",{name:"The widget in hand",exact:true});
 await tree.getByRole("button",{name:"Monthly quantities",exact:true}).click();await inspector.getByRole("combobox",{name:"Aggregate query set",exact:true}).selectOption("window");await inspector.getByRole("combobox",{name:"Chart type",exact:true}).selectOption("area");await inspector.getByRole("combobox",{name:"Grouped by",exact:true}).selectOption("day:month");await inspector.getByRole("combobox",{name:"Measure",exact:true}).selectOption("sum:qty");await inspector.getByRole("combobox",{name:"Chart type",exact:true}).selectOption("line");
 await tree.getByRole("button",{name:"Quantity shares",exact:true}).click();await inspector.getByRole("combobox",{name:"Aggregate query set",exact:true}).selectOption("window");await inspector.getByRole("combobox",{name:"Chart type",exact:true}).selectOption("arc");await inspector.getByRole("combobox",{name:"Grouped by",exact:true}).selectOption("bucket");await inspector.getByRole("combobox",{name:"Measure",exact:true}).selectOption("sum:qty");
 if(process.env.PLATFORM_SCREENSHOTS)await inspector.screenshot({path:info.outputPath("chart-inspector.png")});
 await page.getByRole("button",{name:"Save",exact:true}).click();await expect.poll(async()=>(await(await request.get(`/v1/records/build.page/${id}`,{headers:{Authorization:"Bearer manager"}})).json()).record.sections.find((s:any)=>s.id==="pie")?.mark).toBe("arc");await page.getByRole("button",{name:"Review release",exact:true}).click();await page.getByRole("button",{name:"Check draft and dependencies",exact:true}).click();await page.getByRole("button",{name:"Save immutable candidate",exact:true}).click();
 const saved=(await(await request.get(`/v1/records/build.page/${id}`,{headers:{Authorization:"Bearer manager"}})).json()).record;for(const s of saved.sections)if(s.widget==="chart"){s.mark="bar";delete s.chartVariant;}saved.document.queries.combined.set.op="subtract";await decide(request,"manager","build","build.page.edit",{type:"build.page",id},{sections:saved.sections,document:saved.document});await page.getByRole("button",{name:"Activate release",exact:true}).click();
 const operation=await page.context().newPage();await stableReadRevision(operation);let reads=0;operation.on("request",r=>{if(r.url().endsWith(`/v1/aggregates/${type}/query`)){reads++;const q=r.postDataJSON();expect(q.maxRows).toBe(4096);expect(q.set.op).toBe("union");expect(q.limit).toBeUndefined();}});const monthly=operation.waitForResponse(r=>r.url().endsWith(`/v1/aggregates/${type}/query`)&&r.request().postDataJSON().groups?.[0]==="day:month");
 await open(operation,"desk",`/page?app=build&kind=page&name=${name}`);const trend=operation.getByRole("heading",{name:"Monthly quantities",exact:true}).locator(".."),pie=operation.getByRole("heading",{name:"Quantity shares",exact:true}).locator(".."),input=operation.getByRole("textbox",{name:"Chart bucket",exact:true});await expect(trend.getByRole("img")).toBeVisible();await expect(pie.getByRole("img")).toBeVisible();expect((await(await monthly).json()).rows).toEqual([{"day:month":"2026-01","sum:qty":60},{"day:month":"2026-02","sum:qty":90}]);expect(reads).toBe(2);
 await operation.getByRole("button",{name:"Next page",exact:true}).click();await expect(operation.getByText("2–2 of 5",{exact:true})).toBeVisible();expect(reads).toBe(2);
 let release!:()=>void,delivered!:()=>void,held=false;const gate=new Promise<void>(r=>release=r),done=new Promise<void>(r=>delivered=r);await operation.route(`**/v1/aggregates/${type}/query`,async route=>{const q=route.request().postDataJSON();if(q.groups[0]==="bucket"&&q.set.inputs[1].domain[0][2]==="C"){const response=await route.fetch();held=true;await gate;await route.fulfill({response});delivered();}else await route.continue();});await input.fill("C");await expect.poll(()=>held).toBe(true);await expect(pie.getByRole("img")).toHaveCount(0);await input.fill("D");await expect(pie.getByRole("alert")).toContainText("Pie values must be finite nonnegative");release();await done;await operation.unroute(`**/v1/aggregates/${type}/query`);await expect(pie.getByRole("img")).toHaveCount(0);
 await operation.route(`**/v1/aggregates/${type}/query`,route=>route.fulfill({status:403,contentType:"application/json",body:JSON.stringify({error:{message:"Denied"}})}));await input.fill("B");await expect(pie.getByRole("alert")).toBeVisible();await expect(trend.getByRole("img")).toHaveCount(0);await operation.unroute(`**/v1/aggregates/${type}/query`);await input.fill("C");await expect(pie.getByRole("img")).toBeVisible();await expect(trend.getByRole("img")).toBeVisible();
 if(process.env.PLATFORM_SCREENSHOTS){await trend.scrollIntoViewIfNeeded();await operation.screenshot({path:info.outputPath("chart-runtime.png"),fullPage:true});await pie.screenshot({path:info.outputPath("chart-pie.png")});await operation.setViewportSize({width:390,height:844});await operation.evaluate(()=>new Promise<void>(r=>requestAnimationFrame(()=>requestAnimationFrame(()=>r()))));await operation.screenshot({path:info.outputPath("chart-runtime-narrow.png"),fullPage:true});await trend.screenshot({path:info.outputPath("chart-trend-narrow.png")});}await operation.reload();await expect(trend.getByRole("img")).toBeVisible();await expect(pie.getByRole("img")).toBeVisible();
});
