import {expect,test} from "@playwright/test";
import {decide,fresh,open,pageUIProfile} from "./host";

test("parent-owned child queries isolate nested item state and run original child actions through a frozen page",async({page,request},info)=>{
 test.setTimeout(60_000);
 const name=fresh("nested").replace(/[^a-z0-9]/gi,"").toLowerCase(),parent=`build.${name}parent`,child=`build.${name}child`,parentObject=fresh("OBJ"),childObject=fresh("OBJ"),query=fresh("QUERY"),id=fresh("PAGE"),ref={app:"build",kind:"object",name:parent},childRef={app:"build",kind:"object",name:child};
 await decide(request,"manager","build","build.object.create",{type:"build.object",id:parentObject},{name:`${name}parent`,title:"Nested parents",fields:[{name:"note",title:"Note",type:"text",search:true},{name:"bucket",title:"Bucket",type:"text"}]});await decide(request,"manager","build","build.object.publish",{type:"build.object",id:parentObject},{});
 await decide(request,"manager","build","build.object.create",{type:"build.object",id:childObject},{name:`${name}child`,title:"Nested children",fields:[{name:"note",title:"Note",type:"text"},{name:"parent",title:"Parent",type:"reference",ref:parent,required:true}],states:[{name:"open",title:"Open"},{name:"done",title:"Done"}],actions:[{name:"complete",title:"Complete child",from:["open"],to:"done"}]});await decide(request,"manager","build","build.object.publish",{type:"build.object",id:childObject},{});
 for(const suffix of ["A","B"]){await decide(request,"desk","build",`${parent}.create`,{type:parent,id:`${name}${suffix}`},{note:`PARENT-${suffix}`,bucket:suffix});for(const n of [1,2])await decide(request,"desk","build",`${child}.create`,{type:child,id:`${name}${suffix}${n}`},{note:`CHILD-${suffix}${n}`,parent:`${name}${suffix}`});}
 await decide(request,"manager","build","build.query.create",{type:"build.query",id:query},{name,title:"Children for a parent",description:"Read the original parent reference",object:child,by:"parent",limit:3});await decide(request,"manager","build","build.query.publish",{type:"build.query",id:query},{});
 const document={formatVersion:2,uiProfile:pageUIProfile,root:"root",nodes:{root:{kind:"rows",children:["input","parents"]},input:{kind:"widget",section:"input",valueVariable:"search"},parents:{kind:"loop",title:"Parent cards",children:["parentDetail","children"],loop:{collection:"parentWindow",itemVariable:"parentItem",limit:2}},parentDetail:{kind:"widget",section:"parentDetail"},children:{kind:"loop",title:"Child cards",children:["childDetail","actions","button","notice"],loop:{collection:"childWindow",itemVariable:"childItem",limit:3}},childDetail:{kind:"widget",section:"childDetail"},actions:{kind:"widget",section:"actions"},button:{kind:"widget",section:"button"},notice:{kind:"widget",section:"notice",visibleWhen:"shown"}},variables:{search:{scope:"page",type:"string",mode:"state",initial:""},parentWindow:{scope:"page",type:"object-set",mode:"resource",source:{kind:"plan",query:"parents"}},parentItem:{scope:"loop-item",owner:"parents",type:"record",mode:"resource",source:{kind:"item",node:"parents"}},childWindow:{scope:"loop-item",owner:"parents",type:"object-set",mode:"resource",source:{kind:"plan",query:"children"}},childItem:{scope:"loop-item",owner:"children",type:"record",mode:"resource",source:{kind:"item",node:"children"}},shown:{scope:"loop-item",owner:"children",type:"boolean",mode:"state",initial:false}},queries:{parents:{object:ref,limit:2,sort:["id"],search:{variable:"search"}},children:{title:"Per-parent children",itemOwner:"parents",object:childRef,query:{ref:{app:"build",kind:"query",name},sourceVersion:"1.query-1"},for:{variable:"parentItem"},limit:3,sort:["id"]}},events:[{source:"button",event:"click",target:"shown",value:true}]};
 await decide(request,"manager","build","build.page.create",{type:"build.page",id},{name,title:"Nested operation desk",object:parent,sections:[{id:"input",widget:"input",configVersion:1,title:"Parent search"},{id:"parentDetail",widget:"detail",configVersion:1,title:"Parent",object:parent,fields:["note"],recordVariable:"parentItem"},{id:"childDetail",widget:"detail",configVersion:1,title:"Child",object:child,fields:["note"],recordVariable:"childItem"},{id:"actions",widget:"actions",configVersion:1,title:"Child work",object:child,actions:[`${child}.complete`],recordVariable:"childItem"},{id:"button",widget:"button",configVersion:1,title:"Show child context"},{id:"notice",widget:"text",configVersion:1,text:"This child's context"}],document});
 await open(page,"manager",`/compose?id=${id}`);const tree=page.getByRole("region",{name:"Widgets and layout",exact:true}),inspector=page.getByRole("region",{name:"The widget in hand",exact:true});await tree.getByRole("button",{name:"Query plans",exact:true}).click();await inspector.getByRole("combobox",{name:"Choose query plan",exact:true}).selectOption("children");await expect(inspector.getByRole("combobox",{name:"Query scope",exact:true})).toHaveValue("item:parents");await inspector.getByRole("combobox",{name:"Named query binding",exact:true}).selectOption(`build/${name}@1.query-1`);await inspector.getByRole("textbox",{name:"Query title",exact:true}).fill("Children in this parent");await page.getByRole("button",{name:"Save",exact:true}).click();await expect(page.getByRole("button",{name:"Save",exact:true})).toBeDisabled();await page.getByRole("button",{name:"Review release",exact:true}).click();await page.getByRole("button",{name:"Check draft and dependencies",exact:true}).click();await page.getByRole("button",{name:"Save immutable candidate",exact:true}).click();await page.getByRole("button",{name:"Activate release",exact:true}).click();
 const operation=await page.context().newPage();await open(operation,"desk",`/page?app=build&kind=page&name=${name}`);const parents=operation.getByRole("list",{name:"Parent cards",exact:true}),a=parents.getByRole("region",{name:`${name}A`,exact:true}),b=parents.getByRole("region",{name:`${name}B`,exact:true}),a1=a.getByRole("region",{name:`${name}A1`,exact:true}),b1=b.getByRole("region",{name:`${name}B1`,exact:true});await expect(a1.getByText("CHILD-A1",{exact:true})).toBeVisible();await expect(b1.getByText("CHILD-B1",{exact:true})).toBeVisible();await expect(a.getByText("CHILD-B1",{exact:true})).toHaveCount(0);await a1.getByRole("button",{name:"Show child context",exact:true}).click();await expect(a1.getByText("This child's context",{exact:true})).toBeVisible();await expect(b1.getByText("This child's context",{exact:true})).toHaveCount(0);await a1.getByRole("button",{name:"Complete child",exact:true}).click();await expect.poll(async()=>(await(await request.get(`/v1/records/${child}/${name}A1`,{headers:{Authorization:"Bearer desk"}})).json()).record.state).toBe("done");expect((await(await request.get(`/v1/records/${child}/${name}B1`,{headers:{Authorization:"Bearer desk"}})).json()).record.state).toBe("open");
 const input=operation.getByRole("textbox",{name:"Parent search",exact:true});await input.fill("PARENT-B");await expect(a).toHaveCount(0);await expect(b1.getByText("CHILD-B1",{exact:true})).toBeVisible();await input.fill("");await expect(a1.getByText("CHILD-A1",{exact:true})).toBeVisible();await expect(a1.getByText("This child's context",{exact:true})).toHaveCount(0);
 // A denied child window must clear its own content while the other parent stays usable.
 await operation.route(`**/v1/records/${child}?*`,async route=>{const domain=new URL(route.request().url()).searchParams.get("domain")??"";if(domain.includes(`${name}B`))await route.fulfill({status:403,contentType:"application/json",body:JSON.stringify({error:{message:"Denied"}})});else await route.continue();});
 await input.fill("PARENT-B");await expect(b.getByRole("alert").filter({hasText:"Loop source could not be read."})).toBeVisible();await expect(b.getByText("CHILD-B1",{exact:true})).toHaveCount(0);await operation.unroute(`**/v1/records/${child}?*`);
 await input.fill("");await expect(a1.getByText("CHILD-A1",{exact:true})).toBeVisible();await expect(b1.getByText("CHILD-B1",{exact:true})).toBeVisible();
 // Hold all old A-window responses; removal of A retires their owning session.
 let release!:()=>void,held=false,released=false;const completed:Promise<void>[]=[];const wait=new Promise<void>(resolve=>release=resolve);
 await operation.route(`**/v1/records/${child}?*`,async route=>{const domain=new URL(route.request().url()).searchParams.get("domain")??"";if(domain.includes(`${name}A`)&&!released){let done!:()=>void;completed.push(new Promise<void>(resolve=>done=resolve));try{const response=await route.fetch();held=true;await wait;await route.fulfill({response});}finally{done();}}else await route.continue();});
 await input.fill("PARENT-A");await expect.poll(()=>held).toBe(true);await input.fill("PARENT-B");await expect(a).toHaveCount(0);await expect(b1.getByText("CHILD-B1",{exact:true})).toBeVisible();released=true;release();await Promise.all(completed);await expect(a).toHaveCount(0);await expect(b.getByText("CHILD-A1",{exact:true})).toHaveCount(0);await operation.unroute(`**/v1/records/${child}?*`);
 await input.fill("");await expect(a1.getByText("CHILD-A1",{exact:true})).toBeVisible();
 if(process.env.PLATFORM_SCREENSHOTS){await a1.scrollIntoViewIfNeeded();await operation.screenshot({path:info.outputPath("nested-loop.png"),fullPage:true});await operation.setViewportSize({width:390,height:844});await operation.evaluate(()=>new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve()))));await operation.screenshot({path:info.outputPath("nested-loop-narrow.png"),fullPage:true});}await operation.reload();await expect(a1.getByText("CHILD-A1",{exact:true})).toBeVisible();await expect(a1.getByText("This child's context",{exact:true})).toHaveCount(0);
});
