import {expect,test} from "@playwright/test";
import {readFileSync} from "node:fs";
import {decide,fresh,open,pageUIProfile,stableReadRevision} from "./host";

test("four imported resource and exploration widgets freeze original assets, traverse real relations and publish typed graph outputs",async({page,request},info)=>{
 test.setTimeout(150_000);page.setDefaultTimeout(10_000);
 const name=fresh("explore").replace(/[^a-z0-9]/gi,"").toLowerCase(),types=Object.fromEntries(["asset","sensor","alert","work"].map(s=>[s,`build.${name}${s}`])),id=fresh("PAGE"),get=async(type:string,id:string)=>(await(await request.get(`/v1/records/${type}/${id}`,{headers:{Authorization:"Bearer manager"}})).json()).record;
 const make=async(suffix:string,fields:any[])=>{const object=fresh("OBJ");await decide(request,"manager","build","build.object.create",{type:"build.object",id:object},{name:`${name}${suffix}`,title:`Original ${suffix}`,fields});await decide(request,"manager","build","build.object.publish",{type:"build.object",id:object},{});};
 await make("asset",[{name:"name",title:"Name",type:"text"},{name:"status",title:"Status",type:"choice",choices:"ready,warning"}]);
 await make("sensor",[{name:"name",title:"Name",type:"text"},{name:"asset",title:"Asset",type:"reference",ref:types.asset},{name:"private",title:"Private sensor data",type:"text",read:["builder"]}]);await make("alert",[{name:"name",title:"Name",type:"text"},{name:"asset",title:"Asset",type:"reference",ref:types.asset}]);await make("work",[{name:"name",title:"Name",type:"text"},{name:"sensor",title:"Sensor",type:"reference",ref:types.sensor}]);
 for(let i=0;i<14;i++)await decide(request,"manager","build",`${types.asset}.create`,{type:types.asset,id:`${name}${String(i).padStart(2,"0")}`},{name:`ROOT-${i}`,status:i%2?"warning":"ready"});
 const parent=`${name}00`,other=`${name}01`,shared=parent;
 for(let i=0;i<22;i++)await decide(request,"manager","build",`${types.sensor}.create`,{type:types.sensor,id:i===0?shared:`${name}s${String(i).padStart(2,"0")}`},{name:i<2?"Same sensor name":`Sensor ${i}`,asset:parent,private:"PRIVATE-SENSOR-DATA"});
 await decide(request,"manager","build",`${types.sensor}.create`,{type:types.sensor,id:`${name}other`},{name:"Other root sensor",asset:other});for(let i=0;i<4;i++)await decide(request,"manager","build",`${types.alert}.create`,{type:types.alert,id:i===0?shared:`${name}a${i}`},{name:`Alert ${i}`,asset:parent});await decide(request,"manager","build",`${types.work}.create`,{type:types.work,id:`${name}work`},{name:"ORIGINAL WORK",sensor:shared});
 const linkNames:Record<string,string>={};for(const [suffix,parentType,childType,via,forward,reverse] of [["sensors",types.asset,types.sensor,"asset","Sensors","Asset"],["alerts",types.asset,types.alert,"asset","Alerts","Asset"],["work",types.sensor,types.work,"sensor","Work","Sensor"]]){const link=fresh("LINK"),linkName=`${name}${suffix}`;await decide(request,"manager","build","build.linktype.create",{type:"build.linktype",id:link},{name:linkName,title:`Original ${suffix}`,description:"Original authorized relationship",parent:parentType,child:childType,via,forward:forward.toLowerCase(),reverse:reverse.toLowerCase()});await decide(request,"manager","build","build.linktype.publish",{type:"build.linktype",id:link},{});linkNames[suffix]=linkName;}
 const m=JSON.parse(readFileSync(new URL("../../packages/build/src/module-import/sample.workshop.json",import.meta.url),"utf8")),set=(id:string,object:string)=>({id,name:id,type:"objectSet",definitionKind:"objectSetDefinition",sourceObjectType:object,dependsOn:[],objectSet:{objectType:object,steps:[]}}),selection=(id:string,widget:string)=>({id,name:id,type:"object",definitionKind:"widgetOutput",dependsOn:[],widgetId:widget,widgetOutputKey:"activeObject"}),resources=(id:string,set:string,active:string)=>({id,name:id==="resources"?"Original resources":"Panel resources",type:"ResourceList",config:{objectSetVarId:set,activeVarId:active}}),graph=(id:string,root:string,output?:string)=>({id,name:id==="graph"?"Original Search Around":"Panel Search Around",type:"GraphExplorer",config:{objectVarId:root,...(output?{outputVarId:output}:{})}}),vertex=(id:string,root:string)=>({id,name:id==="vertex"?"Original neighborhood":"Panel neighborhood",type:"VertexGraph",config:{objectVarId:root}}),directory=(id:string)=>({id,name:id==="directory"?"Original mapped directory":"Panel directory",type:"LinkedCompass",config:{}});
 m.variables=[set("items","Asset"),selection("selected","resources"),set("sensors","Sensor"),selection("pickedSensor","sensorTable"),set("localItems","Asset"),selection("localSelected","localResources"),{id:"graphDraft",name:"Graph comment draft",type:"string",definitionKind:"static",staticValue:""},{id:"graphCommentList",name:"Graph comment list",type:"array",definitionKind:"static",staticValue:[]}];
 m.widgets={sensorComments:{id:"sensorComments",name:"Graph output discussion",type:"Comments",config:{draftVarId:"graphDraft",listVarId:"graphCommentList"}},resources:resources("resources","items","selected"),graph:graph("graph","selected","pickedSensor"),vertex:vertex("vertex","selected"),directory:directory("directory"),sensorTable:{id:"sensorTable",name:"Original sensor producer",type:"ObjectTable",config:{objectSetVarId:"sensors",activeVarId:"pickedSensor",columns:[{key:"name"}]}},sensorCard:{id:"sensorCard",name:"Graph output card",type:"ObjectCard",config:{objectVarId:"pickedSensor"}},localResources:resources("localResources","localItems","localSelected"),localGraph:graph("localGraph","localSelected"),localVertex:vertex("localVertex","localSelected"),localDirectory:directory("localDirectory"),trigger:{id:"trigger",name:"Open exploration panel",type:"SingleButton",config:{label:"Open exploration panel",eventActions:[{kind:"openOverlay",overlayId:"panel"}]}},close:{id:"close",name:"Close exploration panel",type:"SingleButton",config:{label:"Close exploration panel",eventActions:[{kind:"closeOverlay",overlayId:"panel"}]}}};
 m.sections={root:{id:"root",name:"Root",layout:"rows",children:["resources","graph","vertex","directory","sensorCard","sensorComments","sensorTable","trigger"].map(id=>({kind:"widget",id}))},panel:{id:"panel",name:"Panel",layout:"rows",children:["localResources","localGraph","localVertex","localDirectory","close"].map(id=>({kind:"widget",id}))}};m.overlays=[{id:"panel",name:"Original exploration panel",kind:"drawer",rootSectionId:"panel"}];
 await decide(request,"manager","build","build.page.create",{type:"build.page",id},{name,title:"Original exploration desk",object:types.asset,sections:[{id:"initial",widget:"text",configVersion:1,text:"Initial"}],document:{formatVersion:2,uiProfile:pageUIProfile,root:"root",nodes:{root:{kind:"rows",children:["initial"]},initial:{kind:"widget",section:"initial"}}}});
 await open(page,"manager",`/compose?id=${id}`);await page.getByRole("button",{name:"Import Workshop module",exact:true}).click();const dialog=page.getByRole("dialog",{name:"Import Workshop module",exact:true});await dialog.getByRole("textbox",{name:"Source module JSON",exact:true}).fill(JSON.stringify(m));for(const [external,type] of [["Asset",types.asset],["Sensor",types.sensor]]){await dialog.getByRole("combobox",{name:`Map object ${external}`,exact:true}).selectOption(type);for(const field of ["name"])await dialog.getByRole("combobox",{name:`Map field ${external}.${field}`,exact:true}).selectOption(field);}
 const optionContaining=async(selector:any,text:string)=>(await selector.locator("option").filter({hasText:text}).first().getAttribute("value"))!;
 for(const title of ["Original resources","Panel resources"]){const group=dialog.getByRole("group",{name:`Map resource list ${title}`,exact:true});await group.getByRole("combobox",{name:"Resource title field",exact:true}).selectOption("name");await group.getByRole("combobox",{name:"Resource status field",exact:true}).selectOption("status");}
 for(const title of ["Original Search Around","Panel Search Around"]){const group=dialog.getByRole("group",{name:`Map graph explorer ${title}`,exact:true});for(const suffix of ["sensors","alerts","work"])await group.getByRole("button",{name:new RegExp(linkNames[suffix])}).click();for(const type of Object.values(types))await group.getByRole("combobox",{name:`Graph title field ${type}`,exact:true}).selectOption("name");if(title==="Original Search Around"){await group.getByRole("combobox",{name:"Graph output migration",exact:true}).selectOption("graph-ports");const selector=group.getByRole("combobox",{name:"Graph consumer output object",exact:true});await selector.selectOption(await optionContaining(selector,types.sensor));}}
 for(const title of ["Original neighborhood","Panel neighborhood"]){const group=dialog.getByRole("group",{name:`Map vertex graph ${title}`,exact:true});for(const [label,suffix] of [["Sensor relation","sensors"],["Alert relation","alerts"]]){const selector=group.getByRole("combobox",{name:label,exact:true});await selector.selectOption(await optionContaining(selector,linkNames[suffix]));}}
 for(const title of ["Original mapped directory","Panel directory"]){const group=dialog.getByRole("group",{name:`Map asset directory ${title}`,exact:true});for(const [index,ref] of [[1,types.asset],[2,types.alert],[3,linkNames.work],[4,linkNames.sensors]]){const selector=group.getByRole("combobox",{name:new RegExp(`^Directory asset ${index}`)}),kind=index<=2?"object":"link-type",values=await selector.locator("option").evaluateAll(options=>options.map(option=>(option as HTMLOptionElement).value)),chosen=values.find(value=>{if(!value)return false;const asset=JSON.parse(value);return asset.ref.kind===kind&&asset.ref.name===ref;});expect(chosen).toBeTruthy();await selector.selectOption(chosen!);}}
 await dialog.getByRole("group",{name:"Map record collaboration Graph output discussion",exact:true}).getByRole("combobox",{name:"Original record selection",exact:true}).selectOption("pickedSensor");const card=dialog.getByRole("group",{name:"Map object card Graph output card",exact:true});await card.getByRole("combobox",{name:"Card title field",exact:true}).selectOption("name");await dialog.getByRole("checkbox").check();await expect(dialog.getByRole("button",{name:"Apply imported page draft",exact:true})).toBeEnabled();await dialog.getByRole("button",{name:"Apply imported page draft",exact:true}).click();await page.getByRole("button",{name:"Save",exact:true}).click();let saved:any;await expect.poll(async()=>{saved=await get("build.page",id);return saved.sections?.filter((s:any)=>["resource-list","graph-explorer","vertex-graph","asset-directory"].includes(s.widget)).length;}).toBe(8);
 await page.getByRole("button",{name:"Review release",exact:true}).click();await page.getByRole("button",{name:"Check draft and dependencies",exact:true}).click();await page.getByRole("button",{name:"Save immutable candidate",exact:true}).click();saved.sections.find((s:any)=>s.title==="Original resources").resourceList.labelField="id";saved.sections.find((s:any)=>s.title==="Original mapped directory").assetDirectory.items[0].label="LATER DIRECTORY";await decide(request,"manager","build","build.page.edit",{type:"build.page",id},{sections:saved.sections});await page.getByRole("button",{name:"Activate release",exact:true}).click();
 const runtime=await page.context().newPage();await stableReadRevision(runtime);await open(runtime,"desk",`/page?app=build&kind=page&name=${name}`);const section=(title:string)=>runtime.getByRole("heading",{name:title,exact:true,level:3}).locator(".."),resourceView=section("Original resources"),explorer=section("Original Search Around"),neighborhood=section("Original neighborhood"),directoryView=section("Original mapped directory"),outputCard=section("Graph output card");
 await expect(resourceView).toContainText("12 of 14");await expect(directoryView).toContainText("Operations / Assets");await expect(directoryView).toContainText(types.asset);await expect(directoryView).not.toContainText("LATER DIRECTORY");await resourceView.getByRole("button").filter({hasText:"ROOT-0"}).click();await expect(explorer.getByRole("tab",{name:"sensors (22)",exact:true})).toBeVisible();await expect(explorer).toContainText("20 of 22");await expect(neighborhood).toContainText("4 of 22");await expect(neighborhood).toContainText("3 of 4");await expect(explorer).not.toContainText("PRIVATE-SENSOR-DATA");
 await explorer.getByRole("button",{name:`Select output ${types.sensor}/${shared}`,exact:true}).click();await expect(outputCard).toContainText("Same sensor name");const discussion=section("Graph output discussion");await expect(discussion).toContainText("No comments on this record.");await discussion.getByRole("textbox",{name:"Comment",exact:true}).fill("COMMENT ON ORIGINAL SENSOR");await discussion.getByRole("button",{name:"Comment",exact:true}).click();await expect(discussion).toContainText("COMMENT ON ORIGINAL SENSOR");const sensorComments=await (await request.post("/v1/records/platform.comment/query",{headers:{Authorization:"Bearer manager"},data:{domain:[["target","=",`${types.sensor}/${shared}`]],limit:20}})).json(),assetComments=await (await request.post("/v1/records/platform.comment/query",{headers:{Authorization:"Bearer manager"},data:{domain:[["target","=",`${types.asset}/${shared}`]],limit:20}})).json();expect(sensorComments.records?.some((r:any)=>r.text==="COMMENT ON ORIGINAL SENSOR")).toBe(true);expect(assetComments.records).toHaveLength(0);await explorer.getByRole("button",{name:`Traverse from ${types.sensor}/${shared}`,exact:true}).click();await expect(explorer.getByRole("tab",{name:"work (1)",exact:true})).toBeVisible();await explorer.getByRole("tab",{name:"work (1)",exact:true}).click();await expect(explorer).toContainText("ORIGINAL WORK");await explorer.getByRole("button",{name:`Traverse from ${types.work}/${name}work`,exact:true}).click();await expect(explorer.getByRole("tab",{name:"sensor (1)",exact:true})).toBeVisible();await explorer.getByRole("navigation",{name:"Exploration path",exact:true}).getByRole("button").first().click();await explorer.getByRole("tab",{name:"alerts (4)",exact:true}).click();await explorer.getByRole("button",{name:`Select output ${types.alert}/${shared}`,exact:true}).click();await expect(outputCard).toContainText("No confirmed record for this card.");await expect(discussion).toContainText("Select a confirmed original record for collaboration.");await expect(explorer.getByRole("button",{name:`Select output ${types.alert}/${shared}`,exact:true})).toHaveAttribute("aria-pressed","true");
 if(process.env.PLATFORM_SCREENSHOTS){await explorer.screenshot({path:info.outputPath("exploration.png")});await neighborhood.screenshot({path:info.outputPath("neighborhood.png")});await directoryView.screenshot({path:info.outputPath("directory.png")});await runtime.setViewportSize({width:390,height:844});await explorer.screenshot({path:info.outputPath("exploration-narrow.png")});await neighborhood.screenshot({path:info.outputPath("neighborhood-narrow.png")});await runtime.setViewportSize({width:1280,height:720});}
 await resourceView.getByRole("button",{name:/^ROOT-1 /}).click();await expect(explorer).toContainText("Other root sensor");await expect(explorer).not.toContainText("Same sensor name");await expect(explorer.getByRole("button",{name:/Select output/})).toHaveAttribute("aria-pressed","false");
 await runtime.getByRole("button",{name:"Open exploration panel",exact:true}).click();const panel=runtime.getByRole("dialog",{name:"Original exploration panel",exact:true}),localExplorer=panel.getByRole("heading",{name:"Panel Search Around",exact:true}).locator("..");await expect(localExplorer).toContainText("Select an original record");await panel.getByRole("heading",{name:"Panel resources",exact:true}).locator("..").getByRole("button").filter({hasText:"ROOT-0"}).click();await expect(localExplorer.getByRole("tab",{name:"sensors (22)",exact:true})).toBeVisible();await panel.getByRole("button",{name:"Close exploration panel",exact:true}).click();await runtime.getByRole("button",{name:"Open exploration panel",exact:true}).click();await expect(localExplorer).toContainText("Select an original record");await panel.getByRole("button",{name:"Close exploration panel",exact:true}).click();await expect(explorer).toContainText("Other root sensor");
 await runtime.route(`**/v1/records/${types.sensor}/query`,route=>route.fulfill({status:403,contentType:"application/json",body:'{"error":{"message":"Denied"}}'}));await runtime.reload();await section("Original resources").getByRole("button").filter({hasText:"ROOT-0"}).click();await expect(section("Original Search Around").getByRole("alert")).toBeVisible();await expect(section("Original Search Around")).not.toContainText("Same sensor name");await runtime.unroute(`**/v1/records/${types.sensor}/query`);await runtime.reload();await section("Original resources").getByRole("button").filter({hasText:"ROOT-0"}).click();await expect(section("Original Search Around")).toContainText("Same sensor name");
 let release:()=>void=()=>{};const gate=new Promise<void>(r=>release=r);let started=false;await runtime.route(`**/v1/records/${types.work}/query`,async route=>{started=true;await gate;await route.continue();});await section("Original Search Around").getByRole("button",{name:`Traverse from ${types.sensor}/${shared}`,exact:true}).click();await expect.poll(()=>started).toBe(true);await section("Original resources").getByRole("button",{name:/^ROOT-1 /}).click();await expect(section("Original Search Around")).toContainText("Other root sensor");release();await runtime.unroute(`**/v1/records/${types.work}/query`);await runtime.evaluate(()=>new Promise<void>(r=>requestAnimationFrame(()=>requestAnimationFrame(()=>r()))));await expect(section("Original Search Around")).not.toContainText("ORIGINAL WORK");
});
