import {expect,test} from "@playwright/test";
import {readFileSync} from "node:fs";
import {decide,fresh,open,pageUIProfile,stableReadRevision} from "./host";

test("default source pivot freezes complete sparse count matrices and isolates private, refused and overlay reads",async({page,request},info)=>{
 test.setTimeout(90_000);
 const name=fresh("matrix").replace(/[^a-z0-9]/gi,"").toLowerCase(),type=`build.${name}`,object=fresh("OBJ"),id=fresh("PAGE");
 await decide(request,"manager","build","build.object.create",{type:"build.object",id:object},{name,title:"Matrix assets",fields:[{name:"note",title:"Note",type:"text"},{name:"bucket",title:"Status",type:"text"},{name:"priority",title:"Priority",type:"text"},{name:"secret",title:"Private group",type:"text",read:["builder"]}]});await decide(request,"manager","build","build.object.publish",{type:"build.object",id:object},{});for(const [suffix,priority] of [["A1","high"],["A2","high"],["A3","low"],["B1","low"],["B2","low"],["C1","medium"]])await decide(request,"manager","build",`${type}.create`,{type,id:`${name}${suffix}`},{note:suffix,bucket:suffix[0],priority,secret:"private"});
 const m=JSON.parse(readFileSync(new URL("../../packages/build/src/workshop/module-import/sample.workshop.json",import.meta.url),"utf8")),pivot=(id:string,name:string,set="notes",rows="status",cols="priority")=>({id,name,type:"PivotTable",config:{objectSetVarId:set,rows,cols,measure:"count"}});
 m.widgets.pivot=pivot("pivot","Status × Priority");m.widgets.hiddenRow=pivot("hiddenRow","Private matrix row","notes","secret");m.widgets.hiddenColumn=pivot("hiddenColumn","Private matrix column","notes","status","secret");m.widgets.hiddenCondition=pivot("hiddenCondition","Private matrix condition","privateNotes");m.widgets.local=pivot("local","Local matrix","localNotes");m.widgets.input={id:"input",name:"Matrix filter",type:"TextInput",config:{variableId:"scratch",label:"Matrix filter"}};m.widgets.localInput={id:"localInput",name:"Local matrix filter",type:"TextInput",config:{variableId:"localScratch",label:"Local matrix filter"}};m.widgets.trigger={id:"trigger",name:"Open matrix",type:"SingleButton",config:{label:"Open matrix",eventActions:[{kind:"openOverlay",overlayId:"panel"}]}};m.widgets.close={id:"close",name:"Close matrix",type:"SingleButton",config:{label:"Close matrix",eventActions:[{kind:"closeOverlay",overlayId:"panel"}]}};
 m.variables.find((v:any)=>v.id==="scratch").staticValue="";m.variables.find((v:any)=>v.id==="notes").objectSet.steps=[{op:"where",clauses:[{id:"status",property:"status",op:"contains",varId:"scratch"}]}];m.variables.push({id:"localScratch",name:"Local status",type:"string",definitionKind:"static",staticValue:""},{id:"localNotes",name:"Local notes",type:"objectSet",definitionKind:"objectSetDefinition",sourceObjectType:"Asset",objectSet:{objectType:"Asset",steps:[{op:"where",clauses:[{id:"local",property:"status",op:"contains",varId:"localScratch"}]}]}},{id:"privateNotes",name:"Private notes",type:"objectSet",definitionKind:"objectSetDefinition",sourceObjectType:"Asset",objectSet:{objectType:"Asset",steps:[{op:"where",clauses:[{id:"private",property:"secret",op:"is",value:"private"}]}]}});
 m.sections={root:{id:"root",name:"Root",layout:"rows",children:["input","table","pivot","hiddenRow","hiddenColumn","hiddenCondition","trigger"].map(id=>({kind:"widget",id}))},panel:{id:"panel",name:"Panel",layout:"rows",children:["localInput","local","close"].map(id=>({kind:"widget",id}))}};m.overlays=[{id:"panel",name:"Matrix panel",kind:"drawer",rootSectionId:"panel"}];
 await decide(request,"manager","build","build.page.create",{type:"build.page",id},{name,title:"Imported matrix",object:type,sections:[{id:"initial",widget:"table",configVersion:1,fields:["note"]}],document:{formatVersion:2,uiProfile:pageUIProfile,root:"root",nodes:{root:{kind:"rows",children:["initial"]},initial:{kind:"widget",section:"initial"}}}});
 await open(page,"manager",`/compose?id=${id}`);await page.getByRole("button",{name:"Import Workshop module",exact:true}).click();const dialog=page.getByRole("dialog",{name:"Import Workshop module",exact:true});await dialog.getByRole("textbox",{name:"Source module JSON",exact:true}).fill(JSON.stringify(m));await dialog.getByRole("combobox",{name:"Map object Asset",exact:true}).selectOption(type);for(const [source,target] of [["name","note"],["status","bucket"],["priority","priority"],["secret","secret"]])await dialog.getByRole("combobox",{name:`Map field Asset.${source}`,exact:true}).selectOption(target);await dialog.getByRole("checkbox").check();await dialog.getByRole("button",{name:"Apply imported page draft",exact:true}).click();const tree=page.getByRole("region",{name:"Widgets and layout",exact:true}),inspector=page.getByRole("region",{name:"The widget in hand",exact:true});await tree.getByRole("button",{name:"Status × Priority",exact:true}).click();await expect(inspector.getByRole("combobox",{name:"Rows grouped by",exact:true})).toHaveValue("bucket");await expect(inspector.getByRole("combobox",{name:"Columns grouped by",exact:true})).toHaveValue("priority");await expect(inspector.getByRole("combobox",{name:"Measure",exact:true})).toHaveValue("count");await page.getByRole("button",{name:"Query plans",exact:true}).click();await page.getByRole("combobox",{name:"Choose query plan",exact:true}).selectOption({index:1});await page.getByRole("spinbutton",{name:"Query window limit",exact:true}).fill("1");await page.getByRole("button",{name:"Save",exact:true}).click();let saved:any;await expect.poll(async()=>{saved=(await(await request.get(`/v1/records/build.page/${id}`,{headers:{Authorization:"Bearer manager"}})).json()).record;return saved.sections?.filter((s:any)=>s.widget==="pivot").length;}).toBe(5);
 await page.getByRole("button",{name:"Review release",exact:true}).click();await page.getByRole("button",{name:"Check draft and dependencies",exact:true}).click();await page.getByRole("button",{name:"Save immutable candidate",exact:true}).click();saved.sections.find((s:any)=>s.title==="Status × Priority").columnGroup="";await decide(request,"manager","build","build.page.edit",{type:"build.page",id},{sections:saved.sections});await page.getByRole("button",{name:"Activate release",exact:true}).click();
 const runtime=await page.context().newPage();await stableReadRevision(runtime);const endpoint=`/v1/aggregates/${type}/query`;let reads=0;runtime.on("request",r=>{if(r.url().endsWith(endpoint)){reads++;const q=r.postDataJSON();expect(q.groups).toEqual(["bucket","priority"]);expect(q.measures).toEqual(["count"]);expect(q.limit).toBeUndefined();expect(q.maxRows).toBe(4096);}});const first=runtime.waitForResponse(r=>r.url().endsWith(endpoint));await open(runtime,"desk",`/page?app=build&kind=page&name=${name}`);const root=runtime.getByRole("heading",{name:"Status × Priority",exact:true}).locator(".."),input=runtime.getByRole("textbox",{name:"Matrix filter",exact:true}),row=(label:string)=>root.getByRole("rowheader",{name:label,exact:true}).locator("..");await expect(root.getByRole("table")).toBeVisible();expect((await(await first).json()).rows).toEqual([{bucket:"A",priority:"high",count:2},{bucket:"A",priority:"low",count:1},{bucket:"B",priority:"low",count:2},{bucket:"C",priority:"medium",count:1}]);await expect(row("A").getByRole("cell")).toHaveText(["2","1","0","3"]);await expect(row("B").getByRole("cell")).toHaveText(["0","2","0","2"]);await expect(row("Total").getByRole("cell")).toHaveText(["2","3","1","6"]);await expect(runtime.getByText("1–1 of 6",{exact:true})).toBeVisible();for(const title of ["Private matrix row","Private matrix column","Private matrix condition"])await expect(runtime.getByRole("heading",{name:title,exact:true})).toHaveCount(0);const before=reads;await runtime.getByRole("button",{name:"Next page",exact:true}).click();await expect(runtime.getByText("2–2 of 6",{exact:true})).toBeVisible();expect(reads).toBe(before);
 if(process.env.PLATFORM_SCREENSHOTS){await root.screenshot({path:info.outputPath("imported-pivot.png")});await runtime.setViewportSize({width:390,height:844});await runtime.evaluate(()=>new Promise<void>(r=>requestAnimationFrame(()=>requestAnimationFrame(()=>r()))));await root.scrollIntoViewIfNeeded();await root.screenshot({path:info.outputPath("imported-pivot-narrow.png")});await runtime.setViewportSize({width:1280,height:720});}
 await input.fill("Z");await expect(root.getByRole("rowheader",{name:"A",exact:true})).toHaveCount(0);await expect(row("Total").getByRole("cell")).toHaveText(["0"]);await runtime.route(`**${endpoint}`,route=>route.fulfill({status:403,contentType:"application/json",body:JSON.stringify({error:{message:"Denied"}})}));await input.fill("A");await expect(root.getByRole("alert")).toBeVisible();await expect(root.getByRole("table")).toHaveCount(0);await runtime.unroute(`**${endpoint}`);await input.fill("B");await expect(row("Total").getByRole("cell")).toHaveText(["2","2"]);
 await runtime.getByRole("button",{name:"Open matrix",exact:true}).click();const panel=runtime.getByRole("dialog",{name:"Matrix panel",exact:true}),localInput=panel.getByRole("textbox",{name:"Local matrix filter",exact:true});await expect(panel.getByRole("rowheader",{name:"Total",exact:true}).locator("..").getByRole("cell")).toHaveText(["2","3","1","6"]);await localInput.fill("A");await expect(panel.getByRole("rowheader",{name:"Total",exact:true}).locator("..").getByRole("cell")).toHaveText(["2","1","3"]);await panel.getByRole("button",{name:"Close matrix",exact:true}).click();await expect(input).toHaveValue("B");await runtime.getByRole("button",{name:"Open matrix",exact:true}).click();await expect(localInput).toHaveValue("");await expect(panel.getByRole("rowheader",{name:"Total",exact:true}).locator("..").getByRole("cell")).toHaveText(["2","3","1","6"]);await panel.getByRole("button",{name:"Close matrix",exact:true}).click();await runtime.reload();await expect(input).toHaveValue("");await expect(row("Total").getByRole("cell")).toHaveText(["2","3","1","6"]);
});
