import {expect,test} from "@playwright/test";
import {decide,fresh,open,pageUIProfile,stableReadRevision} from "./host";

test("three embedded page presentations keep frozen child bytes, isolated state and typed results",async({page,request},info)=>{
 test.setTimeout(90_000);page.setDefaultTimeout(10_000);const name=fresh("embed").replace(/[^a-z0-9]/gi,"").toLowerCase(),type=`build.${name}`,object=fresh("OBJ"),childID=fresh("PAGE"),parentID=fresh("PAGE"),headers={Authorization:"Bearer manager"};
 await decide(request,"manager","build","build.object.create",{type:"build.object",id:object},{name,title:"Embedding records",fields:[{name:"name",title:"Name",type:"text"}]});await decide(request,"manager","build","build.object.publish",{type:"build.object",id:object},{});
 const nodes=(sections:any[])=>({root:{kind:"rows",children:sections.map(s=>s.id)},...Object.fromEntries(sections.map(s=>[s.id,{kind:"widget",section:s.id,...s.widget==="input"?{valueVariable:s.id}:{}}]))});
 const childName=`${name}child`,childSections=[{id:"text",widget:"text",configVersion:1,text:"ORIGINAL EMBEDDED CONTENT"},{id:"note",widget:"input",configVersion:1,title:"Child note"},{id:"return",widget:"button",configVersion:1,title:"Return child note"}],childDoc={formatVersion:2,uiProfile:pageUIProfile,root:"root",nodes:nodes(childSections),variables:{note:{scope:"page",type:"string",mode:"state",initial:"Initial child note"},context:{scope:"page",type:"string",mode:"input"}},interface:{version:1,inputs:{context:{variable:"context",type:"string",required:true}},outputs:{note:{variable:"note",type:"string",required:true}}},events:[{source:"return",event:"click",target:"",return:true}]};
 await decide(request,"manager","build","build.page.create",{type:"build.page",id:childID},{name:childName,title:"Original child",object:type,sections:childSections,document:childDoc});await decide(request,"manager","build","build.page.publish",{type:"build.page",id:childID},{});const defs=await(await request.get("/v1/definitions",{headers})).json(),child=defs.find((d:any)=>d.ref.kind==="page"&&d.ref.name===childName);childSections[0].text="LATER EMBEDDED CONTENT";await decide(request,"manager","build","build.page.edit",{type:"build.page",id:childID},{sections:childSections});await decide(request,"manager","build","build.page.publish",{type:"build.page",id:childID},{});
 const sections:any[]=[{id:"context",widget:"input",configVersion:1,title:"Parent context"},{id:"result",widget:"input",configVersion:1,title:"Parent result"},...["module","custom","dashboard"].map(kind=>({id:kind,widget:"embedded-page",configVersion:1,title:`Original ${kind}`,embedding:{kind,page:{ref:child.ref,sourceVersion:child.version},contentVersion:child.contentVersion,interfaceVersion:1,inputs:{context:{variable:"context"}},results:{note:"result"}}}))],document={formatVersion:2,uiProfile:pageUIProfile,root:"root",nodes:nodes(sections),variables:{context:{scope:"page",type:"string",mode:"state",initial:"FIRST"},result:{scope:"page",type:"string",mode:"state",initial:"No result"}}};await decide(request,"manager","build","build.page.create",{type:"build.page",id:parentID},{name:`${name}parent`,title:"Embedded original pages",object:type,sections,document});
 await open(page,"manager",`/compose?id=${parentID}`);await page.getByRole("region",{name:"Widgets and layout",exact:true}).getByRole("button",{name:"Original module",exact:true}).click();const inspector=page.getByRole("region",{name:"The widget in hand",exact:true});await expect(inspector.getByRole("textbox",{name:"Exact page content version",exact:true})).toHaveValue(child.contentVersion);await page.getByRole("button",{name:"Review release",exact:true}).click();await page.getByRole("button",{name:"Check draft and dependencies",exact:true}).click();await page.getByRole("button",{name:"Save immutable candidate",exact:true}).click();await page.getByRole("button",{name:"Activate release",exact:true}).click();
 const runtime=await page.context().newPage();await stableReadRevision(runtime);await open(runtime,"desk",`/page?app=build&kind=page&name=${name}parent`);const section=(kind:string)=>runtime.getByRole("heading",{name:`Original ${kind}`,exact:true,level:3}).locator(".."),module=section("module"),custom=section("custom"),dashboard=section("dashboard");for(const view of [module,custom,dashboard]){await expect(view).toContainText("ORIGINAL EMBEDDED CONTENT");await expect(view).not.toContainText("LATER EMBEDDED CONTENT");await expect(view.getByRole("textbox",{name:"Child note",exact:true})).toHaveValue("Initial child note");}
 await module.getByRole("textbox",{name:"Child note",exact:true}).fill("Module local draft");await expect(custom.getByRole("textbox",{name:"Child note",exact:true})).toHaveValue("Initial child note");await module.getByRole("button",{name:"Return child note",exact:true}).click();await expect(runtime.getByRole("textbox",{name:"Parent result",exact:true})).toHaveValue("Module local draft");await expect(module.getByRole("textbox",{name:"Child note",exact:true})).toHaveValue("Module local draft");await runtime.getByRole("textbox",{name:"Parent context",exact:true}).fill("SECOND");await expect(module.getByRole("textbox",{name:"Child note",exact:true})).toHaveValue("Initial child note");
 if(process.env.PLATFORM_SCREENSHOTS){await module.screenshot({path:info.outputPath("embedded-module.png")});await runtime.setViewportSize({width:390,height:844});await runtime.evaluate(()=>new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve()))));await expect(dashboard.getByRole("textbox",{name:"Child note",exact:true})).toBeVisible();await dashboard.screenshot({path:info.outputPath("embedded-dashboard-narrow.png")});}
});
