import {expect,test} from "@playwright/test";
import {readFileSync} from "node:fs";
import {decide,fresh,open,pageUIProfile} from "./host";

test("imported inline editing freezes original patch fields and preserves row conflicts without granting field or record writes",async({page,request},info)=>{
 test.setTimeout(90_000);
 const m=JSON.parse(readFileSync(new URL("../../packages/build/src/workshop/module-import/sample.workshop.json",import.meta.url),"utf8")),name=fresh("celledit").replace(/[^a-z0-9]/gi,"").toLowerCase(),type=`build.${name}`,object=fresh("OBJ"),id=fresh("PAGE");
 await decide(request,"manager","build","build.object.create",{type:"build.object",id:object},{name,title:"Cell notes",fields:[{name:"note",title:"Note",type:"text"},{name:"guard",title:"Protected",type:"text",write:["builder"]}],access:[{role:"user",read:"all",create:true,edit:true},{role:"supervisor",read:"all"}],states:[{name:"open",title:"Open"},{name:"done",title:"Done"}],actions:[{name:"close",title:"Close note",from:["open"],to:"done"}]});await decide(request,"manager","build","build.object.publish",{type:"build.object",id:object},{});await decide(request,"manager","platform","platform.member.grant",{type:"platform.member",id:"business-supervisor-1"},{app:"build",role:"supervisor"});
 for(const suffix of ["A","B"])await decide(request,"manager","build",`${type}.create`,{type,id:`${name}${suffix}`},{note:`CELL-${suffix}`,guard:"Protected value"});
 await decide(request,"manager","build","build.page.create",{type:"build.page",id},{name,title:"Cell import",object:type,sections:[{id:"help",widget:"text",configVersion:1,text:"Original"}],document:{formatVersion:2,uiProfile:pageUIProfile,root:"root",nodes:{root:{kind:"rows",children:["help"]},help:{kind:"widget",section:"help"}}}});
 m.widgets.table.config.enableInlineEdit=true;m.widgets.table.config.columns.push({key:"guard",label:"Protected"});m.widgets.detail.config.properties.push("guard");
 await open(page,"manager",`/compose?id=${id}`);await page.getByRole("button",{name:"Import Workshop module",exact:true}).click();const dialog=page.getByRole("dialog",{name:"Import Workshop module",exact:true});await dialog.getByRole("textbox",{name:"Source module JSON",exact:true}).fill(JSON.stringify(m));await dialog.getByRole("combobox",{name:"Map object Asset",exact:true}).selectOption(type);await dialog.getByRole("combobox",{name:"Map field Asset.name",exact:true}).selectOption("note");await dialog.getByRole("combobox",{name:"Map field Asset.guard",exact:true}).selectOption("guard");await dialog.getByRole("combobox",{name:"Map action finishAsset",exact:true}).selectOption(`${type}.close`);await dialog.getByRole("combobox",{name:"Map table edit action Imported notes",exact:true}).selectOption(`${type}.edit`);await expect(dialog.getByRole("button",{name:"Apply imported page draft",exact:true})).toBeDisabled();const fields=dialog.getByRole("group",{name:"Editable table fields",exact:true});await fields.getByRole("button",{name:"Note",exact:true}).click();await fields.getByRole("button",{name:"Protected",exact:true}).click();await dialog.getByRole("checkbox").check();await dialog.getByRole("button",{name:"Apply imported page draft",exact:true}).click();
 const preview=page.getByRole("heading",{name:"Imported notes",exact:true}).locator("..");await preview.getByRole("button",{name:"Edit cells",exact:true}).click();await expect(preview.getByRole("button",{name:"Submit cell edits",exact:true})).toBeDisabled();await preview.getByRole("button",{name:"Cancel cell edits",exact:true}).click();
 await page.getByRole("button",{name:"Save",exact:true}).click();let saved:any;await expect.poll(async()=>{saved=(await(await request.get(`/v1/records/build.page/${id}`,{headers:{Authorization:"Bearer manager"}})).json()).record;return saved.sections?.find((s:any)=>s.widget==="table")?.inlineEdit?.fields;}).toEqual(["note","guard"]);
 await page.getByRole("button",{name:"Review release",exact:true}).click();await page.getByRole("button",{name:"Check draft and dependencies",exact:true}).click();await page.getByRole("button",{name:"Save immutable candidate",exact:true}).click();delete saved.sections.find((s:any)=>s.widget==="table").inlineEdit;await decide(request,"manager","build","build.page.edit",{type:"build.page",id},{sections:saved.sections});await page.getByRole("button",{name:"Activate release",exact:true}).click();
 const runtime=await page.context().newPage();await open(runtime,"desk",`/page?app=build&kind=page&name=${name}`);const table=runtime.getByRole("heading",{name:"Imported notes",exact:true}).locator("..");await table.getByRole("button",{name:"Edit cells",exact:true}).click();
 const stage=async(old:string,value:string)=>{const cell=table.getByRole("cell",{name:old,exact:true});await cell.dblclick();const input=table.getByRole("table").getByRole("textbox");await input.fill(value);await input.press("Enter");};
 await stage("CELL-A","A staged");await stage("CELL-B","B staged");const readonly=table.getByRole("cell",{name:"Protected value",exact:true}).first();await readonly.dblclick();await expect(readonly.getByRole("textbox")).toHaveCount(0);
 await decide(request,"manager","build",`${type}.edit`,{type,id:`${name}B`},{note:"B remote"});await table.getByRole("button",{name:"Submit cell edits",exact:true}).click();await expect(table.getByRole("alert")).toContainText(/CONFLICT|revision|changed/i);await expect(table.getByRole("cell",{name:"B staged",exact:true})).toBeVisible();await expect.poll(async()=>(await(await request.get(`/v1/records/${type}/${name}A`,{headers:{Authorization:"Bearer desk"}})).json()).record.note).toBe("A staged");await expect.poll(async()=>(await(await request.get(`/v1/records/${type}/${name}B`,{headers:{Authorization:"Bearer desk"}})).json()).record.note).toBe("B remote");
 if(process.env.PLATFORM_SCREENSHOTS){await table.screenshot({path:info.outputPath("table-edit-conflict.png")});await runtime.setViewportSize({width:390,height:844});await runtime.evaluate(()=>new Promise<void>(r=>requestAnimationFrame(()=>requestAnimationFrame(()=>r()))));await table.screenshot({path:info.outputPath("table-edit-conflict-narrow.png")});}
 await table.getByRole("button",{name:"Cancel cell edits",exact:true}).click();await table.getByRole("button",{name:"Edit cells",exact:true}).click();await stage("B remote","B retry");await table.getByRole("button",{name:"Submit cell edits",exact:true}).click();await expect.poll(async()=>(await(await request.get(`/v1/records/${type}/${name}B`,{headers:{Authorization:"Bearer desk"}})).json()).record.note).toBe("B retry");
 await expect(decide(request,"desk","build",`${type}.edit`,{type,id:`${name}A`},{guard:"Forbidden"})).rejects.toThrow();await runtime.reload();await expect(table.getByRole("button",{name:"Cancel cell edits",exact:true})).toHaveCount(0);await expect(table.getByRole("cell",{name:"B retry",exact:true})).toBeVisible();
 const reader=await page.context().newPage();await open(reader,"business-supervisor",`/page?app=build&kind=page&name=${name}`);await expect(reader.getByRole("cell",{name:"B retry",exact:true})).toBeVisible();await expect(reader.getByRole("button",{name:"Edit cells",exact:true})).toHaveCount(0);
});
