import {expect,test} from "@playwright/test";
import {decide,fresh,open,pageUIProfile} from "./host";

test("copied tabs keep their own panel identities, toolbar commands and visited action drafts through frozen activation",async({page,request},testInfo)=>{
 test.setTimeout(90_000);
 const name=fresh("tabcopy").replace(/[^a-z0-9]/gi,"").toLowerCase(),type=`build.${name}`,object=fresh("OBJ"),id=fresh("PAGE"),record=fresh("WORK");
 await decide(request,"manager","build","build.object.create",{type:"build.object",id:object},{name,title:"Tabbed work",fields:[{name:"title",title:"Title",type:"text"}],states:[{name:"open",title:"Open"},{name:"done",title:"Done"}],actions:[{name:"finish",title:"Finish tabbed work",from:["open"],to:"done",inputs:[{name:"reason",title:"Completion reason",type:"text",required:true}]}]});await decide(request,"manager","build","build.object.publish",{type:"build.object",id:object},{});await decide(request,"desk","build",`${type}.create`,{type,id:record},{title:"TAB-COPY-WORK"});
 await decide(request,"manager","build","build.page.create",{type:"build.page",id},{name,title:"Tab copy desk",object:type,sections:[{id:"toScratch",widget:"button",configVersion:1,title:"Show scratch"},{id:"toWork",widget:"button",configVersion:1,title:"Show work"},{id:"shared",widget:"input",configVersion:1,title:"Shared input"},{id:"business",widget:"input",configVersion:1,title:"Business text"},{id:"table",widget:"table",configVersion:1,title:"Work records",fields:["title","state"]},{id:"detail",widget:"detail",configVersion:1,title:"Selected work",fields:["title","state"]},{id:"action",widget:"inline-action",configVersion:1,title:"Work form",actions:[`${type}.finish`]},{id:"scratchInput",widget:"input",configVersion:1,title:"Scratch text"},{id:"guide",widget:"text",configVersion:1,text:"Scratch panel active"}],document:{formatVersion:2,uiProfile:pageUIProfile,root:"root",nodes:{root:{kind:"rows",title:"Page root",children:["block"]},block:{kind:"flow",title:"Tabbed block",align:"center",children:["commands","views","guide"]},commands:{kind:"toolbar",title:"View commands",align:"between",children:["toScratch","toWork","shared","business"]},toScratch:{kind:"widget",section:"toScratch"},toWork:{kind:"widget",section:"toWork"},shared:{kind:"widget",section:"shared",valueVariable:"external"},business:{kind:"widget",section:"business",valueVariable:"businessText"},views:{kind:"tabs",title:"Notebook views",activeVariable:"active",children:["work","scratch"]},work:{kind:"rows",title:"Work",children:["table","detail","action"]},table:{kind:"widget",section:"table"},detail:{kind:"widget",section:"detail"},action:{kind:"widget",section:"action"},scratch:{kind:"rows",title:"Scratch",children:["scratchInput"]},scratchInput:{kind:"widget",section:"scratchInput",valueVariable:"draft"},guide:{kind:"widget",section:"guide",visibleWhen:"showScratch"}},variables:{active:{scope:"page",type:"string",mode:"state",initial:"work"},draft:{scope:"page",type:"string",mode:"state",initial:"seed"},businessText:{scope:"page",type:"string",mode:"state",initial:"scratch"},external:{scope:"page",type:"string",mode:"state",initial:"shared"},showScratch:{scope:"page",type:"boolean",mode:"derived",expression:{op:"equal",args:[{variable:"active"},{literal:"scratch"}]}}},interface:{version:1,outputs:{shared:{variable:"external",type:"string"}}},events:[{source:"toScratch",event:"click",target:"active",value:"scratch"},{source:"toWork",event:"click",target:"active",value:"work"}]}});
 await open(page,"manager",`/compose?id=${id}`);const tree=page.getByRole("region",{name:"Widgets and layout",exact:true}),inspector=page.getByRole("region",{name:"The widget in hand",exact:true});
 await tree.getByRole("button",{name:"Commands for Tabbed block",exact:true}).click();await page.getByRole("menuitem",{name:"Copy layout",exact:true}).click();await expect(page.getByRole("button",{name:"Save",exact:true})).toBeDisabled();await tree.getByRole("button",{name:"Commands for Page root",exact:true}).click();await page.getByRole("menuitem",{name:"Paste layout",exact:true}).click();await expect(inspector.getByRole("combobox",{name:"Layout",exact:true})).toHaveValue("flow");await inspector.getByRole("textbox",{name:"Container title",exact:true}).fill("Copied tabbed block");
 await page.getByRole("button",{name:"Undo",exact:true}).click();await page.getByRole("button",{name:"Undo",exact:true}).click();await expect(tree.getByRole("button",{name:"Commands for Notebook views",exact:true})).toHaveCount(1);await page.getByRole("button",{name:"Redo",exact:true}).click();await page.getByRole("button",{name:"Redo",exact:true}).click();await expect(tree.getByRole("button",{name:"Commands for Notebook views",exact:true})).toHaveCount(2);
 if(process.env.PLATFORM_SCREENSHOTS){await tree.getByRole("button",{name:"Commands for Copied tabbed block",exact:true}).click();await page.getByRole("menuitem",{name:"Select layout",exact:true}).click();await inspector.screenshot({path:testInfo.outputPath("tab-copy-inspector.png")});}
 await page.getByRole("button",{name:"Save",exact:true}).click();await expect(page.getByRole("button",{name:"Save",exact:true})).toBeDisabled();const saved=(await(await request.get(`/v1/records/build.page/${id}`,{headers:{Authorization:"Bearer manager"}})).json()).record;
 const copyBlock=saved.document.nodes.root.children[1],copyViews=saved.document.nodes[copyBlock].children.find((id:string)=>saved.document.nodes[id].kind==="tabs"),copyActive=saved.document.nodes[copyViews].activeVariable,copyChildren=saved.document.nodes[copyViews].children;
 expect(saved.document.variables[copyActive].initial).toBe(copyChildren[0]);expect(saved.document.variables[copyActive].initial).not.toBe("work");expect(saved.document.nodes[copyBlock].align).toBe("center");expect(saved.document.nodes[saved.document.nodes[copyBlock].children[0]].align).toBe("between");expect(saved.document.events.filter((e:any)=>e.target===copyActive).map((e:any)=>e.value).sort()).toEqual([...copyChildren].sort());
 await page.getByRole("button",{name:"Review release",exact:true}).click();await page.getByRole("button",{name:"Check draft and dependencies",exact:true}).click();await page.getByRole("button",{name:"Save immutable candidate",exact:true}).click();saved.document.variables[copyActive].initial=copyChildren[1];saved.document.nodes[copyBlock].align="end";await decide(request,"manager","build","build.page.edit",{type:"build.page",id},{document:saved.document});await page.getByRole("button",{name:"Activate release",exact:true}).click();
 const operation=await page.context().newPage();await open(operation,"desk",`/page?app=build&kind=page&name=${name}`);const lists=operation.getByRole("tablist",{name:"Notebook views",exact:true}),original=lists.nth(0).locator(".."),copy=lists.nth(1).locator(".."),commands=operation.getByRole("toolbar",{name:"View commands",exact:true});
 await expect(original.getByRole("tab",{name:"Work",exact:true})).toHaveAttribute("aria-selected","true");await expect(copy.getByRole("tab",{name:"Work",exact:true})).toHaveAttribute("aria-selected","true");await expect(operation.getByText("Scratch panel active",{exact:true})).toHaveCount(0);await expect(operation.getByRole("textbox",{name:"Business text",exact:true}).nth(1)).toHaveValue("scratch");await operation.getByRole("textbox",{name:"Shared input",exact:true}).nth(1).fill("Shared across tab copies");await expect(operation.getByRole("textbox",{name:"Shared input",exact:true}).nth(0)).toHaveValue("Shared across tab copies");
 await original.getByRole("row").filter({hasText:"TAB-COPY-WORK"}).click();await original.getByRole("textbox",{name:"Completion reason *",exact:true}).fill("Original action draft");await expect(copy.getByRole("heading",{name:"Selected work",exact:true}).locator("..")).toContainText("Select a record to see it here.");await copy.getByRole("row").filter({hasText:"TAB-COPY-WORK"}).click();await copy.getByRole("textbox",{name:"Completion reason *",exact:true}).fill("Copied action draft");
 await commands.nth(1).getByRole("button",{name:"Show scratch",exact:true}).click();await expect(copy.getByRole("tab",{name:"Scratch",exact:true})).toHaveAttribute("aria-selected","true");await expect(original.getByRole("tab",{name:"Work",exact:true})).toHaveAttribute("aria-selected","true");await copy.getByRole("textbox",{name:"Scratch text",exact:true}).fill("Copied scratch draft");await expect(operation.getByText("Scratch panel active",{exact:true})).toHaveCount(1);await commands.nth(1).getByRole("button",{name:"Show work",exact:true}).click();await expect(copy.getByRole("textbox",{name:"Completion reason *",exact:true})).toHaveValue("Copied action draft");await expect(operation.getByText("Scratch panel active",{exact:true})).toHaveCount(0);
 await copy.getByRole("tab",{name:"Scratch",exact:true}).click();await expect(copy.getByRole("textbox",{name:"Scratch text",exact:true})).toHaveValue("Copied scratch draft");await original.getByRole("tab",{name:"Scratch",exact:true}).click();await expect(original.getByRole("textbox",{name:"Scratch text",exact:true})).toHaveValue("seed");await original.getByRole("textbox",{name:"Scratch text",exact:true}).fill("Original scratch draft");await commands.nth(1).getByRole("button",{name:"Show work",exact:true}).click();await copy.getByRole("button",{name:"Finish tabbed work",exact:true}).click();await expect(copy.getByRole("heading",{name:"Selected work",exact:true}).locator("..").getByText("Done",{exact:true})).toBeVisible();await expect(original.getByRole("textbox",{name:"Scratch text",exact:true})).toHaveValue("Original scratch draft");await commands.nth(0).getByRole("button",{name:"Show work",exact:true}).click();await expect(original.getByRole("textbox",{name:"Completion reason *",exact:true})).toHaveValue("Original action draft");
 if(process.env.PLATFORM_SCREENSHOTS){await operation.setViewportSize({width:1280,height:1200});await expect(copy.getByRole("row").filter({hasText:"TAB-COPY-WORK"})).toBeVisible();await copy.screenshot({path:testInfo.outputPath("tab-copy-runtime.png")});await operation.setViewportSize({width:390,height:844});await operation.evaluate(()=>new Promise<void>(r=>requestAnimationFrame(()=>requestAnimationFrame(()=>r()))));await lists.nth(1).scrollIntoViewIfNeeded();await lists.nth(1).screenshot({path:testInfo.outputPath("tab-copy-runtime-narrow.png")});await copy.getByRole("heading",{name:"Selected work",exact:true}).locator("..").screenshot({path:testInfo.outputPath("tab-copy-detail-narrow.png")});await copy.getByRole("heading",{name:"Work form",exact:true}).locator("..").screenshot({path:testInfo.outputPath("tab-copy-action-narrow.png")});}
 await operation.reload();await expect(copy.getByRole("tab",{name:"Work",exact:true})).toHaveAttribute("aria-selected","true");await copy.getByRole("tab",{name:"Scratch",exact:true}).click();await expect(copy.getByRole("textbox",{name:"Scratch text",exact:true})).toHaveValue("seed");await expect(original.getByRole("tab",{name:"Work",exact:true})).toHaveAttribute("aria-selected","true");
});
