import {defaultOverviewFixture} from '../../packages/build/src/module-import/default-overview.fixture.mjs';
import {defaultAnalyticsCompleteFixture} from '../../packages/build/src/module-import/default-analytics.fixture.mjs';
import {execFileSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import {defaultMaintenanceFixture} from '../../packages/build/src/module-import/default-maintenance.fixture.mjs';
import {defaultMapFixture} from '../../packages/build/src/module-import/default-map.fixture.mjs';
import {defaultWorkflowFixture} from '../../packages/build/src/module-import/default-workflow.fixture.mjs';
import {defaultTelemetryFixture} from '../../packages/build/src/module-import/default-telemetry.fixture.mjs';
import {expect,test} from '@playwright/test';
import {createServer} from 'node:http';
import {readFileSync} from 'node:fs';
import {decide,fresh,open,pageUIProfile,stableReadRevision} from './host';
const source=readFileSync(new URL('../../packages/build/src/module-import/default.workshop.json',import.meta.url),'utf8'),original=JSON.parse(source);
test('complete seven-page Workshop shares original actions computation attachments and telemetry across one frozen release',async({page,request},info)=>{
 test.setTimeout(480_000);page.setDefaultTimeout(10_000);
 let parent=fresh('PAGE');
 const name=fresh('operations').replace(/[^a-z0-9]/gi,'').toLowerCase(),type=`build.${name}`,operator=`${type}operator`,work=`${type}work`,sensor=`${type}sensor`,alert=`${type}alert`,obj=fresh('OBJ'),op=fresh('OBJ'),wo=fresh('OBJ'),overview=fresh('PAGE'),analytics=fresh('PAGE'),maintenance=fresh('PAGE'),mapPage=fresh('PAGE'),workflow=fresh('PAGE'),telemetry=fresh('PAGE'),code=fresh('CODE'),chat=fresh('FN'),modelFile=fresh('FILE'),contextQuery=fresh('QUERY'),sampleObject=fresh('OBJ'),sampleQuery=fresh('QUERY'),sample=`${type}sample`,openQuery=fresh('QUERY'),app=fresh('APP'),fn=fresh('FN'),provider=fresh('provider').replace(/[^a-z0-9]/gi,''),headers={Authorization:'Bearer manager'},desk={Authorization:'Bearer desk'},calls:any[]=[];
 const server=createServer(async(req,res)=>{let body='';for await(const chunk of req)body+=chunk;const raw=JSON.parse(body),input=JSON.parse(raw.messages.find((m:any)=>m.role==='user').content);calls.push(input);res.setHeader('Content-Type','application/json');res.end(JSON.stringify({choices:[{message:{content:JSON.stringify(input.record?{reply:`Protocol fixture: ${input.record.name} · ${input.question}`}:{summary:`Protocol fixture: ${input.name}`})}}],usage:{prompt_tokens:10,completion_tokens:12,cost:.001}}));});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const address=server.address();if(!address||typeof address==='string')throw Error('fixture address');
 try{
 await decide(request,'manager','platform','platform.member.grant',{type:'platform.member',id:'manager-1'},{app:'ai',role:'admin'});await decide(request,'manager','ai','ai.provider.add',{type:'ai.provider',id:provider},{kind:'local',baseUrl:`http://127.0.0.1:${address.port}`,wire:'openai'});await decide(request,'manager','ai','ai.model.enable',{type:'ai.model',id:`${provider}/probe`},{access:'users'});
 const liveSignals=Array.from({length:100},(_,i)=>({sourceIndex:i,field:({0:'vibration',10:'temperature',20:'pressure',60:'speed',70:'current'} as Record<number,string>)[i]??`signal${i}`,unit:i===0?'mm/s':i===10?'C':i===20?'bar':i===60?'rpm':i===70?'A':''}));
 const stages=['Active','Warning','Maintenance','Offline'],states=[...stages,'Decommissioned'].map(title=>({name:title.toLowerCase(),title})),fields=[{name:'name',title:'Name',type:'text',search:true},{name:'priority',title:'Priority',type:'choice',choices:'Low,High'},{name:'owner',title:'Owner',type:'text'},...['pressure','temperature','availability','openalerts','revenueimpact','latitude','longitude'].map(name=>({name,title:name,type:'integer'})),{name:'model',title:'Model',type:'text'},{name:'installedat',title:'Installed at',type:'date'},{name:'lastinspection',title:'Last inspection',type:'datetime'},{name:'nextmaintenance',title:'Next maintenance',type:'date'}];
 await decide(request,'manager','build','build.object.create',{type:'build.object',id:obj},{name,title:'Original operations assets',fields,states});await decide(request,'manager','build','build.object.publish',{type:'build.object',id:obj},{});
 await decide(request,'manager','build','build.object.create',{type:'build.object',id:op},{name:`${name}operator`,title:'Business operators',fields:[{name:'name',title:'Name',type:'text',search:true}]});await decide(request,'manager','build','build.object.publish',{type:'build.object',id:op},{});await decide(request,'desk','build',`${operator}.create`,{type:operator,id:'OP'},{name:'Business operator'});
 for(const [id,t,title]of [[wo,work,'Work orders'],[fresh('OBJ'),sensor,'Sensors'],[fresh('OBJ'),alert,'Alerts']]){await decide(request,'manager','build','build.object.create',{type:'build.object',id:id!},{name:t!.slice(6),title,...t===alert?{states:[{name:'open',title:'Open'},{name:'closed',title:'Closed'}],actions:[{name:'close',title:'Close alert',from:['open'],to:'closed'}]}:{},fields:[{name:'asset',title:'Asset',type:'reference',ref:type,inverse:t===work?'work':t===sensor?'sensors':'alerts'},{name:'label',title:'Label',type:'text'},...t===alert?[{name:'occurred',title:'Occurred',type:'datetime'},{name:'severity',title:'Severity',type:'choice',choices:'Low,High'}]:[],...t===work?[{name:'operator',title:'Operator',type:'reference',ref:operator,required:true},{name:'title',title:'Title',type:'text',required:true},{name:'due',title:'Due',type:'date',required:true},{name:'status',title:'Status',type:'choice',choices:'Open,Done'},{name:'assignee',title:'Assignee',type:'text'},{name:'started',title:'Started',type:'datetime'},{name:'finished',title:'Finished',type:'datetime'}]:[]]});await decide(request,'manager','build','build.object.publish',{type:'build.object',id:id!},{});}
 await decide(request,'manager','build','build.object.create',{type:'build.object',id:sampleObject},{name:sample.slice(6),title:'Original business samples',fields:[{name:'eventtime',title:'Event time',type:'datetime'},...liveSignals.map(signal=>({name:signal.field,title:signal.field,type:'integer'})),{name:'availability',title:'Availability',type:'integer'},{name:'asset',title:'Asset',type:'reference',ref:type},{name:'plant',title:'Plant',type:'text'},{name:'device',title:'Device',type:'text'},{name:'status',title:'Status',type:'choice',choices:'normal,warning'}]});await decide(request,'manager','build','build.object.publish',{type:'build.object',id:sampleObject},{});
 await decide(request,'manager','build','build.query.create',{type:'build.query',id:sampleQuery},{name:`${name}history`,title:'Original sample history',description:'Original business event time',object:sample,sort:['-eventtime','id'],limit:100});await decide(request,'manager','build','build.query.publish',{type:'build.query',id:sampleQuery},{});
 await decide(request,'manager','build','build.query.create',{type:'build.query',id:contextQuery},{name:`${name}assethistory`,title:'Original asset history',description:'Actual asset reference and event time',object:sample,by:'asset',sort:['-eventtime','id'],limit:100});await decide(request,'manager','build','build.query.publish',{type:'build.query',id:contextQuery},{});
 const active=stages.map(s=>s.toLowerCase());await decide(request,'manager','build','build.object.edit',{type:'build.object',id:obj},{actions:[{name:'update',title:'Update asset status',from:active,toInput:'status',inputs:[{name:'status',title:'Status',type:'choice',choices:active.join(','),required:true},{name:'priority',title:'Priority',type:'choice',choices:'Low,High'},{name:'owner',title:'Owner',type:'text'}],sets:[{field:'priority',from:'priority'},{field:'owner',from:'owner'},{field:'lastinspection',from:'$now'}],conditions:[{when:{field:'input.status',operator:'=',value:'offline'},field:'input.priority',operator:'=',value:'High',message:'Offline requires High priority'}]},{name:'schedule',title:'Create work order',from:active,inputs:[{name:'title',title:'Title',type:'text',required:true,minLength:4},{name:'operator',title:'Operator',type:'reference',ref:operator,required:true},{name:'due',title:'Due',type:'date',required:true}],conditions:[{field:'state',operator:'!=',value:'offline',message:'Cannot schedule work on an Offline asset'}],creates:[{object:work,via:'asset',sets:[{field:'title',from:'title'},{field:'operator',from:'operator'},{field:'due',from:'due'},{field:'status',from:'=Open'}]}]}]});await decide(request,'manager','build','build.object.publish',{type:'build.object',id:obj},{});
 for(let n=0;n<102;n++){const id=n<2?['A','B'][n]!: `C${String(n).padStart(3,'0')}`;await decide(request,'desk','build',`${type}.create`,{type,id},{name:n<2?`Original ${id}`:`Baseline ${n}`,priority:'Low',owner:n<2?`Owner ${id}`:'Baseline owner',pressure:id==='A'?20:id==='B'?80:40+n,temperature:id==='A'?90:id==='B'?60:120+n,availability:id==='B'?100:80,openalerts:0,revenueimpact:id==='B'?2000:1000,latitude:id==='B'?31:37,longitude:id==='B'?121:-122,model:'Original model',installedat:'2020-01-01',nextmaintenance:'2026-10-10'});}await decide(request,'desk','build',`${type}.update`,{type,id:'B'},{status:'warning',priority:'Low',owner:'Owner B'});
 for(let n=0;n<3;n++)await decide(request,'desk','build',`${sample}.create`,{type:sample,id:`S${n}`},{eventtime:`2026-10-04T0${n}:00:00Z`,...Object.fromEntries(liveSignals.map(signal=>[signal.field,signal.sourceIndex===0?10+n:signal.sourceIndex===10?80+n:20+n])),availability:90+n,asset:n===2?'B':'A',plant:'Plant 1',device:'Device 1',status:'normal'});
 for(const t of [sensor,alert,work])await decide(request,'desk','build',`${t}.create`,{type:t,id:'REL-B'},{asset:'B',label:`Related ${t===sensor?'sensor':t===alert?'alert':'work'}`,...t===alert?{occurred:'2026-10-04T01:00:00Z',severity:'High'}:{},...t===work?{operator:'OP',title:'Existing original work',due:'2026-10-10',status:'Open',assignee:'Business operator',started:'2026-10-04T00:00:00Z',finished:'2026-10-06T00:00:00Z'}:{}});
 for(const id of ['OPEN-2','OPEN-3'])await decide(request,'desk','build',`${alert}.create`,{type:alert,id},{asset:'B',label:`Original open alert ${id}`,occurred:'2026-10-04T02:00:00Z',severity:'Low'});
 await decide(request,'desk','build',`${alert}.create`,{type:alert,id:'CLOSED'},{asset:'A',label:'Closed original alert'});await decide(request,'desk','build',`${alert}.close`,{type:alert,id:'CLOSED'},{});
 await decide(request,'manager','build','build.query.create',{type:'build.query',id:openQuery},{name:`${name}openalerts`,title:'Original open alerts',description:'Open-state predicate',object:alert,domain:[['state','=','open']],limit:100});await decide(request,'manager','build','build.query.publish',{type:'build.query',id:openQuery},{});
 await decide(request,'manager','build','build.function.create',{type:'build.function',id:fn},{name:`${name}advice`,title:'Original fixed advice',description:'Protocol fixture',object:type,fields:['name'],instructions:'Use only the original authorized record.',output:[{name:'summary',type:'string',description:'Typed advice',required:true}],model:`${provider}/probe`,maxInputBytes:4096,maxOutputBytes:1024,maxTokens:256,roles:['builder','user']});await decide(request,'manager','build','build.function.publish',{type:'build.function',id:fn},{});
 await decide(request,'manager','build','build.function.create',{type:'build.function',id:chat},{name: name+'chat',title:'Original conversation',description:'Local HTTP protocol fixture',object:type,fields:['name'],conversation:true,instructions:'Use only authorized original context.',output:[{name:'reply',type:'string',description:'Typed reply',required:true}],model:provider+'/probe',maxInputBytes:8192,maxOutputBytes:1024,maxTokens:256,roles:['builder','user']});await decide(request,'manager','build','build.function.publish',{type:'build.function',id:chat},{});
 const numeric={type:'object',properties:{pressure:{type:'number'},temperature:{type:'number'},availability:{type:'number'}},required:['pressure','temperature','availability']};
 await decide(request,'manager','build','build.code.create',{type:'build.code',id:code},{name:name+'probe',title:'Numeric protocol probe',description:'Returns authorized pressure to verify the real Go/Wasm binding; this is not a business risk model.',language:'go',source:'package main\nfunc Run(input Input)(Output,error){return Output{Risk:input.Pressure},nil}',input:numeric,output:{type:'object',properties:{risk:{type:'number'}},required:['risk']},roles:['builder','user'],limits:{timeoutMillis:2000,memoryPages:512,maxInputBytes:4096,maxOutputBytes:4096}});
 await decide(request,'manager','build','build.code.compile',{type:'build.code',id:code},{});await expect.poll(async()=>{const r=(await(await request.get('/v1/records/build.code/'+code,{headers})).json()).record;if(r.state==='failed')throw Error(r.diagnostic);return r.state;},{timeout:180_000}).toBe('compiled');
 await open(page,'manager','/release-review?kind=compute&id='+code);await page.getByRole('button',{name:'Check draft and dependencies',exact:true}).click();await page.getByRole('button',{name:'Save immutable candidate',exact:true}).click();await page.getByRole('button',{name:'Activate release',exact:true}).click();
 const model=readFileSync(new URL('../fixtures/industrial-robot-cell.glb',import.meta.url)),upload=await request.post('/v1/files?name=industrial-robot-cell.glb',{headers:{...headers,'Content-Type':'model/gltf-binary'},data:model});expect(upload.ok()).toBeTruthy();await decide(request,'manager','files','files.file.attach',{type:'files.file',id:modelFile},{...await upload.json(),target:type+'/A'});
 for(const [suffix,child]of [['work',work],['sensor',sensor],['alert',alert]]){const id=fresh('LINK');await decide(request,'manager','build','build.linktype.create',{type:'build.linktype',id},{name:name+suffix+'link',title:'Original '+suffix,description:'Original asset reference',parent:type,child,via:'asset',forward:suffix==='work'?'work':suffix+'s',reverse:'asset'});await decide(request,'manager','build','build.linktype.publish',{type:'build.linktype',id},{});}
 for(const [id,suffix,title]of [[maintenance,'maintenance','Maintenance'],[mapPage,'map','Map'],[workflow,'workflow','Workflow'],[telemetry,'telemetry','Telemetry']]){await decide(request,'manager','build','build.page.create',{type:'build.page',id:id!},{name:name+suffix,title,object:type,sections:[{id:'initial',widget:'text',configVersion:1,text:'Initial'}],document:{formatVersion:2,uiProfile:pageUIProfile,root:'root',nodes:{root:{kind:'rows',children:['initial']},initial:{kind:'widget',section:'initial'}}}});await decide(request,'manager','build','build.page.publish',{type:'build.page',id:id!},{});}
 await decide(request,'manager','build','build.page.create',{type:'build.page',id:overview},{name:`${name}overview`,title:'Asset Overview',object:type,sections:[{id:'initial',widget:'text',configVersion:1,text:'Initial'}],document:{formatVersion:2,uiProfile:pageUIProfile,root:'root',nodes:{root:{kind:'rows',children:['initial']},initial:{kind:'widget',section:'initial'}}}});await decide(request,'manager','build','build.page.publish',{type:'build.page',id:overview},{});
 await decide(request,'manager','build','build.page.create',{type:'build.page',id:analytics},{name:`${name}analytics`,title:'Analytics selection comparison',object:type,sections:[{id:'initial',widget:'text',configVersion:1,text:'Initial'}],document:{formatVersion:2,uiProfile:pageUIProfile,root:'root',nodes:{root:{kind:'rows',children:['initial']},initial:{kind:'widget',section:'initial'}}}});await decide(request,'manager','build','build.page.publish',{type:'build.page',id:analytics},{});
 const ref={app:'build',kind:'object',name:type};await decide(request,'manager','build','build.app.create',{type:'build.app',id:app},{name:`${name}app`,title:'Original operations desk',pages:[`${name}overview`,`${name}analytics`,`${name}maintenance`,`${name}map`,`${name}workflow`,`${name}telemetry`],uiProfile:pageUIProfile,variables:{record:{scope:'application',type:'record',mode:'resource',source:{kind:'record',object:ref}},records:{scope:'application',type:'record-set',mode:'resource',source:{kind:'record-set',object:ref}},currentPage:{scope:'application',type:'string',mode:'state',initial:'pOperations'},showDetail:{scope:'application',type:'boolean',mode:'state',initial:true}}});await decide(request,'manager','build','build.app.publish',{type:'build.app',id:app},{});
 const defs=await(await request.get('/v1/definitions',{headers})).json(),binding=(kind:string,n:string)=>{const d=defs.find((d:any)=>d.ref.kind===kind&&d.ref.name===n);return {ref:d.ref,sourceVersion:d.version};},appBinding=binding('app',`${name}app`),functionBinding=binding('function',`${name}advice`),queryBinding=binding('query',`${name}openalerts`),historyBinding=binding('query',`${name}history`);
 // Reuse the explicit fixture bindings; the complete-module dialog performs the page writes.
 let saved:any,sharedBindings:any={};
 const mergeBindings=(a:any,b:any):any=>!a||!b||Array.isArray(a)||Array.isArray(b)||typeof a!=='object'||typeof b!=='object'?structuredClone(b):Object.fromEntries([...new Set([...Object.keys(a),...Object.keys(b)])].map(key=>[key,key in b?mergeBindings(a[key],b[key]):a[key]]));
 let liveDefs=await(await request.get('/v1/definitions',{headers})).json();const liveEntities=await(await request.get('/v1/entities',{headers})).json(),liveActions=await(await request.get('/v1/actions',{headers})).json();
 const replacements:Record<string,string>={'build.asset':type,'build.work':work,'build.sensor':sensor,'build.alert':alert,'build.operator':operator,'build.sample':sample,'build.asset.update':type+'.update','build.asset.edit':type+'.edit','build.asset.schedule':type+'.schedule','desk':name+'app','advice':name+'advice','asset-assistant':name+'chat','failure-risk':name+'probe','asset-work':name+'worklink','asset-sensor':name+'sensorlink','asset-alert':name+'alertlink','open-alerts':name+'openalerts','sample-history':name+'history','plant-readings':name+'history','asset-readings':name+'assethistory','overview':name+'overview','fleet-kpis':name+'overview','exposure':'revenueimpact','sum:exposure':'sum:revenueimpact','openAlerts':'openalerts','installedAt':'installedat','lastInspection':'lastinspection','nextMaintenance':'nextmaintenance','at':'eventtime','robot-cell-model':modelFile};
 const rebase=(value:any):any=>typeof value==='string'?replacements[value]??value:Array.isArray(value)?value.map(rebase):value&&typeof value==='object'?Object.fromEntries(Object.entries(value).map(([k,v])=>[k.startsWith('build.')?replacements[k]??k:k,rebase(v)])):value;
 for(const [id,pageID,title,make,count] of [[parent,'pOperations','Operations',defaultOverviewFixture,24],[overview,'pOverview','Asset Overview',defaultOverviewFixture,17],[analytics,'pAnalytics','Analytics',defaultAnalyticsCompleteFixture,30],[maintenance,'pMaintenance','Maintenance',defaultMaintenanceFixture,21],[mapPage,'pMap','Map',defaultMapFixture,17],[workflow,'pWorkflow','Workflow',defaultWorkflowFixture,21],[telemetry,'pTelemetry','Telemetry',defaultTelemetryFixture,15]] as const){
  liveDefs=await(await request.get('/v1/definitions',{headers})).json();const f=make(pageUIProfile),bindings:any=rebase(f.bindings);if(pageID==='pOperations'){bindings.edits.wObjectTable1.fields=['owner'];bindings.application.recordSets={selectedAssets:{variable:'records',writable:true}};}if(pageID==='pOperations')bindings.regions={sOperationsRoot:{maxHeight:960},sDrawerRoot:{maxHeight:640}};
  if(bindings.events?.wTimeline)bindings.events.wTimeline.titleField='label';
  const pin=(value:any):void=>{if(!value||typeof value!=='object')return;if(value.ref&&value.sourceVersion){const d=liveDefs.find((d:any)=>JSON.stringify(d.ref)===JSON.stringify(value.ref));expect(d,'actual retained '+JSON.stringify(value.ref)).toBeTruthy();value.sourceVersion=d.version;}Object.values(value).forEach(pin);};pin(bindings);
  if(bindings.embeddings)for(const embed of Object.values(bindings.embeddings) as any[]){const d=liveDefs.find((d:any)=>JSON.stringify(d.ref)===JSON.stringify(embed.page.ref));embed.contentVersion=d.contentVersion;embed.interfaceVersion=d.page.document?.interface?.version??0;}
  if(pageID==='pTelemetry'&&bindings.observations){for(const b of Object.values(bindings.observations) as any[]){b.signals=liveSignals;b.metadata=b.metadata?{plant:'plant',device:'device',status:'status'}:undefined;}}
  if(bindings.spatial?.wDigitalTwin)bindings.spatial.wDigitalTwin.sampleTimeField='eventtime';
  sharedBindings=mergeBindings(sharedBindings,bindings);
  // Preserve an explicitly published analytic dependency for Quiver.
  if(pageID==='pOverview'){
  const compiled=JSON.parse(execFileSync(process.execPath,[fileURLToPath(new URL('../workshop-compile.mjs',import.meta.url))],{input:JSON.stringify({source,page:pageID,bindings,target:{object:type,profile:pageUIProfile,entities:liveEntities,actions:liveActions,definitions:liveDefs}}),maxBuffer:4*1024*1024,timeout:15_000}).toString());expect(compiled.diagnostics.filter((d:any)=>d.blocking),pageID).toEqual([]);expect(compiled.source).toBe(source);expect(compiled.draft.sections).toHaveLength(count);
   await decide(request,'manager','build','build.page.edit',{type:'build.page',id},{title:original.pages.find((p:any)=>p.id===pageID).name,sections:compiled.draft.sections,selections:compiled.draft.selections,document:compiled.draft.document});await decide(request,'manager','build','build.page.publish',{type:'build.page',id},{});
  }
 }

 sharedBindings.application.recordSets.selectedAssets.writable=true;sharedBindings.edits.wObjectTable1.fields=['owner'];
 await open(page,'manager','/application?id='+app);await page.getByRole('button',{name:'Import complete Workshop module',exact:true}).click();const importer=page.getByRole('dialog',{name:'Import Workshop module',exact:true});await importer.getByLabel('Workshop JSON file',{exact:true}).setInputFiles({name:'original-workshop.json',mimeType:'application/json',buffer:Buffer.from(source)});
 for(const [sourcePage,targetID] of [['pOverview',overview],['pAnalytics',analytics],['pMaintenance',maintenance],['pMap',mapPage],['pWorkflow',workflow],['pTelemetry',telemetry]])await importer.getByRole('combobox',{name:'Destination for '+sourcePage,exact:true}).selectOption(targetID!);
 await importer.getByLabel('Imported page name pOperations',{exact:true}).fill(name+'page');
 await importer.getByLabel('Saved mapping report',{exact:true}).setInputFiles({name:'workshop-mapping-report.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({source,bindings:sharedBindings}))});await expect(importer.getByRole('status').filter({hasText:'Ready pages: 7 of 7'})).toBeVisible();await importer.getByRole('checkbox',{name:'I reviewed all pages and the documented presentation, query and lifetime differences.',exact:true}).check();await importer.getByRole('button',{name:'Save and publish imported pages',exact:true}).click();await expect(importer.getByRole('status').filter({hasText:'Imported pages are ready in the application draft.'})).toBeVisible({timeout:30_000});await importer.getByRole('button',{name:'Close',exact:true}).click();await page.getByRole('button',{name:'Save application',exact:true}).click();await expect(page.getByRole('button',{name:'Save application',exact:true})).toBeDisabled();
 saved=(await(await request.get('/v1/records/build.page?limit=500',{headers})).json()).records.find((p:any)=>p.name===name+'page');expect(saved).toBeTruthy();parent=saved.id;
 for(const [id,count] of [[parent,24],[overview,17],[analytics,30],[maintenance,21],[mapPage,17],[workflow,21],[telemetry,15]]){const stored=(await(await request.get('/v1/records/build.page/'+id,{headers})).json()).record;expect(stored.sections).toHaveLength(count);expect(Object.keys(stored.document.overlays)).toHaveLength(4);expect(stored.document.unusedWidgets).toHaveLength(2);}
 const planTitle=`${name} advice evaluation`;await open(page,'manager','/candidate-test');await page.getByRole('combobox',{name:'Candidate kind'}).selectOption('function');await page.getByRole('combobox',{name:'Saved function draft'}).selectOption(fn);await page.getByRole('textbox',{name:'Test plan name'}).fill(planTitle);await page.getByRole('textbox',{name:'Model identifier'}).fill(`${provider}/probe`);await page.getByRole('checkbox',{name:'Require a measured release evaluation'}).check();await page.getByRole('textbox',{name:'Synthetic input (JSON object)'}).fill(JSON.stringify({name:'Synthetic'}));await page.getByRole('textbox',{name:'Expected typed answer (JSON object)'}).fill(JSON.stringify({summary:'Protocol fixture: Synthetic'}));await page.getByRole('button',{name:'Save test plan'}).click();await expect(page.getByRole('status').filter({hasText:'Test plan saved.'})).toBeVisible();
 await open(page,'manager','/candidate-test');await page.getByRole('combobox',{name:'Candidate kind'}).selectOption('function');await page.getByRole('combobox',{name:'Saved function draft'}).selectOption(chat);await page.getByRole('textbox',{name:'Test plan name'}).fill(name+' chat evaluation');await page.getByRole('textbox',{name:'Model identifier'}).fill(provider+'/probe');await page.getByRole('checkbox',{name:'Require a measured release evaluation'}).check();await page.getByRole('textbox',{name:'Synthetic input (JSON object)'}).fill(JSON.stringify({record:{name:'Synthetic chat'},question:'Protocol evaluation',history:[]}));await page.getByRole('textbox',{name:'Expected typed answer (JSON object)'}).fill(JSON.stringify({reply:'Protocol fixture: Synthetic chat · Protocol evaluation'}));await page.getByRole('button',{name:'Save test plan'}).click();
 await open(page,'manager',`/application?id=${app}`);await page.getByRole('button',{name:'Review application release',exact:true}).click();await page.getByRole('button',{name:'Check draft and dependencies',exact:true}).click();await page.getByRole('button',{name:'Save immutable candidate',exact:true}).click();await expect(page.getByRole('button',{name:'Refresh evaluation reports',exact:true})).toBeEnabled();await page.getByRole('combobox',{name:'Evaluation plan'}).selectOption({label:planTitle});await page.getByRole('button',{name:'Run measured evaluation'}).click();await expect.poll(async()=>{const rows=await(await request.get('/v1/records/build.evaluation?limit=500',{headers})).json();return rows.records.some((r:any)=>r.function===`${name}advice`&&r.state==='passed');}).toBe(true);await page.getByRole('button',{name:'Refresh evaluation reports'}).click();await page.getByRole('combobox',{name:'Evaluation plan'}).selectOption({label:name+' chat evaluation'});await page.getByRole('button',{name:'Run measured evaluation'}).click();await expect.poll(async()=>(await(await request.get('/v1/records/build.evaluation?limit=500',{headers})).json()).records.some((r:any)=>r.function===name+'chat'&&r.state==='passed')).toBe(true);await page.getByRole('button',{name:'Refresh evaluation reports'}).click();await page.getByRole('button',{name:'Activate release',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'Release active for operators.'})).toBeVisible();
 await decide(request,'manager','build','build.query.edit',{type:'build.query',id:openQuery},{domain:[['state','=','closed']]});await decide(request,'manager','build','build.query.publish',{type:'build.query',id:openQuery},{});
 const later=structuredClone(saved.sections);later.forEach((s:any)=>{if(s.actionDefaults)s.actionDefaults=[];if(s.metricPresentation?.annotation)s.metricPresentation.annotation.text='Later draft';});await decide(request,'manager','build','build.page.edit',{type:'build.page',id:parent},{sections:later});
 const runtime=await page.context().newPage();runtime.setDefaultTimeout(10_000);await stableReadRevision(runtime);await open(runtime,'desk',`/page?app=build&kind=page&name=${name}page&application=build:${name}app&instance=main`);await expect(runtime.getByRole('heading',{name:'Assets (102)',exact:true})).toBeVisible();const metric=(title:string)=>runtime.getByRole('heading',{name:title,exact:true,level:3}).locator('..');await expect(metric('Active').getByText('101',{exact:true})).toBeVisible();await expect(metric('Warnings').getByText('1',{exact:true})).toBeVisible();await expect(metric('Active')).toContainText('+3');await expect(runtime.getByText('Later draft',{exact:true})).toHaveCount(0);await expect(runtime.getByRole('heading',{name:'Chart 4 (unused)',exact:true})).toHaveCount(0);await expect(runtime.getByRole('heading',{name:'Object Table 3 (unused)',exact:true})).toHaveCount(0);
 const filters=runtime.getByRole('region',{name:'Filters',exact:true});await filters.getByRole('heading',{name:'Search',exact:true,level:3}).locator('..').getByRole('textbox',{name:'Search',exact:true}).fill('Original B');await expect(runtime.getByRole('heading',{name:'Assets (1)',exact:true})).toBeVisible();await expect(metric('Avg Availability').getByText('100%',{exact:true})).toBeVisible();const table=runtime.getByRole('heading',{name:'Assets (1)',exact:true}).locator('..');await table.getByRole('cell',{name:'Original B',exact:true}).click();const detail=runtime.getByRole('region',{name:'Detail',exact:true});await expect(detail.getByRole('status',{name:'Complete collection count',exact:true})).toHaveText('1');await expect(detail.locator('li[aria-current="step"]')).toHaveText('Warning');await expect(detail.getByRole('cell',{name:'Related sensor',exact:true})).toBeVisible();await table.getByRole('button',{name:'Edit cells',exact:true}).click();await table.getByRole('cell',{name:'Owner B',exact:true}).dblclick();const ownerEdit=table.getByRole('table').getByRole('textbox');await ownerEdit.fill('Table owner B');await ownerEdit.press('Enter');await table.getByRole('button',{name:'Submit cell edits',exact:true}).click();await expect.poll(async()=>(await(await request.get(`/v1/records/${type}/B`,{headers:desk})).json()).record.owner).toBe('Table owner B');await table.getByRole('button',{name:'Cancel cell edits',exact:true}).click();await detail.getByRole('button',{name:'Open Detail',exact:true}).click();let drawer=runtime.getByRole('dialog',{name:'Asset Detail Drawer',exact:true});await expect(drawer.getByRole('status',{name:'Complete collection count',exact:true})).toHaveText('1');await drawer.getByRole('button',{name:'Request original analysis',exact:true}).click();await expect(drawer).toContainText('Protocol fixture: Original B');await drawer.getByRole('button',{name:'Edit Status',exact:true}).click();await expect(drawer).not.toBeVisible();let form=runtime.getByRole('dialog',{name:'Edit Asset Status',exact:true});await expect(form.getByRole('combobox',{name:'Status *',exact:true})).toHaveValue('warning');await expect(form.getByRole('textbox',{name:'Owner',exact:true})).toHaveValue('Table owner B');await form.getByRole('button',{name:'Close',exact:true}).click();await expect(runtime.getByRole('dialog')).toHaveCount(0);
 await detail.getByRole('button',{name:'Take offline…',exact:true}).click();form=runtime.getByRole('dialog',{name:'Confirm Offline',exact:true});await form.getByRole('combobox',{name:'Status *',exact:true}).selectOption('offline');await form.getByRole('button',{name:'Update asset status',exact:true}).click();await expect(form).toContainText('Offline requires High priority');await form.getByRole('combobox',{name:'Priority',exact:true}).selectOption('High');await form.getByRole('button',{name:'Update asset status',exact:true}).click();await expect.poll(async()=>(await(await request.get(`/v1/records/${type}/B`,{headers:desk})).json()).record.state).toBe('offline');await form.getByRole('button',{name:'Close',exact:true}).click();await expect(metric('Offline').getByText('1',{exact:true})).toBeVisible();
 await detail.getByRole('button',{name:'Edit Status',exact:true}).click();form=runtime.getByRole('dialog',{name:'Edit Asset Status',exact:true});await form.getByRole('combobox',{name:'Status *',exact:true}).selectOption('maintenance');await form.getByRole('button',{name:'Update asset status',exact:true}).click();await expect.poll(async()=>(await(await request.get(`/v1/records/${type}/B`,{headers:desk})).json()).record.state).toBe('maintenance');await form.getByRole('button',{name:'Close',exact:true}).click();
 await detail.getByRole('button',{name:'Create Work Order',exact:true}).click();form=runtime.getByRole('dialog',{name:'Create Work Order',exact:true});await form.getByRole('textbox',{name:'Title *',exact:true}).fill('Inspect original B');await form.getByRole('combobox',{name:'Operator *',exact:true}).fill('OP');await form.getByRole('option',{name:'OP · Business operator',exact:true}).click();await form.getByLabel('Due *',{exact:true}).fill('2026-10-10');await form.getByRole('button',{name:'Create work order',exact:true}).click();await expect(form).toContainText('Request submitted.');await expect.poll(async()=>(await(await request.get(`/v1/records/${work}`,{headers:desk})).json()).total).toBe(2);const works=await(await request.get(`/v1/records/${work}`,{headers:desk})).json();expect(works.records.some((r:any)=>r.asset==='B'&&r.operator==='OP'&&r.title==='Inspect original B'&&r.due==='2026-10-10')).toBe(true);if(process.env.PLATFORM_SCREENSHOTS)await form.screenshot({path:info.outputPath('complete-original-create.png')});await form.getByRole('button',{name:'Close',exact:true}).click();
 await filters.getByRole('heading',{name:'Search',exact:true,level:3}).locator('..').getByRole('textbox',{name:'Search',exact:true}).fill('Original A');await expect(runtime.getByRole('heading',{name:'Assets (1)',exact:true})).toBeVisible();await table.getByRole('cell',{name:'Original A',exact:true}).click();await detail.getByRole('button',{name:'Open Detail',exact:true}).click();drawer=runtime.getByRole('dialog',{name:'Asset Detail Drawer',exact:true});await expect(drawer).not.toContainText('Protocol fixture: Original B');await drawer.getByRole('button',{name:'Request original analysis',exact:true}).click();await expect(drawer).toContainText('Protocol fixture: Original A');if(process.env.PLATFORM_SCREENSHOTS)await drawer.screenshot({path:info.outputPath('complete-original-drawer.png')});await drawer.getByRole('button',{name:'Close',exact:true}).click();await filters.getByRole('heading',{name:'Search',exact:true,level:3}).locator('..').getByRole('textbox',{name:'Search',exact:true}).fill('');await expect(runtime.getByRole('heading',{name:'Assets (102)',exact:true})).toBeVisible();if(process.env.PLATFORM_SCREENSHOTS){await runtime.getByRole('heading',{name:'Active',exact:true,level:3}).scrollIntoViewIfNeeded();await runtime.screenshot({path:info.outputPath('complete-original-operations.png')});}const originalTable=runtime.getByRole('heading',{name:'Assets (102)',exact:true}).locator('..');await originalTable.getByRole('cell',{name:'Original B',exact:true}).click();await runtime.getByRole('button',{name:'Asset Overview',exact:true}).click();await expect(runtime.getByRole('heading',{name:'Operational Asset Overview',exact:true})).toBeVisible();const gallery=runtime.getByRole('heading',{name:'Asset Gallery',exact:true,level:3}).locator('..');await expect(gallery.getByRole('button',{name:'Original B',exact:true})).toHaveAttribute('aria-pressed','true');await expect(metric('Revenue at Risk').getByText('$103.0K',{exact:true})).toBeVisible();await expect(metric('Open Alerts').getByText('3',{exact:true})).toBeVisible();await expect(metric('In Filter').getByText('102',{exact:true})).toBeVisible();await gallery.getByRole('button',{name:'Original A',exact:true}).click();await expect(gallery.getByRole('button',{name:'Original A',exact:true})).toHaveAttribute('aria-pressed','true');
 const tabLabel=runtime.getByRole('tab',{name:new RegExp(`${name}page`)});await tabLabel.click();await expect(runtime.getByRole('heading',{name:'Assets (102)',exact:true})).toBeVisible();await expect(detail.getByRole('heading',{name:'Original A',exact:true})).toBeVisible();await detail.getByRole('button',{name:'Edit Status',exact:true}).click();form=runtime.getByRole('dialog',{name:'Edit Asset Status',exact:true});await expect(form.getByRole('textbox',{name:'Owner',exact:true})).toHaveValue('Owner A');await form.getByRole('button',{name:'Close',exact:true}).click();await runtime.getByRole('button',{name:'Asset Overview',exact:true}).click();await expect(gallery.getByRole('button',{name:'Original A',exact:true})).toHaveAttribute('aria-pressed','true');if(process.env.PLATFORM_SCREENSHOTS){await runtime.getByRole('heading',{name:'Operational Asset Overview',exact:true}).scrollIntoViewIfNeeded();await runtime.screenshot({path:info.outputPath('complete-original-overview.png')});}
 await tabLabel.click();await originalTable.getByRole('checkbox',{name:'Select A',exact:true}).check();await originalTable.getByRole('checkbox',{name:'Select B',exact:true}).check();await runtime.getByRole('button',{name:'Analytics',exact:true}).click();const comparison=metric('Compare selected');await expect(metric('Availability SLO')).toContainText('102 records');await expect(metric('Telemetry').getByRole('group',{name:'pressure by original event time',exact:true})).toBeVisible();await expect(metric('Alert Timeline')).toContainText('Original open alert OPEN-2');await expect(metric('Status Waterfall').getByLabel('Active: 101; Σ 101',{exact:true})).toBeVisible();await expect(comparison.getByRole('columnheader').filter({hasText:/Original [AB]/})).toHaveCount(2);await metric('Top revenue exposure').getByRole('button',{name:'Original B',exact:true}).click();await expect(comparison.getByRole('columnheader').filter({hasText:/Original [AB]/})).toHaveCount(2);await tabLabel.click();await detail.getByRole('button',{name:'Edit Status',exact:true}).click();form=runtime.getByRole('dialog',{name:'Edit Asset Status',exact:true});await expect(form.getByRole('textbox',{name:'Owner',exact:true})).toHaveValue('Table owner B');await form.getByRole('button',{name:'Close',exact:true}).click();
 await runtime.getByRole('button',{name:'Maintenance Board',exact:true}).click();await expect(metric('Selected asset')).toContainText('Original B');await expect(runtime.getByRole('img',{name:/Failure risk [(]selected[)] · 80/})).toBeVisible({timeout:15_000});await expect(metric('Asset status board')).toContainText('Original B');
 await runtime.getByRole('button',{name:'Map Operations',exact:true}).click();const map=metric('Asset Map');await map.getByText('Records in this map window',{exact:true}).click();const mapA=map.locator('details').getByRole('button',{name:'Original A · A',exact:true}),mapB=map.locator('details').getByRole('button',{name:'Original B · B',exact:true});await mapA.click();await expect(mapA).toHaveAttribute('aria-pressed','true');await mapB.click();await expect(mapB).toHaveAttribute('aria-pressed','true');await expect(metric('Work Order Schedule')).toContainText('Existing original work');
 await runtime.getByRole('button',{name:'Workflow',exact:true}).click();const edit=metric('Edit Asset');await expect(edit.getByRole('textbox',{name:'Owner',exact:true})).toHaveValue('Table owner B');await edit.getByRole('textbox',{name:'Owner',exact:true}).fill('Workflow owner B');await edit.getByRole('button',{name:'Update asset status',exact:true}).click();await expect.poll(async()=>(await(await request.get('/v1/records/'+type+'/B',{headers:desk})).json()).record.owner).toBe('Workflow owner B');
 await metric('Work Orders').getByRole('cell',{name:'Existing original work',exact:true}).click();await runtime.getByRole('tab',{name:'Comments',exact:true}).click();await metric('Discussion').getByRole('textbox',{name:'Comment',exact:true}).fill('Original work discussion');await metric('Discussion').getByRole('button',{name:'Comment',exact:true}).click();await expect(metric('Discussion')).toContainText('Original work discussion');
 const choosing=runtime.waitForEvent('filechooser');await metric('Upload Reading').getByRole('button',{name:'Choose file',exact:true}).click();await(await choosing).setFiles({name:'reading.csv',mimeType:'text/csv',buffer:Buffer.from('pressure\n20\n')});await expect(metric('Upload Reading')).toContainText('Selected file: reading.csv');await metric('Upload Reading').getByRole('button',{name:'Upload and attach',exact:true}).click();await expect.poll(async()=>(await(await request.get('/v1/records/files.file?limit=500',{headers:desk})).json()).records.some((r:any)=>r.target===work+'/REL-B'&&r.name==='reading.csv')).toBe(true);
 await runtime.getByRole('tab',{name:'AIP',exact:true}).click();await metric('AIP Assistant').getByRole('button',{name:'Summarise active alerts',exact:true}).click();await expect(metric('AIP Assistant')).toContainText('Protocol fixture: Original B');await expect(metric('Neighborhood')).toContainText('Showing 1 of 1 neighbors.');await expect(metric('Neighborhood')).toContainText('Showing 3 of 3 neighbors.');await expect(metric('Quiver · Fleet KPIs')).toContainText('Original A');
 await runtime.getByRole('button',{name:'Digital Twin & Telemetry',exact:true}).click();const live=metric('Plant telemetry · 100,000 × 100');await expect(live).toContainText('100 visible signals');await live.getByRole('row').filter({has:runtime.getByRole('cell',{name:'S1',exact:true})}).click();const twin=metric('Robot cell · live digital twin');await expect(twin.locator('canvas')).toBeVisible();await expect(twin.getByRole('status').filter({hasText:/[1-9][0-9]* model meshes · [1-9][0-9]* rendered triangles/})).toBeVisible();await twin.getByRole('button',{name:'Field mappings',exact:true}).click();await expect(twin).toContainText('vibration');await expect(metric('Fleet vibration · WASM')).toContainText('1,000');await twin.scrollIntoViewIfNeeded();await runtime.screenshot({path:info.outputPath('seven-page-telemetry.png'),fullPage:true});await runtime.getByRole('button',{name:'Maintenance Board',exact:true}).click();await expect(metric('Selected asset')).toContainText('Original A');await expect(runtime.getByRole('img',{name:/Failure risk [(]selected[)] · 20/})).toBeVisible({timeout:15_000});
 await runtime.screenshot({path:info.outputPath('seven-page-runtime.png'),fullPage:true});
 expect(calls.some(c=>c.name==='Original B')).toBe(true);expect(calls.some(c=>c.name==='Original A')).toBe(true);
 }finally{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));}
});
