import {expect,test} from '@playwright/test';
import {defaultAnalyticsFacetGroup} from '../../packages/build/src/module-import/default-analytics.fixture.mjs';
import {decide,fresh,open,pageUIProfile} from './host';
test('five untouched Analytics facets share complete counts and original set Owner and numeric predicates in one frozen page',async({page,request},info)=>{
 test.setTimeout(120_000);page.setDefaultTimeout(10_000);
 const name=fresh('facets').replace(/[^a-z0-9]/gi,'').toLowerCase(),type=`build.${name}`,obj=fresh('OBJ'),id=fresh('PAGE'),headers={Authorization:'Bearer manager'},stages=['Active','Warning','Offline','Maintenance'];
 await decide(request,'manager','build','build.object.create',{type:'build.object',id:obj},{name,title:'Original facet assets',fields:[{name:'name',title:'Name',type:'text',search:true},{name:'priority',title:'Priority',type:'choice',choices:'Low,High'},{name:'owner',title:'Owner',type:'text'},{name:'pressure',title:'Pressure',type:'integer'},{name:'secret',title:'Private owner',type:'text',read:['builder']}],states:stages.map(title=>({name:title.toLowerCase(),title})),actions:[{name:'move',title:'Move original',from:['active'],toInput:'next',inputs:[{name:'next',title:'Status',type:'choice',choices:stages.map(s=>s.toLowerCase()).join(','),required:true}]}]});await decide(request,'manager','build','build.object.publish',{type:'build.object',id:obj},{});
 for(let n=0;n<102;n++){const state=n<60?'active':n<90?'warning':'offline',rid=`R${String(n).padStart(3,'0')}`;await decide(request,'manager','build',`${type}.create`,{type,id:rid},{name:`Original ${rid}`,priority:n%2?'Low':'High',owner:n<40?'Team':'Team East',pressure:n%45,secret:'Hidden owner'});if(state!=='active')await decide(request,'manager','build',`${type}.move`,{type,id:rid},{next:state});}
 await decide(request,'manager','build','build.page.create',{type:'build.page',id},{name:`${name}page`,title:'Original Analytics facets',object:type,sections:[{id:'initial',widget:'text',configVersion:1,text:'Initial'}],document:{formatVersion:2,uiProfile:pageUIProfile,root:'root',nodes:{root:{kind:'rows',children:['initial']},initial:{kind:'widget',section:'initial'}}}});
 const fixture=defaultAnalyticsFacetGroup(pageUIProfile),module=fixture.module;
 await open(page,'manager',`/compose?id=${id}`);await page.getByRole('button',{name:'Import Workshop module',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Import Workshop module',exact:true});await dialog.getByRole('textbox',{name:'Source module JSON',exact:true}).fill(JSON.stringify(module));await dialog.getByRole('combobox',{name:'Map object Asset',exact:true}).selectOption(type);for(const [property,field]of [['name','name'],['status','state'],['priority','priority'],['owner','owner'],['pressure','pressure']])await dialog.getByRole('combobox',{name:`Map field Asset.${property}`,exact:true}).selectOption(field!);for(const state of stages)await dialog.getByRole('textbox',{name:`Original value for ${state}`,exact:true}).fill(state.toLowerCase());await dialog.getByRole('checkbox').last().check();await expect(dialog.getByRole('button',{name:'Apply imported page draft',exact:true})).toBeEnabled();await dialog.getByRole('button',{name:'Apply imported page draft',exact:true}).click();await page.getByRole('button',{name:'Save',exact:true}).click();let saved:any;await expect.poll(async()=>{saved=(await(await request.get(`/v1/records/build.page/${id}`,{headers})).json()).record;return saved.sections.length;}).toBe(6);
 // A private-axis consumer uses the same original plan; member projection must clip it.
 const hidden={...structuredClone(saved.sections.find((s:any)=>s.widget==='treemap')),id:'private',title:'Private facet',group:'secret',groupValueVariable:undefined},document=structuredClone(saved.document);document.nodes.private={kind:'widget',section:'private'};document.nodes[document.root].children.push('private');await decide(request,'manager','build','build.page.edit',{type:'build.page',id},{sections:[...saved.sections,hidden],document});await decide(request,'manager','build','build.page.publish',{type:'build.page',id},{});
 await page.getByRole('button',{name:'Review release',exact:true}).click();await page.getByRole('button',{name:'Check draft and dependencies',exact:true}).click();await page.getByRole('button',{name:'Save immutable candidate',exact:true}).click();await page.getByRole('button',{name:'Activate release',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'Release active for operators.'})).toBeVisible();const later=structuredClone(saved.sections);later.find((s:any)=>s.widget==='histogram').histogram.bins=2;await decide(request,'manager','build','build.page.edit',{type:'build.page',id},{sections:later});
 const runtime=await page.context().newPage();runtime.setDefaultTimeout(10_000);await open(runtime,'desk',`/page?app=build&kind=page&name=${name}page`);const frame=(title:string)=>runtime.getByRole('heading',{name:title,exact:true,level:3}).locator('..'),tree=frame('Assets by owner'),heat=frame('Status × Priority heatmap'),terms=frame('Prominent terms'),histogram=frame('Pressure distribution'),pills=frame('Status pills');await expect(tree.getByRole('status').first()).toContainText('102 matching records');await expect(heat.getByRole('status').first()).toContainText('102 matching records');await expect(runtime.getByText('1–100 of 102',{exact:true})).toBeVisible();await expect(runtime.getByRole('heading',{name:'Private facet',exact:true})).toHaveCount(0);await expect(terms.getByRole('listitem')).toHaveCount(3);await expect(histogram.getByRole('listitem')).toHaveCount(14);
 await pills.getByRole('button',{name:'warning',exact:true}).click();await expect(tree.getByRole('status').first()).toContainText('30 matching records');await expect(heat.getByRole('status').first()).toContainText('30 matching records');await pills.getByRole('button',{name:'active',exact:true}).click();await expect(tree.getByRole('status').first()).toContainText('90 matching records');await pills.getByRole('button',{name:'Clear selections',exact:true}).click();await expect(tree.getByRole('status').first()).toContainText('102 matching records');
 await heat.getByRole('button',{name:'warning × High: 15',exact:true}).click();await expect(heat.getByRole('status').first()).toContainText('15 matching records');await expect(tree.getByRole('status').first()).toContainText('15 matching records');await expect(pills.getByRole('button',{name:'warning',exact:true})).toHaveAttribute('aria-pressed','true');await expect(pills.getByRole('button',{name:'active',exact:true})).toHaveAttribute('aria-pressed','false');await heat.getByRole('button',{name:'Clear cell filters',exact:true}).click();await expect(tree.getByRole('status').first()).toContainText('102 matching records');
 // Source ownerFilter is contains: selecting Team also matches Team East, not an invented exact equality.
 await tree.getByRole('list',{name:'Treemap groups',exact:true}).getByRole('button',{name:/^Team · 40 ·/}).click();await expect(tree.getByRole('status').first()).toContainText('102 matching records');await expect(tree.getByRole('list',{name:'Treemap groups',exact:true}).getByRole('button',{name:/^Team · 40 ·/})).toHaveAttribute('aria-pressed','true');await tree.getByRole('list',{name:'Treemap groups',exact:true}).getByRole('button',{name:/^Team East · 62 ·/}).click();await expect(tree.getByRole('status').first()).toContainText('62 matching records');await expect(heat.getByRole('status').first()).toContainText('62 matching records');await tree.getByRole('button',{name:'Clear group filter',exact:true}).click();await expect(tree.getByRole('status').first()).toContainText('102 matching records');if(process.env.PLATFORM_SCREENSHOTS){await heat.scrollIntoViewIfNeeded();await heat.screenshot({path:info.outputPath('original-analytics-heatmap.png')});await tree.scrollIntoViewIfNeeded();await tree.screenshot({path:info.outputPath('original-analytics-treemap.png')});}
});
