import {expect,test} from "@playwright/test";
import {readFileSync} from "node:fs";
import {decide,fresh,open,pageUIProfile,stableReadRevision} from "./host";

test("four imported collection analyses freeze original complete statistics and independent read-only axes",async({page,request},info)=>{
 test.setTimeout(150_000);page.setDefaultTimeout(10_000);const name=fresh("analysis").replace(/[^a-z0-9]/gi,"").toLowerCase(),type=`build.${name}`,object=fresh("OBJ"),id=fresh("PAGE"),read=async()=>(await(await request.get(`/v1/records/build.page/${id}`,{headers:{Authorization:"Bearer manager"}})).json()).record;
 await decide(request,"manager","build","build.object.create",{type:"build.object",id:object},{name,title:"Original analysis assets",fields:[{name:"name",title:"Name",type:"text"},{name:"status",title:"Status",type:"choice",choices:"ready,warning,maintenance,offline"},...[["pressure","Pressure"],["temperature","Temperature"],["availability","Availability"],["exposure","Exposure"]].map(([name,title])=>({name,title,type:"decimal"}))]});await decide(request,"manager","build","build.object.publish",{type:"build.object",id:object},{});
 for(let i=0;i<86;i++)await decide(request,"manager","build",`${type}.create`,{type,id:`${name}${String(i).padStart(3,"0")}`},{name:`ROW-${i}`,status:["ready","warning","maintenance","offline"][i%4],pressure:10+i,temperature:100-i,availability:i%100,exposure:1000+i});
 const m=JSON.parse(readFileSync(new URL("../../packages/build/src/workshop/module-import/sample.workshop.json",import.meta.url),"utf8")),state=(id:string)=>({id,name:id,type:"string",definitionKind:"static",staticValue:""}),set=(id:string,filter:string)=>({id,name:id,type:"objectSet",definitionKind:"objectSetDefinition",sourceObjectType:"Asset",dependsOn:[],objectSet:{objectType:"Asset",steps:[{op:"where",clauses:[{property:"status",op:"contains",varId:filter}]}]}}),widget=(id:string,type:string,title:string,setID:string)=>({id,type,name:title,config:{objectSetVarId:setID}});
 m.variables=[state("filter"),set("items","filter"),state("localFilter"),set("localItems","localFilter")];m.widgets={input:{id:"input",name:"Original analysis filter",type:"TextInput",config:{variableId:"filter",label:"Original analysis filter"}},bars:widget("bars","ChartVega","Original status bars","items"),signed:widget("signed","ChartWaterfall","Original signed counts","items"),mean:widget("mean","DerivedSeries","Original mean","items"),axes:widget("axes","FreeFormAnalysis","Original axis analysis","items"),table:{id:"table",name:"Original shared table",type:"ObjectTable",config:{objectSetVarId:"items",columns:[{key:"name"}]}},localAxes:widget("localAxes","FreeFormAnalysis","Local axis analysis","localItems"),trigger:{id:"trigger",name:"Open original analysis",type:"SingleButton",config:{label:"Open original analysis",eventActions:[{kind:"openOverlay",overlayId:"panel"}]}},close:{id:"close",name:"Close original analysis",type:"SingleButton",config:{label:"Close original analysis",eventActions:[{kind:"closeOverlay",overlayId:"panel"}]}}};m.sections={root:{id:"root",name:"Root",layout:"rows",children:["input","bars","signed","mean","axes","table","trigger"].map(id=>({kind:"widget",id}))},panel:{id:"panel",name:"Panel",layout:"rows",children:["localAxes","close"].map(id=>({kind:"widget",id}))}};m.overlays=[{id:"panel",name:"Original analysis panel",kind:"drawer",rootSectionId:"panel"}];
 await decide(request,"manager","build","build.page.create",{type:"build.page",id},{name,title:"Original collection analysis",object:type,sections:[{id:"initial",widget:"text",configVersion:1,text:"Initial"}],document:{formatVersion:2,uiProfile:pageUIProfile,root:"root",nodes:{root:{kind:"rows",children:["initial"]},initial:{kind:"widget",section:"initial"}}}});
 await open(page,"manager",`/compose?id=${id}`);await page.getByRole("button",{name:"Import Workshop module",exact:true}).click();const dialog=page.getByRole("dialog",{name:"Import Workshop module",exact:true});await dialog.getByRole("textbox",{name:"Source module JSON",exact:true}).fill(JSON.stringify(m));await dialog.getByRole("combobox",{name:"Map object Asset",exact:true}).selectOption(type);for(const [external,field]of [["name","name"],["status","status"],["pressure","pressure"],["temperature","temperature"],["availability","availability"],["revenueImpact","exposure"]])await dialog.getByRole("combobox",{name:`Map field Asset.${external}`,exact:true}).selectOption(field);
 for(const [source,value]of [["Active","ready"],["Warning","warning"],["Maintenance","maintenance"],["Offline","offline"]])await dialog.getByRole("group",{name:"Map collection analysis Original signed counts",exact:true}).getByRole("textbox",{name:`Original analysis value ${source}`,exact:true}).fill(value);await dialog.getByRole("group",{name:"Map collection analysis Original mean",exact:true}).getByRole("textbox",{name:"Original mean unit",exact:true}).fill("bar");await dialog.getByRole("checkbox").check();await expect(dialog.getByRole("button",{name:"Apply imported page draft",exact:true})).toBeEnabled();await dialog.getByRole("button",{name:"Apply imported page draft",exact:true}).click();
 await page.getByRole("region",{name:"Widgets and layout",exact:true}).getByRole("button",{name:"Original axis analysis",exact:true}).click();const inspector=page.getByRole("region",{name:"The widget in hand",exact:true});await expect(inspector.getByRole("combobox",{name:"Collection analysis kind",exact:true})).toHaveValue("record-axes");await expect(inspector.getByRole("combobox",{name:"Analysis X state",exact:true})).not.toHaveValue("");await page.getByRole("button",{name:"Save",exact:true}).click();let saved:any;await expect.poll(async()=>{saved=await read();return saved.sections?.filter((s:any)=>s.widget==="collection-analysis").length;}).toBe(5);
 const originalAxes=saved.sections.find((s:any)=>s.title==="Original axis analysis"),originalMean=saved.sections.find((s:any)=>s.title==="Original mean"),table=saved.sections.find((s:any)=>s.widget==="table");expect(saved.document.queries[saved.document.variables[originalAxes.collectionVariable].source.query].limit).toBe(80);expect(saved.document.queries[saved.document.variables[table.collectionVariable].source.query].limit).toBe(100);
 await page.getByRole("button",{name:"Review release",exact:true}).click();await page.getByRole("button",{name:"Check draft and dependencies",exact:true}).click();await page.getByRole("button",{name:"Save immutable candidate",exact:true}).click();originalMean.analysis.unit="LATER UNIT";saved.document.variables[originalAxes.analysisXVariable].initial="availability";await decide(request,"manager","build","build.page.edit",{type:"build.page",id},{sections:saved.sections,document:saved.document});await page.getByRole("button",{name:"Activate release",exact:true}).click();
 const runtime=await page.context().newPage();await stableReadRevision(runtime);await open(runtime,"desk",`/page?app=build&kind=page&name=${name}`);const section=(title:string)=>runtime.getByRole("heading",{name:title,exact:true,level:3}).locator(".."),bars=section("Original status bars"),signed=section("Original signed counts"),mean=section("Original mean"),axes=section("Original axis analysis"),filter=runtime.getByRole("textbox",{name:"Original analysis filter",exact:true});
 await expect(bars.getByLabel("ready: 22",{exact:true})).toBeVisible();await expect(signed).toContainText("86 matching records");await expect(signed.getByLabel("Offline: -21; Σ -42",{exact:true})).toBeVisible();await expect(mean).toContainText("86 records");await expect(mean).toContainText("52.50 bar");await expect(mean).not.toContainText("LATER UNIT");await expect(axes.getByRole("combobox",{name:"Analysis X axis",exact:true})).toHaveValue("pressure");await expect(axes).toContainText("80 plotted records");await expect(section("Original shared table")).toContainText("1–86 of 86");expect(await axes.getByRole("button").count()).toBe(0);
 let axisReads=0;const track=(request:any)=>{if(request.url().includes(`/records/${type}/query`))axisReads++;};runtime.on("request",track);await axes.getByRole("combobox",{name:"Analysis X axis",exact:true}).selectOption("exposure");await axes.getByRole("combobox",{name:"Analysis Y axis",exact:true}).selectOption("pressure");await expect(axes.getByRole("img",{name:new RegExp(`${name}000.*Exposure: 1000.*Pressure: 10`)})).toBeVisible();await runtime.evaluate(()=>new Promise<void>(r=>requestAnimationFrame(()=>requestAnimationFrame(()=>r()))));expect(axisReads).toBe(0);runtime.off("request",track);
 await filter.fill("warning");await expect(bars.getByLabel("warning: 22",{exact:true})).toBeVisible();await expect(mean).toContainText("22 records");await expect(mean).toContainText("53.00 bar");await expect(axes).toContainText("22 plotted records");await expect(signed.getByLabel("Warning: -22; Σ -22",{exact:true})).toBeVisible();await filter.fill("unknown");await expect(mean).toContainText("0 records");await expect(mean).toContainText("No numeric values");await expect(axes).toContainText("No records with both coordinates");await filter.fill("");await expect(mean).toContainText("52.50 bar");
 await runtime.getByRole("button",{name:"Open original analysis",exact:true}).click();const panel=runtime.getByRole("dialog",{name:"Original analysis panel",exact:true}),local=panel.getByRole("heading",{name:"Local axis analysis",exact:true}).locator("..");await expect(local.getByRole("combobox",{name:"Analysis X axis",exact:true})).toHaveValue("pressure");await local.getByRole("combobox",{name:"Analysis X axis",exact:true}).selectOption("availability");await panel.getByRole("button",{name:"Close original analysis",exact:true}).click();await expect(axes.getByRole("combobox",{name:"Analysis X axis",exact:true})).toHaveValue("exposure");await runtime.getByRole("button",{name:"Open original analysis",exact:true}).click();await expect(local.getByRole("combobox",{name:"Analysis X axis",exact:true})).toHaveValue("pressure");await panel.getByRole("button",{name:"Close original analysis",exact:true}).click();
 if(process.env.PLATFORM_SCREENSHOTS){for(const [title,file]of [["Original status bars","analysis-bars.png"],["Original signed counts","analysis-signed.png"],["Original mean","analysis-mean.png"],["Original axis analysis","analysis-axes.png"]])await section(title).screenshot({path:info.outputPath(file)});await runtime.setViewportSize({width:390,height:844});await axes.screenshot({path:info.outputPath("analysis-axes-narrow.png")});await signed.screenshot({path:info.outputPath("analysis-signed-narrow.png")});await runtime.setViewportSize({width:1280,height:720});}
 await runtime.route(`**/v1/aggregates/${type}**`,route=>route.fulfill({status:403,contentType:"application/json",body:'{"error":{"message":"Denied"}}'}));await filter.fill("maintenance");await expect(bars.getByRole("alert")).toBeVisible();await expect(mean.getByRole("alert")).toBeVisible();await expect(mean).not.toContainText("52.50 bar");await runtime.unroute(`**/v1/aggregates/${type}**`);await filter.fill("");await expect(mean).toContainText("52.50 bar");
 let release:()=>void=()=>{},finished:()=>void=()=>{},started=false;const gate=new Promise<void>(r=>release=r),done=new Promise<void>(r=>finished=r);await runtime.route(`**/v1/aggregates/${type}/query`,async route=>{const body=route.request().postDataJSON();if(!body.groups?.length||!JSON.stringify(body).includes('"ready"'))return route.continue();started=true;await gate;const response=await route.fetch();await route.fulfill({response});finished();});await filter.fill("ready");await expect.poll(()=>started).toBe(true);await filter.fill("warning");await expect(bars.getByLabel("warning: 22",{exact:true})).toBeVisible();release();await done;await runtime.evaluate(()=>new Promise<void>(r=>requestAnimationFrame(()=>requestAnimationFrame(()=>r()))));await expect(bars.getByLabel("warning: 22",{exact:true})).toBeVisible();await expect(bars.getByLabel("ready: 22",{exact:true})).toHaveCount(0);await runtime.unroute(`**/v1/aggregates/${type}/query`);
});
