import {expect,test} from "@playwright/test";
import {readFileSync} from "node:fs";
import {decide,fresh,open,pageUIProfile,stableReadRevision} from "./host";

test("imported metric cards freeze complete-collection aggregates and presentation while scopes reject obsolete or unauthorized reads",async({page,request},info)=>{
 test.setTimeout(90_000);
 const name=fresh("cards").replace(/[^a-z0-9]/gi,"").toLowerCase(),type=`build.${name}`,object=fresh("OBJ"),id=fresh("PAGE");
 await decide(request,"manager","build","build.object.create",{type:"build.object",id:object},{name,title:"Metric assets",fields:[{name:"note",title:"Note",type:"text"},{name:"bucket",title:"Bucket",type:"choice",choices:"Active,Offline"},{name:"availability",title:"Availability",type:"decimal"},{name:"hidden",title:"Private amount",type:"decimal",read:["builder"]}]});await decide(request,"manager","build","build.object.publish",{type:"build.object",id:object},{});
 for(let n=0;n<620;n++)await decide(request,"manager","build",`${type}.create`,{type,id:`${name}${n}`},{note:`ASSET-${n}`,bucket:n%2?"Offline":"Active",availability:n%2?80:20,hidden:999});
 const m=JSON.parse(readFileSync(new URL("../../packages/build/src/module-import/sample.workshop.json",import.meta.url),"utf8"));m.sections={root:{id:"root",name:"Metrics",layout:"rows",children:["input","table","count","mean","active","secret"].map(id=>({kind:"widget",id}))}};
 m.widgets={table:m.widgets.table,input:{id:"input",name:"Metric filter",type:"TextInput",config:{variableId:"scratch",label:"Metric filter"}},count:{id:"count",name:"Whole collection",type:"MetricCard",config:{label:"Whole collection",variableId:"total",variant:"card",suffix:" assets",trend:"up",trendValue:"+3"}},mean:{id:"mean",name:"Mean availability",type:"MetricCard",config:{label:"Mean availability",variableId:"mean",variant:"card",suffix:"%",color:"success"}},active:{id:"active",name:"Active assets",type:"MetricCard",config:{label:"Active assets",variableId:"active",variant:"tag",color:"warning"}},secret:{id:"secret",name:"Private metric",type:"MetricCard",config:{label:"Private metric",variableId:"secret",variant:"simple"}}};
 m.variables=m.variables.filter((v:any)=>v.id!=="selected");m.variables.find((v:any)=>v.id==="scratch").staticValue="";m.variables.find((v:any)=>v.id==="notes").objectSet.steps=[{op:"where",clauses:[{id:"filter",property:"name",op:"contains",varId:"scratch"}]}];delete m.widgets.table.config.activeVarId;
 for(const [id,title,kind,step] of [["total","Filtered count","variableTransformation",{op:"cardinality"}],["mean","Average availability","objectSetAggregation",{op:"aggregate",args:{by:"avgAvailability"}}],["active","Active count","objectSetAggregation",{op:"aggregate",args:{by:"countActive"}}],["secret","Private average","objectSetAggregation",{op:"aggregate",args:{by:"privateAverage"}}]])m.variables.push({id,name:title,type:"numeric",definitionKind:kind,inputVarId:"notes",dependsOn:["notes"],transformations:[step]});
 await decide(request,"manager","build","build.page.create",{type:"build.page",id},{name,title:"Metric card page",object:type,sections:[{id:"initial",widget:"table",configVersion:1,fields:["note"]}],document:{formatVersion:2,uiProfile:pageUIProfile,root:"root",nodes:{root:{kind:"rows",children:["initial"]},initial:{kind:"widget",section:"initial"}}}});
 await open(page,"manager",`/compose?id=${id}`);await page.getByRole("button",{name:"Import Workshop module",exact:true}).click();const dialog=page.getByRole("dialog",{name:"Import Workshop module",exact:true});await dialog.getByRole("textbox",{name:"Source module JSON",exact:true}).fill(JSON.stringify(m));await expect(dialog.getByRole("alert").filter({hasText:"/widgets/count/config/trendValue"})).toBeVisible();delete m.widgets.count.config.trend;delete m.widgets.count.config.trendValue;await dialog.getByRole("textbox",{name:"Source module JSON",exact:true}).fill(JSON.stringify(m));await dialog.getByRole("combobox",{name:"Map object Asset",exact:true}).selectOption(type);await dialog.getByRole("combobox",{name:"Map field Asset.name",exact:true}).selectOption("note");
 for(const [variable,measure] of [["Average availability","avg:availability"],["Active count","count"],["Private average","avg:hidden"]])await dialog.getByRole("group",{name:`Map metric aggregate ${variable}`,exact:true}).getByRole("combobox",{name:"Original metric measure",exact:true}).selectOption(measure);const activeMapping=dialog.getByRole("group",{name:"Map metric aggregate Active count",exact:true});await activeMapping.getByRole("combobox",{name:"Optional metric equality field",exact:true}).selectOption("bucket");await activeMapping.getByRole("combobox",{name:"Metric equality value",exact:true}).selectOption("Active");await dialog.getByRole("checkbox").check();await dialog.getByRole("button",{name:"Apply imported page draft",exact:true}).click();
 await page.getByRole("region",{name:"Widgets and layout",exact:true}).getByRole("button",{name:"Mean availability",exact:true}).click();const inspector=page.getByRole("region",{name:"The widget in hand",exact:true});await inspector.getByRole("textbox",{name:"Metric prefix",exact:true}).fill("Frozen ");await page.getByRole("button",{name:"Save",exact:true}).click();let saved:any;await expect.poll(async()=>{saved=(await(await request.get(`/v1/records/build.page/${id}`,{headers:{Authorization:"Bearer manager"}})).json()).record;return saved.sections?.find((s:any)=>s.title==="Mean availability")?.metricPresentation.prefix;}).toBe("Frozen ");for(const query of Object.values(saved.document.queries) as any[])query.limit=1;await decide(request,"manager","build","build.page.edit",{type:"build.page",id},{document:saved.document});await page.reload();
 await page.getByRole("button",{name:"Review release",exact:true}).click();await page.getByRole("button",{name:"Check draft and dependencies",exact:true}).click();await page.getByRole("button",{name:"Save immutable candidate",exact:true}).click();saved.sections.find((s:any)=>s.title==="Mean availability").metricPresentation.prefix="Later ";saved.sections.find((s:any)=>s.title==="Mean availability").measure="sum:availability";await decide(request,"manager","build","build.page.edit",{type:"build.page",id},{sections:saved.sections});await page.getByRole("button",{name:"Activate release",exact:true}).click();
 const runtime=await page.context().newPage();await stableReadRevision(runtime);let reads=0;runtime.on("request",r=>{if(r.url().endsWith(`/v1/aggregates/${type}/query`)){reads++;const q=r.postDataJSON();expect(q.limit).toBeUndefined();expect(q.offset).toBeUndefined();expect(q.sort).toBeUndefined();}});await open(runtime,"desk",`/page?app=build&kind=page&name=${name}`);const section=(title:string)=>runtime.getByRole("heading",{name:title,exact:true}).locator(".."),count=section("Whole collection"),mean=section("Mean availability"),active=section("Active assets"),input=runtime.getByRole("textbox",{name:"Metric filter",exact:true});await expect(count.getByText("620 assets",{exact:true})).toBeVisible();await expect(mean.getByText("Frozen 50%",{exact:true})).toBeVisible();await expect(active.getByText("310",{exact:true})).toBeVisible();await expect(runtime.getByRole("heading",{name:"Private metric",exact:true})).toHaveCount(0);await expect(runtime.getByText("1–1 of 620",{exact:true})).toBeVisible();const before=reads;await runtime.getByRole("button",{name:"Next page",exact:true}).click();await expect(runtime.getByText("2–2 of 620",{exact:true})).toBeVisible();await expect(count.getByText("620 assets",{exact:true})).toBeVisible();expect(reads).toBe(before);
 if(process.env.PLATFORM_SCREENSHOTS){await mean.screenshot({path:info.outputPath("metric-card.png")});await runtime.setViewportSize({width:390,height:844});await runtime.evaluate(()=>new Promise<void>(r=>requestAnimationFrame(()=>requestAnimationFrame(()=>r()))));await mean.scrollIntoViewIfNeeded();await expect(mean.getByText("Frozen 50%",{exact:true})).toBeVisible();await mean.screenshot({path:info.outputPath("metric-card-narrow.png")});await runtime.setViewportSize({width:1280,height:720});}
 await input.fill("NO-MATCH");await expect(count.getByText("0 assets",{exact:true})).toBeVisible();await expect(mean.getByText("Frozen \u2014%",{exact:true})).toBeVisible();await runtime.route(`**/v1/aggregates/${type}/query`,route=>route.fulfill({status:403,contentType:"application/json",body:JSON.stringify({error:{message:"Denied"}})}));await input.fill("ASSET-1");await expect(mean.getByRole("alert")).toBeVisible();await expect(mean.getByText("Frozen 50%",{exact:true})).toHaveCount(0);await runtime.unroute(`**/v1/aggregates/${type}/query`);await input.fill("");await expect(mean.getByText("Frozen 50%",{exact:true})).toBeVisible();await runtime.reload();await expect(count.getByText("620 assets",{exact:true})).toBeVisible();await expect(mean.getByText("Frozen 50%",{exact:true})).toBeVisible();
});
