import {expect,test} from "@playwright/test";
import {readFileSync} from "node:fs";
import {decide,fresh,open,pageUIProfile,stableReadRevision} from "./host";

test("source board maps original lifecycle actions and freezes isolated authorized selection and real moves",async({page,request},info)=>{
 test.setTimeout(90_000);
 const name=fresh("boards").replace(/[^a-z0-9]/gi,"").toLowerCase(),type=`build.${name}`,object=fresh("OBJ"),id=fresh("PAGE");
 await decide(request,"manager","build","build.object.create",{type:"build.object",id:object},{name,title:"Board assets",fields:[{name:"note",title:"Asset name",type:"text"},{name:"priority",title:"Priority",type:"text"},{name:"secret",title:"Private summary",type:"text",read:["builder"]}],states:[{name:"open",title:"Open"},{name:"done",title:"Done"}],actions:[{name:"finish",title:"Finish board card",from:["open"],to:"done",inputs:[{name:"reason",title:"Reason",type:"text",required:true}],conditions:[{field:"input.reason",operator:"!=",value:"blocked",message:"Reason is blocked"}]}]});await decide(request,"manager","build","build.object.publish",{type:"build.object",id:object},{});for(const suffix of ["A","B","C"])await decide(request,"manager","build",`${type}.create`,{type,id:`${name}${suffix}`},{note:`CARD-${suffix}`,priority:"high",secret:"Hidden summary"});
 const m=JSON.parse(readFileSync(new URL("../../packages/build/src/workshop/module-import/sample.workshop.json",import.meta.url),"utf8")),board=(id:string,name:string,set="notes",active="selected",move=true)=>({id,name,type:"KanbanBoard",config:{objectSetVarId:set,groupBy:"status",...(active?{activeVarId:active}:{}),...(move?{actionId:"updateAssetStatus",actionParam:"status"}:{})}});
 m.widgets.board=board("board","Asset status board");m.widgets.other=board("other","Other board","otherNotes","otherSelected");m.widgets.local=board("local","Local board","localNotes","localSelected");m.widgets.hidden=board("hidden","Hidden board","notes","",false);m.widgets.localDetail={id:"localDetail",name:"Local board detail",type:"PropertyList",config:{objectVarId:"localSelected",properties:["name"],hideNull:false}};m.widgets.input={id:"input",name:"Board filter",type:"TextInput",config:{variableId:"scratch",label:"Board filter"}};m.widgets.trigger={id:"trigger",name:"Open board panel",type:"SingleButton",config:{label:"Open board panel",eventActions:[{kind:"openOverlay",overlayId:"panel"}]}};m.widgets.close={id:"close",name:"Close board panel",type:"SingleButton",config:{label:"Close board panel",eventActions:[{kind:"closeOverlay",overlayId:"panel"}]}};
 m.variables.find((v:any)=>v.id==="scratch").staticValue="";m.variables.find((v:any)=>v.id==="notes").objectSet.steps=[{op:"where",clauses:[{id:"filter",property:"name",op:"contains",varId:"scratch"}]}];for(const kind of ["other","local"])m.variables.push({id:`${kind}Notes`,name:`${kind} notes`,type:"objectSet",definitionKind:"objectSetDefinition",sourceObjectType:"Asset",objectSet:{objectType:"Asset",steps:[]}},{id:`${kind}Selected`,name:`${kind} selected`,type:"object",definitionKind:"widgetOutput",widgetId:kind,widgetOutputKey:"activeObject"});m.sections={root:{id:"root",name:"Root",layout:"rows",children:["input","board","detail","other","hidden","trigger"].map(id=>({kind:"widget",id}))},panel:{id:"panel",name:"Panel",layout:"rows",children:["local","localDetail","close"].map(id=>({kind:"widget",id}))}};m.overlays=[{id:"panel",name:"Board panel",kind:"drawer",rootSectionId:"panel"}];
 await decide(request,"manager","build","build.page.create",{type:"build.page",id},{name,title:"Imported board",object:type,sections:[{id:"initial",widget:"table",configVersion:1,fields:["note"]}],document:{formatVersion:2,uiProfile:pageUIProfile,root:"root",nodes:{root:{kind:"rows",children:["initial"]},initial:{kind:"widget",section:"initial"}}}});
 await open(page,"manager",`/compose?id=${id}`);await page.getByRole("button",{name:"Import Workshop module",exact:true}).click();const dialog=page.getByRole("dialog",{name:"Import Workshop module",exact:true});await dialog.getByRole("textbox",{name:"Source module JSON",exact:true}).fill(JSON.stringify(m));await dialog.getByRole("combobox",{name:"Map object Asset",exact:true}).selectOption(type);for(const [source,target] of [["name","note"],["status","state"]])await dialog.getByRole("combobox",{name:`Map field Asset.${source}`,exact:true}).selectOption(target);
 for(const title of ["Asset status board","Other board","Local board","Hidden board"]){const mapping=dialog.getByRole("group",{name:`Map board ${title}`,exact:true});await mapping.getByRole("combobox",{name:"Card title field",exact:true}).selectOption(title==="Hidden board"?"secret":"note");if(title==="Asset status board")await mapping.getByRole("group",{name:"Card summary fields",exact:true}).getByRole("button",{name:"Private summary",exact:true}).click();if(title!=="Hidden board"){await mapping.getByRole("group",{name:"Map original board move actions",exact:true}).getByRole("button",{name:"Finish board card → Done",exact:true}).click();}}
 await dialog.getByRole("checkbox").check();await dialog.getByRole("button",{name:"Apply imported page draft",exact:true}).click();await page.getByRole("region",{name:"Widgets and layout",exact:true}).getByRole("button",{name:"Asset status board",exact:true}).click();await expect(page.getByRole("region",{name:"The widget in hand",exact:true}).getByRole("button",{name:"Finish board card → Done",exact:true})).toHaveAttribute("aria-pressed","true");await page.getByRole("button",{name:"Save",exact:true}).click();let saved:any;await expect.poll(async()=>{saved=(await(await request.get(`/v1/records/build.page/${id}`,{headers:{Authorization:"Bearer manager"}})).json()).record;return saved.sections?.filter((s:any)=>s.widget==="kanban").length;}).toBe(4);
 await page.getByRole("button",{name:"Review release",exact:true}).click();await page.getByRole("button",{name:"Check draft and dependencies",exact:true}).click();await page.getByRole("button",{name:"Save immutable candidate",exact:true}).click();const rootDraft=saved.sections.find((s:any)=>s.title==="Asset status board");rootDraft.actions=[];rootDraft.cardLabel="id";await decide(request,"manager","build","build.page.edit",{type:"build.page",id},{sections:saved.sections});await page.getByRole("button",{name:"Activate release",exact:true}).click();
 const runtime=await page.context().newPage();await stableReadRevision(runtime);await open(runtime,"desk",`/page?app=build&kind=page&name=${name}`);const section=(title:string)=>runtime.getByRole("heading",{name:title,exact:true}).locator(".."),root=section("Asset status board"),detail=section("Imported selection"),other=section("Other board"),input=runtime.getByRole("textbox",{name:"Board filter",exact:true}),openLane=root.getByRole("region",{name:"Open",exact:true}),doneLane=root.getByRole("region",{name:"Done",exact:true});await expect(openLane.getByRole("button",{name:"CARD-B",exact:true})).toBeVisible();await expect(root.getByText("Hidden summary",{exact:true})).toHaveCount(0);await expect(runtime.getByRole("heading",{name:"Hidden board",exact:true})).toHaveCount(0);await openLane.getByRole("button",{name:"CARD-B",exact:true}).click();await expect(detail.getByRole("definition").filter({hasText:/^CARD-B$/})).toBeVisible();await other.getByRole("button",{name:"CARD-C",exact:true}).click();await expect(detail.getByRole("definition").filter({hasText:/^CARD-B$/})).toBeVisible();
 if(process.env.PLATFORM_SCREENSHOTS){await root.screenshot({path:info.outputPath("imported-board.png")});await runtime.setViewportSize({width:390,height:844});await runtime.evaluate(()=>new Promise<void>(r=>requestAnimationFrame(()=>requestAnimationFrame(()=>r()))));await root.scrollIntoViewIfNeeded();await root.screenshot({path:info.outputPath("imported-board-narrow.png")});await runtime.setViewportSize({width:1280,height:720});}
 await openLane.getByRole("button",{name:"CARD-B",exact:true}).locator('xpath=ancestor::*[@draggable="true"]').dragTo(doneLane);const form=runtime.getByRole("dialog",{name:`Finish board card ${name}B`,exact:true});await expect(form).toBeVisible();expect((await(await request.get(`/v1/records/${type}/${name}B`,{headers:{Authorization:"Bearer desk"}})).json()).record.state).toBe("open");await form.getByRole("textbox",{name:"Reason *",exact:true}).fill("blocked");await form.getByRole("button",{name:"Finish board card",exact:true}).click();await expect(form.getByRole("alert")).toContainText(/blocked|condition/i);await expect(form.getByRole("textbox",{name:"Reason *",exact:true})).toHaveValue("blocked");await form.getByRole("textbox",{name:"Reason *",exact:true}).fill("Native mapped move");await form.getByRole("button",{name:"Finish board card",exact:true}).click();await expect(doneLane.getByRole("button",{name:"CARD-B",exact:true})).toBeVisible();expect((await(await request.get(`/v1/records/${type}/${name}B`,{headers:{Authorization:"Bearer desk"}})).json()).record.state).toBe("done");
 await openLane.getByRole("combobox",{name:"Move CARD-A with action",exact:true}).selectOption(`${type}.finish`);const conflict=runtime.getByRole("dialog",{name:`Finish board card ${name}A`,exact:true});await expect(conflict).toBeVisible();await decide(request,"manager","build",`${type}.finish`,{type,id:`${name}A`},{reason:"External move"});await conflict.getByRole("textbox",{name:"Reason *",exact:true}).fill("Local move");await conflict.getByRole("button",{name:"Finish board card",exact:true}).click();await expect(conflict.getByRole("alert")).toContainText(/revision|conflict|changed/i);await expect(conflict.getByRole("textbox",{name:"Reason *",exact:true})).toHaveValue("Local move");await conflict.getByRole("button",{name:"Cancel",exact:true}).click();await input.fill("CARD-C");await expect(detail.getByRole("definition").filter({hasText:/^CARD-B$/})).toHaveCount(0);await expect(root.getByRole("button",{name:"CARD-B",exact:true})).toHaveCount(0);
 await runtime.getByRole("button",{name:"Open board panel",exact:true}).click();const panel=runtime.getByRole("dialog",{name:"Board panel",exact:true});await panel.getByRole("button",{name:"CARD-C",exact:true}).click();await expect(panel.getByRole("definition").filter({hasText:/^CARD-C$/})).toBeVisible();await panel.getByRole("button",{name:"Close board panel",exact:true}).click();await runtime.getByRole("button",{name:"Open board panel",exact:true}).click();await expect(panel.getByRole("definition").filter({hasText:/^CARD-C$/})).toHaveCount(0);await panel.getByRole("button",{name:"Close board panel",exact:true}).click();await runtime.reload();await expect(detail.getByText("Select a record to see it here.",{exact:true})).toBeVisible();await expect(root.getByRole("button",{name:"CARD-C",exact:true})).toBeVisible();
});
