import {expect,test} from "@playwright/test";
import {readFileSync} from "node:fs";
import {decide,fresh,open,pageUIProfile,stableReadRevision} from "./host";

test("four observation sources import through explicit real queries and reviewed asset consumers into one frozen page",async({page,request},info)=>{
 test.setTimeout(150_000);page.setDefaultTimeout(10_000);const name=fresh("obsimport").replace(/[^a-z0-9]/gi,"").toLowerCase(),assets=`build.${name}assets`,samples=`build.${name}samples`,id=fresh("PAGE"),headers={Authorization:"Bearer manager"};
 for(const [type,fields]of [[assets,[{name:"name",title:"Asset name",type:"text"},{name:"availability",title:"Asset availability",type:"decimal"}]],[samples,[{name:"at",title:"Business event time",type:"datetime"},{name:"pressure",title:"Pressure",type:"decimal"},{name:"temperature",title:"Temperature",type:"decimal"},{name:"availability",title:"Sample availability",type:"decimal"},{name:"asset",title:"Original asset",type:"reference",ref:assets}]]] as const){const object=fresh("OBJ");await decide(request,"manager","build","build.object.create",{type:"build.object",id:object},{name:type.slice(6),title:type===assets?"Imported real assets":"Imported real samples",fields});await decide(request,"manager","build","build.object.publish",{type:"build.object",id:object},{});}
 for(const [asset,value]of [["A",80],["B",98]] as const)await decide(request,"manager","build",`${assets}.create`,{type:assets,id:asset},{name:`Imported original asset ${asset}`,availability:value});
 for(let i=0;i<106;i++)await decide(request,"manager","build",`${samples}.create`,{type:samples,id:`S${String(i).padStart(3,"0")}`},{at:new Date(Date.UTC(2026,9,3,0,0,i)).toISOString(),pressure:i,temperature:100+i,availability:96,asset:i%2?"B":"A"});
 const queryNames:any={};for(const [key,by]of [["all",""],["context","asset"]]){const q=fresh("QUERY"),queryName=`${name}${key}`;await decide(request,"manager","build","build.query.create",{type:"build.query",id:q},{name:queryName,title:key==="all"?"Actual sample history":"Actual history by asset",description:"Original business observations",object:samples,sort:["-at","id"],limit:100,...by?{by}:{}});await decide(request,"manager","build","build.query.publish",{type:"build.query",id:q},{});queryNames[key]=queryName;}
 const response=await(await request.get("/v1/definitions",{headers})).json(),definitions=Array.isArray(response)?response:response.definitions,binding=(key:string)=>{const d=definitions.find((d:any)=>d.ref.kind==="query"&&d.ref.name===queryNames[key]);return {ref:d.ref,sourceVersion:d.version};};
 const m=JSON.parse(readFileSync(new URL("../../packages/build/src/workshop/module-import/sample.workshop.json",import.meta.url),"utf8"));m.name="Original imported observations";m.pages=[{id:"page",name:"Original imported observations",rootSectionId:"root"}];m.variables=[{id:"assets",name:"Original assets",type:"objectSet",definitionKind:"objectSetDefinition",sourceObjectType:"Asset",objectSet:{objectType:"Asset",steps:[{op:"where",clauses:[{property:"name",op:"contains",varId:"assetFilter"}]}]}}, {id:"selected",name:"Selected original asset",type:"object",definitionKind:"widgetOutput",widgetId:"assets",widgetOutputKey:"activeObject"},{id:"selectedSignal",name:"Signal hint",type:"numeric",definitionKind:"static",staticValue:0},{id:"flowStats",name:"Flow output",type:"struct",definitionKind:"static",staticValue:null},{id:"currentTelemetryRow",name:"Row metadata",type:"struct",definitionKind:"static",staticValue:null}];
 m.variables.push({id:"assetFilter",name:"Asset name filter",type:"string",definitionKind:"static",staticValue:""});
 m.widgets={filter:{id:"filter",name:"Original asset name filter",type:"TextInput",config:{variableId:"assetFilter",label:"Original asset name filter"}},assets:{id:"assets",name:"Original asset table",type:"ObjectTable",config:{objectSetVarId:"assets",activeVarId:"selected",columns:[{key:"name"}]}},detail:{id:"detail",name:"Imported asset detail",type:"PropertyList",config:{objectVarId:"selected",properties:["name"]}},table:{id:"table",name:"Imported telemetry rows",type:"TelemetryTable",config:{assetVarId:"selected",selectedSignalVarId:"selectedSignal",rowHeight:30}},stats:{id:"stats",name:"Imported complete statistics",type:"TelemetryStats",config:{assetVarId:"selected",flowStatsVarId:"flowStats",signalIndex:0,threshold:11.5,windowRows:10000}},availability:{id:"availability",name:"Imported asset availability",type:"ObservabilityChart",config:{objectSetVarId:"assets"}},series:{id:"series",name:"Imported actual time series",type:"TimeSeriesAnalysis",config:{objectSetVarId:"assets"}}};m.sections={root:{id:"root",name:"Root",layout:"rows",children:Object.keys(m.widgets).map(id=>({kind:"widget",id}))}};m.overlays=[];const source=JSON.stringify(m);
 await decide(request,"manager","build","build.page.create",{type:"build.page",id},{name,title:"Observation import",object:assets,sections:[{id:"initial",widget:"text",configVersion:1,text:"Initial"}],document:{formatVersion:2,uiProfile:pageUIProfile,root:"root",nodes:{root:{kind:"rows",children:["initial"]},initial:{kind:"widget",section:"initial"}}}});
 await open(page,"manager",`/compose?id=${id}`);await page.getByRole("button",{name:"Import Workshop module",exact:true}).click();const dialog=page.getByRole("dialog",{name:"Import Workshop module",exact:true});await dialog.getByRole("textbox",{name:"Source module JSON",exact:true}).fill(source);await dialog.getByRole("combobox",{name:"Map object Asset",exact:true}).selectOption(assets);for(const field of ["name","availability"])await dialog.getByRole("combobox",{name:`Map field Asset.${field}`,exact:true}).selectOption(field);
 const apply=dialog.getByRole("button",{name:"Apply imported page draft",exact:true});await expect(apply).toBeDisabled();
 for(const [title,kind]of [["Imported telemetry rows","table"],["Imported complete statistics","stats"],["Imported asset availability","availability"],["Imported actual time series","series"]]){const fields=dialog.getByRole("group",{name:`Map business observations ${title}`,exact:true});await fields.getByRole("combobox",{name:"Observation source interpretation",exact:true}).selectOption("actual-business-observations");await fields.getByRole("combobox",{name:"Original sample query version",exact:true}).selectOption(JSON.stringify(binding("all")));await fields.getByRole("combobox",{name:"Original observation time",exact:true}).selectOption("at");for(const [n,field,unit]of (kind==="series"?[[1,"pressure","bar"],[2,"temperature","°C"],[3,"availability","%"]]:[[1,kind==="availability"?"availability":"pressure",kind==="availability"?"%":"bar"]])){await fields.getByRole("button",{name:"Add observation signal",exact:true}).click();await fields.getByRole("combobox",{name:`Observation signal field ${n}`,exact:true}).selectOption(String(field));await fields.getByRole("textbox",{name:`Observation signal unit ${n}`,exact:true}).fill(String(unit));}if(kind==="table"||kind==="stats")await fields.getByRole("combobox",{name:"Original asset reference field",exact:true}).selectOption("asset");if(kind==="table")await fields.getByRole("combobox",{name:"Source asset consumer migration",exact:true}).selectOption("observation-table");if(kind==="stats")await fields.getByRole("combobox",{name:"Original selected asset history",exact:true}).selectOption(JSON.stringify(binding("context")));}
 await dialog.getByRole("checkbox").check();await expect(apply).toBeEnabled();const download=page.waitForEvent("download");await dialog.getByRole("button",{name:"Download mapping report",exact:true}).click();const file=await download,report=JSON.parse(readFileSync((await file.path())!,"utf8"));expect(report.source).toBe(source);expect(report.bindings.observations.table.assetConsumers).toBe("observation-table");expect(report.diagnostics.some((d:any)=>d.code==="native-observation-history"&&!d.blocking)).toBe(true);await apply.click();
 await page.getByRole("region",{name:"Widgets and layout",exact:true}).getByRole("button",{name:"Imported telemetry rows",exact:true}).click();const inspector=page.getByRole("region",{name:"The widget in hand",exact:true});await expect(inspector.getByRole("combobox",{name:"Observation view",exact:true})).toHaveValue("table");await expect(inspector.getByRole("combobox",{name:"Original observation time",exact:true})).toHaveValue("at");await page.getByRole("button",{name:"Save",exact:true}).click();const read=async()=>(await(await request.get(`/v1/records/build.page/${id}`,{headers})).json()).record;let saved:any;await expect.poll(async()=>{saved=await read();return saved.sections?.filter((s:any)=>s.widget==="observation").length;}).toBe(4);
 const table=saved.sections.find((s:any)=>s.observation?.kind==="table"),detail=saved.sections.find((s:any)=>s.widget==="detail");expect(detail.recordVariable).toBe(table.observation.assetOutput);expect(saved.document.variables[detail.recordVariable].source.port).toBe("asset");await page.getByRole("button",{name:"Review release",exact:true}).click();await page.getByRole("button",{name:"Check draft and dependencies",exact:true}).click();await page.getByRole("button",{name:"Save immutable candidate",exact:true}).click();table.observation.signals[0].unit="LATER";await decide(request,"manager","build","build.page.edit",{type:"build.page",id},{sections:saved.sections});await page.getByRole("button",{name:"Activate release",exact:true}).click();
 const runtime=await page.context().newPage();await stableReadRevision(runtime);await open(runtime,"desk",`/page?app=build&kind=page&name=${name}`);const section=(title:string)=>runtime.getByRole("heading",{name:title,exact:true,level:3}).locator(".."),rows=section("Imported telemetry rows"),stats=section("Imported complete statistics"),availability=section("Imported asset availability"),series=section("Imported actual time series"),assetDetail=section("Imported asset detail");await expect(rows).toContainText("Showing 100 of 106 matching records");await expect(stats).toContainText("106 observations · 106 numeric values in the original 10,000-row window");await expect(availability).toContainText("Complete authorized average · 89 % · 2 records");await expect(series.getByRole("group",{name:/by original event time/})).toHaveCount(3);await expect(rows).not.toContainText("LATER");await rows.getByRole("cell",{name:"S105",exact:true}).click();await expect(assetDetail).toContainText("Imported original asset B");await expect(stats).toContainText("Latest original sample · S105");const assetFilter=runtime.getByRole("textbox",{name:"Original asset name filter",exact:true});await assetFilter.fill(" B");await expect(availability).toContainText("Complete authorized average · 98 % · 1 records");await expect(stats).toContainText("106 observations");await expect(series.getByRole("img",{name:/^S105.*Pressure: 105 bar/})).toBeVisible();await assetFilter.fill("");await expect(availability).toContainText("89 % · 2 records");await rows.getByRole("button",{name:"Next",exact:true}).click();await expect(rows).toContainText("101–106");await expect(assetDetail).not.toContainText("Imported original asset B");await expect(stats).toContainText("106 observations");await expect(series.getByRole("img",{name:/^S105.*Pressure: 105 bar/})).toBeVisible();
 if(process.env.PLATFORM_SCREENSHOTS){await stats.screenshot({path:info.outputPath("imported-statistics.png")});await availability.screenshot({path:info.outputPath("imported-availability.png")});await runtime.setViewportSize({width:390,height:844});await runtime.evaluate(()=>new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve()))));await expect(series.getByRole("group",{name:"Pressure by original event time",exact:true})).toBeVisible();await series.screenshot({path:info.outputPath("imported-series-narrow.png")});}
});
