import {expect,test} from "@playwright/test";
import {decide,fresh,open,pageUIProfile,stableReadRevision} from "./host";

test("authored set sources retain fixed versions and combine beyond source windows after frozen activation",async({page,request},info)=>{
 test.setTimeout(60_000);
 const name=fresh("set").replace(/[^a-z0-9]/gi,"").toLowerCase(),type=`build.${name}`,object=fresh("OBJ"),queryID=fresh("QUERY"),id=fresh("PAGE"),ref={app:"build",kind:"object",name:type};
 await decide(request,"manager","build","build.object.create",{type:"build.object",id:object},{name,title:"Set notes",fields:[{name:"note",title:"Note",type:"text"},{name:"bucket",title:"Bucket",type:"text"}]});await decide(request,"manager","build","build.object.publish",{type:"build.object",id:object},{});
 for(const suffix of ["A1","A2","A3","B1","B2","C1"])await decide(request,"desk","build",`${type}.create`,{type,id:`${name}${suffix}`},{note:`SET-${suffix}`,bucket:suffix[0]});
 await decide(request,"manager","build","build.query.create",{type:"build.query",id:queryID},{name,title:"Fixed A source",description:"Keep the A predicate",object:type,domain:[["bucket","=","A"]],limit:1});await decide(request,"manager","build","build.query.publish",{type:"build.query",id:queryID},{});await decide(request,"manager","build","build.query.edit",{type:"build.query",id:queryID},{domain:[["bucket","=","C"]]});await decide(request,"manager","build","build.query.publish",{type:"build.query",id:queryID},{});
 const document={formatVersion:2,uiProfile:pageUIProfile,root:"root",nodes:{root:{kind:"rows",children:["input","table","detail","cards"]},input:{kind:"widget",section:"input",valueVariable:"bucket"},table:{kind:"widget",section:"table"},detail:{kind:"widget",section:"detail"},cards:{kind:"loop",title:"Set cards",children:["card"],loop:{collection:"window",itemVariable:"item",limit:2}},card:{kind:"widget",section:"card"}},variables:{bucket:{scope:"page",type:"string",mode:"state",initial:"B"},window:{scope:"page",type:"object-set",mode:"resource",source:{kind:"plan",query:"combined"}},item:{scope:"loop-item",owner:"cards",type:"record",mode:"resource",source:{kind:"item",node:"cards"}}},queries:{left:{title:"Fixed A",object:ref,limit:1,offset:1,query:{ref:{app:"build",kind:"query",name},sourceVersion:"1.query-1"}},right:{title:"Bucket source",object:ref,limit:1,conditions:[{field:"bucket",op:"=",value:{variable:"bucket"}}]},combined:{title:"Combined notes",object:ref,limit:2,sort:["id"]}}};
 await decide(request,"manager","build","build.page.create",{type:"build.page",id},{name,title:"Set desk",object:type,sections:[{id:"input",widget:"input",configVersion:1,title:"Set bucket"},{id:"table",widget:"table",configVersion:1,title:"Combined records",fields:["note"],collectionVariable:"window"},{id:"detail",widget:"detail",configVersion:1,title:"Selected set record",fields:["note"]},{id:"card",widget:"detail",configVersion:1,title:"Set card",fields:["note"],recordVariable:"item"}],document});
 await open(page,"manager",`/compose?id=${id}`);const tree=page.getByRole("region",{name:"Widgets and layout",exact:true}),inspector=page.getByRole("region",{name:"The widget in hand",exact:true});await tree.getByRole("button",{name:"Query plans",exact:true}).click();await inspector.getByRole("combobox",{name:"Choose query plan",exact:true}).selectOption("combined");await inspector.getByRole("combobox",{name:"Set operation",exact:true}).selectOption("union");await inspector.getByRole("combobox",{name:"Left set source",exact:true}).selectOption("left");await inspector.getByRole("combobox",{name:"Right set source",exact:true}).selectOption("right");await expect(inspector.getByText("Combine complete matching sets. Source sorting and windows do not limit membership; this result has its own window.",{exact:true})).toBeVisible();
 await page.getByRole("button",{name:"Save",exact:true}).click();await expect.poll(async()=>(await(await request.get(`/v1/records/build.page/${id}`,{headers:{Authorization:"Bearer manager"}})).json()).record.document.queries.combined.set?.op).toBe("union");await page.getByRole("button",{name:"Review release",exact:true}).click();await page.getByRole("button",{name:"Check draft and dependencies",exact:true}).click();await page.getByRole("button",{name:"Save immutable candidate",exact:true}).click();
 const saved=await(await request.get(`/v1/records/build.page/${id}`,{headers:{Authorization:"Bearer manager"}})).json();saved.record.document.queries.combined.set.op="subtract";await decide(request,"manager","build","build.page.edit",{type:"build.page",id},{document:saved.record.document});await page.getByRole("button",{name:"Activate release",exact:true}).click();
 const operation=await page.context().newPage();await stableReadRevision(operation);let posts=0;operation.on("request",r=>{if(r.method()==="POST"&&r.url().endsWith(`/v1/records/${type}/query`)){posts++;const body=r.postDataJSON();expect(body.set.op).toBe("union");expect(body.set.inputs[0].domain).toEqual([["bucket","=","A"]]);expect(body.set.inputs[0].limit).toBeUndefined();}});
 await open(operation,"desk",`/page?app=build&kind=page&name=${name}`);const table=operation.getByRole("table"),cards=operation.getByRole("list",{name:"Set cards",exact:true}),input=operation.getByRole("textbox",{name:"Set bucket",exact:true}),detail=operation.getByRole("heading",{name:"Selected set record",exact:true}).locator("..");await expect(table.getByText("SET-A1",{exact:true})).toBeVisible();await expect(cards.getByText("SET-A1",{exact:true})).toBeVisible();expect(posts).toBe(1);await expect(operation.getByText("1–2 of 5",{exact:true})).toBeVisible();await operation.getByRole("button",{name:"Next page",exact:true}).click();await expect(table.getByText("SET-A3",{exact:true})).toBeVisible();await expect(table.getByText("SET-B1",{exact:true})).toBeVisible();await expect(cards.getByText("SET-B1",{exact:true})).toBeVisible();
 await table.getByRole("row").filter({hasText:"SET-A3"}).click();await expect(detail.getByText("SET-A3",{exact:true})).toBeVisible();
 let release!:()=>void,delivered!:()=>void,held=false;const wait=new Promise<void>(resolve=>release=resolve),handled=new Promise<void>(resolve=>delivered=resolve);await operation.route(`**/v1/records/${type}/query`,async route=>{if(route.request().postDataJSON().set.inputs[1].domain[0][2]==="A"&&!held){const response=await route.fetch();held=true;await wait;await route.fulfill({response});delivered();}else await route.continue();});await input.fill("A");await expect.poll(()=>held).toBe(true);await expect(detail.getByText("Select a record to see it here.",{exact:true})).toBeVisible();await input.fill("C");await expect(operation.getByText("1–2 of 4",{exact:true})).toBeVisible();release();await handled;await operation.unroute(`**/v1/records/${type}/query`);await operation.getByRole("button",{name:"Next page",exact:true}).click();await expect(table.getByText("SET-C1",{exact:true})).toBeVisible();
 await operation.route(`**/v1/records/${type}/query`,route=>route.fulfill({status:403,contentType:"application/json",body:JSON.stringify({error:{message:"Denied"}})}));await input.fill("B");await expect(operation.getByRole("alert").filter({hasText:"Resource read failed"}).first()).toBeVisible();await expect(table.getByText("SET-C1",{exact:true})).toHaveCount(0);await operation.unroute(`**/v1/records/${type}/query`);await input.fill("C");await expect(operation.getByText("1–2 of 4",{exact:true})).toBeVisible();
 if(process.env.PLATFORM_SCREENSHOTS){await operation.screenshot({path:info.outputPath("set-query.png"),fullPage:true});await operation.setViewportSize({width:390,height:844});await operation.evaluate(()=>new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve()))));await operation.screenshot({path:info.outputPath("set-query-narrow.png"),fullPage:true});}
 await operation.reload();await expect(input).toHaveValue("B");await expect(operation.getByText("1–2 of 5",{exact:true})).toBeVisible();
});

test("an application editor authors a set shared by its page and resets it on instance close",async({page,request})=>{
 const name=fresh("appset").replace(/[^a-z0-9]/gi,"").toLowerCase(),type=`build.${name}`,object=fresh("OBJ"),id=fresh("PAGE"),app=fresh("APP"),ref={app:"build",kind:"object",name:type};
 await decide(request,"manager","build","build.object.create",{type:"build.object",id:object},{name,title:"App set notes",fields:[{name:"note",title:"Note",type:"text"},{name:"bucket",title:"Bucket",type:"text"}]});await decide(request,"manager","build","build.object.publish",{type:"build.object",id:object},{});for(const suffix of ["A1","A2","B1","B2","C1"])await decide(request,"desk","build",`${type}.create`,{type,id:`${name}${suffix}`},{note:`APPSET-${suffix}`,bucket:suffix[0]});
 await decide(request,"manager","build","build.page.create",{type:"build.page",id},{name,title:"Application set desk",object:type,sections:[{id:"input",widget:"input",configVersion:1,title:"Shared set bucket"},{id:"table",widget:"table",configVersion:1,title:"Shared set",fields:["note"],collectionVariable:"window"},{id:"metric",widget:"metric",configVersion:1,title:"Shared set count",measure:"count",collectionVariable:"window"}],document:{formatVersion:2,uiProfile:pageUIProfile,root:"root",nodes:{root:{kind:"rows",children:["input","table","metric"]},metric:{kind:"widget",section:"metric"},input:{kind:"widget",section:"input",valueVariable:"bucket"},table:{kind:"widget",section:"table"}},variables:{bucket:{scope:"application",type:"string",mode:"shared",writable:true,source:{kind:"application",variable:"bucket"}},window:{scope:"application",type:"object-set",mode:"shared",source:{kind:"application",variable:"window",object:ref}}}}});await decide(request,"manager","build","build.page.publish",{type:"build.page",id},{});
 await decide(request,"manager","build","build.app.create",{type:"build.app",id:app},{name:`${name}app`,title:"Application sets",pages:[name],uiProfile:pageUIProfile,variables:{bucket:{scope:"application",type:"string",mode:"state",initial:"B"},window:{scope:"application",type:"object-set",mode:"resource",source:{kind:"plan",query:"combined"}}},queries:{left:{title:"A source",object:ref,limit:1,conditions:[{field:"bucket",op:"=",value:{literal:"A"}}]},right:{title:"Parameter source",object:ref,limit:1,conditions:[{field:"bucket",op:"=",value:{variable:"bucket"}}]},combined:{title:"App combination",object:ref,limit:10}}});
 await open(page,"manager",`/application?id=${app}`);await page.getByRole("combobox",{name:"Choose query plan",exact:true}).selectOption("combined");await page.getByRole("combobox",{name:"Set operation",exact:true}).selectOption("union");await page.getByRole("combobox",{name:"Left set source",exact:true}).selectOption("left");await page.getByRole("combobox",{name:"Right set source",exact:true}).selectOption("right");await page.getByRole("button",{name:"Save application",exact:true}).click();await expect.poll(async()=>(await(await request.get(`/v1/records/build.app/${app}`,{headers:{Authorization:"Bearer manager"}})).json()).record.queries.combined.set?.op).toBe("union");await page.getByRole("button",{name:"Review application release",exact:true}).click();await page.getByRole("button",{name:"Check draft and dependencies",exact:true}).click();await page.getByRole("button",{name:"Save immutable candidate",exact:true}).click();await page.getByRole("button",{name:"Activate release",exact:true}).click();
 const operation=await page.context().newPage();await stableReadRevision(operation);const route=`/page?app=build&kind=page&name=${name}&application=build:${name}app&instance=main`;await open(operation,"desk",route);const table=operation.getByRole("table"),input=operation.getByRole("textbox",{name:"Shared set bucket",exact:true}),metric=operation.getByRole("heading",{name:"Shared set count",exact:true}).locator("..");await expect(metric.getByText("4",{exact:true})).toBeVisible();await expect(table.getByText("APPSET-A2",{exact:true})).toBeVisible();await expect(table.getByText("APPSET-B1",{exact:true})).toBeVisible();await input.fill("C");await expect(metric.getByText("3",{exact:true})).toBeVisible();await expect(table.getByText("APPSET-C1",{exact:true})).toBeVisible();await expect(table.getByText("APPSET-B1",{exact:true})).toHaveCount(0);await operation.getByRole("button",{name:"Close application instance",exact:true}).click();await operation.evaluate(route=>{location.hash=route},route);await expect(input).toHaveValue("B");await expect(metric.getByText("4",{exact:true})).toBeVisible();await expect(table.getByText("APPSET-B1",{exact:true})).toBeVisible();
});
