import {expect,test} from "@playwright/test";
import {decide,fresh,open,pageUIProfile,stableReadRevision} from "./host";

test("a frozen lifecycle board uses original move forms and retires cards and selection with its query window",async({page,request},testInfo)=>{
 test.setTimeout(90_000);
 const name=fresh("board").replace(/[^a-z0-9]/gi,"").toLowerCase(),type=`build.${name}`,object=fresh("OBJ"),id=fresh("PAGE"),ref={app:"build",kind:"object",name:type};
 await decide(request,"manager","build","build.object.create",{type:"build.object",id:object},{name,title:"Board work",fields:[{name:"title",title:"Title",type:"text"},{name:"team",title:"Team",type:"text"}],states:[{name:"open",title:"Open"},{name:"done",title:"Done"}],actions:[{name:"close",title:"Complete card",from:["open"],to:"done",inputs:[{name:"reason",title:"Completion note",type:"text",required:true}]}]});await decide(request,"manager","build","build.object.publish",{type:"build.object",id:object},{});
 for(const [suffix,team] of [["A1","A"],["A2","A"],["B1","B"],["C1","C"],["D1","D"]])await decide(request,"desk","build",`${type}.create`,{type,id:`${name}${suffix}`},{title:`CARD-${suffix}`,team});
 await decide(request,"manager","build","build.page.create",{type:"build.page",id},{name,title:"Board desk",object:type,sections:[{id:"input",widget:"input",configVersion:1,title:"Board team"},{id:"detail",widget:"detail",configVersion:1,title:"Selected card",fields:["title","state"]}],document:{formatVersion:2,uiProfile:pageUIProfile,root:"root",nodes:{root:{kind:"rows",children:["input","detail"]},input:{kind:"widget",section:"input",valueVariable:"team"},detail:{kind:"widget",section:"detail"}},variables:{team:{scope:"page",type:"string",mode:"state",initial:"A"},window:{scope:"page",type:"object-set",mode:"resource",title:"Board window",source:{kind:"plan",query:"cards"}}},queries:{cards:{object:ref,limit:1,sort:["id"],conditions:[{field:"team",op:"=",value:{variable:"team"}}]}}}});
 await open(page,"manager",`/compose?id=${id}`);const tree=page.getByRole("region",{name:"Widgets and layout",exact:true}),inspector=page.getByRole("region",{name:"The widget in hand",exact:true});
 await tree.getByRole("button",{name:"Kanban board",exact:true}).click();await inspector.getByLabel("Title",{exact:true}).fill("Work board");await inspector.getByRole("combobox",{name:"Kanban query window",exact:true}).selectOption("window");await inspector.getByRole("combobox",{name:"Card title field",exact:true}).selectOption("title");await inspector.getByRole("button",{name:"Team",exact:true}).click();await inspector.getByRole("button",{name:"Complete card → Done",exact:true}).click();
 if(process.env.PLATFORM_SCREENSHOTS)await inspector.screenshot({path:testInfo.outputPath("kanban-inspector.png")});
 await page.getByRole("button",{name:"Save",exact:true}).click();let saved:any;await expect.poll(async()=>{saved=(await(await request.get(`/v1/records/build.page/${id}`,{headers:{Authorization:"Bearer manager"}})).json()).record;return saved.sections.find((s:any)=>s.widget==="kanban")?.actions;}).toEqual([`${type}.close`]);
 await page.getByRole("button",{name:"Review release",exact:true}).click();await page.getByRole("button",{name:"Check draft and dependencies",exact:true}).click();await page.getByRole("button",{name:"Save immutable candidate",exact:true}).click();saved.sections.find((s:any)=>s.widget==="kanban").actions=[];saved.sections.find((s:any)=>s.widget==="kanban").cardLabel="id";await decide(request,"manager","build","build.page.edit",{type:"build.page",id},{sections:saved.sections});await page.getByRole("button",{name:"Activate release",exact:true}).click();
 const operation=await page.context().newPage();await stableReadRevision(operation);await open(operation,"desk",`/page?app=build&kind=page&name=${name}`);
 const board=operation.getByRole("heading",{name:"Work board",exact:true}).locator(".."),openLane=board.getByRole("region",{name:"Open",exact:true}),doneLane=board.getByRole("region",{name:"Done",exact:true}),input=operation.getByRole("textbox",{name:"Board team",exact:true}),detail=operation.getByRole("heading",{name:"Selected card",exact:true}).locator("..");
 await expect(openLane.getByRole("button",{name:"CARD-A1",exact:true})).toBeVisible();await expect(board).toContainText("Showing 1 of 2 matching records");await openLane.getByRole("button",{name:"CARD-A1",exact:true}).click();await expect(detail.getByText("CARD-A1",{exact:true})).toBeVisible();
 await openLane.getByRole("button",{name:"CARD-A1",exact:true}).locator('xpath=ancestor::*[@draggable="true"]').dragTo(doneLane);
 const dialog=operation.getByRole("dialog",{name:`Complete card ${name}A1`,exact:true});await expect(dialog).toBeVisible();expect((await(await request.get(`/v1/records/${type}/${name}A1`,{headers:{Authorization:"Bearer desk"}})).json()).record.state).toBe("open");await dialog.getByRole("textbox",{name:"Completion note *",exact:true}).fill("Finished through the original action");await dialog.getByRole("button",{name:"Complete card",exact:true}).click();await expect(doneLane.getByRole("button",{name:"CARD-A1",exact:true})).toBeVisible();
 await board.getByRole("button",{name:"Next",exact:true}).click();await expect(openLane.getByRole("button",{name:"CARD-A2",exact:true})).toBeVisible();await expect(detail.getByText("CARD-A1",{exact:true})).toHaveCount(0);
 await openLane.getByRole("combobox",{name:"Move CARD-A2 with action",exact:true}).selectOption(`${type}.close`);const second=operation.getByRole("dialog",{name:`Complete card ${name}A2`,exact:true});await expect(second).toBeVisible();await decide(request,"manager","build",`${type}.close`,{type,id:`${name}A2`},{reason:"Remote completion"});await second.getByRole("textbox",{name:"Completion note *",exact:true}).fill("Local completion");await second.getByRole("button",{name:"Complete card",exact:true}).click();await expect(second.getByRole("alert")).toContainText(/CONFLICT|revision|changed/i);await expect(second.getByRole("textbox",{name:"Completion note *",exact:true})).toHaveValue("Local completion");await second.getByRole("button",{name:"Cancel",exact:true}).click();await input.fill("B");await expect(second).toHaveCount(0);await expect(openLane.getByRole("button",{name:"CARD-B1",exact:true})).toBeVisible();
 let release!:()=>void,delivered!:()=>void,held=false;const gate=new Promise<void>(r=>release=r),done=new Promise<void>(r=>delivered=r);await operation.route(`**/v1/records/${type}*`,async route=>{if(new URL(route.request().url()).searchParams.get("domain")?.includes('"C"')){const response=await route.fetch();held=true;await gate;await route.fulfill({response});delivered();}else await route.continue();});await input.fill("C");await expect.poll(()=>held).toBe(true);await expect(openLane.getByRole("button",{name:"CARD-B1",exact:true})).toHaveCount(0);await input.fill("D");await expect(openLane.getByRole("button",{name:"CARD-D1",exact:true})).toBeVisible();release();await done;await operation.unroute(`**/v1/records/${type}*`);await expect(board.getByRole("button",{name:"CARD-C1",exact:true})).toHaveCount(0);
 await operation.route(`**/v1/records/${type}*`,route=>route.fulfill({status:403,contentType:"application/json",body:JSON.stringify({error:{message:"Denied"}})}));await input.fill("B");await expect(board.getByRole("alert")).toBeVisible();await expect(board.getByRole("button",{name:"CARD-D1",exact:true})).toHaveCount(0);await operation.unroute(`**/v1/records/${type}*`);await input.fill("A");await expect(doneLane.getByRole("button",{name:"CARD-A1",exact:true})).toBeVisible();
 if(process.env.PLATFORM_SCREENSHOTS){await board.scrollIntoViewIfNeeded();await operation.screenshot({path:testInfo.outputPath("kanban-runtime.png"),fullPage:true});await operation.setViewportSize({width:390,height:844});await operation.evaluate(()=>new Promise<void>(r=>requestAnimationFrame(()=>requestAnimationFrame(()=>r()))));await board.scrollIntoViewIfNeeded();await operation.screenshot({path:testInfo.outputPath("kanban-runtime-narrow.png"),fullPage:true});}
 await operation.reload();await expect(input).toHaveValue("A");await expect(doneLane.getByRole("button",{name:"CARD-A1",exact:true})).toBeVisible();
});
