import {expect,test} from "@playwright/test";
import {decide,fresh,open,pageUIProfile} from "./host";

test("an authored overlay query shares its local table and loop, isolates selections and drops closed-scope responses",async({page,request},testInfo)=>{
 test.setTimeout(60_000);
 const name=fresh("picker").replace(/[^a-z0-9]/gi,"").toLowerCase(),type=`build.${name}`,object=fresh("OBJ"),id=fresh("PAGE");
 await decide(request,"manager","build","build.object.create",{type:"build.object",id:object},{name,title:"Picker notes",fields:[{name:"note",title:"Note",type:"text"},{name:"bucket",title:"Bucket",type:"text"}],states:[{name:"open",title:"Open"},{name:"done",title:"Done"}],actions:[{name:"close",title:"Complete picked note",from:["open"],to:"done"}]});
 await decide(request,"manager","build","build.object.publish",{type:"build.object",id:object},{});
 for(const [suffix,bucket] of [["A1","A"],["A2","A"],["A3","A"],["B","B"]])await decide(request,"desk","build",`${type}.create`,{type,id:`${name}${suffix}`},{note:`PICK-${suffix}`,bucket});
 await decide(request,"manager","build","build.page.create",{type:"build.page",id},{name,title:"Overlay selection desk",object:type,
 sections:[{id:"main",widget:"table",configVersion:1,title:"Page notes",fields:["note","bucket"]},{id:"pageDetail",widget:"detail",configVersion:1,title:"Page selection",fields:["note"]},{id:"trigger",widget:"button",configVersion:1,title:"Open picker"},{id:"parameter",widget:"input",configVersion:1,title:"Picker bucket"},{id:"local",widget:"table",configVersion:1,title:"Local notes",fields:["note","bucket"]},{id:"localDetail",widget:"detail",configVersion:1,title:"Local selection",fields:["note"]},{id:"card",widget:"detail",configVersion:1,title:"Picker card",fields:["note"]},{id:"actions",widget:"actions",configVersion:1,title:"Picked work",actions:[`${type}.close`]},{id:"close",widget:"button",configVersion:1,title:"Close picker"}],
 document:{formatVersion:2,uiProfile:pageUIProfile,root:"root",nodes:{root:{kind:"rows",children:["main","pageDetail","trigger"]},main:{kind:"widget",section:"main"},pageDetail:{kind:"widget",section:"pageDetail"},trigger:{kind:"widget",section:"trigger"},picker:{kind:"rows",children:["parameter","local","localDetail","cards","close"]},parameter:{kind:"widget",section:"parameter",valueVariable:"bucket"},local:{kind:"widget",section:"local"},localDetail:{kind:"widget",section:"localDetail"},cards:{kind:"rows",title:"Picker cards",children:["card","actions"]},card:{kind:"widget",section:"card"},actions:{kind:"widget",section:"actions"},close:{kind:"widget",section:"close"}},overlays:{picker:{root:"picker",kind:"modal",title:"Find a note",openVariable:"open"}},variables:{open:{scope:"page",type:"boolean",mode:"state",initial:false},bucket:{scope:"overlay",owner:"picker",type:"string",mode:"state",initial:"A"},picked:{title:"Picked record",scope:"overlay",owner:"picker",type:"record",mode:"resource",source:{kind:"record",section:"local"}}},events:[{source:"trigger",event:"click",target:"open",value:true},{source:"close",event:"click",target:"open",value:false}]}});
 await open(page,"manager",`/compose?id=${id}`);
 const tree=page.getByRole("region",{name:"Widgets and layout",exact:true}),inspector=page.getByRole("region",{name:"The widget in hand",exact:true}),canvas=page.getByRole("region",{name:"The page",exact:true});
 await tree.getByRole("button",{name:"Query plans",exact:true}).click();await inspector.getByRole("button",{name:"Add query plan",exact:true}).click();
 await inspector.getByRole("combobox",{name:"Query scope",exact:true}).selectOption("picker");
 await inspector.getByLabel("Query title",{exact:true}).fill("Picker query");await inspector.getByLabel("Query window limit",{exact:true}).fill("2");
 await inspector.getByRole("button",{name:"Add query condition",exact:true}).click();await inspector.getByRole("combobox",{name:"Query condition field",exact:true}).selectOption("bucket");await inspector.getByRole("combobox",{name:"Query condition value",exact:true}).selectOption("bucket");
 await tree.getByRole("button",{name:"Local notes",exact:true}).click();await inspector.getByRole("combobox",{name:"Table query window",exact:true}).selectOption({index:1});
 await tree.getByRole("button",{name:"Local selection",exact:true}).click();await inspector.getByRole("combobox",{name:"Input record binding",exact:true}).selectOption("picked");
 await tree.getByRole("button",{name:/^Rows/}).last().click();await inspector.getByRole("combobox",{name:"Layout",exact:true}).selectOption("loop");
 await expect(canvas.getByRole("list",{name:"Picker cards",exact:true}).getByText("PICK-A1",{exact:true})).toBeVisible();
 await page.getByRole("button",{name:"Save",exact:true}).click();await expect(page.getByRole("button",{name:"Save",exact:true})).toBeDisabled();
 await page.getByRole("button",{name:"Review release",exact:true}).click();await page.getByRole("button",{name:"Check draft and dependencies",exact:true}).click();await page.getByRole("button",{name:"Save immutable candidate",exact:true}).click();await page.getByRole("button",{name:"Activate release",exact:true}).click();
 const operation=await page.context().newPage();let ownedReads=0;operation.on("request",req=>{const u=new URL(req.url());if(u.pathname===`/v1/records/${type}`&&u.searchParams.has("domain"))ownedReads++;});
 await open(operation,"desk",`/page?app=build&kind=page&name=${name}`);
 const main=operation.getByRole("table");await main.getByRole("row").filter({hasText:"PICK-B"}).click();const pageSelection=operation.getByRole("heading",{name:"Page selection",exact:true,includeHidden:true}).locator("..");await expect(pageSelection.getByText("PICK-B",{exact:true})).toBeVisible();expect(ownedReads).toBe(0);
 await operation.getByRole("button",{name:"Open picker",exact:true}).click();const dialog=operation.getByRole("dialog",{name:"Find a note",exact:true}),table=dialog.getByRole("table"),cards=dialog.getByRole("list",{name:"Picker cards",exact:true}),localSelection=dialog.getByRole("heading",{name:"Local selection",exact:true}).locator("..");
 await expect(table.getByText("PICK-A1",{exact:true})).toBeVisible();await expect(cards.getByText("PICK-A1",{exact:true})).toBeVisible();expect(ownedReads).toBe(1);
 await table.getByRole("row").filter({hasText:"PICK-A1"}).click();await expect(localSelection.getByText("PICK-A1",{exact:true})).toBeVisible();await expect(pageSelection.getByText("PICK-B",{exact:true})).toBeVisible();
 await dialog.getByRole("button",{name:"Next page",exact:true}).click();await expect(table.getByText("PICK-A3",{exact:true})).toBeVisible();await expect(localSelection.getByText("Select a record to see it here.",{exact:true})).toBeVisible();
 if(process.env.PLATFORM_SCREENSHOTS)await operation.screenshot({path:testInfo.outputPath("overlay-query-runtime.png"),fullPage:true});
 let release!:()=>void,held=false;const wait=new Promise<void>(resolve=>release=resolve);
 await operation.route(`**/v1/records/${type}?*`,async route=>{const domain=new URL(route.request().url()).searchParams.get("domain")??"";if(domain.includes('"B"')&&!held){const response=await route.fetch();held=true;await wait;await route.fulfill({response});}else await route.continue();});
 await dialog.getByRole("textbox",{name:"Picker bucket",exact:true}).fill("B");await expect.poll(()=>held).toBe(true);
 await dialog.getByRole("button",{name:"Close picker",exact:true}).click();await expect(dialog).not.toBeVisible();await operation.getByRole("button",{name:"Open picker",exact:true}).click();
 await expect(dialog.getByRole("textbox",{name:"Picker bucket",exact:true})).toHaveValue("A");await expect(table.getByText("PICK-A1",{exact:true})).toBeVisible();release();await expect(table.getByText("PICK-B",{exact:true})).toHaveCount(0);await expect(localSelection.getByText("Select a record to see it here.",{exact:true})).toBeVisible();await expect(pageSelection.getByText("PICK-B",{exact:true})).toBeVisible();
 await operation.unroute(`**/v1/records/${type}?*`);
 await cards.getByRole("button",{name:"Complete picked note",exact:true}).first().click();await expect.poll(async()=>(await(await request.get(`/v1/records/${type}/${name}A1`,{headers:{Authorization:"Bearer desk"}})).json()).record.state).toBe("done");
 if(process.env.PLATFORM_SCREENSHOTS){await operation.setViewportSize({width:390,height:844});await operation.evaluate(()=>new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve()))));await operation.screenshot({path:testInfo.outputPath("overlay-query-runtime-narrow.png"),fullPage:true});}
 await operation.reload();await expect(operation.getByRole("dialog",{name:"Find a note",exact:true})).not.toBeVisible();await operation.getByRole("button",{name:"Open picker",exact:true}).click();await expect(operation.getByRole("textbox",{name:"Picker bucket",exact:true})).toHaveValue("A");
});
