import {expect,test} from "@playwright/test";
import {readFileSync} from "node:fs";
import {decide,fresh,open,pageUIProfile,stableReadRevision} from "./host";

test("imported plain headings and collection titles freeze their text and complete counts with permissions and query scope",async({page,request},info)=>{
 test.setTimeout(90_000);
 const name=fresh("titles").replace(/[^a-z0-9]/gi,"").toLowerCase(),type=`build.${name}`,object=fresh("OBJ"),id=fresh("PAGE");
 await decide(request,"manager","build","build.object.create",{type:"build.object",id:object},{name,title:"Title assets",fields:[{name:"note",title:"Note",type:"text"},{name:"secret",title:"Private note",type:"text",read:["builder"]}]});await decide(request,"manager","build","build.object.publish",{type:"build.object",id:object},{});for(const suffix of ["A1","A2","A3","B1","B2","C1"])await decide(request,"manager","build",`${type}.create`,{type,id:`${name}${suffix}`},{note:`TITLE-${suffix}`,secret:"hidden"});
 const m=JSON.parse(readFileSync(new URL("../../packages/build/src/module-import/sample.workshop.json",import.meta.url),"utf8"));m.widgets={table:m.widgets.table,input:{id:"input",name:"Title filter",type:"TextInput",config:{variableId:"scratch",label:"Title filter"}},heading:{id:"heading",name:"Imported heading",type:"HeaderText",config:{text:"<b>Operational overview</b>",variant:"h2"}},title:{id:"title",name:"Collection heading",type:"ObjectSetTitle",config:{objectSetVarId:"notes"}},privateTitle:{id:"privateTitle",name:"Private heading",type:"ObjectSetTitle",config:{objectSetVarId:"privateNotes"}}};delete m.widgets.table.config.activeVarId;m.sections={root:{id:"root",name:"Root",layout:"rows",children:["heading","input","title","table","privateTitle"].map(id=>({kind:"widget",id}))}};m.variables=m.variables.filter((v:any)=>v.id!=="selected");m.variables.find((v:any)=>v.id==="scratch").staticValue="";m.variables.find((v:any)=>v.id==="notes").name="Permitted assets";m.variables.find((v:any)=>v.id==="notes").objectSet.steps=[{op:"where",clauses:[{id:"filter",property:"name",op:"contains",varId:"scratch"}]}];m.variables.push({id:"privateNotes",name:"Private collection",type:"objectSet",definitionKind:"objectSetDefinition",sourceObjectType:"Asset",objectSet:{objectType:"Asset",steps:[{op:"where",clauses:[{id:"private",property:"secret",op:"is",value:"hidden"}]}]}});
 await decide(request,"manager","build","build.page.create",{type:"build.page",id},{name,title:"Collection title page",object:type,sections:[{id:"initial",widget:"table",configVersion:1,fields:["note"]}],document:{formatVersion:2,uiProfile:pageUIProfile,root:"root",nodes:{root:{kind:"rows",children:["initial"]},initial:{kind:"widget",section:"initial"}}}});
 await open(page,"manager",`/compose?id=${id}`);await page.getByRole("button",{name:"Import Workshop module",exact:true}).click();const dialog=page.getByRole("dialog",{name:"Import Workshop module",exact:true});await dialog.getByRole("textbox",{name:"Source module JSON",exact:true}).fill(JSON.stringify(m));await dialog.getByRole("combobox",{name:"Map object Asset",exact:true}).selectOption(type);await dialog.getByRole("combobox",{name:"Map field Asset.name",exact:true}).selectOption("note");await dialog.getByRole("combobox",{name:"Map field Asset.secret",exact:true}).selectOption("secret");await dialog.getByRole("checkbox").check();await dialog.getByRole("button",{name:"Apply imported page draft",exact:true}).click();
 const tree=page.getByRole("region",{name:"Widgets and layout",exact:true}),inspector=page.getByRole("region",{name:"The widget in hand",exact:true});await tree.getByRole("button",{name:"Imported heading",exact:true}).click();await inspector.getByRole("textbox",{name:"Heading text",exact:true}).fill("Frozen <b>overview</b>");await inspector.getByRole("combobox",{name:"Heading level",exact:true}).selectOption("h3");await tree.getByRole("button",{name:"Permitted assets",exact:true}).click();await expect(inspector.getByRole("combobox",{name:"Collection count variable",exact:true})).toBeVisible();await page.getByRole("button",{name:"Save",exact:true}).click();let saved:any;await expect.poll(async()=>{saved=(await(await request.get(`/v1/records/build.page/${id}`,{headers:{Authorization:"Bearer manager"}})).json()).record;return saved.sections?.find((s:any)=>s.widget==="heading")?.text;}).toBe("Frozen <b>overview</b>");for(const query of Object.values(saved.document.queries) as any[])query.limit=1;await decide(request,"manager","build","build.page.edit",{type:"build.page",id},{document:saved.document});await page.reload();
 await page.getByRole("button",{name:"Review release",exact:true}).click();await page.getByRole("button",{name:"Check draft and dependencies",exact:true}).click();await page.getByRole("button",{name:"Save immutable candidate",exact:true}).click();saved.sections.find((s:any)=>s.widget==="heading").text="Later heading";saved.sections.find((s:any)=>s.widget==="heading").headingLevel="h1";await decide(request,"manager","build","build.page.edit",{type:"build.page",id},{sections:saved.sections});await page.getByRole("button",{name:"Activate release",exact:true}).click();
 const runtime=await page.context().newPage();await stableReadRevision(runtime);let reads=0;runtime.on("request",r=>{const url=new URL(r.url());if(url.pathname===`/v1/aggregates/${type}`){reads++;expect(url.searchParams.get("measure")).toBe("count");expect(url.searchParams.has("limit")).toBe(false);expect(url.searchParams.has("offset")).toBe(false);}});await open(runtime,"desk",`/page?app=build&kind=page&name=${name}`);const title=runtime.getByRole("group",{name:"Permitted assets",exact:true}),count=title.getByRole("status",{name:"Complete collection count",exact:true}),input=runtime.getByRole("textbox",{name:"Title filter",exact:true});await expect(runtime.getByRole("heading",{name:"Frozen <b>overview</b>",level:3,exact:true})).toBeVisible();await expect(runtime.locator("b").filter({hasText:"overview"})).toHaveCount(0);await expect(count).toHaveText("6");await expect(runtime.getByRole("group",{name:"Private collection",exact:true})).toHaveCount(0);await expect(runtime.getByText("1–1 of 6",{exact:true})).toBeVisible();expect(reads).toBeGreaterThan(0);const before=reads;await runtime.getByRole("button",{name:"Next page",exact:true}).click();await expect(runtime.getByText("2–2 of 6",{exact:true})).toBeVisible();await expect(count).toHaveText("6");expect(reads).toBe(before);
 if(process.env.PLATFORM_SCREENSHOTS){await title.screenshot({path:info.outputPath("collection-title.png")});await runtime.setViewportSize({width:390,height:844});await runtime.evaluate(()=>new Promise<void>(r=>requestAnimationFrame(()=>requestAnimationFrame(()=>r()))));await title.scrollIntoViewIfNeeded();await title.screenshot({path:info.outputPath("collection-title-narrow.png")});await runtime.setViewportSize({width:1280,height:720});}
 await input.fill("TITLE-A");await expect(count).toHaveText("3");await input.fill("NO-MATCH");await expect(count).toHaveText("0");await runtime.route(`**/v1/aggregates/${type}**`,route=>route.fulfill({status:403,contentType:"application/json",body:JSON.stringify({error:{message:"Denied"}})}));await input.fill("TITLE-B");await expect(title.getByRole("alert")).toBeVisible();await expect(count).toHaveCount(0);await runtime.unroute(`**/v1/aggregates/${type}**`);await input.fill("");await expect(count).toHaveText("6");await runtime.reload();await expect(count).toHaveText("6");await expect(runtime.getByRole("heading",{name:"Frozen <b>overview</b>",level:3,exact:true})).toBeVisible();
});
