import {expect,test,type Locator} from "@playwright/test";
import {readFileSync} from "node:fs";
import {decide,fresh,open,pageUIProfile,stableReadRevision} from "./host";

async function move(slider:Locator,tick:number){
 await slider.evaluate((node,value)=>{const input=node as HTMLInputElement;Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,"value")!.set!.call(input,String(value));input.dispatchEvent(new Event("input",{bubbles:true}));input.dispatchEvent(new Event("change",{bubbles:true}));},tick);
}
test("default pressure range freezes original shared drafts and query bounds while invalid text, denied reads and overlay retirement clear old results",async({page,request},info)=>{
 test.setTimeout(90_000);
 const name=fresh("ranges").replace(/[^a-z0-9]/gi,"").toLowerCase(),type=`build.${name}`,object=fresh("OBJ"),id=fresh("PAGE");
 await decide(request,"manager","build","build.object.create",{type:"build.object",id:object},{name,title:"Pressure assets",fields:[{name:"note",title:"Name",type:"text"},{name:"pressure",title:"Pressure",type:"decimal"},{name:"privatepressure",title:"Private pressure",type:"decimal",read:["builder"]}]});
 await decide(request,"manager","build","build.object.publish",{type:"build.object",id:object},{});
 for(const pressure of [0,10,20,30,50])await decide(request,"manager","build",`${type}.create`,{type,id:`${name}${pressure}`},{note:`PUMP-${pressure}`,pressure,privatepressure:pressure});
 const m=JSON.parse(readFileSync(new URL("../../packages/build/src/workshop/module-import/sample.workshop.json",import.meta.url),"utf8"));
 const variable=(id:string)=>({id,name:id,type:"numeric",definitionKind:"static",staticValue:""}),clauses=(lower:string,upper:string,field="pressure")=>[{id:"lo",property:field,op:"isGreaterThanOrEqualTo",varId:lower},{id:"hi",property:field,op:"isLessThanOrEqualTo",varId:upper}],range=(id:string,label:string,lower:string,upper:string)=>({id,name:`${label} limits`,type:"RangeSlider",config:{minVarId:lower,maxVarId:upper,min:0,max:45,label,unit:"bar"}}),input=(id:string,label:string,variableId:string)=>({id,name:label,type:"NumericInput",config:{variableId,label}});
 m.variables.push(...["pressureMin","pressureMax","localMin","localMax"].map(variable));m.variables.find((v:any)=>v.id==="notes").objectSet.steps=[{op:"where",clauses:clauses("pressureMin","pressureMax")}];
 m.variables.push({id:"privateNotes",name:"Private assets",type:"objectSet",definitionKind:"objectSetDefinition",sourceObjectType:"Asset",objectSet:{objectType:"Asset",steps:[{op:"where",clauses:clauses("pressureMin","pressureMax","privatepressure")}]}},{id:"localNotes",name:"Local assets",type:"objectSet",definitionKind:"objectSetDefinition",sourceObjectType:"Asset",objectSet:{objectType:"Asset",steps:[{op:"where",clauses:clauses("localMin","localMax")}]}},{id:"localSelected",name:"Local selection",type:"object",definitionKind:"widgetOutput",widgetId:"localTable",widgetOutputKey:"activeObject"});
 m.widgets.range=range("range","Pressure","pressureMin","pressureMax");m.widgets.lower=input("lower","Lower pressure","pressureMin");m.widgets.upper=input("upper","Upper pressure","pressureMax");m.widgets.localRange=range("localRange","Local pressure","localMin","localMax");m.widgets.localLower=input("localLower","Local lower pressure","localMin");m.widgets.localUpper=input("localUpper","Local upper pressure","localMax");m.widgets.privateTable={...m.widgets.table,id:"privateTable",name:"Hidden pressure table",config:{...m.widgets.table.config,objectSetVarId:"privateNotes",activeVarId:undefined}};m.widgets.localTable={...m.widgets.table,id:"localTable",name:"Local pressure table",config:{...m.widgets.table.config,objectSetVarId:"localNotes",activeVarId:"localSelected"}};m.widgets.localDetail={...m.widgets.detail,id:"localDetail",name:"Local selection",config:{...m.widgets.detail.config,objectVarId:"localSelected"}};
 m.widgets.trigger={id:"trigger",name:"Open pressure",type:"SingleButton",config:{label:"Open pressure",eventActions:[{kind:"openOverlay",overlayId:"panel"}]}};m.widgets.close={id:"close",name:"Close pressure",type:"SingleButton",config:{label:"Close pressure",eventActions:[{kind:"closeOverlay",overlayId:"panel"}]}};
 m.sections={root:{id:"root",name:"Root",layout:"rows",children:["range","lower","upper","table","detail","privateTable","trigger"].map(id=>({kind:"widget",id}))},panel:{id:"panel",name:"Panel",layout:"rows",children:["localRange","localLower","localUpper","localTable","localDetail","close"].map(id=>({kind:"widget",id}))}};m.overlays=[{id:"panel",name:"Pressure panel",kind:"drawer",rootSectionId:"panel"}];
 await decide(request,"manager","build","build.page.create",{type:"build.page",id},{name,title:"Imported ranges",object:type,sections:[{id:"initial",widget:"text",configVersion:1,text:"Initial"}],document:{formatVersion:2,uiProfile:pageUIProfile,root:"root",nodes:{root:{kind:"rows",children:["initial"]},initial:{kind:"widget",section:"initial"}}}});
 await open(page,"manager",`/compose?id=${id}`);await page.getByRole("button",{name:"Import Workshop module",exact:true}).click();const dialog=page.getByRole("dialog",{name:"Import Workshop module",exact:true});await dialog.getByRole("textbox",{name:"Source module JSON",exact:true}).fill(JSON.stringify(m));await dialog.getByRole("combobox",{name:"Map object Asset",exact:true}).selectOption(type);for(const [source,target] of [["name","note"],["pressure","pressure"],["privatepressure","privatepressure"]])await dialog.getByRole("combobox",{name:`Map field Asset.${source}`,exact:true}).selectOption(target);await dialog.getByRole("checkbox").check();await dialog.getByRole("button",{name:"Apply imported page draft",exact:true}).click();
 const tree=page.getByRole("region",{name:"Widgets and layout",exact:true}),inspector=page.getByRole("region",{name:"The widget in hand",exact:true});await tree.getByRole("button",{name:"Pressure limits",exact:true}).click();await expect(inspector.getByRole("textbox",{name:"Range unit",exact:true})).toHaveValue("bar");await inspector.getByRole("textbox",{name:"Range step",exact:true}).fill("0.7");await expect(page.getByRole("button",{name:"Save",exact:true})).toBeDisabled();await inspector.getByRole("textbox",{name:"Range step",exact:true}).fill("1");await page.getByRole("button",{name:"Save",exact:true}).click();let saved:any;await expect.poll(async()=>{saved=(await(await request.get(`/v1/records/build.page/${id}`,{headers:{Authorization:"Bearer manager"}})).json()).record;return saved.sections?.filter((s:any)=>s.widget==="range-input").length;}).toBe(2);
 const main=saved.sections.find((s:any)=>s.title==="Pressure limits"),lower=saved.sections.find((s:any)=>s.title==="Lower pressure"),node=Object.values(saved.document.nodes).find((n:any)=>n.section===lower.id) as any;expect(node.valueVariable).toBe(main.rangeMinVariable);expect(saved.document.variables[main.rangeMinVariable].initial).toBe("");await page.getByRole("button",{name:"Review release",exact:true}).click();await page.getByRole("button",{name:"Check draft and dependencies",exact:true}).click();await page.getByRole("button",{name:"Save immutable candidate",exact:true}).click();main.rangeInput={min:"0",max:"90",step:"2",label:"Later pressure",unit:"kPa"};await decide(request,"manager","build","build.page.edit",{type:"build.page",id},{sections:saved.sections,document:saved.document});await page.getByRole("button",{name:"Activate release",exact:true}).click();
 const runtime=await page.context().newPage();await stableReadRevision(runtime);await open(runtime,"desk",`/page?app=build&kind=page&name=${name}`);
 const section=(title:string)=>runtime.getByRole("heading",{name:title,exact:true}).locator(".."),root=section("Pressure limits"),table=section("Imported notes"),detail=section("Imported selection"),a=runtime.getByRole("textbox",{name:"Lower pressure",exact:true}),b=runtime.getByRole("textbox",{name:"Upper pressure",exact:true}),min=root.getByRole("slider",{name:"Pressure Minimum",exact:true}),max=root.getByRole("slider",{name:"Pressure Maximum",exact:true}),clear=root.getByRole("button",{name:"Clear range",exact:true});
 await expect(a).toHaveValue("");await expect(b).toHaveValue("");await expect(table.getByText("PUMP-50",{exact:true})).toBeVisible();await expect(root.getByText("Any bound – Any bound bar",{exact:true})).toBeVisible();await expect(max).toHaveAttribute("max","45");await expect(runtime.getByRole("heading",{name:"Hidden pressure table",exact:true})).toHaveCount(0);
 await table.getByRole("row").filter({hasText:"PUMP-50"}).click();await expect(detail.getByRole("definition").filter({hasText:/^PUMP-50$/})).toBeVisible();await move(min,10);await expect(a).toHaveValue("10");await expect(b).toHaveValue("");await expect(table.getByText("PUMP-0",{exact:true})).toHaveCount(0);await expect(table.getByText("PUMP-50",{exact:true})).toBeVisible();await expect(detail.getByText("Select a record to see it here.",{exact:true})).toBeVisible();await move(max,20);await expect(b).toHaveValue("20");await expect(table.getByText("PUMP-20",{exact:true})).toBeVisible();await expect(table.getByText("PUMP-30",{exact:true})).toHaveCount(0);
 if(process.env.PLATFORM_SCREENSHOTS){await root.screenshot({path:info.outputPath("range.png")});await runtime.setViewportSize({width:390,height:844});await runtime.evaluate(()=>new Promise<void>(r=>requestAnimationFrame(()=>requestAnimationFrame(()=>r()))));await root.screenshot({path:info.outputPath("range-narrow.png")});await runtime.setViewportSize({width:1280,height:720});}
 await min.focus();await min.press("End");await expect(a).toHaveValue("20");await expect(b).toHaveValue("20");await max.focus();await max.press("Home");await expect(b).toHaveValue("20");await clear.click();await expect(a).toHaveValue("");await expect(b).toHaveValue("");await expect(table.getByText("PUMP-50",{exact:true})).toBeVisible();
 await a.fill("broken");await expect(a).toHaveValue("broken");await expect(min).toBeDisabled();await expect(root.getByRole("alert")).toBeVisible();await expect(table.getByText("PUMP-50",{exact:true})).toHaveCount(0);await clear.click();await expect(table.getByText("PUMP-50",{exact:true})).toBeVisible();await a.fill("0.5");await expect(a).toHaveValue("0.5");await expect(min).toBeDisabled();await clear.click();await expect(min).toBeEnabled();
 await runtime.route(`**/v1/records/${type}*`,route=>route.fulfill({status:403,contentType:"application/json",body:JSON.stringify({error:{message:"Denied"}})}));await move(min,10);await expect(table.getByRole("alert")).toBeVisible();await expect(table.getByText("PUMP-50",{exact:true})).toHaveCount(0);await runtime.unroute(`**/v1/records/${type}*`);await clear.click();await expect(table.getByText("PUMP-50",{exact:true})).toBeVisible();
 await runtime.getByRole("button",{name:"Open pressure",exact:true}).click();const panel=runtime.getByRole("dialog",{name:"Pressure panel",exact:true}),localA=panel.getByRole("textbox",{name:"Local lower pressure",exact:true}),localB=panel.getByRole("textbox",{name:"Local upper pressure",exact:true});await move(panel.getByRole("slider",{name:"Local pressure Minimum",exact:true}),20);await expect(localA).toHaveValue("20");await expect(runtime.getByLabel("Lower pressure",{exact:true})).toHaveValue("");await panel.getByRole("row").filter({hasText:"PUMP-50"}).click();await expect(panel.getByRole("definition").filter({hasText:/^PUMP-50$/})).toBeVisible();await panel.getByRole("button",{name:"Close pressure",exact:true}).click();await runtime.getByRole("button",{name:"Open pressure",exact:true}).click();await expect(localA).toHaveValue("");await expect(localB).toHaveValue("");await expect(panel.getByText("Select a record to see it here.",{exact:true})).toBeVisible();await expect(panel.getByRole("cell",{name:"PUMP-0",exact:true})).toBeVisible();await panel.getByRole("button",{name:"Close pressure",exact:true}).click();await runtime.reload();await expect(a).toHaveValue("");await expect(b).toHaveValue("");await expect(table.getByText("PUMP-50",{exact:true})).toBeVisible();const unchanged=(await(await request.get(`/v1/records/${type}/${name}50`,{headers:{Authorization:"Bearer manager"}})).json()).record;expect(unchanged.pressure).toBe(50);
});
