import {expect,test} from "@playwright/test";
import {decide,fresh,open,pageUIProfile} from "./host";

test("default collection parameters preserve full fixed membership across child windows, parent paging, refresh and filter changes",async({page,request},info)=>{
 test.setTimeout(120_000);page.setDefaultTimeout(10_000);
 const name=fresh("collectionembed").replace(/[^a-z0-9]/gi,"").toLowerCase(),type=`build.${name}`,objectID=fresh("OBJ"),childID=fresh("PAGE"),parentID=fresh("PAGE"),queryID=fresh("QUERY"),queryName=`${name}source`,headers={Authorization:"Bearer manager"},ref={app:"build",kind:"object",name:type};
 await decide(request,"manager","build","build.object.create",{type:"build.object",id:objectID},{name,title:"Collection input records",fields:[{name:"name",title:"Name",type:"text"},{name:"bucket",title:"Bucket",type:"text"},{name:"active",title:"Active",type:"boolean"}]});await decide(request,"manager","build","build.object.publish",{type:"build.object",id:objectID},{});
 for(let i=0;i<36;i++)await decide(request,"manager","build",`${type}.create`,{type,id:`R${String(i).padStart(2,"0")}`},{name:`Original record ${i}`,bucket:i<24?"A":"B",active:i!==0});
 const fixed={name:queryName,title:"Retained active records",description:"Original fixed membership and independent windows",object:type,domain:[["active","=",true]],sort:["id"],limit:1};
 await decide(request,"manager","build","build.query.create",{type:"build.query",id:queryID},fixed);await decide(request,"manager","build","build.query.publish",{type:"build.query",id:queryID},{});
 const defs=await(await request.get("/v1/definitions",{headers})).json(),query=defs.find((d:any)=>d.ref.kind==="query"&&d.ref.name===queryName),binding={ref:query.ref,sourceVersion:query.version};
 const sections=[{id:"table",widget:"table",configVersion:1,title:"Independent child window",fields:["name"],collectionVariable:"window"},{id:"count",widget:"metric",configVersion:1,title:"Complete inherited count",measure:"count",collectionVariable:"window"},{id:"note",widget:"input",configVersion:1,title:"Private child draft"}];
 const nodes={root:{kind:"rows",children:sections.map(s=>s.id)},...Object.fromEntries(sections.map(s=>[s.id,{kind:"widget",section:s.id,...s.id==="note"?{valueVariable:"note"}:{}}]))};
 await decide(request,"manager","build","build.page.create",{type:"build.page",id:childID},{name:`${name}child`,title:"Collection receiver",object:type,sections,document:{formatVersion:2,uiProfile:pageUIProfile,root:"root",nodes,variables:{objects:{scope:"page",type:"object-set",mode:"input"},window:{scope:"page",type:"object-set",mode:"resource",source:{kind:"plan",query:"read"}},note:{scope:"page",type:"string",mode:"state",initial:"Initial child draft"}},interface:{version:1,inputs:{inputObjectSet:{variable:"objects",type:"object-set",object:ref,required:true}}},queries:{read:{object:ref,input:"objects",limit:5}}}});
 await decide(request,"manager","build","build.page.publish",{type:"build.page",id:childID},{});
 const widgets={filter:{id:"filter",name:"Parent bucket",type:"TextInput",config:{variableId:"bucket",label:"Parent bucket"}},table:{id:"table",name:"Parent one-record window",type:"ObjectTable",config:{objectSetVarId:"filteredAssets",columns:[{key:"name"}]}},module:{id:"module",name:"Collection module",type:"EmbeddedModule",config:{moduleId:"collection.child",bindings:[{parentVar:"filteredAssets",childInterface:"sourceSet"}]}},custom:{id:"custom",name:"Default custom collection",type:"CustomWidget",config:{widgetSet:"com.vendor.ops",version:"1.0.0",params:[{name:"inputObjectSet",varId:"filteredAssets"}],permissions:["read.objects"]}}};
 const module={id:"source",name:"Collection imports",pages:[{id:"page",name:"Collection imports",rootSectionId:"root"}],sections:{root:{id:"root",name:"Root",layout:"rows",children:Object.keys(widgets).map(id=>({kind:"widget",id}))}},widgets,variables:[{id:"bucket",name:"Bucket",type:"string",definitionKind:"static",staticValue:"A"},{id:"filteredAssets",name:"Filtered assets",type:"objectSet",definitionKind:"objectSetDefinition",objectSet:{objectType:"Asset",steps:[{op:"where",clauses:[{property:"bucket",op:"is",varId:"bucket"}]}]}}],overlays:[],unusedWidgetIds:[]};
 await decide(request,"manager","build","build.page.create",{type:"build.page",id:parentID},{name:`${name}parent`,title:"Collection import",object:type,sections:[{id:"initial",widget:"text",configVersion:1,text:"Initial"}],document:{formatVersion:2,uiProfile:pageUIProfile,root:"root",nodes:{root:{kind:"rows",children:["initial"]},initial:{kind:"widget",section:"initial"}}}});
 await open(page,"manager",`/compose?id=${parentID}`);await page.getByRole("button",{name:"Import Workshop module",exact:true}).click();const dialog=page.getByRole("dialog",{name:"Import Workshop module",exact:true});await dialog.getByRole("textbox",{name:"Source module JSON",exact:true}).fill(JSON.stringify(module));
 await dialog.getByRole("combobox",{name:"Map object Asset",exact:true}).selectOption(type);for(const field of ["bucket","name"])await dialog.getByRole("combobox",{name:`Map field Asset.${field}`,exact:true}).selectOption(field);
 await dialog.getByRole("combobox",{name:"Optional query binding Filtered assets",exact:true}).selectOption(JSON.stringify(binding));
 for(const [title,migration,sourcePort]of [["Collection module","original-page","sourceSet"],["Default custom collection","registered-page","inputObjectSet"]]){
  const group=dialog.getByRole("group",{name:`Map embedded source ${title}`,exact:true});await group.getByRole("combobox",{name:"Embedded source interpretation",exact:true}).selectOption(migration);await group.getByRole("combobox",{name:"Fixed original embedded page",exact:true}).selectOption(JSON.stringify({app:"build",kind:"page",name:`${name}child`}));await group.getByRole("combobox",{name:`Map embedded input ${sourcePort}`,exact:true}).selectOption("inputObjectSet");
 }
 await dialog.getByRole("checkbox").check();await expect(dialog.getByRole("button",{name:"Apply imported page draft",exact:true})).toBeEnabled();await dialog.getByRole("button",{name:"Apply imported page draft",exact:true}).click();await page.getByRole("button",{name:"Save",exact:true}).click();
 await expect.poll(async()=>{const body=await(await request.get(`/v1/records/build.page/${parentID}`,{headers})).json();return body.record.sections.filter((s:any)=>s.embedding).length;}).toBe(2);
 await page.getByRole("button",{name:"Review release",exact:true}).click();await page.getByRole("button",{name:"Check draft and dependencies",exact:true}).click();await page.getByRole("button",{name:"Save immutable candidate",exact:true}).click();
 await decide(request,"manager","build","build.query.edit",{type:"build.query",id:queryID},{domain:[["active","=",false]]});await decide(request,"manager","build","build.query.publish",{type:"build.query",id:queryID},{});await page.getByRole("button",{name:"Activate release",exact:true}).click();
 const runtime=await page.context().newPage();runtime.setDefaultTimeout(10_000);await open(runtime,"desk",`/page?app=build&kind=page&name=${name}parent`);
 const section=(title:string)=>runtime.getByRole("heading",{name:title,exact:true,level:3}).locator(".."),parent=section("Parent one-record window"),child=section("Collection module"),custom=section("Default custom collection"),count=(view:ReturnType<typeof section>,value:string)=>view.getByRole("heading",{name:"Complete inherited count",exact:true,level:3}).locator("..").getByText(value,{exact:true});
 await expect(parent).toContainText("1–1 of 23");await expect(child).toContainText("1–5 of 23");await expect(count(child,"23")).toBeVisible();await expect(count(custom,"23")).toBeVisible();await expect(child).not.toContainText("Original record 0");
 const draft=child.getByRole("textbox",{name:"Private child draft",exact:true});await draft.fill("Keep private draft");await parent.getByRole("button",{name:"Next page",exact:true}).click();await expect(parent).toContainText("Original record 2");await expect(draft).toHaveValue("Keep private draft");await expect(count(child,"23")).toBeVisible();
 await decide(request,"manager","build",`${type}.create`,{type,id:"NEW"},{name:"New authorized record",bucket:"A",active:true});await expect(count(child,"24")).toBeVisible();await expect(draft).toHaveValue("Keep private draft");
 await runtime.getByRole("textbox",{name:"Parent bucket",exact:true}).fill("B");await expect(count(child,"12")).toBeVisible();await expect(count(custom,"12")).toBeVisible();await expect(child).not.toContainText("New authorized record");await expect(child.getByRole("textbox",{name:"Private child draft",exact:true})).toHaveValue("Initial child draft");
 await runtime.getByRole("textbox",{name:"Parent bucket",exact:true}).fill("NONE");await expect(count(child,"0")).toBeVisible();await expect(child).not.toContainText("Original record 24");
 if(process.env.PLATFORM_SCREENSHOTS){await child.screenshot({path:info.outputPath("collection-child.png")});await runtime.setViewportSize({width:390,height:844});await expect(count(custom,"0")).toBeVisible();await custom.screenshot({path:info.outputPath("collection-custom-narrow.png")});}
});
