import {expect,test} from '@playwright/test';import {readFileSync} from 'node:fs';
import {decide,fresh,open,pageUIProfile} from './host';
const original=JSON.parse(readFileSync(new URL('../../packages/build/src/workshop/module-import/default.workshop.json',import.meta.url),'utf8'));
test('four original KPI configurations and table controls import inspect freeze and follow real complete queries',async({page,request},info)=>{
 test.setTimeout(150_000);page.setDefaultTimeout(10_000);const name=fresh('opdisplay').replace(/[^a-z0-9]/gi,'').toLowerCase(),type=`build.${name}`,object=fresh('OBJ'),parent=fresh('PAGE'),headers={Authorization:'Bearer manager'},fields=[{name:'name',title:'Name',type:'text',search:true},{name:'priority',title:'Priority',type:'choice',choices:'High,Medium,Low'},{name:'owner',title:'Owner',type:'text'},...['pressure','temperature','availability'].map(name=>({name,title:name,type:'decimal'})),{name:'openalerts',title:'Alerts',type:'integer'},{name:'lastinspection',title:'Last inspection',type:'date'}];
 await decide(request,'manager','build','build.object.create',{type:'build.object',id:object},{name,title:'Original display assets',fields,states:['active','warning','offline','maintenance'].map(name=>({name,title:name})),actions:[{name:'warn',title:'Warn',from:['active'],to:'warning'},{name:'offline',title:'Offline',from:['active'],to:'offline'}]});await decide(request,'manager','build','build.object.publish',{type:'build.object',id:object},{});
 for(const [id,availability,move] of [['A',100,''],['B',50,''],['C',25,'warn'],['D',75,'offline']] as const){await decide(request,'desk','build',`${type}.create`,{type,id},{name:`Original ${id}`,priority:'High',owner:'owner',pressure:10,temperature:20,availability,openalerts:0,lastinspection:'2026-10-04'});if(move)await decide(request,'desk','build',`${type}.${move}`,{type,id},{});}
 const ids=['wKpi1','wKpi2','wKpi3','wKpi4','wObjectTable1','wSearch1'],module={id:'group',name:'Original Operations displays',description:'Original four KPIs and table configurations',pages:[{id:'page',name:'Operations display group',rootSectionId:'root'}],sections:{root:{id:'root',name:'Original display group',layout:'rows',children:ids.map(id=>({kind:'widget',id}))}},widgets:Object.fromEntries(ids.map(id=>[id,structuredClone(original.widgets[id])])),variables:structuredClone(original.variables),overlays:[],unusedWidgetIds:[]};
 await decide(request,'manager','build','build.page.create',{type:'build.page',id:parent},{name:`${name}page`,title:'Original display task',object:type,sections:[{id:'initial',widget:'text',configVersion:1,text:'Initial'}],document:{formatVersion:2,uiProfile:pageUIProfile,root:'root',nodes:{root:{kind:'rows',children:['initial']},initial:{kind:'widget',section:'initial'}}}});
 await open(page,'manager',`/compose?id=${parent}`);await page.getByRole('button',{name:'Import Workshop module',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Import Workshop module',exact:true});await dialog.getByRole('textbox',{name:'Source module JSON',exact:true}).fill(JSON.stringify(module));await dialog.getByRole('combobox',{name:'Map object Asset',exact:true}).selectOption(type);for(const field of ['id','name','priority','owner','pressure','temperature','availability','openAlerts','lastInspection','status'])await dialog.getByRole('combobox',{name:`Map field Asset.${field}`,exact:true}).selectOption(field==='status'?'state':field.toLowerCase());
 for(const title of ['Active Assets','Warnings','Offline'])await dialog.getByRole('combobox',{name:`Interpret KPI note ${title}`,exact:true}).selectOption('static-note');
 for(const id of ['activeCount','warningCount','offlineCount']){const group=dialog.getByRole('group',{name:`Map metric aggregate ${id}`,exact:true});await group.getByRole('combobox',{name:'Original metric measure',exact:true}).selectOption('count');await group.getByRole('combobox',{name:'Optional metric equality field',exact:true}).selectOption('state');await group.getByRole('combobox',{name:'Metric equality value',exact:true}).selectOption({activeCount:'active',warningCount:'warning',offlineCount:'offline'}[id]!);}
 await dialog.getByRole('group',{name:'Map metric aggregate avgAvailability',exact:true}).getByRole('combobox',{name:'Original metric measure',exact:true}).selectOption('avg:availability');const edits=dialog.getByRole('group',{name:'Editable table fields',exact:true});await edits.getByRole('combobox',{name:'Map table edit action Assets',exact:true}).selectOption(`${type}.edit`);await edits.getByRole('button',{name:'Name',exact:true}).click();await dialog.getByRole('checkbox').check();await expect(dialog.getByRole('button',{name:'Apply imported page draft',exact:true})).toBeEnabled();await dialog.getByRole('button',{name:'Apply imported page draft',exact:true}).click();await page.getByRole('heading',{name:/Assets \(/,level:3}).click();await expect(page.getByRole('combobox',{name:'Initial record density',exact:true})).toHaveValue('compact');await expect(page.getByRole('textbox',{name:'Table count title template',exact:true})).toHaveValue('Assets ({count})');await page.getByRole('heading',{name:'Active',level:3,exact:true}).click();await expect(page.getByRole('textbox',{name:'Static annotation text',exact:true})).toHaveValue('+3');await page.getByRole('button',{name:'Save',exact:true}).click();await expect.poll(async()=>{const row=await(await request.get(`/v1/records/build.page/${parent}`,{headers})).json();return row.record.sections.some((s:any)=>s.tablePresentation?.titleTemplate==='Assets ({count})');}).toBe(true);
 await page.getByRole('button',{name:'Review release',exact:true}).click();await page.getByRole('button',{name:'Check draft and dependencies',exact:true}).click();await page.getByRole('button',{name:'Save immutable candidate',exact:true}).click();await page.getByRole('button',{name:'Activate release',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'Release active for operators.'})).toBeVisible();
 const saved=await(await request.get(`/v1/records/build.page/${parent}`,{headers})).json(),later=structuredClone(saved.record.sections);later.find((s:any)=>s.tablePresentation).tablePresentation.showToolbar=false;later.find((s:any)=>s.metricPresentation?.annotation?.text==='+3').metricPresentation.annotation.text='Later draft';await decide(request,'manager','build','build.page.edit',{type:'build.page',id:parent},{sections:later});
 const runtime=await page.context().newPage();runtime.setDefaultTimeout(10_000);await open(runtime,'desk',`/page?app=build&kind=page&name=${name}page`);const section=(title:string)=>runtime.getByRole('heading',{name:title,level:3,exact:true}).locator('..'),table=()=>runtime.getByRole('heading',{name:/Assets \(/,level:3}).locator('..');await expect(section('Active').getByText('2',{exact:true})).toBeVisible();await expect(section('Active')).toContainText('+3');await expect(section('Active')).toContainText('Static note:');await expect(section('Warnings').getByText('1',{exact:true})).toBeVisible();await expect(section('Offline')).toContainText('-1');await expect(runtime.getByRole('heading',{name:'Assets (4)',level:3,exact:true})).toBeVisible();await table().getByRole('combobox',{name:'Record density',exact:true}).selectOption('normal');await runtime.getByRole('textbox',{name:'Search',exact:true}).last().fill('Original A');await expect(runtime.getByRole('heading',{name:'Assets (1)',level:3,exact:true})).toBeVisible();await expect(table().getByRole('combobox',{name:'Record density',exact:true})).toHaveValue('normal');await expect(section('Avg Availability').getByText('100%',{exact:true})).toBeVisible();await decide(request,'desk','build',`${type}.edit`,{type,id:'A'},{availability:80});await expect(section('Avg Availability').getByText('80%',{exact:true})).toBeVisible();await expect(table().getByRole('combobox',{name:'Record density',exact:true})).toHaveValue('normal');await expect(section('Active')).toContainText('+3');await expect(runtime.getByText('Later draft',{exact:true})).toHaveCount(0);
 if(process.env.PLATFORM_SCREENSHOTS)await runtime.screenshot({path:info.outputPath('operations-original-presentations.png'),fullPage:true});
 await runtime.route(`**/v1/records/${type}?**`,r=>r.fulfill({status:403,contentType:'application/json',body:JSON.stringify({error:{message:'Denied'}})}));await decide(request,'desk','build',`${type}.edit`,{type,id:'A'},{availability:81});await expect(runtime.getByRole('heading',{name:'Assets (…)',level:3,exact:true})).toBeVisible();await expect(runtime.getByRole('heading',{name:'Assets (1)',level:3,exact:true})).toHaveCount(0);
});
