import {expect,test} from "@playwright/test";
import {readFileSync} from "node:fs";
import {decide,fresh,open,pageUIProfile,stableReadRevision} from "./host";

test("per-record source charts freeze ordered original points, retain repeated labels and clear refused or closed windows",async({page,request},info)=>{
 test.setTimeout(90_000);
 const name=fresh("points").replace(/[^a-z0-9]/gi,"").toLowerCase(),type=`build.${name}`,object=fresh("OBJ"),id=fresh("PAGE");
 await decide(request,"manager","build","build.object.create",{type:"build.object",id:object},{name,title:"Chart records",fields:[{name:"note",title:"Asset name",type:"text"},{name:"qty",title:"Pressure",type:"decimal"},{name:"bucket",title:"Bucket",type:"text"},{name:"secret",title:"Private label",type:"text",read:["builder"]},{name:"sensitive",title:"Private pressure",type:"decimal",read:["builder"]}]});await decide(request,"manager","build","build.object.publish",{type:"build.object",id:object},{});
 for(let i=0;i<75;i++)await decide(request,"manager","build",`${type}.create`,{type,id:`${name}${String(i).padStart(3,"0")}`},{note:"Repeated asset",qty:i,bucket:i<50?"A":"B",secret:"private",sensitive:100});
 const m=JSON.parse(readFileSync(new URL("../../packages/build/src/module-import/sample.workshop.json",import.meta.url),"utf8")),chart=(id:string,name:string,set="notes",x="id",y="pressure",kind="line")=>({id,name,type:"ChartXY",config:{objectSetVarId:set,chartKind:kind,xProperty:x,yProperty:y}});
 m.widgets.pressure=chart("pressure","Pressure over Assets");m.widgets.repeated=chart("repeated","Repeated labels","notes","name","pressure","bar");m.widgets.hiddenx=chart("hiddenx","Hidden chart labels","notes","secret");m.widgets.hiddeny=chart("hiddeny","Hidden chart values","notes","id","sensitive");m.widgets.hiddencondition=chart("hiddencondition","Hidden chart condition","privateNotes");m.widgets.local=chart("local","Local record points","localNotes");
 m.widgets.input={id:"input",name:"Point bucket",type:"TextInput",config:{variableId:"scratch",label:"Point bucket"}};m.widgets.localInput={id:"localInput",name:"Local point bucket",type:"TextInput",config:{variableId:"localScratch",label:"Local point bucket"}};m.widgets.trigger={id:"trigger",name:"Open points",type:"SingleButton",config:{label:"Open points",eventActions:[{kind:"openOverlay",overlayId:"panel"}]}};m.widgets.close={id:"close",name:"Close points",type:"SingleButton",config:{label:"Close points",eventActions:[{kind:"closeOverlay",overlayId:"panel"}]}};
 m.variables.find((v:any)=>v.id==="scratch").staticValue="";m.variables.find((v:any)=>v.id==="notes").objectSet.steps=[{op:"where",clauses:[{id:"bucket",property:"bucket",op:"contains",varId:"scratch"}]}];m.variables.push({id:"localScratch",name:"Local bucket",type:"string",definitionKind:"static",staticValue:""},{id:"localNotes",name:"Local notes",type:"objectSet",definitionKind:"objectSetDefinition",sourceObjectType:"Asset",objectSet:{objectType:"Asset",steps:[{op:"where",clauses:[{id:"bucket",property:"bucket",op:"contains",varId:"localScratch"}]}]}},{id:"privateNotes",name:"Private notes",type:"objectSet",definitionKind:"objectSetDefinition",sourceObjectType:"Asset",objectSet:{objectType:"Asset",steps:[{op:"where",clauses:[{id:"private",property:"secret",op:"is",value:"private"}]}]}});
 m.sections={root:{id:"root",name:"Root",layout:"rows",children:["input","table","pressure","repeated","hiddenx","hiddeny","hiddencondition","trigger"].map(id=>({kind:"widget",id}))},panel:{id:"panel",name:"Panel",layout:"rows",children:["localInput","local","close"].map(id=>({kind:"widget",id}))}};m.overlays=[{id:"panel",name:"Point panel",kind:"drawer",rootSectionId:"panel"}];
 await decide(request,"manager","build","build.page.create",{type:"build.page",id},{name,title:"Record points",object:type,sections:[{id:"initial",widget:"table",configVersion:1,fields:["note"]}],document:{formatVersion:2,uiProfile:pageUIProfile,root:"root",nodes:{root:{kind:"rows",children:["initial"]},initial:{kind:"widget",section:"initial"}}}});
 await open(page,"manager",`/compose?id=${id}`);await page.getByRole("button",{name:"Import Workshop module",exact:true}).click();const dialog=page.getByRole("dialog",{name:"Import Workshop module",exact:true});await dialog.getByRole("textbox",{name:"Source module JSON",exact:true}).fill(JSON.stringify(m));await dialog.getByRole("combobox",{name:"Map object Asset",exact:true}).selectOption(type);for(const [source,target] of [["name","note"],["id","id"],["pressure","qty"],["bucket","bucket"],["secret","secret"],["sensitive","sensitive"]])await dialog.getByRole("combobox",{name:`Map field Asset.${source}`,exact:true}).selectOption(target);await dialog.getByRole("checkbox").check();await dialog.getByRole("button",{name:"Apply imported page draft",exact:true}).click();
 const tree=page.getByRole("region",{name:"Widgets and layout",exact:true}),inspector=page.getByRole("region",{name:"The widget in hand",exact:true});await tree.getByRole("button",{name:"Pressure over Assets",exact:true}).click();await expect(inspector.getByRole("combobox",{name:"Record chart label field",exact:true})).toHaveValue("id");await inspector.getByRole("combobox",{name:"Record chart value field",exact:true}).selectOption("");await expect(page.getByRole("button",{name:"Save",exact:true})).toBeDisabled();await inspector.getByRole("combobox",{name:"Record chart value field",exact:true}).selectOption("qty");await inspector.getByRole("combobox",{name:"Record chart type",exact:true}).selectOption("bar");await inspector.getByRole("combobox",{name:"Record chart type",exact:true}).selectOption("line");
 await page.getByRole("button",{name:"Query plans",exact:true}).click();await page.getByRole("combobox",{name:"Choose query plan",exact:true}).selectOption({label:"Pressure over Assets"});await expect(page.getByRole("combobox",{name:"Query sort",exact:true})).toHaveValue("id");await page.getByRole("spinbutton",{name:"Query window limit",exact:true}).fill("41");await page.getByRole("button",{name:"Save",exact:true}).click();let saved:any;await expect.poll(async()=>{saved=(await(await request.get(`/v1/records/build.page/${id}`,{headers:{Authorization:"Bearer manager"}})).json()).record;return saved.sections?.filter((s:any)=>s.widget==="record-chart").length;}).toBe(6);
 await page.getByRole("button",{name:"Review release",exact:true}).click();await page.getByRole("button",{name:"Check draft and dependencies",exact:true}).click();await page.getByRole("button",{name:"Save immutable candidate",exact:true}).click();const rootChart=saved.sections.find((s:any)=>s.title==="Pressure over Assets");rootChart.recordChart={mark:"bar",xField:"note",yField:"qty"};await decide(request,"manager","build","build.page.edit",{type:"build.page",id},{sections:saved.sections});await page.getByRole("button",{name:"Activate release",exact:true}).click();
 const runtime=await page.context().newPage();await stableReadRevision(runtime);let aggregateReads=0;runtime.on("request",r=>{if(r.url().includes(`/v1/aggregates/${type}`))aggregateReads++;});const first=runtime.waitForResponse(r=>new URL(r.url()).pathname===`/v1/records/${type}`);await open(runtime,"desk",`/page?app=build&kind=page&name=${name}`);const section=(title:string)=>runtime.getByRole("heading",{name:title,exact:true}).locator(".."),root=section("Pressure over Assets"),repeated=section("Repeated labels"),input=runtime.getByRole("textbox",{name:"Point bucket",exact:true});await expect(root.getByRole("img")).toBeVisible();await expect(root.getByText("Plotting 40 of 41 records in this window.",{exact:true})).toBeVisible();await expect(repeated.getByRole("img")).toBeVisible();const firstRows=(await(await first).json()).records;expect(firstRows).toHaveLength(41);expect(firstRows.map((r:any)=>r.qty)).toEqual(Array.from({length:41},(_,i)=>i));for(const title of ["Hidden chart labels","Hidden chart values","Hidden chart condition"])await expect(runtime.getByRole("heading",{name:title,exact:true})).toHaveCount(0);expect(aggregateReads).toBe(0);
 if(process.env.PLATFORM_SCREENSHOTS){await root.screenshot({path:info.outputPath("record-chart.png")});await repeated.screenshot({path:info.outputPath("record-chart-repeated.png")});await runtime.setViewportSize({width:390,height:844});await runtime.evaluate(()=>new Promise<void>(r=>requestAnimationFrame(()=>requestAnimationFrame(()=>r()))));await root.scrollIntoViewIfNeeded();await root.screenshot({path:info.outputPath("record-chart-narrow.png")});await runtime.setViewportSize({width:1280,height:720});}
 await root.getByRole("button",{name:"Next",exact:true}).click();await expect(root.getByText("Plotting 34 of 34 records in this window.",{exact:true})).toBeVisible();await expect(repeated.getByText("Plotting 34 of 34 records in this window.",{exact:true})).toBeVisible();
 await input.fill("B");await expect(root.getByText("Plotting 25 of 25 records in this window.",{exact:true})).toBeVisible();await runtime.route(`**/v1/records/${type}*`,route=>route.fulfill({status:403,contentType:"application/json",body:JSON.stringify({error:{message:"Denied"}})}));await input.fill("A");await expect(root.getByRole("alert")).toBeVisible();await expect(root.getByRole("img")).toHaveCount(0);await runtime.unroute(`**/v1/records/${type}*`);await input.fill("B");await expect(root.getByRole("img")).toBeVisible();
 await runtime.getByRole("button",{name:"Open points",exact:true}).click();const panel=runtime.getByRole("dialog",{name:"Point panel",exact:true}),localInput=panel.getByRole("textbox",{name:"Local point bucket",exact:true});await expect(panel.getByText("Plotting 40 of 75 records in this window.",{exact:true})).toBeVisible();await localInput.fill("A");await expect(panel.getByText("Plotting 40 of 50 records in this window.",{exact:true})).toBeVisible();await panel.getByRole("button",{name:"Close points",exact:true}).click();await expect(input).toHaveValue("B");await runtime.getByRole("button",{name:"Open points",exact:true}).click();await expect(localInput).toHaveValue("");await expect(panel.getByText("Plotting 40 of 75 records in this window.",{exact:true})).toBeVisible();await panel.getByRole("button",{name:"Close points",exact:true}).click();await runtime.reload();await expect(input).toHaveValue("");await expect(root.getByText("Plotting 40 of 41 records in this window.",{exact:true})).toBeVisible();expect(aggregateReads).toBe(0);
});
