import {expect,test} from "@playwright/test";
import {readFileSync} from "node:fs";
import {decide,fresh,open,pageUIProfile,stableReadRevision} from "./host";

test("three explicitly migrated work views freeze original services and operate real approvals, member notifications and authorized history",async({page,browser,request},info)=>{
 test.setTimeout(120_000);page.setDefaultTimeout(10_000);
 const name=fresh("workviews").replace(/[^a-z0-9]/gi,"").toLowerCase(),type=`build.${name}`,object=fresh("OBJ"),id=fresh("PAGE"),headers=(token:string)=>({Authorization:`Bearer ${token}`}),record=async(token:string,type:string,id:string)=>(await(await request.get(`/v1/records/${type}/${id}`,{headers:headers(token)})).json()).record;
 await decide(request,"manager","build","build.object.create",{type:"build.object",id:object},{name,title:"Original work requests",fields:[{name:"note",title:"Request note",type:"text"},{name:"secret",title:"Hidden work note",type:"text",read:["builder"]}],access:[{role:"user",read:"all",create:true,edit:true},{role:"supervisor",read:"all"}],states:[{name:"open",title:"Open"},{name:"pending",title:"Pending"},{name:"approved",title:"Approved"}],actions:[{name:"submit",title:"Request original approval",from:["open"],to:"approved",roles:["user","builder"],approval:{pending:"pending",levels:[{title:"First reviewer",role:"supervisor"},{title:"Final reviewer",role:"supervisor"}]}}]});
 await decide(request,"manager","build","build.object.publish",{type:"build.object",id:object},{});await decide(request,"manager","platform","platform.member.grant",{type:"platform.member",id:"business-supervisor-1"},{app:"build",role:"supervisor"});
 for(const suffix of ["A","B"])await decide(request,"desk","build",`${type}.create`,{type,id:`${name}${suffix}`},{note:`REQUEST-${suffix}`});await decide(request,"manager","build",`${type}.edit`,{type,id:`${name}A`},{secret:"HIDDEN-ORIGINAL-WORK"});
 const m=JSON.parse(readFileSync(new URL("../../packages/build/src/workshop/module-import/sample.workshop.json",import.meta.url),"utf8")),set=(id:string)=>({id,name:id,type:"objectSet",definitionKind:"objectSetDefinition",sourceObjectType:"Asset",objectSet:{objectType:"Asset",steps:[]}}),selected=(id:string,widget:string)=>({id,name:id,type:"object",definitionKind:"widgetOutput",widgetId:widget,widgetOutputKey:"activeObject"}),table=(id:string,title:string,set:string,active:string)=>({id,name:title,type:"ObjectTable",config:{objectSetVarId:set,activeVarId:active,columns:[{key:"name"}]}}),approval=(id:string,title:string)=>({id,name:title,type:"ApprovalInbox",config:{objectSetVarId:"items",approveActionId:"completeWorkOrder",rejectActionId:"cancelWorkOrder",pendingProperty:"status",doneValue:"Done"}}),notification=(id:string,title:string)=>({id,name:title,type:"NotificationFeed",config:{}}),history=(id:string,title:string)=>({id,name:title,type:"ActionLogTimeline",config:{objectSetVarId:"items"}});
 m.variables=[set("items"),selected("selected","table"),set("localItems"),selected("localSelected","localTable")];m.widgets={table:table("table","Original requests","items","selected"),approvals:approval("approvals","My actual approvals"),notices:notification("notices","My actual notifications"),history:history("history","Original operation history"),localTable:table("localTable","Panel requests","localItems","localSelected"),localApprovals:approval("localApprovals","Panel approvals"),localNotices:notification("localNotices","Panel notifications"),localHistory:history("localHistory","Panel history"),trigger:{id:"trigger",name:"Open work panel",type:"SingleButton",config:{label:"Open work panel",eventActions:[{kind:"openOverlay",overlayId:"panel"}]}},close:{id:"close",name:"Close work panel",type:"SingleButton",config:{label:"Close work panel",eventActions:[{kind:"closeOverlay",overlayId:"panel"}]}}};m.sections={root:{id:"root",name:"Root",layout:"rows",children:["table","approvals","notices","history","trigger"].map(id=>({kind:"widget",id}))},panel:{id:"panel",name:"Panel",layout:"rows",children:["localTable","localApprovals","localNotices","localHistory","close"].map(id=>({kind:"widget",id}))}};m.overlays=[{id:"panel",name:"Original work panel",kind:"drawer",rootSectionId:"panel"}];
 await decide(request,"manager","build","build.page.create",{type:"build.page",id},{name,title:"Original work desk",object:type,sections:[{id:"initial",widget:"text",configVersion:1,text:"Initial"}],document:{formatVersion:2,uiProfile:pageUIProfile,root:"root",nodes:{root:{kind:"rows",children:["initial"]},initial:{kind:"widget",section:"initial"}}}});
 await open(page,"manager",`/compose?id=${id}`);await page.getByRole("button",{name:"Import Workshop module",exact:true}).click();const dialog=page.getByRole("dialog",{name:"Import Workshop module",exact:true});await dialog.getByRole("textbox",{name:"Source module JSON",exact:true}).fill(JSON.stringify(m));await dialog.getByRole("combobox",{name:"Map object Asset",exact:true}).selectOption(type);await dialog.getByRole("combobox",{name:"Map field Asset.name",exact:true}).selectOption("note");await expect(dialog.getByRole("button",{name:"Apply imported page draft",exact:true})).toBeDisabled();
 for(const [title,kind,variable] of [["My actual approvals","caller-approvals",""],["My actual notifications","caller-notifications",""],["Original operation history","record-history","selected"],["Panel approvals","caller-approvals",""],["Panel notifications","caller-notifications",""],["Panel history","record-history","localSelected"]]){const group=dialog.getByRole("group",{name:`Map platform work ${title}`,exact:true});await group.getByRole("combobox",{name:"Platform work migration",exact:true}).selectOption(kind);if(variable)await group.getByRole("combobox",{name:"Original record selection",exact:true}).selectOption(variable);}
 await dialog.getByRole("checkbox").check();await expect(dialog.getByRole("button",{name:"Apply imported page draft",exact:true})).toBeEnabled();await dialog.getByRole("button",{name:"Apply imported page draft",exact:true}).click();await page.getByRole("region",{name:"Widgets and layout",exact:true}).getByRole("button",{name:"Original operation history",exact:true}).click();const inspector=page.getByRole("region",{name:"The widget in hand",exact:true}),limit=inspector.getByRole("spinbutton",{name:"History window size",exact:true});await expect(limit).toHaveValue("18");await limit.fill("0");await expect(page.getByRole("button",{name:"Save",exact:true})).toBeDisabled();await limit.fill("18");await page.getByRole("button",{name:"Save",exact:true}).click();let saved:any;await expect.poll(async()=>{saved=await record("manager","build.page",id);return saved.sections?.filter((s:any)=>["approval-inbox","notification-feed","timeline"].includes(s.widget)).length;}).toBe(6);
 await page.getByRole("button",{name:"Review release",exact:true}).click();await page.getByRole("button",{name:"Check draft and dependencies",exact:true}).click();await page.getByRole("button",{name:"Save immutable candidate",exact:true}).click();saved.sections.find((s:any)=>s.title==="Original operation history").historyLimit=1;saved.sections.find((s:any)=>s.title==="My actual notifications").title="Later draft notifications";await decide(request,"manager","build","build.page.edit",{type:"build.page",id},{sections:saved.sections});await page.getByRole("button",{name:"Activate release",exact:true}).click();
 for(const suffix of ["A","B"])await decide(request,"desk","build",`${type}.submit`,{type,id:`${name}${suffix}`},{});const offered=(await(await request.get("/v1/inbox",{headers:headers("business-supervisor")})).json()).filter((task:any)=>task.ref?.startsWith("work.approval/")&&task.title.includes(name)),requests=await Promise.all(offered.map(async(task:any)=>({task,request:await record("business-supervisor","work.approval",task.ref.slice("work.approval/".length))}))),a=requests.find(x=>x.request.target===`${type}/${name}A`)! ,b=requests.find(x=>x.request.target===`${type}/${name}B`)!;expect(a).toBeTruthy();expect(b).toBeTruthy();
 await expect(decide(request,"desk","work","work.approval.approve",{type:"work.approval",id:a.request.id},{})).rejects.toThrow(/POLICY_DENIED/);
 const context=await browser.newContext({baseURL:"http://127.0.0.1:18496",locale:"en-US"});try{const runtime=await context.newPage();runtime.setDefaultTimeout(10_000);await stableReadRevision(runtime);await open(runtime,"business-supervisor",`/page?app=build&kind=page&name=${name}`);const section=(title:string)=>runtime.getByRole("heading",{name:title,exact:true,level:3}).locator(".."),tableView=section("Original requests"),approvals=section("My actual approvals"),notices=section("My actual notifications"),historyView=section("Original operation history"),row=(suffix:string)=>approvals.getByRole("listitem").filter({hasText:`${type}/${name}${suffix}`});
 await expect(row("A").getByRole("button",{name:"Approve",exact:true})).toBeEnabled();await expect(row("A")).toContainText(`Revision ${a.request.revision}`);await expect(row("A")).toContainText("First reviewer");await tableView.getByRole("row").filter({hasText:`${name}A`}).click();await expect(historyView).toContainText(`${type}.submit`);await expect(historyView).not.toContainText("HIDDEN-ORIGINAL-WORK");await expect(runtime.getByText("Later draft notifications",{exact:true})).toHaveCount(0);
 if(process.env.PLATFORM_SCREENSHOTS){await row("A").screenshot({path:info.outputPath("work-approval-ready.png")});await runtime.setViewportSize({width:390,height:844});await runtime.waitForTimeout(300);await row("A").screenshot({path:info.outputPath("work-approval-ready-narrow.png")});await runtime.setViewportSize({width:1280,height:720});}
 const notification=notices.getByRole("listitem").filter({hasText:a.request.id}).filter({has:runtime.getByRole("button",{name:"Mark read",exact:true})}).first();await expect(notification).toBeVisible();await notification.getByRole("button",{name:"Mark read",exact:true}).click();const originalNotices=(await(await request.get("/v1/notifications",{headers:headers("business-supervisor")})).json());expect(originalNotices.some((n:any)=>n.ref===`work.approval/${a.request.id}`&&n.read)).toBe(true);
 let release:()=>void=()=>{};const gate=new Promise<void>(resolve=>release=resolve);let observed:any;await runtime.route("**/v1/submissions",async route=>{const body=route.request().postDataJSON();if(body.schema?.name==="work.approval.approve"&&body.target?.id===a.request.id&&!observed){observed=body;await gate;}await route.continue();});await row("A").getByRole("button",{name:"Approve",exact:true}).click();await expect.poll(()=>!!observed).toBe(true);expect(Number(observed.expectedRevision)).toBe(a.request.revision);await decide(request,"business-supervisor","work","work.approval.approve",{type:"work.approval",id:a.request.id},{});release();await expect(row("A").getByRole("alert")).toContainText(/revision|CONFLICT|changed/i);await runtime.unroute("**/v1/submissions");expect((await record("business-supervisor","work.approval",a.request.id)).state).toBe("pending");await expect(row("A")).toContainText("Final reviewer");await row("A").getByRole("button",{name:"Approve",exact:true}).click();await expect(row("A")).toHaveCount(0);expect((await record("business-supervisor",type,`${name}A`)).state).toBe("approved");await expect(historyView).toContainText("approved");
 await row("B").getByRole("button",{name:"Reject",exact:true}).click();await expect(row("B")).toHaveCount(0);expect((await record("business-supervisor","work.approval",b.request.id)).state).toBe("rejected");

 if(process.env.PLATFORM_SCREENSHOTS){await approvals.screenshot({path:info.outputPath("work-approvals.png")});await notices.screenshot({path:info.outputPath("work-notifications.png")});await historyView.screenshot({path:info.outputPath("work-history.png")});await runtime.setViewportSize({width:390,height:844});await runtime.waitForTimeout(300);await historyView.screenshot({path:info.outputPath("work-history-narrow.png")});await notices.screenshot({path:info.outputPath("work-notifications-narrow.png")});await runtime.setViewportSize({width:1280,height:720});}
 await runtime.getByRole("button",{name:"Open work panel",exact:true}).click();const panel=runtime.getByRole("dialog",{name:"Original work panel",exact:true}),localHistory=panel.getByRole("heading",{name:"Panel history",exact:true,level:3}).locator("..");await expect(localHistory).toContainText("Select a record to see what happened to it.");await panel.getByRole("row").filter({hasText:`${name}B`}).click();await expect(localHistory).toContainText(`${name}B`);await panel.getByRole("button",{name:"Close work panel",exact:true}).click();await runtime.getByRole("button",{name:"Open work panel",exact:true}).click();await expect(localHistory).toContainText("Select a record to see what happened to it.");await panel.getByRole("button",{name:"Close work panel",exact:true}).click();await expect(historyView).toContainText(`${name}A`);
 await runtime.route("**/v1/notifications",route=>route.fulfill({status:403,contentType:"application/json",body:'{"error":{"code":"ERROR_CODE_FORBIDDEN"}}'}));await runtime.reload();await expect(section("My actual notifications").getByRole("alert")).toContainText("could not be read");await expect(section("My actual notifications").getByRole("listitem")).toHaveCount(0);await runtime.unroute("**/v1/notifications");await runtime.reload();await expect(section("My actual notifications").getByRole("listitem").first()).toBeVisible();
 }finally{await context.close();}
});
