import {expect,test} from "@playwright/test";
import {decide,fresh,open,pageUIProfile} from "./host";

test("authored metric and chart aggregate the complete frozen set while table paging and obsolete responses cannot change totals",async({page,request},info)=>{
 test.setTimeout(60_000);
 const name=fresh("setagg").replace(/[^a-z0-9]/gi,"").toLowerCase(),type=`build.${name}`,object=fresh("OBJ"),id=fresh("PAGE"),ref={app:"build",kind:"object",name:type};
 await decide(request,"manager","build","build.object.create",{type:"build.object",id:object},{name,title:"Aggregate set notes",fields:[{name:"note",title:"Note",type:"text"},{name:"bucket",title:"Bucket",type:"text"}]});await decide(request,"manager","build","build.object.publish",{type:"build.object",id:object},{});for(const suffix of ["A1","A2","A3","B1","B2","C1"])await decide(request,"desk","build",`${type}.create`,{type,id:`${name}${suffix}`},{note:`AGG-${suffix}`,bucket:suffix[0]});
 await decide(request,"manager","build","build.page.create",{type:"build.page",id},{name,title:"Aggregate set desk",object:type,sections:[{id:"input",widget:"input",configVersion:1,title:"Aggregate bucket"},{id:"table",widget:"table",configVersion:1,title:"One record window",fields:["note"],collectionVariable:"window"},{id:"metric",widget:"metric",configVersion:1,title:"Whole set count",measure:"count"},{id:"chart",widget:"chart",configVersion:1,title:"Whole set by bucket",measure:"count",group:"bucket"}],document:{formatVersion:2,uiProfile:pageUIProfile,root:"root",nodes:{root:{kind:"rows",children:["input","table","metric","chart"]},input:{kind:"widget",section:"input",valueVariable:"bucket"},table:{kind:"widget",section:"table"},metric:{kind:"widget",section:"metric"},chart:{kind:"widget",section:"chart"}},variables:{bucket:{scope:"page",type:"string",mode:"state",initial:"B"},window:{title:"Complete set",scope:"page",type:"object-set",mode:"resource",source:{kind:"plan",query:"combined"}}},queries:{left:{object:ref,limit:1,conditions:[{field:"bucket",op:"=",value:{literal:"A"}}]},right:{object:ref,limit:1,conditions:[{field:"bucket",op:"=",value:{variable:"bucket"}}]},combined:{object:ref,limit:1,sort:["id"],set:{op:"union",inputs:["left","right"]}}}}});
 await open(page,"manager",`/compose?id=${id}`);const tree=page.getByRole("region",{name:"Widgets and layout",exact:true}),inspector=page.getByRole("region",{name:"The widget in hand",exact:true});for(const title of ["Whole set count","Whole set by bucket"]){await tree.getByRole("button",{name:title,exact:true}).click();await inspector.getByRole("combobox",{name:"Aggregate query set",exact:true}).selectOption("window");}
 await page.getByRole("button",{name:"Save",exact:true}).click();await expect.poll(async()=>(await(await request.get(`/v1/records/build.page/${id}`,{headers:{Authorization:"Bearer manager"}})).json()).record.sections.filter((s:any)=>["chart","metric"].includes(s.widget)).every((s:any)=>s.collectionVariable==="window")).toBe(true);await page.getByRole("button",{name:"Review release",exact:true}).click();await page.getByRole("button",{name:"Check draft and dependencies",exact:true}).click();await page.getByRole("button",{name:"Save immutable candidate",exact:true}).click();const saved=await(await request.get(`/v1/records/build.page/${id}`,{headers:{Authorization:"Bearer manager"}})).json();saved.record.document.queries.combined.set.op="intersect";await decide(request,"manager","build","build.page.edit",{type:"build.page",id},{document:saved.record.document});await page.getByRole("button",{name:"Activate release",exact:true}).click();
 const operation=await page.context().newPage(),grouped=operation.waitForResponse(response=>response.url().endsWith(`/v1/aggregates/${type}/query`)&&response.request().postDataJSON().groups?.[0]==="bucket");let aggregates=0;operation.on("request",r=>{if(r.url().endsWith(`/v1/aggregates/${type}/query`)){aggregates++;const q=r.postDataJSON();expect(q.set.op).toBe("union");expect(q.limit).toBeUndefined();expect(q.offset).toBeUndefined();expect(q.sort).toBeUndefined();}});
 await open(operation,"desk",`/page?app=build&kind=page&name=${name}`);const metric=operation.getByRole("heading",{name:"Whole set count",exact:true}).locator(".."),chart=operation.getByRole("heading",{name:"Whole set by bucket",exact:true}).locator(".."),input=operation.getByRole("textbox",{name:"Aggregate bucket",exact:true});await expect(metric.getByText("5",{exact:true})).toBeVisible();await expect(operation.getByText("1–1 of 5",{exact:true})).toBeVisible();expect((await(await grouped).json()).rows).toEqual([{bucket:"A",count:3},{bucket:"B",count:2}]);await expect(chart.getByRole("img")).toBeVisible();const before=aggregates;await operation.getByRole("button",{name:"Next page",exact:true}).click();await expect(operation.getByText("2–2 of 5",{exact:true})).toBeVisible();await expect(metric.getByText("5",{exact:true})).toBeVisible();expect(aggregates).toBe(before);
 let release!:()=>void,complete!:()=>void,held=0,done=0;const wait=new Promise<void>(r=>release=r),handled=new Promise<void>(r=>complete=r);await operation.route(`**/v1/aggregates/${type}/query`,async route=>{if(route.request().postDataJSON().set.inputs[1].domain[0][2]==="C"){const response=await route.fetch();held++;await wait;await route.fulfill({response});if(++done===2)complete();}else await route.continue();});await input.fill("C");await expect.poll(()=>held).toBe(2);await expect(metric.getByText("5",{exact:true})).toHaveCount(0);await input.fill("D");await expect(metric.getByText("3",{exact:true})).toBeVisible();release();await handled;await operation.unroute(`**/v1/aggregates/${type}/query`);await expect(metric.getByText("4",{exact:true})).toHaveCount(0);await expect(metric.getByText("3",{exact:true})).toBeVisible();
 await operation.route(`**/v1/aggregates/${type}/query`,route=>route.fulfill({status:403,contentType:"application/json",body:JSON.stringify({error:{message:"Denied"}})}));await input.fill("B");await expect(metric.getByRole("alert")).toBeVisible();await expect(metric.getByText("3",{exact:true})).toHaveCount(0);await operation.unroute(`**/v1/aggregates/${type}/query`);await input.fill("C");await expect(metric.getByText("4",{exact:true})).toBeVisible();if(process.env.PLATFORM_SCREENSHOTS){await metric.scrollIntoViewIfNeeded();await operation.screenshot({path:info.outputPath("set-aggregate.png"),fullPage:true});await operation.setViewportSize({width:390,height:844});await operation.evaluate(()=>new Promise<void>(r=>requestAnimationFrame(()=>requestAnimationFrame(()=>r()))));await operation.screenshot({path:info.outputPath("set-aggregate-narrow.png"),fullPage:true});}await operation.reload();await expect(metric.getByText("5",{exact:true})).toBeVisible();
});
