import {expect,test} from "@playwright/test";
import {decide,fresh,open,pageUIProfile} from "./host";

test("region sizing is authored with history and frozen without changing original record work",async({page,request},testInfo)=>{
 const name=fresh("sized").replace(/[^a-z0-9]/gi,"").toLowerCase(),object=fresh("OBJ"),id=fresh("PAGE"),type=`build.${name}`;
 await decide(request,"manager","build","build.object.create",{type:"build.object",id:object},{name,title:"Layout work",states:[{name:"open",title:"Open"},{name:"done",title:"Done"}],actions:[{name:"close",title:"Complete layout work",from:["open"],to:"done"}],fields:[{name:"title",title:"Title",type:"text"}]});
 await decide(request,"manager","build","build.object.publish",{type:"build.object",id:object},{});
 await decide(request,"desk","build",`${type}.create`,{type,id:"WORK"},{title:"SIZED-WORK"});
 await decide(request,"manager","build","build.page.create",{type:"build.page",id},{name,title:"Sized work desk",object:type,sections:[{id:"table",widget:"table",configVersion:1,title:"Work choices",fields:["title"]},{id:"detail",widget:"detail",configVersion:1,title:"Chosen work",fields:["title","state"]},{id:"actions",widget:"actions",configVersion:1,title:"Original work",actions:[`${type}.close`]}],document:{formatVersion:2,uiProfile:pageUIProfile,root:"root",nodes:{root:{kind:"columns",children:["table","right"]},table:{kind:"widget",section:"table"},right:{kind:"rows",children:["detail","actions"]},detail:{kind:"widget",section:"detail"},actions:{kind:"widget",section:"actions"}}}});
 await open(page,"manager",`/compose?id=${id}`);
 const tree=page.getByRole("region",{name:"Widgets and layout",exact:true}),inspector=page.getByRole("region",{name:"The widget in hand",exact:true}),save=page.getByRole("button",{name:"Save",exact:true});
 await tree.getByRole("button",{name:/^Columns/}).click();await inspector.getByLabel("Height (px)",{exact:true}).fill("520");await inspector.getByLabel("Layout gap (px)",{exact:true}).fill("16");
 await tree.getByRole("button",{name:"Work choices",exact:true}).click();await inspector.getByLabel("Layout weight",{exact:true}).fill("0");await expect(page.getByRole("alert").filter({hasText:"Layout weight needs a Rows or Columns parent."})).toBeVisible();await expect(save).toBeDisabled();await inspector.getByLabel("Layout weight",{exact:true}).fill("2");await inspector.getByLabel("Minimum width (px)",{exact:true}).fill("240");await inspector.getByRole("combobox",{name:"Region scroll",exact:true}).selectOption("auto");
 await tree.getByRole("button",{name:/^Rows/}).click();await inspector.getByLabel("Layout weight",{exact:true}).fill("1");
 await tree.getByRole("button",{name:"Chosen work",exact:true}).click();await inspector.getByLabel("Layout weight",{exact:true}).fill("2");await inspector.getByRole("combobox",{name:"Region scroll",exact:true}).selectOption("auto");
 await tree.getByRole("button",{name:"Original work",exact:true}).click();await inspector.getByLabel("Layout weight",{exact:true}).fill("1");await inspector.getByLabel("Minimum height (px)",{exact:true}).fill("96");
 await page.getByRole("button",{name:"Undo",exact:true}).click();await expect(inspector.getByLabel("Minimum height (px)",{exact:true})).toHaveValue("");await page.getByRole("button",{name:"Redo",exact:true}).click();await expect(inspector.getByLabel("Minimum height (px)",{exact:true})).toHaveValue("96");
 if(process.env.PLATFORM_SCREENSHOTS){await page.setViewportSize({width:1280,height:1100});await inspector.screenshot({path:testInfo.outputPath("layout-sizing-inspector.png")});}
 await save.click();await expect(save).toBeDisabled();let saved:any=(await(await request.get(`/v1/records/build.page/${id}`,{headers:{Authorization:"Bearer manager"}})).json()).record;
 expect(saved.document.nodes.root.size.height).toBe(520);expect(saved.document.nodes.table.size.weight).toBe(2);expect(Object.keys(saved.document.nodes).sort()).toEqual(["actions","detail","right","root","table"]);
 await page.getByRole("button",{name:"Review release",exact:true}).click();await page.getByRole("button",{name:"Check draft and dependencies",exact:true}).click();await page.getByRole("button",{name:"Save immutable candidate",exact:true}).click();
 saved.document.nodes.root.size.height=800;saved.document.nodes.table.size.weight=1;await decide(request,"manager","build","build.page.edit",{type:"build.page",id},{document:saved.document});await page.getByRole("button",{name:"Activate release",exact:true}).click();
 const check=async()=>{const definitions=await(await request.get("/v1/definitions",{headers:{Authorization:"Bearer desk"}})).json();const doc=definitions.find((d:any)=>d.ref.kind==="page"&&d.ref.name===name).page.document;expect(doc.nodes.root.size.height).toBe(520);expect(doc.nodes.table.size.weight).toBe(2);expect(doc.nodes.detail.size.weight).toBe(2);expect(doc.nodes.actions.size.minHeight).toBe(96);};await check();
 const operation=await page.context().newPage();await open(operation,"desk",`/page?app=build&kind=page&name=${name}`);const detail=operation.getByRole("heading",{name:"Chosen work",exact:true}).locator("..");await operation.getByRole("row").filter({hasText:"SIZED-WORK"}).click();await expect(detail.getByText("SIZED-WORK",{exact:true})).toBeVisible();await operation.getByRole("button",{name:"Complete layout work",exact:true}).click();await expect(detail.getByText("Done",{exact:true})).toBeVisible();
 if(process.env.PLATFORM_SCREENSHOTS){await expect(operation.getByRole("row").filter({hasText:"SIZED-WORK"})).toBeVisible();await operation.screenshot({path:testInfo.outputPath("layout-sizing-runtime.png"),fullPage:true});await operation.setViewportSize({width:390,height:844});await operation.evaluate(()=>new Promise<void>(r=>requestAnimationFrame(()=>requestAnimationFrame(()=>r()))));await operation.screenshot({path:testInfo.outputPath("layout-sizing-narrow.png"),fullPage:true});await operation.getByRole("heading",{name:"Original work",exact:true}).scrollIntoViewIfNeeded();await operation.screenshot({path:testInfo.outputPath("layout-sizing-narrow-work.png"),fullPage:true});}
 await operation.reload();await operation.getByRole("row").filter({hasText:"SIZED-WORK"}).click();await expect(detail.getByText("Done",{exact:true})).toBeVisible();await check();
});
