import {expect,test} from '@playwright/test';
import {defaultAnalyticsSelectionGroup} from '../../packages/build/src/workshop/module-import/default-analytics.fixture.mjs';
import {decide,fresh,open,pageUIProfile,stableReadRevision} from './host';

test('original Analytics scatter and ranking share authorized selection with original properties across frozen pages',async({page,request},info)=>{
 test.setTimeout(120_000);page.setDefaultTimeout(10_000);
 const name=fresh('choice').replace(/[^a-z0-9]/gi,'').toLowerCase(),type=`build.${name}`,obj=fresh('OBJ'),id=fresh('PAGE'),other=fresh('PAGE'),app=fresh('APP'),headers={Authorization:'Bearer manager'},ref={app:'build',kind:'object',name:type},application=`build:${name}app`;
 const fields=[{name:'name',title:'Name',type:'text',search:true},{name:'status',title:'Status',type:'choice',choices:'active,warning,offline,maintenance'},{name:'priority',title:'Priority',type:'choice',choices:'Low,High'},{name:'owner',title:'Owner',type:'text'},...['pressure','temperature','availability','exposure'].map(name=>({name,title:name[0]!.toUpperCase()+name.slice(1),type:'integer'})),{name:'model',title:'Model',type:'text'},...['installedat','lastinspection','nextmaintenance'].map(name=>({name,title:name,type:'date'})),{name:'secret',title:'Private ranking',type:'integer',read:['builder']}];
 await decide(request,'manager','build','build.object.create',{type:'build.object',id:obj},{name,title:'Shared Analytics assets',fields});await decide(request,'manager','build','build.object.publish',{type:'build.object',id:obj},{});
 for(let n=0;n<12;n++)await decide(request,'manager','build',`${type}.create`,{type,id:`R${String(n).padStart(2,'0')}`},{name:`Asset ${String(n).padStart(2,'0')}`,status:n%2?'warning':'active',priority:'Low',owner:'Original owner',pressure:n<2?5:n,temperature:n<2?10:n*2,availability:90,exposure:n*100,model:'Original model',installedat:'2020-01-01',lastinspection:'2026-10-01',nextmaintenance:'2026-10-10',secret:1});
 const emptyDocument={formatVersion:2,uiProfile:pageUIProfile,root:'root',nodes:{root:{kind:'rows',children:['initial']},initial:{kind:'widget',section:'initial'}}};
 for(const [p,suffix,title]of [[id,'page','Analytics selection'],[other,'other','Shared selection destination']]){await decide(request,'manager','build','build.page.create',{type:'build.page',id:p!},{name:`${name}${suffix}`,title,object:type,sections:[{id:'initial',widget:'text',configVersion:1,text:'Initial'}],document:emptyDocument});await decide(request,'manager','build','build.page.publish',{type:'build.page',id:p!},{});}
 await decide(request,'manager','build','build.app.create',{type:'build.app',id:app},{name:`${name}app`,title:'Shared Analytics desk',pages:[`${name}page`,`${name}other`],uiProfile:pageUIProfile,variables:{record:{scope:'application',type:'record',mode:'resource',source:{kind:'record',object:ref}}}});await decide(request,'manager','build','build.app.publish',{type:'build.app',id:app},{});
 const defs=await(await request.get('/v1/definitions',{headers})).json(),definition=defs.find((d:any)=>d.ref.kind==='app'&&d.ref.name===`${name}app`),binding={ref:definition.ref,sourceVersion:definition.version},fixture=defaultAnalyticsSelectionGroup(pageUIProfile);
 await open(page,'manager',`/compose?id=${id}`);await page.getByRole('button',{name:'Import Workshop module',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Import Workshop module',exact:true});await dialog.getByRole('textbox',{name:'Source module JSON',exact:true}).fill(JSON.stringify(fixture.module));await dialog.getByRole('combobox',{name:'Map object Asset',exact:true}).selectOption(type);
 const mapped={id:'id',name:'name',status:'status',priority:'priority',owner:'owner',pressure:'pressure',temperature:'temperature',availability:'availability',revenueImpact:'exposure',model:'model',installedAt:'installedat',lastInspection:'lastinspection',nextMaintenance:'nextmaintenance'};for(const [property,field]of Object.entries(mapped))await dialog.getByRole('combobox',{name:`Map field Asset.${property}`,exact:true}).selectOption(field);
 await dialog.getByRole('combobox',{name:'Reviewed original application',exact:true}).selectOption(JSON.stringify(binding));await dialog.getByRole('combobox',{name:'Map module port selectedAsset',exact:true}).selectOption('record');await dialog.getByRole('group',{name:'Map scatter plot Pressure vs temperature',exact:true}).getByRole('combobox',{name:'Scatter title field',exact:true}).selectOption('name');await dialog.getByRole('group',{name:'Map leaderboard Top revenue exposure',exact:true}).getByRole('combobox',{name:'Ranking title field',exact:true}).selectOption('name');await dialog.getByRole('checkbox').last().check();await expect(dialog.getByRole('button',{name:'Apply imported page draft',exact:true})).toBeEnabled();await dialog.getByRole('button',{name:'Apply imported page draft',exact:true}).click();
 const tree=page.getByRole('region',{name:'Widgets and layout',exact:true}),inspector=page.getByRole('region',{name:'The widget in hand',exact:true});for(const title of ['Pressure vs temperature','Top revenue exposure']){await tree.getByRole('button',{name:title,exact:true}).click();await expect(inspector.getByRole('combobox',{name:'Shared record selection',exact:true})).not.toHaveValue('');}await page.getByRole('button',{name:'Save',exact:true}).click();let saved:any;await expect.poll(async()=>{saved=(await(await request.get(`/v1/records/build.page/${id}`,{headers})).json()).record;return saved.sections.length;}).toBe(4);
 const selected=saved.sections.find((s:any)=>s.widget==='record-scatter').selectionVariable;expect(saved.sections.find((s:any)=>s.widget==='record-leaderboard').selectionVariable).toBe(selected);saved.sections.push({id:'next',widget:'button',configVersion:1,title:'Shared destination'});saved.document.nodes.next={kind:'widget',section:'next'};saved.document.nodes[saved.document.root].children.push('next');saved.document.events=[{source:'next',event:'click',target:'',navigate:{page:{app:'build',kind:'page',name:`${name}other`},interfaceVersion:0}}];
 const ranks=saved.sections.find((s:any)=>s.widget==='record-leaderboard'),set=saved.document.variables[ranks.collectionVariable],query=saved.document.queries[set.source.query];saved.sections.push({...structuredClone(ranks),id:'private',title:'Private Analytics ranks',collectionVariable:'privateSet',leaderboard:{...ranks.leaderboard,valueField:'secret'}});saved.document.nodes.private={kind:'widget',section:'private'};saved.document.nodes[saved.document.root].children.push('private');saved.document.variables.privateSet={...set,source:{kind:'plan',query:'privateQuery'}};saved.document.queries.privateQuery={...query,sort:['-secret','id']};
 await decide(request,'manager','build','build.page.edit',{type:'build.page',id},{sections:saved.sections,document:saved.document});await decide(request,'manager','build','build.page.publish',{type:'build.page',id},{});
 const destination={formatVersion:2,uiProfile:pageUIProfile,root:'root',nodes:{root:{kind:'rows',children:['detail','back']},detail:{kind:'widget',section:'detail'},back:{kind:'widget',section:'back'}},variables:{selected:{scope:'application',type:'record',mode:'shared',source:{kind:'application',variable:'record',object:ref}}},events:[{source:'back',event:'click',target:'',navigate:{page:{app:'build',kind:'page',name:`${name}page`},interfaceVersion:0}}]};
 await decide(request,'manager','build','build.page.edit',{type:'build.page',id:other},{sections:[{id:'detail',widget:'detail',configVersion:1,title:'Shared destination details',recordVariable:'selected',fields:['name']},{id:'back',widget:'button',configVersion:1,title:'Back to Analytics'}],document:destination});await decide(request,'manager','build','build.page.publish',{type:'build.page',id:other},{});
 await open(page,'manager',`/application?id=${app}`);await page.getByRole('button',{name:'Review application release',exact:true}).click();await page.getByRole('button',{name:'Check draft and dependencies',exact:true}).click();await page.getByRole('button',{name:'Save immutable candidate',exact:true}).click();await page.getByRole('button',{name:'Activate release',exact:true}).click();const later=structuredClone(saved.sections);later.find((s:any)=>s.widget==='record-scatter').scatter.yField='pressure';await decide(request,'manager','build','build.page.edit',{type:'build.page',id},{sections:later});
 const runtime=await page.context().newPage();runtime.setDefaultTimeout(10_000);await stableReadRevision(runtime);const route=`/page?app=build&kind=page&name=${name}page&application=${application}&instance=main`;await open(runtime,'desk',route);const frame=(title:string)=>runtime.getByRole('heading',{name:title,exact:true,level:3}).locator('..'),scatter=frame('Pressure vs temperature'),rank=frame('Top revenue exposure'),detail=frame('Properties'),point=(n:number)=>scatter.getByRole('group',{name:'Record scatter plot',exact:true}).getByRole('button',{name:new RegExp(`R${String(n).padStart(2,'0')} · Pressure:`)});
 const choosePoint=async(n:number)=>{await point(n).focus();await point(n).press('Enter');};
 await expect(point(0)).toHaveAccessibleName(/Temperature: 10/);await expect(rank.getByRole('button',{name:'Asset 11',exact:true})).toBeVisible();await expect(runtime.getByRole('heading',{name:'Private Analytics ranks',exact:true})).toHaveCount(0);
 await choosePoint(1);await expect(detail.getByRole('definition').filter({hasText:/^Asset 01$/})).toBeVisible();await expect(point(1)).toHaveAttribute('aria-pressed','true');await rank.getByRole('button',{name:'Asset 11',exact:true}).click();await expect(detail.getByRole('definition').filter({hasText:/^Asset 11$/})).toBeVisible();await expect(point(11)).toHaveAttribute('aria-pressed','true');await expect(point(1)).toHaveAttribute('aria-pressed','false');
 await runtime.getByRole('button',{name:'Shared destination',exact:true}).click();await expect(frame('Shared destination details').getByRole('definition').filter({hasText:/^Asset 11$/})).toBeVisible();await runtime.getByRole('button',{name:'Back to Analytics',exact:true}).click();await expect(detail.getByRole('definition').filter({hasText:/^Asset 11$/})).toBeVisible();
 await runtime.route(`**/v1/records/${type}/R00`,r=>r.fulfill({status:403,contentType:'application/json',body:JSON.stringify({error:{message:'Denied'}})}));await choosePoint(0);await expect(scatter.getByRole('alert')).toContainText('could not be confirmed');await expect(detail.getByText('Select a record to see it here.',{exact:true})).toBeVisible();await runtime.unroute(`**/v1/records/${type}/R00`);
 let release:()=>void=()=>{},held=false;const gate=new Promise<void>(resolve=>release=resolve);await runtime.route(`**/v1/records/${type}/R02`,async r=>{held=true;await gate;await r.continue();});await choosePoint(2);await expect.poll(()=>held).toBe(true);await rank.getByRole('button',{name:'Asset 10',exact:true}).click();await expect(detail.getByRole('definition').filter({hasText:/^Asset 10$/})).toBeVisible();const completed=runtime.waitForResponse(r=>r.url().endsWith(`/${type}/R02`));release();await completed;await expect(point(2)).toHaveAttribute('aria-pressed','false');await expect(detail.getByRole('definition').filter({hasText:/^Asset 10$/})).toBeVisible();await runtime.unroute(`**/v1/records/${type}/R02`);
 const search=runtime.getByRole('textbox',{name:'Original search',exact:true});await search.fill('Asset 00');await expect(scatter.getByRole('group',{name:'Record scatter plot',exact:true}).getByRole('button')).toHaveCount(1);await expect(detail.getByText('Select a record to see it here.',{exact:true})).toBeVisible();await search.fill('');await expect(point(0)).toBeVisible();await choosePoint(1);await expect(detail.getByRole('definition').filter({hasText:/^Asset 01$/})).toBeVisible();if(process.env.PLATFORM_SCREENSHOTS)await runtime.screenshot({path:info.outputPath('original-analytics-shared-selection.png'),fullPage:true});await runtime.getByRole('button',{name:'Close application instance',exact:true}).click();await runtime.evaluate(route=>{location.hash=route},route);await expect(detail.getByText('Select a record to see it here.',{exact:true})).toBeVisible();
});
