import {expect,test} from "@playwright/test";
import {readFileSync} from "node:fs";
import {decide,fresh,open,pageUIProfile} from "./host";

test("three imported record-work widgets freeze original row actions, eight selected tiles and scoped editable notes",async({page,request},info)=>{
 test.setTimeout(150_000);page.setDefaultTimeout(10_000);
 const name=fresh("recordwork").replace(/[^a-z0-9]/gi,"").toLowerCase(),type=`build.${name}`,object=fresh("OBJ"),id=fresh("PAGE"),get=async(record:string)=>(await(await request.get(`/v1/records/${type}/${record}`,{headers:{Authorization:"Bearer manager"}})).json()).record,read=async()=>(await(await request.get(`/v1/records/build.page/${id}`,{headers:{Authorization:"Bearer manager"}})).json()).record;
 await decide(request,"manager","build","build.object.create",{type:"build.object",id:object},{name,title:"Original row assets",fields:[{name:"name",title:"Name",type:"text"},{name:"qty",title:"Quantity",type:"integer"}],states:[{name:"open",title:"Open"}],actions:[{name:"adjust",title:"Adjust originals",from:["open"],inputs:[{name:"next",title:"Next quantity",type:"integer",required:true}],sets:[{field:"qty",from:"next"}],conditions:[{field:"input.next",operator:">",value:"0",message:"Quantity must be positive"}]}]});await decide(request,"manager","build","build.object.publish",{type:"build.object",id:object},{});
 const rid=(i:number)=>`${name}${String(i).padStart(3,"0")}`;for(let i=0;i<52;i++)await decide(request,"manager","build",`${type}.create`,{type,id:rid(i)},{name:`ROW-${i}`,qty:10+i});
 const m=JSON.parse(readFileSync(new URL("../../packages/build/src/workshop/module-import/sample.workshop.json",import.meta.url),"utf8")),set=(id:string)=>({id,name:id,type:"objectSet",definitionKind:"objectSetDefinition",sourceObjectType:"Asset",objectSet:{objectType:"Asset",steps:[]}}),w=(id:string,type:string,name:string,config:any)=>({id,type,name,config});
 m.variables=[set("items"),set("localItems"),{id:"selected",name:"Selection",type:"object",definitionKind:"widgetOutput",widgetId:"tiles",widgetOutputKey:"activeObject"}];m.widgets={rows:w("rows","ActionTable","Row requests",{objectSetVarId:"items",actionId:"adjustAsset"}),tiles:w("tiles","MapTemplate","Ignored template label",{objectSetVarId:"items",activeVarId:"selected"}),note:w("note","NotepadEmbed","Original session note",{title:"Ignored note title"}),table:w("table","ObjectTable","Original full table",{objectSetVarId:"items",columns:[{key:"name"}]}),detail:w("detail","PropertyList","Selected tile",{objectVarId:"selected",properties:["name"],inlineEdit:false,hideNull:false}),localRows:w("localRows","ActionTable","Local requests",{objectSetVarId:"localItems",actionId:"adjustAsset"}),localNote:w("localNote","NotepadEmbed","Local note",{}),trigger:w("trigger","SingleButton","Open record panel",{label:"Open record panel",eventActions:[{kind:"openOverlay",overlayId:"panel"}]}),close:w("close","SingleButton","Close record panel",{label:"Close record panel",eventActions:[{kind:"closeOverlay",overlayId:"panel"}]})};m.sections={root:{id:"root",name:"Root",layout:"rows",children:["note","tiles","detail","rows","table","trigger"].map(id=>({kind:"widget",id}))},panel:{id:"panel",name:"Panel",layout:"rows",children:["localNote","localRows","close"].map(id=>({kind:"widget",id}))}};m.overlays=[{id:"panel",name:"Original record panel",kind:"drawer",rootSectionId:"panel"}];
 await decide(request,"manager","build","build.page.create",{type:"build.page",id},{name,title:"Original record work",object:type,sections:[{id:"initial",widget:"text",configVersion:1,text:"Initial"}],document:{formatVersion:2,uiProfile:pageUIProfile,root:"root",nodes:{root:{kind:"rows",children:["initial"]},initial:{kind:"widget",section:"initial"}}}});
 await open(page,"manager",`/compose?id=${id}`);await page.getByRole("button",{name:"Import Workshop module",exact:true}).click();const dialog=page.getByRole("dialog",{name:"Import Workshop module",exact:true});await dialog.getByRole("textbox",{name:"Source module JSON",exact:true}).fill(JSON.stringify(m));await dialog.getByRole("combobox",{name:"Map object Asset",exact:true}).selectOption(type);await dialog.getByRole("combobox",{name:"Map field Asset.name",exact:true}).selectOption("name");await dialog.getByRole("combobox",{name:"Map action adjustAsset",exact:true}).selectOption(`${type}.adjust`);for(const title of ["Row requests","Local requests"])await dialog.getByRole("group",{name:`Map row action ${title}`,exact:true}).getByRole("combobox",{name:"Original seed field for next",exact:true}).selectOption("qty");await dialog.getByRole("group",{name:"Map session note Original session note",exact:true}).getByRole("combobox",{name:"Note initial content",exact:true}).selectOption("sample");await dialog.getByRole("group",{name:"Map session note Local note",exact:true}).getByRole("combobox",{name:"Note initial content",exact:true}).selectOption("empty");await dialog.getByRole("checkbox").check();await dialog.getByRole("button",{name:"Apply imported page draft",exact:true}).click();
 await page.getByRole("button",{name:"Save",exact:true}).click();let saved:any;await expect.poll(async()=>{saved=await read();return saved.sections?.filter((s:any)=>s.widget==="action-table").length;}).toBe(2);const original=structuredClone(saved);await page.getByRole("button",{name:"Review release",exact:true}).click();await page.getByRole("button",{name:"Check draft and dependencies",exact:true}).click();await page.getByRole("button",{name:"Save immutable candidate",exact:true}).click();const note=saved.sections.find((s:any)=>s.widget==="notepad");saved.document.variables[note.notepadVariable].initial="LATER DRAFT";await decide(request,"manager","build","build.page.edit",{type:"build.page",id},{document:saved.document});await page.getByRole("button",{name:"Activate release",exact:true}).click();
 const runtime=await page.context().newPage();await open(runtime,"manager",`/page?app=build&kind=page&name=${name}`);const section=(title:string)=>runtime.getByRole("heading",{name:title,exact:true}).locator(".."),rows=section("Adjust originals"),tiles=section("Map Application"),text=runtime.getByRole("textbox",{name:"Original session note",exact:true});await expect(text).toContainText("Shift handover");await expect(text).not.toHaveValue("LATER DRAFT");await text.fill("My current handover");await expect(tiles.getByRole("button",{name:/^ROW-/})).toHaveCount(8);await tiles.getByRole("button",{name:"ROW-3",exact:true}).click();await expect(section("Selected tile")).toContainText("ROW-3");await expect(rows).toContainText("50 of 52 matching records");await expect(section("Original full table")).toContainText("1–52 of 52");
 const stage=async(area:any,old:string,value:string)=>{await area.getByRole("cell",{name:old,exact:true}).dblclick();const input=area.getByRole("table").getByRole("spinbutton");await input.fill(value);await input.press("Enter");},confirm=async(area:any)=>{await area.getByRole("button",{name:"Submit cell edits",exact:true}).click();await runtime.getByRole("dialog",{name:"Review row actions",exact:true}).getByRole("button",{name:"Confirm row actions",exact:true}).click();};
 await stage(rows,"10","101");await stage(rows,"11","-1");await rows.getByRole("button",{name:"Submit cell edits",exact:true}).click();await runtime.getByRole("dialog",{name:"Review row actions",exact:true}).getByRole("button",{name:"Cancel",exact:true}).click();expect((await get(rid(0))).qty).toBe(10);await confirm(rows);await expect(rows.getByRole("alert")).toContainText("Quantity must be positive");await expect.poll(async()=>(await get(rid(0))).qty).toBe(101);await expect(rows.getByRole("cell",{name:"-1",exact:true})).toBeVisible();await rows.getByRole("button",{name:"Cancel cell edits",exact:true}).click();await stage(rows,"11","102");await decide(request,"manager","build",`${type}.edit`,{type,id:rid(1)},{qty:103});await confirm(rows);await expect(rows.getByRole("alert")).toContainText(/CONFLICT|revision|changed/i);await expect(rows.getByRole("cell",{name:"102",exact:true})).toBeVisible();await rows.getByRole("button",{name:"Cancel cell edits",exact:true}).click();await stage(rows,"103","104");await confirm(rows);await expect.poll(async()=>(await get(rid(1))).qty).toBe(104);
 await runtime.getByRole("button",{name:"Open record panel",exact:true}).click();const panel=runtime.getByRole("dialog",{name:"Original record panel",exact:true}),localText=panel.getByRole("textbox",{name:"Local note",exact:true}),localRows=panel.getByRole("heading",{name:"Adjust originals",exact:true}).locator("..");await expect(localText).toHaveValue("");await localText.fill("Temporary local note");await panel.getByRole("button",{name:"Close record panel",exact:true}).click();await runtime.getByRole("button",{name:"Open record panel",exact:true}).click();await expect(localText).toHaveValue("");await panel.getByRole("button",{name:"Close record panel",exact:true}).click();await expect(text).toHaveValue("My current handover");
 if(process.env.PLATFORM_SCREENSHOTS){await rows.screenshot({path:info.outputPath("record-actions.png")});await tiles.screenshot({path:info.outputPath("record-tiles.png")});await section("Original session note").screenshot({path:info.outputPath("record-note.png")});await runtime.setViewportSize({width:390,height:844});await rows.screenshot({path:info.outputPath("record-actions-narrow.png")});await tiles.screenshot({path:info.outputPath("record-tiles-narrow.png")});await runtime.setViewportSize({width:1280,height:720});}

 // A lost answer retains the original K5 decision instead of producing a second row action.
 const retryKeys:string[]=[];let lose=true;await runtime.route("**/v1/submissions",async route=>{const body=route.request().postDataJSON();if(body.schema?.name!==`${type}.adjust`||body.target?.id!==rid(4))return route.continue();retryKeys.push(body.idempotencyKey);const response=await route.fetch();if(lose){lose=false;return route.abort("failed");}return route.fulfill({response});});await stage(rows,"14","114");await confirm(rows);await expect(rows.getByRole("alert")).toBeVisible();await confirm(rows);await expect.poll(async()=>(await get(rid(4))).qty).toBe(114);await expect(rows).toContainText("0 rows staged");expect(retryKeys.length).toBeGreaterThanOrEqual(2);expect(new Set(retryKeys).size).toBe(1);await runtime.unroute("**/v1/submissions");
 // Retiring an Overlay must stop the rest of its already reviewed rows, while the original first decision completes.
 await runtime.getByRole("button",{name:"Open record panel",exact:true}).click();await stage(localRows,"12","112");await stage(localRows,"13","113");let release!:()=>void,started=false;const gate=new Promise<void>(r=>release=r),keys:string[]=[];await runtime.route("**/v1/submissions",async route=>{const body=route.request().postDataJSON();if(body.schema?.name!==`${type}.adjust`)return route.continue();keys.push(body.target.id);if(body.target.id===rid(2)){const response=await route.fetch();started=true;await gate;return route.fulfill({response});}return route.continue();});await confirm(localRows);await expect.poll(()=>started).toBe(true);await panel.getByRole("button",{name:"Close record panel",exact:true}).click();release();await expect.poll(async()=>(await get(rid(2))).qty).toBe(112);await runtime.waitForTimeout(250);expect(keys).toEqual([rid(2)]);expect((await get(rid(3))).qty).toBe(13);await runtime.unroute("**/v1/submissions");
 await runtime.reload();await expect(text).toContainText("Shift handover");expect(original.document.uiProfile).toBe(pageUIProfile);
});
