import {expect,test} from '@playwright/test';
import {decide,fresh,open,pageUIProfile} from './host';

test('collection builder imports freezes and drives original table and complete count beyond the loaded source window',async({page,request},testInfo)=>{
 test.setTimeout(180_000);page.setDefaultTimeout(10_000);
 const name=fresh('builder').replace(/[^a-z0-9]/gi,'').toLowerCase(),type=`build.${name}`,object=fresh('OBJ'),query=fresh('QUERY'),parent=fresh('PAGE'),headers={Authorization:'Bearer manager'};
 await decide(request,'manager','build','build.object.create',{type:'build.object',id:object},{name,title:'Original collection assets',fields:[{name:'name',title:'Name',type:'text'},{name:'qty',title:'Quantity',type:'decimal'}]});await decide(request,'manager','build','build.object.publish',{type:'build.object',id:object},{});
 for(let i=1;i<=103;i++)await decide(request,'manager','build',`${type}.create`,{type,id:`R${String(i).padStart(3,'0')}`},{name:`Original record ${i}`,qty:i});
 await decide(request,'manager','build','build.query.create',{type:'build.query',id:query},{name:`${name}source`,title:'Retained original base',description:'Complete original source, two-row read window',object:type,sort:['id'],limit:2});await decide(request,'manager','build','build.query.publish',{type:'build.query',id:query},{});
 const definitions=await(await request.get('/v1/definitions',{headers})).json(),q=definitions.find((d:any)=>d.ref.kind==='query'&&d.ref.name===`${name}source`),binding={ref:q.ref,sourceVersion:q.version};
 const widgets={builder:{id:'builder',name:'Collection conditions',type:'ObjectSetBuilder',config:{objectSetVarId:'base',outputVarId:'filtered'}},table:{id:'table',name:'Original result rows',type:'ObjectTable',config:{objectSetVarId:'filtered',columns:[{key:'name',label:'Name'},{key:'qty',label:'Quantity'}]}},count:{id:'count',name:'Complete collection count',type:'MetricCard',config:{variableId:'count',label:'Complete collection count'}}},module={id:'source',name:'Collection task source',pages:[{id:'page',name:'Collection task source',rootSectionId:'root'}],sections:{root:{id:'root',name:'Root',layout:'rows',children:Object.keys(widgets).map(id=>({kind:'widget',id}))}},widgets,variables:[{id:'base',name:'Original base',type:'objectSet',definitionKind:'objectSetDefinition',objectSet:{objectType:'Asset',steps:[]}},{id:'filtered',name:'Filtered output',type:'array',definitionKind:'static',staticValue:[]},{id:'count',name:'Complete count',type:'numeric',definitionKind:'variableTransformation',inputVarId:'filtered',transformations:[{op:'cardinality'}]}],overlays:[],unusedWidgetIds:[]};
 await decide(request,'manager','build','build.page.create',{type:'build.page',id:parent},{name:`${name}page`,title:'Collection task',object:type,sections:[{id:'initial',widget:'text',configVersion:1,text:'Initial'}],document:{formatVersion:2,uiProfile:pageUIProfile,root:'root',nodes:{root:{kind:'rows',children:['initial']},initial:{kind:'widget',section:'initial'}}}});
 await open(page,'manager',`/compose?id=${parent}`);await page.getByRole('button',{name:'Import Workshop module',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Import Workshop module',exact:true});await dialog.getByRole('textbox',{name:'Source module JSON',exact:true}).fill(JSON.stringify(module));await dialog.getByRole('combobox',{name:'Map object Asset',exact:true}).selectOption(type);for(const field of ['name','qty'])await dialog.getByRole('combobox',{name:`Map field Asset.${field}`,exact:true}).selectOption(field);await dialog.getByRole('combobox',{name:'Optional query binding Original base',exact:true}).selectOption(JSON.stringify(binding));
 const migration=dialog.getByRole('group',{name:'Map collection builder Collection conditions',exact:true});await migration.getByRole('combobox',{name:'Collection source interpretation',exact:true}).selectOption('complete-predicate');await migration.getByRole('button',{name:'Name',exact:true}).click();await migration.getByRole('button',{name:'Quantity',exact:true}).click();await dialog.getByRole('checkbox').check();await expect(dialog.getByRole('button',{name:'Apply imported page draft',exact:true})).toBeEnabled();await dialog.getByRole('button',{name:'Apply imported page draft',exact:true}).click();await page.getByRole('heading',{name:'Collection conditions',level:3,exact:true}).click();await expect(page.getByRole('combobox',{name:'Complete collection output',exact:true})).toHaveValue(/import_builder_output_/);await page.getByRole('button',{name:'Save',exact:true}).click();await expect.poll(async()=>{const body=await(await request.get(`/v1/records/build.page/${parent}`,{headers})).json();return body.record.sections.some((s:any)=>s.widget==='collection-builder');}).toBe(true);
 await page.getByRole('button',{name:'Review release',exact:true}).click();await page.getByRole('button',{name:'Check draft and dependencies',exact:true}).click();await page.getByRole('button',{name:'Save immutable candidate',exact:true}).click();await page.getByRole('button',{name:'Activate release',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'Release active for operators.'})).toBeVisible();
 const saved=await(await request.get(`/v1/records/build.page/${parent}`,{headers})).json(),changed=structuredClone(saved.record.sections);changed.find((s:any)=>s.collectionBuilder).collectionBuilder.fields=['name'];await decide(request,'manager','build','build.page.edit',{type:'build.page',id:parent},{sections:changed});
 const runtime=await page.context().newPage();runtime.setDefaultTimeout(10_000);await open(runtime,'desk',`/page?app=build&kind=page&name=${name}page`);const section=(title:string)=>runtime.getByRole('heading',{name:title,level:3,exact:true}).locator('..'),builder=section('Collection conditions'),table=section('Original result rows'),count=section('Complete collection count');
 await expect(count.getByText('103',{exact:true})).toBeVisible();await expect(table).toContainText('1–100 of 103');await builder.getByRole('button',{name:'Filter',exact:true}).click();await builder.getByRole('combobox',{name:'Field',exact:true}).selectOption('qty');await builder.getByRole('combobox',{name:'Operator',exact:true}).selectOption('gte');const draft=builder.getByRole('textbox');await draft.fill('101');
 await table.getByRole('button',{name:'Next page',exact:true}).click();await expect(table).toContainText('101–103 of 103');await expect(draft).toHaveValue('101');await expect(count.getByText('103',{exact:true})).toBeVisible();await builder.getByRole('button',{name:'Apply collection conditions',exact:true}).click();await expect(count.getByText('3',{exact:true})).toBeVisible();await expect(table).toContainText('Original record 101');await expect(table).not.toContainText('Original record 100');
 await decide(request,'manager','build',`${type}.edit`,{type,id:'R103'},{qty:100});await expect(count.getByText('2',{exact:true})).toBeVisible();await expect(draft).toHaveValue('101');await draft.fill('invalid');await expect(builder.getByRole('button',{name:'Apply collection conditions',exact:true})).toBeDisabled();await expect(count.getByText('2',{exact:true})).toBeVisible();await expect(builder.getByRole('alert')).toBeVisible();
 if(process.env.PLATFORM_SCREENSHOTS)await runtime.screenshot({path:testInfo.outputPath('collection-builder.png'),fullPage:true});
 await builder.getByRole('button',{name:'Clear collection conditions',exact:true}).click();await expect(count.getByText('103',{exact:true})).toBeVisible();await expect(builder.getByRole('combobox',{name:'Field',exact:true})).toHaveCount(0);
 const record=await(await request.get(`/v1/records/build.page/${parent}`,{headers})).json();expect(record.record.sections.find((s:any)=>s.collectionBuilder).collectionBuilder.fields).toEqual(['name']);await runtime.reload();await expect(count.getByText('103',{exact:true})).toBeVisible();await builder.getByRole('button',{name:'Filter',exact:true}).click();await expect(builder.getByRole('combobox',{name:'Field',exact:true})).toContainText('Quantity');
});
