import {expect,test} from "@playwright/test";
import {decide,fresh,open,pageUIProfile} from "./host";

test("an overlay copy freezes its own entry and resources and retires input, selection and late responses on close",async({page,request},testInfo)=>{
 test.setTimeout(90_000);
 const name=fresh("overlaycopy").replace(/[^a-z0-9]/gi,"").toLowerCase(),type=`build.${name}`,object=fresh("OBJ"),id=fresh("PAGE"),ref={app:"build",kind:"object",name:type};
 await decide(request,"manager","build","build.object.create",{type:"build.object",id:object},{name,title:"Copied picker notes",fields:[{name:"note",title:"Note",type:"text"},{name:"bucket",title:"Bucket",type:"text"}],states:[{name:"open",title:"Open"},{name:"done",title:"Done"}],actions:[{name:"close",title:"Complete selected note",from:["open"],to:"done",inputs:[{name:"reason",title:"Completion reason",type:"text",required:true}]}]});await decide(request,"manager","build","build.object.publish",{type:"build.object",id:object},{});
 for(const [suffix,bucket] of [["A","A"],["B","B"]])await decide(request,"desk","build",`${type}.create`,{type,id:`${name}${suffix}`},{note:`PICK-${suffix}`,bucket});
 const sections=[{id:"main",widget:"table",configVersion:1,title:"Page notes",fields:["note"]},{id:"pageDetail",widget:"detail",configVersion:1,title:"Page selection",fields:["note"]},{id:"trigger",widget:"button",configVersion:1,title:"Open original picker"},{id:"global",widget:"input",configVersion:1,title:"Page text"},{id:"parameter",widget:"input",configVersion:1,title:"Picker bucket"},{id:"scratch",widget:"input",configVersion:1,title:"Picker scratch"},{id:"shared",widget:"input",configVersion:1,title:"Shared page text"},{id:"local",widget:"table",configVersion:1,title:"Local notes",fields:["note","state"],collectionVariable:"window"},{id:"detail",widget:"detail",configVersion:1,title:"Local selection",fields:["note","state"],recordVariable:"picked"},{id:"action",widget:"inline-action",configVersion:1,title:"Picked work",actions:[`${type}.close`]},{id:"card",widget:"detail",configVersion:1,title:"Picker card",fields:["note"],recordVariable:"item"},{id:"close",widget:"button",configVersion:1,title:"Close picker"}];
 await decide(request,"manager","build","build.page.create",{type:"build.page",id},{name,title:"Overlay copy desk",object:type,sections,document:{formatVersion:2,uiProfile:pageUIProfile,root:"root",nodes:{root:{kind:"rows",title:"Page root",children:["main","pageDetail","global","trigger"]},...Object.fromEntries(sections.map(s=>[s.id,{kind:"widget",section:s.id,...(s.id==="parameter"?{valueVariable:"bucket"}:s.id==="scratch"?{valueVariable:"scratchValue"}:s.id==="global"||s.id==="shared"?{valueVariable:"pageText"}:{})}])),picker:{kind:"rows",children:["parameter","scratch","shared","local","detail","action","cards","close"]},cards:{kind:"loop",title:"Picker cards",children:["card"],loop:{collection:"window",itemVariable:"item",limit:2}}},overlays:{picker:{root:"picker",kind:"drawer",title:"Find a note",openVariable:"opened"}},variables:{opened:{scope:"page",type:"boolean",mode:"state",initial:false},pageText:{scope:"page",type:"string",mode:"state",initial:"page seed"},bucket:{scope:"overlay",owner:"picker",type:"string",mode:"state",initial:"A"},scratchValue:{scope:"overlay",owner:"picker",type:"string",mode:"state",initial:"scratch seed"},window:{scope:"overlay",owner:"picker",type:"object-set",mode:"resource",source:{kind:"plan",query:"notes"}},picked:{scope:"overlay",owner:"picker",type:"record",mode:"resource",source:{kind:"record",section:"local"}},item:{scope:"loop-item",owner:"cards",type:"record",mode:"resource",source:{kind:"item",node:"cards"}}},queries:{notes:{owner:"picker",object:ref,limit:2,conditions:[{field:"bucket",op:"=",value:{variable:"bucket"}}]}},events:[{source:"trigger",event:"click",effects:[{kind:"set", target:"opened", value:true}]},{source:"close",event:"click",effects:[{kind:"set", target:"opened", value:false}]}]}});
 await open(page,"manager",`/compose?id=${id}`);const tree=page.getByRole("region",{name:"Widgets and layout",exact:true}),inspector=page.getByRole("region",{name:"The widget in hand",exact:true});await tree.getByRole("button",{name:"Commands for Find a note",exact:true}).click();await page.getByRole("menuitem",{name:"Copy layout",exact:true}).click();await expect(page.getByRole("button",{name:"Save",exact:true})).toBeDisabled();await tree.getByRole("button",{name:"Commands for Page root",exact:true}).click();await page.getByRole("menuitem",{name:"Paste layout",exact:true}).click();await expect(inspector.getByRole("textbox",{name:"Overlay title",exact:true})).toHaveValue("Copy of Find a note");await expect(inspector.getByRole("combobox",{name:"Overlay kind",exact:true})).toHaveValue("drawer");await inspector.getByRole("combobox",{name:"Overlay kind",exact:true}).selectOption("modal");
 await page.getByRole("button",{name:"Undo",exact:true}).click();await page.getByRole("button",{name:"Undo",exact:true}).click();await expect(tree.getByRole("button",{name:"Commands for Copy of Find a note",exact:true})).toHaveCount(0);await page.getByRole("button",{name:"Redo",exact:true}).click();await page.getByRole("button",{name:"Redo",exact:true}).click();await expect(tree.getByRole("button",{name:"Commands for Copy of Find a note",exact:true})).toBeVisible();
 if(process.env.PLATFORM_SCREENSHOTS){await tree.getByRole("button",{name:"Commands for Copy of Find a note",exact:true}).click();await page.getByRole("menuitem",{name:"Select layout",exact:true}).click();await inspector.screenshot({path:testInfo.outputPath("overlay-copy-inspector.png")});}
 await page.getByRole("button",{name:"Save",exact:true}).click();await expect(page.getByRole("button",{name:"Save",exact:true})).toBeDisabled();const saved=(await(await request.get(`/v1/records/build.page/${id}`,{headers:{Authorization:"Bearer manager"}})).json()).record,[copyID,copyOverlay]=Object.entries(saved.document.overlays).find(([id])=>id!=="picker") as [string,any],copyQuery=Object.keys(saved.document.queries).find(id=>saved.document.queries[id].owner===copyID)!;
 expect(copyOverlay.root).not.toBe(copyID);expect(saved.document.nodes.root.children).not.toContain(copyOverlay.root);expect(saved.document.variables[copyOverlay.openVariable].initial).toBe(false);expect(saved.document.overlays.picker.kind).toBe("drawer");expect(saved.document.events.some((e:any)=>e.target===copyOverlay.openVariable&&e.value===true)).toBe(true);
 await page.getByRole("button",{name:"Review release",exact:true}).click();await page.getByRole("button",{name:"Check draft and dependencies",exact:true}).click();await page.getByRole("button",{name:"Save immutable candidate",exact:true}).click();saved.document.queries[copyQuery].conditions=[{field:"bucket",op:"=",value:{literal:"missing"}}];await decide(request,"manager","build","build.page.edit",{type:"build.page",id},{document:saved.document});await page.getByRole("button",{name:"Activate release",exact:true}).click();
 const operation=await page.context().newPage();await open(operation,"desk",`/page?app=build&kind=page&name=${name}`);const original=operation.getByRole("dialog",{name:"Find a note",exact:true}),copy=operation.getByRole("dialog",{name:"Copy of Find a note",exact:true}),copyEntry=operation.getByRole("button",{name:"Open Copy of Find a note",exact:true}),originalEntry=operation.getByRole("button",{name:"Open original picker",exact:true}),pageDetail=operation.getByRole("heading",{name:"Page selection",exact:true}).locator("..");
 await expect(copy).not.toBeVisible();await operation.getByRole("heading",{name:"Page notes",exact:true}).locator("..").getByRole("row").filter({hasText:"PICK-B"}).click();await expect(pageDetail.getByText("PICK-B",{exact:true})).toBeVisible();await originalEntry.click();await original.getByRole("textbox",{name:"Picker bucket",exact:true}).fill("B");await original.getByRole("textbox",{name:"Picker scratch",exact:true}).fill("Original scratch");await original.getByRole("textbox",{name:"Shared page text",exact:true}).fill("Shared parent input");await original.getByRole("button",{name:"Close picker",exact:true}).click();await expect(originalEntry).toBeFocused();
 await copyEntry.click();await expect(copy.getByRole("textbox",{name:"Picker bucket",exact:true})).toHaveValue("A");await expect(copy.getByRole("textbox",{name:"Picker scratch",exact:true})).toHaveValue("scratch seed");await expect(copy.getByRole("textbox",{name:"Shared page text",exact:true})).toHaveValue("Shared parent input");const table=copy.getByRole("heading",{name:"Local notes",exact:true}).locator(".."),detail=copy.getByRole("heading",{name:"Local selection",exact:true}).locator(".."),form=copy.getByRole("heading",{name:"Picked work",exact:true}).locator("..");await expect(table.getByRole("row").filter({hasText:"PICK-A"})).toBeVisible();await expect(copy.getByRole("list",{name:"Picker cards",exact:true}).getByText("PICK-A",{exact:true})).toBeVisible();await table.getByRole("row").filter({hasText:"PICK-A"}).click();await expect(detail.getByText("PICK-A",{exact:true})).toBeVisible();await form.getByRole("textbox",{name:"Completion reason *",exact:true}).fill("Copied work");await form.getByRole("button",{name:"Complete selected note",exact:true}).click();await expect(detail.getByText("Done",{exact:true})).toBeVisible();
 let release!:()=>void,delivered!:()=>void,held=false;const finished=new Promise<void>(resolve=>delivered=resolve),gate=new Promise<void>(resolve=>release=resolve);await operation.route(`**/v1/records/${type}?*`,async route=>{if(!held&&(new URL(route.request().url()).searchParams.get("domain")??"").includes('"B"')){const response=await route.fetch();held=true;await gate;await route.fulfill({response});delivered();}else await route.continue();});await copy.getByRole("textbox",{name:"Picker bucket",exact:true}).fill("B");await expect.poll(()=>held).toBe(true);await copy.getByRole("button",{name:"Close picker",exact:true}).click();await expect(copyEntry).toBeFocused();await copyEntry.click();await expect(copy.getByRole("textbox",{name:"Picker bucket",exact:true})).toHaveValue("A");await expect(table.getByRole("row").filter({hasText:"PICK-A"})).toBeVisible();release();await finished;await expect(table.getByText("PICK-B",{exact:true})).toHaveCount(0);await expect(detail).toContainText("Select a record to see it here.");await operation.unroute(`**/v1/records/${type}?*`);
 if(process.env.PLATFORM_SCREENSHOTS){await copy.screenshot({path:testInfo.outputPath("overlay-copy-runtime.png")});await operation.setViewportSize({width:390,height:844});await operation.evaluate(()=>new Promise<void>(r=>requestAnimationFrame(()=>requestAnimationFrame(()=>r()))));await copy.screenshot({path:testInfo.outputPath("overlay-copy-runtime-narrow.png")});}
 await copy.getByRole("textbox",{name:"Picker scratch",exact:true}).fill("Closed copy draft");await copy.getByRole("button",{name:"Close picker",exact:true}).click();await originalEntry.click();await expect(original.getByRole("textbox",{name:"Picker bucket",exact:true})).toHaveValue("A");await expect(original.getByRole("textbox",{name:"Picker scratch",exact:true})).toHaveValue("scratch seed");await original.getByRole("button",{name:"Close picker",exact:true}).click();await expect(pageDetail.getByText("PICK-B",{exact:true})).toBeVisible();await operation.reload();await expect(copy).not.toBeVisible();await copyEntry.click();await expect(copy.getByRole("textbox",{name:"Picker scratch",exact:true})).toHaveValue("scratch seed");
});
