import {expect,test} from '@playwright/test';
import {defaultAnalyticsChartGroup} from '../../packages/build/src/module-import/default-analytics.fixture.mjs';
import {decide,fresh,open,pageUIProfile,stableReadRevision} from './host';
test('five original Analytics charts freeze complete aggregates and a line window independent of table pagination and sorting',async({page,request},info)=>{
 test.setTimeout(120_000);page.setDefaultTimeout(10_000);const name=fresh('graphs').replace(/[^a-z0-9]/gi,'').toLowerCase(),type=`build.${name}`,obj=fresh('OBJ'),id=fresh('PAGE'),headers={Authorization:'Bearer manager'};
 await decide(request,'manager','build','build.object.create',{type:'build.object',id:obj},{name,title:'Original chart assets',fields:[{name:'name',title:'Name',type:'text',search:true},{name:'status',title:'Status',type:'choice',choices:'active,warning,offline,maintenance'},{name:'priority',title:'Priority',type:'choice',choices:'Low,High'},{name:'owner',title:'Owner',type:'text'},{name:'pressure',title:'Pressure',type:'integer'},{name:'availability',title:'Availability',type:'integer'},{name:'secret',title:'Private measure',type:'integer',read:['builder']}]});await decide(request,'manager','build','build.object.publish',{type:'build.object',id:obj},{});
 for(let n=0;n<102;n++)await decide(request,'manager','build',`${type}.create`,{type,id:`R${String(n).padStart(3,'0')}`},{name:`Original ${String(n).padStart(3,'0')}`,status:n<60?'active':n<90?'warning':'offline',priority:n%2?'Low':'High',owner:'Original owner',pressure:n,availability:n===101?1000:100,secret:1});
 await decide(request,'manager','build','build.page.create',{type:'build.page',id},{name:`${name}page`,title:'Original five charts',object:type,sections:[{id:'initial',widget:'text',configVersion:1,text:'Initial'}],document:{formatVersion:2,uiProfile:pageUIProfile,root:'root',nodes:{root:{kind:'rows',children:['initial']},initial:{kind:'widget',section:'initial'}}}});
 const fixture=defaultAnalyticsChartGroup(pageUIProfile);await open(page,'manager',`/compose?id=${id}`);await page.getByRole('button',{name:'Import Workshop module',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Import Workshop module',exact:true});await dialog.getByRole('textbox',{name:'Source module JSON',exact:true}).fill(JSON.stringify(fixture.module));await dialog.getByRole('combobox',{name:'Map object Asset',exact:true}).selectOption(type);for(const field of ['id','name','status','priority','owner','pressure','availability'])await dialog.getByRole('combobox',{name:`Map field Asset.${field}`,exact:true}).selectOption(field);await dialog.getByRole('checkbox').last().check();await expect(dialog.getByRole('button',{name:'Apply imported page draft',exact:true})).toBeEnabled();await dialog.getByRole('button',{name:'Apply imported page draft',exact:true}).click();await page.getByRole('button',{name:'Save',exact:true}).click();let saved:any;await expect.poll(async()=>{saved=(await(await request.get(`/v1/records/build.page/${id}`,{headers})).json()).record;return saved.sections.length;}).toBe(7);
 const line=saved.sections.find((s:any)=>s.widget==='record-chart'),table=saved.sections.find((s:any)=>s.widget==='table');expect(line.collectionVariable).not.toBe(table.collectionVariable);const hidden={...structuredClone(saved.sections.find((s:any)=>s.title==='Availability by Status')),id:'private',title:'Private grouped chart',measure:'avg:secret'},document=structuredClone(saved.document);document.nodes.private={kind:'widget',section:'private'};document.nodes[document.root].children.push('private');await decide(request,'manager','build','build.page.edit',{type:'build.page',id},{sections:[...saved.sections,hidden],document});await decide(request,'manager','build','build.page.publish',{type:'build.page',id},{});
 await page.getByRole('button',{name:'Review release',exact:true}).click();await page.getByRole('button',{name:'Check draft and dependencies',exact:true}).click();await page.getByRole('button',{name:'Save immutable candidate',exact:true}).click();await page.getByRole('button',{name:'Activate release',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'Release active for operators.'})).toBeVisible();const later=structuredClone(saved.sections);later.find((s:any)=>s.widget==='record-chart').recordChart.mark='bar';await decide(request,'manager','build','build.page.edit',{type:'build.page',id},{sections:later});
 const runtime=await page.context().newPage();runtime.setDefaultTimeout(10_000);await stableReadRevision(runtime);const aggregates:any[]=[];runtime.on('response',async response=>{if(response.url().endsWith(`/v1/aggregates/${type}/query`)&&response.ok())aggregates.push({query:response.request().postDataJSON(),body:await response.json()});});await open(runtime,'desk',`/page?app=build&kind=page&name=${name}page`);const frame=(title:string)=>runtime.getByRole('heading',{name:title,exact:true,level:3}).locator('..'),plot=frame('Pressure over Assets'),window=frame('Original query window'),pivot=frame('Status × Priority');await expect(plot.getByText('Plotting 40 of 100 records in this window.',{exact:true})).toBeVisible();await expect(plot.getByRole('img')).toBeVisible();await expect(runtime.getByRole('heading',{name:'Private grouped chart',exact:true})).toHaveCount(0);await expect.poll(()=>aggregates.find(r=>r.query.measures?.[0]==='avg:availability')?.body.rows).toEqual([{status:'active','avg:availability':100},{status:'offline','avg:availability':175},{status:'warning','avg:availability':100}]);await expect(pivot.getByRole('rowheader',{name:'Total',exact:true}).locator('..').getByRole('cell').last()).toHaveText('102');for(const title of ['Status Distribution','Priority Breakdown'])await expect(frame(title).getByRole('img')).toBeVisible();await expect.poll(()=>aggregates.some(r=>r.query.groups?.[0]==='status'&&r.query.groups.length===1&&r.query.measures?.[0]==='count'&&r.body.rows.reduce((sum:number,row:any)=>sum+row.count,0)===102)).toBe(true);
 const before=aggregates.length;await window.getByRole('button',{name:'Next page',exact:true}).click();await expect(window.getByText('101–102 of 102',{exact:true})).toBeVisible();await expect(plot.getByText('Plotting 40 of 100 records in this window.',{exact:true})).toBeVisible();await expect(pivot.getByRole('rowheader',{name:'Total',exact:true}).locator('..').getByRole('cell').last()).toHaveText('102');expect(aggregates.length).toBe(before);await window.getByRole('combobox',{name:'Sort',exact:true}).selectOption('-name');await expect(plot.getByText('Plotting 40 of 100 records in this window.',{exact:true})).toBeVisible();
 await plot.getByRole('button',{name:'Next',exact:true}).click();await expect(plot.getByText('Plotting 2 of 2 records in this window.',{exact:true})).toBeVisible();await expect(window.getByText('1–100 of 102',{exact:true})).toBeVisible();await runtime.getByRole('textbox',{name:'Original search',exact:true}).fill('Original 101');await expect(plot.getByText('Plotting 1 of 1 records in this window.',{exact:true})).toBeVisible();await expect(pivot.getByRole('rowheader',{name:'Total',exact:true}).locator('..').getByRole('cell').last()).toHaveText('1');await expect.poll(()=>aggregates.some(r=>r.query.search==='Original 101'&&r.query.measures?.[0]==='avg:availability'&&r.body.rows[0]?.['avg:availability']===1000)).toBe(true);await runtime.getByRole('textbox',{name:'Original search',exact:true}).fill('');await expect(pivot.getByRole('rowheader',{name:'Total',exact:true}).locator('..').getByRole('cell').last()).toHaveText('102');if(process.env.PLATFORM_SCREENSHOTS){await pivot.scrollIntoViewIfNeeded();await pivot.screenshot({path:info.outputPath('original-analytics-pivot.png')});await frame('Availability by Status').scrollIntoViewIfNeeded();await frame('Availability by Status').screenshot({path:info.outputPath('original-analytics-average.png')});}
});
