import {expect,test} from "@playwright/test";
import {readFileSync} from "node:fs";
import {decide,fresh,open,pageUIProfile,stableReadRevision} from "./host";

test("default status tracker freezes mapped original states and follows records without performing transitions",async({page,request},info)=>{
 test.setTimeout(90_000);
 const name=fresh("status").replace(/[^a-z0-9]/gi,"").toLowerCase(),type=`build.${name}`,object=fresh("OBJ"),id=fresh("PAGE"),stages=["Active","Warning","Maintenance","Offline"],states=stages.map(title=>({name:title.toLowerCase(),title}));
 await decide(request,"manager","build","build.object.create",{type:"build.object",id:object},{name,title:"Tracked assets",fields:[{name:"note",title:"Note",type:"text"}],states,actions:[{name:"warn",title:"Mark warning",from:["active"],to:"warning"},{name:"offline",title:"Take offline",from:["active","warning","maintenance"],to:"offline",inputs:[{name:"reason",title:"Reason",type:"text",required:true}]}]});await decide(request,"manager","build","build.object.publish",{type:"build.object",id:object},{});
 for(const suffix of ["A","B"])await decide(request,"desk","build",`${type}.create`,{type,id:`${name}${suffix}`},{note:`ASSET-${suffix}`});await decide(request,"desk","build",`${type}.warn`,{type,id:`${name}B`},{});
 const m=JSON.parse(readFileSync(new URL("../../packages/build/src/workshop/module-import/sample.workshop.json",import.meta.url),"utf8"));
 m.widgets={table:m.widgets.table,status:{id:"status",name:"Asset status",type:"StatusTracker",config:{objectVarId:"selected",stages,activeProp:"status"}},action:m.widgets.action,trigger:{id:"trigger",name:"Open local status",type:"SingleButton",config:{label:"Open local status",eventActions:[{kind:"openOverlay",overlayId:"panel"}]}},close:{id:"close",name:"Close local status",type:"SingleButton",config:{label:"Close local status",eventActions:[{kind:"closeOverlay",overlayId:"panel"}]}},picker:{id:"picker",name:"Local assets",type:"ObjectTable",config:{objectSetVarId:"localNotes",activeVarId:"localSelected",columns:[{key:"name"}],enableSelection:true,selectionMode:"single",enableInlineEdit:false}},localStatus:{id:"localStatus",name:"Local status",type:"StatusTracker",config:{objectVarId:"localSelected",stages,activeProp:"status"}}};
 m.sections={root:{id:"root",name:"Root",layout:"rows",children:[{kind:"widget",id:"table"},{kind:"widget",id:"status"},{kind:"widget",id:"action"},{kind:"widget",id:"trigger"}]},panel:{id:"panel",name:"Panel",layout:"rows",children:[{kind:"widget",id:"picker"},{kind:"widget",id:"localStatus"},{kind:"widget",id:"close"}]}};
 m.variables=m.variables.filter((v:any)=>v.id!=="scratch");m.variables.push({...structuredClone(m.variables.find((v:any)=>v.id==="notes")),id:"localNotes",name:"Local notes"},{id:"localSelected",name:"Local selection",type:"object",definitionKind:"widgetOutput",widgetId:"picker",widgetOutputKey:"activeObject"});m.overlays=[{id:"panel",name:"Local status panel",kind:"drawer",rootSectionId:"panel"}];
 await decide(request,"manager","build","build.page.create",{type:"build.page",id},{name,title:"Status page",object:type,sections:[{id:"initial",widget:"table",configVersion:1,fields:["note"]}],document:{formatVersion:2,uiProfile:pageUIProfile,root:"root",nodes:{root:{kind:"rows",children:["initial"]},initial:{kind:"widget",section:"initial"}}}});
 await open(page,"manager",`/compose?id=${id}`);await page.getByRole("button",{name:"Import Workshop module",exact:true}).click();const dialog=page.getByRole("dialog",{name:"Import Workshop module",exact:true});await dialog.getByRole("textbox",{name:"Source module JSON",exact:true}).fill(JSON.stringify(m));await dialog.getByRole("combobox",{name:"Map object Asset",exact:true}).selectOption(type);await dialog.getByRole("combobox",{name:"Map field Asset.name",exact:true}).selectOption("note");await dialog.getByRole("combobox",{name:"Map field Asset.status",exact:true}).selectOption("state");await dialog.getByRole("combobox",{name:"Map action finishAsset",exact:true}).selectOption(`${type}.offline`);
 for(const widget of ["Asset status","Local status"])for(const state of stages)await dialog.getByRole("group",{name:`Map lifecycle stages ${widget}`,exact:true}).getByRole("combobox",{name:`Map lifecycle state ${state}`,exact:true}).selectOption(state.toLowerCase());await dialog.getByRole("checkbox").check();await dialog.getByRole("button",{name:"Apply imported page draft",exact:true}).click();
 await page.getByRole("region",{name:"Widgets and layout",exact:true}).getByRole("button",{name:"Asset status",exact:true}).click();const inspector=page.getByRole("region",{name:"The widget in hand",exact:true}),options=inspector.getByRole("group",{name:"Displayed stages",exact:true});for(const state of stages)await options.getByRole("button",{name:state,exact:true}).click();await expect(page.getByRole("button",{name:"Save",exact:true})).toBeDisabled();for(const state of stages)await options.getByRole("button",{name:state,exact:true}).click();await page.getByRole("button",{name:"Save",exact:true}).click();
 let saved:any;await expect.poll(async()=>{saved=(await(await request.get(`/v1/records/build.page/${id}`,{headers:{Authorization:"Bearer manager"}})).json()).record;return saved.sections?.find((s:any)=>s.widget==="status-tracker")?.statusTracker.stages;}).toEqual(states.map(s=>s.name));
 await page.getByRole("button",{name:"Review release",exact:true}).click();await page.getByRole("button",{name:"Check draft and dependencies",exact:true}).click();await page.getByRole("button",{name:"Save immutable candidate",exact:true}).click();saved.sections.find((s:any)=>s.widget==="status-tracker").statusTracker.stages=["active"];await decide(request,"manager","build","build.page.edit",{type:"build.page",id},{sections:saved.sections,document:saved.document});await page.getByRole("button",{name:"Activate release",exact:true}).click();
 const runtime=await page.context().newPage();await stableReadRevision(runtime);await open(runtime,"desk",`/page?app=build&kind=page&name=${name}`);const table=runtime.getByRole("heading",{name:"Imported notes",exact:true}).locator(".."),tracker=runtime.getByRole("heading",{name:"Asset status",exact:true}).locator(".."),active=tracker.locator('li[aria-current="step"]');await table.getByRole("cell",{name:"ASSET-A",exact:true}).click();await expect(active).toHaveText("Active");await expect(tracker.getByRole("listitem")).toHaveCount(4);await table.getByRole("cell",{name:"ASSET-B",exact:true}).click();await expect(active).toHaveText("Warning");await tracker.getByText("Offline",{exact:true}).click();expect((await(await request.get(`/v1/records/${type}/${name}B`,{headers:{Authorization:"Bearer desk"}})).json()).record.state).toBe("warning");await expect(active).toHaveText("Warning");
 if(process.env.PLATFORM_SCREENSHOTS){await tracker.screenshot({path:info.outputPath("status-tracker.png")});await runtime.setViewportSize({width:390,height:844});await tracker.screenshot({path:info.outputPath("status-tracker-narrow.png")});await runtime.setViewportSize({width:1280,height:720});}
 const form=runtime.getByRole("heading",{name:"Imported action",exact:true}).locator("..");await form.getByRole("textbox",{name:"Reason *",exact:true}).fill("Original controlled transition");await form.getByRole("button",{name:"Take offline",exact:true}).click();await expect.poll(async()=>(await(await request.get(`/v1/records/${type}/${name}B`,{headers:{Authorization:"Bearer desk"}})).json()).record.state).toBe("offline");await expect(active).toHaveText("Offline");await table.getByRole("cell",{name:"ASSET-A",exact:true}).click();await expect(active).toHaveText("Active");
 await runtime.getByRole("button",{name:"Open local status",exact:true}).click();const panel=runtime.getByRole("dialog",{name:"Local status panel",exact:true}),local=panel.getByRole("heading",{name:"Local status",exact:true}).locator("..");await expect(local.getByText("Select a record to see it here.",{exact:true})).toBeVisible();await panel.getByRole("cell",{name:"ASSET-B",exact:true}).click();await expect(local.locator('li[aria-current="step"]')).toHaveText("Offline");await panel.getByRole("button",{name:"Close local status",exact:true}).click();await runtime.getByRole("button",{name:"Open local status",exact:true}).click();await expect(local.getByRole("listitem")).toHaveCount(0);await expect(local.getByText("Select a record to see it here.",{exact:true})).toBeVisible();await panel.getByRole("button",{name:"Close local status",exact:true}).click();await runtime.reload();await expect(tracker.getByRole("listitem")).toHaveCount(0);await table.getByRole("cell",{name:"ASSET-B",exact:true}).click();await expect(active).toHaveText("Offline");
});
