import {expect,test} from "@playwright/test";
import {readFileSync} from "node:fs";
import {decide,fresh,open,pageUIProfile,stableReadRevision} from "./host";

test("source calendars freeze original business dates and record identity while month, query and overlay changes retire selection",async({page,request},info)=>{
 test.setTimeout(90_000);
 const name=fresh("calendar").replace(/[^a-z0-9]/gi,"").toLowerCase(),type=`build.${name}`,object=fresh("OBJ"),id=fresh("PAGE");
 await decide(request,"manager","build","build.object.create",{type:"build.object",id:object},{name,title:"Original calendar records",fields:[{name:"note",title:"Title",type:"text"},{name:"due",title:"Due date",type:"date"},{name:"raised",title:"Business timestamp",type:"datetime"},{name:"bucket",title:"Bucket",type:"text"},{name:"secret",title:"Private title",type:"text",read:["builder"]},{name:"privatedate",title:"Private date",type:"date",read:["builder"]}]});await decide(request,"manager","build","build.object.publish",{type:"build.object",id:object},{});
 for(const [suffix,due,bucket] of [["A","2026-10-02","A"],["B","2026-10-02","B"],["C","2026-10-03","B"],["D","2026-11-01","B"]])await decide(request,"manager","build",`${type}.create`,{type,id:`${name}${suffix}`},{note:`CAL-${suffix}`,due,bucket,raised:"2026-10-01T23:30:00-02:00",secret:"Private record",privatedate:due});
 const m=JSON.parse(readFileSync(new URL("../../packages/build/src/workshop/module-import/sample.workshop.json",import.meta.url),"utf8")),calendar=(id:string,title:string,set="notes",date="due",active?:string)=>({id,name:title,type:"Calendar",config:{objectSetVarId:set,dateProperty:date,...active?{activeVarId:active}:{}}});
 m.widgets.calendar=calendar("calendar","Work order calendar","notes","due","selected");m.widgets.other=calendar("other","Other calendar");m.widgets.utc=calendar("utc","UTC calendar","notes","raised");m.widgets.hiddenDate=calendar("hiddenDate","Hidden date calendar","notes","privatedate");m.widgets.hiddenTitle=calendar("hiddenTitle","Hidden title calendar");m.widgets.local=calendar("local","Local calendar","localNotes","due","localSelected");m.widgets.localDetail={...m.widgets.detail,id:"localDetail",name:"Local selection",config:{...m.widgets.detail.config,objectVarId:"localSelected"}};
 m.widgets.input={id:"input",name:"Calendar filter",type:"TextInput",config:{variableId:"scratch",label:"Calendar filter"}};m.widgets.trigger={id:"trigger",name:"Open calendar",type:"SingleButton",config:{label:"Open calendar",eventActions:[{kind:"openOverlay",overlayId:"panel"}]}};m.widgets.close={id:"close",name:"Close calendar",type:"SingleButton",config:{label:"Close calendar",eventActions:[{kind:"closeOverlay",overlayId:"panel"}]}};
 m.variables.find((v:any)=>v.id==="scratch").staticValue="";m.variables.find((v:any)=>v.id==="notes").objectSet.steps=[{op:"where",clauses:[{id:"bucket",property:"bucket",op:"contains",varId:"scratch"}]}];m.variables.push({id:"localNotes",name:"Local notes",type:"objectSet",definitionKind:"objectSetDefinition",sourceObjectType:"Asset",objectSet:{objectType:"Asset",steps:[]}},{id:"localSelected",name:"Local selection",type:"object",definitionKind:"widgetOutput",widgetId:"local",widgetOutputKey:"activeObject"});
 m.sections={root:{id:"root",name:"Root",layout:"rows",children:["input","calendar","detail","other","utc","hiddenDate","hiddenTitle","trigger"].map(id=>({kind:"widget",id}))},panel:{id:"panel",name:"Panel",layout:"rows",children:["local","localDetail","close"].map(id=>({kind:"widget",id}))}};m.overlays=[{id:"panel",name:"Calendar panel",kind:"drawer",rootSectionId:"panel"}];
 await decide(request,"manager","build","build.page.create",{type:"build.page",id},{name,title:"Imported calendars",object:type,sections:[{id:"initial",widget:"table",configVersion:1,fields:["note"]}],document:{formatVersion:2,uiProfile:pageUIProfile,root:"root",nodes:{root:{kind:"rows",children:["initial"]},initial:{kind:"widget",section:"initial"}}}});
 await open(page,"manager",`/compose?id=${id}`);await page.getByRole("button",{name:"Import Workshop module",exact:true}).click();const dialog=page.getByRole("dialog",{name:"Import Workshop module",exact:true});await dialog.getByRole("textbox",{name:"Source module JSON",exact:true}).fill(JSON.stringify(m));await dialog.getByRole("combobox",{name:"Map object Asset",exact:true}).selectOption(type);for(const field of ["due","raised","privatedate","bucket"])await dialog.getByRole("combobox",{name:`Map field Asset.${field}`,exact:true}).selectOption(field);await dialog.getByRole("combobox",{name:"Map field Asset.name",exact:true}).selectOption("note");
 for(const title of ["Work order calendar","Other calendar","UTC calendar","Hidden date calendar","Hidden title calendar","Local calendar"]){const group=dialog.getByRole("group",{name:`Map calendar ${title}`,exact:true});await group.getByRole("combobox",{name:"Calendar record title field",exact:true}).selectOption(title==="Hidden title calendar"?"secret":"note");}
 await dialog.getByRole("checkbox").check();await dialog.getByRole("button",{name:"Apply imported page draft",exact:true}).click();const tree=page.getByRole("region",{name:"Widgets and layout",exact:true}),inspector=page.getByRole("region",{name:"The widget in hand",exact:true});await tree.getByRole("button",{name:"Work order calendar",exact:true}).click();await inspector.getByRole("combobox",{name:"Business calendar date field",exact:true}).selectOption("");await expect(page.getByRole("button",{name:"Save",exact:true})).toBeDisabled();await inspector.getByRole("combobox",{name:"Business calendar date field",exact:true}).selectOption("due");await page.getByRole("button",{name:"Save",exact:true}).click();let saved:any;await expect.poll(async()=>{saved=(await(await request.get(`/v1/records/build.page/${id}`,{headers:{Authorization:"Bearer manager"}})).json()).record;return saved.sections?.filter((s:any)=>s.widget==="record-calendar").length;}).toBe(6);
 await page.getByRole("button",{name:"Review release",exact:true}).click();await page.getByRole("button",{name:"Check draft and dependencies",exact:true}).click();await page.getByRole("button",{name:"Save immutable candidate",exact:true}).click();saved.sections.find((s:any)=>s.title==="Work order calendar").recordCalendar={dateField:"due",labelField:"id",initialMonth:"2027-01"};await decide(request,"manager","build","build.page.edit",{type:"build.page",id},{sections:saved.sections});await page.getByRole("button",{name:"Activate release",exact:true}).click();
 const runtime=await page.context().newPage();await stableReadRevision(runtime);await open(runtime,"desk",`/page?app=build&kind=page&name=${name}`);const section=(title:string)=>runtime.getByRole("heading",{name:title,exact:true}).locator(".."),root=section("Work order calendar"),detail=section("Imported selection"),input=runtime.getByRole("textbox",{name:"Calendar filter",exact:true});const day=(scope:any,date:string,count:number)=>scope.getByRole("button",{name:`${date} · ${count} records`,exact:true}),empty=()=>expect(detail.getByText("Select a record to see it here.",{exact:true})).toBeVisible();
 await day(root,"2026-10-02",2).click();await root.getByRole("button",{name:"CAL-A",exact:true}).click();await expect(detail.getByRole("definition").filter({hasText:/^CAL-A$/})).toBeVisible();await day(section("Other calendar"),"2026-10-03",1).click();await section("Other calendar").getByRole("button",{name:"CAL-C",exact:true}).click();await expect(detail.getByRole("definition").filter({hasText:/^CAL-A$/})).toBeVisible();await day(section("UTC calendar"),"2026-10-02",4).click();await expect(section("UTC calendar").getByRole("button",{name:"CAL-D",exact:true})).toBeVisible();for(const title of ["Hidden date calendar","Hidden title calendar"])await expect(runtime.getByRole("heading",{name:title,exact:true})).toHaveCount(0);
 if(process.env.PLATFORM_SCREENSHOTS){await root.scrollIntoViewIfNeeded();await root.screenshot({path:info.outputPath("calendar.png")});await runtime.setViewportSize({width:390,height:844});await root.scrollIntoViewIfNeeded();await root.screenshot({path:info.outputPath("calendar-narrow.png")});await runtime.setViewportSize({width:1280,height:720});}
 await root.getByRole("button",{name:"Next month",exact:true}).click();await empty();await day(root,"2026-11-01",1).click();await root.getByRole("button",{name:"CAL-D",exact:true}).click();await expect(detail.getByRole("definition").filter({hasText:/^CAL-D$/})).toBeVisible();await input.fill("A");await empty();await day(root,"2026-10-02",1).click();await root.getByRole("button",{name:"CAL-A",exact:true}).click();await runtime.route(`**/v1/records/${type}*`,route=>route.fulfill({status:403,contentType:"application/json",body:JSON.stringify({error:{message:"Denied"}})}));await input.fill("B");await expect(root.getByRole("alert")).toBeVisible();await expect(root.getByRole("button",{name:"CAL-A",exact:true})).toHaveCount(0);await empty();await runtime.unroute(`**/v1/records/${type}*`);await input.fill("");await day(root,"2026-10-02",2).click();await day(root,"2026-10-03",1).click();await empty();
 await runtime.getByRole("button",{name:"Open calendar",exact:true}).click();const panel=runtime.getByRole("dialog",{name:"Calendar panel",exact:true});await day(panel,"2026-10-02",2).click();await panel.getByRole("button",{name:"CAL-B",exact:true}).click();await expect(panel.getByRole("definition").filter({hasText:/^CAL-B$/})).toBeVisible();await panel.getByRole("button",{name:"Next month",exact:true}).click();await panel.getByRole("button",{name:"Close calendar",exact:true}).click();await runtime.getByRole("button",{name:"Open calendar",exact:true}).click();await expect(day(panel,"2026-10-02",2)).toBeVisible();await expect(panel.getByRole("button",{name:"CAL-B",exact:true})).toHaveCount(0);await panel.getByRole("button",{name:"Close calendar",exact:true}).click();await runtime.reload();await empty();await expect(day(root,"2026-10-02",2)).toBeVisible();
});
