import {expect,test} from "@playwright/test";
import {decide,fresh,open,pageUIProfile} from "./host";

test("overlay filters isolate original record reads and clear on close without changing a fixed plan",async({page,request},testInfo)=>{
 test.setTimeout(60_000);
 const name=fresh("filters").replace(/[^a-z0-9]/gi,"").toLowerCase(),type=`build.${name}`,object=fresh("OBJ"),id=fresh("PAGE"),query=fresh("QUERY"),queryName=`${name}fixed`;
 await decide(request,"manager","build","build.object.create",{type:"build.object",id:object},{name,title:"Filter notes",fields:[{name:"note",title:"Note",type:"text"},{name:"bucket",title:"Bucket",type:"choice",choices:"A,B"},{name:"active",title:"Active",type:"boolean"}]});await decide(request,"manager","build","build.object.publish",{type:"build.object",id:object},{});
 for(const [suffix,bucket,active] of [["A1","A",true],["A2","A",false],["B","B",false]])await decide(request,"desk","build",`${type}.create`,{type,id:`${name}${suffix}`},{note:`FILTER-${suffix}`,bucket,active});
 await decide(request,"manager","build","build.query.create",{type:"build.query",id:query},{name:queryName,title:"Fixed A notes",description:"Only A",object:type,domain:[["bucket","=","A"]],limit:20});await decide(request,"manager","build","build.query.publish",{type:"build.query",id:query},{});
 await decide(request,"manager","build","build.page.create",{type:"build.page",id},{name,title:"Local filter desk",object:type,sections:[{id:"pageFilter",widget:"filter",configVersion:1,title:"Page filter",fields:["active"]},{id:"pageTable",widget:"table",configVersion:1,title:"Page notes",fields:["note"]},{id:"pageDetail",widget:"detail",configVersion:1,title:"Page selection",fields:["note"]},{id:"fixed",widget:"table",configVersion:1,title:"Fixed plan",fields:["note"],collectionVariable:"fixedWindow"},{id:"trigger",widget:"button",configVersion:1,title:"Open filters"},{id:"localFilter",widget:"filter",configVersion:1,title:"Local filter",fields:["active"]},{id:"localTable",widget:"table",configVersion:1,title:"Local notes",fields:["note"],query:`build.${queryName}`},{id:"localDetail",widget:"detail",configVersion:1,title:"Local selection",fields:["note"]},{id:"notice",widget:"text",configVersion:1,text:"Local filter active"},{id:"close",widget:"button",configVersion:1,title:"Close filters"}],document:{formatVersion:2,uiProfile:pageUIProfile,root:"root",nodes:{root:{kind:"rows",children:["pageFilter","pageTable","pageDetail","fixed","trigger"]},pageFilter:{kind:"widget",section:"pageFilter"},pageTable:{kind:"widget",section:"pageTable"},pageDetail:{kind:"widget",section:"pageDetail"},fixed:{kind:"widget",section:"fixed"},trigger:{kind:"widget",section:"trigger"},picker:{kind:"rows",children:["localFilter","localTable","localDetail","notice","close"]},localFilter:{kind:"widget",section:"localFilter"},localTable:{kind:"widget",section:"localTable"},localDetail:{kind:"widget",section:"localDetail"},notice:{kind:"widget",section:"notice",visibleWhen:"filtered"},close:{kind:"widget",section:"close"}},overlays:{picker:{root:"picker",kind:"drawer",title:"Filter picker",openVariable:"open"}},variables:{open:{scope:"page",type:"boolean",mode:"state",initial:false},localFilters:{title:"Local filters",scope:"overlay",owner:"picker",type:"string",mode:"state",initial:""},filtered:{scope:"overlay",owner:"picker",type:"boolean",mode:"constant",initial:false},fixedWindow:{scope:"page",type:"object-set",mode:"resource",source:{kind:"plan",query:"fixed"}}},queries:{fixed:{object:{app:"build",kind:"object",name:type},limit:10,conditions:[{field:"bucket",op:"=",value:{literal:"B"}}]}},events:[{source:"trigger",event:"click",effects:[{kind:"set", target:"open", value:true}]},{source:"close",event:"click",effects:[{kind:"set", target:"open", value:false}]}]}});
 await open(page,"manager",`/compose?id=${id}`);const tree=page.getByRole("region",{name:"Widgets and layout",exact:true}),inspector=page.getByRole("region",{name:"The widget in hand",exact:true});
 await tree.getByRole("button",{name:"Page variables",exact:true}).click();await inspector.getByRole("combobox",{name:"Choose page variable",exact:true}).selectOption("localFilters");await inspector.getByRole("combobox",{name:"Variable mode",exact:true}).selectOption("resource");await inspector.getByRole("combobox",{name:"Resource output kind",exact:true}).selectOption("filter");await inspector.getByRole("combobox",{name:"Source widget",exact:true}).selectOption("localFilter");
 await inspector.getByRole("combobox",{name:"Choose page variable",exact:true}).selectOption("filtered");await inspector.getByRole("combobox",{name:"Variable mode",exact:true}).selectOption("derived");await inspector.getByRole("combobox",{name:"Operator",exact:true}).selectOption("present");await inspector.getByRole("combobox",{name:"Argument source",exact:true}).selectOption("localFilters");
 await page.getByRole("button",{name:"Save",exact:true}).click();await expect(page.getByRole("button",{name:"Save",exact:true})).toBeDisabled();await page.getByRole("button",{name:"Review release",exact:true}).click();await page.getByRole("button",{name:"Check draft and dependencies",exact:true}).click();await page.getByRole("button",{name:"Save immutable candidate",exact:true}).click();await page.getByRole("button",{name:"Activate release",exact:true}).click();
 const operation=await page.context().newPage();await open(operation,"desk",`/page?app=build&kind=page&name=${name}`);
 const pageFilter=operation.getByRole("search",{name:"Page filter",exact:true}),pageTable=operation.getByRole("heading",{name:"Page notes",exact:true,includeHidden:true}).locator("..").getByRole("table",{includeHidden:true}),fixed=operation.getByRole("heading",{name:"Fixed plan",exact:true,includeHidden:true}).locator("..").getByRole("table",{includeHidden:true}),pageSelection=operation.getByRole("heading",{name:"Page selection",exact:true,includeHidden:true}).locator("..");
 await pageFilter.getByRole("combobox",{name:"Active",exact:true}).selectOption("false");await expect(pageTable.getByText("FILTER-A1",{exact:true})).toHaveCount(0);await expect(pageTable.getByText("FILTER-A2",{exact:true})).toBeVisible();await expect(fixed.getByText("FILTER-B",{exact:true})).toBeVisible();
 await pageTable.getByRole("row").filter({hasText:"FILTER-B"}).click();await expect(pageSelection.getByText("FILTER-B",{exact:true})).toBeVisible();await operation.getByRole("button",{name:"Open filters",exact:true}).click();
 const dialog=operation.getByRole("dialog",{name:"Filter picker",exact:true}),localFilter=dialog.getByRole("search",{name:"Local filter",exact:true}),localTable=dialog.getByRole("table"),localSelection=dialog.getByRole("heading",{name:"Local selection",exact:true}).locator("..");
 await expect(localFilter.getByRole("combobox",{name:"Active",exact:true})).toHaveValue("");await expect(localTable.getByText("FILTER-A1",{exact:true})).toBeVisible();await expect(localTable.getByText("FILTER-B",{exact:true})).toHaveCount(0);
 await localFilter.getByRole("combobox",{name:"Active",exact:true}).selectOption("true");await expect(localTable.getByText("FILTER-A1",{exact:true})).toBeVisible();await expect(localTable.getByText("FILTER-A2",{exact:true})).toHaveCount(0);await expect(dialog.getByText("Local filter active",{exact:true})).toBeVisible();await expect(pageSelection.getByText("FILTER-B",{exact:true})).toBeVisible();await expect(fixed.getByText("FILTER-B",{exact:true})).toBeVisible();
 await localTable.getByRole("row").filter({hasText:"FILTER-A1"}).click();await expect(localSelection.getByText("FILTER-A1",{exact:true})).toBeVisible();
 if(process.env.PLATFORM_SCREENSHOTS)await operation.screenshot({path:testInfo.outputPath("overlay-filter-runtime.png"),fullPage:true});
 let release!:()=>void,held=false;const wait=new Promise<void>(resolve=>release=resolve);await operation.route(`**/v1/records/${type}?*`,async r=>{const domain=new URL(r.request().url()).searchParams.get("domain")??"";if(domain.includes('"A"')&&domain.includes('false')&&!held){const response=await r.fetch();held=true;await wait;await r.fulfill({response});}else await r.continue();});
 await localFilter.getByRole("combobox",{name:"Active",exact:true}).selectOption("false");await expect.poll(()=>held).toBe(true);await dialog.getByRole("button",{name:"Close filters",exact:true}).click();await expect(dialog).not.toBeVisible();await expect(pageFilter.getByRole("combobox",{name:"Active",exact:true})).toHaveValue("false");await operation.getByRole("button",{name:"Open filters",exact:true}).click();await expect(localFilter.getByRole("combobox",{name:"Active",exact:true})).toHaveValue("");release();await expect(localTable.getByText("FILTER-A1",{exact:true})).toBeVisible();await expect(localTable.getByText("FILTER-A2",{exact:true})).toBeVisible();await expect(localSelection.getByText("Select a record to see it here.",{exact:true})).toBeVisible();await expect(dialog.getByText("Local filter active",{exact:true})).toHaveCount(0);await expect(pageSelection.getByText("FILTER-B",{exact:true})).toBeVisible();await operation.unroute(`**/v1/records/${type}?*`);
 if(process.env.PLATFORM_SCREENSHOTS){await operation.setViewportSize({width:390,height:844});await operation.evaluate(()=>new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve()))));await operation.screenshot({path:testInfo.outputPath("overlay-filter-runtime-narrow.png"),fullPage:true});}
 await operation.reload();await expect(operation.getByRole("dialog",{name:"Filter picker",exact:true})).not.toBeVisible();await expect(pageFilter.getByRole("combobox",{name:"Active",exact:true})).toHaveValue("");
});
