import {expect,test} from '@playwright/test';
import {decide,fresh,open,pageUIProfile,stableReadRevision} from './host';

test('shared board card breadcrumb and graph freeze one application selection and keep graph outputs local',async({page,request})=>{
 test.setTimeout(120_000);page.setDefaultTimeout(10_000);
 const name=fresh('maintenance').replace(/[^a-z0-9]/gi,'').toLowerCase(),type=`build.${name}`,child=`build.${name}work`,first=fresh('PAGE'),second=fresh('PAGE'),app=fresh('APP'),ref={app:'build',kind:'object',name:type},work={app:'build',kind:'object',name:child},application=`build:${name}app`;
 for(const [n,fields,states,actions] of [[name,[{name:'name',title:'Name',type:'text'},{name:'private',title:'Private note',type:'text',read:['builder']}],[{name:'open',title:'Open'},{name:'done',title:'Done'}],[{name:'close',title:'Complete asset',from:['open'],to:'done'}]],[`${name}work`,[{name:'name',title:'Name',type:'text'},{name:'asset',title:'Asset',type:'reference',ref:type}],[],[]]] as const){const id=fresh('OBJ');await decide(request,'manager','build','build.object.create',{type:'build.object',id},{name:n,title:n,fields,states,actions});await decide(request,'manager','build','build.object.publish',{type:'build.object',id},{});}
 for(const suffix of ['A','B']){await decide(request,'manager','build',`${type}.create`,{type,id:`${name}${suffix}`},{name:`ASSET-${suffix}`,private:'PRIVATE-CARD'});await decide(request,'manager','build',`${child}.create`,{type:child,id:`${name}work${suffix}`},{name:`WORK-${suffix}`,asset:`${name}${suffix}`});}
 const link=fresh('LINK'),linkName=`${name}worklink`;await decide(request,'manager','build','build.linktype.create',{type:'build.linktype',id:link},{name:linkName,title:'Asset work',description:'Original asset work',parent:type,child,via:'asset',forward:'work',reverse:'asset'});await decide(request,'manager','build','build.linktype.publish',{type:'build.linktype',id:link},{});
 const definitions=(await(await request.get('/v1/definitions',{headers:{Authorization:'Bearer manager'}})).json());const linkDef=definitions.find((d:any)=>d.ref.kind==='link-type'&&d.ref.name===linkName);expect(linkDef).toBeTruthy();
 const variable={title:'Shared asset',scope:'application',type:'record',mode:'shared',writable:true,source:{kind:'application',variable:'selected',object:ref}};
 const graph={objects:[{object:ref,labelField:'name'},{object:work,labelField:'name'}],relations:[{id:'work',binding:{ref:linkDef.ref,sourceVersion:linkDef.version}}],outputs:[{id:'asset',object:ref,variable:'graphAsset'},{id:'work',object:work,variable:'graphWork'}]};
 const sections=(board:boolean)=>board?[{id:'board',widget:'kanban',configVersion:1,title:'Asset board',collectionVariable:'assets',selectionVariable:'selected',cardLabel:'name',fields:['state'],actions:[`${type}.close`]},{id:'card',widget:'record-card',configVersion:1,title:'Current asset',recordVariable:'selected',recordCard:{labelField:'name',tone:'neutral'},fields:['state','private']},{id:'trail',widget:'breadcrumb',configVersion:1,title:'Shared trail',recordVariable:'selected',breadcrumb:{homeLabel:'Choices',pageLabel:'Maintenance',labelField:'name'}},{id:'graph',widget:'graph-explorer',configVersion:1,title:'Asset graph',recordVariable:'selected',graphExplorer:graph},{id:'workCard',widget:'record-card',configVersion:1,title:'Graph work',object:child,recordVariable:'graphWork',recordCard:{labelField:'name',tone:'info'}}]:[{id:'table',widget:'table',configVersion:1,title:'Remote choices',fields:['name'],selectionVariable:'selected'},{id:'next',widget:'button',configVersion:1,title:'Open maintenance'}];
 const document=(board:boolean)=>{const ids=board?['board','card','trail','graph','workCard']:['table','next'];return {formatVersion:2,uiProfile:pageUIProfile,root:'root',nodes:{root:{kind:'rows',children:ids},...Object.fromEntries(ids.map(id=>[id,{kind:'widget',section:id}]))},variables:{selected:variable,...(board?{assets:{scope:'page',type:'object-set',mode:'resource',source:{kind:'plan',query:'assets'}},graphAsset:{scope:'page',type:'record',mode:'resource',source:{kind:'record',section:'graph',port:'asset'}},graphWork:{scope:'page',type:'record',mode:'resource',source:{kind:'record',section:'graph',port:'work'}}}:{})},...(board?{queries:{assets:{object:ref,limit:100,sort:['id']}}}:{}),events:[board?{source:'trail',event:'click',control:'home',effects:[{kind:'navigate',navigate:{page:{app:'build',kind:'page',name:`${name}choices`},interfaceVersion:0}}]}:{source:'next',event:'click',effects:[{kind:'navigate',navigate:{page:{app:'build',kind:'page',name:`${name}board`},interfaceVersion:0}}]}]};};
 // Publish the navigation target before the board, then install its return event.
 await decide(request,'manager','build','build.page.create',{type:'build.page',id:second},{name:`${name}choices`,title:'Asset choices',object:type,sections:[{id:'initial',widget:'text',configVersion:1,text:'Initial'}],document:{formatVersion:2,uiProfile:pageUIProfile,root:'root',nodes:{root:{kind:'rows',children:['initial']},initial:{kind:'widget',section:'initial'}}}});await decide(request,'manager','build','build.page.publish',{type:'build.page',id:second},{});
 await decide(request,'manager','build','build.page.create',{type:'build.page',id:first},{name:`${name}board`,title:'Shared maintenance',object:type,sections:sections(true),document:document(true)});await decide(request,'manager','build','build.page.publish',{type:'build.page',id:first},{});
 await decide(request,'manager','build','build.page.edit',{type:'build.page',id:second},{sections:sections(false),document:document(false)});await decide(request,'manager','build','build.page.publish',{type:'build.page',id:second},{});
 await open(page,'manager',`/compose?id=${first}`);const tree=page.getByRole('region',{name:'Widgets and layout',exact:true}),inspector=page.getByRole('region',{name:'The widget in hand',exact:true});
 for(const title of ['Current asset','Shared trail','Asset graph']){await tree.getByRole('button',{name:title,exact:true}).click();await expect(inspector.getByRole('combobox',{name:'Input record binding',exact:true})).toHaveValue('selected');}
 await tree.getByRole('button',{name:'Asset board',exact:true}).click();await expect(inspector.getByRole('combobox',{name:'Shared record selection',exact:true})).toHaveValue('selected');await expect(page.getByRole('button',{name:'Save',exact:true})).toBeDisabled();
 await decide(request,'manager','build','build.app.create',{type:'build.app',id:app},{name:`${name}app`,title:'Maintenance application',pages:[`${name}board`,`${name}choices`],uiProfile:pageUIProfile,variables:{selected:{scope:'application',type:'record',mode:'resource',source:{kind:'record',object:ref}}}});await decide(request,'manager','build','build.app.publish',{type:'build.app',id:app},{});
 await open(page,'manager',`/application?id=${app}`);await page.getByRole('button',{name:'Review application release',exact:true}).click();await page.getByRole('button',{name:'Check draft and dependencies',exact:true}).click();await page.getByRole('button',{name:'Save immutable candidate',exact:true}).click();await decide(request,'manager','build','build.page.edit',{type:'build.page',id:first},{title:'Later draft title'});await page.getByRole('button',{name:'Activate release',exact:true}).click();
 const runtime=await page.context().newPage();await stableReadRevision(runtime);const route=`/page?app=build&kind=page&name=${name}board&application=${application}&instance=main`;await open(runtime,'desk',route);
 const section=(title:string)=>runtime.getByRole('heading',{name:title,exact:true,level:3}).locator('..'),card=section('Current asset'),explorer=section('Asset graph'),output=section('Graph work'),trail=runtime.getByRole('navigation',{name:'Shared trail',exact:true});
 await section('Asset board').getByRole('button',{name:'ASSET-A',exact:true}).click();await expect(card).toContainText('ASSET-A');await expect(card).not.toContainText('PRIVATE-CARD');await expect(trail).toContainText('ASSET-A');await expect(explorer).toContainText('WORK-A');
 await explorer.getByRole('button',{name:`Select output ${child}/${name}workA`,exact:true}).click();await expect(output).toContainText('WORK-A');
 await section('Asset board').getByRole('button',{name:'ASSET-B',exact:true}).click();await expect(card).toContainText('ASSET-B');await expect(explorer).toContainText('WORK-B');await expect(output).toContainText('No confirmed record for this card.');await expect(explorer).not.toContainText('WORK-A');
 let release!:()=>void,held=false;const gate=new Promise<void>(resolve=>release=resolve);await runtime.route(`**/v1/records/${child}/query`,async r=>{if(!held){const response=await r.fetch();held=true;await gate;await r.fulfill({response});}else await r.continue();});
 await section('Asset board').getByRole('button',{name:'ASSET-A',exact:true}).click();await expect.poll(()=>held).toBe(true);await section('Asset board').getByRole('button',{name:'ASSET-B',exact:true}).click();await expect(explorer).toContainText('WORK-B');release();await runtime.unroute(`**/v1/records/${child}/query`);await runtime.evaluate(()=>new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve()))));await expect(explorer).not.toContainText('WORK-A');
 await trail.getByRole('button',{name:'Choices',exact:true}).click();await runtime.getByRole('row').filter({hasText:'ASSET-A'}).click();await runtime.getByRole('button',{name:'Open maintenance',exact:true}).click();await expect(card).toContainText('ASSET-A');await expect(explorer).toContainText('WORK-A');
 await trail.getByRole('button',{name:'Maintenance',exact:true}).click();await expect(card).toContainText('No confirmed record for this card.');await expect(explorer).toContainText('Select an original record');
 await runtime.route(`**/v1/records/${type}/${name}A`,r=>r.fulfill({status:403,contentType:'application/json',body:JSON.stringify({error:{message:'Denied'}})}));await section('Asset board').getByRole('button',{name:'ASSET-A',exact:true}).click();await expect(card).not.toContainText('ASSET-A');await expect(explorer).not.toContainText('WORK-A');await expect(runtime.getByRole('alert').filter({hasText:'Resource read failed'})).toBeVisible();await runtime.unroute(`**/v1/records/${type}/${name}A`);
 await section('Asset board').getByRole('button',{name:'ASSET-B',exact:true}).click();await expect(card).toContainText('ASSET-B');await runtime.getByRole('button',{name:'New application instance',exact:true}).click();await expect(card).toContainText('No confirmed record for this card.');await expect(explorer).not.toContainText('WORK-B');
});
