import {expect,test} from "@playwright/test";
import {readFileSync} from "node:fs";
import {decide,fresh,open,pageUIProfile} from "./host";

test("default source facets preserve empty and multi-value filtering, complete counts, revision cleanup and frozen original actions",async({page,request},info)=>{
 test.setTimeout(90_000);
 const m=JSON.parse(readFileSync(new URL("../../packages/build/src/module-import/filters.workshop.json",import.meta.url),"utf8")),name=fresh("facets").replace(/[^a-z0-9]/gi,"").toLowerCase(),type=`build.${name}`,object=fresh("OBJ"),id=fresh("PAGE");
 await decide(request,"manager","build","build.object.create",{type:"build.object",id:object},{name,title:"Source assets",fields:[{name:"name",title:"Asset name",type:"text",search:true},{name:"status",title:"Status",type:"choice",choices:"Active,Warning,Offline"},{name:"priority",title:"Priority",type:"choice",choices:"High,Low"},{name:"owner",title:"Owner",type:"text"},{name:"pressure",title:"Pressure",type:"decimal"}],states:[{name:"open",title:"Open"},{name:"done",title:"Done"}],actions:[{name:"close",title:"Finish asset",from:["open"],to:"done",inputs:[{name:"reason",title:"Reason",type:"text",required:true}]}]});await decide(request,"manager","build","build.object.publish",{type:"build.object",id:object},{});
 for(const [suffix,status,priority,owner,pressure] of [["A","Active","High","Ops",12],["B","Warning","High","Ops",20],["C","Offline","Low","Other",5]])await decide(request,"desk","build",`${type}.create`,{type,id:`${name}${suffix}`},{name:`ASSET-${suffix}`,status,priority,owner,pressure});
 await decide(request,"manager","build","build.page.create",{type:"build.page",id},{name,title:"Facet import",object:type,sections:[{id:"help",widget:"text",configVersion:1,text:"Original page"}],document:{formatVersion:2,uiProfile:pageUIProfile,root:"root",nodes:{root:{kind:"rows",children:["help"]},help:{kind:"widget",section:"help"}}}});
 await open(page,"manager",`/compose?id=${id}`);await page.getByRole("button",{name:"Import Workshop module",exact:true}).click();const dialog=page.getByRole("dialog",{name:"Import Workshop module",exact:true});await dialog.getByRole("textbox",{name:"Source module JSON",exact:true}).fill(JSON.stringify(m));await expect(dialog.getByRole("region",{name:"Migration diagnostics",exact:true})).toContainText("edit-binding");await expect(dialog.getByRole("button",{name:"Apply imported page draft",exact:true})).toBeDisabled();
 // Explicit source repairs, never a hidden fallback in the importer.
 const fields=["id","name","status","priority","owner","pressure"];
 m.widgets.wObjectTable1.config={objectSetVarId:"filteredAssets",activeVarId:"selectedAsset",columns:fields.map(key=>({key})),enableInlineEdit:false,selectionMode:"single"};m.widgets.wObjectTable1.events=[];m.widgets.wPropList1.config={objectVarId:"selectedAsset",properties:fields,hideNull:false};
 for(const [key,variableId,label] of [["minimum","pressureMin","Minimum pressure"],["maximum","pressureMax","Maximum pressure"]]){m.widgets[key]={id:key,type:"NumericInput",name:label,config:{variableId,label}};m.sections.root.children.push({kind:"widget",id:key});}
 await dialog.getByRole("textbox",{name:"Source module JSON",exact:true}).fill(JSON.stringify(m));await dialog.getByRole("combobox",{name:"Map object Asset",exact:true}).selectOption(type);for(const field of fields)await dialog.getByRole("combobox",{name:`Map field Asset.${field}`,exact:true}).selectOption(field);await dialog.getByRole("combobox",{name:"Map action updateAssetStatus",exact:true}).selectOption(`${type}.close`);await dialog.getByRole("checkbox").check();await dialog.getByRole("button",{name:"Apply imported page draft",exact:true}).click();
 await page.getByRole("button",{name:"Save",exact:true}).click();let saved:any;await expect.poll(async()=>{saved=(await(await request.get(`/v1/records/build.page/${id}`,{headers:{Authorization:"Bearer manager"}})).json()).record;return saved.sections?.length;}).toBe(6);
 // A one-record source window still gives complete facet counts.
 const filter=saved.sections.find((s:any)=>s.widget==="filter"),query=saved.document.variables[filter.collectionVariable].source.query;saved.document.queries[query].limit=1;await decide(request,"manager","build","build.page.edit",{type:"build.page",id},{document:saved.document});await page.reload();
 await page.getByRole("button",{name:"Review release",exact:true}).click();await page.getByRole("button",{name:"Check draft and dependencies",exact:true}).click();await page.getByRole("button",{name:"Save immutable candidate",exact:true}).click();saved.sections.find((s:any)=>s.widget==="inline-action").actions=[`${type}.edit`];await decide(request,"manager","build","build.page.edit",{type:"build.page",id},{sections:saved.sections});await page.getByRole("button",{name:"Activate release",exact:true}).click();
 const runtime=await page.context().newPage();await open(runtime,"desk",`/page?app=build&kind=page&name=${name}`);const facets=runtime.getByRole("search",{name:"Asset Filters",exact:true}),table=runtime.getByRole("heading",{name:"Assets",exact:true}).locator(".."),detail=runtime.getByRole("heading",{name:m.widgets.wPropList1.name,exact:true}).locator(".."),form=runtime.getByRole("heading",{name:m.widgets.wInlineAction.name,exact:true}).locator("..");
 await expect(table.getByRole("row").filter({hasText:"ASSET-C"})).toBeVisible();await expect(facets.getByRole("group",{name:"Priority",exact:true})).toContainText("2");await table.getByRole("row").filter({hasText:"ASSET-C"}).click();await expect(detail.getByRole("heading",{name:"ASSET-C",exact:true})).toBeVisible();
 await facets.getByRole("checkbox",{name:"Active",exact:true}).check();await expect(table.getByText("ASSET-C",{exact:true})).toHaveCount(0);await expect(detail).toContainText("Select a record to see it here.");await expect(table.getByText("ASSET-A",{exact:true})).toBeVisible();await facets.getByRole("checkbox",{name:"Warning",exact:true}).check();await expect(table.getByText("ASSET-B",{exact:true})).toBeVisible();await facets.getByRole("checkbox",{name:"Active",exact:true}).uncheck();await facets.getByRole("checkbox",{name:"Warning",exact:true}).uncheck();await expect(table.getByText("ASSET-C",{exact:true})).toBeVisible();
 await facets.getByRole("textbox",{name:"Owner",exact:true}).fill("op");await expect(table.getByText("ASSET-C",{exact:true})).toHaveCount(0);await expect(table.getByText("ASSET-B",{exact:true})).toBeVisible();await runtime.getByRole("textbox",{name:"Minimum pressure",exact:true}).fill("13");await expect(table.getByText("ASSET-A",{exact:true})).toHaveCount(0);await runtime.getByRole("textbox",{name:"Minimum pressure",exact:true}).fill("invalid");await expect(table.getByText("ASSET-B",{exact:true})).toHaveCount(0);await runtime.getByRole("textbox",{name:"Minimum pressure",exact:true}).fill("");await expect(table.getByText("ASSET-A",{exact:true})).toBeVisible();
 await facets.getByRole("textbox",{name:"Search",exact:true}).fill("ASSET-B");await expect(table.getByText("ASSET-A",{exact:true})).toHaveCount(0);await table.getByRole("row").filter({hasText:"ASSET-B"}).click();await form.getByRole("textbox",{name:"Reason *",exact:true}).fill("From imported filters");
 if(process.env.PLATFORM_SCREENSHOTS){await facets.screenshot({path:info.outputPath("module-facets.png")});await runtime.setViewportSize({width:390,height:844});await runtime.evaluate(()=>new Promise<void>(r=>requestAnimationFrame(()=>requestAnimationFrame(()=>r()))));await facets.screenshot({path:info.outputPath("module-facets-narrow.png")});}
 await form.getByRole("button",{name:"Finish asset",exact:true}).click();await expect.poll(async()=>(await(await request.get(`/v1/records/${type}/${name}B`,{headers:{Authorization:"Bearer desk"}})).json()).record.state).toBe("done");await runtime.reload();await expect(facets.getByRole("checkbox",{name:"Active",exact:true})).not.toBeChecked();await expect(facets.getByRole("textbox",{name:"Owner",exact:true})).toHaveValue("");await expect(table.getByText("ASSET-C",{exact:true})).toBeVisible();
});
