import {expect,test} from "@playwright/test";
import {decide,fresh,open,pageUIProfile} from "./host";

test("a layout subtree copies owned bindings atomically and freezes independent real record work",async({page,request},testInfo)=>{
 test.setTimeout(90_000);
 const name=fresh("layoutcopy").replace(/[^a-z0-9]/gi,"").toLowerCase(),type=`build.${name}`,object=fresh("OBJ"),id=fresh("PAGE");
 await decide(request,"manager","build","build.object.create",{type:"build.object",id:object},{name,title:"Copy work",fields:[{name:"title",title:"Title",type:"text"},{name:"bucket",title:"Bucket",type:"text"}],states:[{name:"open",title:"Open"},{name:"done",title:"Done"}],actions:[{name:"finish",title:"Finish copied work",from:["open"],to:"done",inputs:[{name:"reason",title:"Completion reason",type:"text",required:true}]}]});await decide(request,"manager","build","build.object.publish",{type:"build.object",id:object},{});
 for(const [suffix,bucket] of [["A1","A"],["A2","A"],["B1","B"]])await decide(request,"desk","build",`${type}.create`,{type,id:`${name}${suffix}`},{title:`WORK-${suffix}`,bucket});
 await decide(request,"manager","build","build.page.create",{type:"build.page",id},{name,title:"Copied work desk",object:type,sections:[{id:"bucket",widget:"input",configVersion:1,title:"Work bucket"},{id:"shared",widget:"input",configVersion:1,title:"Shared scratch"},{id:"table",widget:"table",configVersion:1,title:"Work choices",fields:["title","state"],collectionVariable:"window"},{id:"detail",widget:"detail",configVersion:1,title:"Selected work",fields:["title","state"],recordVariable:"selected"},{id:"action",widget:"inline-action",configVersion:1,title:"Finish in place",actions:[`${type}.finish`]},{id:"reset",widget:"button",configVersion:1,title:"Reset work bucket"},{id:"dormant",widget:"text",configVersion:1,title:"Saved note",text:"Keep this dormant content"}],document:{formatVersion:2,uiProfile:pageUIProfile,root:"root",nodes:{root:{kind:"rows",title:"Page root",children:["group"]},group:{kind:"columns",title:"Work block",gap:20,children:["controls","records"]},controls:{kind:"rows",children:["bucket","shared","reset"]},records:{kind:"rows",children:["table","detail","action"]},bucket:{kind:"widget",section:"bucket",valueVariable:"term"},shared:{kind:"widget",section:"shared",valueVariable:"external"},table:{kind:"widget",section:"table"},detail:{kind:"widget",section:"detail"},action:{kind:"widget",section:"action"},reset:{kind:"widget",section:"reset"},dormant:{kind:"widget",section:"dormant"}},unusedWidgets:[{node:"dormant",parent:"records"}],variables:{term:{scope:"page",type:"string",mode:"state",initial:"A"},external:{scope:"page",type:"string",mode:"state",initial:"shared"},window:{scope:"page",type:"object-set",mode:"resource",source:{kind:"plan",query:"read"}},selected:{scope:"page",type:"record",mode:"resource",source:{kind:"record",section:"table"}}},queries:{read:{object:{app:"build",kind:"object",name:type},limit:10,conditions:[{field:"bucket",op:"=",value:{variable:"term"}}]}},interface:{version:1,outputs:{scratch:{variable:"external",type:"string"}}},events:[{source:"reset",event:"click",effects:[{kind:"set", target:"term", value:"A"}]}]}});
 await open(page,"manager",`/compose?id=${id}`);const tree=page.getByRole("region",{name:"Widgets and layout",exact:true}),inspector=page.getByRole("region",{name:"The widget in hand",exact:true}),save=page.getByRole("button",{name:"Save",exact:true}),unused=tree.getByRole("region",{name:"Unused widgets",exact:true});
 await tree.getByRole("button",{name:"Commands for Work block",exact:true}).click();await page.getByRole("menuitem",{name:"Select layout",exact:true}).click();await tree.getByRole("button",{name:"Commands for Work block",exact:true}).click();await page.getByRole("menuitem",{name:"Copy layout",exact:true}).click();await expect(save).toBeDisabled();
 await inspector.getByRole("textbox",{name:"Container title",exact:true}).fill("Original block");await tree.getByRole("button",{name:"Commands for Page root",exact:true}).click();await page.getByRole("menuitem",{name:"Paste layout",exact:true}).click();await expect(inspector.getByRole("textbox",{name:"Container title",exact:true})).toHaveValue("Work block");await inspector.getByRole("textbox",{name:"Container title",exact:true}).fill("Copied block");await expect(unused.getByRole("button",{name:"Saved note",exact:true})).toHaveCount(2);
 await page.getByRole("button",{name:"Undo",exact:true}).click();await page.getByRole("button",{name:"Undo",exact:true}).click();await expect(unused.getByRole("button",{name:"Saved note",exact:true})).toHaveCount(1);await page.getByRole("button",{name:"Redo",exact:true}).click();await page.getByRole("button",{name:"Redo",exact:true}).click();await expect(unused.getByRole("button",{name:"Saved note",exact:true})).toHaveCount(2);
 await tree.getByRole("button",{name:"Commands for Copied block",exact:true}).click();await page.getByRole("menuitem",{name:"Select layout",exact:true}).click();const canvas=page.getByRole("region",{name:"The page",exact:true});await expect(canvas.getByRole("button",{name:"Layout commands",exact:true})).toBeVisible();await canvas.getByRole("button",{name:"Layout commands",exact:true}).click();await page.getByRole("menuitem",{name:"Duplicate layout",exact:true}).click();await expect(unused.getByRole("button",{name:"Saved note",exact:true})).toHaveCount(3);await page.getByRole("button",{name:"Undo",exact:true}).click();await expect(unused.getByRole("button",{name:"Saved note",exact:true})).toHaveCount(2);
 await tree.getByRole("button",{name:"Commands for Page root",exact:true}).click();await page.getByRole("menuitem",{name:"Select layout",exact:true}).click();await tree.getByRole("button",{name:"Commands for Page root",exact:true}).focus();await page.keyboard.press("Meta+v");await expect(unused.getByRole("button",{name:"Saved note",exact:true})).toHaveCount(3);await page.getByRole("button",{name:"Undo",exact:true}).click();
 if(process.env.PLATFORM_SCREENSHOTS){await tree.getByRole("button",{name:"Commands for Copied block",exact:true}).click();await page.screenshot({path:testInfo.outputPath("layout-copy-editor.png"),fullPage:true});await page.keyboard.press("Escape");}
 await save.click();await expect(save).toBeDisabled();const saved=(await(await request.get(`/v1/records/build.page/${id}`,{headers:{Authorization:"Bearer manager"}})).json()).record;
 const copiedTable=saved.sections.find((s:any)=>s.widget==="table"&&s.id!=="table"),copiedBucket=saved.sections.find((s:any)=>s.widget==="input"&&s.title==="Work bucket"&&s.id!=="bucket"),copiedNode=Object.values(saved.document.nodes).find((n:any)=>n.section===copiedBucket.id) as any,copiedQuery=saved.document.variables[copiedTable.collectionVariable].source.query;
 expect(saved.document.nodes.group.title).toBe("Original block");expect(saved.document.queries[copiedQuery].conditions[0].value.variable).toBe(copiedNode.valueVariable);expect(copiedTable.selection).toBeTruthy();expect(saved.document.unusedWidgets).toHaveLength(2);expect(saved.sections.find((s:any)=>s.widget==="inline-action"&&s.id!=="action").selection).toBe(copiedTable.selection);
 await page.getByRole("button",{name:"Review release",exact:true}).click();await page.getByRole("button",{name:"Check draft and dependencies",exact:true}).click();await page.getByRole("button",{name:"Save immutable candidate",exact:true}).click();saved.document.queries[copiedQuery].conditions=[{field:"bucket",op:"=",value:{literal:"missing"}}];await decide(request,"manager","build","build.page.edit",{type:"build.page",id},{document:saved.document});await page.getByRole("button",{name:"Activate release",exact:true}).click();
 const operation=await page.context().newPage();await open(operation,"desk",`/page?app=build&kind=page&name=${name}`);
 const buckets=operation.getByRole("textbox",{name:"Work bucket",exact:true}),shared=operation.getByRole("textbox",{name:"Shared scratch",exact:true}),tables=operation.getByRole("heading",{name:"Work choices",exact:true}),originalTable=tables.nth(0).locator(".."),copyTable=tables.nth(1).locator(".."),details=operation.getByRole("heading",{name:"Selected work",exact:true}),actions=operation.getByRole("heading",{name:"Finish in place",exact:true}),originalAction=actions.nth(0).locator(".."),copyAction=actions.nth(1).locator("..");
 await expect(originalTable.getByRole("row").filter({hasText:"WORK-A1"})).toBeVisible();await expect(copyTable.getByRole("row").filter({hasText:"WORK-A1"})).toBeVisible();await buckets.nth(1).fill("B");await expect(copyTable.getByRole("row").filter({hasText:"WORK-B1"})).toBeVisible();await expect(buckets.nth(0)).toHaveValue("A");await expect(originalTable.getByRole("row").filter({hasText:"WORK-A1"})).toBeVisible();await shared.nth(0).fill("Shared across copies");await expect(shared.nth(1)).toHaveValue("Shared across copies");
 await originalTable.getByRole("row").filter({hasText:"WORK-A1"}).click();await expect(details.nth(0).locator("..").getByText("WORK-A1",{exact:true})).toBeVisible();await expect(details.nth(1).locator("..")).toContainText("Select a record to see it here.");await originalAction.getByRole("textbox",{name:"Completion reason *",exact:true}).fill("Original draft");await copyTable.getByRole("row").filter({hasText:"WORK-B1"}).click();await expect(copyAction.getByRole("textbox",{name:"Completion reason *",exact:true})).toHaveValue("");await copyAction.getByRole("textbox",{name:"Completion reason *",exact:true}).fill("Copied work completed");await copyAction.getByRole("button",{name:"Finish copied work",exact:true}).click();await expect(details.nth(1).locator("..").getByText("Done",{exact:true})).toBeVisible();await expect(originalAction.getByRole("textbox",{name:"Completion reason *",exact:true})).toHaveValue("Original draft");
 await operation.getByRole("button",{name:"Reset work bucket",exact:true}).nth(1).click();await expect(buckets.nth(1)).toHaveValue("A");await expect(buckets.nth(0)).toHaveValue("A");await expect(copyAction).toContainText("Select a record to act on it.");await expect(originalAction.getByRole("textbox",{name:"Completion reason *",exact:true})).toHaveValue("Original draft");await expect(operation.getByText("Keep this dormant content",{exact:true})).toHaveCount(0);
 if(process.env.PLATFORM_SCREENSHOTS){await originalAction.screenshot({path:testInfo.outputPath("layout-copy-runtime.png")});await operation.setViewportSize({width:390,height:844});await operation.evaluate(()=>new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve()))));await originalAction.scrollIntoViewIfNeeded();await originalAction.screenshot({path:testInfo.outputPath("layout-copy-runtime-narrow.png")});}
 await operation.reload();await expect(buckets.nth(0)).toHaveValue("A");await expect(buckets.nth(1)).toHaveValue("A");await expect(shared.nth(0)).toHaveValue("shared");await expect(originalAction).toContainText("Select a record to act on it.");
 await open(page,"manager",`/compose?id=${id}`);await page.reload();await tree.getByRole("button",{name:"Commands for Page root",exact:true}).click();await page.getByRole("menuitem",{name:"Select layout",exact:true}).click();await expect(page.getByRole("button",{name:"Paste layout",exact:true})).toBeDisabled();await page.getByRole("button",{name:"Copy layout",exact:true}).click();await expect(page.getByRole("button",{name:"Paste layout",exact:true})).toBeEnabled();await page.getByRole("button",{name:/manager-1 hotel-a/}).click();await page.getByRole("menuitemradio",{name:/desk-1/}).click();await expect(page.getByRole("button",{name:/desk-1 hotel-a/})).toBeVisible();await page.getByRole("button",{name:/desk-1 hotel-a/}).click();await page.getByRole("menuitemradio",{name:/manager-1/}).click();await expect(page.getByRole("button",{name:/manager-1 hotel-a/})).toBeVisible();await page.evaluate(route=>location.hash=route,`/compose?id=${id}`);await tree.getByRole("button",{name:"Commands for Page root",exact:true}).click();await page.getByRole("menuitem",{name:"Select layout",exact:true}).click();await expect(page.getByRole("button",{name:"Paste layout",exact:true})).toBeDisabled();
});
