import {expect,test} from "@playwright/test";
import {decide,fresh,open,pageUIProfile} from "./host";

test("an authored count controls interaction from the complete frozen set and drops refused and obsolete results",async({page,request},info)=>{
 test.setTimeout(60_000);
 const name=fresh("count").replace(/[^a-z0-9]/gi,"").toLowerCase(),type=`build.${name}`,object=fresh("OBJ"),id=fresh("PAGE"),ref={app:"build",kind:"object",name:type};
 await decide(request,"manager","build","build.object.create",{type:"build.object",id:object},{name,title:"Count notes",fields:[{name:"note",title:"Note",type:"text"},{name:"bucket",title:"Bucket",type:"text"}]});await decide(request,"manager","build","build.object.publish",{type:"build.object",id:object},{});for(const suffix of ["A1","A2","A3","B1","B2","C1"])await decide(request,"desk","build",`${type}.create`,{type,id:`${name}${suffix}`},{note:`COUNT-${suffix}`,bucket:suffix[0]});
 const document={formatVersion:2,uiProfile:pageUIProfile,root:"root",nodes:{root:{kind:"rows",children:["input","table","button","notice"]},input:{kind:"widget",section:"input",valueVariable:"bucket"},table:{kind:"widget",section:"table"},button:{kind:"widget",section:"button",enabledWhen:"canRun"},notice:{kind:"widget",section:"notice",visibleWhen:"canRun"}},variables:{bucket:{scope:"page",type:"string",mode:"state",initial:"B"},count:{title:"Matching count",scope:"page",type:"decimal",mode:"state",initial:{kind:"decimal",value:"0"}},canRun:{scope:"page",type:"boolean",mode:"derived",expression:{op:"decimal-less",args:[{literal:{kind:"decimal",value:"3"}},{variable:"count"}]}},shown:{scope:"page",type:"boolean",mode:"state",initial:false},window:{scope:"page",type:"object-set",mode:"resource",source:{kind:"plan",query:"combined"}}},queries:{left:{object:ref,limit:1,conditions:[{field:"bucket",op:"=",value:{literal:"A"}}]},right:{object:ref,limit:1,conditions:[{field:"bucket",op:"=",value:{variable:"bucket"}}]},combined:{title:"Complete matches",object:ref,limit:1,sort:["id"],set:{op:"union",inputs:["left","right"]}}},events:[{source:"button",event:"click",target:"shown",value:true}]};
 await decide(request,"manager","build","build.page.create",{type:"build.page",id},{name,title:"Count operation desk",object:type,sections:[{id:"input",widget:"input",configVersion:1,title:"Count bucket"},{id:"table",widget:"table",configVersion:1,title:"One record window",fields:["note"],collectionVariable:"window"},{id:"button",widget:"button",configVersion:1,title:"Continue with matches"},{id:"notice",widget:"text",configVersion:1,text:"Enough permitted matches"}],document});
 await open(page,"manager",`/compose?id=${id}`);const tree=page.getByRole("region",{name:"Widgets and layout",exact:true}),inspector=page.getByRole("region",{name:"The widget in hand",exact:true});await tree.getByRole("button",{name:"Page variables",exact:true}).click();await inspector.getByRole("combobox",{name:"Choose page variable",exact:true}).selectOption("count");await inspector.getByRole("combobox",{name:"Variable mode",exact:true}).selectOption("aggregate");await inspector.getByRole("combobox",{name:"Count query source",exact:true}).selectOption("combined");await expect(inspector.getByRole("region",{name:"Current variable value",exact:true}).getByText("5",{exact:true})).toBeVisible();await page.getByRole("button",{name:"Save",exact:true}).click();await expect(page.getByRole("button",{name:"Save",exact:true})).toBeDisabled();await page.getByRole("button",{name:"Review release",exact:true}).click();await page.getByRole("button",{name:"Check draft and dependencies",exact:true}).click();await page.getByRole("button",{name:"Save immutable candidate",exact:true}).click();const draft=await(await request.get(`/v1/records/build.page/${id}`,{headers:{Authorization:"Bearer manager"}})).json();draft.record.document.queries.combined.set.op="intersect";await decide(request,"manager","build","build.page.edit",{type:"build.page",id},{document:draft.record.document});await page.getByRole("button",{name:"Activate release",exact:true}).click();
 const operation=await page.context().newPage();let reads=0;operation.on("request",r=>{if(r.url().endsWith(`/v1/aggregates/${type}/query`)){reads++;expect(r.postDataJSON().set.op).toBe("union");expect(r.postDataJSON().limit).toBeUndefined();}});await open(operation,"desk",`/page?app=build&kind=page&name=${name}`);const input=operation.getByRole("textbox",{name:"Count bucket",exact:true}),button=operation.getByRole("button",{name:"Continue with matches",exact:true}),notice=operation.getByText("Enough permitted matches",{exact:true});await expect(button).toBeEnabled();await expect(notice).toBeVisible();await expect(operation.getByText("1–1 of 5",{exact:true})).toBeVisible();const before=reads;await operation.getByRole("button",{name:"Next page",exact:true}).click();await expect(operation.getByText("2–2 of 5",{exact:true})).toBeVisible();expect(reads).toBe(before);
 let release!:()=>void,held=false,released=false;const pending:Promise<void>[]=[];const wait=new Promise<void>(resolve=>release=resolve);await operation.route(`**/v1/aggregates/${type}/query`,async route=>{if(route.request().postDataJSON().set.inputs[1].domain[0][2]==="C"&&!released){let done!:()=>void;pending.push(new Promise<void>(r=>done=r));try{const response=await route.fetch();held=true;await wait;await route.fulfill({response});}finally{done();}}else await route.continue();});await input.fill("C");await expect.poll(()=>held).toBe(true);await expect(button).toBeDisabled();await expect(notice).toHaveCount(0);await input.fill("D");await expect(operation.getByText("1–1 of 3",{exact:true})).toBeVisible();released=true;release();await Promise.all(pending);await expect(button).toBeDisabled();await expect(notice).toHaveCount(0);await operation.unroute(`**/v1/aggregates/${type}/query`);
 await operation.route(`**/v1/aggregates/${type}/query`,route=>route.fulfill({status:403,contentType:"application/json",body:JSON.stringify({error:{message:"Denied"}})}));await input.fill("B");await expect(operation.getByRole("alert").filter({hasText:"Resource read failed"})).toBeVisible();await expect(button).toBeDisabled();await expect(notice).toHaveCount(0);await operation.unroute(`**/v1/aggregates/${type}/query`);await operation.getByRole("button",{name:"Retry query",exact:true}).click();await expect(button).toBeEnabled();await expect(notice).toBeVisible();
 if(process.env.PLATFORM_SCREENSHOTS){await operation.screenshot({path:info.outputPath("count.png"),fullPage:true});await operation.setViewportSize({width:390,height:844});await operation.evaluate(()=>new Promise<void>(r=>requestAnimationFrame(()=>requestAnimationFrame(()=>r()))));await operation.screenshot({path:info.outputPath("count-narrow.png"),fullPage:true});}await operation.reload();await expect(button).toBeEnabled();await expect(notice).toBeVisible();
});

test("an application count shares its scoped read across pages and retires with the application instance",async({page,request})=>{
 test.setTimeout(60_000);
 const name=fresh("appcount").replace(/[^a-z0-9]/gi,"").toLowerCase(),type=`build.${name}`,object=fresh("OBJ"),app=fresh("APP"),ids=[fresh("PAGE"),fresh("PAGE")],ref={app:"build",kind:"object",name:type},application=`build:${name}app`;
 await decide(request,"manager","build","build.object.create",{type:"build.object",id:object},{name,title:"Application count notes",fields:[{name:"bucket",title:"Bucket",type:"text"}]});await decide(request,"manager","build","build.object.publish",{type:"build.object",id:object},{});for(const suffix of ["A1","B1","B2"])await decide(request,"desk","build",`${type}.create`,{type,id:`${name}${suffix}`},{bucket:suffix[0]});
 const document=(target:string)=>({formatVersion:2,uiProfile:pageUIProfile,root:"root",nodes:{root:{kind:"rows",children:["input","notice","next"]},input:{kind:"widget",section:"input",valueVariable:"bucket"},notice:{kind:"widget",section:"notice",visibleWhen:"enough"},next:{kind:"widget",section:"next"}},variables:{bucket:{scope:"application",type:"string",mode:"shared",writable:true,source:{kind:"application",variable:"bucket"}},count:{scope:"application",type:"decimal",mode:"shared",source:{kind:"application",variable:"count"}},enough:{scope:"page",type:"boolean",mode:"derived",expression:{op:"decimal-less",args:[{literal:{kind:"decimal",value:"1"}},{variable:"count"}]}}},events:[{source:"next",event:"click",target:"",navigate:{page:{app:"build",kind:"page",name:target},interfaceVersion:0}}]});
 for(const [at,id] of ids.entries()){await decide(request,"manager","build","build.page.create",{type:"build.page",id},{name:`${name}${at}`,title:`Count page ${at}`,object:type,sections:[{id:"input",widget:"input",configVersion:1,title:"Shared count bucket"},{id:"notice",widget:"text",configVersion:1,text:"Shared count allows work"},{id:"next",widget:"button",configVersion:1,title:"Next count page"}],document:document(`${name}${at}`)});await decide(request,"manager","build","build.page.publish",{type:"build.page",id},{});}
 await decide(request,"manager","build","build.app.create",{type:"build.app",id:app},{name:`${name}app`,title:"Count application",pages:[`${name}0`,`${name}1`],uiProfile:pageUIProfile,queries:{read:{object:ref,limit:1,conditions:[{field:"bucket",op:"=",value:{variable:"bucket"}}]}},variables:{bucket:{scope:"application",type:"string",mode:"state",initial:"B"},count:{scope:"application",type:"decimal",mode:"state",initial:{kind:"decimal",value:"0"}}}});
 await open(page,"manager",`/application?id=${app}`);await page.getByRole("combobox",{name:"Choose application variable",exact:true}).selectOption("count");await page.getByRole("combobox",{name:"Variable mode",exact:true}).selectOption("aggregate");await page.getByRole("combobox",{name:"Count query source",exact:true}).selectOption("read");await page.getByRole("button",{name:"Save application",exact:true}).click();await expect(page.getByRole("button",{name:"Save application",exact:true})).toBeDisabled();await decide(request,"manager","build","build.app.publish",{type:"build.app",id:app},{});
 for(const [at,id] of ids.entries()){await decide(request,"manager","build","build.page.edit",{type:"build.page",id},{document:document(`${name}${1-at}`)});await decide(request,"manager","build","build.page.publish",{type:"build.page",id},{});}
 await open(page,"manager",`/application?id=${app}`);await page.getByRole("button",{name:"Review application release",exact:true}).click();await page.getByRole("button",{name:"Check draft and dependencies",exact:true}).click();await page.getByRole("button",{name:"Save immutable candidate",exact:true}).click();await page.getByRole("button",{name:"Activate release",exact:true}).click();
 const operation=await page.context().newPage(),route=`/page?app=build&kind=page&name=${name}0&application=${application}&instance=main`;let reads=0;operation.on("request",r=>{if(new URL(r.url()).pathname===`/v1/aggregates/${type}`)reads++;});await open(operation,"desk",route);const input=operation.getByRole("textbox",{name:"Shared count bucket",exact:true}),notice=operation.getByRole("paragraph").filter({hasText:"Shared count allows work"});await expect(notice).toBeVisible();expect(reads).toBe(1);await operation.getByRole("button",{name:"Next count page",exact:true}).click();await expect(operation.getByRole("heading",{name:"Count page 1",exact:true})).toBeVisible();await expect(notice).toBeVisible();expect(reads).toBe(1);await input.fill("A");await expect(notice).toHaveCount(0);await operation.getByRole("button",{name:"Next count page",exact:true}).click();await expect(input).toHaveValue("A");await expect(notice).toHaveCount(0);expect(reads).toBe(2);
 await operation.getByRole("button",{name:"New application instance",exact:true}).click();await expect(input).toHaveValue("B");await expect(notice).toBeVisible();await operation.evaluate(route=>{location.hash=route},route);await expect(input).toHaveValue("A");await expect(notice).toHaveCount(0);await operation.getByRole("button",{name:"Close application instance",exact:true}).click();await operation.evaluate(route=>{location.hash=route},route);await expect(input).toHaveValue("B");await expect(notice).toBeVisible();await operation.reload();await expect(notice).toBeVisible();
});
