import {expect,test} from "@playwright/test";
import {open} from "./host";

test("three spatial views show actual map geometry, raster bytes and GLB parts through shared catalog entries",async({page},info)=>{
 test.setTimeout(90_000);page.setDefaultTimeout(10_000);
 await page.addInitScript(()=>{const state={calls:0,context:undefined as WebGL2RenderingContext|undefined};(window as any).__spatialGPU=state;for(const key of ["drawArrays","drawElements"] as const){const original=WebGL2RenderingContext.prototype[key];(WebGL2RenderingContext.prototype as any)[key]=function(...args:any[]){state.calls++;state.context=this;return (original as any).apply(this,args);};}});
 await open(page,"manager","/catalog-example?id=ui/record-map");const map=page.getByRole("group",{name:"Record map",exact:true});await expect(map).toBeVisible();await expect.poll(()=>map.locator("path").count()).toBe(2);const beta=map.getByRole("button",{name:"Example Beta · EXAMPLE-B",exact:true});await beta.click();await expect(beta).toHaveAttribute("aria-pressed","true");await page.getByRole("button",{name:"Zoom in",exact:true}).click();await page.getByRole("button",{name:"Fit records",exact:true}).click();if(process.env.PLATFORM_SCREENSHOTS)await page.screenshot({path:info.outputPath("record-map.png")});
 await open(page,"manager","/catalog-example?id=ui/image-annotation");const image=page.getByRole("group",{name:"Annotated image",exact:true});await expect(image).toBeVisible();await expect(image.locator("image")).toHaveAttribute("href",/^blob:/);await page.getByRole("button",{name:"Example region",exact:true}).click();await expect(page.getByRole("textbox",{name:"Region label",exact:true})).toHaveValue("Example region");await expect(page.getByRole("textbox",{name:"Region label",exact:true})).toBeDisabled();if(process.env.PLATFORM_SCREENSHOTS)await page.screenshot({path:info.outputPath("image-annotation.png")});
 await open(page,"manager","/catalog-example?id=ui/scene-3d");await expect(page.getByRole("status").filter({hasText:"1 model meshes · 1 rendered triangles"})).toBeVisible();const part=page.getByRole("button",{name:"FixturePart",exact:true});await part.click();await expect(page.getByText(/^Selected model part:.*FixturePart/)).toBeVisible();await page.getByRole("button",{name:"Model layers",exact:true}).click();const layer=page.getByRole("button",{name:"Example layer",exact:true});await layer.click();await expect(layer).toHaveAttribute("aria-pressed","false");await layer.click();await page.getByRole("button",{name:"Field mappings",exact:true}).click();await expect(page.getByText(/FixturePart.*pressure.*12/)).toBeVisible();await page.getByRole("button",{name:"Fit model",exact:true}).click();await page.getByRole("button",{name:"Isolate part",exact:true}).click();if(process.env.PLATFORM_SCREENSHOTS){await page.screenshot({path:info.outputPath("scene-3d.png")});await page.setViewportSize({width:390,height:844});await page.screenshot({path:info.outputPath("scene-3d-narrow.png")});}
 await open(page,"manager","/catalog-example?id=ui/record-map");await expect(page.getByRole("group",{name:"Record map",exact:true})).toBeVisible();await expect(page.locator("canvas")).not.toBeVisible();await expect.poll(async()=>{const before=await page.evaluate(()=>(window as any).__spatialGPU.calls);await page.waitForTimeout(150);return before===await page.evaluate(()=>(window as any).__spatialGPU.calls);}).toBe(true);const paused=await page.evaluate(()=>(window as any).__spatialGPU.calls);await page.getByRole("tab",{name:"3D scene · Live example",exact:true}).click();await expect.poll(()=>page.evaluate(()=>(window as any).__spatialGPU.calls)).toBeGreaterThan(paused);await page.getByRole("tab",{name:"3D scene · Live example",exact:true}).getByRole("button",{name:"Close tab",exact:true}).click();await expect(page.locator("canvas")).toHaveCount(0);await expect.poll(()=>page.evaluate(()=>(window as any).__spatialGPU.context?.isContextLost())).toBe(true);
});
