import {expect,test} from "@playwright/test";
import {decide,fresh,open} from "./host";

test("original window statistics use actual business time beyond record-page limits and the public reader keeps controlled parameters",async({page,request},info)=>{
 test.setTimeout(90_000);page.setDefaultTimeout(10_000);const name=fresh("windows").replace(/[^a-z0-9]/gi,"").toLowerCase(),type=`build.${name}`,object=fresh("OBJ"),headers={Authorization:"Bearer manager"};
 await decide(request,"manager","build","build.object.create",{type:"build.object",id:object},{name,title:"Window observations",fields:[{name:"name",title:"Name",type:"text",search:true},{name:"at",title:"Event time",type:"datetime"},{name:"value",title:"Signal",type:"decimal"}]});await decide(request,"manager","build","build.object.publish",{type:"build.object",id:object},{});
 for(let i=0;i<530;i++)await decide(request,"manager","build",`${type}.create`,{type,id:`${name}${String(i).padStart(4,"0")}`},{name:"Original observation",at:new Date(Date.UTC(2026,9,3,0,0,i)).toISOString(),value:i});
 const pageData=await(await request.get(`/v1/records/${type}?limit=1000`,{headers})).json();expect(pageData.records).toHaveLength(500);expect(pageData.total).toBe(530);
 const read=async(rows:number)=>(await(await request.post(`/v1/aggregates/${type}/query`,{headers,data:{window:{timeField:"at",field:"value",rows,threshold:"499"},search:"Original"}})).json()).window;
 const complete=await read(1000),recent=await read(25);expect(complete).toMatchObject({requestedRows:1000,total:530,timed:530,count:530,valid:530,above:30,min:0,mean:264.5,max:529});expect(recent).toMatchObject({requestedRows:25,total:530,count:25,valid:25,above:25,min:505,mean:517,max:529});expect(recent.first.id).toBe(`${name}0529`);expect(recent.last.id).toBe(`${name}0505`);
 const invalid=await request.post(`/v1/aggregates/${type}/query`,{headers,data:{window:{timeField:"at",field:"value",rows:100001,threshold:"0"}}});expect(invalid.status()).toBe(400);
 await open(page,"manager","/catalog-example?id=app/observation-statistics-reader");await expect(page.getByText("The window reader example uses a fixed local answer and performs no tenant query.",{exact:true}).filter({visible:true})).toBeVisible();await expect(page.getByText("3 observations · 3 numeric values in the original 1,000-row window",{exact:true})).toBeVisible();const threshold=page.getByRole("textbox",{name:"Alarm above",exact:true});await threshold.fill("2");await expect(page.getByText("Above 2",{exact:true})).toBeVisible();await page.getByRole("combobox",{name:"Observation window rows",exact:true}).selectOption("100000");await expect(page.getByText("3 observations · 3 numeric values in the original 100,000-row window",{exact:true})).toBeVisible();await threshold.fill("0x10");await expect(page.getByRole("alert").filter({hasText:"invalid draft"})).toBeVisible();await threshold.fill("3");await expect(page.getByText("Above 3",{exact:true})).toBeVisible();
 if(process.env.PLATFORM_SCREENSHOTS){await page.screenshot({path:info.outputPath("window-reader.png")});await page.setViewportSize({width:390,height:844});await page.evaluate(()=>new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve()))));await expect(page.getByRole("textbox",{name:"Alarm above",exact:true})).toBeVisible();await expect(page.getByText("3 observations · 3 numeric values in the original 100,000-row window",{exact:true}).filter({visible:true})).toBeVisible();await page.screenshot({path:info.outputPath("window-reader-narrow.png")});}
});
