package enterprise

import (
	"strconv"
	"strings"

	"platformserver/apps/enterprise/uaf"
	"platformserver/platform"
)

// The typed SDK over this app's declarations (ADR-0094 D4): the same pipeline
// that generates the host's TypeScript (cmd/api-types) emits this file into
// web/packages/kernel/src/gen/enterprise-sdk.ts, and TestAPIContract fails
// while it is stale. Nothing here is written by hand — Profile(), Views() and
// declarations() are the sources, so the types cannot drift from the contract.

// SDK is the generated enterprise-sdk.ts source.
func SDK() string {
	var b strings.Builder
	b.WriteString("// Generated by capabilities/server/cmd/api-types from the enterprise app's own declarations (ADR-0094). Do not edit:\n")
	b.WriteString("// change the Go declarations (profile, views, actions), then run `go run ./cmd/api-types` in capabilities/server.\n")
	b.WriteString("import type { EnterpriseQueryResult } from \"./host\";\n\n")

	b.WriteString("// EnterpriseStereotype is every stereotype the Enterprise Core Profile offers the palette (ADR-0067 D1).\n")
	b.WriteString("export type EnterpriseStereotype =\n")
	for _, p := range Profile() {
		b.WriteString("\t| " + strconv.Quote(p.Stereotype) + "\n")
	}
	b.WriteString(";\n\n")

	b.WriteString("// EnterpriseViewpoint is the five description views the model projects onto itself (ADR-0093).\n")
	b.WriteString("export type EnterpriseViewpoint =\n")
	for _, v := range Views(uaf.Current()) {
		b.WriteString("\t| " + strconv.Quote(v.ID) + "\n")
	}
	b.WriteString(";\n\n")

	actions := declarations()
	b.WriteString("// enterpriseWrites is the write contract: every schema that may change the model (ADR-0094 D3).\n")
	b.WriteString("export const enterpriseWrites = [\n")
	for _, a := range actions {
		b.WriteString("\t" + strconv.Quote(a.Schema) + ",\n")
	}
	b.WriteString("] as const;\n\n")
	b.WriteString("export type EnterpriseWrite = (typeof enterpriseWrites)[number];\n\n")

	b.WriteString("// Payloads of the write contract: required fields are required, the rest optional.\n")
	for _, a := range actions {
		name := payloadType(a.Schema)
		b.WriteString("export type " + name + " = {\n")
		for _, f := range a.Payload {
			if f.Description != "" {
				b.WriteString("\t// " + singleLine(f.Description) + "\n")
			}
			key := f.Name
			if !f.Required {
				key += "?"
			}
			b.WriteString("\t" + key + ": " + payloadFieldType(a, f) + ";\n")
		}
		b.WriteString("};\n\n")
	}
	b.WriteString("// EnterpriseWritePayloads maps each write to its payload type.\nexport type EnterpriseWritePayloads = {\n")
	for _, a := range actions {
		b.WriteString("\t" + strconv.Quote(a.Schema) + ": " + payloadType(a.Schema) + ";\n")
	}
	b.WriteString("};\n\n")

	b.WriteString("export type EnterpriseTarget = { type: string; id: string };\n\n")
	b.WriteString("// EnterpriseDecide is any host's decide(), structurally: schema, target, payload.\n")
	b.WriteString("export type EnterpriseDecide = (schema: string, target: EnterpriseTarget, payload: Record<string, unknown>) => Promise<unknown>;\n\n")
	b.WriteString("// enterpriseWrite applies the write contract typed: the schema picks the payload.\n")
	b.WriteString("export function enterpriseWrite<K extends EnterpriseWrite>(\n\tdecide: EnterpriseDecide,\n\tschema: K,\n\ttarget: EnterpriseTarget,\n\tpayload: EnterpriseWritePayloads[K],\n): Promise<unknown> {\n\treturn decide(schema, target, payload);\n}\n\n")

	b.WriteString("export type EnterpriseGet = <T>(path: string) => Promise<T>;\n\n")
	b.WriteString("export type EnterpriseQueryFilters = {\n")
	b.WriteString("\tstereotype?: EnterpriseStereotype | EnterpriseStereotype[];\n")
	b.WriteString("\tkind?: string;\n")
	b.WriteString("\tq?: string;\n")
	b.WriteString("\t// alive is a YYYY-MM-DD day, or \"all\" for closed and future elements too; default today.\n")
	b.WriteString("\talive?: string;\n")
	b.WriteString("\tlimit?: number;\n};\n\n")
	b.WriteString("// queryElements reads the model through the query contract (ADR-0094 D1): a typed,\n// filtered projection, never the whole graph.\n")
	b.WriteString("export async function queryElements(get: EnterpriseGet, filters: EnterpriseQueryFilters = {}): Promise<EnterpriseQueryResult> {\n")
	b.WriteString("\tconst params = new URLSearchParams();\n")
	b.WriteString("\tconst stereotypes = filters.stereotype === undefined ? [] : Array.isArray(filters.stereotype) ? filters.stereotype : [filters.stereotype];\n")
	b.WriteString("\tif (stereotypes.length > 0) params.set(\"stereotype\", stereotypes.join(\",\"));\n")
	b.WriteString("\tif (filters.kind) params.set(\"kind\", filters.kind);\n")
	b.WriteString("\tif (filters.q) params.set(\"q\", filters.q);\n")
	b.WriteString("\tif (filters.alive) params.set(\"alive\", filters.alive);\n")
	b.WriteString("\tif (filters.limit) params.set(\"limit\", String(filters.limit));\n")
	b.WriteString("\tconst query = params.toString();\n")
	b.WriteString("\treturn get<EnterpriseQueryResult>(query === \"\" ? \"/v1/enterprise-query\" : \"/v1/enterprise-query?\" + query);\n}\n\n")
	b.WriteString("// resolveElements names stored ids through the ref contract (ADR-0094 D2): closed\n// elements resolve too, marked; unknown ids are skipped.\n")
	b.WriteString("export async function resolveElements(get: EnterpriseGet, ids: readonly string[]): Promise<EnterpriseQueryResult> {\n")
	b.WriteString("\tif (ids.length === 0) return { elements: [] };\n")
	b.WriteString("\treturn get<EnterpriseQueryResult>(\"/v1/enterprise-resolve?ids=\" + encodeURIComponent(ids.join(\",\")));\n}\n")
	return b.String()
}

// payloadType is the Go side name of one write's payload type.
func payloadType(schema string) string {
	var b strings.Builder
	b.WriteString("Enterprise")
	for _, part := range strings.Split(strings.TrimPrefix(schema, "enterprise."), ".") {
		b.WriteString(strings.ToUpper(part[:1]) + part[1:])
	}
	return b.String() + "Payload"
}

// payloadFieldType is one payload field's TypeScript type. The two fields the
// metamodel itself enumerates take their unions; everything else is a scalar
// or an id (references are ids — the SDK does not re-check them, the kernel does).
func payloadFieldType(a platform.Action, f platform.Field) string {
	switch {
	case a.Schema == SchemaElementAdd && f.Name == "stereotype" && f.Type == "string":
		return "EnterpriseStereotype"
	case f.Name == "viewpoint" && f.Type == "string":
		return "EnterpriseViewpoint"
	case f.Type == "integer", f.Type == "number":
		return "number"
	case f.Type == "boolean":
		return "boolean"
	case f.Type == "json":
		return "unknown"
	default:
		return "string"
	}
}

// singleLine keeps a declaration description on one comment line.
func singleLine(s string) string { return strings.ReplaceAll(s, "\n", " ") }
