import type {ChartSource,EntityInfo,EntityRecord,RecordSource,RecordList} from '@platform/ui';
import type {Definition,Host} from '../index';
import type {PageSessionStore} from '../runtime/Session';
import type {usePageQueries} from '../runtime/PageQueries';
import type {VariableResult} from '../runtime/variables';
import type {ScalarValue} from '../runtime/decimal';
import type {QueryWindow} from './QueryWindowFrame';
type Page=NonNullable<Definition['page']>;
type Section=NonNullable<Page['sections']>[number];
type Narrowed=Record<string,Record<string,unknown>>;
/** Owner-side binding context. Renderers receive only the ports selected by adapters. */
export type WidgetBindingContext = {builder?:ReturnType<typeof usePageQueries>["builders"][string];sceneWindow?:QueryWindow;embeddingInputs?:Record<string,VariableResult>;embeddingReturn?:(values:Record<string,unknown>)=>void;observationHistory?:QueryWindow;observationContext?:QueryWindow;observationAsset?:EntityRecord;observationSelected?:string;onObservationRow?:(record:EntityRecord)=>Promise<void>;notepadValue?:VariableResult;onNotepad?:(value:string)=>void;explorationRoot?:EntityRecord;explorationStatus?:"empty"|"pending"|"value"|"error";explorationIdentity?:string;explorationActive?:()=>boolean;onGraphOutput?:(object:string,record:EntityRecord)=>Promise<boolean>;graphSelected?:{object:string;id:string};contextReadCurrent?:boolean;avatarContextStatus?:"empty"|"pending"|"value"|"error";onClearContext?:()=>void;collaborationRecord?:EntityRecord;collaborationReference?:import("../runtime/Session").RecordReference;collaborationStatus?:"empty"|"pending"|"value"|"error";collaborationSlot?:string;commentDraft?:VariableResult;fileValue?:VariableResult;pdfPageValue?:VariableResult;onCommentDraft?:(value:string)=>void;onFileID?:(value:string)=>void;onPdfPage?:(value:string)=>void;comparisonRecords?:EntityRecord[];comparisonStatus?:"empty"|"pending"|"value"|"error";confirmedRecord?:EntityRecord;recordStatus?:"empty"|"pending"|"value"|"error";sparklineValue?:VariableResult;groupValue?:VariableResult;onGroupFilter?:(value?:string)=>void;onHeatmap?:(row?:string,column?:string)=>void;pickerConfirmation?:"empty"|"pending"|"value"|"error";pickerValue?:VariableResult;onPickerID?:(record?:EntityRecord)=>void;alertValue?:VariableResult;dateValue?:VariableResult;onDate?:(value:string)=>void;choiceSetValue?:VariableResult;onChoiceSet?:(value:string[])=>void;choiceValue?:VariableResult;onChoice?:(value:string)=>void;booleanInput?:VariableResult;onBoolean?:(checked:boolean)=>void;rangeLower?:VariableResult;rangeUpper?:VariableResult;onRange?:(lower:string,upper:string)=>void;statisticsValue?:VariableResult;gaugeValue?:VariableResult;progressValue?:VariableResult;progressTotal?:VariableResult;countValue?:string;countError?:string;
  info?:EntityInfo;sourceScope?:string;aggregateSource?:ChartSource;recordSource?:RecordSource;definitions?:readonly Definition[];catalog?:Host['catalog'];decide?:Host['decide'];
  actionReady?:boolean;onRecordOpen?:(type:string,record:EntityRecord)=>void;onControl?:(id:string)=>void;controlBound?:(id:string)=>boolean;
  page: Page; section: Section; selected?: EntityRecord; onSelect: (record?: EntityRecord) => void; live: boolean;
  master?: EntityRecord;
  session?: PageSessionStore;
  window?: NonNullable<Parameters<typeof RecordList>[0]["window"]>;
 collection?:VariableResult; aggregateScope?:string;
  selectionSet?:import("@platform/ui").RecordSelectionPort;
  keepActive?:boolean;
  facetValues?:Record<string,VariableResult>;onFacet?:(id:string,value:ScalarValue)=>void;
  inputScopes?:string[];onClick?: () => void; numeric?:boolean; valueError?:string; value?: string; onValue?: (value: string) => void; enabled?: boolean; readSource?: RecordSource;
  sharedFilter?:Record<string,unknown>; narrowed: Narrowed; onNarrow: (object: string, field: string, value: unknown) => void;
};
