import {registerHooks} from 'node:module';
import {readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
import test from 'node:test';
const manifest=JSON.parse(readFileSync(new URL('../../../../../capabilities/server/platform/pageui/widgets.json',import.meta.url)));
registerHooks({resolve(s,c,next){if(s==='@platform/kernel')return {url:'data:text/javascript,'+encodeURIComponent(`export const pageUIManifest=${JSON.stringify(manifest)}`),shortCircuit:true};if(s==='@platform/ui')return {url:'data:text/javascript,export const t=s=>s;',shortCircuit:true};try{return next(s,c)}catch(e){if(s.startsWith('./')||s.startsWith('../'))return next(s+'.ts',c);throw e;}}});
const {defineWidgetPlugin}=await import('./plugin.ts');
const {createWidgetDefinitions,createWidgetRegistry,widgetContracts}=await import('./registry.ts');
const {inputPlugins}=await import('./input-plugins.ts');
const {contentPlugins}=await import('./content-plugins.ts');
const {scalarPlugins}=await import('./scalar-plugins.ts');
const {recordWindowPlugins}=await import('./record-window-plugins.ts');
const {distributionPlugins}=await import('./distribution-plugins.ts');
const {navigationPlugins}=await import('./navigation-plugins.ts');
const {recordPresentationPlugins}=await import('./record-presentation-plugins.ts');
const {surfacePlugins}=await import('./surface-plugins.ts');

test('runtime and authoring reject missing, undeclared or incompatible registrations and keep definitions immutable',()=>{
 const definitions=Object.fromEntries(widgetContracts.map(c=>[c.componentID,{configVersion:1,owner:'original'}]));
 const registry=createWidgetDefinitions(definitions);assert.equal(registry.resolve('input',1).owner,'original');assert.equal(registry.resolve('input',2),undefined);assert.equal(registry.resolve('unknown',1),undefined);assert.ok(Object.isFrozen(registry.entries));assert.ok(Object.isFrozen(registry.resolve('input',1)));
 const missing={...definitions};delete missing.text;assert.throws(()=>createWidgetDefinitions(missing),/Missing widget implementation/);assert.throws(()=>createWidgetDefinitions({...definitions,custom:{configVersion:1}}),/Undeclared widget implementation/);assert.throws(()=>createWidgetDefinitions({...definitions,text:{configVersion:2}}),/Unsupported widget configuration/);
 const renderer=()=>null,implementations=Object.fromEntries(widgetContracts.map(c=>[c.componentID,renderer]));assert.throws(()=>createWidgetRegistry({...implementations,text:inputPlugins.input}),/Mismatched widget plugin/);assert.throws(()=>createWidgetRegistry({...implementations,text:undefined}),/Missing widget implementation/);
 const plugins={...inputPlugins,...contentPlugins,...scalarPlugins,...recordWindowPlugins,...distributionPlugins,...navigationPlugins,...recordPresentationPlugins,...surfacePlugins},current=createWidgetRegistry({...implementations,...plugins});assert.equal(Object.keys(plugins).length,40);for(const [id,plugin]of Object.entries(plugins)){assert.equal(current.resolve(id,1),plugin.Renderer);assert.equal(current.resolve(id,2),undefined);}
});
test('record presentations preserve independent confirmations, original picker IDs and authorized services',()=>{
 const record={id:'A',revision:7},other={id:'B',revision:8},callback=()=>{},picker=()=>{},window={query:{limit:20,sort:['id']}},source={scope:'original-member'},info={type:'original.asset',fields:[]},value={status:'value',value:'A'},collection={status:'error',code:'refused'};
 const context={page:{object:{name:'original.asset'}},section:{fields:['name'],recordCard:{labelField:'name'},recordComparison:{labelField:'name'},avatar:{labelField:'name'},resourceList:{labelField:'name'},recordPicker:{labelField:'name'},pickerValueVariable:'picker'},window,info,recordSource:source,confirmedRecord:record,recordStatus:'pending',comparisonRecords:[record,other],comparisonStatus:'error',selected:record,onSelect:callback,pickerValue:value,onPickerID:picker,pickerConfirmation:'pending',collection,avatarContextStatus:'error',contextReadCurrent:false,enabled:false};
 for(const key of ['session','readSource','catalog'])Object.defineProperty(context,key,{get:()=>{throw Error(`forbidden ${key}`);}});
 for(const plugin of Object.values(recordPresentationPlugins)){const props=plugin.Renderer(context).props;for(const forbidden of ['page','section','session','readSource','catalog'])assert.equal(Object.hasOwn(props,forbidden),false);}
 assert.equal(recordPresentationPlugins['record-card'].bind(context).status,'pending');assert.equal(recordPresentationPlugins['record-comparison'].bind(context).status,'error');assert.equal(recordPresentationPlugins['record-comparison'].bind(context).records,context.comparisonRecords);assert.equal(recordPresentationPlugins['avatar-stack'].bind(context).contextStatus,'error');assert.equal(recordPresentationPlugins['resource-list'].bind(context).readCurrent,false);assert.equal(recordPresentationPlugins['resource-list'].bind(context).collection,collection);
 const bound=recordPresentationPlugins['record-picker'].bind(context);assert.equal(bound.source,source);assert.equal(bound.value,value);assert.equal(bound.confirmation,'pending');assert.equal(bound.onSelect,picker);const local=recordPresentationPlugins['record-picker'].bind({...context,onPickerID:undefined,section:{...context.section,pickerValueVariable:undefined}});assert.equal(local.value,undefined);assert.equal(local.confirmation,undefined);assert.equal(local.onSelect,callback);
});
test('surface plugins retain exact embedding versions and expose only offered navigation and original map context',()=>{
 const calls=[],control=id=>calls.push(id),allowed=id=>id==='page',returns=()=>{},values={input:{status:'value',value:'old'}},definitions=[{ref:{kind:'page',name:'original'}}],embedding={page:{ref:{app:'build',kind:'page',name:'child'},sourceVersion:'original'},contentVersion:'page.sha256.original',interfaceVersion:3,inputs:{input:{variable:'input'}}},frame={origin:'https://example.test'};
 const context={section:{title:'Original',map:{latitudeField:'latitude',longitudeField:'longitude'},assetDirectory:{items:[{id:'page',asset:{ref:{kind:'page'}}},{id:'object',asset:{ref:{kind:'object'}}}]},embedding,externalFrame:frame},definitions,sourceScope:'original-member',onControl:control,controlBound:allowed,enabled:false,pickerConfirmation:'pending',window:{query:{limit:100}},onSelect:returns,onClick:returns,embeddingInputs:values,facetValues:{unused:{status:'value',value:'do not replace inputs'}},embeddingReturn:returns,aggregateScope:'original-app/overlay',contextReadCurrent:false,live:false};
 for(const key of ['page','session','readSource'])Object.defineProperty(context,key,{get:()=>{throw Error(`forbidden ${key}`);}});
 for(const plugin of Object.values(surfacePlugins)){const props=plugin.Renderer(context).props;for(const forbidden of ['page','section','session','readSource'])assert.equal(Object.hasOwn(props,forbidden),false);}
 const directory=surfacePlugins['asset-directory'].bind(context);assert.equal(directory.definitions,definitions);directory.onOpen('object');directory.onOpen('page');assert.deepEqual(calls,['page']);assert.equal(surfacePlugins['asset-directory'].bind({...context,controlBound:()=>false}).onOpen,undefined);
 const child=surfacePlugins['embedded-page'].bind(context);assert.equal(child.config,embedding);assert.equal(child.values,values);assert.equal(child.scope,'original-app/overlay');assert.equal(child.onReturn,returns);assert.equal(child.readCurrent,false);assert.equal(child.live,false);assert.equal(surfacePlugins['external-frame'].bind(context).config,frame);assert.equal(surfacePlugins['record-map'].bind(context).scope,'original-member');assert.equal(surfacePlugins['record-map'].bind(context).confirmation,'pending');assert.equal(surfacePlugins.button.bind(context).onClick,returns);
});
test('distribution plugins forward the original full-set reader and selection values without reading records during binding',()=>{
 let calls=0;const source={aggregate:async()=>{calls++;},scope:'original-app/overlay-epoch',revision:8},window={query:{domain:[['state','=','warning']],limit:100,offset:100}},info={type:'original.asset',fields:[]},callback=()=>{};
 const context={page:{object:{name:'original.asset'}},section:{title:'Original distribution',group:'state',histogram:{field:'pressure',bins:14},analysis:{kind:'mean'},analysisXVariable:'x',analysisYVariable:'y',analysisCountVariable:'count',analysisMeanVariable:'mean'},window,info,aggregateSource:source,groupValue:{status:'value',value:{kind:'string-set',values:['active','warning']}},enabled:false,onGroupFilter:callback,onFacet:callback,facetValues:{x:{status:'value',value:'pressure'}}};
 for(const key of ['session','readSource','catalog'])Object.defineProperty(context,key,{get:()=>{throw Error(`forbidden ${key}`);}});
 for(const plugin of Object.values(distributionPlugins)){const props=plugin.Renderer(context).props;assert.equal(props.source,source);assert.equal(props.window,window);assert.equal(props.info,info);assert.equal(props.object,'original.asset');for(const forbidden of ['page','section','session','readSource','catalog'])assert.equal(Object.hasOwn(props,forbidden),false);}
 assert.equal(calls,0);assert.deepEqual(distributionPlugins.treemap.bind(context).selected,['active','warning']);assert.equal(distributionPlugins['tag-counts'].bind(context).onSelect,callback);assert.equal(distributionPlugins.treemap.bind(context).enabled,false);assert.deepEqual(distributionPlugins.treemap.bind({...context,groupValue:{status:'value',value:'active'}}).selected,['active']);assert.deepEqual(distributionPlugins.treemap.bind({...context,groupValue:{status:'pending'}}).selected,[]);
 const analysis=distributionPlugins['collection-analysis'].bind(context);assert.equal(analysis.onAxis,callback);assert.equal(analysis.values,context.facetValues);assert.equal(analysis.meanVariable,'mean');assert.equal(distributionPlugins.histogram.bind(context).fields.bins,14);
});
test('navigation plugins preserve offered-control checks and original confirmed record/note state',()=>{
 const activated=[],onControl=id=>activated.push(id),clear=()=>{},record={id:'A',revision:7},note={status:'error',code:'refused'},info={type:'original.asset',fields:[]},bound=id=>id==='offered';
 const context={section:{title:'Original title',buttons:[{id:'offered',label:'Original'}],breadcrumb:{homeLabel:'Original home',pageLabel:'Original page'},image:{url:'https://example.test/image.png',caption:''}},countValue:'0',countError:'refused',onControl,controlBound:bound,onClearContext:clear,confirmedRecord:record,recordStatus:'pending',contextReadCurrent:false,info,enabled:false,notepadValue:note,onNotepad:clear};
 for(const key of ['page','session','readSource'])Object.defineProperty(context,key,{get:()=>{throw Error(`forbidden ${key}`);}});
 for(const plugin of Object.values(navigationPlugins)){const props=plugin.Renderer(context).props;for(const forbidden of ['page','section','session','readSource'])assert.equal(Object.hasOwn(props,forbidden),false);}
 const buttons=navigationPlugins['button-group'].bind(context);assert.equal(buttons.isBound,bound);assert.equal(buttons.enabled,false);assert.equal(buttons.isBound('unknown'),false);buttons.onActivate('offered');assert.deepEqual(activated,['offered']);assert.equal(navigationPlugins['button-group'].bind({...context,controlBound:undefined}).isBound('offered'),false);
 const breadcrumb=navigationPlugins.breadcrumb.bind(context);assert.equal(breadcrumb.record,record);assert.equal(breadcrumb.status,'pending');assert.equal(breadcrumb.readCurrent,false);assert.equal(breadcrumb.onClear,clear);breadcrumb.onHome();assert.deepEqual(activated,['offered','home']);assert.equal(navigationPlugins.notepad.bind(context).value,note);assert.equal(navigationPlugins.notepad.bind(context).readCurrent,false);assert.equal(navigationPlugins['collection-title'].bind(context).value,'0');assert.equal(navigationPlugins['static-image'].bind(context).config.caption,'');
});
test('scalar and record-window adapters preserve pending results, authorization confirmation and original window callbacks',()=>{
 const pending={status:'pending'},error={status:'error',code:'refused'},selected={id:'original',revision:7},callback=()=>{},info={type:'original.asset',fields:[]},query={limit:100,offset:0},window={query,page:{records:[selected],total:1},onChange:callback};
 const section={title:'Original title',gauge:{max:100},progressLabel:'',progressTotal:'0',progressTotalVariable:'total',summaryField:'pressure',sparkline:{field:'pressure'},alertBanner:{tone:'warning'},recordCalendar:{dateField:'at',labelField:'name'},recordGantt:{startField:'start'},recordEvents:{timeField:'at'},scatter:{xField:'x',yField:'y'},leaderboard:{valueField:'pressure'}};
 const context={page:{object:{name:'original.asset'}},sourceScope:'member/definition',section,window,info,selected,onSelect:callback,enabled:false,pickerConfirmation:'pending',gaugeValue:pending,progressValue:error,progressTotal:pending,statisticsValue:error,sparklineValue:pending,alertValue:error};
 for(const key of ['session','readSource','catalog'])Object.defineProperty(context,key,{get:()=>{throw Error(`forbidden context ${key}`);}});
 for(const plugin of Object.values({...scalarPlugins,...recordWindowPlugins})){const props=plugin.Renderer(context).props;for(const forbidden of ['page','section','session','readSource','catalog','sourceScope'])assert.equal(Object.hasOwn(props,forbidden),false);}
 assert.equal(scalarPlugins.gauge.bind(context).value,pending);const progress=scalarPlugins.progress.bind(context);assert.equal(progress.value,error);assert.equal(progress.total,pending);assert.equal(progress.fixedTotal,undefined);assert.equal(progress.title,'');assert.equal(scalarPlugins.progress.bind({...context,section:{...section,progressTotalVariable:undefined}}).fixedTotal,'0');assert.equal(scalarPlugins['summary-stats'].bind(context).info,info);assert.equal(scalarPlugins['sparkline-kpi'].bind(context).window,window);
 const scatter=recordWindowPlugins['record-scatter'].bind(context);assert.equal(scatter.confirmation,'pending');assert.equal(scatter.enabled,false);assert.equal(scatter.selected,selected);assert.equal(scatter.onSelect,callback);
 for(const id of ['record-gantt','record-calendar','record-events','record-leaderboard'])assert.equal(recordWindowPlugins[id].bind(context).window,window);
 const calendar=recordWindowPlugins['record-calendar'],key=calendar.Renderer(context).key;
 assert.equal(calendar.Renderer({...context,window:{...window,page:{records:[],total:0}}}).key,key);
 for(const next of [{...context,sourceScope:'other-member'},{...context,page:{object:{name:'other.asset'}}},{...context,section:{...section,recordCalendar:{...section.recordCalendar,initialMonth:'2026-11'}}},{...context,window:{...window,query:{...query,offset:100}}}])assert.notEqual(calendar.Renderer(next).key,key);
});
test('the plugin adapter projects only declared props and never loads a renderer during registration or binding',()=>{
 let loads=0;const define=defineWidgetPlugin(),plugin=define('input',1,context=>({value:context.value}),async()=>{loads++;return ()=>null;});const context={value:'kept',privateSession:'must not escape'};
 const element=plugin.Renderer(context);assert.deepEqual(element.props,{value:'kept'});assert.equal(loads,0);assert.ok(Object.isFrozen(plugin));assert.throws(()=>define('input',2,()=>({}),async()=>()=>null),/Unsupported widget plugin/);
});
test('five input and five content plugins preserve ports and explicit empty/zero values without receiving host or session state',()=>{
 const callback=()=>{},value={status:'value',value:'draft'};
 const section={title:'Original title',text:'Original text',inputKind:'search',booleanLabel:'',booleanVariant:'checkbox',choiceInput:{variant:'multiple',options:['a']},dateKind:'datetime',dateOffset:'+08:00',dateLabel:'',rangeInput:{min:'0',max:'100',step:'1'},headingLevel:'h3',spacer:{size:0},separator:{label:''},notice:{title:'',message:'Original note',tone:'info'}};
 const context={section,value:'typed',numeric:true,valueError:'invalid-decimal',inputScopes:['original'],onValue:callback,enabled:false,dateValue:value,onDate:callback,choiceValue:value,choiceSetValue:{status:'value',value:{kind:'string-set',values:['a']}},onChoice:callback,onChoiceSet:callback,booleanInput:{status:'value',value:false},onBoolean:callback,rangeLower:value,rangeUpper:value,onRange:callback};
 for(const key of ['page','session','readSource','window'])Object.defineProperty(context,key,{get:()=>{throw Error(`forbidden context ${key}`);}});
 for(const plugin of Object.values({...inputPlugins,...contentPlugins})){const props=plugin.Renderer(context).props;for(const forbidden of ['page','section','session','readSource','window'])assert.equal(Object.hasOwn(props,forbidden),false);}
 assert.equal(inputPlugins.input.bind(context).onChange,callback);assert.equal(inputPlugins.input.bind(context).error,'invalid-decimal');assert.equal(inputPlugins['boolean-input'].bind(context).value.value,false);assert.equal(inputPlugins['boolean-input'].bind(context).label,'');assert.equal(inputPlugins['boolean-input'].bind(context).enabled,false);assert.equal(inputPlugins['date-input'].bind(context).offset,'+08:00');assert.equal(inputPlugins['choice-input'].bind(context).onSet,callback);assert.equal(inputPlugins['range-input'].bind(context).lower,value);assert.equal(contentPlugins.spacer.bind(context).config.size,0);assert.equal(contentPlugins.separator.bind(context).config.label,'');assert.equal(contentPlugins.notice.bind(context).config.title,'');assert.equal(contentPlugins.heading.bind(context).level,3);
});
