import {registerHooks} from "node:module";
registerHooks({resolve(specifier,context,next){try{return next(specifier,context)}catch(error){if(specifier.startsWith(".")&&!specifier.endsWith(".ts"))return next(`${specifier}.ts`,context);throw error;}}});
import assert from "node:assert/strict";
import test from "node:test";
const {approvalDecisionReason,approvalTaskID,approvalTasks,originalApproval,originalNotifications,createWorkViews}=await import("./service.ts");
const task={id:"TASK-A",revision:1,ref:"work.approval/REQUEST-A",state:"open",candidates:["approver"],title:"True offered approval",app:"work"};
const request={id:"REQUEST-A",revision:7,title:"Original request",requester:"requester",target:"sample.note/A",action:"sample.note.submit",state:"pending",level:0,levels:[{title:"Original level",approvers:["approver"],approved:[]}]};
const notice={id:"NOTICE",member:"approver",title:"Real notice",at:"2026-10-03T00:00:00Z",read:false};
function fixture(){let active=true;const calls=[],host={me:{principalId:"approver"},can:()=>true,client:{connection:{tenant:"T",principal:"approver"},authorities:{outbox:[]}},source:{get:async(type,id)=>{calls.push({type,id});return{record:type==="work.task"?task:request};}},decide:async(schema,target,payload,options)=>{calls.push({schema,target,payload,options});return true;},resend:async()=>{calls.push({resend:true});host.client.authorities.outbox[0].state="SUBMISSION_STATE_CONFIRMED";}};return {host,calls,service:createWorkViews(host,()=>active),retire:()=>active=false};}
test("only original offered approval tasks enter the current caller inbox, without ordinary task or business status coercion",()=>{assert.equal(approvalTaskID(task),"REQUEST-A");assert.deepEqual(approvalTasks([task,{...task,id:"TASK-X",ref:"sample.note/B"}],"approver"),[task]);for(const patch of [{archived:true,assignee:"approver"},{state:"done"},{candidates:["other"]},{assignee:"other"}])assert.throws(()=>approvalTasks([{...task,...patch}],"approver"),/no longer/);assert.throws(()=>approvalTasks([task,{...task,id:"OTHER"}],"approver"),/duplicate/);});
test("approval reads retain exact request identity and decisions use the original request revision rather than task revision",async()=>{const f=fixture();assert.equal(await f.service.approval(task),request);assert.equal(await f.service.decideApproval(task,request,"approve"),true);assert.deepEqual(f.calls[0],{type:"work.approval",id:"REQUEST-A"});assert.deepEqual(f.calls[1],{type:"work.task",id:"TASK-A"});assert.equal(f.calls[2].schema,"work.approval.approve");assert.equal(f.calls[2].options.expectedRevision,7);for(const patch of [{id:"OTHER"},{state:"approved"},{archived:true},{revision:0},{level:1}])assert.throws(()=>originalApproval(task,{...request,...patch}),/unavailable/);await assert.rejects(()=>f.service.decideApproval(task,{...request,requester:"approver"},"approve"),/requester/);});
test("lost approval answers resend the exact original key and opposite decisions or later revisions cannot create unanswered work",async()=>{const f=fixture();f.host.client.authorities.outbox.push({state:"SUBMISSION_STATE_UNKNOWN",submission:{tenantId:"T",principalId:"approver",target:{type:"work.approval",id:"REQUEST-A"},schema:{name:"work.approval.approve"},expectedRevision:7,payload:btoa("{}"),idempotencyKey:"ORIGINAL"}});await assert.rejects(()=>f.service.decideApproval(task,request,"reject"),/unanswered/);await assert.rejects(()=>f.service.decideApproval(task,{...request,revision:8},"approve"),/unanswered/);assert.equal(await f.service.decideApproval(task,request,"approve"),true);assert.deepEqual(f.calls,[{resend:true}]);assert.equal(f.host.client.authorities.outbox[0].submission.idempotencyKey,"ORIGINAL");});
test("notification membership, stable ID, refusal and retired read results remain explicit",async()=>{const f=fixture();assert.deepEqual(originalNotifications([notice],"approver"),[notice]);assert.throws(()=>originalNotifications([{...notice,member:"other"}],"approver"),/incompatible/);assert.throws(()=>originalNotifications([notice,notice],"approver"),/incompatible/);assert.equal(await f.service.readNotification(notice),true);assert.equal(f.calls[0].schema,"platform.notification.read");f.host.decide=async(_schema,_target,_payload,options)=>{options.onRefused("Denied original decision");return false;};await assert.rejects(()=>f.service.readNotification(notice),/Denied/);f.host.source.get=async()=>{f.retire();return {record:request};};await assert.rejects(()=>f.service.approval(task),/scope/);});
test("the original Go nil approvals slice means no decisions; missing or malformed values remain unavailable",()=>{const raw={...request,levels:[{...request.levels[0],approved:null}]};assert.deepEqual(originalApproval(task,raw).levels[0].approved,[]);assert.equal(raw.levels[0].approved,null);for(const approved of [undefined,"approver",{}])assert.throws(()=>originalApproval(task,{...raw,levels:[{...raw.levels[0],approved}]}),/unavailable/);});
test("a request cannot replace an earlier offered task that has already closed or changed identity",async()=>{for(const patch of [{state:"done"},{id:"OTHER"},{ref:"work.approval/OTHER"},{assignee:"other"}]){const f=fixture();f.host.source.get=async type=>({record:type==="work.task"?{...task,...patch}:request});await assert.rejects(()=>f.service.approval(task),/no longer/);}});
test("multiple views synchronously reserve one request before authority refresh can queue competing decisions",async()=>{const f=fixture(),other=createWorkViews(f.host,()=>true);let release;const gate=new Promise(resolve=>release=resolve);f.host.decide=async(schema)=>{f.calls.push(schema);return gate;};const first=f.service.decideApproval(task,request,"approve"),same=other.decideApproval(task,request,"approve");await assert.rejects(()=>other.decideApproval(task,request,"reject"),/already being/);assert.deepEqual(f.calls,["work.approval.approve"]);release(true);assert.equal(await first,true);assert.equal(await same,true);assert.equal(await other.decideApproval(task,request,"reject"),true);});
test("mixed unanswered decisions or note/evidence variants cannot be silently resent as this empty native decision",async()=>{for(const patch of [{schema:{name:"work.approval.reject"}},{payload:btoa('{"note":"different intent"}')},{evidenceFactIds:["ORIGINAL-FACT"]}]){const f=fixture(),base={tenantId:"T",principalId:"approver",target:{type:"work.approval",id:"REQUEST-A"},schema:{name:"work.approval.approve"},expectedRevision:7,payload:btoa("{}"),idempotencyKey:"ORIGINAL"};f.host.client.authorities.outbox.push({state:"SUBMISSION_STATE_UNKNOWN",submission:base},{state:"SUBMISSION_STATE_UNKNOWN",submission:{...base,...patch,idempotencyKey:"OTHER"}});await assert.rejects(()=>f.service.decideApproval(task,request,"approve"),/unanswered/);assert.equal(f.calls.length,0);}});
test("all-approver rows and delegates reflect already recorded original approval identities without inferring roles",async()=>{const all={...request,levels:[{...request.levels[0],all:true,approved:["approver"]}]};assert.match(approvalDecisionReason(all,"approver"),/already recorded/);await assert.rejects(()=>fixture().service.decideApproval(task,all,"approve"),/already recorded/);const delegated={...request,levels:[{title:"Original level",approvers:["chief"],approved:[],delegates:{delegate:"chief"}}]};assert.equal(approvalDecisionReason(delegated,"delegate"),undefined);assert.match(approvalDecisionReason({...delegated,levels:[{...delegated.levels[0],approved:["chief"]}]},"delegate"),/already recorded/);assert.match(approvalDecisionReason(delegated,"constructor"),/not a current/);});
