import {useEffect,useState} from "react";
import {Input,Select} from "../primitives/input";
import {t} from "../i18n";
import type {EntityInfo,EntityRecord} from "./Records";
import {ObservationTimeSeries} from "./ObservationTimeSeries";
import {observationFields,observationStatisticsCurrent,observationThresholdDraft,observationTimeSeries,type ObservationSignal,type ObservationStatisticsValue,type ObservationWindow} from "./observation-model";

export type ObservationStatisticsProps={scope:string;info:EntityInfo;signals:ObservationSignal[];timeField:string;signal:string;threshold:number;windowRows:number;windowOptions:number[];value?:ObservationStatisticsValue;latest?:{scope:string;signal:string;record:EntityRecord};history?:ObservationWindow;enabled?:boolean;readCurrent?:boolean;error?:string;onChange?:(value:{signal:string;threshold:number;windowRows:number})=>void};
export function ObservationStatistics(props:ObservationStatisticsProps){return <StatisticsSurface key={JSON.stringify([props.scope,props.signal])} {...props}/>;}
function StatisticsSurface(props:ObservationStatisticsProps){
 const {scope,info,signals,timeField,signal,threshold,windowRows,windowOptions,value,latest,history,enabled=true,readCurrent=true,error,onChange}=props;
 const [draft,setDraft]=useState<{basis:number;text:string}|undefined>(),text=draft&&Object.is(draft.basis,threshold)?draft.text:String(threshold),selected=signals.find(s=>s.field===signal);
 useEffect(()=>setDraft(undefined),[threshold]);
 const compatible=!!selected&&!!observationFields(info,signals,{time:timeField})&&Number.isFinite(threshold)&&windowOptions.length>0&&windowOptions.length<=8&&new Set(windowOptions).size===windowOptions.length&&windowOptions.every(n=>Number.isSafeInteger(n)&&n>0&&n<=100000)&&windowOptions.includes(windowRows),current=value?observationStatisticsCurrent(value,scope,signal,threshold,windowRows):"stale";
 if(!compatible)return <p role="alert">{t("Original observation statistics bindings are unavailable or incompatible.")}</p>;
 const write=(patch:Partial<{signal:string;threshold:number;windowRows:number}>)=>{if(enabled&&readCurrent)onChange?.({signal,threshold,windowRows,...patch});},disabled=!enabled||!readCurrent||!onChange;
 const number=observationThresholdDraft(text),validDraft=number!==undefined,latestCurrent=latest?.scope===scope&&latest.signal===signal?latest.record:undefined,model=latestCurrent?observationTimeSeries([latestCurrent],info,timeField,[selected!]):undefined,point=model?.series[0]?.points[0];
 const format=(n?:number)=>n===undefined?t("No value"):n.toLocaleString(undefined,{maximumFractionDigits:2});
 return <div className="grid min-w-0 gap-3"><div className="grid min-w-0 grid-cols-1 gap-2 sm:grid-cols-3"><label className="grid min-w-0 gap-1 text-xs">{t("Observation signal")}<Select value={signal} disabled={disabled} onChange={e=>{if(signals.some(s=>s.field===e.target.value))write({signal:e.target.value});}}>{signals.map(s=><option key={s.field} value={s.field}>{info.fields.find(f=>f.name===s.field)!.title}{s.unit?` (${s.unit})`:""}</option>)}</Select></label><label className="grid gap-1 text-xs">{t("Observation window rows")}<Select value={String(windowRows)} disabled={disabled} onChange={e=>{const n=Number(e.target.value);if(windowOptions.includes(n))write({windowRows:n});}}>{windowOptions.map(n=><option key={n} value={String(n)}>{n.toLocaleString()}</option>)}</Select></label><label className="grid gap-1 text-xs">{t("Alarm above")}<Input inputMode="decimal" aria-invalid={!validDraft} value={text} disabled={disabled} onChange={e=>{const next=e.target.value;setDraft({basis:threshold,text:next});const n=observationThresholdDraft(next);if(n!==undefined)write({threshold:n});}}/></label></div>{!validDraft&&<p role="alert">{t("Enter a finite alarm value. The invalid draft does not change the original threshold.")}</p>}{error?<p role="alert">{t(error)}</p>:!readCurrent||validDraft&&number!==threshold||current==="stale"?<p role="status">{t("Loading original observation statistics…")}</p>:current==="invalid"?<p role="alert">{t("The original observation statistics answer is invalid.")}</p>:<><dl className="grid min-w-0 grid-cols-2 gap-3 sm:grid-cols-4">{[[t("Mean"),format(value!.mean)],[t("Min"),format(value!.min)],[t("Max"),format(value!.max)],[t("Above {threshold}" ,{threshold}),String(value!.above)]].map(([title,value])=><div key={title} className="min-w-0"><dt className="break-words text-[10px] uppercase text-muted">{title}</dt><dd className="break-all text-lg font-semibold tabular-nums">{value}</dd></div>)}</dl><p role="status" className="text-xs text-muted">{t("{count} observations · {valid} numeric values in the original {rows}-row window",{count:value!.count.toLocaleString(),valid:value!.valid.toLocaleString(),rows:windowRows.toLocaleString()})}</p>{latestCurrent&&!model?<p role="alert">{t("The original latest sample is unavailable or incompatible.")}</p>:point?<p role="status" className="break-all text-xs">{t("Latest original sample")} · {latestCurrent!.id} · {point.time} · {format(point.value??undefined)}{selected!.unit?` ${selected!.unit}`:""}</p>:<p role="status">{t("No confirmed latest sample.")}</p>}{history&&<ObservationTimeSeries scope={scope} window={history} info={info} timeField={timeField} signals={[selected!]} label={t("Original signal history")}/>}</>}</div>;
}
