import {Blob as NodeBlob} from "node:buffer";
import {act,cleanup,fireEvent,render,screen,waitFor} from "@testing-library/react";
import {afterEach,beforeEach,expect,test,vi} from "vitest";
import {pageUIManifest} from "@platform/kernel";
import {PdfViewer} from "./PdfViewer";
import type {AttachedFile} from "./Records";
import type {PdfDocument} from "./pdf-engine";
const engine=vi.hoisted(()=>({load:vi.fn()}));vi.mock("./pdf-engine",()=>({loadPdfDocument:engine.load}));
afterEach(cleanup);beforeEach(()=>engine.load.mockReset());
const stamp={by:"test",at:"2026-10-03T12:00:00Z"},blob=()=>new NodeBlob(["%PDF-1.4 fixture bytes"],{type:"application/pdf"}) as unknown as Blob,attachment=(data:Blob,id="FILE-PDF"):AttachedFile=>({id,revision:1,created:stamp,changed:stamp,by:"member",name:"actual.pdf",size:data.size,contentType:data.type});
const document=():PdfDocument=>({pages:3,render:vi.fn(async()=>{}),destroy:vi.fn(async()=>{})});
function deferred<T>(){let resolve!:(value:T)=>void;const promise=new Promise<T>(done=>{resolve=done;});return {promise,resolve};}
test("PDF controller uses parsed page count and original page state without source totals or automatic writes",async()=>{
 const doc=document(),data=blob(),writes:string[]=[],props={attachment:attachment(data),blob:data,page:"1",onPage:(value:string)=>writes.push(value)};engine.load.mockResolvedValue(doc);const view=render(<PdfViewer {...props}/>);await screen.findByRole("img",{name:"PDF page 1 of 3"});expect(screen.getByText("of 3 actual pages")).toBeTruthy();expect(doc.render).toHaveBeenCalledWith(1,expect.any(HTMLCanvasElement),expect.any(AbortSignal));expect(writes).toEqual([]);expect((screen.getByRole("button",{name:"Previous PDF page"}) as HTMLButtonElement).disabled).toBe(true);
 fireEvent.click(screen.getByRole("button",{name:"Next PDF page"}));expect(writes).toEqual(["2"]);expect(screen.getByRole("img",{name:"PDF page 1 of 3"})).toBeTruthy();view.rerender(<PdfViewer {...props} page="3"/>);await screen.findByRole("img",{name:"PDF page 3 of 3"});expect((screen.getByRole("button",{name:"Next PDF page"}) as HTMLButtonElement).disabled).toBe(true);expect(engine.load).toHaveBeenCalledOnce();
});
test("empty, malformed or out-of-range original page values remain visible drafts with no falsely clamped page",async()=>{
 const doc=document(),data=blob(),writes:string[]=[],props={attachment:attachment(data),blob:data,page:"",onPage:(value:string)=>writes.push(value)};engine.load.mockResolvedValue(doc);const view=render(<PdfViewer {...props}/>);await screen.findByRole("textbox",{name:"PDF page"});expect((screen.getByRole("textbox") as HTMLInputElement).value).toBe("");expect(screen.queryByRole("img")).toBeNull();expect(doc.render).not.toHaveBeenCalled();
 for(const page of ["0","4","01","1e0","-1","9007199254740993"]){view.rerender(<PdfViewer {...props} page={page}/>);expect((screen.getByRole("textbox") as HTMLInputElement).value).toBe(page);expect(screen.getByRole("status").textContent).toContain("original page value");expect(screen.queryByRole("img")).toBeNull();}
 expect(writes).toEqual([]);fireEvent.change(screen.getByRole("textbox"),{target:{value:"2"}});expect(writes).toEqual(["2"]);expect(doc.render).not.toHaveBeenCalled();view.rerender(<PdfViewer {...props} page="2"/>);await screen.findByRole("img",{name:"PDF page 2 of 3"});
});
test("obsolete page rendering cannot restore an old canvas or overwrite the current page",async()=>{
 const old=deferred<void>(),doc=document();vi.mocked(doc.render).mockImplementationOnce(()=>old.promise);const data=blob(),props={attachment:attachment(data),blob:data,onPage:vi.fn()};engine.load.mockResolvedValue(doc);const view=render(<PdfViewer {...props} page="1"/>);await waitFor(()=>expect(doc.render).toHaveBeenCalledOnce());const oldCanvas=view.container.querySelector("canvas")!,oldSignal=vi.mocked(doc.render).mock.calls[0]![2];view.rerender(<PdfViewer {...props} page="2"/>);await screen.findByRole("img",{name:"PDF page 2 of 3"});expect(oldSignal.aborted).toBe(true);expect(oldCanvas.isConnected).toBe(false);await act(async()=>old.resolve());expect(screen.getByRole("img",{name:"PDF page 2 of 3"})).toBeTruthy();expect(screen.queryByRole("img",{name:"PDF page 1 of 3"})).toBeNull();
});
test("changing attachment or member scope retires the parser and cannot publish a late document",async()=>{
 const old=deferred<PdfDocument>(),previous=document(),next=document(),data=blob(),props={attachment:attachment(data),blob:data,page:"1"};engine.load.mockImplementationOnce(()=>old.promise).mockResolvedValueOnce(next);const view=render(<PdfViewer {...props} scope="member:one"/>);await waitFor(()=>expect(engine.load).toHaveBeenCalledOnce());const signal=engine.load.mock.calls[0]![1] as AbortSignal;view.rerender(<PdfViewer {...props} scope="member:two"/>);await screen.findByRole("img");expect(signal.aborted).toBe(true);await act(async()=>old.resolve(previous));expect(previous.destroy).toHaveBeenCalledOnce();expect(previous.render).not.toHaveBeenCalled();view.unmount();expect(next.destroy).toHaveBeenCalledOnce();
});
test("bytes budget, type and confirmed size refuse parsing while explicit browser, password and render failures stay honest",async()=>{
 const data=blob(),download=vi.fn(),view=render(<PdfViewer attachment={{...attachment(data),size:0}} blob={data} page="1" onDownload={download}/>);expect(screen.getByRole("alert").textContent).toContain("do not match");expect(engine.load).not.toHaveBeenCalled();
 const huge=new NodeBlob([new Uint8Array(pageUIManifest.runtime.collaboration.maxPreviewBytes+1)],{type:"application/pdf"}) as unknown as Blob;view.rerender(<PdfViewer attachment={attachment(huge)} blob={huge} page="1"/>);expect(screen.getByRole("alert").textContent).toContain("bytes exceed");expect(engine.load).not.toHaveBeenCalled();
 for(const message of ["This browser does not support the required PDF rendering APIs.","Password-protected PDFs cannot be previewed.","The PDF page count exceeds the preview budget."]){engine.load.mockRejectedValueOnce(new Error(message));const next=blob();view.rerender(<PdfViewer attachment={attachment(next)} blob={next} page="1" onDownload={download}/>);await waitFor(()=>expect(screen.getByRole("alert").textContent).toBe(message));expect(screen.queryByRole("img")).toBeNull();}
 fireEvent.click(screen.getByRole("button",{name:"Download original attachment"}));expect(download).toHaveBeenCalledOnce();
 const doc=document();vi.mocked(doc.render).mockRejectedValueOnce(new Error("PDF page dimensions exceed the preview budget."));engine.load.mockResolvedValueOnce(doc);const next=blob();view.rerender(<PdfViewer attachment={attachment(next)} blob={next} page="1"/>);await waitFor(()=>expect(screen.getByRole("alert").textContent).toContain("dimensions exceed"));expect(screen.queryByRole("img")).toBeNull();
});
