import {cleanup,fireEvent,render,screen} from "@testing-library/react";
import {afterEach,expect,test,vi} from "vitest";
import {RecordCalendar,calendarRecords,adjacentCalendarMonth,validCalendarMonth} from "./RecordCalendar";
import type {EntityRecord} from "./Records";
afterEach(cleanup);
const row=(id:string,due:string):EntityRecord=>({id,revision:1,created:{by:"test",at:"2001-01-01T00:00:00Z"},changed:{by:"test",at:"2001-01-01T00:00:00Z"},title:id,due});
const fields={dateField:"due",labelField:"title",initialMonth:"2026-10",kind:"date" as const};
test("calendar preserves civil days, uses UTC datetime days and validates month/year boundaries",()=>{expect(calendarRecords([row("A","2026-10-02")],fields).rows[0]!.day).toBe("2026-10-02");expect(calendarRecords([row("B","2026-10-01T23:30:00-02:00")],{...fields,kind:"datetime"}).rows[0]!.day).toBe("2026-10-02");expect(calendarRecords([row("C","2026-02-30")],fields).invalid).toBe(1);expect(adjacentCalendarMonth("2026-12",1)).toBe("2027-01");expect(adjacentCalendarMonth("0001-01",-1)).toBeUndefined();expect(adjacentCalendarMonth("9999-12",1)).toBeUndefined();expect(validCalendarMonth("0000-01")).toBe(false);expect(validCalendarMonth("2026-13")).toBe(false);});
test("calendar emits original authorized records and clears selection on month/day and binding changes",()=>{const records=[row("A","2026-10-02"),row("B","2026-10-03")],select=vi.fn(),props={records,fields,scope:"one",onSelect:select};const {rerender}=render(<RecordCalendar {...props}/>);fireEvent.click(screen.getByRole("button",{name:"2026-10-02 · 1 records"}));fireEvent.click(screen.getByRole("button",{name:"A"}));expect(select).toHaveBeenLastCalledWith(records[0]);fireEvent.click(screen.getByRole("button",{name:"Next month"}));expect(select).toHaveBeenLastCalledWith(undefined);expect(screen.queryByRole("button",{name:"A"})).toBeNull();expect(screen.getByText("2026-11")).toBeTruthy();rerender(<RecordCalendar {...props} scope="two"/>);expect(screen.getByText("2026-10")).toBeTruthy();expect(screen.queryByRole("region",{name:"Records on 2026-10-02"})).toBeNull();});
