import {cleanup,fireEvent,render,screen} from "@testing-library/react";
import {afterEach,expect,test,vi} from "vitest";
import {SearchAround,type SearchAroundPathEntry} from "./SearchAround";
import {pageUIManifest} from "@platform/kernel";
import type {EntityInfo,EntityRecord} from "./Records";
afterEach(cleanup);
const info=(object:string)=>({type:object,title:object,fields:[{name:"name",title:"Name",type:"text"}]}) as EntityInfo;
const row=(id:string):EntityRecord=>({id,revision:1,created:{},changed:{},name:"<b>Same object</b>"});
const entry=(object:string,id:string):SearchAroundPathEntry=>({object,record:row(id),info:info(object),labelField:"name"});
const relations=[{id:"retained:v1:forward:orders",label:"Same relation",total:42},{id:"retained:v3:reverse:sensors",label:"Same relation",total:0}],window={records:[row("A"),row("B")],info:info("sample.order"),labelField:"name",total:42};
test("Search Around preserves repeated original path occurrences, real tab identities/counts and independent traverse/output selection",()=>{
 const path=[entry("sample.asset","A"),entry("sample.order","A"),entry("sample.asset","A")],back=vi.fn(),relation=vi.fn(),traverse=vi.fn(),select=vi.fn(),view=render(<SearchAround path={path} relations={relations} activeRelation={relations[0]!.id} window={window} onBack={back} onRelation={relation} onTraverse={traverse} onSelect={select} selected={{object:"sample.order",id:"B"}}/>);
 expect(view.container.querySelector("b")).toBeNull();expect(screen.getByRole("status").textContent).toBe("Showing 2 of 42 related records.");const tabs=screen.getAllByRole("tab");expect(tabs[0]!.textContent).toContain("(42)");expect(tabs[1]!.textContent).toContain("(0)");fireEvent.click(tabs[1]!);expect(relation).toHaveBeenCalledWith(relations[1]!.id);fireEvent.keyDown(tabs[0]!,{key:"ArrowRight"});expect(relation).toHaveBeenLastCalledWith(relations[1]!.id);fireEvent.click(screen.getAllByRole("button",{name:/Same object/})[0]!);expect(back).toHaveBeenCalledWith(0);
 fireEvent.click(screen.getByRole("button",{name:"Traverse from sample.order/A"}));expect(traverse).toHaveBeenCalledWith("sample.order",window.records[0]);expect(select).not.toHaveBeenCalled();const output=screen.getByRole("button",{name:"Select output sample.order/B"});fireEvent.click(output);expect(select).toHaveBeenCalledWith("sample.order",window.records[1]);expect(output.getAttribute("aria-pressed")).toBe("true");
});
test("unconfirmed and refused relation/output states do not invent zero, emit callbacks or retain old rows",()=>{
 const props={path:[entry("sample.asset","A")],relations,activeRelation:relations[0]!.id,window},traverse=vi.fn(),select=vi.fn(),view=render(<SearchAround {...props} onTraverse={traverse} onSelect={select} selectionEnabled={false}/>);fireEvent.click(screen.getByRole("button",{name:"Select output sample.order/A"}));expect(select).not.toHaveBeenCalled();fireEvent.click(screen.getByRole("button",{name:"Traverse from sample.order/A"}));expect(traverse).toHaveBeenCalledTimes(1);
 view.rerender(<SearchAround {...props} onSelect={select} selectionPending selectionError="Original output read refused"/>);expect(screen.getAllByRole("status").at(-1)!.textContent).toBe("Confirming original output record…");fireEvent.click(screen.getByRole("button",{name:"Select output sample.order/A"}));expect(select).not.toHaveBeenCalled();expect(screen.getByRole("alert").textContent).toBe("Original output read refused");
 view.rerender(<SearchAround {...props} relations={[{...relations[0]!,total:undefined,error:"Original relation denied"}]} onTraverse={traverse}/>);expect(screen.getByRole("alert").textContent).toBe("Original relation denied");expect(screen.getByRole("tab").textContent).toContain("Unavailable");expect(screen.queryByRole("button",{name:/Traverse from/})).toBeNull();expect(screen.queryByText("sample.order/B")).toBeNull();
 view.rerender(<SearchAround {...props} relations={[{...relations[0]!,total:undefined,pending:true}]} onTraverse={traverse}/>);expect(screen.getByRole("tab").textContent).toContain("Loading…");expect(screen.queryByText("(0)")).toBeNull();
 view.rerender(<SearchAround {...props} relations={[{...relations[0]!,total:undefined}]} onTraverse={traverse}/>);expect(screen.getByRole("tab").textContent).toContain("Count unavailable");
});
test("scope-owned controlled frames replace prior identities, readonly callbacks are blocked and invalid paths/windows refuse",()=>{
 const props={path:[entry("sample.asset","A")],relations,activeRelation:relations[0]!.id,window},back=vi.fn(),relation=vi.fn(),traverse=vi.fn(),select=vi.fn(),view=render(<SearchAround {...props} onBack={back} onRelation={relation} onTraverse={traverse} onSelect={select} enabled={false}/>);for(const button of screen.getAllByRole("button"))fireEvent.click(button);expect(back).not.toHaveBeenCalled();expect(relation).not.toHaveBeenCalled();expect(traverse).not.toHaveBeenCalled();expect(select).not.toHaveBeenCalled();
 view.rerender(<SearchAround path={[]} relations={[]}/>);expect(screen.getByRole("status").textContent).toBe("Select a confirmed record to start Search Around.");expect(screen.queryByText("sample.order/B")).toBeNull();
 for(const patch of [{path:Array.from({length:pageUIManifest.runtime.exploration.maxPath+1},()=>entry("sample.asset","A"))},{path:[{...entry("sample.asset","A"),labelField:"private"}]},{relations:[relations[0]!,relations[0]!]},{window:{...window,total:1}},{window:{...window,records:[row("A"),row("A")]}},{window:{...window,records:Array.from({length:21},(_,index)=>row(String(index)))}}]){view.rerender(<SearchAround {...props} {...patch}/>);expect(screen.getByRole("alert")).toBeTruthy();expect(screen.queryByRole("tablist")).toBeNull();}
});
test("each original self-link can expose both independent direction tabs within the declared relation budget",()=>{
 const directed=Array.from({length:pageUIManifest.runtime.exploration.maxRelations},(_,index)=>["forward","reverse"].map((direction,side)=>({id:JSON.stringify([`self-link-${index}`,"retained-v1",direction,"sample.person"]),label:"Original self relation",total:index+side}))).flat(),change=vi.fn(),view=render(<SearchAround path={[entry("sample.person","A")]} relations={directed} activeRelation={directed[0]!.id} onRelation={change}/>);
 expect(screen.getAllByRole("tab")).toHaveLength(2*pageUIManifest.runtime.exploration.maxRelations);fireEvent.click(screen.getAllByRole("tab")[1]!);expect(change).toHaveBeenCalledWith(directed[1]!.id);expect(directed[0]!.id).not.toBe(directed[1]!.id);expect(screen.queryByRole("alert")).toBeNull();
 view.rerender(<SearchAround path={[entry("sample.person","A")]} relations={[...directed,{id:"over-budget",label:"Extra",total:0}]}/>);expect(screen.getByRole("alert")).toBeTruthy();expect(screen.queryByRole("tablist")).toBeNull();
});
