import type { CatalogEntry } from "@platform/catalog";

// Meaning is maintained by the UI owner. Props remain the actual exported types;
// this file never imports the preview bundle into application code.
const asset = (id: string, name: string, summary: string, layer: CatalogEntry["layer"], source: string,
  exports: string[], example: string, extra: Partial<CatalogEntry> = {}): CatalogEntry => ({
  id, owner: "@platform/ui", name, summary, layer, source: `web/packages/ui/src/${source}`,
  exports, example, authority: "api", maturity: "recommended", scope: "platform", uses: ["code"], tags: [], ...extra,
});

export const entries: CatalogEntry[] = [
  asset("ui/record-events","Authorized event list","Present ordered original business events with explicit time and severity tones.",3,"records/RecordEvents.tsx",["RecordEvents","recordEventRows"],"RecordEventsExample",{tags:["events","timeline","window"],constraints:["The caller owns the authorized window and business time; the list does not create events or read another collection."]}),
  asset("ui/record-chart","Ordered record chart","Plot original authorized records without merging equal axis labels or reading another collection.",3,"records/RecordChart.tsx",["RecordChart","recordChartSpec"],"RecordChartExample",{tags:["records","chart","window"],dependencies:["ui/chart"],constraints:["The caller owns the ordered window, field permissions and point budget; this chart performs no reads or writes."]}),
  asset("ui/record-cards","Record cards","Select original records from a caller-owned grid or list window.",3,"records/RecordCards.tsx",["RecordCards"],"RecordCardsExample",{tags:["records","cards","selection"],dependencies:["ui/entity-card","ui/button"],constraints:["Card fields come from permission-filtered metadata; the caller owns reads, selection and navigation."]}),
  asset("ui/collection-title","Collection title","Show a declared collection name and its caller-owned complete count.",2,"components/CollectionTitle.tsx",["CollectionTitle"],"CollectionTitles",{tags:["title","count"],states:["Loading","Error","Ready"],constraints:["The caller owns the authorized complete count and clears obsolete values."]}),
  asset("ui/facet-choices","Facet choices","Choose several authorized options with complete source counts and an optional histogram.",2,"fields/FacetChoices.tsx",["FacetChoices"],"FacetChoicesExample",{tags:["filter","facets","selection"],constraints:["The caller owns authorized options, counts and typed selected values."]}),
  asset("ui/command-menu", "Context commands", "Use the same commands from a pointer context menu or an explicit keyboard and touch trigger.", 2,
    "components/CommandMenu.tsx", ["CommandMenu"], "ContextCommands", {tags:["menu","commands","keyboard"],dependencies:["ui/button"],constraints:["The caller owns commands and disabled states; the menu does not perform business operations itself."]}),
  asset("ui/layout-region", "Sized layout regions", "Arrange weighted regions with bounded dimensions and local scrolling, stacking columns in narrow containers.", 2,
    "layout/LayoutRegion.tsx", ["LayoutRegion", "LayoutStack"], "SizedLayouts", {tags:["layout","sizing","scroll"], constraints:["The caller supplies validated dimensions and parent axes; layout grants no business access."]}),
  asset("foundation/semantic-tokens", "Semantic tokens", "Use shared surface, text, focus and status tokens across themes.", 0,
    "styles.css", [], "Tokens", { authority: "specification", uses: ["reference"], tags: ["color", "theme", "density"],
      constraints: ["Use semantic tokens instead of assigning domain meaning to raw colors."] }),
  asset("ui/virtual-stack", "Virtual item list", "Render measured rows by stable identity and retain the focused item.", 2,
    "layout/VirtualStack.tsx", ["VirtualStack"], "VirtualItems", { tags: ["virtual", "list", "layout"], constraints: ["The caller owns data reads and item state; offscreen local inputs are disposed."] }),
  asset("ui/flow-layout", "Flow layout and toolbar", "Wrap presentation items and navigate toolbar buttons with arrow keys.", 2,
    "layout/FlowLayout.tsx", ["FlowLayout"], "FlowLayouts", { tags: ["layout", "toolbar"], dependencies: ["ui/button"] }),
  asset("ui/content-tabs", "Content tabs", "Switch stable named panels with keyboard navigation and retain visited content.", 2,
    "layout/ContentTabs.tsx", ["ContentTabs"], "ContentTabsExample", { tags: ["tabs", "layout", "state"], dependencies: ["ui/button"] }),
  asset("ui/button", "Button", "One action control with primary, quiet, destructive, link and row variants.", 1,
    "primitives/button.tsx", ["Button"], "Buttons", { type: "ButtonProps", tags: ["action", "variants"],
      states: ["Enabled", "Disabled", "Keyboard focus"], snippet: 'import { Button } from "@platform/ui";\n<Button variant="primary" onClick={save}>Save</Button>' }),
  asset("ui/metal-button", "Metal button", "Tactile metallic and liquid glass styled buttons for prominent actions.", 1,
    "primitives/metalButton.tsx", ["MetalButton", "LiquidButton"], "MetalButtons", {
      tags: ["button", "metal", "tactile", "liquid", "variants"],
      states: ["Pressed", "Hover", "Touch"],
      snippet: 'import { MetalButton, LiquidButton } from "@platform/ui";\n<MetalButton variant="gold">Confirm</MetalButton>',
    }),
  asset("ui/retro-button", "Retro button", "Tactile mechanical keycap buttons styled after industrial equipment.", 1,
    "primitives/retroButton.tsx", ["RetroButton"], "RetroButtons", {
      tags: ["button", "retro", "tactile", "keycap", "variants"],
      states: ["Enabled", "Pressed", "Disabled", "Keyboard focus"],
      maturity: "experimental",
      snippet: 'import { RetroButton } from "@platform/ui";\n<RetroButton variant="default">RUN</RetroButton>',
    }),
  asset("ui/input", "Input controls", "Text, select and multiline controls for explicit labelled values.", 1,
    "primitives/input.tsx", ["Input", "Select", "Textarea"], "Inputs", { tags: ["text", "input", "select"], states: ["Enabled", "Disabled", "Invalid"] }),
  asset("ui/checkbox", "Checkbox", "A labelled boolean choice with an explicit disabled state.", 1,
    "primitives/controls.tsx", ["Checkbox"], "Checkboxes", { states: ["Checked", "Unchecked", "Disabled"] }),
  asset("ui/panels", "Cards and panels", "Group related content with a shared heading, description and action area.", 2,
    "primitives/card.tsx", ["Card", "Panel"], "Panels", { tags: ["inspector", "grouping"], dependencies: ["ui/button", "foundation/semantic-tokens"] }),
  asset("ui/editor-workbench", "Editor workbench", "Arrange a library, canvas and inspector with keyboard and pointer pane resizing.", 2,
    "layout/EditorWorkbench.tsx", ["EditorWorkbench"], "EditorPanels", { tags: ["editor", "layout", "inspector", "resize"], dependencies: ["ui/panels", "foundation/semantic-tokens"] }),
  asset("ui/form", "Form submission", "Submit an ad hoc form on Enter without reloading the page.", 2,
    "primitives/controls.tsx", ["Form"], "Forms", { dependencies: ["ui/input", "ui/button"] }),
  asset("ui/disclosure", "Disclosure", "Reveal supporting details while keeping the summary visible.", 2,
    "primitives/controls.tsx", ["Disclosure"], "Disclosures", { states: ["Expanded", "Collapsed"] }),
  asset("ui/file-picker", "File picker", "Pick a local file through a shared button; the caller owns upload.", 2,
    "primitives/controls.tsx", ["FilePicker"], "FilePicking", { dependencies: ["ui/button"], constraints: ["Picking a file does not upload or publish it."] }),
  asset("ui/toggles", "Multiple choices", "Switch several named choices on or off without a custom control.", 2,
    "primitives/controls.tsx", ["Toggles"], "Choices", { tags: ["tags", "options"] }),
  asset("ui/tree", "Hierarchy selection", "Select a row from a small hierarchy of labelled records.", 2,
    "primitives/controls.tsx", ["Tree"], "Hierarchy", { tags: ["tree", "parents"], maturity: "experimental",
      constraints: ["Rows are always expanded; collapse and full tree keyboard navigation are not implemented."] }),
  asset("ui/dialog", "Modal dialog", "Ask for a bounded decision with focus trapping and a labelled title.", 2,
    "primitives/dialog.tsx", ["Dialog"], "Dialogs", { states: ["Open", "Closed"], dependencies: ["ui/button"] }),
  asset("ui/sheet", "Detail sheet", "Inspect or edit details while keeping the underlying task in view.", 2,
    "primitives/sheet.tsx", ["Sheet"], "Sheets", { tags: ["inspector", "details"], states: ["Open", "Closed"] }),
  asset("ui/status", "Semantic status tags", "Map actual domain or kernel states to a label and one of five tones.", 2,
    "components/StatusTag.tsx", ["StatusTag", "Tag"], "Statuses", { tags: ["feedback", "status"], type: "StatusRegistry",
      dependencies: ["foundation/semantic-tokens"], constraints: ["Use exact registry keys; unknown states fall back to a neutral label."] }),
  asset("ui/data-table", "Data table", "Browse, sort and edit typed rows in a shared virtualized table.", 2,
    "components/DataTable.tsx", ["DataTable"], "Tables", { type: "DataTableProps", tags: ["table", "rows", "sorting"],
      states: ["Loading", "Empty", "Selected", "Editing"], dependencies: ["ui/input", "ui/field-types"] }),
  asset("ui/markdown", "Markdown display and editor", "Read formatted content or edit its source with a shared preview.", 2,
    "components/Markdown.tsx", ["Markdown", "MarkdownEditor"], "MarkdownContent", { tags: ["knowledge", "content"] }),
  asset("ui/page-header", "Page header", "Give a task its title, description and visible actions.", 2,
    "components/PageHeader.tsx", ["PageHeader"], "Headers", { dependencies: ["ui/button"] }),
  asset("ui/field-types", "Typed field vocabulary", "One field type owns display, editing, validation, sorting and filtering.", 3,
    "fields/types.tsx", ["field.text", "field.longText", "field.markdown", "field.number", "field.currency", "field.percent", "field.checkbox", "field.date", "field.datetime", "field.duration", "field.singleSelect", "field.multiSelect", "field.tags", "field.email", "field.url", "field.phone", "field.barcode", "field.rating", "field.attachment", "field.link", "field.formula", "field.timestamp"], "Fields", { type: "FieldType", tags: ["text", "longText", "markdown", "number", "currency", "percent", "checkbox", "date", "datetime", "duration", "singleSelect", "multiSelect", "tags", "email", "url", "phone", "barcode", "rating", "attachment", "link", "formula", "timestamp"],
      constraints: ["Reference links need a Workspace; attachment upload needs an explicit caller implementation."] }),
  asset("ui/entity-form", "Schema form", "Render labelled editors and validate an ad hoc schema before submission.", 3,
    "components/EntityForm.tsx", ["EntityForm"], "SchemaForms", { tags: ["form", "schema"], states: ["Invalid", "Submitting"], dependencies: ["ui/field-types", "ui/button"] }),
  asset("ui/record-form", "Entity form", "Edit declared entity fields using their shared validators and editors.", 3,
    "components/EntityForm.tsx", ["RecordForm"], "RecordForms", { tags: ["form", "entity"], states: ["Invalid", "Submitting"],
      dependencies: ["ui/field-types", "ui/button"], constraints: ["The caller owns persistence, authorization and conflict handling."] }),
  asset("ui/filter-bar", "Typed filters", "Build filters from the entity's declared fields and operators.", 3,
    "fields/entity.tsx", ["FilterBar"], "Filters", { type: "Filter", dependencies: ["ui/field-types", "ui/button"] }),
  asset("ui/entity-card", "Record summary", "Present a record's title, status and labelled properties.", 3,
    "components/EntityCard.tsx", ["EntityCard", "PropertyList"], "RecordSummaries", { tags: ["record", "properties"], dependencies: ["ui/status"] }),
  asset("ui/button-group","Button group","Activate stable scoped presentation controls through caller-owned bindings.",2,"components/ButtonGroup.tsx",["ButtonGroup"],"ButtonGroups",{tags:["buttons","toolbar"],dependencies:["ui/button","ui/flow-layout"],constraints:["Each control has a stable identity; the caller owns its binding, permissions and execution."]}),
  asset("ui/notifications", "Notifications", "Show unread changes and let the caller mark a notification as read.", 3,
    "components/NotificationList.tsx", ["NotificationList"], "Notifications", { type: "NotificationItem", states: ["Empty", "Read", "Unread"] }),
  asset("ui/record-list", "Record list", "Browse a scoped entity source with search, sort and paging.", 3,
"records/Records.tsx", ["RecordList"], "RecordLists", { type: "RecordSource", states: ["Loading", "Empty", "Error", "Selected", "Staged edits"], constraints:["An optional RecordEditPort supplies authorized displayed fields and the original revision-bound submit callback. Failed edits remain staged; the caller owns permissions and execution.","RecordColumnPresentation configures visible column titles, widths and typed formats without replacing field metadata or permissions. Hiding search retains the caller query.","RecordSelectionPort controls bounded selection in the current window; the caller confirms record permissions and owns pending, failure and cleanup. Window selection is not a complete matching set."], dependencies: ["ui/data-table", "ui/filter-bar"] }),
  asset("ui/record-kanban", "Authorized lifecycle board", "Select bounded records in their original lifecycle lanes and emit declared move commands.", 3,
    "records/RecordKanban.tsx", ["RecordKanban"], "RecordKanbans", {tags:["kanban","work","records"],states:["Empty","Selected","Invalid"],dependencies:["ui/entity-card","ui/button","ui/input"],constraints:["The caller supplies authorized records, lifecycle states and actions. This component does not write state."]}),
  asset("ui/record-timeline", "Authorized record timeline", "Display a bounded record window as time points or intervals, grouped by an original resource field.", 3,
    "records/RecordTimeline.tsx", ["RecordTimeline"], "RecordTimelines", { type:"TimelineFields",tags:["timeline","scheduling","records"],states:["Empty","Selected","Invalid"],dependencies:["ui/button"], constraints:["The caller supplies authorized records and selection. This component does not schedule or write records."] }),
  asset("ui/record-page", "Record detail and history", "Read a record's declared fields, related work and recorded changes.", 3,
    "records/Records.tsx", ["RecordPage", "RecordLinks", "RecordHistory"], "RecordDetails", { type: "RecordView", states: ["Loading", "Error", "Ready"],
      dependencies: ["ui/entity-card", "ui/lifecycle", "ui/tasks"], constraints: ["Visibility and allowed actions come from the scoped source and caller."] }),
  asset("ui/record-lookup", "Record lookup", "Search a caller's scoped source to choose a reference by record ID.", 3,
    "records/RecordLookup.tsx", ["RecordLookup"], "RecordLookups", { type: "RecordSource", states: ["Loading", "Empty", "Error", "Selected"], dependencies: ["ui/input"] }),
  asset("ui/tasks", "Tasks and inbox", "Present assigned work with the answers and actions supplied by its owner.", 3,
    "records/Records.tsx", ["Tasks", "Inbox"], "TaskInbox", { type: "InboxTask", tags: ["approval", "work"], states: ["Empty", "Pending"],
      dependencies: ["ui/button", "ui/status"], constraints: ["An inbox preview is not an approval or permission engine."] }),
  asset("ui/lifecycle", "Lifecycle status bar", "Display declared record states and caller-allowed transitions.", 3,
    "records/Records.tsx", ["StatusBar", "RecordStatus"], "Lifecycle", { type: "Lifecycle", dependencies: ["ui/button"],
      constraints: ["Only the canonical action owner may authorize and apply a transition."] }),
  asset("ui/chart", "Chart", "Render a visualization spec using inline values or a scoped aggregate source.", 3,
    "charts/Chart.tsx", ["Chart"], "Charts", { type: "ChartSpec", tags: ["chart", "kpi", "aggregate"], states: ["Loading", "Empty", "Error", "Ready"] }),
  asset("ui/pivot", "Pivot table", "Compare aggregate groups with totals and explicit drill-down.", 3,
    "charts/Pivot.tsx", ["Pivot"], "Pivots", { type: "ChartSource", uses:["code","widget"],widgets:["pivot"], tags: ["report", "aggregate"], states: ["Loading", "Empty", "Error", "Ready"] }),
  asset("ui/graph", "Read-only graph", "Observe relationships and execution paths through the shared canvas.", 3,
    "graph/Graph.tsx", ["Graph"], "Graphs", { type: "GraphNode", dependencies: ["ui/block-canvas"], states: ["Selected"] }),
  asset("ui/block-canvas", "Typed block canvas", "Compose nodes through typed ports with one shared graph interaction model.", 3,
    "graph/BlockCanvas.tsx", ["BlockCanvas", "NodeCanvas"], "Blocks", { type: "BlockCanvasProps", tags: ["flow", "node", "canvas"],
      states: ["Read only", "Editing", "Selected"], constraints: ["The canvas owns interaction; its caller owns graph semantics, validation and persistence."] }),
  asset("ui/flow", "Flow observation", "Inspect a native flow's graph, waiting steps and decision trace.", 3,
    "flows/FlowView.tsx", ["FlowView", "FlowGraph", "FlowReleaseBinding"], "FlowObservation", { type: "FlowInstanceData", tags: ["flow", "trace", "release", "version"], dependencies: ["ui/graph", "ui/status"] }),
  asset("ui/record-workspace", "Record list and detail", "Keep record browsing and focused detail in one responsive task frame.", 3,
    "records/RecordWorkspace.tsx", ["RecordWorkspace"], "MasterDetail", { tags: ["master-detail", "record", "workspace"],
      dependencies: ["ui/record-list", "ui/record-page", "ui/page-header"], constraints: ["Pass a scoped RecordSource; this layout does not define a business entity."] }),
  asset("pattern/workspace", "App Shell / Workspace", "Compose app navigation, routed tabs, commands and session context in one shell.", 4,
    "shell/Workspace.tsx", ["Workspace"], "WorkspaceShell", { tags: ["AppShell", "navigation", "tabs", "commands"],
      constraints: ["Applications reuse Workspace; app navigation and views come from their AppUI declaration.",
        "Open this full-window preview separately; its shell owns routes and saved layout."] }),
];

/** Public nonvisual API, classified explicitly rather than pretending to be UI. */
export const api = [
  "t", "language", "languages", "setLanguage", "register", "cn", "defineStatuses", "submissionStatuses", "parseInline",
  "defineEntity", "columnsFor", "recordSchema", "applyFilters", "valueOf", "useWorkspace", "useViewCall", "useViewVisible", "useUnsavedChanges", "notify",
  "routeKey", "routeToHash", "routeFromHash", "layout", "canvasNodeHeight", "canvasNodeWidth", "canvasPlacement", "validateCanvasConnection",
  "flowStates", "useChartData", "groupDomain", "aggregateQuery", "aggregateValues", "columnOf",
  "groupable", "measurable", "entityFrom", "setCurrency", "humanizeKernelError",
];
