import type { CatalogEntry } from "@platform/catalog";

// Meaning is maintained by the UI owner. Props remain the actual exported types;
// this file never imports the preview bundle into application code.
const asset = (id: string, name: string, summary: string, layer: CatalogEntry["layer"], source: string,
  exports: string[], example: string, extra: Partial<CatalogEntry> = {}): CatalogEntry => ({
  id, owner: "@platform/ui", name, summary, layer, source: `web/packages/ui/src/${source}`,
  exports, example, authority: "api", maturity: "recommended", scope: "platform", uses: ["code"], tags: [], ...extra,
});

export const entries: CatalogEntry[] = [
 asset("ui/record-comments","Record discussion","Present original persisted comments and a caller-owned draft whose confirmation belongs to the host.",3,"records/RecordComments.tsx",["RecordComments"],"RecordCommentsExample",{type:"RecordCommentsProps",tags:["comments","record","draft","collaboration"],dependencies:["ui/button"],constraints:["The caller owns authorization, the original bounded comment window, total and persistence. Unknown totals remain explicit; the presenter never invents authors, timestamps, comments or confirmations."]}),
 asset("ui/record-uploader","Record attachment uploader","Select a real local file and explicitly upload it through the caller's confirmed-record attachment path.",3,"records/RecordUploader.tsx",["RecordUploader"],"RecordUploaderExample",{type:"RecordUploaderProps",tags:["files","upload","record","attachment"],dependencies:["ui/file-picker","ui/button"],constraints:["The caller owns the actual File, bytes upload, attach decision and confirmed metadata. Refusal preserves the selected file; this control reports no simulated progress or local filename as a confirmed attachment."]}),
 asset("ui/media-preview","Authorized raster preview","Decode original attachment bytes and retain their confirmed identity and actual metadata.",3,"records/MediaPreview.tsx",["MediaPreview"],"MediaPreviewExample",{type:"AttachmentPreviewProps",tags:["media","image","bytes","attachment"],dependencies:["ui/button"],constraints:["The caller supplies authorized bytes and confirmed attachment metadata. Only PNG, JPEG, GIF and WebP with bounded matching dimensions render inline; other formats keep metadata and downloads. Object URLs retire with bytes, scope or unmount."]}),
 asset("ui/pdf-viewer","Authorized PDF pages","Render actual PDF pages from authorized attachment bytes with caller-owned original page state.",3,"records/PdfViewer.tsx",["PdfViewer"],"PdfViewerExample",{type:"PdfViewerProps",tags:["pdf","pages","bytes","attachment"],dependencies:["ui/button","ui/input"],constraints:["The caller owns attachment authorization and the original page string. The lazy renderer uses bundled PDF.js, its same-version worker and fixed font assets; actual page and pixel budgets apply. PDF-provided URLs, scripts, forms, XFA and annotations are not activated."]}),
 asset("ui/indexed-choices","Steps and tabs","Select original string identities through ordered steps or semantic tabs with independently keyed labels.",1,"components/IndexedChoices.tsx",["StepSelector","TabSelector"],"IndexedChoicesExample",{tags:["choice","steps","tabs","index"],dependencies:["ui/button"],constraints:["The caller owns current state and optional writes. Duplicate labels retain distinct values; empty or unmatched state has no current choice. Step position makes no business workflow claim and tabs do not invent panel content."]}),
 asset("ui/tag-counts","Counted tag groups","Present complete original scalar counts as fixed-size tags with optional caller-owned group selection.",2,"components/TagCounts.tsx",["TagCounts"],"TagCountsExample",{tags:["tags","count","groups","filter"],dependencies:["ui/button","ui/term-counts"],constraints:["The caller owns authorized complete counts and filter writes. Null, empty and literal groups retain their original identities; missing groups cannot be written to text filters. No array expansion, string coercion or record reads happen here."]}),
 asset("ui/record-comparison","Confirmed record comparison","Compare two to four complete original records with typed differences, stable identities and original field formatting.",3,"records/RecordComparison.tsx",["RecordComparison"],"RecordComparisonExample",{tags:["record","comparison","identity","properties"],constraints:["The caller confirms every original record and supplies permission-filtered metadata. Values are compared by their declared scalar types; presentation performs no reads or writes and never truncates the selection."]}),
 asset("ui/histogram","Numeric distribution","Present complete caller-owned bins with exact bounds, counts and missing-value disclosure.",2,"components/Histogram.tsx",["Histogram","validHistogram"],"HistogramExample",{tags:["histogram","distribution","bins"],constraints:["The caller owns authorized complete bins. The control validates intervals and counts without re-binning, and never writes records."]}),
 asset("ui/record-card","Confirmed record summary","Present an original confirmed record through shared card and field formatters with explicit identity and properties.",3,"records/RecordCard.tsx",["RecordCard"],"RecordCardExample",{tags:["record","card","identity","properties"],dependencies:["ui/entity-card"],constraints:["The caller confirms original record access and supplies permission-filtered metadata. Titles and properties remain in their original field owners; the card performs no reads or writes."]}),
 asset("ui/record-sparkline","Original scalar and record sparkline","Present a caller-owned scalar and original ordered record values without inventing time or replacing missing data.",3,"records/RecordSparkline.tsx",["RecordSparkline","recordSparklinePoints"],"RecordSparklineExample",{tags:["sparkline","scalar","records","window"],constraints:["The caller owns scalar precision, authorized window and field metadata. Missing values break the line; points retain stable IDs and never read or write records."]}),
 asset("ui/count-treemap","Authorized proportional treemap","Partition caller-owned complete group counts into proportional rectangles with independently accessible groups.",3,"charts/CountTreemap.tsx",["CountTreemap","treemapRectangles"],"CountTreemapExample",{tags:["treemap","area","count","filter"],constraints:["The caller owns authorized complete counts and filter writes. Layout never inflates small groups, reads records or writes business data."]}),
 asset("ui/term-counts","Counted term labels","Present complete caller-owned counts as bounded frequency-scaled literal labels.",2,"components/TermCounts.tsx",["TermCounts"],"TermCountsExample",{type:"TermCount",tags:["terms","count","labels"],constraints:["The caller owns authorized complete counts and stable order. Empty text and null remain distinct; this control performs no queries or mutations."]}),
 asset("ui/search-input","Scoped search input","Edit caller-owned search text and show the actual readable object scope.",1,"components/SearchInput.tsx",["SearchInput"],"SearchInputExample",{tags:["search","input","scope"],dependencies:["ui/input"],constraints:["The caller owns text, object scope and authorized reads. This control performs no queries and does not promise global ontology search."]}),
 asset("layout/spacer","Controlled blank space","Reserve one caller-owned blank region independently of container gaps.",2,"layout/LayoutRegion.tsx",["Spacer"],"SpacerExample",{tags:["spacer","spacing","layout"],constraints:["The document owner validates finite sizes against the original layout budget. Zero is preserved; the region is hidden from accessibility and is not a focus target."]}),
 asset("ui/separator","Semantic separator","Separate operator groups with an optional literal label and accessible identity.",1,"primitives/separator.tsx",["Separator"],"SeparatorExample",{tags:["separator","divider","layout"],constraints:["The caller owns the label and visibility. The separator is horizontal and noninteractive, without data reads or text evaluation."]}),
 asset("ui/notice","Semantic notice","Present caller-owned plain text with an accessible semantic tone.",1,"components/Notice.tsx",["Notice"],"NoticeExample",{tags:["alert","callout","notice"],constraints:["The caller owns the condition and message. This component performs no queries, template execution or notification delivery."]}),
 asset("ui/datetime-input","Offset datetime input","Edit caller-owned timestamp text without browser timezone conversion or precision truncation.",1,"components/DateTimeInput.tsx",["DateTimeInput","validTimestamp","validTimestampOffset","timestampParts","withTimestampOffset"],"DateTimeInputExample",{tags:["datetime","offset","input"],constraints:["The caller owns original text and query conditions. UTC offset is explicit; seconds and up to nine fractional digits are retained, and invalid drafts remain repairable."]}),
  asset("ui/date-input","Civil date input","Edit original business date text with a native picker and explicit invalid draft repair.",1,"components/DateInput.tsx",["DateInput","validCivilDate"],"DateInputExample",{tags:["date","civil","input"],constraints:["The caller owns the original date text and query conditions. Invalid drafts remain visible; no local timezone or timestamp conversion is applied."]}),
  asset("ui/multiple-choice-input","Set choice input","Present caller-owned string selections through shared toggles without dropping unmatched values.",2,"components/MultipleChoiceInput.tsx",["MultipleChoiceInput"],"MultipleChoiceInputExample",{tags:["choice","multiple","string-set"],dependencies:["ui/toggles","ui/button"],constraints:["The caller owns the original string set and query conditions. Toggles change one declared choice and preserve unmatched selections.","Optional whole-set clearing removes all selected values, including unmatched values."]}),
  asset("ui/choice-input","Single choice input","Present caller-owned static choices as a select, radio group, segmented control, steps or tabs.",1,"components/ChoiceInput.tsx",["ChoiceInput","validChoiceInput"],"ChoiceInputExample",{tags:["choice","radio","select","segments","steps","tabs"],dependencies:["ui/indexed-choices"],constraints:["The caller owns the original string state, options and query conditions. Empty or unmatched values are preserved until explicit selection.","Steps and tabs use canonical index string values and a same-length label list; duplicate labels remain separate choices. An absent write callback renders them read-only."]}),
  asset("ui/record-leaderboard","Authorized record leaderboard","Present original host-ranked Top-N records and emit their original identities.",3,"records/RecordLeaderboard.tsx",["RecordLeaderboard","leaderboardRows"],"RecordLeaderboardExample",{tags:["leaderboard","rank","records"],constraints:["The caller owns the ranked query and record authorization. This component does not sort an unranked window or write records."]}),
  asset("ui/summary-statistics","Authorized summary statistics","Present five measures from one complete authorized aggregate answer.",3,"components/SummaryStatistics.tsx",["SummaryStatistics"],"SummaryStatisticsExample",{tags:["statistics","aggregate","summary"],constraints:["The caller owns the original five-measure answer. Counts remain exact; missing numeric measures remain empty."]}),
  asset("ui/range-input","Exact decimal range input","Edit two original text drafts on an exact decimal tick grid and clear them atomically.",3,"components/RangeInput.tsx",["RangeInput","rangeGrid","rangeDrafts"],"RangeInputExample",{tags:["range","input","decimal"],constraints:["The caller owns the original state pair and query conditions. Empty or invalid drafts are never replaced by bounds."]}),
  asset("ui/gauge","Authorized numeric gauge","Display the original finite numeric aggregate with a bounded arc and warning threshold.",3,"components/Gauge.tsx",["Gauge","gaugeModel"],"GaugeExample",{tags:["gauge","aggregate","number"],constraints:["The caller owns the original numeric result and complete set. The gauge does not substitute zero for empty or denied values."]}),
  asset("ui/progress","Exact decimal progress","Show exact authorized scalar values with a bounded progress ratio.",3,"components/Progress.tsx",["Progress","progressRatio"],"ProgressExample",{tags:["progress","decimal","count"],constraints:["The caller owns the original scalars and complete-set count. Invalid values never become zero or a denominator of one."]}),
  asset("ui/record-gantt","Authorized task Gantt","Present original ordered business intervals on an explicit fixed UTC range.",3,"records/RecordGantt.tsx",["RecordGantt","recordGanttRows","ganttRange"],"RecordGanttExample",{tags:["gantt","schedule","window"],constraints:["The caller owns the authorized window; this presentation does not reorder records, filter by the viewport, or write dates."]}),
  asset("ui/record-calendar","Authorized record calendar","Browse original business dates by month and day and select original records.",3,"records/RecordCalendar.tsx",["RecordCalendar","calendarRecords","adjacentCalendarMonth","validCalendarMonth"],"RecordCalendarExample",{tags:["calendar","date","records","selection"],constraints:["The caller owns the bounded window and record authorization; the calendar never writes dates or reads another collection."]}),
  asset("ui/record-events","Authorized event list","Present ordered original business events with explicit time and severity tones.",3,"records/RecordEvents.tsx",["RecordEvents","recordEventRows"],"RecordEventsExample",{tags:["events","timeline","window"],constraints:["The caller owns the authorized window and business time; the list does not create events or read another collection."]}),
  asset("ui/count-matrix","Complete typed count matrix","Present original complete counts with distinct axis identities and optional controlled heatmap selection.",3,"charts/CountMatrix.tsx",["CountMatrix","countMatrix"],"CountMatrixExample",{tags:["heatmap","matrix","count","filter"],constraints:["The caller owns complete authorized counts and filter writes. Missing, empty and literal values remain distinct; no grouping, truncation or record reads happen here."]}),
  asset("ui/record-scatter","Authorized record scatter plot","Plot original numeric record coordinates and retain independently selectable stable identities.",3,"records/RecordScatter.tsx",["RecordScatter","scatterPoints"],"RecordScatterExample",{tags:["scatter","records","selection"],constraints:["The caller owns the ordered authorized window and confirmation. Missing coordinates are excluded; invalid values refuse the plot, and overlapping points remain separate records."]}),
  asset("ui/record-chart","Ordered record chart","Plot original authorized records without merging equal axis labels or reading another collection.",3,"records/RecordChart.tsx",["RecordChart","recordChartSpec"],"RecordChartExample",{tags:["records","chart","window"],dependencies:["ui/chart"],constraints:["The caller owns the ordered window, field permissions and point budget; this chart performs no reads or writes."]}),
  asset("ui/record-cards","Record cards","Select original records from a caller-owned grid or list window.",3,"records/RecordCards.tsx",["RecordCards"],"RecordCardsExample",{tags:["records","cards","selection"],dependencies:["ui/entity-card","ui/button"],constraints:["Card fields come from permission-filtered metadata; the caller owns reads, selection and navigation."]}),
  asset("ui/collection-title","Collection title","Show a declared collection name and its caller-owned complete count.",2,"components/CollectionTitle.tsx",["CollectionTitle"],"CollectionTitles",{tags:["title","count"],states:["Loading","Error","Ready"],constraints:["The caller owns the authorized complete count and clears obsolete values."]}),
  asset("ui/facet-choices","Facet choices","Choose several authorized options with complete source counts and an optional histogram.",2,"fields/FacetChoices.tsx",["FacetChoices"],"FacetChoicesExample",{tags:["filter","facets","selection"],constraints:["The caller owns authorized options, counts and typed selected values."]}),
  asset("ui/command-menu", "Context commands", "Use the same commands from a pointer context menu or an explicit keyboard and touch trigger.", 2,
    "components/CommandMenu.tsx", ["CommandMenu"], "ContextCommands", {tags:["menu","commands","keyboard"],dependencies:["ui/button"],constraints:["The caller owns commands and disabled states; the menu does not perform business operations itself."]}),
  asset("ui/layout-region", "Sized layout regions", "Arrange weighted regions with bounded dimensions and local scrolling, stacking columns in narrow containers.", 2,
    "layout/LayoutRegion.tsx", ["LayoutRegion", "LayoutStack"], "SizedLayouts", {tags:["layout","sizing","scroll"], constraints:["The caller supplies validated dimensions and parent axes; layout grants no business access."]}),
  asset("foundation/semantic-tokens", "Semantic tokens", "Use shared surface, text, focus and status tokens across themes.", 0,
    "styles.css", [], "Tokens", { authority: "specification", uses: ["reference"], tags: ["color", "theme", "density"],
      constraints: ["Use semantic tokens instead of assigning domain meaning to raw colors."] }),
  asset("ui/virtual-stack", "Virtual item list", "Render measured rows by stable identity and retain the focused item.", 2,
    "layout/VirtualStack.tsx", ["VirtualStack"], "VirtualItems", { tags: ["virtual", "list", "layout"], constraints: ["The caller owns data reads and item state; offscreen local inputs are disposed."] }),
  asset("ui/flow-layout", "Flow layout and toolbar", "Wrap presentation items and navigate toolbar buttons with arrow keys.", 2,
    "layout/FlowLayout.tsx", ["FlowLayout"], "FlowLayouts", { tags: ["layout", "toolbar"], dependencies: ["ui/button"] }),
  asset("ui/content-tabs", "Content tabs", "Switch stable named panels with keyboard navigation and retain visited content.", 2,
    "layout/ContentTabs.tsx", ["ContentTabs"], "ContentTabsExample", { tags: ["tabs", "layout", "state"], dependencies: ["ui/button"] }),
  asset("ui/button", "Button", "One action control with primary, quiet, destructive, link and row variants.", 1,
    "primitives/button.tsx", ["Button"], "Buttons", { type: "ButtonProps", tags: ["action", "variants"],
      states: ["Enabled", "Disabled", "Keyboard focus"], snippet: 'import { Button } from "@platform/ui";\n<Button variant="primary" onClick={save}>Save</Button>' }),
  asset("ui/metal-button", "Metal button", "Tactile metallic and liquid glass styled buttons for prominent actions.", 1,
    "primitives/metalButton.tsx", ["MetalButton", "LiquidButton"], "MetalButtons", {
      tags: ["button", "metal", "tactile", "liquid", "variants"],
      states: ["Pressed", "Hover", "Touch"],
      snippet: 'import { MetalButton, LiquidButton } from "@platform/ui";\n<MetalButton variant="gold">Confirm</MetalButton>',
    }),
  asset("ui/retro-button", "Retro button", "Tactile mechanical keycap buttons styled after industrial equipment.", 1,
    "primitives/retroButton.tsx", ["RetroButton"], "RetroButtons", {
      tags: ["button", "retro", "tactile", "keycap", "variants"],
      states: ["Enabled", "Pressed", "Disabled", "Keyboard focus"],
      maturity: "experimental",
      snippet: 'import { RetroButton } from "@platform/ui";\n<RetroButton variant="default">RUN</RetroButton>',
    }),
  asset("ui/input", "Input controls", "Text, select and multiline controls for explicit labelled values.", 1,
    "primitives/input.tsx", ["Input", "Select", "Textarea"], "Inputs", { tags: ["text", "input", "select"], states: ["Enabled", "Disabled", "Invalid"] }),
  asset("ui/switch","Boolean switch","Toggle one caller-owned boolean with explicit checked and disabled states.",1,"primitives/controls.tsx",["Switch"],"SwitchExample",{tags:["switch","boolean","input"],states:["Checked","Unchecked","Disabled"],constraints:["The caller owns the boolean and its effects; this control does not coerce unrelated values or write records."]}),
  asset("ui/checkbox", "Checkbox", "A labelled boolean choice with an explicit disabled state.", 1,
    "primitives/controls.tsx", ["Checkbox"], "Checkboxes", { states: ["Checked", "Unchecked", "Disabled"] }),
  asset("ui/panels", "Cards and panels", "Group related content with a shared heading, description and action area.", 2,
    "primitives/card.tsx", ["Card", "Panel"], "Panels", { tags: ["inspector", "grouping"], dependencies: ["ui/button", "foundation/semantic-tokens"] }),
  asset("ui/editor-workbench", "Editor workbench", "Arrange a library, canvas and inspector with keyboard and pointer pane resizing.", 2,
    "layout/EditorWorkbench.tsx", ["EditorWorkbench"], "EditorPanels", { tags: ["editor", "layout", "inspector", "resize"], dependencies: ["ui/panels", "foundation/semantic-tokens"] }),
  asset("ui/form", "Form submission", "Submit an ad hoc form on Enter without reloading the page.", 2,
    "primitives/controls.tsx", ["Form"], "Forms", { dependencies: ["ui/input", "ui/button"] }),
  asset("ui/disclosure", "Disclosure", "Reveal supporting details while keeping the summary visible.", 2,
    "primitives/controls.tsx", ["Disclosure"], "Disclosures", { states: ["Expanded", "Collapsed"] }),
  asset("ui/file-picker", "File picker", "Pick a local file through a shared button; the caller owns upload.", 2,
    "primitives/controls.tsx", ["FilePicker"], "FilePicking", { dependencies: ["ui/button"], constraints: ["Picking a file does not upload or publish it."] }),
  asset("ui/toggles", "Multiple choices", "Switch several named choices on or off without a custom control.", 2,
    "primitives/controls.tsx", ["Toggles"], "Choices", { tags: ["tags", "options"] }),
  asset("ui/tree", "Hierarchy selection", "Select a row from a small hierarchy of labelled records.", 2,
    "primitives/controls.tsx", ["Tree"], "Hierarchy", { tags: ["tree", "parents"], maturity: "experimental",
      constraints: ["Rows are always expanded; collapse and full tree keyboard navigation are not implemented."] }),
  asset("ui/dialog", "Modal dialog", "Ask for a bounded decision with focus trapping and a labelled title.", 2,
    "primitives/dialog.tsx", ["Dialog"], "Dialogs", { states: ["Open", "Closed"], dependencies: ["ui/button"] }),
  asset("ui/sheet", "Detail sheet", "Inspect or edit details while keeping the underlying task in view.", 2,
    "primitives/sheet.tsx", ["Sheet"], "Sheets", { tags: ["inspector", "details"], states: ["Open", "Closed"] }),
  asset("ui/status", "Semantic status tags", "Map actual domain or kernel states to a label and one of five tones.", 2,
    "components/StatusTag.tsx", ["StatusTag", "Tag"], "Statuses", { tags: ["feedback", "status"], type: "StatusRegistry",
      dependencies: ["foundation/semantic-tokens"], constraints: ["Use exact registry keys; unknown states fall back to a neutral label."] }),
  asset("ui/data-table", "Data table", "Browse, sort and edit typed rows in a shared virtualized table.", 2,
    "components/DataTable.tsx", ["DataTable"], "Tables", { type: "DataTableProps", tags: ["table", "rows", "sorting"],
      states: ["Loading", "Empty", "Selected", "Editing"], dependencies: ["ui/input", "ui/field-types"] }),
  asset("ui/markdown", "Markdown display and editor", "Read formatted content or edit its source with a shared preview.", 2,
    "components/Markdown.tsx", ["Markdown", "MarkdownEditor"], "MarkdownContent", { tags: ["knowledge", "content"] }),
  asset("ui/page-header", "Page header", "Give a task its title, description and visible actions.", 2,
    "components/PageHeader.tsx", ["PageHeader"], "Headers", { dependencies: ["ui/button"] }),
  asset("ui/field-types", "Typed field vocabulary", "One field type owns display, editing, validation, sorting and filtering.", 3,
    "fields/types.tsx", ["field.text", "field.longText", "field.markdown", "field.number", "field.currency", "field.percent", "field.checkbox", "field.date", "field.datetime", "field.duration", "field.singleSelect", "field.multiSelect", "field.tags", "field.email", "field.url", "field.phone", "field.barcode", "field.rating", "field.attachment", "field.link", "field.formula", "field.timestamp"], "Fields", { type: "FieldType", tags: ["text", "longText", "markdown", "number", "currency", "percent", "checkbox", "date", "datetime", "duration", "singleSelect", "multiSelect", "tags", "email", "url", "phone", "barcode", "rating", "attachment", "link", "formula", "timestamp"],
      constraints: ["Reference links need a Workspace; attachment upload needs an explicit caller implementation."] }),
  asset("ui/entity-form", "Schema form", "Render labelled editors and validate an ad hoc schema before submission.", 3,
    "components/EntityForm.tsx", ["EntityForm"], "SchemaForms", { tags: ["form", "schema"], states: ["Invalid", "Submitting"], dependencies: ["ui/field-types", "ui/button"] }),
  asset("ui/record-form", "Entity form", "Edit declared entity fields using their shared validators and editors.", 3,
    "components/EntityForm.tsx", ["RecordForm"], "RecordForms", { tags: ["form", "entity"], states: ["Invalid", "Submitting"],
      dependencies: ["ui/field-types", "ui/button"], constraints: ["The caller owns persistence, authorization and conflict handling."] }),
  asset("ui/filter-bar", "Typed filters", "Build filters from the entity's declared fields and operators.", 3,
    "fields/entity.tsx", ["FilterBar"], "Filters", { type: "Filter", dependencies: ["ui/field-types", "ui/button"] }),
  asset("ui/entity-card", "Record summary", "Present a record's title, status and labelled properties.", 3,
    "components/EntityCard.tsx", ["EntityCard", "PropertyList"], "RecordSummaries", { tags: ["record", "properties"], dependencies: ["ui/status"] }),
  asset("ui/button-group","Button group","Activate stable scoped presentation controls through caller-owned bindings.",2,"components/ButtonGroup.tsx",["ButtonGroup"],"ButtonGroups",{tags:["buttons","toolbar"],dependencies:["ui/button","ui/flow-layout"],constraints:["Each control has a stable identity; the caller owns its binding, permissions and execution."]}),
  asset("ui/notifications", "Notifications", "Show unread changes and let the caller mark a notification as read.", 3,
    "components/NotificationList.tsx", ["NotificationList"], "Notifications", { type: "NotificationItem", states: ["Empty", "Read", "Unread"] }),
  asset("ui/record-list", "Record list", "Browse a scoped entity source with search, sort and paging.", 3,
"records/Records.tsx", ["RecordList"], "RecordLists", { type: "RecordSource", states: ["Loading", "Empty", "Error", "Selected", "Staged edits"], constraints:["An optional RecordEditPort supplies authorized displayed fields and the original revision-bound submit callback. Failed edits remain staged; the caller owns permissions and execution.","RecordColumnPresentation configures visible column titles, widths and typed formats without replacing field metadata or permissions. Hiding search retains the caller query.","RecordSelectionPort controls bounded selection in the current window; the caller confirms record permissions and owns pending, failure and cleanup. Window selection is not a complete matching set."], dependencies: ["ui/data-table", "ui/filter-bar"] }),
  asset("ui/record-kanban", "Authorized lifecycle board", "Select bounded records in their original lifecycle lanes and emit declared move commands.", 3,
    "records/RecordKanban.tsx", ["RecordKanban"], "RecordKanbans", {tags:["kanban","work","records"],states:["Empty","Selected","Invalid"],dependencies:["ui/entity-card","ui/button","ui/input"],constraints:["The caller supplies authorized records, lifecycle states and actions. This component does not write state."]}),
  asset("ui/record-timeline", "Authorized record timeline", "Display a bounded record window as time points or intervals, grouped by an original resource field.", 3,
    "records/RecordTimeline.tsx", ["RecordTimeline"], "RecordTimelines", { type:"TimelineFields",tags:["timeline","scheduling","records"],states:["Empty","Selected","Invalid"],dependencies:["ui/button"], constraints:["The caller supplies authorized records and selection. This component does not schedule or write records."] }),
  asset("ui/record-page", "Record detail and history", "Read a record's declared fields, related work and recorded changes.", 3,
    "records/Records.tsx", ["RecordPage", "RecordLinks", "RecordHistory"], "RecordDetails", { type: "RecordView", states: ["Loading", "Error", "Ready"],
      dependencies: ["ui/entity-card", "ui/lifecycle", "ui/tasks"], constraints: ["Visibility and allowed actions come from the scoped source and caller."] }),
  asset("ui/record-lookup", "Record lookup", "Search a caller's scoped source to choose a reference by record ID.", 3,
    "records/RecordLookup.tsx", ["RecordLookup"], "RecordLookups", { type: "RecordSource", states: ["Loading", "Empty", "Error", "Selected"], dependencies: ["ui/input"] }),
  asset("ui/tasks", "Tasks and inbox", "Present assigned work with the answers and actions supplied by its owner.", 3,
    "records/Records.tsx", ["Tasks", "Inbox"], "TaskInbox", { type: "InboxTask", tags: ["approval", "work"], states: ["Empty", "Pending"],
      dependencies: ["ui/button", "ui/status"], constraints: ["An inbox preview is not an approval or permission engine."] }),
  asset("ui/lifecycle", "Lifecycle status bar", "Display declared record states and caller-allowed transitions.", 3,
    "records/Records.tsx", ["StatusBar", "RecordStatus"], "Lifecycle", { type: "Lifecycle", dependencies: ["ui/button"],
      constraints: ["Only the canonical action owner may authorize and apply a transition."] }),
  asset("ui/chart", "Chart", "Render a visualization spec using inline values or a scoped aggregate source.", 3,
    "charts/Chart.tsx", ["Chart"], "Charts", { type: "ChartSpec", tags: ["chart", "kpi", "aggregate"], states: ["Loading", "Empty", "Error", "Ready"] }),
  asset("ui/pivot", "Pivot table", "Compare aggregate groups with totals and explicit drill-down.", 3,
    "charts/Pivot.tsx", ["Pivot"], "Pivots", { type: "ChartSource", uses:["code","widget"],widgets:["pivot"], tags: ["report", "aggregate"], states: ["Loading", "Empty", "Error", "Ready"] }),
  asset("ui/graph", "Read-only graph", "Observe relationships and execution paths through the shared canvas.", 3,
    "graph/Graph.tsx", ["Graph"], "Graphs", { type: "GraphNode", dependencies: ["ui/block-canvas"], states: ["Selected"] }),
  asset("ui/block-canvas", "Typed block canvas", "Compose nodes through typed ports with one shared graph interaction model.", 3,
    "graph/BlockCanvas.tsx", ["BlockCanvas", "NodeCanvas"], "Blocks", { type: "BlockCanvasProps", tags: ["flow", "node", "canvas"],
      states: ["Read only", "Editing", "Selected"], constraints: ["The canvas owns interaction; its caller owns graph semantics, validation and persistence."] }),
  asset("ui/flow", "Flow observation", "Inspect a native flow's graph, waiting steps and decision trace.", 3,
    "flows/FlowView.tsx", ["FlowView", "FlowGraph", "FlowReleaseBinding"], "FlowObservation", { type: "FlowInstanceData", tags: ["flow", "trace", "release", "version"], dependencies: ["ui/graph", "ui/status"] }),
  asset("ui/record-workspace", "Record list and detail", "Keep record browsing and focused detail in one responsive task frame.", 3,
    "records/RecordWorkspace.tsx", ["RecordWorkspace"], "MasterDetail", { tags: ["master-detail", "record", "workspace"],
      dependencies: ["ui/record-list", "ui/record-page", "ui/page-header"], constraints: ["Pass a scoped RecordSource; this layout does not define a business entity."] }),
  asset("pattern/workspace", "App Shell / Workspace", "Compose app navigation, routed tabs, commands and session context in one shell.", 4,
    "shell/Workspace.tsx", ["Workspace"], "WorkspaceShell", { tags: ["AppShell", "navigation", "tabs", "commands"],
      constraints: ["Applications reuse Workspace; app navigation and views come from their AppUI declaration.",
        "Open this full-window preview separately; its shell owns routes and saved layout."] }),
];

/** Public nonvisual API, classified explicitly rather than pretending to be UI. */
export const api = [
  "t", "language", "languages", "setLanguage", "register", "cn", "defineStatuses", "submissionStatuses", "parseInline",
  "defineEntity", "columnsFor", "recordSchema", "applyFilters", "valueOf", "useWorkspace", "useViewCall", "useViewVisible", "useUnsavedChanges", "notify",
  "routeKey", "routeToHash", "routeFromHash", "layout", "canvasNodeHeight", "canvasNodeWidth", "canvasPlacement", "validateCanvasConnection",
  "flowStates", "useChartData", "groupDomain", "aggregateQuery", "aggregateValues", "columnOf",
  "groupable", "measurable", "entityFrom", "setCurrency", "humanizeKernelError",
];
