import {registerHooks} from "node:module";
registerHooks({resolve(s,c,next){try{return next(s,c)}catch(e){if(s.startsWith(".")&&!s.endsWith(".ts"))return next(`${s}.ts`,c);throw e;}}});
import assert from "node:assert/strict";
import test from "node:test";
const {createRecordActionSubmitter}=await import("../record-actions.ts");
const target={type:"sample.item",id:"A"};
function fixture(){let active=true;const calls=[],host={client:{connection:{tenant:"T",principal:"member"},authorities:{outbox:[]}},can:()=>true,decide:async(...args)=>{calls.push(args);return true},resend:async()=>{calls.push("resend");host.client.authorities.outbox[0].state="SUBMISSION_STATE_CONFIRMED";}};return{host,calls,submit:createRecordActionSubmitter(host,()=>active),retire:()=>active=false};}
test("each row retains the original target, full typed payload and opened revision",async()=>{const f=fixture();assert.equal((await f.submit("sample.item.adjust",target,7,{next:3,reason:"original"})).accepted,true);assert.deepEqual(f.calls[0].slice(0,3),["sample.item.adjust",target,{next:3,reason:"original"}]);assert.equal(f.calls[0][3].expectedRevision,7);f.retire();await assert.rejects(()=>f.submit("sample.item.adjust",target,7,{next:3}),/ended/);assert.equal(f.calls.length,1);});
test("an unanswered row retries its original key; altered payload/revision and other views cannot create another decision",async()=>{const f=fixture();f.host.decide=async(schema,target,payload,options)=>{f.calls.push(schema);f.host.client.authorities.outbox.push({state:"SUBMISSION_STATE_UNKNOWN",submission:{tenantId:"T",principalId:"member",target,schema:{name:schema},expectedRevision:options.expectedRevision,idempotencyKey:"ORIGINAL"}});return false;};assert.equal((await f.submit("sample.item.adjust",target,7,{next:3})).accepted,false);await assert.rejects(()=>f.submit("sample.item.adjust",target,7,{next:4}),/unanswered/);await assert.rejects(()=>f.submit("sample.item.adjust",target,8,{next:3}),/unanswered/);await assert.rejects(()=>createRecordActionSubmitter(f.host,()=>true)("sample.item.adjust",target,7,{next:3}),/unanswered/);assert.equal((await f.submit("sample.item.adjust",target,7,{next:3})).accepted,true);assert.deepEqual(f.calls,["sample.item.adjust","resend"]);assert.equal(f.host.client.authorities.outbox[0].submission.idempotencyKey,"ORIGINAL");});
test("original permission and principal changes retire a submitter; simultaneous views reserve a row before authority refresh",async()=>{const f=fixture();let release;f.host.decide=async()=>new Promise(r=>release=r);const first=f.submit("sample.item.adjust",target,7,{next:3});await assert.rejects(()=>createRecordActionSubmitter(f.host,()=>true)("sample.item.adjust",target,7,{next:3}),/already being/);release(true);await first;f.host.can=()=>false;await assert.rejects(()=>f.submit("sample.item.adjust",target,7,{next:3}),/unavailable/);f.host.can=()=>true;f.host.client.connection.principal="other";await assert.rejects(()=>f.submit("sample.item.adjust",target,7,{next:3}),/ended/);});
