import {registerHooks} from "node:module";
registerHooks({resolve(specifier,context,next){try{return next(specifier,context)}catch(error){if(specifier.startsWith("./")&&!specifier.endsWith(".ts"))return next(`${specifier}.ts`,context);throw error;}}});
import assert from "node:assert/strict";
import test from "node:test";
const {createRecordCollaboration}=await import("./service.ts");
const file=new File(["data"],"real.txt",{type:"text/plain"});
const attachment={id:"FILE",revision:1,created:{by:"M",at:"2026-10-03T00:00:00Z"},changed:{by:"M",at:"2026-10-03T00:00:00Z"},name:"real.txt",size:4,contentType:"text/plain",target:"sample.note/A",by:"M"};
function fixture(){const calls=[],host={me:{principalId:"M"},can:()=>true,resend:async()=>{},source:{get:async()=>({record:attachment})},client:{connection:{tenant:"TENANT",principal:"MEMBER"},authorities:{outbox:[]},upload:async(body,name)=>{calls.push({kind:"bytes",body,name});return{hash:"a".repeat(64),name,size:4,contentType:"text/plain"};},download:async()=>new Blob(["data"],{type:"text/plain"})},decide:async(schema,target,payload)=>{calls.push({kind:"decision",schema,target,payload});return true;}};let active=true;return {host,calls,retire:()=>active=false,service:createRecordCollaboration(host,{type:"sample.note",id:"A"},()=>active,prefix=>prefix==="FILE"?"FILE":"COMMENT")};}
test("comments use the original action and do not mistake refusal for confirmed posting",async()=>{const f=fixture();assert.equal(await f.service.addComment("literal <b>"),true);assert.equal(f.calls[0].schema,"platform.comment.add");assert.deepEqual(f.calls[0].payload,{target:"sample.note/A",text:"literal <b>"});f.host.decide=async()=>false;assert.equal(await f.service.addComment("kept"),false);f.retire();await assert.rejects(()=>f.service.addComment("late"),/scope/);});
test("uploads attach actual bytes with a stable confirmed file ID and reject wrong or archived metadata",async()=>{const f=fixture();f.host.source.get=async()=>{throw Error("Obsolete record read");};assert.equal(await f.service.upload(file),"FILE");assert.equal(f.calls[0].body,file);assert.equal(f.calls[1].schema,"files.file.attach");assert.equal(f.calls[1].payload.target,"sample.note/A");assert.equal(f.calls[1].payload.name,"real.txt");for(const patch of [{id:"OTHER"},{target:"sample.note/B"},{archived:true},{size:-1}]){f.host.source.get=async()=>({record:{...attachment,...patch}});await assert.rejects(()=>f.service.attachment("FILE"),/original record/);}});
test("a retired upload never attaches to a newly selected record and an already queued decision suppresses obsolete output",async()=>{let f=fixture();f.host.client.upload=async()=>{f.retire();return{hash:"a".repeat(64),name:"real.txt",size:4,contentType:"text/plain"};};await assert.rejects(()=>f.service.upload(file),/scope/);assert.equal(f.calls.length,0);f=fixture();f.host.decide=async(_schema,_target,payload)=>{assert.equal(payload.target,"sample.note/A");f.retire();return true;};assert.equal(await f.service.upload(file),undefined);});
test("attachment refusal and preview byte mismatches are explicit failures without fake metadata or outputs",async()=>{const f=fixture();f.host.decide=async(_schema,_target,_payload,options)=>{options.onRefused("Denied attachment");return false;};await assert.rejects(()=>f.service.upload(file),/Denied attachment/);await assert.rejects(()=>f.service.bytes(attachment,3),/budget/);f.host.client.download=async()=>new Blob(["wrong bytes"]);await assert.rejects(()=>f.service.bytes(attachment,100),/metadata/);f.host.source.get=async()=>({record:{...attachment,target:"sample.note/B"}});await assert.rejects(()=>f.service.attachment("FILE"),/original record/);});
function loseAnswer(f){let creates=0,resends=0;f.host.decide=async(schema,target,payload)=>{creates++;f.host.client.authorities.outbox.push({submission:{tenantId:"TENANT",principalId:"MEMBER",schema:{name:schema},target,idempotencyKey:`ORIGINAL-${creates}`,payload:btoa(JSON.stringify(payload))},state:"SUBMISSION_STATE_UNKNOWN"});return false;};f.host.resend=async()=>{resends++;for(const entry of f.host.client.authorities.outbox)entry.state="SUBMISSION_STATE_CONFIRMED";};return()=>({creates,resends});}
test("a comment with a lost answer retries its original outbox entry rather than creating another comment",async()=>{const f=fixture(),counts=loseAnswer(f);assert.equal(await f.service.addComment("literal draft"),false);assert.equal(await f.service.addComment("literal draft"),true);assert.deepEqual(counts(),{creates:1,resends:1});assert.equal(f.host.client.authorities.outbox[0].submission.idempotencyKey,"ORIGINAL-1");});
test("an attachment with a lost answer reuses its original bytes, file ID and submission key",async()=>{const f=fixture(),counts=loseAnswer(f);await assert.rejects(()=>f.service.upload(file),/not confirmed/);assert.equal(await f.service.upload(file),"FILE");assert.deepEqual(counts(),{creates:1,resends:1});assert.equal(f.calls.filter(call=>call.kind==="bytes").length,1);assert.equal(f.host.client.authorities.outbox[0].submission.target.id,"FILE");});
test("changed drafts, changed files and reopened views cannot silently recreate unanswered work",async()=>{const f=fixture(),counts=loseAnswer(f);assert.equal(await f.service.addComment("earlier draft"),false);await assert.rejects(()=>f.service.addComment("changed draft"),/unanswered/);const reopened=createRecordCollaboration(f.host,{type:"sample.note",id:"A"},()=>true,prefix=>`${prefix}-NEW`);await assert.rejects(()=>reopened.addComment("earlier draft"),/unanswered/);await assert.rejects(()=>f.service.upload(file),/not confirmed/);await assert.rejects(()=>f.service.upload(new File(["next"],"changed.txt",{type:"text/plain"})),/unanswered/);await assert.rejects(()=>reopened.upload(file),/unanswered/);assert.deepEqual(counts(),{creates:2,resends:0});assert.equal(f.calls.filter(call=>call.kind==="bytes").length,1);});

test("image regions retain exact author, hash, file revision and unanswered intent",async()=>{
 const f=fixture(),regions=[{id:"R",label:"Label",x:.1,y:.2,width:.3,height:.4}],hash="a".repeat(64);let row={...attachment,contentType:"image/png",hash};f.host.source.get=async()=>({record:row});
 let creates=0,resends=0;f.host.decide=async(schema,target,payload,options)=>{creates++;assert.equal(options.expectedRevision,1);f.host.client.authorities.outbox.push({submission:{tenantId:"TENANT",principalId:"MEMBER",schema:{name:schema},target,expectedRevision:1,payload:btoa(JSON.stringify(payload)),idempotencyKey:"REGION-ORIGINAL"},state:"SUBMISSION_STATE_UNKNOWN"});return false;};
 f.host.resend=async()=>{resends++;for(const e of f.host.client.authorities.outbox)e.state="SUBMISSION_STATE_CONFIRMED";};
 await assert.rejects(f.service.annotate("FILE",1,hash,regions),/draft is retained/);await assert.rejects(f.service.annotate("FILE",1,hash,[{...regions[0],label:"Changed"}]),/unanswered/);row={...row,revision:2};assert.equal(await f.service.annotate("FILE",1,hash,regions),true);assert.equal(creates,1);assert.equal(resends,1);
 await assert.rejects(f.service.annotate("FILE",1,hash,regions),/attachment changed/);row={...row,by:"other"};await assert.rejects(f.service.annotate("FILE",2,hash,regions),/original attachment author/);f.retire();await assert.rejects(f.service.annotate("FILE",2,hash,regions),/scope/);
});
