import {registerHooks} from 'node:module';import {readFileSync} from 'node:fs';import assert from 'node:assert/strict';import test from 'node:test';
registerHooks({resolve(s,c,next){try{return next(s,c)}catch(e){if(s.startsWith('./')||s.startsWith('../'))return next(s+'.ts',c);throw e;}}});
const {activeQueryPlans,queryInventoryBudget}=await import('./query-inventory.ts'),limits=JSON.parse(readFileSync(new URL('../../../../../capabilities/server/platform/pageui/widgets.json',import.meta.url))).runtime.query;
const fixture=()=>({sections:[{id:'table',widget:'table',collectionVariable:'set'},{id:'unused',widget:'table',collectionVariable:'spare'}],document:{uiProfile:'platform.page.v2.97',root:'root',nodes:{root:{kind:'rows',children:['table']},table:{kind:'widget',section:'table'},unused:{kind:'widget',section:'unused'}},unusedWidgets:[{node:'unused',parent:'root'}],queries:{read:{object:{app:'sample',kind:'object',name:'sample.note'},limit:100},inventory:{object:{app:'sample',kind:'object',name:'sample.note'},limit:100},orphan:{object:{app:'sample',kind:'object',name:'sample.note'},limit:100}},variables:{set:{type:'object-set',mode:'resource',scope:'page',source:{kind:'plan',query:'read'}},spare:{type:'object-set',mode:'resource',scope:'page',source:{kind:'plan',query:'inventory'}}}}});
test('only inventory-exclusive plans defer; restored, referenced, overlay and legacy declarations still count',()=>{
 let f=fixture();assert.deepEqual([...activeQueryPlans(f.document,f.sections,limits.inventoryUIProfile)].sort(),['orphan','read']);assert.equal(queryInventoryBudget(f.document,f.sections,limits).total,200);assert.equal(queryInventoryBudget(f.document,f.sections,limits).declared,300);
 for(const mutate of [f=>f.document.nodes.root.children.push('unused'),f=>f.document.nodes.root.visibleWhen='spare',f=>f.document.interface={version:1,outputs:{data:{variable:'spare',type:'object-set'}}},f=>f.document.overlays={drawer:{root:'unused',openVariable:'open'}},f=>f.document.uiProfile='platform.page.v2.96']){f=fixture();mutate(f);assert.equal(activeQueryPlans(f.document,f.sections,limits.inventoryUIProfile).has('inventory'),true);}
 f=fixture();f.document.queries.read.input='spare';assert.equal(activeQueryPlans(f.document,f.sections,limits.inventoryUIProfile).has('inventory'),true);
 f=fixture();f.document.nodes.root.title='spare';assert.equal(activeQueryPlans(f.document,f.sections,limits.inventoryUIProfile).has('inventory'),true);
});
test('deferred inventory keeps its own ceiling and mounting it restores the original active budget',()=>{
 const f=fixture();assert.equal(queryInventoryBudget(f.document,f.sections,{...limits,maxTotalLimit:200}).valid,true);f.document.nodes.root.children.push('unused');assert.equal(queryInventoryBudget(f.document,f.sections,{...limits,maxTotalLimit:200}).valid,false);f.document.nodes.root.children.pop();assert.equal(queryInventoryBudget(f.document,f.sections,{...limits,maxDeclaredTotalLimit:299}).valid,false);
});
