import {afterEach,expect,test} from "vitest";
import {cleanup,fireEvent,render,screen,within} from "@testing-library/react";
import {CountTreemap,treemapRectangles} from "./CountTreemap";
afterEach(cleanup);
test("treemap rectangles partition the whole area by true counts, retain independent labels and never inflate tiny groups",()=>{
 const terms=[{value:"A",count:64},{value:"B",count:24},{value:"",count:8},{value:null,count:3},{value:"constructor",count:1}],m=treemapRectangles(terms)!;expect(m.total).toBe(100n);expect(m.rectangles.map(r=>r.value)).toEqual(terms.map(t=>t.value));expect(m.rectangles.map(r=>r.share)).toEqual(["64.00%","24.00%","8.00%","3.00%","1.00%"]);
 let area=0;for(const r of m.rectangles){const a=r.width*r.height;area+=a;expect(a/(m.width*m.height)).toBeCloseTo(r.count/100,12);expect(r.x).toBeGreaterThanOrEqual(0);expect(r.y).toBeGreaterThanOrEqual(0);expect(r.x+r.width).toBeLessThanOrEqual(m.width+1e-9);expect(r.y+r.height).toBeLessThanOrEqual(m.height+1e-9);}expect(area).toBeCloseTo(m.width*m.height,8);
 for(let i=0;i<m.rectangles.length;i++)for(let j=i+1;j<m.rectangles.length;j++){const a=m.rectangles[i]!,b=m.rectangles[j]!,overlap=Math.max(0,Math.min(a.x+a.width,b.x+b.width)-Math.max(a.x,b.x))*Math.max(0,Math.min(a.y+a.height,b.y+b.height)-Math.max(a.y,b.y));expect(overlap).toBeCloseTo(0,8);}
 const skew=treemapRectangles([{value:"Huge",count:Number.MAX_SAFE_INTEGER},{value:"Tiny",count:1}])!;expect(skew.rectangles[1]!.width*skew.rectangles[1]!.height/(skew.width*skew.height)).toBeLessThan(1e-12);expect(skew.total).toBe(9007199254740992n);
});
test("empty groups have no fake total, ties keep host order, and duplicate or unsafe counts and invalid geometry are refused",()=>{
 expect(treemapRectangles([])?.total).toBe(0n);expect(treemapRectangles([])?.rectangles).toEqual([]);expect(treemapRectangles([{value:"B",count:1},{value:"A",count:1}])?.rectangles.map(r=>r.value)).toEqual(["B","A"]);for(const count of [0,-1,NaN,Infinity,1.5,Number.MAX_SAFE_INTEGER+1])expect(treemapRectangles([{value:"A",count}])).toBeUndefined();expect(treemapRectangles([{value:"A",count:1},{value:"A",count:2}])).toBeUndefined();expect(treemapRectangles([{value:"A",count:1}],0,400)).toBeUndefined();expect(treemapRectangles([{value:"A",count:1}],Infinity,400)).toBeUndefined();expect(treemapRectangles(Array.from({length:65},(_,i)=>({value:String(i),count:1})))).toBeUndefined();
});
test("geometry and accessible group entries use raw identities, refuse missing and disabled writes, and keep clearing empty results",()=>{
 let selected:unknown="none";const terms=[{value:"<b>literal</b>",count:9},{value:"constructor",count:1},{value:null,count:1}],select=(value?:string)=>{selected=value;},view=render(<CountTreemap terms={terms} label="Assets" onSelect={select}/>),plot=screen.getByRole("group",{name:"Assets"});const button=within(plot).getByRole("button",{name:/constructor/});fireEvent.keyDown(button,{key:"Enter"});expect(selected).toBe("constructor");expect(view.container.querySelector("b")).toBeNull();fireEvent.click(within(screen.getByRole("list",{name:"Treemap groups"})).getByRole("button",{name:/<b>literal/}));expect(selected).toBe("<b>literal</b>");fireEvent.keyDown(within(plot).getByRole("button",{name:/No value/}),{key:" "});expect(selected).toBe("<b>literal</b>");view.rerender(<CountTreemap terms={terms} label="Assets" enabled={false} onSelect={select}/>);fireEvent.click(within(plot).getByRole("button",{name:/constructor/}));expect(selected).toBe("<b>literal</b>");view.rerender(<CountTreemap terms={[]} label="Assets" onSelect={select}/>);fireEvent.click(screen.getByRole("button",{name:"Clear group filter"}));expect(selected).toBeUndefined();
});
